const arabic = [
["لا", "No"],
["من", "From"],
["هذا", "This"],
["أن", "that"],
["في", "at"],
["أنا", "I am"],
["على", "On"],
["ما", "What"],
["هل", "Do you"],
["يا", "Oh"],
["و", "And the"],
["لقد", "lhave"],
["ذلك", "that"],
["ماذا", "What"],
["أنت", "You are"],
["هنا", "Here"],
["لم", "did not"],
["إلى", "to me"],
["نعم", "Yeah"],
["كان", "It was"],
["هو", "he is"],
["ان", "that"],
["هذه", "this is"],
["هناك", "over there"],
["عن", "About"],
["فى", "at"],
["كل", "Each"],
["ليس", "Not"],
["فقط", "Just"],
["كنت", "I was"],
["الآن", "right Now"],
["يجب", "Must"],
["انا", "I am"],
["لك", "is yours"],
["مع", "With"],
["شيء", "Thing"],
["لكن", "But"],
["لن", "will not"],
["الذي", "Which"],
["حسنا", "Okay"],
["كيف", "How"],
["سوف", "Will"],
["هيا", "Come on"],
["نحن", "we"],
["إنه", "it's a"],
["ـ", ""],
["أجل", "Yes"],
["لماذا", "Why"],
["إذا", "if"],
["عندما", "When"],
["انه", "it's a"],
["كذلك", "As well"],
["لي", "Mine"],
["الى", "to me"],
["بعد", "distance"],
["انت", "You are"],
["هي", "she"],
["أين", "Where"],
["أنه", "it's a"],
["كانت", "she was"],
["حتى", "Even"],
["أي", "Which"],
["إنها", "It"],
["أعرف", "I know"],
["قد", "may be"],
["قبل", "Before"],
["تلك", "That"],
["الأمر", "It"],
["بعض", "Some"],
["أو", "or"],
["مثل", "Like"],
["أريد", "I want"],
["رجل", "a leg"],
["لو", "If"],
["أعتقد", "Think"],
["ربما", "Maybe"],
["أيها", "O"],
["بخير", "Fine"],
["يكون", "is being"],
["عليك", "on you"],
["جيد", "good"],
["أنك", "You"],
["شخص", "Person"],
["إن", "that"],
["التي", "Which"],
["ولكن", "But"],
["أليس", "Alice"],
["علي", "Ali"],
["أحد", "One"],
["به", "with it"],
["الوقت", "Time"],
["يمكن", "Could"],
["انها", "It"],
["اليوم", "Today"],
["شئ", "a thing"],
["تعرف", "Recognize"],
["تريد", "You want"],
["صحيح", "Right"],
["أكثر", "More"],
["تكون", "Be"],
["لست", "I'm not"],
["كما", "as such"],
["أستطيع", "I can"],
["منذ", "Ago"],
["جدا", "very"],
["سيدي", "sir"],
["يمكنك", "you may"],
["لذا", "So"],
["واحد", "One"],
["لديك", "You have"],
["يبدو", "sound"],
["أوه", "Oh"],
["كلا", "Both"],
["الرجل", "the man"],
["لدي", "I have"],
["تفعل", "are doing"],
["غير", "Non"],
["عليه", "on him"],
["اذا", "if"],
["آخر", "else"],
["حدث", "Event"],
["مرة", "Once"],
["شكرا", "Thank you"],
["لدينا", "we've got"],
["الناس", "People"],
["يوجد", "exist"],
["له", "for him"],
["مكان", "Place"],
["سيد", "Mr"],
["سيكون", "Will be"],
["أعلم", "I know"],
["رائع", "Gorgeous"],
["مرحبا", "Hi"],
["آسف", "Sorry"],
["بهذا", "by this"],
["وقت", "time"],
["اللعنة", "Curse"],
["كم", "How many"],
["ليست", "Not"],
["أفضل", "Best"],
["بها", "By"],
["معك", "With you"],
["أنها", "It"],
["الذى", "Which"],
["الكثير", "Lots"],
["قلت", "I said"],
["بك", "Your"],
["يحدث", "Happen or occur"],
["الان", "right Now"],
["يكن", "Not"],
["يوم", "day"],
["وأنا", "I"],
["واحدة", "one"],
["بي", "My"],
["أخرى", "Others"],
["ولا", "Nor"],
["علينا", "We"],
["أبي", "My Father"],
["بأن", "That"],
["ثم", "Then"],
["تعال", "Come"],
["هكذا", "So"],
["يمكنني", "I can"],
["هم", "they"],
["ألا", "Except"],
["بالطبع", "Of course"],
["أنني", "I"],
["المكان", "the place"],
["بذلك", "So"],
["معي", "With me"],
["لهذا", "For this"],
["ها", "Ha"],
["شىء", "Thing"],
["انك", "You"],
["إلهي", "divine"],
["تستطيع", "Could you"],
["العمل", "the work"],
["العالم", "the world"],
["الحقيقة", "Truth"],
["الليلة", "Tonight"],
["بالتأكيد", "Certainly"],
["حقا", "Oh really"],
["تعلم", "Learn"],
["أمي", "Illiterate"],
["الطريق", "The Road"],
["حال", "If"],
["لى", "Mine"],
["لها", "to her"],
["الأن", "right Now"],
["هؤلاء", "these"],
["فعل", "Act"],
["توقف", "Stop"],
["عمل", "Action"],
["حول", "Around"],
["لنا", "Our"],
["خلال", "Through"],
["اعتقد", "Think"],
["السيد", "the master"],
["انظر", "Look"],
["منك", "From you"],
["أى", "Which"],
["أفعل", "I do"],
["فعلت", "I did"],
["لأن", "Because"],
["إذن", "So"],
["قال", "He said"],
["الجميع", "everybody"],
["تم", "The"],
["الجحيم", "hell"],
["هى", "she"],
["فيه", "in it"],
["جيدة", "Good"],
["عنه", "about him"],
["بشكل", "In"],
["بما", "Including"],
["تقول", "Says"],
["لديه", "he have"],
["ثانية", "a second"],
["لذلك", "So"],
["أكون", "I be"],
["دعنا", "Let's"],
["ايها", "Dear"],
["المال", "the money"],
["يمكننا", "We can"],
["الذهاب", "going"],
["متى", "when"],
["تعتقد", "U think"],
["اريد", "I want"],
["عليها", "on her"],
["أذهب", "Go"],
["ستكون", "it will be"],
["فضلك", "Please"],
["بدون", "without"],
["أرجوك", "I beg you"],
["التى", "Which"],
["شيئا", "Something"],
["نذهب", "We go"],
["لكي", "in order to"],
["نفسك", "yourself"],
["بنا", "coffee beans"],
["اين", "Where"],
["وأنت", "And you"],
["لكم", "to you"],
["اي", "Which"],
["بين", "between"],
["إنهم", "that they"],
["أرى", "I see"],
["المنزل", "Home"],
["بحق", "Rightly"],
["كنا", "We were"],
["عند", "At"],
["أم", "Mother"],
["منه", "from him"],
["نفس", "The same"],
["اذهب", "Go"],
["حيث", "Where"],
["مجرد", "Just"],
["أقول", "I say"],
["تبدو", "Look"],
["الحياة", "Life"],
["أيضا", "Also"],
["تحت", "Under"],
["الأشياء", "The things"],
["معه", "With him"],
["يريد", "Wants"],
["أننا", "We"],
["أنظر", "Look"],
["لما", "when"],
["اعرف", "I know"],
["إلي", "to me"],
["ثلاثة", "three"],
["انتظر", "wait"],
["الرجال", "Men"],
["الذين", "Whose"],
["حصلت", "I got"],
["أني", "I"],
["سعيد", "Happy"],
["لابد", "Must"],
["عزيزتي", "Darling"],
["الشيء", "Thing"],
["فكرة", "idea"],
["انهم", "that they"],
["الله", "Allah"],
["الباب", "The Door"],
["سيدى", "sir"],
["دائما", "Always"],
["رأيت", "I have seen"],
["مشكلة", "Problem"],
["استطيع", "I can"],
["com", "com"],
["تكن", "Not"],
["تذهب", "Go"],
["ليلة", "a night"],
["شيئ", "Thing"],
["أظن", "I suspect"],
["طوال", "throughout"],
["جميل", "Nice"],
["وهو", "and he"],
["الشرطة", "the police"],
["او", "or"],
["دولار", "Dollar"],
["السيارة", "The Car"],
["وهذا", "and this is"],
["كبير", "Large"],
["مني", "Mona"],
["بسرعة", "Quickly"],
["النار", "fire"],
["الأمور", "Things"],
["سمعت", "I heard"],
["أشعر", "I feel"],
["يعرف", "Known"],
["a", "a"],
["أعني", "I mean"],
["لدى", "I have"],
["بهذه", "In this"],
["أحب", "I love"],
["سنوات", "Years"],
["بأس", "Okay"],
["الأفضل", "Best"],
["بالنسبة", "about"],
["أنتم", "you"],
["عظيم", "Great"],
["يقول", "Says"],
["جميلة", "Beautiful"],
["جون", "John"],
["جاك", "Jack"],
["بسبب", "Because"],
["الوحيد", "the only"],
["أمر", "Command"],
["بل", "but"],
["بالفعل", "Indeed"],
["الشخص", "the person"],
["الي", "to me"],
["دعني", "Let me"],
["خارج", "Outside"],
["اجل", "Yes"],
["الخير", "The good"],
["ــ", ""],
["حالك", "Are you"],
["للغاية", "Extremely"],
["فحسب", "Solely"],
["كانوا", "they were"],
["أردت", "I wanted"],
["فتاة", "Girl"],
["بشأن", "about"],
["يعني", "Means"],
["كبيرة", "big"],
["ترى", "See"],
["آسفة", "Sorry"],
["دقيقة", "Accurate"],
["أنهم", "that they"],
["يستطيع", "Can"],
["احد", "One"],
["بأنك", "You"],
["تعمل", "Working"],
["تريدين", "Want"],
["فيها", "In which"],
["اليس", "Wallis"],
["رائعة", "Fantastic"],
["رجال", "Men"],
["نوع", "Type"],
["حياتي", "my life"],
["الأرض", "Earth"],
["البيت", "House"],
["قتل", "killing"],
["اوه", "Oh"],
["والآن", "Now"],
["مات", "Die"],
["بكل", "All"],
["تعرفين", "You know"],
["أحتاج", "I need"],
["نستطيع", "We can"],
["جديد", "new"],
["صباح", "morning"],
["ألم", "Pain"],
["عيد", "Feast"],
["منها", "Of which"],
["يعمل", "Works"],
["الموت", "the death"],
["إليك", "Here"],
["جميع", "all"],
["لأنه", "Because he"],
["لحظة", "Moment"],
["لكني", "But I"],
["الامر", "It"],
["عشر", "ten"],
["لكنه", "But he"],
["بحاجة", "In need"],
["بأنه", "That"],
["أتمنى", "I wish"],
["إليه", "mechanism"],
["عنك", "About you"],
["الفتاة", "the girl"],
["لهم", "for them"],
["بالضبط", "exactly"],
["سأكون", "I will be"],
["اعلم", "I know"],
["اللعين", "Dreaded"],
["رقم", "number"],
["طريق", "Way"],
["منهم", "who are they"],
["المدينة", "City"],
["الحب", "the love"],
["لنذهب", "Let's go"],
["خذ", "take"],
["أكن", "I"],
["فوق", "above"],
["عزيزي", "my dear"],
["دون", "Without"],
["الـ", "The"],
["صغيرة", "Small"],
["الرئيس", "President"],
["تتحدث", "Talk"],
["ترجمة", "Translation"],
["صديقي", "My friend"],
["فقد", "Lost"],
["الصغير", "Little"],
["ولم", "It did not"],
["ساعة", "hour"],
["يفعل", "Do"],
["غرفة", "room"],
["وماذا", "and what"],
["المرة", "Time"],
["قام", "The"],
["إلا", "Except"],
["عام", "Public"],
["هذة", "this is"],
["متأكد", "Certain"],
["دقائق", "minutes"],
["سيارة", "Car"],
["فعله", "Do"],
["سعيدة", "happy"],
["مما", "Than"],
["ومن", "And from"],
["معنا", "With us"],
["سبب", "reason"],
["سأذهب", "I will go"],
["الطريقة", "Way"],
["الأطفال", "children"],
["سنة", "Year"],
["بينما", "While"],
["يرام", "Okay"],
["السبب", "Reason"],
["أننى", "I am"],
["أول", "first"],
["اى", "Which"],
["أريدك", "I want you"],
["قمت", "You"],
["الأولى", "First"],
["المدرسة", "The school"],
["ذهبت", "you went"],
["لطيف", "Nice"],
["نفسي", "Myself"],
["الا", "Except"],
["الجنس", "Gender"],
["أية", "Verse"],
["أقصد", "I mean"],
["غريب", "a stranger"],
["نفعل", "Do"],
["الصباح", "the morning"],
["حالة", "status"],
["المزيد", "More"],
["أبدا", "Start"],
["مهما", "Whatever"],
["اسمع", "Listen"],
["لأنك", "because you are"],
["أحاول", "I'm trying"],
["وقد", "The"],
["ايضا", "Also"],
["أحبك", "I love you"],
["اكثر", "More"],
["فرصة", "Chance"],
["رأيك", "Your opinion"],
["افعل", "I do"],
["الحصول", "Get"],
["صغير", "Small"],
["الماء", "water"],
["جيدا", "Well"],
["التحدث", "Talk"],
["يمكننى", "I can"],
["الساعة", "the clock"],
["طريقة", "method"],
["أيتها", "O"],
["كثيرا", "Much"],
["سيدة", "Lady"],
["خمسة", "five"],
["وجدت", "Found"],
["قليلا", "Slightly"],
["وانا", "I"],
["اخرى", "Other"],
["الليل", "Night"],
["تعني", "Means"],
["تماما", "Completely"],
["نهاية", "End"],
["عرفت", "I knew"],
["اني", "I"],
["أفكر", "think"],
["معها", "with her"],
["الأول", "the first"],
["لكنك", "but you are"],
["تعالي", "come"],
["البعض", "Some"],
["أفهم", "I understand"],
["أخبرك", "I tell you"],
["حياة", "Life"],
["أتعرف", "You know"],
["نفسه", "Himself"],
["الواقع", "Indeed"],
["أيام", "days"],
["انني", "I"],
["تأتي", "Come"],
["لديهم", "They have"],
["فهمت", "I understand"],
["لـ", "To"],
["لديها", "she has"],
["الحرب", "the war"],
["الأقل", "the least"],
["أخبرني", "tell me"],
["إنك", "You"],
["بـ", "With"],
["الصغيرة", "Small"],
["تحتاج", "need"],
["بدأت", "Began"],
["حياتك", "Your Life"],
["عني", "About Me"],
["إذهب", "Go"],
["عندي", "I have"],
["تقلق", "Worry"],
["نحتاج", "We need"],
["إنتظر", "wait"],
["أصبح", "has become"],
["مجنون", "crazy"],
["يكفي", "Enough"],
["اننا", "We"],
["خطأ", "Error"],
["الطفل", "Child"],
["نصف", "Half"],
["أكبر", "Larger"],
["الخاص", "The private"],
["عليهم", "on them"],
["نريد", "We want"],
["لأنني", "because I"],
["حان", "It's"],
["تعلمين", "You know"],
["نعرف", "We know"],
["هنالك", "there"],
["رفاق", "friends"],
["لكنني", "But I"],
["معى", "With me"],
["دكتور", "Doctor"],
["جديدة", "New"],
["هلا", "Hi"],
["افضل", "Best"],
["طفل", "Child"],
["عنها", "about her"],
["أتعلم", "you know what"],
["تقوم", "get up"],
["أعمل", "Make"],
["بد", "Must"],
["الهاتف", "the phone"],
["بالخارج", "Outside"],
["السيدة", "Ms"],
["الطعام", "the food"],
["ثلاث", "three"],
["أقوم", "I"],
["صديق", "Friend"],
["أتحدث", "I speak"],
["فرانك", "Frank"],
["الجديد", "the new"],
["مالذي", "What you"],
["للتو", "just yet"],
["سيدتي", "Madam"],
["طويلة", "long"],
["وما", "gesticulate"],
["السجن", "the prison"],
["أشياء", "Things"],
["فأنا", "I"],
["أخبرتك", "I told you"],
["العديد", "Many"],
["أعطني", "Give me"],
["أراك", "See you"],
["أخي", "My brother"],
["سام", "Poisonous"],
["قالت", "She said"],
["فريق", "Team"],
["فيما", "The"],
["جو", "Atmosphere"],
["يتم", "Complete"],
["نكون", "We"],
["وليس", "Not"],
["يذهب", "he goes"],
["ممكن", "Maybe"],
["لمدة", "For"],
["حق", "right"],
["اسف", "Sorry"],
["يجري", "Being"],
["تفعله", "You do"],
["مثلك", "same to you"],
["وبعد", "After"],
["تشعر", "feel"],
["تحب", "Love"],
["اخر", "else"],
["رؤية", "Vision"],
["طويل", "Long"],
["والدك", "Father"],
["ذهب", "Go"],
["آه", "Uh"],
["أقل", "Less"],
["حصل", "happened"],
["لكى", "in order to"],
["اللعنه", "Curse"],
["سأفعل", "I'll do"],
["يعلم", "Know"],
["كله", "Entire"],
["القيام", "The performance"],
["فتى", "boy"],
["الممكن", "Possible"],
["أخرج", "Get out"],
["النوم", "Sleeping"],
["داخل", "inside"],
["جورج", "George"],
["رجاء", "Please"],
["أصبحت", "I became"],
["الخاصة", "Private"],
["اذن", "So"],
["ذات", "Related"],
["جميعا", "All"],
["منا", "from U.S"],
["الموضوع", "Subject"],
["الفتى", "Boy"],
["اللقاء", "Meeting"],
["أخر", "else"],
["كي", "So that"],
["كلمة", "a word"],
["عبر", "Across"],
["أود", "I would like"],
["بيت", "a house"],
["تفهم", "Understand"],
["تفعلين", "Doin"],
["علاقة", "Relationship"],
["بى", "Pei"],
["نيويورك", "New York"],
["الآخر", "The other"],
["بلا", "without"],
["مايكل", "Michael"],
["نظرة", "a look"],
["ونحن", "We"],
["الخارج", "the outside"],
["تحاول", "Trying to"],
["المشكلة", "the problem"],
["بواسطة", "by"],
["كن", "Be"],
["المفترض", "Supposed"],
["قل", "Say"],
["يارجل", "Hey man"],
["تظن", "You think"],
["يقوم", "get up"],
["مليون", "Million"],
["أخذ", "Taking"],
["توم", "Tom"],
["يمكنه", "Can"],
["مباشرة", "directly"],
["سيئة", "Bad"],
["الحال", "adverb"],
["العودة", "Go Back"],
["حاول", "try to"],
["عندك", "you have"],
["تكوني", "Tkona"],
["ميت", "dead"],
["hotmail", "hotmail"],
["الكبير", "Great"],
["الفتيات", "the girls"],
["النساء", "Women"],
["رئيس", "President"],
["أسرع", "Faster"],
["النهاية", "The end"],
["قادم", "coming"],
["أحضر", "Bring"],
["جزء", "part"],
["الهي", "divine"],
["ذاهب", "Going"],
["العام", "General"],
["لكنها", "but she"],
["أتريد", "you want to"],
["بخصوص", "Concerning"],
["الوغد", "villain"],
["حقيقي", "real"],
["إنني", "I"],
["البقاء", "Stay"],
["حبيبتي", "My love"],
["بهم", "Their"],
["المساعدة", "Help"],
["تصبح", "Become"],
["عشرة", "ten"],
["أحدهم", "One of them"],
["الخروج", "Exit"],
["قصة", "a story"],
["مستحيل", "No way"],
["أربعة", "four"],
["وهي", "Which"],
["أبى", "My Father"],
["كلها", "all of which"],
["ضد", "against"],
["حاولت", "I tried"],
["القادمة", "Coming"],
["يأتي", "Come"],
["تفضل", "please enter"],
["أسمع", "Listen"],
["تمت", "Has"],
["توجد", "There"],
["لكل", "for every"],
["العشاء", "the Dinner"],
["الغرفة", "the room"],
["وانت", "And you"],
["وسوف", "will"],
["خمس", "five"],
["تذكر", "remember"],
["أصدق", "believe"],
["ألف", "a thousand"],
["بنفسك", "by yourself"],
["شباب", "Youth"],
["الماضي", "the past"],
["دعونا", "We Invited"],
["الأسبوع", "the week"],
["نتحدث", "we are talking"],
["نسيت", "Forgot"],
["بأنني", "I"],
["منزل", "a house"],
["وضع", "put"],
["ولد", "Boy"],
["أنتي", "you"],
["جاهز", "Ready"],
["رسالة", "Message"],
["دي", "De"],
["ابن", "Son"],
["اكون", "I be"],
["حقيقة", "Fact"],
["مايك", "Mike"],
["حين", "when"],
["عائلة", "a family"],
["أدري", "Know"],
["وكان", "The"],
["القائد", "Leader"],
["للمنزل", "Home"],
["مساعدتك", "Help"],
["غدا", "Tomorrow"],
["ظننت", "I thought"],
["ولن", "Will not"],
["المرأة", "woman"],
["لهذه", "These"],
["تحرك", "Move"],
["يهم", "Matters"],
["تبقى", "Stay"],
["الطبيب", "the doctor"],
["اسم", "Noun"],
["انظري", "Look"],
["تبا", "Damn"],
["أتذكر", "I remember"],
["فترة", "interval"],
["ساعات", "Hours"],
["تفكر", "Contemplate"],
["تحصل", "Obtain"],
["بأي", "Any"],
["النقود", "Money"],
["لعبة", "Game"],
["زوجتي", "my wife"],
["الكلام", "talk"],
["ستفعل", "you will do"],
["أسف", "Sorry"],
["فهو", "It"],
["الملك", "King"],
["مدينة", "City"],
["بكم", "Welcome"],
["الوحيدة", "The only"],
["أمام", "Before"],
["عدد", "Number"],
["اخرج", "Get out"],
["بول", "Urine"],
["سأعود", "I'll come back"],
["جئت", "I came"],
["لأني", "because I am"],
["تحدث", "Talk"],
["السلامة", "safety"],
["الماضية", "Last"],
["أمك", "Your mother"],
["اعتقدت", "I thought"],
["مره", "Once"],
["مساء", "evening"],
["بطريقة", "in a way"],
["الرب", "God"],
["ابدا", "Start"],
["أهذا", "Is that"],
["وفي", "In"],
["وكل", "All"],
["أتيت", "Comes"],
["منكم", "You"],
["انتهى", "is over"],
["بوب", "Bob"],
["بعيدا", "Away"],
["ضع", "Put"],
["وجود", "Existence"],
["تعود", "Return"],
["زلت", "I still"],
["اللعينة", "Damned"],
["نقوم", "We"],
["كلنا", "all of us"],
["أحصل", "Get"],
["يريدون", "They want"],
["تأخذ", "Take"],
["المحتمل", "Likely"],
["الشمس", "the sun"],
["بدأ", "seem"],
["www", "www"],
["ارجوك", "I beg you"],
["المسيح", "The messiah"],
["جاء", "came"],
["كهذا", "Such a"],
["سنذهب", "We'll go"],
["تعالى", "come"],
["إثنان", "two"],
["فعلا", "Really"],
["حتي", "Even"],
["سيحدث", "Will happen"],
["الجيد", "Good"],
["وشك", "About"],
["القادم", "Next"],
["معرفة", "knowledge"],
["صورة", "picture"],
["أعود", "I come back"],
["اسمي", "My name"],
["طلب", "Request"],
["آنسة", "miss"],
["الثانية", "the second"],
["فقدت", "Lost"],
["حفلة", "party"],
["تنظر", "Consider"],
["مثير", "Thrilling"],
["اننى", "I"],
["وصلت", "Arrived"],
["أنتظر", "wait"],
["السماء", "The sky"],
["يقولون", "They say"],
["الهراء", "Fudge"],
["معهم", "With them"],
["ابي", "My Father"],
["وعندما", "When"],
["مجموعة", "Collection"],
["العاهرة", "Bitch"],
["ماري", "Marie"],
["حسن", "Hassan"],
["الزواج", "marriage"],
["نحو", "Toward"],
["دعيني", "Let me"],
["الجديدة", "New"],
["مهم", "Important"],
["أمس", "yesterday"],
["اتصل", "call"],
["ابتعد", "step away"],
["هراء", "Bullshit"],
["ستة", "six"],
["الأخرى", "Other"],
["يحصل", "Gets"],
["ولكني", "But I"],
["الطائرة", "The Plane"],
["أصدقاء", "friends"],
["الحظ", "Luck"],
["مشاكل", "Problems"],
["الترجمة", "Translation"],
["تبدين", "Loveable"],
["لسنا", "We are not"],
["مستعد", "ready"],
["ولكنه", "But he"],
["اقول", "I say"],
["أولئك", "Those"],
["النوع", "Type"],
["أثناء", "during"],
["اسمه", "its name"],
["اسمك", "Your Name"],
["مكتب", "Office"],
["والدي", "My father"],
["ينبغي", "Should"],
["منى", "Mona"],
["كرة", "a ball"],
["بيتر", "Peter"],
["عدم", "Non"],
["أطفال", "Children"],
["الإطلاق", "All"],
["سوى", "but"],
["مضحك", "Funny"],
["الوضع", "The situation"],
["جي", "G"],
["الأخيرة", "Last"],
["صعب", "Difficult"],
["أحمق", "Foolish"],
["يحاول", "Try"],
["الشئ", "Thing"],
["حينما", "When"],
["الأشخاص", "Persons"],
["البحر", "the sea"],
["إليها", "to her"],
["عرض", "Show"],
["بأني", "I"],
["يحتاج", "Need"],
["سيء", "Bad"],
["عالم", "Scientist"],
["كثير", "a lot"],
["الداخل", "Inside"],
["الكتاب", "the book"],
["ذو", "A"],
["الأيام", "the days"],
["خلف", "behind"],
["بعضنا", "Some of us"],
["يعود", "Returns"],
["ام", "Mother"],
["اللعبة", "the game"],
["إني", "I"],
["رأسك", "Your head"],
["شركة", "a company"],
["زال", "Still"],
["بشيء", "Something"],
["الاشياء", "The things"],
["قطعة", "Piece"],
["خائف", "horrified"],
["واضح", "Clear"],
["أمى", "Illiterate"],
["موجود", "Existing"],
["علم", "Science"],
["يعد", "Prepare"],
["أبحث", "Search"],
["الدخول", "Access"],
["جين", "Gene"],
["امرأة", "a woman"],
["متأكدة", "Sure"],
["هيه", "Hey"],
["تخبرني", "Tell me"],
["مدى", "Bezel"],
["إلهى", "divine"],
["احب", "I love"],
["عما", "What"],
["نرى", "We see"],
["بيننا", "Between us"],
["تعيش", "Live"],
["قتلت", "Killed"],
["الأحمق", "the fool"],
["تشارلي", "Charlie"],
["بيل", "Bill"],
["عليكم", "on you"],
["سؤال", "A question"],
["طلبت", "Requested"],
["الهواء", "Air"],
["وهذه", "And this"],
["صوت", "Voice"],
["انتم", "you"],
["ميلاد", "birth"],
["ماكس", "Max"],
["تعتقدين", "Think"],
["الحديث", "the talk"],
["الجانب", "the side"],
["صديقك", "Friend"],
["ذا", "The"],
["خطر", "Danger"],
["the", "the"],
["l", "l"],
["أطلق", "Release"],
["الشارع", "Street"],
["عملية", "Operation"],
["ببعض", "Some"],
["تتكلم", "she speaks"],
["مختلف", "Different"],
["تحمل", "Bearing"],
["مساعدة", "Help"],
["t", "t"],
["بضعة", "a few"],
["المناسب", "the appropriate"],
["المنطقة", "Region"],
["قم", "Download"],
["بالداخل", "Inside"],
["البداية", "the beginning"],
["لأجل", "For"],
["زوجتك", "Your wife"],
["مقابل", "Opposite"],
["يحب", "Likes"],
["هاري", "Harry"],
["ممتاز", "Excellent"],
["قريبا", "soon"],
["سنكون", "We will be"],
["فعلته", "I did"],
["بتلك", "Those"],
["التفكير", "Thinking"],
["أسفل", "Down"],
["للعمل", "for work"],
["العجوز", "The old"],
["امي", "Illiterate"],
["الكلب", "dog"],
["انتظري", "Wait"],
["مازال", "Still"],
["إننا", "We"],
["اشعر", "I feel"],
["الجيش", "Army"],
["شرطة", "police"],
["القليل", "Little"],
["السؤال", "the question"],
["تخرج", "Graduation"],
["ب", "B"],
["i", "i"],
["بعمل", "Work"],
["المشاكل", "Problems"],
["معا", "together"],
["يعيش", "Live"],
["الحقيقي", "Real"],
["الولد", "the boy"],
["عدة", "several"],
["قول", "say"],
["العائلة", "the family"],
["موعد", "an appointment"],
["يتحدث", "Speaking"],
["العرض", "Display"],
["الآخرين", "Others"],
["كابتن", "Captain"],
["الثاني", "The second"],
["تقصد", "You mean"],
["أخذت", "I took"],
["نخرج", "We go out"],
["الكرة", "the ball"],
["منتصف", "Mid"],
["مفهوم", "Concept"],
["عد", "Count"],
["أعد", "Prepared"],
["you", "you"],
["هـذا", "This"],
["د", "Dr"],
["يصبح", "Become"],
["أقسم", "I swear"],
["بني", "brouwn"],
["الكبيرة", "Large"],
["للبيت", "House"],
["واحده", "one"],
["الصعب", "Difficult"],
["أولا", "Firstly"],
["أشهر", "Months"],
["إبن", "Son"],
["بالأمر", "Order"],
["ميل", "Tendency"],
["فكرت", "I thought"],
["شهر", "Month"],
["راي", "Opinion"],
["يموت", "Dies"],
["رأيته", "I saw him"],
["أسوأ", "worst"],
["البلدة", "the town"],
["تركت", "I left"],
["الوصول", "Access"],
["جيمس", "James"],
["بأنها", "As"],
["القديمة", "Old"],
["أطلب", "I request"],
["بعيد", "far"],
["الفريق", "the team"],
["أنى", "Anne"],
["وأن", "and surely"],
["الخطأ", "The error"],
["أنتى", "you"],
["ترك", "leave"],
["قليل", "Little"],
["بنفسي", "by myself"],
["لويس", "Louis"],
["فأنت", "You"],
["السادة", "Gentlemen"],
["بشدة", "Deeply"],
["توقفي", "Stop"],
["تقريبا", "Almost"],
["لكننا", "But"],
["فلا", "Not"],
["جيمي", "Jimmy"],
["إمرأة", "a woman"],
["السنة", "the year"],
["حوالي", "around"],
["مركز", "center"],
["قيد", "Entry"],
["اثنان", "two"],
["عندها", "Then"],
["بعدها", "Then"],
["خاصة", "Especially"],
["سي", "CNN"],
["تستطيعين", "you can"],
["لأي", "for any"],
["انة", "it's a"],
["أكره", "I hate"],
["صاح", "Hoot"],
["القيادة", "Leadership"],
["وكيف", "How"],
["مازلت", "I still"],
["بوبي", "Bobby"],
["أجلك", "You"],
["غبي", "Stupid"],
["قوة", "Energy"],
["وهم", "Illusion"],
["أشكرك", "Thank you"],
["المستشفى", "the hospital"],
["الفيلم", "the movie"],
["بماذا", "With what"],
["اللحظة", "the moment"],
["ارى", "I see"],
["بن", "The son of"],
["الموسيقى", "Music"],
["مكانك", "Your place"],
["ال", "The"],
["فإن", "The"],
["رحلة", "Trip"],
["مرات", "Times"],
["ماتت", "she died"],
["دعينا", "Let's"],
["أهتم", "I care"],
["الفرصة", "the opportunity"],
["وراء", "behind"],
["ولكنك", "But you"],
["القانون", "Law"],
["أجد", "I find"],
["كامل", "Whole"],
["تموت", "you die"],
["بلى", "Yes"],
["كثيرة", "a lot"],
["عدت", "I returned"],
["حقيقية", "Real"],
["يعتقد", "Believes"],
["التالي", "next one"],
["طبيب", "A doctor"],
["لطيفة", "Latifa"],
["لاحقا", "Later"],
["الصور", "Pictures"],
["لعين", "Accursed"],
["الجزء", "Section"],
["يدك", "Your hand"],
["النظر", "look"],
["أمريكا", "USA"],
["يديك", "Your hands"],
["سيئ", "Bad"],
["أما", "As for"],
["عزيزتى", "Darling"],
["لوس", "Los"],
["نيك", "Nick"],
["تجد", "You find"],
["سنفعل", "We will do"],
["دعنى", "Let me"],
["عملك", "Your Business"],
["بالإمكان", "Can"],
["القوة", "Power"],
["وإلا", "Otherwise"],
["القصة", "the story"],
["يكونوا", "They"],
["الهدف", "Target"],
["النجدة", "Help"],
["تتحرك", "Moving"],
["القطار", "the train"],
["المعذرة", "Excuse me"],
["أهلا", "Welcome"],
["كلب", "dog"],
["قدم", "Foot"],
["ذاك", "that"],
["اتفقنا", "We agreed"],
["بأننا", "We"],
["ديفيد", "David"],
["اليك", "Here"],
["تبدأ", "start"],
["المعلومات", "the information"],
["بالكامل", "Fully"],
["وإذا", "If"],
["وجه", "Face"],
["ا", "a"],
["الصورة", "Image"],
["الكل", "All"],
["القضية", "the case"],
["ل", "to"],
["ساعدني", "help me"],
["تبحث", "Looking"],
["فيلم", "Movie"],
["بجانب", "Next to"],
["حاجة", "need"],
["قاتل", "killer"],
["أنظري", "Look"],
["معذرة", "Sorry"],
["عاد", "is back"],
["سارة", "Sarah"],
["بكثير", "Much"],
["حبيبي", "Darling"],
["المخدرات", "Drugs"],
["البشر", "Humans"],
["لكنى", "But I"],
["قلبي", "My heart"],
["الرقص", "Dancing"],
["اهلا", "Welcome"],
["الخلف", "Back"],
["أترى", "Do you see"],
["سبعة", "Seven"],
["طالما", "as long"],
["أخبر", "Tell"],
["لفترة", "For a period of"],
["الدكتور", "Dr"],
["السفينة", "the ship"],
["نجد", "We find"],
["سأقوم", "I will"],
["هنري", "Henry"],
["عدا", "Except"],
["هاي", "Hi"],
["جهاز", "Device"],
["شعرت", "I felt"],
["محق", "Right"],
["فلن", "You will not"],
["yahoo", "yahoo"],
["خاص", "Special"],
["إنتهى", "is over"],
["أعلى", "Top"],
["للأبد", "Forever"],
["الجميلة", "the beautiful"],
["القهوة", "Coffee"],
["ملك", "king"],
["انتي", "you"],
["رؤيتك", "seeing you"],
["الصحيح", "the correct"],
["الكفاية", "Enough"],
["الملابس", "Clothing"],
["قسم", "Department"],
["قلته", "I said"],
["نبدأ", "We start"],
["البحث", "search"],
["اللعب", "Play"],
["تقل", "Less"],
["نفسها", "itself"],
["اليه", "mechanism"],
["إعتقدت", "I thought"],
["تمزح", "Kidding"],
["بإمكانك", "You"],
["نعود", "Go back"],
["وهل", "Is"],
["المتحدة", "United"],
["منطقة", "Area"],
["الظلام", "the darkness"],
["القتال", "Fighting"],
["تريده", "You want"],
["تحركوا", "They moved"],
["الطابق", "Floor"],
["تفعلي", "You doing"],
["السيطرة", "the control"],
["الولايات", "the states"],
["وجهك", "Your face"],
["أخبار", "News"],
["آمل", "hopefull"],
["خائفة", "Scared"],
["القديم", "the old"],
["قط", "Cat"],
["ولقد", "I have"],
["فعلها", "Do"],
["فكر", "thought"],
["عملي", "my work"],
["أتصل", "call"],
["اجلس", "Sit"],
["انى", "I"],
["لأنها", "Because she"],
["إلينا", "Us"],
["لان", "Because"],
["الثالث", "the third"],
["شي", "Shi"],
["سوية", "Together"],
["درجة", "Degree"],
["مهمة", "Task"],
["الميلاد", "Birth"],
["وضعت", "Developed"],
["لنفسك", "For yourself"],
["تسمع", "You hear"],
["بالله", "God"],
["الحق", "Right"],
["يعنى", "Means"],
["الحمام", "the toilet"],
["الغد", "tomorrow"],
["مختلفة", "Different"],
["ظهر", "Back"],
["مريض", "Patient"],
["خطة", "plan"],
["نعمل", "We"],
["قريب", "Near"],
["حياتى", "my life"],
["الأكثر", "Most"],
["نقطة", "Point"],
["لديكم", "You have"],
["فهذا", "This"],
["كلما", "whenever"],
["مارك", "Mark"],
["أدخل", "Enter"],
["اتمنى", "I wish"],
["الامور", "Things"],
["عملت", "I worked"],
["هاى", "Hi"],
["أفعله", "I do"],
["السيدات", "Ladies"],
["جيم", "C."],
["القتل", "the kill"],
["نظام", "System"],
["مال", "Money"],
["وحسب", "According to"],
["الغير", "Third parties"],
["أعرفه", "I know him"],
["هدية", "Present"],
["حد", "Limit"],
["ماهو", "What is the"],
["معنى", "meaning of"],
["يفترض", "Supposedly"],
["انظروا", "Look"],
["الخط", "Line"],
["السلاح", "Arms"],
["مدرسة", "School"],
["أتى", "came"],
["موافقة", "Assent"],
["فعلتها", "I did"],
["الشاب", "the guy"],
["نحصل", "We get"],
["عندنا", "We have"],
["أولاد", "Children"],
["صاحب", "owner"],
["أذا", "if"],
["تتذكر", "Remember"],
["الضوء", "the light"],
["الدم", "the blood"],
["الأخير", "the last one"],
["الأخبار", "The news"],
["الحفلة", "the party"],
["تقلقي", "Worry"],
["المكتب", "the desk"],
["الأولاد", "Boys"],
["يجعل", "Makes"],
["الواضح", "Obviously"],
["سمحت", "Allowed"],
["الاتصال", "Connection"],
["تود", "Todd"],
["ماهذا", "What is that"],
["الافضل", "Best"],
["كوني", "Cosmic"],
["نعلم", "We know"],
["العظيم", "Great"],
["المهمة", "the mission"],
["الصوت", "the sound"],
["اهدأ", "just chill"],
["لمن", "Whose"],
["أنتما", "you"],
["احتاج", "I need"],
["ينتهي", "finish"],
["باريس", "Paris"],
["الحيوانات", "the animals"],
["أحضرت", "I brought"],
["الشعور", "Feeling"],
["سأتصل", "I'll call"],
["داني", "Danny"],
["المياه", "Water"],
["اردت", "I wanted"],
["ويل", "Woe"],
["أريده", "I want"],
["أعدك", "I promise you"],
["يخرج", "Out"],
["زوجة", "wife"],
["المسدس", "Pistol"],
["بيلي", "Billy"],
["by", "by"],
["تعد", "Prepare"],
["موقع", "Site"],
["ابقى", "Stay"],
["ستيف", "Steve"],
["كتاب", "Book"],
["أبدو", "I look"],
["ملابس", "Clothes"],
["لندن", "London"],
["أعيش", "I live"],
["آي", "Which"],
["الثالثة", "Third"],
["صديقى", "My friend"],
["اسمعي", "Hear"],
["المحكمة", "Court"],
["يأخذ", "Takes"],
["ولكنها", "But"],
["ليسوا", "Not"],
["ستذهب", "you will go"],
["اكن", "I"],
["بنت", "Girl"],
["خير", "Good"],
["لأننا", "Because we"],
["كارل", "Carl"],
["يوما", "One day"],
["صندوق", "Box"],
["ماما", "my mom"],
["لبعض", "For some"],
["عظيمة", "Great"],
["أنكم", "You"],
["يجعلك", "make you"],
["تلعب", "Play"],
["إسمع", "Listen"],
["حياته", "His life"],
["ألن", "Allen"],
["دليل", "Evidence"],
["شرطي", "Policeman"],
["وذلك", "That"],
["تريدني", "You want me"],
["فهم", "Understanding"],
["المستقبل", "the future"],
["الليله", "Tonight"],
["قادمة", "coming"],
["بان", "Ban"],
["الحالة", "Case"],
["عمله", "Currency"],
["بالمناسبة", "Incidentally"],
["أستطع", "I could"],
["ولو", "Albeit"],
["أرغب", "I want"],
["خرجت", "Came out"],
["البلاد", "Country"],
["أعنى", "I mean"],
["الإتصال", "Connection"],
["الرقم", "the number"],
["سأخبرك", "I will tell you"],
["السرير", "the bed"],
["غريبة", "Strange"],
["إطلاق", "release"],
["القمر", "the moon"],
["تي", "T"],
["الغابة", "Jungle"],
["حب", "Love"],
["كلهم", "All of them"],
["تغيير", "A change"],
["جيده", "Good"],
["توقفوا", "Stop"],
["رائحة", "Smell"],
["طعام", "food"],
["ريتشارد", "Richard"],
["اه", "Uh"],
["منزلي", "Household"],
["أتكلم", "I speak"],
["نصل", "blade"],
["أنـا", "I"],
["الشىء", "Thing"],
["النظام", "the system"],
["جريمة", "a crime"],
["معلومات", "informations"],
["افتح", "Open"],
["مجنونة", "crazy"],
["سبق", "Already"],
["متأخر", "Late"],
["ابني", "my son"],
["مثلي", "Like me"],
["جنون", "Insanity"],
["محمد", "Mohammed"],
["لحم", "Meat"],
["تصل", "Reach"],
["قلب", "heart"],
["مؤخرتك", "Your ass"],
["احضر", "Bring"],
["معكم", "With you"],
["الفندق", "the hotel"],
["طيب", "Ok"],
["قطع", "cut"],
["دور", "Role"],
["الدماء", "Blood"],
["تملك", "Ownership"],
["اعطني", "Give me"],
["الشيطان", "evil"],
["قوية", "Powerful"],
["طائرة", "Plane"],
["بسيط", "simple"],
["وسط", "Center"],
["حرب", "war"],
["ثمانية", "eight"],
["بنفس", "The same"],
["استمع", "Listen"],
["الأب", "the father"],
["يعرفون", "Know"],
["جوني", "Johnny"],
["يبقى", "Remains"],
["أبقى", "Kept"],
["أخشى", "I'm afraid"],
["اعني", "I mean"],
["علمت", "I learned"],
["زوجي", "my husband"],
["عنى", "About Me"],
["حسب", "On"],
["صح", "true"],
["الأمن", "Security"],
["سهل", "Easy"],
["الجو", "the weather"],
["يهتم", "Cares about"],
["يدعى", "he claims"],
["وهناك", "There"],
["مـن", "From"],
["السيارات", "the cars"],
["أتعلمين", "Do you know"],
["العيش", "Live"],
["قائمة", "List"],
["واو", "Wow"],
["سيدتى", "Madam"],
["يمكنهم", "They can"],
["يستحق", "Deserve"],
["سلاح", "a weapon"],
["كلام", "talking"],
["كريس", "Chris"],
["اذهبي", "Go"],
["فيك", "in you"],
["الآنسة", "miss"],
["سماع", "Hearing"],
["إنظر", "Look"],
["أربع", "Four"],
["الأعلى", "the above"],
["رأس", "head"],
["ولماذا", "Why"],
["السلام", "Peace"],
["القاتل", "the killer"],
["تهتم", "care"],
["تضع", "Put"],
["المهم", "The important"],
["لكنهم", "But they"],
["موجودة", "Found"],
["أتعرفين", "Do you know"],
["النهر", "the river"],
["خذي", "Take"],
["وصل", "Arrive"],
["مثلما", "as"],
["قائد", "Leader"],
["لله", "Allah"],
["الأسلحة", "Weapons"],
["اخرس", "shut up"],
["ترغب", "Wish"],
["التلفاز", "the television"],
["شون", "Shawn"],
["عاهرة", "whore"],
["تغير", "change"],
["مثيرة", "Exciting"],
["قالوا", "They said"],
["طريقي", "My way"],
["الحقير", "Despicable"],
["وظيفة", "Function"],
["معظم", "Most"],
["القدم", "Football"],
["أختي", "My sister"],
["وصلنا", "We arrived"],
["حصلنا", "We got"],
["يمكنها", "Can"],
["الشركة", "Company"],
["عادة", "Habit"],
["شعور", "Feeling"],
["حينها", "Then"],
["جاهزة", "Ready"],
["زمن", "time"],
["تعالوا", "Come"],
["شراب", "drink"],
["أيمكنك", "Can"],
["إحدى", "one"],
["بعضهم", "Some of them"],
["سان", "San"],
["آن", "that"],
["حالا", "Immediately"],
["ثمن", "price"],
["تسير", "going"],
["بداية", "Start"],
["العثور", "Found"],
["فمك", "your mouth"],
["الشعر", "Poetry"],
["المفتاح", "the key"],
["هنـا", "Here"],
["شخصا", "People"],
["تقوله", "You say"],
["أراه", "I see"],
["فجأة", "Suddenly"],
["جاد", "Serious"],
["شارع", "Street"],
["قضية", "Issue"],
["تدخل", "intervention"],
["شعر", "Poetry"],
["الأبيض", "the White"],
["أرسل", "Send"],
["أسابيع", "Weeks"],
["قوي", "strong"],
["عنده", "Has"],
["زوج", "Husband"],
["أأنت", "Are"],
["انتى", "you"],
["الشباب", "Young"],
["عائلتي", "my family"],
["السرعة", "the speed"],
["أقوله", "I say"],
["مزيد", "More"],
["اريدك", "I want"],
["جيري", "Jerry"],
["فـي", "In"],
["القلب", "the heart"],
["محظوظ", "Lucky"],
["بالرغم", "Although"],
["الخطة", "the plan"],
["خط", "Line"],
["برنامج", "a program"],
["الحكومة", "the government"],
["آلاف", "Thousands"],
["مايرام", "Okay"],
["بيتي", "my house"],
["صديقة", "Girlfriend"],
["كنتم", "You"],
["تأتى", "Come"],
["تنتظر", "Waiting for"],
["ادخل", "Enter"],
["ديف", "Dave"],
["بطل", "a hero"],
["روبرت", "Robert"],
["تتوقف", "Stop"],
["تناول", "Take"],
["جانب", "side"],
["حيال", "About"],
["إعادة", "Return"],
["الكلاب", "Dogs"],
["الشراب", "the drink"],
["يتعلق", "Regard"],
["يصل", "Reach"],
["تحدثت", "she spoke"],
["مشغول", "Busy"],
["خيار", "Option"],
["وكنت", "I"],
["الدفاع", "Defense"],
["افكر", "think"],
["مناسب", "Appropriate"],
["أملك", "I have"],
["لاري", "Lari"],
["تعنى", "Means"],
["الصندوق", "box"],
["م", "M"],
["الكلمات", "the words"],
["احصل", "Get"],
["والتر", "Walter"],
["فتيات", "Girls"],
["بسرعه", "Quickly"],
["تجعل", "Make"],
["تتصل", "Related"],
["والدتك", "your mom"],
["آخذ", "Taking"],
["اخبرك", "I tell you"],
["الم", "Pain"],
["أ", "a"],
["حاضر", "Present"],
["أحسنت", "Well done"],
["تومي", "Tommy"],
["أصدقائي", "my friends"],
["لربما", "Maybe"],
["أغلق", "close"],
["فسوف", "Will"],
["الصف", "Class"],
["المفضل", "Preferred"],
["مضى", "Ago"],
["مرتين", "Twice"],
["احبك", "I love you"],
["الجريمة", "the crime"],
["الخوف", "the fear"],
["واثق", "confident"],
["البارحة", "yesterday"],
["قررت", "I decided"],
["طول", "Length"],
["نحاول", "we try"],
["عندى", "I have"],
["امر", "Command"],
["سخيف", "silly"],
["يدي", "my hand"],
["ماء", "Water"],
["الأبد", "Forever"],
["مـا", "What"],
["كاملة", "perfect"],
["تقدم", "Progress"],
["أسألك", "I ask"],
["زوجته", "His wife"],
["محاولة", "Attempt"],
["يبدوا", "seems"],
["قلق", "Worry"],
["فان", "The"],
["كلانا", "both of us"],
["أتفهم", "I understand"],
["حل", "Solution"],
["التاريخ", "Date"],
["أسبوع", "a week"],
["الطاقة", "energy"],
["آمن", "security"],
["أشخاص", "Persons"],
["الرحلة", "the journey"],
["دفع", "Pay"],
["يرى", "be seen"],
["الكنيسة", "the church"],
["خدمة", "service"],
["فندق", "Hotel"],
["أراد", "want"],
["يفعلون", "They do"],
["الرسالة", "the message"],
["ولكنى", "But I"],
["تقولين", "You say"],
["للذهاب", "To go"],
["القول", "Say"],
["والذي", "Which"],
["آنا", "I am"],
["يظهر", "Appears"],
["النافذة", "the window"],
["قادر", "able"],
["موت", "death"],
["الملازم", "Lt."],
["اتصلت", "I called"],
["أراهن", "I bet"],
["الغبي", "Stupid"],
["للحصول", "to get"],
["ايتها", "Mandate"],
["قف", "Stop"],
["اعمل", "Make"],
["شهور", "Months"],
["توماس", "Thomas"],
["ثمة", "There is"],
["لنرى", "To see"],
["خاطئ", "wrong"],
["الجميل", "Beautiful"],
["اقصد", "I mean"],
["اللحم", "the meat"],
["الأعمال", "Business"],
["اول", "first"],
["انتهت", "Expired"],
["للخارج", "Out"],
["وجدنا", "We found"],
["الشاحنة", "truck"],
["الجنرال", "The general"],
["بالكاد", "barely"],
["رغم", "despite"],
["عمي", "My uncle"],
["مستر", "Mr."],
["تعرفي", "Know"],
["السابق", "the previous"],
["يزال", "Still"],
["إبتعد", "step away"],
["المدير", "Manager"],
["صور", "photo"],
["احاول", "I'm trying"],
["سأقول", "I will say"],
["تشارلز", "Charles"],
["هه", "laugh"],
["نبحث", "Look"],
["اسمها", "Its name"],
["فظيع", "Horrible"],
["بإمكاني", "I"],
["قرأت", "I read"],
["اظن", "I suspect"],
["الفكرة", "The idea"],
["رأسي", "my head"],
["أقدم", "Senior"],
["هاتف", "Phone"],
["يمكنكم", "You can"],
["قديم", "Old"],
["موافق", "OK"],
["الأحمر", "the Red"],
["يومين", "Two days"],
["ببساطة", "Simply"],
["تعرفه", "You know"],
["أه", "Uh"],
["اثنين", "Two"],
["الثلج", "The snow"],
["الحقيبة", "Satchel"],
["بالإضافة", "In addition"],
["استمر", "continue"],
["تسمعني", "Hear me"],
["مهلا", "Hey"],
["العملية", "the operation"],
["يفعله", "Do"],
["ابنتي", "My daughter"],
["أتريدين", "Do you want"],
["أمزح", "Kidding"],
["أجلي", "Me"],
["شك", "Doubt"],
["حلم", "Dream"],
["ألديك", "Do you have"],
["شاب", "young man"],
["طريقه", "method"],
["الضابط", "The officer"],
["أليكس", "Alex"],
["تظهر", "Appear"],
["مذهل", "just awesome"],
["والان", "Now"],
["عزيزى", "my dear"],
["حظ", "luck"],
["ملايين", "Millions"],
["وجهي", "Facial"],
["الطيران", "Aviation"],
["الحقيقه", "Truth"],
["المحقق", "The investigator"],
["أعمال", "Business"],
["لرؤية", "To see"],
["تصدق", "Incredible"],
["دان", "Dan"],
["أنة", "it's a"],
["إيجاد", "finding"],
["أخبرتني", "you told me"],
["سنقوم", "We will"],
["تمانع", "Mind"],
["تدفع", "Pay"],
["اتحدث", "I speak"],
["تتحدثين", "Talking"],
["أترك", "Leave"],
["رأيتها", "her"],
["القبض", "Arrested"],
["تعرفون", "You know"],
["مفاجأة", "Surprise"],
["الأسود", "the black"],
["تنتهي", "Ends"],
["الموقف", "Situation"],
["مدير", "Manager"],
["نفسى", "Myself"],
["الارض", "Earth"],
["التحكم", "control"],
["قليلة", "A few"],
["وعلى", "and on"],
["آسفه", "Sorry"],
["قلبك", "your heart"],
["ضربة", "a hit"],
["دع", "Let"],
["دعه", "Let him"],
["فيكتور", "Victor"],
["بالعمل", "Work"],
["حفل", "Party"],
["الهى", "divine"],
["محطة", "Station"],
["إنتظري", "Wait"],
["تريدون", "You want"],
["أموت", "Die"],
["اخبرني", "tell me"],
["سيارتي", "My car"],
["أوقف", "arrested"],
["العمر", "Age"],
["عينيك", "Your eyes"],
["سرقة", "theft"],
["يبدأ", "Started"],
["التعامل", "Dealing"],
["المحيط", "Ocean"],
["اية", "Verse"],
["أحيانا", "Sometimes"],
["كلير", "Claire"],
["وبعدها", "and then"],
["الحدود", "the border"],
["الكلمة", "Word"],
["الغداء", "the lunch"],
["القاعدة", "Al-Qaeda"],
["تاريخ", "History"],
["بسهولة", "Easily"],
["صفقة", "Deal"],
["فرقة", "Squad"],
["فهي", "They are"],
["وكذلك", "As well as"],
["ولكنني", "But I"],
["الرحيل", "Leave"],
["صنع", "Made"],
["يتكلم", "Speak"],
["يقتل", "Kill"],
["التصوير", "Photography"],
["إبني", "my son"],
["شخصية", "Character"],
["عائلتك", "your family"],
["وربما", "Perhaps"],
["تقتل", "Kill"],
["بارد", "cool"],
["اراك", "See you"],
["المبنى", "Building"],
["أخبره", "Told him"],
["الإنتظار", "Waiting"],
["بيني", "Penny"],
["الوحش", "the monster"],
["جدتي", "My grandmother"],
["سيداتي", "Ladies"],
["قابلت", "she met"],
["مجال", "field"],
["سأحضر", "I will attend"],
["الدرجة", "Degree"],
["ومع", "With"],
["دخلت", "Entered"],
["مسألة", "Issue"],
["قدر", "Saucepan"],
["عقلك", "Your mind"],
["أمل", "Amal"],
["شديد", "Intense"],
["منزلك", "Your home"],
["الشهر", "the month"],
["أخبريني", "Tell me"],
["خطير", "Dangerous"],
["تشارلى", "CHARLIE"],
["كتب", "Wrote"],
["تسعة", "nine"],
["ابحث", "Search"],
["روح", "Soul"],
["الأسئلة", "questions"],
["مـاذا", "What"],
["تشعرين", "Feel"],
["رأيتك", "I saw you"],
["الأمريكية", "American"],
["بقدر", "As far"],
["بطاقة", "Card"],
["عطلة", "Holiday"],
["مدهش", "Amazing"],
["لانه", "Because he"],
["مشاهدة", "Watch"],
["الموافقة", "Approval"],
["وداعا", "Good-bye"],
["الأم", "the mother"],
["حادث", "accident"],
["تأخرت", "Delayed"],
["حياتنا", "Our life"],
["تراجع", "Retreat"],
["قوله", "Saying"],
["ذاهبة", "going"],
["اخذ", "Taking"],
["سكوت", "Silence"],
["تطلب", "Ask"],
["نأخذ", "Take"],
["البيض", "eggs"],
["الاطفال", "children"],
["اصبح", "has become"],
["زالت", "Still"],
["تقولي", "Tell"],
["الأسفل", "lower"],
["ابى", "My Father"],
["يستطيعون", "Can"],
["ياإلهي", "My God"],
["باب", "Door"],
["مر", "Bitter"],
["شكل", "Form"],
["وقعت", "Occurred"],
["الشكل", "the shape"],
["يدخل", "Enters"],
["للنوم", "To sleep"],
["الصيف", "the summer"],
["اقوم", "I do"],
["يد", "hand"],
["زوجك", "your husband"],
["يشعر", "Feel"],
["جاي", "Jay"],
["لشخص", "Someone"],
["تكلم", "speak"],
["سبيل", "Way"],
["قمنا", "We have"],
["لعب", "play"],
["أقوى", "more powerful"],
["اسرع", "Faster"],
["كهذه", "Such"],
["الاسبوع", "the week"],
["سيصبح", "Will become"],
["المفاتيح", "Key"],
["الجزيرة", "The island"],
["to", "to"],
["رأسه", "his head"],
["مستعدة", "ready"],
["كى", "Ki"],
["افهم", "I understand"],
["خرج", "went out"],
["مسرور", "pleased"],
["موضوع", "Theme"],
["حقيقى", "real"],
["أبعد", "far"],
["طبيعي", "natural"],
["ترين", "Train"],
["يكفى", "Enough"],
["التالية", "next"],
["تأكل", "Eat"],
["لأنهم", "because they are"],
["أثق", "I trust"],
["يملك", "Owns"],
["تري", "See"],
["الأحيان", "Often"],
["بمجرد", "Once"],
["تترك", "Leave"],
["فضلكم", "Please"],
["ريد", "Reed"],
["أعتذر", "I apologise"],
["يجدر", "It is worth"],
["سيأتي", "Will come"],
["عشرون", "twenty"],
["القدر", "Destiny"],
["بالقرب", "Near"],
["سقط", "Fall"],
["أرجو", "Please"],
["ابق", "Stay"],
["حي", "Neighborhood"],
["مشكلتك", "Your problem"],
["الرائع", "Wonderful"],
["بقوة", "Strongly"],
["إس", "S"],
["القاضي", "the judge"],
["داعي", "caller to"],
["مدة", "Period"],
["سيتم", "Will be"],
["ماك", "Mac"],
["انتبه", "Whatch out"],
["الموقع", "Site"],
["الحقيقية", "Real"],
["حبيبتى", "My love"],
["تذهبي", "You go"],
["وإن", "and surely"],
["أعرفك", "I know you"],
["دخل", "Enter"],
["السابقة", "Previous"],
["حقيبة", "a bag"],
["كنتي", "Kantian"],
["مائة", "a hundred"],
["للهول", "Hall of"],
];
