let czech = [["to", "it"],
["se", "with"],
["je", "Yippee"],
["a", "and"],
["na", "on"],
["jsem", "I am"],
["že", "that"],
["co", "what"],
["v", "in"],
["si", "you"],
["tak", "so"],
["ne", "No"],
["ale", "but"],
["s", "with"],
["já", "I"],
["mi", "me"],
["mě", "me"],
["jsi", "you are"],
["do", "to"],
["o", "O"],
["ty", "you"],
["jak", "how"],
["už", "already"],
["z", "of"],
["jste", "you"],
["ti", "you"],
["za", "for"],
["tady", "here"],
["tu", "here"],
["když", "when"],
["ho", "him"],
["ano", "Yes"],
["jako", "as"],
["jen", "just"],
["jsme", "we are"],
["jo", "Yeah"],
["by", "would"],
["pro", "for"],
["tě", "you"],
["není", "It is not"],
["dobře", "good"],
["tam", "push"],
["něco", "something"],
["proč", "why"],
["byl", "was"],
["mám", "I have"],
["jsou", "they are"],
["teď", "now"],
["k", "to"],
["no", "well"],
["ten", "the"],
["pane", "Sir"],
["vás", "your"],
["bude", "will be"],
["nic", "nothing"],
["toho", "that"],
["tohle", "this"],
["vám", "you"],
["být", "be"],
["bych", "I would"],
["ve", "in"],
["kdo", "who"],
["má", "has"],
["kde", "where"],
["ještě", "still"],
["nebo", "or"],
["i", "and"],
["ji", "her"],
["tom", "that"],
["po", "after"],
["aby", "that"],
["máš", "you"],
["prosím", "Please"],
["bylo", "it was"],
["můj", "my"],
["vy", "you"],
["všechno", "all"],
["byla", "It was"],
["nás", "our"],
["jestli", "if"],
["než", "than"],
["od", "from"],
["nikdy", "never"],
["měl", "he had"],
["chci", "I want"],
["mu", "him"],
["myslím", "I think"],
["ani", "neither"],
["moc", "power"],
["jeho", "his"],
["víš", "you know"],
["tím", "that"],
["takže", "so"],
["sem", "pull"],
["protože", "because"],
["vím", "I know"],
["taky", "also"],
["možná", "maybe"],
["moje", "My"],
["tebe", "you"],
["až", "when"],
["nevím", "I do not know"],
["ahoj", "Hello"],
["chceš", "you"],
["nám", "U.S"],
["on", "he"],
["ta", "the"],
["jí", "her"],
["hej", "Hey"],
["máme", "we have"],
["pak", "then"],
["díky", "Thanks"],
["pořádku", "alright"],
["u", "at"],
["musím", "I have"],
["dobrý", "good"],
["všichni", "all"],
["budu", "I"],
["řekl", "he said"],
["opravdu", "really"],
["jít", "go"],
["říct", "say"],
["asi", "about"],
["před", "before"],
["pojď", "come on"],
["někdo", "someone"],
["tomu", "that"],
["máte", "you have"],
["rád", "order"],
["myslíš", "You think"],
["my", "we"],
["trochu", "a little"],
["mít", "have"],
["ze", "that"],
["den", "day"],
["dělat", "do"],
["pokud", "if"],
["mohl", "could"],
["jenom", "only"],
["všechny", "all"],
["dva", "two"],
["chtěl", "he wanted"],
["bys", "you"],
["který", "who"],
["musíme", "we must"],
["abych", "me"],
["mnou", "me"],
["budeš", "you"],
["děkuji", "Thank you"],
["víc", "more"],
["dnes", "today"],
["nemůžu", "I can not"],
["tvůj", "your"],
["mně", "me"],
["pořád", "show"],
["stalo", "happened"],
["můžu", "I can"],
["vaše", "your"],
["nikdo", "no one"],
["tebou", "you"],
["jde", "goes"],
["bože", "God"],
["jeden", "one"],
["kdy", "when"],
["udělat", "make"],
["ať", "whatever"],
["oh", "oh"],
["které", "which"],
["sakra", "damn"],
["život", "life"],
["čas", "time"],
["můžeš", "you can"],
["bez", "without"],
["velmi", "very"],
["prostě", "just"],
["ní", "it"],
["vážně", "seriously"],
["hned", "brown"],
["měla", "had"],
["děláš", "you do"],
["dost", "enough"],
["jim", "them"],
["může", "can"],
["musí", "must"],
["říkal", "he said"],
["víte", "you know"],
["právě", "just"],
["kam", "where"],
["měli", "They had"],
["jasně", "clearly"],
["musíš", "you have"],
["takhle", "like this"],
["tvoje", "your"],
["další", "next"],
["lidi", "people"],
["dobrá", "Good"],
["podívej", "look"],
["děje", "going"],
["své", "his"],
["budeme", "we will"],
["nechci", "I do not want"],
["dej", "plot"],
["nemám", "I do not have"],
["pár", "few"],
["věci", "things"],
["jdeme", "going"],
["vůbec", "at all"],
["udělal", "did"],
["nejsem", "I'm not"],
["ona", "she"],
["kvůli", "due to"],
["tři", "three"],
["hodně", "lots of"],
["ok", "ok"],
["ses", "you"],
["zpátky", "back"],
["sám", "alone"],
["chce", "wants"],
["let", "flight"],
["naše", "ours"],
["pryč", "away"],
["první", "first"],
["počkej", "wait"],
["kurva", "whore"],
["chcete", "you want"],
["proto", "therefore"],
["byli", "they were"],
["pravdu", "truth"],
["dlouho", "long"],
["viděl", "saw"],
["místo", "place"],
["domů", "home"],
["jednou", "once"],
["peníze", "money"],
["řekni", "tell"],
["noc", "night"],
["byste", "would"],
["něj", "him"],
["práci", "working"],
["vždycky", "always"],
["zase", "again"],
["kdyby", "if"],
["přesně", "exactly"],
["rychle", "fast"],
["dobré", "good"],
["někdy", "sometimes"],
["vědět", "know"],
["myslel", "thought"],
["její", "her"],
["práce", "work"],
["té", "the"],
["tobě", "thee"],
["nech", "leave"],
["ním", "it"],
["sebe", "myself"],
["mé", "me"],
["paní", "Gentlemen"],
["dál", "gave"],
["vypadá", "looks"],
["promiňte", "sorry"],
["večer", "evening"],
["vidět", "see"],
["každý", "each"],
["snad", "perhaps"],
["mluvit", "speak"],
["můžeme", "we can"],
["jejich", "their"],
["bychom", "we"],
["určitě", "certainly"],
["svou", "his"],
["promiň", "sorry"],
["ráno", "morning"],
["ke", "to"],
["věc", "thing"],
["kolik", "pin"],
["můžete", "you can"],
["děti", "children"],
["jistě", "sure"],
["váš", "your"],
["říká", "says"],
["budou", "will"],
["cože", "what"],
["nejlepší", "the best"],
["lidé", "people"],
["mami", "Mum"],
["stejně", "equally"],
["vlastně", "actually"],
["otec", "father"],
["mají", "have"],
["fakt", "fact"],
["ráda", "advice"],
["tati", "Dad"],
["nebude", "will"],
["která", "which"],
["také", "also"],
["nějaké", "some"],
["abys", "you"],
["řekla", "she said"],
["poslední", "last"],
["žádný", "none"],
["nějaký", "some"],
["jdu", "I go"],
["žádné", "no"],
["dítě", "child"],
["budete", "will"],
["dvě", "two"],
["přišel", "came"],
["ven", "out"],
["dostat", "get"],
["zítra", "tomorrow"],
["jdi", "go"],
["potom", "then"],
["spolu", "together"],
["problém", "problem"],
["pravda", "truth"],
["úplně", "completely"],
["lepší", "better"],
["zlato", "gold"],
["celý", "whole"],
["pod", "under"],
["chvíli", "for a while"],
["někoho", "somebody"],
["člověk", "human"],
["mezi", "between"],
["jedna", "one"],
["pozor", "Attention"],
["třeba", "perhaps"],
["jméno", "name"],
["svůj", "its"],
["přece", "yet"],
["žena", "woman"],
["hele", "Hey"],
["fajn", "Okay"],
["muž", "man"],
["stále", "still"],
["těch", "those"],
["omlouvám", "sorry"],
["mohla", "she could"],
["chtěla", "wanted"],
["samozřejmě", "Of course"],
["vše", "all"],
["lidí", "people"],
["myslíte", "do you think"],
["pan", "Mr"],
["čem", "what"],
["náš", "our"],
["při", "at"],
["sis", "sis"],
["vidím", "I see"],
["dát", "give"],
["běž", "without"],
["podle", "according to"],
["nebyl", "has not been"],
["znamená", "means"],
["dělá", "makes"],
["dostal", "received"],
["pomoc", "Help"],
["dal", "gave"],
["toto", "this"],
["jedno", "one"],
["tenhle", "this"],
["oni", "they"],
["znovu", "again"],
["dokud", "while"],
["jaký", "what"],
["proti", "against"],
["štěstí", "luck"],
["pojďte", "come"],
["mohli", "could"],
["přes", "over"],
["nemá", "has"],
["jednu", "one"],
["teda", "therefore"],
["líto", "sorry"],
["doma", "home"],
["říkám", "I say"],
["auto", "car"],
["najít", "find"],
["nemůžeš", "You can not"],
["dneska", "today"],
["nich", "them"],
["haló", "Hello"],
["tedy", "therefore"],
["líbí", "like"],
["kterou", "Which"],
["musíte", "you have to"],
["doufám", "hope"],
["kámo", "dude"],
["mého", "my"],
["sebou", "row"],
["dobrou", "Good night"],
["poslouchej", "listen"],
["řeknu", "I say"],
["věděl", "knew"],
["neměl", "had"],
["přestaň", "stop"],
["ví", "knows"],
["vidíš", "you see"],
["byly", "the"],
["vámi", "you"],
["dělej", "come on"],
["příliš", "too much"],
["pojďme", "lets go"],
["svého", "his"],
["tolik", "so many"],
["děkuju", "Thank you"],
["celou", "the whole"],
["tento", "this"],
["stát", "state"],
["pět", "five"],
["nejsou", "They are not"],
["slyšel", "heard"],
["noci", "nights"],
["odsud", "from here"],
["potřebuju", "I need"],
["kdybych", "I"],
["pohodě", "cool"],
["námi", "us"],
["minut", "minutes"],
["zrovna", "just"],
["kteří", "who"],
["podívejte", "Look"],
["vzít", "take"],
["sama", "herself"],
["zemi", "country"],
["zabít", "kill"],
["buď", "either"],
["jaké", "what"],
["nebudu", "I will not"],
["takový", "such"],
["uvidíme", "we'll see"],
["velký", "big"],
["matka", "mother"],
["vlastní", "own"],
["tvé", "your"],
["nemáš", "you do not"],
["dám", "give"],
["nemůže", "can not"],
["vždyť", "after all"],
["jinak", "otherwise"],
["ruce", "hands"],
["muset", "have to"],
["abyste", "to"],
["sobě", "themselves"],
["srdce", "heart"],
["vždy", "always"],
["později", "later"],
["číslo", "number"],
["prdele", "shit"],
["mohu", "I can"],
["muže", "man"],
["všem", "all"],
["nechte", "leave"],
["nechat", "let"],
["koho", "whom"],
["pomoct", "help"],
["správně", "correctly"],
["dolů", "down"],
["dejte", "give"],
["dveře", "door"],
["nebylo", "was not"],
["jednoho", "one"],
["nad", "over"],
["konec", "end"],
["miluju", "I love"],
["zde", "here"],
["svět", "world"],
["tyhle", "these"],
["nejsi", "you are not"],
["skoro", "almost"],
["myslela", "thought"],
["zabil", "killed"],
["kolem", "around"],
["přímo", "direct"],
["pozdě", "late"],
["děláte", "you do"],
["musel", "He had to"],
["radši", "rather"],
["života", "life"],
["dům", "House"],
["táta", "dad"],
["říkala", "she"],
["pánové", "Messrs"],
["znám", "I know"],
["máma", "mum"],
["venku", "outdoors"],
["myslí", "think"],
["nějak", "somehow"],
["dovnitř", "in"],
["chlap", "guy"],
["mne", "me"],
["ostatní", "other"],
["hrát", "play"],
["našel", "found"],
["bůh", "God"],
["nápad", "idea"],
["ach", "oh"],
["světě", "world"],
["čtyři", "four"],
["brzy", "soon"],
["žít", "live"],
["dolarů", "dollars"],
["skvělý", "great"],
["slečno", "Miss"],
["drž", "hold"],
["dělám", "I'm doing"],
["jasný", "clear"],
["počkejte", "Wait"],
["vrátit", "return"],
["seš", "you're"],
["svoje", "my"],
["včera", "yesterday"],
["nějakou", "some"],
["aspoň", "at least"],
["něm", "it"],
["všech", "all"],
["zdá", "whether"],
["oči", "eyes"],
["mou", "my"],
["the", "the"],
["tuhle", "this"],
["strach", "fear"],
["naší", "our"],
["hlavu", "head"],
["někde", "somewhere"],
["viděla", "seeing"],
["hodin", "hours"],
["půjdu", "I will go"],
["udělám", "I do"],
["celé", "throughout"],
["času", "time"],
["jiného", "another"],
["nový", "new"],
["oba", "both"],
["abychom", "us"],
["šel", "going"],
["vzal", "married"],
["nahoru", "up"],
["cítím", "I feel"],
["zůstat", "remain"],
["nebyla", "was not"],
["zpět", "back"],
["přijde", "coming"],
["malý", "small"],
["rok", "year"],
["muži", "men"],
["nemůžeme", "we can not"],
["nechceš", "want"],
["stane", "happens"],
["zatím", "yet"],
["říkáš", "you say"],
["více", "more"],
["daleko", "far"],
["dokonce", "even"],
["dělal", "did"],
["nemáme", "we have"],
["čím", "more"],
["copak", "Have"],
["jdeš", "going"],
["holka", "girl"],
["svým", "his"],
["ně", "No"],
["týden", "week"],
["tys", "you with"],
["této", "this"],
["chlape", "man"],
["pěkně", "well"],
["jiný", "other"],
["dřív", "sooner"],
["vaší", "your"],
["země", "Earth"],
["ni", "it"],
["zbraň", "weapon"],
["cestu", "path"],
["podívat", "look"],
["smrti", "death"],
["tahle", "this"],
["ženy", "women"],
["nejde", "not"],
["předtím", "previously"],
["nyní", "now"],
["takové", "such"],
["žádná", "none"],
["jich", "there"],
["skvělé", "Great"],
["počkat", "wait"],
["slovo", "word"],
["udělala", "she did"],
["syn", "son"],
["vaši", "your"],
["cokoliv", "anything"],
["kluk", "boy"],
["ženu", "woman"],
["spát", "sleep"],
["stačí", "enough"],
["špatně", "poorly"],
["dny", "days"],
["klid", "peace"],
["přítel", "friend"],
["konečně", "finally"],
["chvilku", "moment"],
["moji", "my"],
["mluvíš", "talking about"],
["jistý", "sure"],
["potřebujeme", "need"],
["promluvit", "speak"],
["roky", "years"],
["mrtvý", "dead"],
["docela", "quite"],
["new", "new"],
["otce", "father"],
["problémy", "trouble"],
["neviděl", "seen"],
["dá", "can"],
["nemohl", "could not"],
["ono", "it"],
["řekněte", "tell"],
["šest", "six"],
["chtějí", "they want"],
["auta", "Cars"],
["ruku", "hand"],
["chtít", "want"],
["hodiny", "clock"],
["nechtěl", "wanted"],
["pokoj", "room"],
["mnoho", "many"],
["policie", "police"],
["doktore", "Doctor"],
["přišla", "she came"],
["vypadáš", "look"],
["věcí", "things"],
["nejdřív", "first"],
["jseš", "are you"],
["tvá", "thy"],
["jediný", "only"],
["naši", "our"],
["životě", "life"],
["deset", "ten"],
["možné", "possible"],
["potřebuji", "need"],
["neboj", "do not worry"],
["důvod", "reason"],
["nechal", "had"],
["domu", "home"],
["tou", "the"],
["madam", "madam"],
["prachy", "dough"],
["jmenuje", "appointed"],
["věřit", "trust"],
["nemyslím", "I do not"],
["dne", "of the day"],
["cestě", "way"],
["velké", "large"],
["smrt", "death"],
["přijít", "come"],
["pocit", "feeling"],
["stojí", "cost"],
["raději", "rather"],
["tělo", "body"],
["nikoho", "nobody"],
["říkat", "say"],
["dole", "down"],
["znáš", "you know"],
["chápu", "I understand"],
["you", "you"],
["mým", "my"],
["jídlo", "food"],
["všude", "everywhere"],
["šanci", "chance"],
["tomhle", "this"],
["neřekl", "told"],
["jděte", "go"],
["zní", "sounds"],
["nemohu", "can not"],
["jet", "go"],
["vezmu", "take"],
["dobu", "time"],
["proboha", "for heaven's sake"],
["mojí", "my"],
["dámy", "ladies"],
["taková", "such a"],
["vidíte", "you see"],
["loď", "ship"],
["místě", "place"],
["bejt", "Beit"],
["kapitáne", "Captain"],
["super", "super"],
["velice", "very"],
["půl", "half"],
["mohlo", "could"],
["zvláštní", "strange"],
["potřebuje", "needs"],
["pouze", "only"],
["aha", "I see"],
["doktor", "doctor"],
["hubu", "up"],
["školy", "schools"],
["doby", "time"],
["rozumím", "I understand"],
["odejít", "leave"],
["odtud", "from here"],
["starý", "old"],
["čau", "Hi"],
["bratr", "brother"],
["nemáte", "you do not"],
["což", "which"],
["jaká", "what a"],
["tvou", "your"],
["nevíš", "you know"],
["odkud", "whence"],
["tudy", "This way"],
["nové", "new"],
["výborně", "Great"],
["kluci", "boys"],
["města", "cities"],
["vem", "take"],
["malá", "small"],
["nemůžete", "You can not"],
["ó", "O"],
["vězení", "prison"],
["nedělej", "do"],
["těžké", "difficult"],
["přátelé", "friends"],
["během", "during"],
["našli", "they found"],
["pomoci", "help"],
["světa", "world"],
["mnohem", "much"],
["říkají", "they say"],
["začal", "he has begun"],
["nimi", "them"],
["město", "city"],
["svých", "their"],
["nevadí", "does not matter"],
["peněz", "money"],
["nakonec", "finally"],
["sbohem", "Goodbye"],
["skvěle", "Great"],
["chlapi", "guys"],
["neměla", "had"],
["udělej", "do"],
["vrať", "return"],
["blázen", "fool"],
["jiné", "other"],
["telefon", "phone"],
["příběh", "story"],
["mimo", "outside"],
["támhle", "there"],
["poprvé", "first"],
["ukaž", "phenomena"],
["vrátím", "return"],
["dní", "days"],
["otče", "Father"],
["li", "if"],
["krev", "blood"],
["nechce", "does not want"],
["miláčku", "my darling"],
["čeká", "waiting"],
["velká", "big"],
["mluvil", "speaking"],
["holky", "girls"],
["vezmi", "take"],
["zůstaň", "stay"],
["nahoře", "up"],
["zeptat", "ask"],
["uděláme", "do"],
["jakou", "what"],
["zavolám", "call"],
["líp", "better"],
["plán", "plan"],
["syna", "son"],
["jacku", "jack"],
["kdybys", "if you"],
["pana", "Mr."],
["film", "film"],
["cesty", "path"],
["pracovat", "work"],
["způsob", "way"],
["půjdeme", "we will go"],
["víme", "we know"],
["tohoto", "this"],
["pokoji", "room"],
["vypadni", "scram"],
["skutečně", "really"],
["potřebovat", "need"],
["rodiče", "parents"],
["chyba", "error"],
["dr", "dr"],
["kromě", "except"],
["vede", "leads"],
["rodina", "family"],
["mělo", "had"],
["nebudeš", "will not"],
["přišli", "they came"],
["čekat", "wait"],
["začít", "start"],
["chlapče", "boy"],
["láska", "love"],
["našeho", "our"],
["večeři", "dinner"],
["zavolat", "call"],
["chceme", "we want"],
["slyšet", "hear"],
["smysl", "meaning"],
["spoustu", "a lot"],
["jasné", "clearly"],
["žije", "lives"],
["nohy", "legs"],
["běžte", "go"],
["myslet", "think"],
["potřebuješ", "need"],
["mých", "my"],
["nějaká", "some"],
["větší", "larger"],
["věděla", "knew"],
["miluji", "love"],
["několik", "several"],
["lety", "flights"],
["poslouchejte", "listen"],
["dala", "she"],
["vrátil", "returned"],
["mém", "my"],
["případě", "event"],
["jediná", "only"],
["domě", "house"],
["tuto", "this"],
["chtěli", "they wanted"],
["mluví", "speaks"],
["ode", "from"],
["malé", "small"],
["čemu", "what"],
["čeho", "what"],
["uvnitř", "inside"],
["neříkej", "Do not say"],
["městě", "city"],
["svoji", "his"],
["nemusíš", "you do not"],
["důležité", "important"],
["tyto", "these"],
["dobrej", "good"],
["udělali", "done"],
["spíš", "Are you sleeping"],
["zastavit", "stop"],
["zbraně", "guns"],
["však", "however"],
["druhé", "other"],
["klidně", "calmly"],
["pamatuješ", "remember"],
["viděli", "saw"],
["špatné", "poorly"],
["rádi", "like"],
["neví", "know"],
["takového", "such a"],
["joe", "joe"],
["okamžitě", "immediately"],
["pěkný", "nice"],
["někam", "somewhere"],
["případ", "case"],
["dostali", "they got"],
["moment", "moment"],
["věřím", "I believe"],
["žádnou", "any"],
["jedeme", "we are going"],
["začíná", "begins"],
["vašeho", "yours"],
["znáte", "you know"],
["hlavně", "mainly"],
["zatraceně", "damn"],
["straně", "page"],
["jistá", "sure"],
["snažím", "I try"],
["zprávy", "news"],
["škole", "school"],
["každou", "every"],
["tisíc", "thousand"],
["hlavní", "main"],
["mysli", "mind"],
["najednou", "suddenly"],
["dostanu", "get"],
["prdel", "ass"],
["takovou", "a"],
["zas", "again"],
["pohyb", "movement"],
["nevěděl", "know"],
["charlie", "charlie"],
["titulky", "headlines"],
["pořádně", "properly"],
["mluvím", "I am talking"],
["cos", "what with"],
["hlavy", "heads"],
["chodit", "walk"],
["měsíc", "Moon"],
["hrozně", "awfully"],
["patří", "belongs"],
["tvého", "your"],
["špatný", "not good"],
["páni", "Gentlemen"],
["nikomu", "anyone"],
["naprosto", "absolutely"],
["ticho", "silence"],
["vedle", "next to"],
["celá", "cell"],
["cesta", "way"],
["tomto", "this"],
["tato", "this"],
["slyšíš", "hear"],
["uklidni", "calm down"],
["rodinu", "family"],
["sestra", "sister"],
["člověka", "man"],
["vlasy", "hair"],
["zkus", "try"],
["strašně", "horribly"],
["cenu", "price"],
["největší", "biggest"],
["bolí", "hurts"],
["hodinu", "an hour"],
["neměli", "They had"],
["lidem", "to people"],
["prý", "allegedly"],
["vrátí", "returns"],
["dělají", "make"],
["uh", "uh"],
["slova", "words"],
["rukou", "hand"],
["velkou", "great"],
["náhodou", "by chance"],
["l", "l"],
["dostala", "she got"],
["lépe", "better"],
["šla", "she went"],
["otevři", "open"],
["dostane", "gets"],
["svém", "his"],
["rozumíš", "okay"],
["dcera", "daughter"],
["sen", "dream"],
["našich", "our"],
["me", "me"],
["ježíši", "jeez"],
["zbytek", "residue"],
["člověče", "Man"],
["sedm", "seven"],
["druhý", "second"],
["koukni", "look"],
["johne", "John"],
["zemřel", "died"],
["slyšela", "heard"],
["sami", "themselves"],
["nejste", "you are not"],
["část", "part"],
["tajemství", "secret"],
["šaty", "dress"],
["blízko", "close"],
["nejsme", "we are"],
["bojovat", "combat"],
["chlapci", "boys"],
["policii", "police"],
["šéfe", "boss"],
["půjde", "will go"],
["často", "often"],
["čertu", "hell"],
["zavolej", "call"],
["místa", "places"],
["zabiju", "kill"],
["nechápu", "I do not understand"],
["and", "and"],
["tým", "team"],
["pomalu", "slowly"],
["tý", "you"],
["král", "king"],
["vody", "waters"],
["dáme", "we"],
["ztratil", "lost"],
["právo", "right"],
["tamhle", "there"],
["manžel", "husband"],
["záleží", "it depends"],
["představit", "introduce"],
["navíc", "moreover"],
["zdravím", "Hello"],
["poslal", "sent"],
["drahá", "path"],
["kým", "while"],
["chlapec", "boy"],
["dávno", "long time ago"],
["alespoň", "at least"],
["žes", "you did"],
["šlo", "was"],
["přísahám", "I swear"],
["bohu", "God"],
["téhle", "this"],
["okay", "okay"],
["možnost", "possibility"],
["starosti", "worry"],
["odešel", "retired"],
["normální", "normal"],
["stará", "old"],
["vodu", "water"],
["zapomněl", "forgot"],
["společnost", "company"],
["krásná", "beautiful"],
["hajzlu", "Shit"],
["uvěřit", "believe"],
["dáš", "give"],
["říkáte", "call"],
["klidu", "peace"],
["trošku", "slightly"],
["hezký", "pretty"],
["hmm", "hmm"],
["musela", "she had to"],
["tentokrát", "this time"],
["ulici", "street"],
["srandu", "joking"],
["kterého", "which"],
["slunce", "sun"],
["šťastný", "happy"],
["rozhodně", "definitely"],
["vítejte", "welcome"],
["roku", "year"],
["něho", "it"],
["jeď", "poison"],
["bezpečí", "safety"],
["říci", "say"],
["vole", "dude"],
["osm", "eight"],
["kousek", "bit"],
["hlad", "hunger"],
["zač", "You're welcome"],
["nikam", "nowhere"],
["již", "already"],
["příští", "next"],
["nechám", "I leave"],
["skutečnosti", "reality"],
["chodí", "goes"],
["bysme", "we"],
["připraven", "ready"],
["měsíce", "month"],
["honem", "Come on"],
["občas", "sometimes"],
["držet", "hold"],
["neudělal", "done"],
["jíst", "eat"],
["chápeš", "do you understand"],
["udělá", "makes"],
["ukázat", "show"],
["mrzí", "sorry"],
["obchod", "trade"],
["dopis", "letter"],
["harry", "harry"],
["našla", "she found"],
["týdny", "weeks"],
["řekli", "they said"],
["zprávu", "report"],
["pusť", "fasting"],
["hra", "game"],
["jménem", "on behalf of"],
["nevěřím", "I do not believe"],
["vzala", "married"],
["yorku", "york"],
["koupit", "buy"],
["hovno", "shit"],
["rodiny", "families"],
["pěkné", "nice"],
["roce", "year"],
["otázka", "question"],
["třetí", "third"],
["nelíbí", "dislikes"],
["brzo", "soon"],
["uděláš", "you do"],
["jediné", "only"],
["přestaňte", "stop"],
["těm", "those"],
["spousta", "a lot"],
["tehdy", "then"],
["dostaneš", "get"],
["pomoz", "help"],
["najdu", "I will find"],
["panebože", "Oh my God"],
["věř", "trust"],
["opatrně", "carefully"],
["změnit", "alter"],
["tvým", "thy"],
["zdraví", "health"],
["dali", "they gave"],
["příště", "next time"],
["tvoji", "yours"],
["lodi", "boat"],
["hm", "hm"],
["někým", "someone"],
["těmi", "those"],
["dostaneme", "we will get"],
["němu", "it"],
["horší", "worse"],
["zapomeň", "forget"],
["volal", "called"],
["nejspíš", "probably"],
["nemocnice", "hospital"],
["době", "time"],
["koně", "horses"],
["půjdeš", "you go"],
["řekne", "says"],
["světlo", "light"],
["mohou", "they can"],
["pití", "drink"],
["děvče", "girl"],
["měsíců", "months"],
["snaží", "try"],
["nebudeme", "we will not"],
["pes", "dog"],
["mladý", "young"],
["ukážu", "show"],
["nemají", "have"],
["cítíš", "feeling"],
["kapitán", "captain"],
["můžou", "they can"],
["pokračovat", "continue"],
["málo", "little"],
["dvakrát", "twice"],
["mrtvá", "dead"],
["tvář", "face"],
["informace", "information"],
["dívka", "girl"],
["odpoledne", "afternoon"],
["ovšem", "of course"],
["dohromady", "together"],
["jedné", "one"],
["těchto", "these"],
["druhou", "second"],
["úžasné", "amazing"],
["nemohla", "could not"],
["zachránit", "save"],
["odpověď", "answer"],
["bohužel", "unfortunately"],
["nevidím", "I do not see"],
["kdybyste", "if you"],
["nového", "new"],
["boty", "shoes"],
["pivo", "beer"],
["řekneš", "tell"],
["jimmy", "jimmy"],
["válka", "war"],
["škoda", "damage"],
["slyším", "I hear"],
["jakmile", "once"],
["ha", "ha"],
["nerozumím", "I do not understand"],
["znova", "anew"],
["rozkaz", "command"],
["společnosti", "company"],
["vzhůru", "up"],
["nechtěla", "wanted"],
["samé", "The same"],
["voda", "water"],
["dvou", "two"],
["konce", "ends"],
["naživu", "alive"],
["hlas", "voice"],
["skvělá", "great"],
["sedni", "sit"],
["sex", "sex"],
["těla", "bodies"],
["synu", "son"],
["komu", "whom"],
["příteli", "friend"],
["existuje", "there"],
["dvěma", "two"],
["nebuď", "do not be"],
["boha", "God"],
["jdou", "go"],
["nechcete", "you do not"],
["autě", "car"],
["těší", "enjoying"],
["platí", "pay"],
["pomozte", "help"],
["někomu", "to someone"],
["přítele", "Friend"],
["každého", "each"],
["zkusit", "try"],
["novou", "new"],
["stal", "stood"],
["televizi", "TV"],
["krásné", "beautifully"],
["hotelu", "hotel"],
["říkali", "they said"],
["společně", "together"],
["kterým", "which"],
["malou", "small"],
["držte", "keep"],
["poslyš", "listen"],
["lásku", "love"],
["okolo", "around"],
["stejné", "the same"],
["svojí", "his"],
["chlapa", "guy"],
["john", "john"],
["mary", "bier"],
["někteří", "some"],
["šance", "chance"],
["překvapení", "surprise"],
["drahý", "expensive"],
["postele", "beds"],
["dívat", "look"],
["pán", "Mr"],
["sílu", "power"],
["www", "www"],
["nazdar", "Hi"],
["buďte", "be"],
["snažil", "sought"],
["všeho", "all"],
["zem", "ground"],
["dávej", "watch"],
["cítit", "feel"],
["děláme", "we do"],
["hezké", "nice"],
["perfektní", "perfect"],
["funguje", "works"],
["dík", "thanks"],
["slečna", "miss"],
["com", "com"],
["zjistit", "find out"],
["de", "de"],
["neznám", "I know"],
["franku", "franc"],
["bratra", "brother"],
["pokoje", "rooms"],
["bojím", "I fear"],
["navždy", "forever"],
["holku", "girl"],
["hledat", "search"],
["nedá", "can not"],
["každé", "every"],
["uvidíš", "you will see"],
["měj", "have"],
["šéf", "boss"],
["zatímco", "while"],
["stejný", "same"],
["kdysi", "once"],
["miluje", "he loves"],
["či", "whose"],
["pravděpodobně", "probably"],
["přijdu", "I come"],
["tvojí", "yours"],
["budoucnost", "future"],
["tímhle", "this one"],
["zajímá", "interested"],
["zemřít", "die"],
["zlatíčko", "sweetheart"],
["matku", "mother"],
["jedem", "poison"],
["jmenuji", "My name"],
["chvíle", "moment"],
["moci", "can"],
["klíč", "key"],
["e", "E"],
["milovat", "love"],
["mimochodem", "by the way"],
["cokoli", "anything"],
["dalších", "next"],
["hlavě", "head"],
["nesmí", "can not"],
["d", "d"],
["koupil", "bought"],
["umí", "can"],
["pracuje", "working"],
["staré", "old"],
["radost", "joy"],
["zřejmě", "apparently"],
["dává", "gives"],
["dělala", "done"],
["letadlo", "airplane"],
["rozhodnutí", "decision"],
["jinou", "other"],
["vydrž", "stamina"],
["zabili", "killed"],
["neřekla", "tell"],
["připraveni", "ready"],
["hledám", "seeking"],
["ženou", "woman"],
["chybí", "miss"],
["zadek", "bum"],
["šťastná", "happy"],
["it", "it"],
["dáte", "you"],
["mluvíte", "you speak"],
["většina", "most"],
["přestat", "stop"],
["yeah", "yeah"],
["seznam", "list"],
["naposledy", "last"],
["krásný", "beautiful"],
["hezky", "pretty"],
["boží", "divine"],
["vánoce", "Christmas"],
["jede", "goes"],
["dříve", "previously"],
["napsal", "wrote"],
["dárek", "gift"],
["začne", "starts"],
["osobně", "personally"],
["hru", "game"],
["války", "war"],
["rande", "date"],
["plánu", "plan"],
["ah", "ah"],
["nějakej", "some kind"],
["poslouchat", "listen"],
["totiž", "namely"],
["otázky", "issues"],
["vstávej", "Get up"],
["oběd", "lunch"],
["napadlo", "thought"],
["svý", "my"],
["ja", "I"],
["museli", "they had"],
["duše", "soul"],
["dceru", "a daughter"],
["hlava", "head"],
["umíš", "can you"],
["jack", "jack"],
["nevíte", "know"],
["beru", "I take"],
["hoši", "boys"],
["doktora", "Dr."],
["jedu", "poison"],
["zachránil", "saved"],
["brácho", "bro"],
["dělejte", "do"],
["pěkná", "nice"],
["henry", "henry"],
["stůj", "Stop"],
["show", "show"],
["nebudou", "will"],
["milý", "nice"],
["viď", "vide"],
["společného", "common"],
["mrtví", "dead"],
["přichází", "coming"],
["začala", "began"],
["jedním", "one"],
["šli", "they went"],
["dnešní", "current"],
["hraje", "plays"],
["b", "b"],
["očí", "eye"],
["nová", "new"],
["omluvte", "excuse"],
["použít", "use"],
["pomůže", "help"],
["neviděla", "seen"],
["systém", "system"],
["úžasný", "amazing"],
["skončil", "ended"],
["chlápek", "bloke"],
["dětí", "children"],
["znamenat", "mean"],
["kafe", "coffee"],
["potřebujete", "need"],
["zůstaňte", "stay"],
["najdeme", "find"],
["tvých", "your"],
["líbit", "like"],
["přijel", "arrived"],
["pomohl", "help"],
["letech", "years"],
["názor", "opinion"],
["la", "la"],
["začátku", "beginning"],
["obávám", "fear"],
["otázku", "question"],
["nestalo", "happened"],
["billy", "billy"],
["zavolejte", "call"],
["obvykle", "usually"],
["kluka", "boy"],
["nezáleží", "does not matter"],
["druh", "species"],
["sedět", "sit"],
["vysvětlit", "explain"],
["zavři", "shut"],
["rozdíl", "difference"],
["pusťte", "release"],
["pravidla", "rules"],
["t", "T"],
["nechala", "leaving"],
["vašich", "your"],
["posteli", "bed"],
["jdete", "you go"],
["nesnáším", "I hate"],
["c", "C"],
["nemyslíš", "do not"],
["zastavte", "stop"],
["konci", "end"],
["vzali", "married"],
["osud", "fate"],
["umění", "art"],
["uprostřed", "middle"],
["devět", "nine"],
["duši", "the soul"],
["párty", "party"],
["rozhodl", "decided"],
["drahoušku", "honey"],
["projít", "go through"],
["dvacet", "twenty"],
["mužů", "men"],
["skončí", "ends"],
["zastav", "stop"],
["brát", "take"],
["světla", "lights"],
["dokázal", "managed"],
["čekal", "waited"],
["stop", "Stop"],
["vsadím", "I bet"],
["zájem", "interest"],
["řídit", "drive"],
["kus", "piece"],
["psa", "dog"],
["došlo", "there"],
["dělali", "done"],
["zima", "winter"],
["čaj", "tea"],
["knihu", "book"],
["způsobem", "way"],
["oddělení", "department"],
["zabije", "kill"],
["vyhrál", "won"],
["dovolit", "allow"],
["noční", "night"],
["lásky", "love"],
["miluješ", "love"],
["získat", "gain"],
["pohled", "view"],
["opět", "again"],
["hry", "games"],
["byt", "be"],
["mluv", "speak"],
["filmu", "movie"],
["děkujeme", "thank you"],
["vtip", "joke"],
["připravit", "prepare"],
["bolest", "pain"],
["zuby", "teeth"],
["domov", "home"],
["správné", "correctly"],
["lidmi", "people"],
["hudba", "music"],
["potřeboval", "need"],
["některé", "some"],
["tome", "tom"],
["vzduchu", "air"],
["postarám", "take care"],
["každej", "each"],
["plný", "full"],
["nebezpečí", "danger"],
["koukej", "look"],
["poslat", "send"],
["hey", "hey"],
["nejhorší", "worst"],
["osobní", "personal"],
["jej", "him"],
["pracoval", "he worked"],
["celkem", "total"],
["bát", "fear"],
["tvém", "your"],
["bratře", "brother"],
["naučil", "learned"],
["bobby", "bobby"],
["moře", "sea"],
["celej", "the whole"],
["city", "feelings"],
["kdybychom", "we"],
["vzadu", "back"],
["mozek", "brain"],
["ženská", "woman"],
["rovnou", "straight"],
["přesto", "yet"],
["stranu", "party"],
["volá", "calls"],
["jmenuješ", "your name"],
["nezajímá", "cares"],
["těžko", "difficult"],
["vemte", "take"],
["zápas", "wrestle"],
["úkol", "task"],
["situaci", "the situation"],
["hodný", "good"],
["mrtvej", "dead"],
["nervózní", "nervous"],
["cíl", "target"],
["otevřít", "open"],
["umřít", "die"],
["střední", "medium"],
["zcela", "completely"],
["same", "same"],
["rychleji", "faster"],
["kterém", "which"],
["nevíme", "We do not know"],
["slyšíte", "hear"],
["jdem", "Let's go"],
["bezva", "cool"],
["klíče", "keys"],
["přítelkyně", "girlfriend"],
["mistře", "Master"],
["johnny", "johnny"],
["george", "george"],
["zničit", "destroy"],
["zpráva", "message"],
["naučit", "learn"],
["tohohle", "this one"],
["důkaz", "evidence"],
["hajzle", "motherfucker"],
["nezapomeň", "remember"],
["dále", "further"],
["tony", "tony"],
["neslyšel", "heard"],
["téměř", "almost"],
["slíbil", "promised"],
["slyšeli", "heard"],
["nenávidím", "I hate"],
["oheň", "fire"],
["klubu", "club"],
["příležitost", "opportunity"],
["málem", "almost"],
["milé", "mile"],
["davide", "davide"],
["äŕ", "AR"],
["zákon", "law"],
["zjistil", "found out"],
["chybu", "mistake"],
["sexy", "sexy"],
["knihy", "books"],
["rána", "wound"],
["oblečení", "clothes"],
["situace", "situation"],
["krok", "step"],
["cítil", "feeling"],
["pokračuj", "go ahead"],
["jane", "I do not"],
["potíže", "difficulties"],
["nebe", "sky"],
["nemocnici", "hospital"],
["divný", "odd"],
["cestou", "way"],
["anebo", "or"],
["zda", "whether"],
["vrah", "murderer"],
["jiná", "other"],
["umím", "I can"],
["svému", "his"],
["pardon", "Pardon"],
["in", "in"],
["ničemu", "useless"],
["mysleli", "thought"],
["nebudete", "you"],
["vzkaz", "message"],
["posledních", "last"],
["řadě", "row"],
["cz", "cz"],
["zůstane", "will remain"],
["pusu", "mouth"],
["začneme", "begin"],
["schůzku", "meeting"],
["chuť", "taste"],
["vidí", "sees"],
["jednoduché", "easy"],
["dokáže", "can"],
["zlý", "evil"],
["eddie", "eddie"],
["neznamená", "does not"],
["okamžik", "moment"],
["kriste", "good heavens"],
["č", "C"],
["vypadat", "to look like"],
["číst", "read"],
["pomůžu", "help"],
["j", "j"],
["potkal", "met"],
["zbláznil", "crazy"],
["žádnej", "s no"],
["mladá", "Young"],
["začali", "they started"],
["náma", "us"],
["ted", "now"],
["těžký", "heavy"],
["of", "of"],
["takovej", "sort of"],
["nim", "them"],
["připravte", "ready"],
["sny", "dreams"],
["telefonu", "phone"],
["odešla", "gone"],
["san", "san"],
["jenže", "only"],
["jednom", "one meter"],
["koule", "ball"],
["divné", "weird"],
["vlak", "train"],
["trvat", "last"],
["například", "for example"],
["narozeniny", "birthday"],
["starší", "elderly"],
["jména", "names"],
["zemřela", "died"],
["lásko", "baby"],
["vraťte", "return"],
["otevřete", "open"],
["drží", "holds"],
["poznal", "recognized"],
["jestliže", "if"],
["utéct", "escape"],
["věděli", "they knew"],
["och", "oh"],
["nejvíc", "most"],
["změnil", "changed"],
["minulý", "last"],
["sehnat", "get"],
["slibuju", "I promise"],
["vina", "fault"],
["soudu", "court"],
["sledovat", "track"],
["vezměte", "take"],
["našem", "our"],
["matky", "mothers"],
["nestane", "happen"],
["nevěděla", "know"],
["místnosti", "the room"],
["doopravdy", "really"],
["mí", "me"],
["druhá", "second"],
["hrál", "played"],
["vašem", "your"],
["pokračujte", "continue"],
["posaďte", "sit down"],
["typ", "type"],
["fotky", "photos"],
["kamarád", "friend"],
["zajímavé", "interestingly"],
["seržante", "Sergeant"],
["mýho", "my"],
["pravý", "right"],
["čest", "honor"],
["nesmíš", "you can not"],
["všechna", "all"],
["nemusí", "not"],
["zůstal", "remained"],
["pozornost", "attention"],
["teprve", "only"],
["ženě", "woman"],
["minuty", "minutes"],
["zaplatit", "pay"],
["čekám", "I'm waiting"],
["vypadám", "look"],
["kávu", "coffee"],
["ničeho", "nothing"],
["spojení", "connection"],
["manželství", "marriage"],
["steve", "steve"],
["hlavou", "head"],
["tisíce", "thousand"],
["jel", "goin"],
["celém", "around"],
["plukovníku", "Colonel"],
["zná", "knows"],
["fbi", "fbi"],
["nebojte", "do not worry"],
["přinesl", "brought"],
["velkej", "big"],
["miloval", "he loved"],
["rozumíte", "understand"],
["dávat", "give"],
["sedí", "seated"],
["slib", "promise"],
["opustit", "forsake"],
["směrem", "direction"],
["otci", "father"],
["signál", "signal"],
["dokážeš", "can you"],
["krve", "blood"],
["á", "and"],
["méně", "less"],
["malej", "small"],
["tommy", "tommy"],
["líbilo", "liked"],
["laskavost", "kindness"],
["danny", "danny"],
["síla", "strong"],
["válce", "war"],
["silný", "strong"],
["týmu", "team"],
["chlapce", "boy"],
["ohledně", "regarding"],
["uvidím", "I'll see"],
["nebezpečné", "dangerously"],
["tímto", "hereby"],
["kamaráde", "man"],
["bene", "bene"],
["vzpomínáš", "remember"],
["obě", "both"],
["m", "m"],
["přátele", "friends"],
["policejní", "police"],
["svými", "his"],
["lee", "lee"],
["neexistuje", "there"],
["prezident", "president"],
["budem", "I'll"],
["kterých", "which"],
["četl", "read"],
["nashle", "Bye"],
["povím", "tell"],
["tvrdí", "says"],
["nebyli", "they were not"],
["vypadněte", "Get out"],
["georgi", "Georgi"],
["akorát", "just"],
["mil", "mil"],
["zticha", "quiet"],
["idiot", "idiot"],
["krále", "King"],
["školu", "school"],
["podívám", "look"],
["každá", "every"],
["sklapni", "shut up"],
["manžela", "husband"],
["milionů", "million"],
["stůl", "table"],
["nemusíte", "you do not"],
["vztah", "relationship"],
["nos", "nose"],
["daří", "flourishes"],
["spí", "sleeps"],
["povolení", "authorization"],
["bobe", "Bob"],
["udělejte", "make"],
["generále", "General"],
["léta", "years"],
["vědí", "know"],
["zvíře", "animal"],
["sranda", "hoot"],
["sam", "alone"],
["mluvili", "they speak"],
["čase", "time"],
["rodině", "family"],
["učit", "teach"],
["vzduch", "air"],
["připravený", "prepared"],
["blíž", "closer"],
["víno", "wine"],
["kate", "kate"],
["zlé", "badly"],
["nechoď", "Do not go"],
["drogy", "drugs"],
["zvládnu", "can handle"],
["síly", "forces"],
["mému", "my"],
["uvidí", "sees"],
["přemýšlel", "thinking"],
["starej", "old"],
["vítej", "welcome"],
["nemyslel", "thought"],
["zapomenout", "forget"],
["kruci", "Heck"],
["poznávám", "to meet"],
["poté", "thereafter"],
["baby", "baby"],
["kanceláře", "office"],
["žil", "lived"],
["přijdeš", "will come"],
["ulice", "street"],
["škola", "school"],
["sice", "Although"],
["dostanete", "get"],
["kecy", "crap"],
["přání", "washing"],
["nějakého", "some"],
["baru", "bar"],
["mluvila", "she spoke"],
["bydlí", "lives"],
["pochopit", "understand"],
["bacha", "bacha"],
["ou", "ou"],
["znamení", "sign"],
["wow", "wow"],
["vyhrát", "win"],
["pospěš", "hurry"],
["tihle", "these"],
["sto", "hundred"],
["psát", "write"],
["mámu", "mom"],
["boj", "combat"],
["útok", "attack"],
["utekl", "fled"],
["válku", "war"],
["poznat", "know"],
["znal", "knew"],
["vrátíme", "return"],
["otcem", "father"],
["moct", "able"],
["milá", "dear"],
["bavit", "entertain"],
["pojd", "Come"],
["věku", "age"],
["soud", "court"],
["julie", "Julia"],
["jinýho", "else"],
["znát", "know"],
["p", "p"],
["stala", "became"],
["nedokážu", "I can not"],
["strany", "sides"],
["přijdou", "they come"],
["metrů", "m"],
["přeložil", "translated"],
["blíží", "approaching"],
["plány", "FALSE"],
["nemohli", "could not"],
["stává", "juice"],
["matko", "Mother"],
["střílet", "shoot"],
["šílený", "crazy"],
["podívejme", "look"],
["matce", "mother"],
["účet", "account"],
["bojíš", "afraid of"],
["ptal", "he asked"],
["jazyk", "language"],
["výběr", "choice"],
["většinou", "mostly"],
["nádhera", "splendor"],
["jiným", "other"],
["maso", "meat"],
["začátek", "beginning"],
["začalo", "started"],
["setkání", "meeting"],
["r", "r"],
["hrozné", "bad"],
["stopy", "tracks"],
["zůstanu", "stay"],
["zmizel", "disappeared"],
["utíkej", "run"],
["dokážu", "I can"],
["paráda", "great"],
["zabila", "killed"],
["hudbu", "music"],
["slibuji", "I promise"],
["zbavit", "deprive"],
["zvířata", "animals"],
["blbost", "crap"],
["sotva", "barely"],
["srdci", "heart"],
["přines", "bring"],
["agent", "agent"],
["skončila", "ended"],
["zajímalo", "interested"],
["stavu", "state"],
["neuvěřitelné", "incredibly"],
["vypadnout", "fall out"],
["překlad", "translation"],
["kterej", "who's"],
["pokaždé", "always"],
["neumím", "I can not"],
["dávám", "I give"],
["jerry", "jerry"],
["vrátila", "returned"],
["okna", "window"],
["zábava", "entertainment"],
["sarah", "sarah"],
["něčem", "something"],
["obličej", "face"],
["vítězství", "victory"],
["stačilo", "enough"],
["zdi", "wall"],
["přeci", "after all"],
["starost", "concern"],
["měly", "should"],
["paule", "Paul"],
["um", "um"],
["doprdele", "hell"],
["denně", "daily"],
["ukradl", "stolen"],
["vezmeme", "taking"],
["skutečný", "real"],
["pěti", "five"],
["kéž", "I wish"],
["nohu", "leg"],
["pověz", "tell"],
["prsten", "ring"],
["každém", "each"],
["části", "section"],
["místní", "local"],
["promluvíme", "talk"],
["večeře", "dinner"],
["předpokládám", "I suppose"],
["umřel", "died"],
["vším", "all"],
["nemusím", "do not have to"],
["poručíku", "Lieutenant"],
["zvuk", "sound"],
["hrdina", "hero"],
["zavolal", "call"],
["odjet", "leave"],
["polož", "put"],
["zbraní", "weapons"],
["víkend", "weekend"],
["akce", "action"],
["chovat", "breed"],
["vláda", "government"],
["jist", "eat"],
["takto", "thus"],
["píše", "writes"],
["životy", "lives"],
["nádherné", "wonderful"],
["vzpomínám", "I remember"],
["profesore", "Professor"],
["zapomněla", "forgot"],
["armáda", "army"],
["hezká", "pretty"],
["vesmíru", "universe"],
["zasranej", "fucking"],
["volala", "she called"],
["seru", "fuck"],
["naděje", "hope"],
["součástí", "part"],
["pít", "drink"],
["letadla", "planes"],
["vítr", "wind"],
["zpívat", "sing"],
["chování", "behaviour"],
["dívku", "girl"],
["řek", "Greek"],
["dovolte", "allow"],
["sestru", "sister"],
["dívej", "watch"],
["nima", "them"],
["potřeba", "need"],
["zdálo", "it seemed"],
["sekund", "seconds"],
["vybrat", "choose"],
["najdi", "find"],
["mámě", "we have"],
["zbývá", "leaves"],
["narodil", "born"],
["výsosti", "highness"],
["navštívit", "visit"],
["plné", "fully"],
["věříš", "trust"],
["najde", "finds"],
["zkuste", "try"],
["dalšího", "further"],
["důležitý", "important"],
["sestry", "nurses"],
["au", "au"],
["krku", "neck"],
["tátu", "dad"],
["požádal", "he asked"],
["nůž", "knife"],
["něčeho", "something"],
["záda", "back"],
["týdnů", "weeks"],
["nehoda", "accident"],
["vojáci", "soldiers"],
["don", "don"],
["pátek", "Friday"],
["kámoš", "friend"],
["vypadáte", "look"],
["uvidíte", "you see"],
["jmenuju", "My name"],
["lidské", "human"],
["kdykoliv", "anytime"],
["něčím", "something"],
["řečeno", "speaking"],
["miku", "miku"],
["zvedni", "pick up"],
["čekají", "waiting for"],
["neviděli", "seen"],
["upřímně", "honestly"],
["obchodu", "trade"],
["samý", "very"],
["beze", "without"],
["ztratili", "lost"],
["několika", "several"],
["aniž", "without"],
["menší", "smaller"],
["jednoduše", "simply"],
["hvězda", "star"],
["vaším", "your"],
["věří", "trusts"],
["pošlete", "send"],
["posaď", "sit down"],
["krk", "neck"],
["končí", "ends"],
["nevypadá", "does not"],
["vybral", "selected"],
["nemocný", "sick"],
["nemožné", "impossible"],
["jejího", "its"],
["pamatuj", "remember"],
["trvalo", "It took"],
["postavit", "build"],
["legraci", "fun"],
];
