 
const french = [
 ["de", "of"],
 ["je", "I"],
 ["est", "East"],
 ["pas", "not"],
 ["le", "the"],
 ["vous", "you"],
 ["la", "the"],
 ["tu", "you"],
 ["que", "than"],
 ["un", "a"],
 ["il", "he"],
 ["et", "and"],
 ["à", "at"],
 ["a", "at"],
 ["ne", "born"],
 ["les", "the"],
 ["ce", "this"],
 ["en", "in"],
 ["on", "we"],
 ["ça", "it"],
 ["une", "a"],
 ["ai", "have"],
 ["pour", "for"],
 ["des", "of the"],
 ["moi", "me"],
 ["qui", "who"],
 ["nous", "we"],
 ["mais", "But"],
 ["y", "there"],
 ["me", "me"],
 ["dans", "in"],
 ["du", "of"],
 ["bien", "well"],
 ["elle", "she"],
 ["si", "if"],
 ["tout", "all"],
 ["plus", "more"],
 ["non", "no"],
 ["mon", "my"],
 ["suis", "am"],
 ["te", "you"],
 ["au", "at"],
 ["avec", "with"],
 ["oui", "Yes"],
 ["va", "go"],
 ["toi", "you"],
 ["fait", "made"],
 ["ils", "they"],
 ["as", "ace"],
 ["être", "be"],
 ["faire", "to do"],
 ["se", "himself"],
 ["comme", "as"],
 ["était", "was"],
 ["sur", "sure"],
 ["quoi", "what"],
 ["ici", "here"],
 ["sais", "know"],
 ["lui", "him"],
 ["veux", "want"],
 ["ma", "my"],
 ["là", "the"],
 ["rien", "nothing"],
 ["dit", "said"],
 ["es", "es"],
 ["où", "or"],
 ["votre", "your"],
 ["pourquoi", "Why"],
 ["sont", "are"],
 ["cette", "this"],
 ["quand", "when"],
 ["par", "by"],
 ["son", "his"],
 ["ton", "your"],
 ["peux", "can"],
 ["alors", "so"],
 ["dire", "say"],
 ["vais", "am going to"],
 ["comment", "How? 'Or' What"],
 ["avez", "have"],
 ["bon", "Well"],
 ["ou", "or"],
 ["très", "very"],
 ["même", "even"],
 ["merci", "thank you"],
 ["ont", "have"],
 ["jamais", "never"],
 ["aussi", "also"],
 ["chose", "thing"],
 ["voir", "see"],
 ["allez", "going"],
 ["tous", "all"],
 ["ces", "these"],
 ["deux", "of them"],
 ["sa", "her"],
 ["faut", "should"],
 ["été", "summer"],
 ["êtes", "are"],
 ["ta", "your"],
 ["avoir", "to have"],
 ["fais", "do"],
 ["peut", "can"],
 ["autre", "other"],
 ["maintenant", "now"],
 ["encore", "again"],
 ["peu", "little"],
 ["vraiment", "really"],
 ["mes", "my"],
 ["temps", "time"],
 ["toujours", "always"],
 ["notre", "our"],
 ["vie", "life"],
 ["oh", "Oh"],
 ["juste", "fair"],
 ["sans", "without"],
 ["avait", "had"],
 ["quelque", "some"],
 ["monde", "world"],
 ["accord", "agreement"],
 ["vu", "seen"],
 ["fois", "time"],
 ["aller", "to go"],
 ["trop", "too much"],
 ["viens", "come"],
 ["crois", "think"],
 ["dois", "have"],
 ["père", "dad"],
 ["dieu", "God"],
 ["homme", "man"],
 ["sûr", "sure"],
 ["aux", "to the"],
 ["leur", "their"],
 ["avant", "before"],
 ["étais", "was"],
 ["besoin", "need"],
 ["femme", "women"],
 ["personne", "no one"],
 ["avais", "had"],
 ["aime", "love"],
 ["chez", "in"],
 ["vrai", "true"],
 ["ans", "years"],
 ["ses", "his"],
 ["mal", "wrong"],
 ["parler", "talk"],
 ["vos", "your"],
 ["après", "after"],
 ["mort", "death"],
 ["ca", "it"],
 ["eu", "had"],
 ["veut", "wants"],
 ["parce", "by"],
 ["sera", "will be"],
 ["mieux", "better"],
 ["bonne", "good"],
 ["petit", "small"],
 ["tes", "your"],
 ["dis", "tell"],
 ["beaucoup", "many"],
 ["monsieur", "gentleman"],
 ["voilà", "here"],
 ["depuis", "since"],
 ["doit", "must"],
 ["mère", "mother"],
 ["quel", "what"],
 ["vas", "going"],
 ["vois", "see"],
 ["fille", "girl"],
 ["déjà", "already"],
 ["gens", "people"],
 ["donc", "so"],
 ["jour", "day"],
 ["ll", "It"],
 ["autres", "other"],
 ["soir", "evening"],
 ["toute", "all"],
 ["ouais", "yeah"],
 ["argent", "silver"],
 ["maison", "House"],
 ["nom", "last name"],
 ["bonjour", "Hello"],
 ["pense", "thought"],
 ["nos", "our"],
 ["cela", "it"],
 ["nuit", "night"],
 ["avons", "have"],
 ["ii", "ii"],
 ["merde", "shit"],
 ["cet", "this"],
 ["papa", "dad"],
 ["maman", "mom"],
 ["reste", "rest"],
 ["peur", "fear"],
 ["désolé", "sorry"],
 ["salut", "Hi"],
 ["seul", "only"],
 ["arrive", "come"],
 ["vite", "quick"],
 ["prendre", "take"],
 ["regarde", "looked"],
 ["soit", "is"],
 ["air", "air"],
 ["quelle", "what"],
 ["passé", "past"],
 ["trois", "three"],
 ["savoir", "know"],
 ["plaît", "please"],
 ["choses", "things"],
 ["fils", "son"],
 ["ah", "ha"],
 ["bas", "low"],
 ["moins", "less"],
 ["entre", "Between"],
 ["passe", "past"],
 ["hé", "Hey"],
 ["demain", "tomorrow"],
 ["appelle", "call"],
 ["grand", "tall"],
 ["tête", "head"],
 ["voulez", "want"],
 ["faites", "make"],
 ["arrête", "stopped"],
 ["hein", "huh"],
 ["attends", "hold on"],
 ["raison", "reason"],
 ["enfants", "children"],
 ["assez", "enough"],
 ["aurais", "would"],
 ["elles", "they"],
 ["voulais", "wanted"],
 ["sommes", "are"],
 ["jours", "days"],
 ["parle", "speak"],
 ["moment", "moment"],
 ["amour", "love"],
 ["toutes", "all"],
 ["heure", "hour"],
 ["puis", "then"],
 ["tard", "late"],
 ["tuer", "kill"],
 ["eh", "eh"],
 ["dû", "of"],
 ["ami", "friend"],
 ["petite", "small"],
 ["partir", "go"],
 ["hommes", "men"],
 ["connais", "know"],
 ["aider", "help"],
 ["savez", "know"],
 ["gars", "guys"],
 ["chance", "luck"],
 ["combien", "how much"],
 ["tant", "so"],
 ["sait", "know"],
 ["part", "go"],
 ["voiture", "car"],
 ["pris", "taken"],
 ["problème", "problem"],
 ["hui", "hui"],
 ["coup", "stroke"],
 ["porte", "door"],
 ["serait", "would be"],
 ["prends", "take"],
 ["venir", "come"],
 ["travail", "job"],
 ["pu", "could"],
 ["famille", "family"],
 ["seule", "only"],
 ["sens", "meaning"],
 ["allons", "let's go"],
 ["putain", "whore"],
 ["idée", "idea"],
 ["ni", "or"],
 ["contre", "against"],
 ["revoir", "meet again"],
 ["entendu", "heard"],
 ["comprends", "understand"],
 ["passer", "pass"],
 ["pendant", "while"],
 ["trouvé", "find"],
 ["trouver", "find"],
 ["quelques", "a few"],
 ["vient", "just"],
 ["vieux", "old"],
 ["aurait", "would have"],
 ["attention", "Warning"],
 ["demande", "request"],
 ["chercher", "look for"],
 ["sous", "under"],
 ["pouvez", "can"],
 ["voici", "here is"],
 ["pourrait", "could"],
 ["sang", "blood"],
 ["histoire", "history"],
 ["amis", "friends"],
 ["sortir", "go out"],
 ["question", "question"],
 ["venez", "come"],
 ["rester", "stay"],
 ["frère", "brother"],
 ["ville", "city"],
 ["fini", "finished"],
 ["nouveau", "new"],
 ["eux", "them"],
 ["truc", "thing"],
 ["tiens", "here"],
 ["yeux", "eyes"],
 ["mois", "month"],
 ["laisse", "leash"],
 ["mec", "guy"],
 ["longtemps", "long time"],
 ["belle", "pretty"],
 ["police", "police"],
 ["seulement", "only"],
 ["importe", "imported"],
 ["heures", "hours"],
 ["eau", "water"],
 ["car", "because"],
 ["super", "Great"],
 ["chaque", "each"],
 ["cas", "case"],
 ["vont", "will"],
 ["tué", "kill"],
 ["terre", "Earth"],
 ["place", "square"],
 ["main", "hand"],
 ["ensemble", "together"],
 ["type", "type"],
 ["beau", "beautiful"],
 ["pardon", "sorry"],
 ["vers", "towards"],
 ["aucun", "no"],
 ["guerre", "war"],
 ["trouve", "find"],
 ["partie", "part"],
 ["suite", "after"],
 ["prie", "pray"],
 ["devant", "in front of"],
 ["compris", "including"],
 ["arrivé", "come"],
 ["mme", "Mrs"],
 ["leurs", "their"],
 ["étaient", "were"],
 ["mettre", "to put"],
 ["matin", "morning"],
 ["aide", "help"],
 ["dessus", "above"],
 ["sois", "be"],
 ["genre", "kind"],
 ["fin", "end"],
 ["perdu", "lost"],
 ["jeune", "young"],
 ["chérie", "sweetheart"],
 ["premier", "first"],
 ["attendez", "Wait"],
 ["enfant", "child"],
 ["donne", "given"],
 ["venu", "came"],
 ["aimerais", "would like to"],
 ["droit", "law"],
 ["côté", "side"],
 ["chambre", "bedroom"],
 ["loin", "far"],
 ["donner", "give"],
 ["devrais", "should"],
 ["laisser", "let"],
 ["feu", "fire"],
 ["jouer", "to play"],
 ["ie", "ie"],
 ["train", "train"],
 ["gros", "large"],
 ["compte", "account"],
 ["savais", "knew"],
 ["mourir", "pass away"],
 ["pouvoir", "power"],
 ["regardez", "look"],
 ["parlé", "speak"],
 ["donné", "given"],
 ["première", "first"],
 ["aura", "will have"],
 ["dernière", "latest"],
 ["minutes", "minutes"],
 ["aucune", "any"],
 ["mari", "husband"],
 ["enfin", "finally"],
 ["madame", "Mrs"],
 ["façon", "way"],
 ["devrait", "should"],
 ["mis", "placed"],
 ["film", "movie"],
 ["femmes", "women"],
 ["fort", "strong"],
 ["pourrais", "could"],
 ["écoute", "listen"],
 ["pays", "country"],
 ["parti", "left"],
 ["affaire", "case"],
 ["endroit", "place"],
 ["corps", "body"],
 ["ia", "ia"],
 ["fou", "crazy"],
 ["vivre", "live"],
 ["prêt", "ready"],
 ["dont", "whose"],
 ["espère", "hope"],
 ["grande", "big"],
 ["cause", "cause"],
 ["point", "point"],
 ["filles", "girls"],
 ["dehors", "outside"],
 ["hier", "yesterday"],
 ["boulot", "job"],
 ["pensais", "thought"],
 ["garçon", "boy"],
 ["près", "near"],
 ["désolée", "sorry"],
 ["cinq", "five"],
 ["chef", "chief"],
 ["ainsi", "so"],
 ["haut", "high"],
 ["celui", "the one"],
 ["demandé", "request"],
 ["dirait", "would say"],
 ["bébé", "baby"],
 ["possible", "possible"],
 ["école", "school"],
 ["plein", "full"],
 ["mains", "hands"],
 ["années", "years"],
 ["dites", "say"],
 ["nouvelle", "news"],
 ["manger", "eat"],
 ["docteur", "doctor"],
 ["tour", "tower"],
 ["croire", "believe"],
 ["ceux", "those"],
 ["quatre", "four"],
 ["plutôt", "rather"],
 ["marche", "market"],
 ["semaine", "week"],
 ["vérité", "truth"],
 ["envie", "desire"],
 ["capitaine", "captain"],
 ["arrêter", "Stop"],
 ["affaires", "business"],
 ["bientôt", "soon"],
 ["vue", "view"],
 ["demander", "request"],
 ["dernier", "latest"],
 ["instant", "moment"],
 ["essaie", "try"],
 ["arriver", "arrive"],
 ["font", "make"],
 ["tellement", "so much"],
 ["derrière", "behind"],
 ["tomber", "fall"],
 ["presque", "almost"],
 ["voulait", "wanted to"],
 ["meilleur", "better"],
 ["numéro", "number"],
 ["dr", "dr"],
 ["journée", "day"],
 ["appeler", "call"],
 ["dollars", "dollars"],
 ["c", "vs"],
 ["attendre", "wait"],
 ["confiance", "trust"],
 ["garde", "keep"],
 ["souviens", "remember"],
 ["dur", "hard"],
 ["serai", "will"],
 ["bureau", "office"],
 ["voyez", "see"],
 ["abord", "on board"],
 ["important", "important"],
 ["devez", "must"],
 ["ben", "ben"],
 ["peine", "trouble"],
 ["cours", "Classes"],
 ["fera", "will"],
 ["prend", "take"],
 ["seigneur", "Lord"],
 ["suffit", "enough"],
 ["route", "road"],
 ["cul", "ass"],
 ["lls", "They"],
 ["minute", "minute"],
 ["bonsoir", "Good evening"],
 ["jeu", "Game"],
 ["croyais", "thought"],
 ["ferme", "closed"],
 ["plaisir", "pleasure"],
 ["voudrais", "would like"],
 ["heureux", "happy"],
 ["mot", "word"],
 ["musique", "music"],
 ["chien", "dog"],
 ["messieurs", "gentlemen"],
 ["prenez", "take"],
 ["calme", "calm"],
 ["parents", "parents"],
 ["dedans", "in"],
 ["fous", "crazy"],
 ["arrêtez", "stop"],
 ["mariage", "wedding"],
 ["entrer", "enter"],
 ["rentrer", "return"],
 ["ait", "has"],
 ["lit", "bed"],
 ["voit", "sees"],
 ["autant", "as much"],
 ["reviens", "come back"],
 ["parfait", "perfect"],
 ["coeur", "heart"],
 ["ceci", "this"],
 ["service", "service"],
 ["téléphone", "phone"],
 ["pauvre", "poor"],
 ["mlle", "Ms"],
 ["attend", "waits"],
 ["drôle", "funny"],
 ["ira", "will"],
 ["parfois", "sometimes"],
 ["retour", "return"],
 ["á", "at"],
 ["verre", "glass"],
 ["pensé", "thought"],
 ["six", "six"],
 ["ci", "this"],
 ["impossible", "impossible"],
 ["ferai", "will"],
 ["aimes", "love"],
 ["payer", "pay"],
 ["facile", "easy"],
 ["maître", "master"],
 ["new", "new"],
 ["appelé", "called"],
 ["mauvais", "bad"],
 ["doute", "doubt"],
 ["prison", "jail"],
 ["adore", "love"],
 ["faute", "fault"],
 ["entends", "hear"],
 ["oublié", "forget it"],
 ["bras", "arms"],
 ["exactement", "exactly"],
 ["fête", "Party"],
 ["café", "coffee"],
 ["chéri", "Darling"],
 ["sors", "go outside"],
 ["gentil", "kind"],
 ["penser", "think"],
 ["vaut", "worth"],
 ["lieu", "location"],
 ["malade", "sick"],
 ["changer", "switch"],
 ["roi", "King"],
 ["commence", "start"],
 ["entendre", "hear"],
 ["président", "President"],
 ["travailler", "to work"],
 ["partout", "all over"],
 ["cher", "expensive"],
 ["morts", "dead"],
 ["rendre", "return"],
 ["écrit", "written"],
 ["équipe", "team"],
 ["joue", "play"],
 ["sinon", "if not"],
 ["esprit", "mind"],
 ["regarder", "watch"],
 ["rentre", "returns"],
 ["plan", "plan"],
 ["cœur", "heart"],
 ["veulent", "want"],
 ["montrer", "to show"],
 ["voulu", "desired"],
 ["boire", "to drink"],
 ["travaille", "work"],
 ["propre", "clean"],
 ["année", "year"],
 ["état", "state"],
 ["soyez", "are"],
 ["bois", "wood"],
 ["cherche", "looking"],
 ["laissé", "leash"],
 ["essayer", "try"],
 ["dès", "from"],
 ["semble", "seems"],
 ["dix", "ten"],
 ["faisait", "was"],
 ["génial", "awesome"],
 ["penses", "think"],
 ["sécurité", "security"],
 ["tôt", "early"],
 ["mets", "dish"],
 ["rêve", "dream"],
 ["armée", "army"],
 ["perdre", "to lose"],
 ["parles", "talk"],
 ["avis", "view"],
 ["surtout", "mostly"],
 ["difficile", "difficult"],
 ["york", "york"],
 ["dormir", "to sleep"],
 ["ensuite", "then"],
 ["pire", "worst"],
 ["ecoute", "listen"],
 ["simple", "simple"],
 ["allait", "was going to"],
 ["paix", "peace"],
 ["morte", "dead woman"],
 ["arme", "armed"],
 ["sujet", "topic"],
 ["retard", "delay"],
 ["voyons", "see"],
 ["livre", "delivered"],
 ["appris", "learned"],
 ["peuvent", "can"],
 ["sale", "dirty"],
 ["serais", "would"],
 ["souvent", "often"],
 ["an", "year"],
 ["sauf", "except"],
 ["choix", "choice"],
 ["sûrement", "surely"],
 ["étiez", "were"],
 ["or", "gold"],
 ["visage", "face"],
 ["ordre", "order"],
 ["comprendre", "understand"],
 ["essayé", "tried"],
 ["noir", "black"],
 ["dîner", "having dinner"],
 ["âge", "age"],
 ["chemin", "path"],
 ["changé", "exchange"],
 ["bout", "end"],
 ["face", "face"],
 ["rue", "street"],
 ["inquiète", "worry"],
 ["photo", "Photo"],
 ["allé", "go"],
 ["personnes", "people"],
 ["sérieux", "serious"],
 ["ciel", "sky"],
 ["honneur", "honor"],
 ["amie", "friend"],
 ["questions", "Questions"],
 ["force", "strength"],
 ["garder", "keep"],
 ["petits", "small"],
 ["tirer", "shoot"],
 ["millions", "million"],
 ["grave", "serious"],
 ["marché", "market"],
 ["nouvelles", "news"],
 ["voix", "voice"],
 ["semaines", "weeks"],
 ["pouvais", "could"],
 ["courant", "current"],
 ["propos", "about"],
 ["bateau", "boat"],
 ["oublie", "forget it"],
 ["con", "cunt"],
 ["celle", "that"],
 ["gauche", "left"],
 ["content", "happy"],
 ["prix", "price"],
 ["rouge", "red"],
 ["faim", "hunger"],
 ["ferais", "would"],
 ["avion", "plane"],
 ["devenir", "to become"],
 ["devoir", "duty"],
 ["prochaine", "next"],
 ["restez", "stay"],
 ["acheter", "buy"],
 ["voyage", "trip"],
 ["sorte", "kind"],
 ["long", "long"],
 ["espèce", "species"],
 ["idiot", "idiot"],
 ["gueule", "mouth"],
 ["début", "beginning"],
 ["bouge", "moves"],
 ["continue", "keep on going"],
 ["hôpital", "hospital"],
 ["sort", "fate"],
 ["grâce", "grace"],
 ["problèmes", "problems"],
 ["message", "message"],
 ["certains", "some"],
 ["patron", "boss"],
 ["sûre", "safe"],
 ["reçu", "received"],
 ["trucs", "stuff"],
 ["avaient", "had"],
 ["ouvre", "opens"],
 ["promis", "promised"],
 ["the", "tea"],
 ["oncle", "uncle"],
 ["euh", "uh"],
 ["connaissez", "know"],
 ["laissez", "leave"],
 ["devons", "must"],
 ["bienvenue", "welcome"],
 ["occupe", "busy"],
 ["allais", "going"],
 ["camp", "camp"],
 ["manque", "lack"],
 ["soleil", "Sun"],
 ["devait", "was"],
 ["pars", "leave"],
 ["pouvait", "could"],
 ["cheveux", "hair"],
 ["armes", "arms"],
 ["pensez", "think"],
 ["salle", "room"],
 ["croyez", "believe"],
 ["bizarre", "weird"],
 ["gagner", "to win"],
 ["commencé", "start"],
 ["fond", "background"],
 ["sauver", "to save"],
 ["pièce", "room"],
 ["erreur", "mistake"],
 ["ailleurs", "elsewhere"],
 ["rapport", "report"],
 ["froid", "cold"],
 ["apprendre", "learn"],
 ["scène", "scene"],
 ["secret", "secret"],
 ["sac", "bag"],
 ["seconde", "second"],
 ["cru", "vintage"],
 ["allô", "Hello"],
 ["revenir", "return"],
 ["battre", "beat"],
 ["hôtel", "hotel"],
 ["soirée", "evening"],
 ["aurai", "have"],
 ["soeur", "sister"],
 ["pieds", "feet"],
 ["seras", "shalt"],
 ["carte", "menu"],
 ["jolie", "pretty one"],
 ["n", "not"],
 ["pied", "foot"],
 ["groupe", "group"],
 ["venue", "arrival"],
 ["monte", "mounted"],
 ["agent", "agent"],
 ["fallait", "needed"],
 ["effet", "effect"],
 ["libre", "free"],
 ["seront", "will"],
 ["mots", "words"],
 ["neuf", "new"],
 ["tire", "drawn"],
 ["faux", "false"],
 ["situation", "situation"],
 ["tue", "kill"],
 ["lumière", "light"],
 ["vieille", "old"],
 ["droite", "right"],
 ["debout", "standing"],
 ["noël", "Christmas"],
 ["cheval", "horse"],
 ["intérieur", "inside"],
 ["écoutez", "Listen"],
 ["joli", "pretty"],
 ["gagné", "won"],
 ["loi", "law"],
 ["entrez", "Come in"],
 ["auras", "get"],
 ["incroyable", "unbelievable"],
 ["lettre", "letter"],
 ["présent", "present"],
 ["occuper", "to occupy"],
 ["connaît", "knows"],
 ["absolument", "absolutely"],
 ["aviez", "had"],
 ["dame", "lady"],
 ["professeur", "professor"],
 ["fric", "money"],
 ["george", "george"],
 ["retrouver", "find"],
 ["coin", "corner"],
 ["table", "table"],
 ["colonel", "colonel"],
 ["âme", "soul"],
 ["dos", "back"],
 ["magnifique", "magnificent"],
 ["rencontrer", "meet"],
 ["réussi", "success"],
 ["meilleure", "best"],
 ["rappelle", "remember"],
 ["tranquille", "quiet"],
 ["fut", "was"],
 ["chaud", "hot"],
 ["mr", "mr"],
 ["commencer", "to start"],
 ["sœur", "sister"],
 ["agit", "is"],
 ["cool", "cool"],
 ["doucement", "slowly"],
 ["pareil", "the same"],
 ["jeunes", "youth"],
 ["joe", "joe"],
 ["accident", "accident"],
 ["appel", "call"],
 ["anniversaire", "anniversary"],
 ["blanc", "White"],
 ["finir", "finish"],
 ["risque", "risk"],
 ["doivent", "have to"],
 ["moyen", "way"],
 ["terminé", "finished"],
 ["complètement", "completely"],
 ["clair", "clear"],
 ["meurtre", "murder"],
 ["sam", "sat"],
 ["parlez", "speak"],
 ["heureuse", "happy"],
 ["ordres", "orders"],
 ["disais", "said"],
 ["touche", "touch"],
 ["frank", "frank"],
 ["prêts", "loans"],
 ["fasse", "make"],
 ["puisse", "can"],
 ["déjeuner", "lunch"],
 ["envoyé", "sent"],
 ["lire", "read"],
 ["disait", "said"],
 ["tombe", "grave"],
 ["su", "knew"],
 ["marcher", "walk"],
 ["avance", "advanced"],
 ["déteste", "hated"],
 ["forme", "form"],
 ["â", "at"],
 ["mauvaise", "bad"],
 ["bord", "edge"],
 ["décidé", "decided"],
 ["mer", "sea"],
 ["vivant", "living"],
 ["médecin", "doctor"],
 ["midi", "midday"],
 ["devenu", "become"],
 ["montre", "watch"],
 ["porter", "carry"],
 ["vraie", "real"],
 ["disent", "say"],
 ["ferait", "would do"],
 ["charlie", "charlie"],
 ["connaître", "know"],
 ["silence", "silence"],
 ["diable", "Devil"],
 ["sortez", "get out"],
 ["tom", "tom"],
 ["cadeau", "gift"],
 ["suppose", "Assumed"],
 ["flics", "cops"],
 ["avocat", "lawyer"],
 ["jure", "sworn"],
 ["anglais", "English"],
 ["sept", "seven"],
 ["devriez", "should"],
 ["moitié", "half"],
 ["aimé", "love"],
 ["surprise", "surprise"],
 ["chacun", "each"],
 ["serez", "will"],
 ["exact", "exact"],
 ["commandant", "commanding officer"],
 ["télé", "TV"],
 ["autour", "around"],
 ["disparu", "faded away"],
 ["ligne", "line"],
 ["expliquer", "explain"],
 ["aimer", "like"],
 ["arrivée", "arrival"],
 ["grosse", "big"],
 ["simplement", "simply"],
 ["mission", "mission"],
 ["monter", "ascend"],
 ["tenir", "hold"],
 ["bons", "good"],
 ["balle", "ball"],
 ["quitter", "to leave"],
 ["selon", "according to"],
 ["classe", "class"],
 ["paris", "Paris"],
 ["sorti", "got out"],
 ["mange", "eat"],
 ["peuple", "people"],
 ["habitude", "habit"],
 ["voie", "way"],
 ["dangereux", "dangerous"],
 ["pote", "mate"],
 ["contrôle", "control"],
 ["prête", "ready"],
 ["honte", "shame"],
 ["rencontré", "meet"],
 ["photos", "Pictures"],
 ["impression", "impression"],
 ["folle", "crazy woman"],
 ["écrire", "to write"],
 ["suivre", "to follow"],
 ["oublier", "forget"],
 ["livres", "books"],
 ["aille", "go"],
 ["retourner", "return"],
 ["offre", "offer"],
 ["chanson", "song"],
 ["envoie", "send"],
 ["trou", "hole"],
 ["arrière", "back"],
 ["poste", "post"],
 ["amérique", "America"],
 ["huit", "eight"],
 ["radio", "radio"],
 ["paul", "paul"],
 ["ressemble", "looks like"],
 ["attaque", "attack"],
 ["arrêté", "stopped"],
 ["change", "exchange"],
 ["baiser", "kiss"],
 ["pourtant", "However"],
 ["réponse", "reply"],
 ["connu", "known"],
 ["connard", "shithead"],
 ["lu", "read"],
 ["pute", "bitch"],
 ["bande", "bandaged"],
 ["enfer", "hell"],
 ["tenez", "hold"],
 ["rend", "makes"],
 ["triste", "sad"],
 ["tel", "Phone"],
 ["bravo", "well done"],
 ["etre", "be"],
 ["savait", "knew"],
 ["david", "david"],
 ["plusieurs", "many"],
 ["existe", "exist"],
 ["met", "puts"],
 ["rire", "to laugh"],
 ["compagnie", "company"],
 ["étrange", "strange"],
 ["exemple", "example"],
 ["devais", "had"],
 ["vit", "lives"],
 ["combat", "fight"],
 ["secours", "help"],
 ["aurez", "will"],
 ["conneries", "bullshit"],
 ["visite", "visit"],
 ["joué", "play"],
 ["michael", "michael"],
 ["pourra", "will"],
 ["coucher", "sleep"],
 ["imagine", "conceived"],
 ["bob", "bob"],
 ["merveilleux", "wonderful"],
 ["continuer", "Continue"],
 ["ecoutez", "Listen"],
 ["dirai", "tell"],
 ["volé", "Fly"],
 ["lune", "Moon"],
 ["bouche", "mouth"],
 ["sud", "South"],
 ["danse", "dance"],
 ["ennuis", "trouble"],
 ["but", "goal"],
 ["aie", "Ouch"],
 ["hors", "except"],
 ["sortie", "exit"],
 ["boîte", "box"],
 ["vol", "flight"],
 ["public", "public"],
 ["lieutenant", "lieutenant"],
 ["écouter", "listen"],
 ["présente", "present"],
 ["système", "system"],
 ["époque", "time"],
 ["retourne", "return"],
 ["certain", "certain"],
 ["bête", "stupid"],
 ["vendre", "sell"],
 ["avenir", "to come up"],
 ["grands", "great"],
 ["coups", "shots"],
 ["santé", "health"],
 ["partez", "leave"],
 ["amoureux", "lover"],
 ["envoyer", "to send"],
 ["cuisine", "cooked"],
 ["normal", "normal"],
 ["danger", "danger"],
 ["gouvernement", "government"],
 ["village", "town"],
 ["poser", "to pose"],
 ["ouvrir", "to open"],
 ["journal", "newspaper"],
 ["approche", "approach"],
 ["faudra", "will"],
 ["dommage", "pity"],
 ["peau", "skin"],
 ["pleine", "full"],
 ["voler", "steal"],
 ["nez", "nose"],
 ["danser", "dance"],
 ["servir", "to serve"],
 ["sympa", "friendly"],
 ["bonnes", "good"],
 ["mille", "thousand"],
 ["héros", "hero"],
 ["banque", "bank"],
 ["sergent", "sergeant"],
 ["clé", "key"],
 ["secondes", "seconds"],
 ["nord", "North"],
 ["inspecteur", "inspector"],
 ["hey", "hey"],
 ["liberté", "freedom"],
 ["salaud", "bastard"],
 ["plait", "please"],
 ["cour", "court"],
 ["juge", "judge"],
 ["viennent", "are coming"],
 ["bruit", "noise"],
 ["flic", "cop"],
 ["tient", "is holding"],
 ["terrible", "terrible"],
 ["paraît", "seems"],
 ["crime", "crime"],
 ["prochain", "next"],
 ["pouvons", "can"],
 ["assis", "seated"],
 ["thé", "tea"],
 ["bonheur", "happiness"],
 ["payé", "paid"],
 ["tas", "heap"],
 ["travers", "through"],
 ["stupide", "stupid"],
 ["blague", "joke"],
 ["préfère", "prefer"],
 ["conseil", "advice"],
 ["robe", "dress"],
 ["tiré", "drawn"],
 ["protéger", "protect"],
 ["rêves", "dreams"],
 ["seuls", "only"],
 ["pitié", "pity"],
 ["oeil", "eye"],
 ["mêmes", "same"],
 ["vin", "wine"],
 ["avions", "had"],
 ["don", "Don"],
 ["sol", "ground"],
 ["vent", "wind"],
 ["club", "club"],
 ["garçons", "boys"],
 ["gamin", "kid"],
 ["tante", "aunt"],
 ["croit", "believes"],
 ["mesdames", "ladies"],
 ["bar", "bar"],
 ["milieu", "middle"],
 ["reine", "Queen"],
 ["signe", "sign"],
 ["centre", "center"],
 ["probablement", "probably"],
 ["bière", "beer"],
 ["dingue", "crazy"],
 ["inutile", "useless"],
 ["nulle", "nothing"],
 ["mike", "mike"],
 ["sent", "feels"],
 ["différent", "different"],
 ["emmener", "bring"],
 ["comprenez", "understand"],
 ["verra", "will"],
 ["prise", "taking"],
 ["vêtements", "clothing"],
 ["liste", "listing"],
 ["savent", "know"],
 ["unis", "United"],
 ["société", "society"],
 ["chère", "Dear"],
 ["soin", "care"],
 ["pierre", "Pierre"],
 ["appelez", "call"],
 ["utiliser", "use"],
 ["acheté", "bought"],
 ["laquelle", "which"],
 ["fiche", "plug"],
 ["parole", "speech"],
 ["mecs", "guys"],
 ["faisais", "doing"],
 ["marier", "marry"],
 ["départ", "departure"],
 ["ennemi", "enemy"],
 ["irai", "go"],
 ["aimez", "like"],
 ["spectacle", "show"],
 ["vouloir", "want to"],
 ["recherche", "research"],
 ["devient", "bECOMES"],
 ["choisi", "selected"],
 ["pose", "pose"],
 ["films", "movies"],
 ["intérêt", "interest"],
 ["intéresse", "interested"],
 ["rôle", "role"],
 ["félicitations", "Congratulations"],
 ["descendre", "go down"],
 ["harry", "harry"],
 ["tourne", "turned"],
 ["position", "position"],
 ["sert", "serves"],
 ["blessé", "injured"],
 ["humain", "human"],
 ["asseoir", "Sit"],
 ["match", "match"],
 ["coupable", "guilty"],
 ["environ", "about"],
 ["art", "art"],
 ["mise", "setting"],
 ["londres", "London"],
 ["espoir", "hope"],
 ["quitté", "quits"],
 ["lequel", "which"],
 ["mur", "wall"],
 ["peter", "to fart"],
 ["ouvert", "open"],
 ["église", "church"],
 ["salope", "slut"],
 ["beauté", "beauty"],
 ["lâche", "loose"],
 ["adresse", "address"],
 ["mademoiselle", "miss"],
 ["petites", "small"],
 ["sauter", "jump"],
 ["colère", "anger"],
 ["directeur", "director"],
 ["adieu", "farewell"],
 ["jimmy", "jimmy"],
 ["faisons", "do"],
 ["parie", "bet"],
 ["entrée", "Entrance"],
 ["tort", "wrong"],
 ["conduire", "drive"],
 ["américain", "American"],
 ["revenu", "returned"],
 ["justice", "justice"],
 ["soldat", "soldier"],
 ["expérience", "experience"],
 ["auriez", "would"],
 ["cerveau", "brain"],
 ["fenêtre", "window"],
 ["quartier", "district"],
 ["prince", "prince"],
 ["vis", "screw"],
 ["promets", "promise"],
 ["venus", "Venus"],
 ["soldats", "soldiers"],
 ["tombé", "grave"],
 ["riche", "rich"],
 ["fleurs", "flowers"],
 ["bill", "bill"],
 ["mary", "mary"],
 ["œil", "eye"],
 ["présenter", "present"],
 ["presse", "hurry"],
 ["frères", "brothers"],
 ["ridicule", "ridiculous"],
 ["preuve", "evidence"],
 ["ouvrez", "open"],
 ["revient", "come back"],
 ["pourriez", "might"],
 ["épouser", "marry"],
 ["intéressant", "interesting"],
 ["gosse", "kid"],
 ["faudrait", "should"],
 ["histoires", "stories"],
 ["rose", "pink"],
 ["veuillez", "please"],
 ["nature", "nature"],
 ["vide", "empty"],
 ["responsable", "responsible"],
 ["courage", "courage"],
 ["capable", "able"],
 ["cinéma", "cinema"],
 ["max", "max"],
 ["décision", "decision"],
 ["taxi", "Taxi"],
 ["chanter", "sing"],
 ["excuse", "excuse"],
 ["sentir", "feel"],
 ["jim", "jim"],
 ["portes", "doors"],
 ["james", "james"],
 ["fier", "proud"],
 ["deuxième", "second"],
 ["eiie", "eiie"],
 ["appartement", "apartment"],
 ["contact", "contact"],
 ["essayez", "try"],
 ["sauvé", "Safe"],
 ["cacher", "hide"],
 ["ià", "ià"],
 ["répondre", "reply"],
 ["manière", "way"],
 ["aimais", "liked"],
 ["jambes", "legs"],
 ["occasion", "opportunity"],
 ["défense", "defense"],
 ["longue", "long"],
 ["jésus", "Jesus"],
 ["jeter", "throw"],
 ["allée", "driveway"],
 ["formidable", "wonderful"],
 ["base", "based"],
 ["telle", "such"],
 ["marie", "married"],
 ["san", "san"],
 ["glace", "ice cream"],
 ["dents", "teeth"],
 ["parmi", "among"],
 ["immédiatement", "at once"],
 ["marié", "married"],
 ["paie", "pay"],
 ["nul", "no"],
 ["vacances", "vacation"],
 ["épouse", "wife"],
 ["monstre", "monster"],
 ["souvenir", "memory"],
 ["tueur", "killer"],
 ["né", "born"],
 ["continuez", "go on"],
 ["français", "French"],
 ["rendu", "made"],
 ["course", "race"],
 ["majesté", "majesty"],
 ["mien", "mine"],
 ["types", "Types"],
 ["certainement", "certainly"],
 ["coupe", "chopped off"],
 ["ouest", "Where is"],
 ["idées", "ideas"],
 ["gagne", "wins"],
 ["oubliez", "forget"],
 ["chat", "cat"],
 ["ayez", "have"],
 ["trouves", "found"],
 ["dégage", "releases"],
 ["chier", "take a dump"],
 ["ravi", "delighted"],
 ["étions", "were"],
 ["arrivent", "arrive"],
 ["joie", "joy"],
 ["prévu", "planned"],
 ["lorsque", "when"],
 ["superbe", "superb"],
 ["touché", "touch"],
 ["bain", "bath"],
 ["contente", "content"],
 ["horrible", "horrible"],
 ["retrouve", "finds"],
 ["court", "short"],
 ["dérange", "disturbs"],
 ["and", "and"],
 ["bombe", "bomb"],
 ["ramener", "bring back"],
 ["certaines", "some"],
 ["réalité", "reality"],
 ["enquête", "investigation"],
 ["camion", "truck"],
 ["signifie", "means"],
 ["cent", "hundred"],
 ["toucher", "to touch"],
 ["occupé", "busy"],
 ["attendais", "expecting"],
 ["rencontre", "meet"],
 ["excellent", "excellent"],
 ["respect", "respect"],
 ["quitte", "quits"],
 ["tourner", "turn"],
 ["terrain", "ground"],
 ["blanche", "white"],
 ["projet", "project"],
 ["éviter", "to avoid"],
 ["poisson", "fish"],
 ["plupart", "mostly"],
 ["descends", "down"],
 ["joyeux", "happy"],
 ["empêcher", "avoid"],
 ["mariée", "married"],
 ["mangé", "eat"],
 ["envers", "towards"],
 ["ange", "angel"],
 ["meilleurs", "best"],
 ["copine", "girlfriend"],
 ["chaussures", "shoes"],
 ["dossier", "folder"],
 ["règles", "rules"],
 ["dure", "tough"],
 ["animaux", "animals"],
 ["langue", "language"],
 ["américains", "US"],
 ["imbécile", "imbecile"],
 ["chevaux", "horses"],
 ["princesse", "princess"],
 ["zone", "zoned"],
 ["pius", "pius"],
 ["drogue", "drug"],
 ["charge", "charge"],
 ["nourriture", "food"],
 ["pont", "bridge"],
 ["refuse", "refuse"],
 ["chiens", "dogs"],
 ["contraire", "opposite"],
 ["enchanté", "nice to meet you"],
 ["douleur", "pain"],
 ["politique", "politics"],
 ["faits", "facts"],
 ["arrivera", "to arrive at"],
 ["essaye", "try"],
 ["magasin", "shop"],
 ["soient", "are"],
 ["dirais", "say"],
 ["entier", "full"],
 ["vécu", "lived"],
 ["offrir", "to offer"],
 ["chapeau", "hat"],
 ["raconte", "recounts"],
 ["cartes", "cards"],
 ["discuter", "discuss"],
 ["papier", "paper"],
 ["action", "action"],
 ["permis", "allowed"],
 ["bu", "drank"],
 ["rapide", "fast"],
 ["shérif", "sheriff"],
 ["frais", "fresh"],
 ["partis", "gone"],
 ["emmène", "takes"],
 ["réunion", "meeting"],
 ["mettez", "put"],
 ["île", "Isle"],
 ["toilettes", "bathroom"],
 ["code", "coded"],
 ["billy", "billy"],
 ["opération", "surgery"],
 ["spécial", "special"],
 ["planète", "planet"],
 ["viendra", "will come"],
 ["champ", "field"],
 ["couleur", "color"],
 ["pain", "bread"],
 ["excuser", "excuse"],
 ["destin", "destiny"],
 ["rends", "thank"],
 ["découvert", "discovered"],
 ["puisque", "since"],
 ["taille", "cut"],
 ["nick", "nick"],
 ["tony", "tony"],
 ["vaisseau", "vessel"],
 ["sexe", "sex"],
 ["sacré", "sacred"],
 ["repas", "meal"],
 ["contrat", "contract"],
 ["qu", "that"],
 ["nécessaire", "necessary"],
 ["client", "customer"],
 ["détruire", "destroy"],
 ["lait", "milk"],
 ["iis", "iis"],
 ["faite", "done"],
 ["mémoire", "memory"],
 ["pleurer", "cry"],
 ["copain", "boyfriend"],
 ["miss", "Miss"],
 ["restes", "remains"],
 ["ray", "ray"],
 ["personnel", "staff"],
 ["double", "double"],
 ["mignon", "cute"],
 ["couteau", "knife"],
 ["sache", "know"],
 ["témoin", "witness"],
 ["foi", "faith"],
 ["dors", "sleep"],
 ["remercie", "thank"],
 ["direction", "direction"],
 ["steve", "steve"],
 ["malin", "malignant"],
 ["niveau", "level"],
 ["remettre", "reset"],
 ["habite", "lives"],
 ["apporté", "brought"],
 ["aiment", "like"],
 ["mienne", "mine"],
 ["procès", "trial"],
 ["doux", "soft"],
 ["eddie", "eddie"],
 ["trouvez", "find"],
 ["solution", "solution"],
 ["raconter", "tell"],
 ["fermer", "to close"],
 ["choisir", "to choose"],
 ["goût", "taste"],
 ["nouveaux", "new"],
 ["end", "end"],
 ["amuser", "amuse"],
 ["différence", "difference"],
 ["stop", "stop"],
 ["charles", "charles"],
 ["gosses", "kids"],
 ["réfléchir", "reflect"],
 ["clients", "clients"],
 ["enceinte", "pregnant"],
 ["beaux", "beautiful"],
 ["université", "university"],
 ["bleu", "blue"],
 ["mètres", "meters"],
 ["vus", "seen"],
 ["aimait", "loved"],
 ["marre", "fed up"],
 ["menti", "lied"],
 ["appelles", "call"],
 ["courir", "run"],
 ["arranger", "arrange"],
 ["travaillé", "work"],
 ["papiers", "papers"],
 ["retrouvé", "found"],
 ["officier", "officer"],
 ["espace", "space"],
 ["sourire", "smile"],
 ["dise", "tell"],
 ["mérite", "deserved"],
 ["lettres", "letters"],
 ["accepter", "accept"],
 ["quels", "what"],
 ["failli", "bankrupt"],
 ["angleterre", "England"],
 ["vitesse", "speed"],
 ["jambe", "leg"],
 ["caméra", "camera"],
 ["rappeler", "call back"],
 ["arbre", "tree"],
 ["pièces", "rooms"],
 ["forces", "strengths"],
 ["trésor", "treasure"],
 ["victime", "victim"],
 ["énergie", "energy"],
 ["disons", "say"],
 ["énorme", "huge"],
 ["rentré", "returns"],
 ["alex", "alex"],
 ["appartient", "belongs"],
 ["préparer", "to prepare"],
 ["propres", "own"],
 ["regrette", "sorry"],
 ["finalement", "finally"],
 ["france", "France"],
 ["invité", "guest"],
 ["moindre", "lesser"],
 ["censé", "supposed"],
 ["washington", "Washington"],
 ["bobby", "bobby"],
 ["image", "picture"],
 ["justement", "exactly"],
 ["to", "to"],
 ["compter", "count"],
 ["enlever", "to take off"],
 ["chasse", "hunt"],
 ["unique", "unique"],
 ["fout", "fout"],
 ["arrêt", "stop"],
 ["file", "file"],
 ["balles", "bullets"],
 ["preuves", "evidence"],
 ["dimanche", "Sunday"],
 ["lycée", "high school"],
 ["fil", "wire"],
 ["morceau", "piece"],
 ["noms", "names"],
 ["durant", "during"],
 ["sarah", "sarah"],
 ["cassé", "broken"],
 ["doigts", "fingers"],
 ["vérifier", "check"],
 ["million", "million"],
 ["appareil", "apparatus"],
 ["tirez", "pull"],
 ["apporte", "brings"],
 ["réponds", "answer"],
 ["piste", "track"],
 ["derniers", "last"],
 ["man", "man"],
 ["troisième", "third"],
 ["dépend", "depends"],
 ["humains", "humans"],
 ["programme", "program"],
 ["honnête", "honest"],
 ["voitures", "Car"],
 ["bougez", "move"],
 ["richard", "richard"],
 ["belles", "beautiful"],
 ["régler", "adjust"],
 ["flingue", "gat"],
 ["couper", "cut"],
 ["noire", "black"],
 ["entendez", "hear"],
 ["aveugle", "blinded"],
 ["bouger", "move"],
 ["venait", "had"],
 ["présence", "presence"],
 ["savons", "know"],
 ["crise", "crisis"],
 ["amène", "bring"],
 ["interdit", "prohibited"],
 ["trés", "very"],
 ["lever", "raise"],
 ["partons", "leave"],
 ["clés", "Keywords"],
 ["obtenir", "get"],
 ["pluie", "rain"],
 ["récupérer", "recover"],
 ["grandes", "great"],
 ["quelles", "what"],
 ["prouver", "to prove"],
 ["souris", "mouse"],
 ["restaurant", "restaurant"],
 ["regard", "look"],
 ["okay", "okay"],
 ["intention", "intention"],
 ["forte", "strong"],
 ["danny", "danny"],
 ["cou", "neck"],
 ["points", "points"],
 ["manqué", "lack"],
 ["proche", "close"],
 ["urgence", "emergency"],
 ["folie", "madness"],
 ["ancien", "former"],
 ["relation", "relationship"],
 ["bouteille", "bottle"],
 ["étage", "floor"],
 ["rejoindre", "rejoin"],
 ["casse", "broken"],
 ["jardin", "garden"],
 ["malgré", "despite"],
 ["oiseau", "bird"],
 ["méchant", "mean"],
 ["raisons", "reasons"],
 ["perds", "lose"],
 ["pleure", "cry"],
 ["meurt", "dies"],
 ["claire", "Claire"],
 ["frappé", "hit"],
 ["chante", "sung"],
 ["pourrai", "could"],
 ["nombre", "number"],
 ["gentille", "kind"],
 ["pourras", "able"],
 ["sentiments", "feelings"],
 ["regardé", "looked"],
 ["toit", "roof"],
 ["lors", "then"],
 ["métier", "job"],
 ["maladie", "disease"],
 ["poche", "poached"],
 ["três", "very"],
 ["frapper", "hit"],
 ["tommy", "tommy"],
 ["succès", "success"],
 ["étant", "being"],
 ["lee", "lee"],
 ["dessous", "below"],
 ["voudrait", "would"],
 ["théâtre", "theater"],
 ["chinois", "Chinese"],
 ["crains", "fear"],
 ["afin", "to"],
 ["gare", "station"],
 ["billets", "tickets"],
 ["douce", "fresh"],
 ["frappe", "hit"],
 ["remarqué", "Note"],
 ["paradis", "paradise"],
 ["étranger", "foreign"],
 ["campagne", "campaign"],
 ["fermé", "closed"],
 ["alcool", "alcohol"],
 ["jerry", "jerry"],
 ["vendu", "sold"],
 ["samedi", "Saturday"],
 ["parlait", "speaking"],
 ["produit", "product"],
 ["répète", "say again"],
 ["amoureuse", "in love"],
 ["souhaite", "wish"],
 ["odeur", "odour"],
 ["appelait", "called"],
 ["vôtre", "your"],
 ["attendant", "Meanwhile"],
 ["montagne", "Mountain"],
 ["oû", "or"],
 ["vies", "lives"],
 ["demandez", "ask"],
 ["fantastique", "fantastic"],
 ["victoire", "victory"],
 ["mens", "mens"],
 ["carrière", "career"],
 ["enlève", "removes"],
 ["fatigué", "tired"],
 ["suivi", "followed"],
 ["animal", "animal"],
 ["raté", "missed"],
 ["règle", "rule"],
 ["meurs", "die"],
 ["remercier", "thank"],
 ["assurer", "ensure"],
 ["queue", "tail"],
 ["viande", "meat"],
 ["rivière", "river"],
 ["falloir", "have to"],
 ["suivant", "following"],
 ["assure", "assures"],
 ["obligé", "forced"],
 ["martin", "martin"],
 ["fusil", "musket"],
 ["passage", "passage"],
 ["hasard", "hazard"],
 ["pauvres", "poor"],
 ["neige", "snow"],
 ["parfaitement", "perfectly"],
 ["journaux", "newspapers"],
 ["échapper", "escape"],
 ["plage", "beach"],
 ["secrets", "secrets"],
 ["signal", "signal"],
 ["crétin", "dumbass"],
 ["aies", "hast"],
 ["coffre", "chest"],
 ["pression", "pressure"],
 ["costume", "suit"],
 ["informations", "news"],
 ["futur", "future"],
 ["disant", "saying"],
 ["univers", "universe"],
 ["auraient", "would"],
 ["gardes", "guards"],
 ["lis", "Lily"],
 ["volonté", "will"],
 ["attendu", "expected"],
 ["verras", "see"],
 ["donnez", "give"],
 ["demandais", "asked"],
 ["excuses", "apology"],
 ["vienne", "Vienna"],
 ["pensent", "think"],
 ["faible", "low"],
 ["cache", "hidden"],
 ["fiston", "son"],
 ["van", "van"],
 ["prendra", "will take"],
 ["attraper", "to catch"],
 ["dort", "sleeps"],
 ["décider", "decide"],
 ["inquiétez", "worry"],
 ["cesse", "constantly"],
 ["gaffe", "gaffe"],
 ["serons", "will"],
 ["ministre", "minister"],
 ["naissance", "birth"],
 ["agir", "to act"],
 ["utile", "useful"],
 ["gaz", "gas"],
 ["bataille", "battle"],
 ["noirs", "black"],
 ["vouliez", "wanted"],
 ["retraite", "retirement"],
 ["voleur", "thief"],
 ["poids", "weight"],
 ["discours", "speech"],
 ["star", "star"],
 ["nouvel", "new"],
 ["gâteau", "cake"],
 ["cents", "cents"],
 ["ventre", "belly"],
 ["connaissance", "knowledge"],
 ["voulons", "want to"],
 ["vive", "viva"],
 ["blancs", "whites"],
 ["assassin", "assassin"],
 ["jeux", "games"],
 ["vendredi", "Friday"],
 ["europe", "Europe"],
 ["accepte", "accepted"],
 ["parlons", "let's talk"],
 ["certaine", "some"],
 ["couple", "couple"],
 ["sérieusement", "seriously"],
 ["militaire", "military"],
 ["date", "dated"],
 ["rome", "Rome"],
 ["entend", "hears"],
 ["droits", "rights"],
 ["resté", "rest"],
 ["montez", "mount"],
 ["titre", "title"],
 ["génie", "genius"],
 ["couilles", "balls"],
 ["revenez", "return"],
 ["recevoir", "to receive"],
 ["autrement", "other"],
 ["répondu", "answered"],
 ["amené", "bring"],
 ["os", "bone"],
 ["perd", "loses"],
 ["valeur", "value"],
 ["puissant", "powerful"],
 ["style", "style"],
 ["vert", "green"],
 ["fortune", "fortune"],
 ["vieil", "old"],
 ["major", "Staff"],
 ["amener", "lead"],
 ["prépare", "prepare"],
 ["poulet", "chicken"],
 ["embrasser", "to kiss"],
 ["genoux", "knees"],
 ["acte", "act"],
 ["détruit", "destroy"],
 ["célèbre", "popular"],
 ["cible", "target"],
 ["cousin", "cousin"],
 ["conscience", "consciousness"],
 ["prévenir", "prevent"],
 ["ramène", "brings back"],
 ["arrivés", "arrived"],
 ["doigt", "finger"],
 ["californie", "California"],
 ["article", "article"],
 ["cherchez", "looking"],
 ["étoiles", "stars"],
 ["milliers", "thousands"],
 ["reprendre", "resume"],
 ["mine", "mine"],
 ["regardes", "look"],
 ["servi", "served"],
 ["ennemis", "enemies"],
 ["charmant", "charming"],
 ["sentiment", "feeling"],
 ["reposer", "rest"],
 ["note", "note"],
 ["couché", "layer"],
 ["gardez", "keep"],
 ["jake", "jake"],
 ["www", "www"],
 ["agréable", "pleasant"],
 ["préféré", "prefer"],
 ["château", "castle"],
 ["bal", "ball"],
 ["oreilles", "ears"],
 ["découvrir", "discover"],
 ["apparemment", "apparently"],
 ["los", "the bone"],
 ["zéro", "zero"],
 ["saint", "Holy"],
 ["côtés", "sides"],
 ["marrant", "funny"],
 ["comprend", "comprises"],
 ["pourrez", "can"],
 ["joues", "play"],
 ["salon", "living room"],
 ["lève", "survey"],
 ["utilise", "uses"],
 ["conversation", "conversation"],
 ["pilote", "pilot"],
 ["fer", "iron"],
 ["attendent", "wait"],
 ["humaine", "human"],
 ["conduit", "pipe"],
 ["gorge", "throat"],
 ["victimes", "victims"],
 ["détails", "details"],
 ["talent", "talent"],
 ["passée", "past"],
 ["sexy", "sexy"],
 ["iui", "iui"],
 ["maria", "maria"],
 ["privé", "private"],
 ["apporter", "to bring"],
 ["tuée", "killed"],
 ["violence", "violence"],
 ["feras", "shalt"],
 ["nerveux", "nervous"],
 ["aéroport", "airport"],
 ["direct", "direct"],
 ["tribunal", "court"],
 ["commande", "ordered"],
 ["in", "in"],
 ["jette", "throws"],
 ["paquet", "package"],
 ["fumer", "to smoke"],
 ["aise", "easy"],
 ["dieux", "gods"],
 ["emmerde", "hassle"],
 ["joindre", "join"],
 ["lance", "spear"],
 ["usine", "factory"],
 ["défendre", "defend"],
 ["will", "will"],
 ["forêt", "forest"],
 ["champion", "champion"],
 ["horreur", "horror"],
 ["importante", "important"],
 ["paroles", "lyrics"],
 ["test", "test"],
 ["désormais", "from now on"],
 ["tres", "very"],
 ["dernières", "latest"],
 ["tombée", "fall"],
 ["chris", "chris"],
 ["extérieur", "outside"],
 ["désert", "desert"],
 ["coupé", "chopped off"],
 ["intelligent", "clever"],
 ["aidé", "help"],
 ["saura", "will know"],
 ["dira", "tell"],
 ["passera", "will pass"],
 ["comptes", "accounts"],
 ["mode", "fashion"],
 ["parlais", "speaking"],
 ["invités", "guests"],
 ["série", "series"],
 ["pis", "udder"],
 ["sage", "wise"],
 ["rappelles", "remember"],
 ["concerne", "concerned"],
 ["mariés", "married"],
 ["grandi", "grown up"],
 ["pousse", "shoot"],
 ["vache", "cow"],
 ["accepté", "accepted"],
 ["meme", "even"],
 ["pensait", "thought"],
 ["repos", "rest"],
 ["ordinateur", "computer"],
 ["rock", "rock"],
 ["allo", "Hello"],
 ["smith", "smith"],
 ["ombre", "shadow"],
 ["it", "it"],
 ["russe", "Russian"],
 ["minuit", "midnight"],
 ["vole", "Fly"],
 ["amusant", "amusing"],
 ["membres", "members"],
 ["jane", "jane"],
 ["moyens", "means"],
 ["surpris", "surprised"],
 ["ouverte", "opened"],
 ["nombreux", "numerous"],
 ["également", "also"],
 ["imaginer", "imagine"],
 ["mince", "thin"],
 ["dormi", "slept"],
 ["page", "page"],
 ["essence", "gasoline"],
 ["maire", "mayor"],
 ["faisant", "making"],
 ["lundi", "Monday"],
 ["entré", "Between"],
 ["billet", "ticket"],
 ["moteur", "engine"],
 ["réparer", "to fix"],
 ["franchement", "frankly"],
 ["caché", "hidden"],
 ["cigarette", "cigarette"],
 ["al", "al"],
 ["riches", "rich"],
 ["partager", "share"],
 ["puissance", "power"],
 ["trouvée", "found"],
 ["parfaite", "perfect"],
 ["hiver", "winter"],
 ["épée", "sword"],
 ["of", "of"],
 ["reviendra", "will come back"],
 ["haute", "high"],
 ["souffle", "breath"],
 ["tente", "attempted"],
 ["vingt", "twenty"],
 ["miracle", "miracle"],
 ["arbres", "trees"],
 ["apprécie", "appreciate"],
 ["senti", "felt"],
 ["manquer", "to lack"],
 ["artiste", "artist"],
 ["créer", "create"],
 ["lac", "lake"],
 ["jeté", "thrown"],
 ["souvenirs", "memories"],
 ["sommeil", "sleep"],
 ["vrais", "real"],
 ["réveiller", "wake"],
 ["leçon", "lesson"],
 ["casser", "break"],
 ["courses", "racing"],
 ["chemise", "shirt"],
 ["fantôme", "ghost"],
 ["membre", "member"],
 ["passez", "skip"],
 ["acteur", "actor"],
 ["battu", "beaten"],
 ["parc", "Park"],
 ["chair", "flesh"],
 ["rues", "streets"],
 ["utilisé", "in use"],
 ["reculez", "step back"],
 ["japonais", "Japanese"],
 ["mentir", "lie"],
 ["rentrez", "come back"],
 ["plans", "Plans"],
 ["coûte", "cost"],
 ["champagne", "Champagne"],
 ["no", "No."],
 ["américaine", "American"],
 ["risques", "risks"],
 ["pete", "pete"],
 ["offert", "Free"],
 ["semblant", "show"],
 ["annonce", "ad"],
 ["échange", "exchange"],
 ["paye", "paid"],
 ["premiers", "first"],
 ["débarrasser", "get rid of"],
 ["fuir", "to run away"],
 ["louis", "louis"],
 ["supplie", "beseech"],
 ["saute", "jumped up"],
 ["signer", "sign"],

 ['dispositif', 'device'],
 ['fondé', 'based'],
 ['communément', 'commonly'],
 ['appelées', 'called'],
 ['Cependant', 'However'],
 ['tandis', 'while'],
 ['permettent', 'allow'],
 ['délivrées', 'delivered'],
 ['valeurs', 'values'],
 ['lien', 'link'],
 ['appela', 'called'],
 ['roue', 'wheel'],
 ['étoile', 'star'],
 ['plongent', 'dive'],
 ['godet', 'bucket'],
 ['contenant', 'containing'],
 ['cependant', 'However'],

 ['associant', 'teaming up'],
 ['continu', 'continuous'],
 ['séparés', 'separated'],
 ['brevet', 'patent'],
 ['traités', 'treated'],
 ['reliées', 'related'],
 ['décalées', 'staggered'],
 ['décalage', 'gap'],
 ['Voire', 'Even'],
 ['raccordement', 'connection'],
 ['balais', 'broom'],
 ['élevées', 'high'],
 ['défrettage', 'defrosting'],
 ['spires', 'turns'],
 ['frettage', 'fretting'],
 ['partiellement', 'partially'],
 ['résolus', 'resolved'],
 ['cloches', 'bells'],
 ['néanmoins', 'nevertheless'],
 ['possèdent', 'own'],

 ['aimants', 'magnets'],
 ['pourvu', 'provided'],
 ['capteur', 'sensor'],
 ['balai', 'broom'],
 ['enroulements', 'windings'],
 ['puissances', 'powers'],
 ['autrefois', 'formerly'],
 ['dévolu', 'devolved'],
 ['moyenne', 'average'],
 ['déclinent', 'decline'],
 ['universel', 'universal'],
 ['alimenté', 'powered'],
 ['apparaissent', 'appear'],
 ['soumises', 'submitted'],
 ['feuilletés', 'puff pastry'],
 ['rendement', 'yield'],
 ['réduit', 'reduced'],
 ['est', 'East'],
 ['exigeant', 'demanding'],
 ['nombreuses', 'many'],
 ['gradateurs', 'dimmers'],
 ['avoisiner', 'neighbor'],
 ['relever', 'raise'],
 ['asservissement', 'enslavement'],
 ['bagues', 'rings'],
 ['notamment', 'notably'],
 ['éoliennes', 'wind turbines'],
 ['intérieure', 'interior'],
 ['montée', 'climb'],
 ['roulements', 'bearings'],
 ['réduit', 'reduced'],
 ['pertes', 'losses'],
 ['noyau', 'core'],
 ['démarrage', 'startup'],
 ['hottes', 'hoods'],
 ['vidange', 'emptying'],
 ['laver', 'wash'],
 ['alimentés', 'powered'],

 ['carré', 'square'],
 ['dispositifs', 'devices'],
 ['associés', 'associates'],
 ['aspirateurs', 'vacuum cleaners'],
 ['facilement', 'easily'],
 ['coûteux', 'expensive'],
 ['onduleurs', 'inverters'],
 ['environs', 'surroundings'],
 ['dirigée', 'directed'],
 ['aspirantes', 'aspiring'],
 ['tend', 'tends'],
 ['disparaître', 'disappear'],
 ['liée', 'linked'],
 ['lave', 'wash'],
 ['vaisselle', 'dishes'],
 ['déplacé', 'moved'],
 ['précis', 'accurate'],
 ['lents', 'slow'],
 ['remplacés', 'replaced'],
 ['essentiellement', 'basically'],
 ['déroulé', 'unrolled'],
 ['améliorée', 'improved'],
 ['végétale', 'vegetable'],
 ['solvants', 'solvents'],
 ['tôles', 'sheet metal'],
 ['améliorés', 'improved'],
 ['cadre', 'frame'],
 ['entraînée', 'trained'],
 ['entraînante', 'catchy'],
 ['freinage', 'braking'],
 ['déplaçant', 'moving'],
 ['écoles', 'schools'],
 ['soutenue', 'supported'],
 ['polluantes', 'pollutants'],

 ['amants', 'lovers'],
 ['maudits', 'cursed'],
 ['judiciaire', 'judicial'],
 ["c'est", 'It is'],
 ['confier', 'entrust'],
 ['dossiers', 'files'],
 ['conclusion', 'conclusion'],
 ['scénario', 'scenario'],
 ['attirer', 'attract'],
 ['inhumain', 'inhuman'],
 ['personnage', 'character'],
 ['désirez', 'desire'],
 ["l'écran", 'the screen'],
 
 ["n'est", 'is not'],
 ['crimes', 'crimes'],
 ['crapuleux', 'villainous'],
 ['sordides', 'sordid'],
 ["N'importe", 'Anything'],
 ['apprendrait', 'would learn'],
 ['coté', 'side'],
 ["d'histoire", 'of history'],
 ['étudié', 'studied'],
 ['intéressera', 'interested in'],
 ["l'homme", 'the man'],
 ['réactions', 'reactions'],
 ['humaines', 'human'],
 ['Parallèlement', 'in parallel'],
 ['comportement', 'behavior'],
 ['quotidienne', 'daily'],
 ["d'homme", 'of man'],
 ['traqué', 'hunted'],
 ['pouvant', 'can'],
 ['réagir', 'react'],
 ['habituels', 'usual'],
 ['tels', 'such'],
 ["l'amour", 'love'],
 ['haine', 'hate'],
 ['exploits', 'Exploits'],
 ['intéressants', 'interesting'],
 ['éluder', 'evade'],
 ['partagez', 'share'],
 ['Brièvement', 'Briefly'],
 ['résumons', "let's summarize"],
 ["D'abord", 'First of all'],
 ['Morelli', 'Morelli'],
 ['Pigalle', 'Pigalle'],
 ['discuté', 'discussed'],
 ['menthe', 'mint'],
 ['couillon', 'idiot'],
 ['chopine', 'pint'],
 ['menthe', 'mint'],
 ['clos', 'closed'],
 ['lentement', 'slowly'],
 ['valse', 'waltz'],
 ['désir', 'desire'],
 ['follement', 'madly'],
 ['serrés', 'tight'],
 ['battant', 'beating'],
 ['clos', 'closed'],
 ['échanger', 'to exchange'],
 ["s'étreignent", 'hug each other'],
 ['passionnément', 'passionately'],
 ['lourde', 'heavy'],
 ['volupté', 'voluptuousness'],
 ['musiques', 'music'],
 ['sourdes', 'deaf'],
 ['Ferveur', 'Fervor'],
 ['couples', 'couples'],
 ['enlacés', 'entwined'],
 ['saoule', 'drunk'],
 
 ["L'accordéon", 'The Accordion'],
 ['grisé', 'grey'],
 ["s'écroulent", 'collapse'],
 ["s'effondrer", 'collapse'],
 ["qu'on", 'that we'],
 ['tournent', 'turn'],
 ["jusqu'à", 'until'],
 ["l'aurore", 'dawn'],
 ['Perdus', 'Lost'],
 ['lueurs', 'glows'],
 ['blêmes', 'pale'],
 ['bals', 'balls'],
 ['souffleurs', 'blowers'],
 ['crachent', 'spit'],
 ['bruits', 'noises'],
 ['Ajaccio', 'Ajaccio'],
 ['buté', 'stop'],
 ['dénoncer', 'denounce'],
 ["m'a", 'my'],
 ["l'aurais", 'would have'],
 ['tournant', 'turning'],
 ['anciens', 'old'],
 ['méchants', 'bad guys'],
 ['finalo', 'final'],
 ["Qu'est", 'What is'],
 ['finalos', 'finalos'],
 ["qu'elle", 'what'],
 ['jouait', 'played'],
 ['terreurs', 'terrors'],
 ['raconté', 'tell'],
 ['bobards', 'fibs'],
 ['corse', 'Corsica'],
 ["qu'il", 'that he'],
 ['lieutenants', 'lieutenants'],
 ['servant', 'servant'],
 ['liqueurs', 'liquors'],
 ['caïd', 'boss'],
 ['Panzani', 'Panzani'],
 ['charriait', 'carried'],
 ["Qu'attendez", 'What are you waiting for'],
 ['rêvent', 'dream'],
 ['prennent', 'take'],
 ['manie', 'mania'],
 ['dingues', 'crazy'],
 ['Lab', 'Lab'],
 ['gâter', 'spoil'],
 ['Aaah', 'Aaah'],
 ['malheureux', 'unfortunate'],
 ['Henri', 'Henry'],
 ['foutre', 'cum'],
 ["t'en", "don't worry"],
 ['macaque', 'macaque'],
 ['Tape', 'Tape'],
 ['taule', 'jail'],
 ['lustre', 'chandelier'],
 ['Éclaire', 'Enlightened'],
 ['monnaie', 'cash'],
 ['bourre', 'wad'],
 ['liqueurs', 'liquors'],
 ['caïd', 'boss'],
 ['terreur', 'terror'],
 ['Panzani', 'Panzani'],
 ['foutras', 'foutras'],
 ['regagné', 'regained'],
 ['poursuivi', 'for follow-up'],
 ['facilité', 'ease'],
 ['dérisoire', 'paltry'],
 ['commençait', 'began'],
 ["l'étonner", 'surprise him'],
 ["D'où", 'From where'],
 ['suffi', 'enough'],
 ["c'était", 'it was'],
 ['veule', 'spineless'],
 ['bouffi', 'puffy'],
 ['jouet', 'toy'],
 ['magique', 'Magic'],
 ["l'envahissait", 'invaded him'],
 ['supériorité', 'superiority'],
 ['possédé', 'possesses'],
 ['communes', 'municipalities'],
 ["l'avait", 'had it'],
 ["n'était", 'was not'],
 ['prenait', 'taking'],
 ['décide', 'decided'],
 ["qu'en", 'that in'],
 ['appuyant', 'pressing'],
 ['gâchette', 'trigger'],
 ['verrait', 'would see'],
 ['projets', 'projects'],
 ["l'argent", 'money'],
 ['irait', 'would go'],
 ['disposition', 'arrangement'],
 ['gendarmes', 'gendarmes'],
 ['satisfait', 'satisfied'],
 ["d'une", 'of a'],
 ['baraque', 'shack'],
 ['recommande', 'recommended'],
 ['Pommery', 'Pommery'],
 ['grenade', 'grenade'],
 ['rosé', 'pink'],
 ['cuvée', 'vintage'],
 ['réservée', 'reserved'],
 ['Envoyez', 'Send'],
 ['rosé', 'pink'],
 ['Magnum', 'Magnum'],
 ["t'elle", 'she'],
 ['jouez', 'play'],
 ['cens', 'cens'],
 ['Appliquez', 'Apply'],
 ["j'en", 'I have'],

 ['foncer', 'rush'],
 ["T'as", 'You have'],
 ['brûle', 'burns'],
 ['bouquin', 'book'],
 ['remets', 'put back'],
 ["l'inspecteur", 'the inspector'],
 ['camionnette', 'van'],
 ['emmenez', 'take'],
 ['menottes', 'handcuffs'],
 ['hauts', 'Tops'],
 ["t'inquiète", "don't worry"],
 ['piquer', 'sting'],
 ['moutons', 'sheep'],
 ['pleins', 'full'],
 ['promène', 'walk'],
 ['matins', 'mornings'],
 ['voile', 'veil'],
 ['Nice', 'Nice'],
 ["d'argent", 'silver'],
 ["n'avaient", 'had'],
 ['Provence', 'Provence'],
 ['Aix', 'Aix'],
 ['arrivèrent', 'arrived'],
 ['maquillée', 'made up'],
 ['volée', 'stolen'],
 ['soirs', 'evenings'],
 ['plais', 'pleases'],
 ['appréhension', 'apprehension'],
 ['ressens', 'feel'],
 ["m'attire", 'attracts me'],
 ['plaisez', 'please'],
 ['veine', 'vein'],
 ['flamber', 'blaze'],
 ['grosses', 'big'],
 ['bricoleur', 'handyman'],
 ['mouiller', 'wet'],
 ["n'avez", 'do not have'],
 ['mener', 'carry out'],
 ['robes', 'dresses'],
 ["J'y", "I'm there"],
 ['boniments', 'sales pitches'],
 ['fumée', 'smoke'],
 ['accordéons', 'accordions'],
 ['indiquais', 'indicated'],
 ['baccara', 'baccarat'],
 ["J'avais", 'I had'],
 ['jouais', 'was playing'],
 ['robes', 'dresses'],
 ['Cannes', 'Cannes'],
 ['Deauville', 'Deauville'],
 ['Biarritz', 'Biarritz'],
 ['palaces', 'palaces'],
 ['misérablement', 'miserably'],
 ["d'années", 'of years'],
 ['dizaine', 'ten'],
 ['provisoire', 'provisional'],
 ['pointe', 'point'],
 ["n'avez", 'do not have'],
 ['lendemain', 'the following day'],
 ['détrompez', 'undeceive'],
 ['particulier', 'particular'],
 ['suffisent', 'are enough'],
 ['cuillerées', 'spoonfuls'],
 ['pognon', 'money'],

 
 ['amant', 'lover'],
 ["m'en", 'me'],
 ['mangeait', 'ate'],
 ['buvait', 'drank'],
 ['commerce', 'trade'],
 ['fainéant', 'lazy'],
 ['présenté', 'present'],
 ['Léo', 'Leo'],
 ["s'occupe", 'takes care'],
 ['cigarettes', 'cigarettes'],
 ['refusé', 'denied'],
 ['Mésange', 'Tit'],
 ["n'as", "don't have"],
 ["l'air", 'the air'],
 ['planques', 'hideouts'],
 ["m'attend", 'waiting for me'],
 ['combine', 'combined'],
 ['dépannes', 'breakdowns'],
 ["t'auras", 'you will have'],
 ["d'oseilles", 'sorrel'],
 ['sourde', 'deaf'],
 ["T'auras", 'You will have'],
 ['plaisantais', 'was joking'],
 ["t'aider", 'help you'],
 ['régulier', 'regular'],
 ['merveille', 'wonder'],
 ['salades', 'salads'],
 ['Raoul', 'Raoul'],
 ['Assieds', 'Sit'],
 ["l'ami", 'the friend'],
 ["t'ai", 'you have'],
 ['Asseyez', 'Sit down'],
 ["m'attend", 'waiting for me'],
 ['préparera', 'will prepare'],
 ['presser', 'squeeze'],
 ['repéré', 'spotted'],
 ['planquer', 'hide'],
 ['constitué', 'constituted'],
 ['tristement', 'sadly'],
 ['surnom', 'nickname'],
 ['Tractions', 'Pull-ups'],
 ['débarquèrent', 'disembarked'],
 ['Cagnes', 'Cagnes'],
 ['démerde', 'screw up'],
 ['Rendez', 'Make'],
 ["l'hôtel", 'the hotel'],
 ['paires', 'pairs'],
 ['comtesse', 'countess'],
 ['loué', 'rented'],
 ['somptueuse', 'sumptuous'],
 ['vêtue', 'dressed'],
 ['vulgaire', 'vulgar'],
 ['veuf', 'widower'],
 ['rompez', 'break up'],
 ['centaines', 'hundreds'],
 ['remarqua', 'noticed'],
 ['fonds', 'funds'],
 ['fourgon', 'van'],
 ['insuffisamment', 'insufficiently'],
 ['gardé', 'guard'],
 ["l'idée", 'the idea'],
 ['vint', 'came'],
 ['fructueuse', 'fruitful'],
 ['rapporter', 'report'],
 ['viendrait', 'would come'],
 ['confié', 'entrusts'],
 ['couler', 'to flow'],
 ['recommencerait', 'would do it again'],
 ['rappela', 'reminded'],
 ["s'en", 'go away'],
 ['souvenait', 'remembered'],
 ['passion', 'passion'],
 ['joueuse', 'player'],
 ['expliqué', 'explain'],
 ['rendez', 'go'],
 ['prêtes', 'ready'],
 ['costard', 'suit'],
 ['loquet', 'latch'],
 ['comtesse', 'countess'],
 ['bouquet', 'bunch'],
 ['compliments', 'compliments'],
 ['refuses', 'refuse'],
 ["T'es", 'Your'],
 ["m'aiderais", 'would help me'],
 ['flambé', 'flambé'],
 ["d'un", 'of a'],
 ['rendrai', 'will return'],
 ['rendrai', 'will return'],
 ['Explique', 'Explain'],
 ["m'intéresse", 'interests me'],
 ['rapporte', 'reports'],
 ["t'auras", 'you will have'],
 ["t'imagines", 'you imagine'],
 ['cavaler', 'ride'],
 ['raccourcir', 'shorten'],
 ['foutes', 'foutes'],
 ["m'étais", 'I keep quiet'],
 ["t'es", 'your'],
 ['comtesses', 'countesses'],
 ["qu'ils", 'that they'],
 ['déchargent', 'unload'],
 ['fourgon', 'van'],
 ['réussir', 'succeed'],
 ['fourgon', 'van'],
 ["m'occupe", 'keeps me busy'],
 ['conducteur', 'driver'],
 ["t'occupes", 'take care'],
 ['sacs', 'bags'],
 ['bagnoles', 'cars'],
 ['couvrir', 'cover'],
 ["l'avant", 'the front'],
 ['tourné', 'turned'],
 ["l'envers", 'the reverse'],
 ["l'autre", 'the other'],
 ['filer', 'spin'],
 ['repéré', 'spotted'],
 ['sacs', 'bags'],
 ['piquera', 'will sting'],
 ['amusera', 'will amuse'],
 ['risquerai', 'will risk'],
 ['cousu', 'sewn'],
 ['neuve', 'new'],
 ["L'un", 'Mon'],
 ['verrez', 'see'],
 ['performance', 'performance'],
 ['raboter', 'plane'],
 ['culasse', 'cylinder head'],
 ['verrez', 'see'],
 ['craint', 'fears'],
 ['antivol', 'anti-theft'],
 ['fricfrac', 'fricfrac'],
 ['bloque', 'blocked'],
 ["l'heure", 'time'],
 ['quatrième', 'fourth'],
 ['sentais', 'Smelt'],
 ["j'allais", 'I was going'],
 ['vague', 'wave'],
 ["l'âme", 'blade'],
 ["n'aurions", 'would not have'],
 ['Corniche', 'Cornice'],
 ["l'instant", 'the moment'],
 ['jus', 'juice'],
 ['fruit', 'fruit'],
 ["L'atmosphère", 'The atmosphere'],
 ['pluvieuse', 'rainy'],
 ['inusitée', 'unusual'],
 ['déplaît', 'displeases'],
 ["J'adore", 'I adore'],
 ['demi', 'half'],
 ['teintes', 'shades'],
 ['armé', 'armed'],
 ['manœuvre', 'maneuver'],
 ["d'affolement", 'panic'],
 ['essuie', 'wipe'],
 ['volants', 'ruffles'],
 ["l'essence", 'gasoline'],
 ['traces', 'traces'],
 ['gants', 'gloves'],
 ['files', 'files'],
 ["t'ai", 'you have'],
 ['geste', 'gesture'],
 ["l'air", 'the air'],
 ['hop', 'hop'],
 ['Trente', 'Thirty'],
 ['poussières', 'dust'],
 ['Seize', 'Sixteen'],
 ['briques', 'bricks'],
 ['réglé', 'ruler'],
 ["d'empreintes", 'of fingerprints'],
 ['digitales', 'digital'],
 ['gants', 'gloves'],
 ['abandonnées', 'abandoned'],
 ['propriétaires', 'owners'],
 ["l'a", 'there'],
 ["l'ai", 'have it'],
 ['laissiez', 'let'],
 ["l'avais", 'had it'],
 ['antivol', 'anti-theft'],
 ['perfectionné', 'perfected'],
 ['bloque', 'blocked'],

 ['impressionne', 'impressed'],
 ['détail', 'detail'],
 ['intéressé', 'interested'],
 ['volées', 'stolen'],
 ["d'intervalle", 'interval'],
 ['croupier', 'dealer'],
 ['changeur', 'changer'],
 ['joueurs', 'players'],
 ['joueuses', 'players'],
 ["d'elles", 'of them'],
 ['belge', 'Belgian'],
 ['Veuvre', 'Widow'],
 ['soda', 'soda'],
 ['devions', 'had to'],
 ["d'avis", 'of opinion'],
 ['préférait', 'preferred'],
 ['quittée', 'left'],
 ['sortant', 'outgoing'],
 ['aperçu', 'preview'],
 ['dérobée', 'backdoor'],
 ['décrire', 'describe'],
 ['figure', 'figure'],
 ['typée', 'typed'],
 ['coiffée', 'hairstyle'],
 ['Plie', 'Plaice'],
 ['routes', 'roads'],
 ['gares', 'stations'],
 ['gardées', 'guarded'],
 ['Mavraux', 'Mavraux'],
 ['coriace', 'tough'],
 ['tapera', 'will type'],
 ['pokers', 'pokers'],
 ['rarement', 'rarely'],
 ['paraître', 'appear'],
 ['louche', 'suspicious'],
 ['brusque', 'sudden'],
 ['plongeon', 'diving'],
 ['francs', 'francs'],
 ["D'accord", 'All right'],
 ['Bomans', 'Bomans'],
 ['Veuvre', 'Widow'],
 ['propriétaire', 'owner'],
 ["d'avance", 'in advance'],
 ['surveillons', "let's watch"],
 ["l'attention", 'attention'],
 ["S'ils", 'If they'],
 ['montreront', 'will show'],
 ['fatalement', 'inevitably'],
 ['foncerons', "let's go for it"],
 ['surveillez', 'monitor'],
 ['tenons', "let's hold"],
 ['Échec', 'Failure'],
 ['jouent', 'are playing'],
 ['belote', 'belote'],
 ['partagé', 'sharing'],
 ['racontes', 'tell'],
 ["t'avais", 'you had'],
 ['dérailles', 'derails'],
 ["m'as", 'got me'],
 ['cavale', 'run'],
 ['fâche', 'angry'],
 ['archi', 'archi'],
 ['grillés', 'grilled'],
 ["l'étranger", 'the stranger'],
 ['tranquilles', 'quiet'],
 ["d'oublier", 'to forget'],
 ['planqués', 'hidden'],
 ['renseigner', 'to inform'],
 ["n'aurait", 'would not have'],
 ['méfie', 'wary'],
 ["d'aller", 'to go'],
 ['couru', 'ran'],
 ['Bénard', 'Benard'],
 ['Antibes', 'Antibes'],
 ['vedette', 'featured'],
 ["l'achète", 'cowardice'],
 ["s'enfuit", 'runs away'],
 ['sentent', 'feel'],
 ["n'ai", "don't have"],
 ['précise', 'precise'],
 ['bicoque', 'shack'],
 ['repérée', 'spotted'],
 ['cueillir', 'gather'],
 ['vedette', 'featured'],
 ['Gênes', 'Genoa'],
 ['accoster', 'dock'],
 ['youyou', 'dinghy'],
 ['cachera', 'will hide'],
 ['Lombardini', 'Lombardini'],
 ["aujourd'hui", 'Today'],
 ['donnerai', 'will give'],
 ['Gênes', 'Genoa'],
 ['blagues', 'jokes'],
 ['boucler', 'buckle'],
 ['chapitre', 'chapter'],
 ["n'y", 'no'],
 ["s'ils", 'if they'],
 ["t'oblige", 'obliges you'],
 ['redis', 'redis'],
 ["t'énerve", 'get angry'],
 ['policier', 'police officer'],
 ['Marius', 'Marius'],
 ['bagnole', 'car'],
 ['embarque', 'embarks'],
 ['téléphoné', 'phone'],
 ["l'impression", 'the impression'],
 ['Signalement', 'Reporting'],
 ['conforme', 'compliant'],
 ['cherchais', 'was looking for'],
 ['tasse', 'cup'],
 ['précautions', 'precautions'],
 ['habituelles', 'usual'],
 ["n'y", 'no'],
 ["l'amener", 'bring him'],
 ["d'Antibes", 'from Antibes'],
 ["l'attend", 'waiting for him'],
 ['doublé', 'double'],
 ['chamailler', 'bicker'],
 ["S'il", 'If he'],
 ['bagnole', 'car'],
 ['taco', 'taco'],
 ['bagages', 'luggage'],
 ['Posez', 'Ask'],
 ['ambulance', 'ambulance'],
 ['téléphoné', 'phone'],
 ['veniez', 'came'],
 ['allés', 'went'],
 ['motards', 'bikers'],
 ['foncez', 'go for it'],
 ["presqu'île", 'peninsula'],
 ['empêchez', 'prevent'],
 ["s'embarquer", 'embark'],
 ['sommations', 'summons'],
 ['suivrons', 'will follow'],
 ['Appuie', 'Support'],
 ['appuie', 'supports'],
 ['doublé', 'double'],
 ['magnez', 'magnez'],
 ['grouillez', 'swarm'],
 ['tirent', 'shoot'],
 ['salopards', 'bastards'],
 ['Dépêche', 'Dispatch'],
 ['embarque', 'embarks'],
 ['démarre', 'started'],
 ["qu'évanouie", 'that fainted'],
 ['touchée', 'touched'],
 ['Brigadier', 'Brigadier'],
 ['aidez', 'help'],
 ['transporter', 'carry'],
 ['correct', 'correct'],
 ['sauvages', 'wild'],
 ['repose', 'rests'],
 ['réfléchi', 'thoughtful'],
 ['proposition', 'proposal'],
 ['mêler', 'mix'],
 ['Dernièrement', 'Lately'],
 ['recommencer', 'restart'],
 ["m'occuper", 'take care of myself'],
 ['refusez', 'refuse'],
 ["n'arrête", "don't stop"],
 ["n'intéresse", 'not interested'],
 ['froidement', 'coldly'],
 ['acceptez', 'accept'],
 ['ferons', 'will do'],
 ["l'accepte", 'accept it'],
 ['frousse', 'scares'],
 ['embêtements', 'hassles'],
 
 ["m'ont", 'Mountain'],
 ["l'hôpital", 'the hospital'],
 ['guérisses', 'healers'],
 ['fière', 'proud'],
 ["n'en", "don't"],
 ["m'étonne", 'surprises me'],
 ["t'étonne", 'surprise you'],
 ["t'y", 'there you go'],
 ['fatigues', 'fatigue'],
 ['chou', 'cabbage'],
 ['vice', 'vice'],
 ['barque', 'small boat'],
 ['pourtour', 'perimeter'],
 ['combines', 'combines'],
 ["l'emmener", 'take him away'],
 ['Tamara', 'Tamara'],
 ['surveiller', 'to watch'],
 ['reconnu', 'recognized'],
 ['Montmartre', 'Montmartre'],
 ['Djacobini', 'Djacobini'],
 ['téléphonez', 'call'],
 ['débris', 'debris'],
 ['ramassez', 'pick up'],
 ['Djacobini', 'Djacobini'],
 ['culotté', 'cheeky'],
 ['copains', 'friends'],
 ['décoré', 'decorated'],
 ['musiciens', 'musicians'],
 ['dancing', 'dancing'],
 ['permettrez', 'will allow'],
 ["d'honneur", 'of honor'],
 ['remerciez', 'thank'],
 ["l'offrir", 'offer it'],
 ['heureux', 'happy'],
 ['Djacobini', 'Djacobini'],
 ['conseille', 'advises'],
 ["m'appelle", 'call me'],
 ["m'asseoir", 'sit down'],
 ['commission', 'commission'],
 ["d'hôtel", 'hotel'],
 ["qu'un", 'one'],
 ["d'amour", 'of love'],
 ['fréquentent', 'frequent'],
 ['matous', 'cats'],
 ["d'armée", 'army'],
 ['général', 'general'],
 ["qu'un", 'one'],
 ['décoré', 'decorated'],
 ['champêtre', 'country'],
 ['souffler', 'blow'],
 ["s'arrête", 'stop'],
 ["d'amour", 'of love'],
 ['migrateurs', 'migratory'],
 ['oiseaux', 'birds'],
 ['girouette', 'weathercock'],
 ['aplatis', 'flattened'],
 ['fragiles', 'fragile'],
 ['semblent', 'seem'],
 ['maisons', 'houses'],
 ["n'être", 'not to be'],
 ['poulbot', 'poultbot'],
 ['charrie', 'charrie'],
 ['sourit', 'smiles'],
 ['marchande', 'Merchant'],
 ['souffler', 'blow'],
 ["s'arrête", 'stop'],
 ["l'on", 'we'],
 ['terminée', 'finished'],
 ['retraitées', 'retired'],
 ["d'histoires", 'of stories'],
 ['banale', 'banal'],
 ['chansons', 'songs'],
 ['Molman', 'Molman'],
 ['dépêchez', 'hurry'],
 ['orchidées', 'orchids'],
 ['Molman', 'Molman'],
 ['camoufle', 'camouflage'],
 ['téléphones', 'phones'],
 ['ayons', "let's have"],
 ['œuvre', 'artwork'],
 ['impuissants', 'powerless'],
 ['laissaient', 'left'],
 ['déconcertante', 'disconcerting'],
 ['audace', 'audacity'],
 ['exécutés', 'executed'],
 ['vols', 'flights'],
 ['individus', 'people'],
 ['innocentes', 'innocent'],
 ['convoyeurs', 'conveyors'],
 ['meurtres', 'murders'],
 ['attaques', 'attacks'],
 ['banques', 'banks'],
 ['forfaits', 'packages'],
 ['accumulèrent', 'accumulated'],
 ['rappelaient', 'reminded'],
 ['brutalement', 'brutally'],
 ['existé', 'exist'],
 ['volatilisés', 'volatilized'],
 ['littéralement', 'literally'],
 ['déprimante', 'depressing'],
 ["s'être", "to be"],
 ['donnèrent', 'gave'],
 ['quelconque', 'any'],
 ['indice', 'hint'],
 ["d'avoir", "having"],
 ["l'engager", 'engage him'],
 ['attendions', 'expectations'],
 ['Bonifacio', 'Bonifacio'],
 ['abordé', 'addressed'],
 ['attendaient', 'were waiting'],
 ['alertés', 'alerted'],
 ['Roccapina', 'Roccapina'],
 ['devaient', 'were to'],
 ['fichera', 'will file'],
 ["d'autre", 'else'],
 ["m'occuperai", 'I will take care'],
 ['condition', 'condition'],
 ['trompée', 'deceived'],
 
 ['jugement', 'judgement'],
 ['mars', 'March'],
 ["t'interdis", 'forbid you'],
 ['pépé', 'grandpa'],
 ['mordu', 'bitten'],
 ['crâneur', 'braggart'],
 ['dérangez', 'disturb'],
 ['regretté', 'regretted'],
 ["m'avais", 'had me'],
 ['doublée', 'doubled'],
 ["d'ex", 'from ex'],
 ["qu'à", 'than to'],
 ['quittes', 'leaves'],
 ['demandes', 'requests'],
 ["t'embêtes", 'bother you'],
 ['passais', 'I was passing'],
 ["t'expliquer", 'explain to you'],
 ['foutu', 'fucked up'],
 ['coûter', 'cost'],
 ['filé', 'spun'],
 ['suivie', 'followed'],
 ['fasses', 'do'],
 ['endroits', 'locations'],
 ['continueras', 'will continue'],
 ['téléphoner', 'call'],
 ['passés', 'past'],
 ['brochet', 'pike'],
 ['contrôlez', 'control'],
 ['communication', 'communication'],
 ['renseignement', 'information'],
 ['mené', 'led'],
 ['mentez', 'lie'],
 ['bleue', 'blue'],
 ['flotte', 'fleet'],
 ['bouillon', 'broth'],
 ['dégagez', 'get out'],
 ['bouts', 'tips'],
 ['triplots', 'triplets'],
 ['crapule', 'scoundrel'],
 ['posséder', 'possess'],
 ["n'avais", "didn't have"],
 ['bijoutier', 'jeweler'],
 ['cailloux', 'pebbles'],
 ['partage', 'sharing'],
 ['surveillait', 'monitored'],
 ["l'andouille", 'the andouille'],
 ['cloche', 'Bell'],
 ['désire', 'longed for'],
 ["l'addition", 'the bill'],
 ['arrogant', 'arrogant'],
 ['retordre', 'twist'],
 ['commandait', 'commanded'],
 ['nerfs', 'nerves'],
 ['déguisé', 'disguised'],
 ['chasseur', 'hunter'],
 ['donneur', 'giver'],
 ['Couche', 'Layer'],
 ['fabriquent', 'make'],
 ['hostellerie', 'hostelry'],
 ['grandeurs', 'sizes'],
 ['planqué', 'hidden'],
 ['culot', 'cheek'],
 ['barrez', 'cross out'],
 ['Lucienne', 'Lucienne'],
 ['carton', 'cardboard'],
 ['champs', 'fields'],
 ['luzerne', 'alfalfa'],
 ['régaler', 'treat'],
 ['carton', 'cardboard'],
 ["qu'à", 'than to'],
 ['indécis', 'undecided'],
 ['marrer', 'to laugh'],
 ['guillotine', 'guillotine'],
 ['huppés', 'crested'],
 ['nid', 'nest'],
 ['Honnêtement', 'Honestly'],
 ['blessure', 'injury'],
 ['dégonfle', 'deflates'],
 ['gueules', 'gules'],
 ['prêter', 'lend'],
 ['fourrure', 'fur'],
 ['boutique', 'shop'],
 ['curieux', 'curious'],
 ['importants', 'important'],
 ["m'énerve", 'annoys me'],
 ['chiffre', 'figure'],
 ['chiffre', 'figure'],
 ['barrer', 'bar'],
 ['Barrez', 'Bar'],
 ['Tirons', "Let's shoot"],
 ['nettoyait', 'cleaned'],
 ['pistolet', 'gun'],
 ['déclarer', 'to announce'],
 ["l'opération", 'the operation'],
 ['commissariat', 'police station'],
 ['idiote', 'idiot'],
 ['toubib', 'doctor'],
 ['déclarer', 'to announce'],
 ["l'accident", 'the accident'],
 ['mourra', 'will die'],
 ['cuisiner', 'cook'],
 ['claboter', 'splash'],
 ['chahutez', 'heckle'],
 ['clabotera', 'will splash'],
 ['soignera', 'will treat'],
 ["l'emmènes", 'take him'],
 ['Albigeois', 'Albigensian'],
 ['Nantes', 'Nantes'],
 ['chialer', 'complaining'],
 ['Soulève', 'Raised'],
 ['Boucle', 'Loop'],
 ['pépins', 'pips'],
 ['combinet', 'combination'],
 ['réveillé', 'wake up'],
 ['fourrure', 'fur'],
 ['Nantes', 'Nantes'],
 ['sûreté', 'safety'],
 ['guérir', 'heal'],
 ['clinique', 'clinical'],
 ['crever', 'die'],
 ['Tais', 'Shut up'],
 ['crever', 'die'],
 ['taire', 'to hush up'],
 ['emmerdes', 'trouble'],
 ['foutu', 'fucked up'],
 ['cessé', 'stopped'],
 ['nuire', 'harm'],
 ['trouvés', 'found'],
 ['enterrés', 'buried'],
 ['pudeur', 'modesty'],
 ['confondus', 'confused'],
 ['sépulture', 'burial'],
 ['croix', 'cross'],
 ['fourrière', 'pound'],
 ['voient', 'see'],
 ['aventureux', 'adventurous'],
 ['gangsters', 'gangsters'],
 ['infiniment', 'infinitely'],
 ['récit', 'narrative'],
 ['convient', 'agrees'],
 ["d'elle", 'of her'],
 ['exposé', 'exposed'],
 ['suggéré', 'suggested'],
 ['déposé', 'deposit'],
 ['confierais', 'would confide'],
 
 
 ["l'essai", 'the test'],
 ['chaîne', 'chain'],
 ['célibataire', 'Single'],
 ['passionné', 'keen'],
 ["l'histoire", 'the story'],
 ['réussite', 'success'],
 ['designer', 'designate'],
 ['emploi', 'job'],
 ['Menacé', 'Threat'],
 ['juteux', 'juicy'],
 ['remboursement', 'refund'],
 ["d'impôts", 'taxes'],
 ['macho', 'macho'],
 ['choyé', 'pampered'],
 ['finit', 'ends'],
 ['fabricant', 'maker'],
 ['meubles', 'furniture'],
 ['stipule', 'stipulates'],
 ['toutefois', 'however'],
 ['candidat', 'candidate'],
 ['retenu', 'retained'],
 ['souhaiterait', 'would like'],
 ['dettes', 'debts'],
 ['causées', 'caused'],
 ['rémunéré', 'paid'],
 ['tyrannique', 'tyrannical'],
 ['donnent', 'give'],
 ['réalisme', 'realism'],
 ['connaissent', 'know'],
 ['secrètement', 'secretly'],
 ['créateur', 'Creator'],
 ['apprend', 'learn'],
 ['engage', 'engaged'],
 ["s'assurer", 'make sure'],
 ['bouleverse', 'upset'],
 ['antérieur', 'prior'],
 ['choc', 'shock'],
 ["n'avait", 'did not have'],
 
 
 ['rater', 'miss'],
 ["d'hommes", 'of men'],
 ['tigres', 'tigers'],
 ['pingouins', 'penguins'],
 ['tigres', 'tigers'],
 ['sauvage', 'savage'],
 ['reproduit', 'reproduced'],
 ['repart', 'leaves again'],
 ['chasser', 'chase'],
 ['proie', 'prey'],
 ['jungle', 'jungle'],
 ['pingouins', 'penguins'],
 ['dandine', 'waddle'],
 ['fidèles', 'faithful'],
 ['vente', 'sale'],
 ['pingouins', 'penguins'],
 ["l'équipe", 'the team'],
 ['économiques', 'economic'],
 ['canapés', 'sofas'],
 ['peluche', 'plush'],
 ['mondes', 'worlds'],
 ['môme', 'kid'],
 ["n'ya", 'does not have'],
 ['façons', 'manners'],
 ['traverser', 'to cross'],
 ["l'existence", 'existence'],
 ['mômes', 'kids'],
 ['moritz', 'moritz'],
 ['either', 'either'],
 ['charmante', 'charming'],
 ['dispenser', 'to dispense'],
 ['prononcer', 'pronounce'],
 ['ricaner', 'sneer'],
 ['craquez', 'crack'],
 ['évident', 'obvious'],
 ['craquez', 'crack'],
 ['deviner', 'guess'],
 ['stupides', 'stupid'],
 ['reproche', 'reproach'],
 ['grilles', 'grids'],
 ['collègue', 'colleague'],
 ['rayon', 'Ray'],
 ['véritable', 'true'],
 ['cyclone', 'cyclone'],
 ['personnifiée', 'personified'],
 ['lots', 'batches'],
 ['féminin', 'feminine'],
 ['alternance', 'alternation'],
 ['masculins', 'masculine'],
 ['science', 'science'],
 ['nina', 'nina'],
 ['schmidt', 'schmidt'],
 ['traite', 'treaty'],
 ['grain', 'grain'],
 ['lourd', 'heavy'],
 ['craquer', 'crack'],
 ['connaîtra', 'will know'],
 ["qu'une", 'that one'],
 ['mâts', 'masts'],
 ['bouillotte', 'hot water bottle'],
 ['bouillottes', 'hot water bottles'],
 ['ayant', 'having'],
 ['larges', 'wide'],
 ['pôles', 'poles'],
 ['jolies', 'pretty'],
 ['fesses', 'buttocks'],
 ['torse', 'torso'],
 ['viry', 'viry'],
 ['environnement', 'environment'],
 ['diminue', 'decreases'],
 ['courte', 'short'],
 ['cérémonie', 'ceremony'],
 ['steam', 'steam'],
 ['propose', 'propose'],
 ['sièges', 'seats'],
 ['acier', 'steel'],
 ['cuir', 'leather'],
 ['luche', 'luche'],
 ['peluche', 'plush'],
 ['proposez', 'propose'],
 ['peluche', 'plush'],
 ['bosser', 'work'],
 ['concurrence', 'competition'],
 ['couronnement', 'coronation'],
 ['quasars', 'quasars'],
 ['contredire', 'contradict'],
 ['excitant', 'exciting'],
 ['exceptionnelle', 'exceptional'],
 ['absolue', 'absolute'],
 ['mérité', 'deserved'],
 ['fiers', 'proud'],
 ['élément', 'element'],
 ['ayant', 'having'],
 ['qualités', 'qualities'],
 ['compétence', 'skill'],
 ['capacité', 'ability'],
 ["d'imposer", 'to impose'],
 ['souhaitons', 'wish'],
 ["l'endroit", 'the place'],
 ['entreprise', 'business'],
 ["d'applaudir", 'to applaud'],
 ['chaleureusement', 'warmly'],
 ['associé', 'partner'],
 ['karine', 'Karine'],
 ['mekhissi', 'mekhissi'],
 ['book', 'book'],
 ['réjouis', 'rejoice'],
 ['collaborer', 'collaborate'],
 ['choisissez', 'choose'],
 ['cottin', 'cotin'],
 ['lanka', 'lanka'],
 ['chouf', 'chouf'],
 ['douter', 'doubt'],
 ['précisément', 'precisely'],
 ['trouvait', 'found'],
 ['impersonnel', 'impersonal'],
 ['trouverez', 'will find'],
 ['meut', 'moves'],
 ['prestigieux', 'prestigious'],
 ['postes', 'positions'],
 ['harnais', 'harness'],
 ['majidi', 'majidi'],
 ['salue', 'greet'],
 ['inscrire', 'register'],
 ['géniale', 'awesome'],
 ['puce', 'chip'],
 ['indigné', 'unworthy'],
 ["d'affaires", 'business'],
 ['fêtera', 'will celebrate'],
 ['bisous', 'Kisses'],
 ['goutte', 'drop'],
 ['futura', 'futura'],
 ['pratiquement', 'practically'],
 ['repoussé', 'pushed back'],
 ['avances', 'advances'],
 ['ingrat', 'ungrateful'],
 ["m'envoies", 'send me'],
 ['rassurer', 'to reassure'],
 ['conseiller', 'advise'],
 ['basiques', 'basic'],
 ['crache', 'spit'],
 ['redressement', 'recovery'],
 ["l'objet", 'the object'],
 ['virer', 'fire'],
 ['fisc', 'tax'],
 ['redressement', 'recovery'],
 ['moritz', 'moritz'],
 ['fiches', 'sheets'],
 ['avertissement', 'warning'],
 ['millième', 'thousandth'],
 ['arriérés', 'arrears'],
 ['montants', 'amounts'],
 ["l'année", 'the year'],
 ['versement', 'payment'],
 ['anticipé', 'anticipated'],
 ['montant', 'Rising'],
 ["l'année", 'the year'],
 ["t'énerves", 'you get angry'],
 ['maurice', 'mauritius'],
 ['paille', 'straw'],
 ['saisir', 'to input'],
 ['challenge', 'challenge'],
 ["d'accepter", 'to accept'],
 ['mobilier', 'furniture'],
 ['brûlent', 'burn'],
 ['ayant', 'having'],
 ['souci', 'worry'],
 ['vallées', 'valleys'],
 ['finie', 'finished'],
 ['banier', 'banier'],
 ['pages', 'pages'],
 ['exprès', 'on purpose'],
 ['manquent', 'missing'],
 ["qu'importe", 'whatever'],
 ['démissionne', 'resigns'],
 ['déchiré', 'torn'],
 ['pimbêche', 'pimbêche'],
 ['anorexique', 'anorexic'],
 ['verdict', 'verdict'],
 ['manager', 'manager'],
 ['vraies', 'true'],
 ['prises', 'taken'],
 ['réfugier', 'refuge'],
 ['patachon', 'patachon'],
 ['naissent', 'are born'],
 ['théories', 'theories'],
 ['vestiaire', 'changing room'],
 ['thani', 'thani'],
 ["d'aujourd'hui", 'today'],
 ['deviens', 'become'],
 ['adultes', 'adults'],
 ['impératif', 'imperative'],
 ['urgent', 'urgent'],
 ['nettoyer', 'to clean'],
 ['frigidaire', 'fridge'],
 ['cadavres', 'corpses'],
 ['ivrogne', 'drunkard'],
 ['congélateur', 'freezer'],
 ['options', 'options'],
 ['gibbs', 'gibbs'],
 ['chocolat', 'chocolate'],
 ['futurs', 'future'],
 ['démission', 'resignation'],
 ['wes', 'wes'],
 ['lutte', 'struggle'],
 ['jungle', 'jungle'],
 ['mobilier', 'furniture'],
 ['écologique', 'ecological'],
 ['misons', "let's bet"],
 ['chanvre', 'hemp'],
 ['meublés', 'furniture'],
 ['totalement', 'totally'],
 ['équipés', 'equipped'],
 ['aménagés', 'fitted out'],
 ['chambres', 'bedrooms'],
 ["d'enfants", 'of children'],
 ['espaces', 'spaces'],
 ['garderie', 'nursery'],
 ['conseiller', 'advise'],
 ['ouf', 'phew'],
 ['mettais', 'put'],
 ['linge', 'laundry'],
 ['avicii', 'avicii'],
 ["l'épeautre", 'spelled'],
 ["l'aménagement", 'the layout'],
 ['complet', 'complete'],
 ['familiale', 'family'],
 ['confiée', 'entrusted'],
 ['ayant', 'having'],
 ["l'année", 'the year'],
 ['design', 'design'],
 ['meuble', 'furniture'],
 ['award', 'awards'],
 ['impressionnant', 'impressive'],
 ['valais', 'valais'],
 ["d'enfants", 'of children'],
 ['mobilier', 'furniture'],
 ["n'ont", "don't have"],
 ['cure', 'priest'],
 ['philosophie', 'philosophy'],
 ['entreprise', 'business'],
 ["s'agit", 'is'],
 ['réellement', 'really'],
 ["l'arrêt", 'the stop'],
 ['delà', 'of the'],
 ['tâches', 'tasks'],
 ['bouillie', 'porridge'],
 ["s'assortit", 'matches'],
 ['zut', 'Damn'],
 ['chenapan', 'chenapan'],
 ['tendance', 'tendency'],
 ['vicieux', 'vicious'],
 ['déjeuné', 'lunch'],
 ['permettrait', 'would allow'],
 ['ample', 'loose'],
 ['marc', 'mark'],
 ['réjouis', 'rejoice'],
 ['peluches', 'stuffed animals'],
 ['matière', 'matter'],
 ['griffes', 'claws'],
 ['provisoirement', 'temporarily'],
 ['calcul', 'calculation'],
 ['ouchy', 'ouchy'],
 ['mouton', 'sheep'],
 ['effrontément', 'brazenly'],
 ['tricher', 'cheat'],
 ["m'adapter", 'adapt'],
 ['rovers', 'rovers'],
 ['signes', 'signs'],
 ['hockey', 'hockey'],
 ['gamme', 'range'],
 ['chouettes', 'owls'],
 ['prenne', 'take'],
 ['comédie', 'comedy'],
 ['typique', 'typical'],
 ['championne', 'champion'],
 ['sports', 'sports'],
 ['généreux', 'generous'],
 ['courageux', 'brave'],
 ["d'aimer", 'to love'],
 ['soucis', 'worries'],
 ['manager', 'manager'],
 ['exécutif', 'executive'],
 ['crue', 'raw'],
 ['futura', 'futura'],
 ['difficilement', 'with difficulty'],
 ['éventuellement', 'possibly'],
 ['physique', 'physical'],
 ['tondeuse', 'mower'],
 ['maurice', 'mauritius'],
 ['cherches', 'looking for'],
 ['particulièrement', 'particularly'],
 ['syli', 'syl'],
 ['cruelles', 'cruel'],
 ['botha', 'botha'],
 ['aberrant', 'aberrant'],
 ['totalement', 'totally'],
 ['inconcevable', 'inconceivable'],
 ['soins', 'care'],
 ['bastille', 'bastille'],
 ['investi', 'invested'],
 ['opposer', 'oppose'],
 ["s'y", 'there'],
 ['soucis', 'worries'],
 ['optionnel', 'optional'],
 ['optimale', 'optimal'],
 ['traverse', 'crosses'],
 ['ajout', 'addition'],
 ['tutos', 'tutorials'],
 ['chocolat', 'chocolate'],
 ['maurice', 'mauritius'],
 ['raf', 'raf'],
 ['dopé', 'dope'],
 ['siffloter', 'whistle'],
 ["s'est", 'its'],
 ['inconnus', 'strangers'],
 ['inconnu', 'unknown'],
 ['dispute', 'dispute'],
 ['antipathique', 'unfriendly'],
 ['passeur', 'ferryman'],



 ['foudre', 'lightning'],
 ['mignard', 'cute'],
 ['loup', 'wolf'],
 ['risquez', 'risk'],
 ["m'accompagner", 'accompany me'],
 ["l'affairé", 'the case'],
 ['refuser', 'refuse'],
 ["n'êtes", 'are not'],
 ['camacho', 'camacho'],
 ['prétentieux', 'pretentious'],
 ['narcissique', 'narcissistic'],
 ['saurais', 'would know'],
 ['cousine', 'cousin'],
 ['degré', 'degree'],
 ['commencez', 'start'],
 ["s'acheter", 'to buy'],
 ["s'adresser", 'address'],
 ['mauvaises', 'bad'],
 ['maquillage', 'makeup'],
 ['reprocher', 'to reproach'],
 ["d'ailleurs", 'Besides'],
 ['foot', 'football'],
 ['anciennes', 'ancient'],
 ["t'achèterai", 'will buy you'],
 ['maillot', 'jersey'],
 ['labécède', 'labecedes'],
 ['pourri', 'rotten'],
 ['flambant', 'blazing'],
 ['talons', 'heels'],
 ['mettrais', 'would put'],
 ['expliquez', 'explain'],
 ['mamans', 'moms'],
 ['terrifiant', 'creepy'],
 ["m'attendait", 'was waiting for me'],
 ['royaume', 'kingdom'],
 ['foulée', 'stride'],
 ['mâles', 'males'],
 ['habitudes', 'habits'],
 ['tofu', 'tofu'],
 ['méthadone', 'methadone'],
 ['végétariens', 'vegetarians'],
 ['garantissant', 'guaranteeing'],
 ["j'aille", "I'm going"],
 ['chasseurs', 'hunters'],
 ['lances', 'spears'],
 ['missiles', 'missiles'],
 ['connus', 'known'],
 ['manif', 'demonstration'],
 ['rencontrés', 'met'],
 ['bâton', 'stick'],
 ["l'époque", 'the time'],
 ['travaillais', 'worked'],
 ['commandé', 'order'],
 ['cappuccino', 'cappuccino'],
 ['renversé', 'reversed'],
 ["d'efforts", 'of effort'],
 ['commander', 'order'],
 ['blement', 'bly'],
 ['aussitôt', 'right away'],
 ['portez', 'wear'],
 ["d'alliance", 'alliance'],
 ['agrandir', 'enlarge'],
 ['tourteaux', 'cakes'],
 ['oublies', 'forget'],
 ['devoirs', 'homework'],
 ['lessive', 'laundry'],
 ['équipé', 'team'],
 ['gaillard', 'fellow'],
 ['obtenez', 'get'],
 ['occupez', 'occupy'],
 ['souvenez', 'remember'],
 ["m'éloigner", 'move away'],
 ['oies', 'geese'],
 ['affection', 'affection'],
 ["n'aurais", 'would not have'],
 ['imaginé', 'conceived'],
 ['gravats', 'rubble'],
 ['tuilerie', 'tile factory'],
 ['rive', 'shore'],
 ["n'accuse", 'do not accuse'],
 ["l'eau", 'the water'],
 ['assise', 'seated'],
 ["d'éprouver", 'to prove'],
 ['enseignants', 'teachers'],
 ['vomi', 'vomit'],
 ["s'étriper", 'to gut oneself'],
 ['retombés', 'fallout'],
 ['pisser', 'piss'],
 ['iceberg', 'iceberg'],
 ['manquaient', 'were missing'],
 ['brûlures', 'burns'],
 ['geignard', 'whiny'],
 ["s'éloigner", 'move away'],
 ['relevé', 'statement'],
 ['popai', 'popai'],
 ['occupez', 'occupy'],
 ['riez', 'laugh'],
 ['démon', 'demon'],
 ["n'aurais", 'would not have'],
 ['maudit', 'damn'],
 ['reid', 'reid'],
 ['produits', 'products'],
 ['loisirs', 'hobbies'],
 ['souplesse', 'flexibility'],
 ['caractéristiques', 'features'],
 ['félin', 'feline'],
 ['intelligence', 'intelligence'],
 ['directement', 'directly'],
 ['diriez', 'say'],
 ['revoit', 'see again'],
 ['continuerai', 'will continue'],
 ['paierez', 'will pay'],
 ['lesquels', 'which'],
 ['importance', 'importance'],
 ["lorsqu'à", 'when to'],
 ['distributeurs', 'distributors'],
 ['auront', 'will have'],
 ['essayent', 'are trying'],
 ['alliances', 'wedding rings'],
 ["n'aura", 'will not have'],
 ['lisse', 'smooth'],
 ['courait', 'ran'],
 ['interphone', 'intercom'],
 ['lier', 'bind'],
 ['croque', 'crunches'],
 ['caisse', 'box'],
 ['blue', 'blue'],
 ['peste', 'plague'],
 ['constamment', 'constantly'],
 ['querelle', 'quarrel'],
 ['déranger', 'to disturb'],
 ['chouette', 'owl'],
 ['sain', 'healthy'],
 ['caisse', 'box'],
 ['patates', 'potatoes'],
 ["d'enfant", 'child'],
 ['caisse', 'box'],
 ["s'était", 'is silent'],
 ['chiffres', 'numbers'],
 ['veillé', 'day before'],
 ['demandait', 'asked'],
 ["d'efforts", 'of effort'],
 ['consiste', 'consists'],
 ['compliqué', 'complicated'],
 ["n'hésite", 'hesitate'],
 ['amasser', 'amass'],
 ['buts', 'goals'],
 ['bague', 'ring'],
 ["l'intention", 'the intention'],
 ["d'offrir", 'to offer'],
 ['black', 'black'],
 ['strange', 'strange'],
 ["n'allait", 'was not going'],
 ['prédilection', 'predilection'],
 ['allemand', 'German'],
 ['mondiaux', 'global'],
 ['graine', 'seed'],
 ['concentre', 'concentrate'],
 ['joutes', 'jousting'],
 ['gagnants', 'winners'],
 ['royaume', 'kingdom'],
 ['dérangé', 'disturbs'],
 ['fausse', 'false'],
 ["t'ont", 'you have'],
 ['habites', 'live'],
 ["l'oublier", 'forget it'],
 ['lanterne', 'lantern'],
 ['tournage', 'filming'],
 ['fabriquer', 'make'],
 ['treize', 'thirteen'],
 ['calmer', 'calm'],
 ['auteur', 'author'],
 ['préférés', 'favorites'],
 ["j'aille", "I'm going"],
 ['hôtels', 'hotels'],
 ['réaménagé', 'redeveloped'],
 ["d'horreur", 'horror'],
 ['auprès', 'with'],
 ['agréables', 'pleasant'],
 ["l'esprit", 'the mind'],
 ['sorties', 'exits'],
 ['voilier', 'sailing ship'],
 ['séjour', 'stay'],
 ['comprimée', 'compressed'],
 ['beurre', 'butter'],
 ['dirigé', 'directed'],
 ['troc', 'barter'],
 ['conçue', 'designed'],
 ['mamans', 'moms'],
 ["l'andouillette", 'the andouillette'],
 ['valise', 'suitcase'],
 ['tendre', 'tender'],
 ["n'irait", 'would not go'],
 ["puisqu'il", 'since he'],
 ['remorque', 'trailer'],
 ['bagage', 'luggage'],
 ["n'êtes", 'are not'],
 ['pipi', 'pee'],
 ['respirer', 'breathe'],
 ['limonade', 'lemonade'],
 ['inversée', 'reversed'],
 ['chine', 'China'],
 ['revends', 'resell'],
 ["s'inquiète", 'worries'],
 ['lattes', 'slats'],
 ['groupes', 'groups'],
 ['raccourcit', 'shortens'],
 ['logement', 'accommodation'],
 ['faiblesse', 'weakness'],
 ['profonde', 'deep'],
 ['bêtise', 'stupidity'],
 ['augmente', 'increase'],
 ['tarifs', 'prices'],
 ['destination', 'destination'],
 ['conduisent', 'drive'],
 ['directement', 'directly'],
 ['juil', 'jul'],
 ['promener', 'to take a walk'],
 ['suggère', 'suggests'],
 ['parlions', "let's talk"],
 ['breuer', 'breuer'],
 ['jarre', 'jar'],
 ['félicite', 'congratulate'],
 ['merveilleuse', 'wonderful'],
 ['commun', 'common'],
 ['paraisse', 'appears'],
 ['voyant', 'seeing'],
 ['évoquer', 'recall'],
 ["jusqu'en", 'until'],
 ['nettement', 'clearly'],
 ["t'assure", 'assure you'],
 ['into', 'into'],
 ['sauve', 'Safe'],
 ['fée', 'fairy'],
 ["jusqu'au", 'until'],
 ['fogon', 'fogon'],
 ['sautent', 'jump'],
 ["l'étang", 'the pond'],
 ["l'arbre", 'the tree'],
 ['replonge', 'dive back'],
 ['serrer', 'to squeeze'],
 ['cac', 'cac'],
 ['gagnerai', 'will win'],
 ['énormément', 'enormously'],
 ["m'achèterai", 'will buy me'],
 ["l'aurait", 'would have'],
 ["d'ailleurs", 'Besides'],
 ['voilier', 'sailing ship'],
 ['cadeaux', 'gifts'],
 ['souple', 'flexible'],
 ['louer', 'to rent out'],
 ['chouette', 'owl'],
 ['donnerais', 'would give'],
 ["n'aura", 'will not have'],
 ["s'acheter", 'to buy'],
 ['responsabilités', 'responsibilities'],
 ['décrocher', 'pick up'],
 ['convertir', 'convert'],
 ['concentre', 'concentrate'],
 ["s'entraîner", 'practice'],
 ['confie', 'entrusts'],
 ['extraordinaire', 'extraordinary'],
 ['pareille', 'similar'],
 ["d'agir", 'to act'],
 ['tartines', 'toasts'],
 ['extrêmement', 'extremely'],
 ['appétissante', 'appetizing'],
 ['craque', 'cracks'],
 ['glaces', 'ice cream'],
 ['glaces', 'ice cream'],
 ['marchand', 'merchant'],
 ['goûter', 'to taste'],
 ['rêvais', 'dreamed'],
 ["n'aurais", 'would not have'],
 ['paux', 'paux'],
 ['laissant', 'leaving'],
 ["s'occuper", 'take care'],
 ['profiter', 'enjoy'],
 ['bienne', 'well'],
 ['confie', 'entrusts'],
 ['noces', 'wedding'],
 ['voisine', 'neighbor'],
 ["d'attendre", 'to wait'],
 ['sortira', 'will come out'],
 ['disputez', 'argue'],
 ["l'est", 'ballast'],
 ['monty', 'monty'],
 ['chaussées', 'roadways'],
 ['troncs', 'trunks'],
 ["d'arbres", 'of trees'],
 ['balançoires', 'swings'],
 ['toboggans', 'slides'],
 ['rené', 'rein'],
 ['tipis', 'teepees'],
 ['originale', 'original'],
 ['ambiance', 'atmosphere'],
 ['cales', 'wedges'],
 ['enverrai', 'will send'],
 ['marine', 'Marine'],
 ['guise', 'as you wish'],
 ['kettering', 'kettering'],
 ['respecte', 'respect'],
 ['timing', 'timing'],
 ['unités', 'units'],
 ['shell', 'shell'],
 ['envoyés', 'sent'],
 ["l'eau", 'the water'],
 ['annulé', 'canceled'],
 ['bateaux', 'boats'],
 ['mégapole', 'megacity'],
 ['hostilité', 'hostility'],
 ['overbooké', 'overbooked'],
 ['atterri', 'landed'],
 ['excusez', 'excuse'],
 ['détente', 'relaxation'],
 ['comprenne', 'understand'],
 ['détente', 'relaxation'],
 ['excusez', 'excuse'],
 ['relaxnews', 'relaxnews'],
 ['cambodge', 'Cambodia'],
 ['distrait', 'distracted'],
 ['âgé', 'age'],
 ['bakwa', 'bakwa'],
 ['méritent', 'deserve'],
 ['fessée', 'spanking'],
 ['gamine', 'kid'],
 ['embouché', 'mouthed'],
 ['fichez', 'file'],
 ['traitez', 'treat'],
 ['sarreguemines', 'sarreguemines'],
 ['embouché', 'mouthed'],
 ['bijouterie', 'jewelry store'],
 ['adorable', 'adorable'],
 ['danseurs', 'dancers'],
 ['lasserre', 'lasserre'],
 ['pâtisseries', 'pastries'],
 ['aménagé', 'Finished'],
 ['respire', 'breathe'],
 ["l'harmonie", 'harmony'],
 ['piana', 'piana'],
 ['menteur', 'liar'],
 ['triplette', 'triplet'],
 ['baguette', 'baguette'],
 ['prétends', 'pretend'],
 ['monclar', 'monclar'],
 ['perversité', 'perversity'],
 ['tienne', 'hold on'],
 ['mènes', 'leads'],
 ['daba', 'daba'],
 ["t'assure", 'assure you'],
 ['fumes', 'smoke'],
 ['traîner', 'hang out'],

 ["d'enfin", 'finally'],
 ['détendre', 'loosen'],
 ['mesure', 'measure'],
 ['récolte', 'harvest'],
 ['sème', 'sow'],
 ['fiancée', 'fiancee'],
 ['doubs', 'doubles'],
 ['goûts', 'tastes'],
 ['chiotte', 'toilet'],
 ['fiancée', 'fiancee'],
 ['raccourci', 'shortcut'],
 ['raccourcis', 'shortcuts'],
 ['taper', 'type'],
 ['réseau', 'network'],
 ['vents', 'winds'],
 ['chauds', 'hot'],
 ['arbuste', 'shrub'],
 ['montmagny', 'montmagny'],
 ['capables', 'capable'],
 ['dépenser', 'spend'],
 ['andouille', 'andouille'],
 ['retournés', 'returned'],
 ['allemagne', 'Germany'],
 ['épousé', 'marry'],
 ['hisser', 'hoist'],
 ['rendais', 'returned'],
 ['villes', 'cities'],
 ['lunettes', 'glasses'],
 ['armure', 'armor'],
 ["l'intérieur", 'the interior'],
 ['indignité', 'indignity'],
 ['reviendras', 'will come back'],
 ['vibreur', 'vibrator'],
 ['viré', 'fired'],
 ['adil', 'adil'],
 ['gênés', 'Genoa'],
 ["d'employer", 'to use'],
 ['fondamentales', 'fundamental'],
 ['direz', 'you will say'],
 ['virée', 'trip'],
 ['tracassez', 'worry'],
 ['viré', 'fired'],
 ['ratez', 'miss'],
 ['paravent', 'screen'],
 ['couverts', 'Covered'],
 ['miroirs', 'mirrors'],
 ['envoient', 'send'],
 ["l'image", 'the image'],
 ['rassurante', 'reassuring'],
 ['règne', 'reign'],
 ['intègre', 'integrated'],
 ['vibreur', 'vibrator'],
 ['lâcheté', 'cowardice'],
 ["j'espère", 'I hope'],
 ["n'étais", "wasn't"],
 ['renoncé', 'renounced'],
 ['reprend', 'resumes'],
 ['rangée', 'row'],
 ['saouchi', 'saouchi'],
 ['effectivement', 'Effectively'],
 ['lion', 'lion'],
 ["l'empereur", 'the emperor'],
 ['sortes', 'kinds'],
 ['crèches', 'nurseries'],
 ['protègent', 'protect'],
 ['foie', 'liver'],
 ['forts', 'strong'],
 ['intelligents', 'intelligent'],
 ['indépendant', 'independent'],
 ['quasiment', 'nearly'],
 ['tiennent', 'hold'],
 ['refaire', 'redo'],
 ['sikasso', 'sikasso'],
 ['protège', 'protected'],
 ['fans', 'fans'],
 ['mangas', 'manga'],
 ['foire', 'fair'],
 ['francfort', 'frankfurt'],
 ['foire', 'fair'],
 ['toits', 'rooftops'],
 ['rougis', 'blush'],
 ['lâcher', 'let go'],
 ['francfort', 'frankfurt'],
 ['ôtez', 'take away'],
 ['concernant', 'concerning'],
 ['décisions', 'decisions'],
 ['julien', 'Julian'],
 ['cinglé', 'crazy'],
 ["l'administration", 'administration'],
 ['fiscale', 'tax'],
 ['renard', 'fox'],
 ["s'appelle", 'is called'],
 ['stolberg', 'stolberg'],
 ['brink', 'brink'],
 ["d'essayer", 'to try'],
 ["d'obtenir", 'to get'],
 ['échelonnement', 'staggering'],
 ["d'impôt", 'tax'],
 ['bouteilles', 'bottles'],
 ["l'irrésistible", 'the irresistible'],
 ['charte', 'charter'],
 ['splendeur', 'splendor'],
 ['ponctualité', 'punctuality'],
 ['poubelles', 'trash cans'],
 ['sauvegarde', 'backup'],
 ["m'entends", 'hear me'],
 ['chars', 'tanks'],
 ['joignable', 'reachable'],
 ['nizar', 'nizar'],
 ['stoke', 'stoke'],
 ['touches', 'keys'],
 ['stress', 'stress'],
 ["t'asseoir", 'sit down'],
 ['hurler', 'to yell'],
 ['défendu', 'defended'],
 ['affronter', 'confront'],
 ['fumier', 'manure'],
 ["qu'outre", 'that besides'],
 ['incite', 'encourages'],
 ['estomac', 'stomach'],
 ['branchée', 'trendy'],
 ['bluffer', 'bluff'],
 ['demeurer', 'remain'],
 ['conflits', 'Conflicts'],
 ['railleries', 'taunts'],
 ['poings', 'fists'],
 ['gênait', 'bothered'],
 ['devienne', 'become'],
 ['bompas', 'bompas'],
 ['jalouse', 'jealous'],
 ["d'oeil", 'eye'],
 ['discret', 'discreet'],
 ['rentrée', 'back to school'],
 ['souhaiteriez', 'would like'],
 ['fixement', 'fixedly'],
 ['mathématiques', 'mathematics'],
 ['prof', 'teacher'],
 ['ménage', 'household'],
 ['ratent', 'miss'],
 ["s'amuser", 'enjoy'],
 ['fit', 'fit'],
 ['adulte', 'adult'],
 ['gigantesque', 'gigantic'],
 ["m'efforce", 'I strive'],
 ['liés', 'related'],
 ["d'aucune", 'of none'],
 ['brique', 'brick'],
 ['terminées', 'finished'],
 ["d'exposition", 'exhibition'],
 ["s'abritera", 'will shelter'],
 ['triomphe', 'triumph'],
 ['tonique', 'tonic'],
 ['devrions', 'should'],
 ['tutoyer', 'to familiarize yourself'],
 ['fêter', 'to celebrate'],
 ['nerveuse', 'nervous'],
 ['hurd', 'hurd'],
 ['latif', 'latif'],
 ['maxxo', 'maxxo'],
 ['morton', 'morton'],
 ['nerveuse', 'nervous'],
 ["t'aime", 'love you'],
 ['assortis', 'assorted'],
 ['cravate', 'tie'],
 ['ponctuelle', 'punctual'],
 ['sitter', 'sitter'],
 ['vibreurs', 'vibrators'],
 ["m'appeler", 'call me'],
 ['attrapé', 'caught'],
 ['rubéole', 'rubella'],
 ["n'avons", "we don't have"],
 ["t'appelles", 'you call'],
 ['chips', 'chips'],
 ["d'être", 'to be'],
 ['gaufres', 'waffles'],
 ['vanoise', 'vanoise'],
 ['boule', 'ball '],
 ['ambulant', 'traveling'],
 ['différemment', 'differently'],
 ['accouche', 'gives birth'],
 ['annoncent', 'announce'],
 ['monts', 'mountains'],
 ['dégonfle', 'deflates'],
 ['merveilles', 'wonders'],
 ['winner', 'winner'],
 ['rentrée', 'back to school'],
 ['appart', 'apartment'],
 ['abattu', 'beaten down'],
 ['pleurant', 'crying'],
 ['larmes', 'tears'],
 ['refusant', 'refusing'],
 ["d'expliquer", 'to explain'],
 ['romantique', 'romantic'],
 ["d'abruti", 'idiot'],
 ['dorénavant', 'from now on'],

 ["m'énerves", 'annoy me'],
 ['croient', 'believe'],
 ["j'essaie", 'I try'],
 ['gâche', 'spoils'],
 ['hauteur', 'height'],
 ['voyait', 'saw'],
 ['poutres', 'beams'],
 ['oeuvre', 'artwork'],
 ['géniaux', 'awesome'],
 ['résolu', 'resolved'],
 ["t'envoyer", 'send you'],
 ["d'affreuses", 'awful'],
 ['conçu', 'designed'],
 ['caisses', 'crates'],
 ['dacquois', 'dacquois'],
 ['concevoir', 'design'],
 ["l'avez", 'have it'],
 ['deviné', 'guess'],
 ['poubelle', 'garbage can'],
 ["lorsqu'il", 'when he'],
 ["j'arrête", 'I stop'],
 ['arrêtiez', 'stop'],
 ['viendrai', 'will come'],
 ['lande', 'moor'],
 ['estiment', 'estimate'],
 ['réjouit', 'rejoices'],
 ['pleurez', 'cry'],
 ['repartirai', 'will leave again'],
 ["qu'après", 'that after'],
 ['démissionné', 'resigned'],
 ['valait', 'was worth'],
 ['décevra', 'will disappoint'],
 ['uniquement', 'uniquely'],
 ['boucles', 'loops'],
 ['salaire', 'salary'],
 ['fermant', 'closing'],
 ['noyer', 'walnut'],
 ['dunoyer', 'dunoyer'],
 ['uniquement', 'uniquely'],
 ['suffisamment', 'enough'],
 ['tenter', 'to attempt'],
 ['pourrions', 'could'],
 ['reviendrez', 'will come back'],
 ['souhaité', 'wish'],
 ["qu'associé", 'that associate'],
 ['évidemment', 'obviously'],
 ['raisonnes', 'reasons'],
 ['promènent', 'walk'],
 ['taches', 'tasks'],
 ['récompenses', 'rewards'],
 ['prestigieuses', 'prestigious'],
 ["j'avance", 'I advance'],
 ['accompli', 'accomplished'],
 ['proposé', 'propose'],
 ['mignonne', 'cute'],
 ["d'antan", 'from yesteryear'],
 ['soirées', 'evenings'],
 ['foncé', 'dark'],
 ['prenant', 'taking'],
 ['enfuis', 'ran away'],
 ['crécy', 'crecy'],
 ['durement', 'hard'],
 ['défauts', 'defaults'],
 ['changera', 'will change'],
 ["l'as", 'the ace'],
 ["qu'avec", 'that with'],
 ['relèvera', 'will raise'],
 ["l'étoile", 'the star'],
 ['quotidien', 'daily'],
 ['juifs', 'Jews'],
 ['merveilleusement', 'wonderfully'],
 ["s'entend", 'hear'],
 ['vues', 'views'],
 ['dessin', 'drawing'],
 ['abandonné', 'abandoned'],
 ['pardonnerai', 'will forgive'],
 ['douloureux', 'painful'],
 ["d'autant", 'especially'],
 ['ressenti', 'feeling'],
 ['semblais', 'seemed'],
 ["j'attendrai", "I'll wait"],
 ['déçu', 'disappointed'],
 ["t'aurais", 'you would have'],
 ["l'aiment", 'love it'],
 ['gâches', 'strikers'],
 ["d'animal", 'animal'],
 
 ];
 
