let hebrew = [["לא ", "No"],
["את ", "You"],
["אני ", "I am"],
["זה ", "It"],
["אתה ", "are you"],
["מה ", "what"],
["הוא ", "he"],
["לי", "to me"],
["על", "On"],
["כן", "Yes"],
["לך", "to you"],
["של", "of"],
["יש ", "there is"],
["בסדר ", "OK"],
["אבל ", "but"],
["כל ", "all"],
["שלי ", "My"],
["טוב ", "are good"],
["עם", "With"],
["היא", "She"],
["אם", "If"],
["רוצה", "wants to"],
["שלך", "your"],
["היה", "Was"],
["אנחנו", "we"],
["הם", "they"],
["אותך", "you"],
["יודע", "Know"],
["אז", "Then"],
["רק", "only"],
["אותו", "him"],
["יכול", "Might"],
["אותי", "me"],
["יותר", "More"],
["הזה", "this"],
["אל", "to"],
["כאן", "Here"],
["או", "or"],
["למה", "Why"],
["שאני", "I"],
["כך", "so"],
["אחד", "one"],
["עכשיו", "now"],
["משהו", "something"],
["להיות", "to be"],
["היי", "Hey"],
["תודה", "Thanks"],
["כמו", "same as"],
["אין", "nothing"],
["זאת", "this"],
["איך", "how"],
["נכון", "Right"],
["מי", "who will"],
["שם", "Name"],
["לו", "to him"],
["צריך", "Must"],
["לעשות", "to do"],
["קדימה", "forward"],
["לנו", "us"],
["חושב", "thinking"],
["כמה", "Some"],
["שאתה", "You"],
["זו", "this"],
["גם", "also"],
["יודעת", "Know"],
["אותה", "her"],
["עוד", "More"],
["באמת", "really"],
["הייתי", "I was"],
["שהוא", "that he"],
["אולי", "Maybe"],
["בבקשה", "you are welcome"],
["עושה", "Doing"],
["פשוט", "simple"],
["שזה", "of such"],
["דבר", "Nothing"],
["מאוד", "is very"],
["כבר", "already"],
["שלא", "That"],
["נראה", "seen"],
["לעזאזל", "Damn"],
["אתם", "you"],
["כדי", "In order to"],
["ואני", "And I"],
["פה", "Here"],
["אלוהים", "God"],
["הנה", "here"],
["פעם", "time"],
["האם", "the mother"],
["בוא", "Let's"],
["שלו", "His"],
["איפה", "where"],
["הרבה", "Much"],
["כי", "Because"],
["יכולה", "Can"],
["שלנו", "our"],
["אומר", "Says"],
["יהיה", "will be"],
["אותם", "them"],
["עד", "Until"],
["קצת", "Some"],
["לפני", "before"],
["זמן", "time"],
["הכל", "Everything"],
["ממש", "really"],
["אבא", "father"],
["הולך", "Going"],
["מר", "Mr"],
["אדוני", "The lord"],
["לראות", "See"],
["ובכן", "Well"],
["מישהו", "someone"],
["חייב", "have to"],
["עדיין", "Yet"],
["לה", "her"],
["אף", "Nose"],
["בכל", "in all"],
["בדיוק", "exactly"],
["היום", "Today"],
["אנשים", "people"],
["ללכת", "go"],
["מצטער", "Sorry"],
["היית", "Would you"],
["שלום", "Peace"],
["קרה", "Happened"],
["שוב", "again"],
["אוהב", "Love"],
["אחת", "One"],
["הייתה", "was"],
["אמא", "mother"],
["חשבתי", "I thought"],
["בן", "son"],
["איזה", "Which"],
["יום", "a day"],
["לדבר", "Speak"],
["תמיד", "Always"],
["צריכה", "consumption"],
["לזה", "It"],
["חושבת", "Think"],
["להם", "to them"],
["היו", "there were"],
["שאת", "You"],
["שיש", "That"],
["רואה", "Views"],
["אפילו", "Even"],
["בטח", "Probably"],
["כולם", "Everyone"],
["בגלל", "Because of"],
["שום", "garlic"],
["שהיא", "It"],
["אחר", "Other"],
["חבר", "Friend"],
["בשביל", "For"],
["קורה", "Happens"],
["איתך", "with your"],
["הזאת", "this"],
["אמרתי", "I said"],
["אדם", "A person"],
["תן", "Make"],
["צריכים", "Need"],
["הזמן", "the time"],
["יכולים", "can"],
["ואז", "and then"],
["כלום", "is nothing"],
["רגע", "moment"],
["האלה", "these"],
["אחרי", "after"],
["מבין", "Understand"],
["תראה", "Look"],
["בטוח", "Sure"],
["שהם", "that they"],
["לכם", "to you"],
["בו", "at him"],
["אמר", "said"],
["מדי", "every"],
["ג", "third"],
["טובה", "favor"],
["אותנו", "us"],
["תהיה", "Will be"],
["אנו", "we"],
["אך", "but"],
["ככה", "So"],
["בזה", "plunder"],
["יפה", "Beautiful"],
["כזה", "such a"],
["אוכל", "Food"],
["מותק", "honey"],
["מספיק", "enough"],
["בואו", "Come"],
["אפשר", "Allow"],
["שלה", "its"],
["דברים", "Stuff"],
["הכי", "the most"],
["מזה", "from this"],
["מקום", "Place"],
["בואי", "Bowie"],
["לכאן", "Here"],
["אה", "Oh"],
["בבית", "House"],
["דרך", "way"],
["איתי", "With me"],
["מתכוון", "Going"],
["ביותר", "most"],
["הביתה", "Home"],
["לומר", "to tell"],
["אחי", "Brother"],
["מת", "dead"],
["הזו", "This"],
["ה", "God"],
["הדבר", "the thing"],
["מדבר", "Speak"],
["שאנחנו", "We"],
["לעזור", "help"],
["לעולם", "forever"],
["זהו", "This"],
["לדעת", "know"],
["כאילו", "like"],
["גדול", "big"],
["אוהבת", "Love"],
["שנים", "Years"],
["בי", "Me"],
["מכאן", "hence"],
["יודעים", "Know"],
["לקחת", "to take"],
["ראיתי", "have seen"],
["בלי", "without"],
["נהדר", "magnificent"],
["די", "enough"],
["כסף", "Of money"],
["הו", "Oh"],
["היתה", "was"],
["מהר", "Faster"],
["עליי", "Me"],
["י", "The"],
["מצטערת", "Sorry"],
["וזה", "and this"],
["ילד", "Boy"],
["לשם", "opal"],
["קשה", "Hard"],
["חכה", "Fishing rod"],
["לאן", "where"],
["ואתה", "And you"],
["ממני", "from me"],
["ו", "and"],
["תגיד", "Tell"],
["רוצים", "Want"],
["שני", "Crimson"],
["הלילה", "The night"],
["עליך", "You must"],
["כמובן", "of course"],
["עליו", "It"],
["נחמד", "Nice"],
["לכל", "to all"],
["להגיד", "say"],
["סליחה", "Sorry"],
["אמרת", "you said"],
["ל", "To"],
["מוכן", "prepared"],
["מחר", "tomorrow"],
["בא", "come"],
["ולא", "And"],
["והוא", "and he"],
["אוקיי", "OK"],
["אומרת", "Says"],
["גברת", "Lady"],
["בך", "in you"],
["נלך", "Go"],
["בית", "House"],
["מעולם", "Ever"],
["שלהם", "their"],
["אי", "an island"],
["הבחור", "the guy"],
["עבודה", "Working"],
["למצוא", "find"],
["נמצא", "available"],
["חייבים", "Must"],
["מכיר", "Know"],
["מנסה", "Try"],
["ב", "B"],
["ואת", "and you"],
["מתי", "When"],
["תעשה", "Make"],
["בשבילך", "For you"],
["מספר", "A number"],
["כדאי", "worthwhile"],
["דקות", "subtlety"],
["שלכם", "your"],
["האמת", "Truth"],
["עושים", "Do"],
["אלה", "goddess"],
["חייבת", "must"],
["דולר", "dollar"],
["הכסף", "the money"],
["כעת", "Now"],
["לילה", "night"],
["איש", "man"],
["עלי", "pestle"],
["לצאת", "to go out"],
["רציתי", "I wanted to"],
["לתת", "Give"],
["בחור", "a guy"],
["בכלל", "at all"],
["איתו", "With"],
["רע", "Bad"],
["עשית", "You did"],
["מרגיש", "feels"],
["הכול", "All"],
["בעיה", "problem"],
["עבור", "for"],
["אמור", "supposed"],
["לקבל", "Get"],
["עובד", "Employee"],
["בנאדם", "Man"],
["הולכים", "Going"],
["החיים", "Life"],
["נוכל", "We can"],
["מאמין", "Believe"],
["סוף", "end"],
["ידעתי", "I have known"],
["הולכת", "Going"],
["לב", "heart"],
["בחייך", "Come on"],
["היכן", "where"],
["שנה", "sleep"],
["זוכר", "Remember"],
["ממך", "from you"],
["הגיע", "have come"],
["קטן", "Little"],
["החוצה", "outside"],
["תוכל", "will be able to"],
["בזמן", "On time"],
["הן", "they"],
["ילדים", "Children"],
["נשמע", "audible"],
["חיים", "Haim"],
["בדרך", "through"],
["אכפת", "concern"],
["נעשה", "has been done"],
["הבית", "Home"],
["ש", "That"],
["ידי", "By"],
["בוקר", "Morning"],
["עשה", "Made"],
["לחזור", "Return"],
["המקום", "the place"],
["הבא", "the next"],
["מקווה", "Hope"],
["קח", "take"],
["עשיתי", "I did"],
["חשוב", "It is important"],
["הי", "Hi"],
["אלו", "These"],
["בחיים", "alive"],
["גבר", "man"],
["ללא", "with no"],
["במקום", "instead of"],
["משנה", "Mishna"],
["הלו", "Hello?"],
["להרוג", "to kill"],
["שמעתי", "I heard"],
["העולם", "the world"],
["ספר", "Book"],
["ר", "R"],
["זונה", "whore"],
["עצמך", "yourself"],
["האנשים", "the people"],
["למעלה", "up"],
["בני", "my son"],
["לגבי", "About"],
["מאוחר", "late"],
["כמעט", "almost"],
["תראי", "Look"],
["לספר", "tell"],
["בקשר", "Connection"],
["שמח", "happy"],
["להתראות", "See you"],
["לבד", "Own"],
["הדרך", "the road"],
["האלו", "These"],
["שלוש", "three"],
["יופי", "Beauty"],
["לגמרי", "Completely"],
["מדוע", "why"],
["אליך", "You"],
["מפה", "from here"],
["קודם", "previous"],
["ראית", "Have you seen"],
["למטה", "down"],
["בה", "in her"],
["להגיע", "to arrive"],
["חלק", "Smooth"],
["מגיע", "is coming"],
["מ", "M"],
["בין", "between"],
["לבוא", "come"],
["אתן", "you"],
["היינו", "We were"],
["חרא", "Shit"],
["הדברים", "Things"],
["תפסיק", "Stop"],
["אחרת", "Other"],
["לשמוע", "Listen"],
["מזל", "luck"],
["המפקד", "the commander"],
["בחוץ", "outside"],
["אהיה", "Will be"],
["הספר", "the book"],
["אליי", "Me"],
["ערב", "evening"],
["תקשיב", "Listen"],
["אישה", "wife"],
["השני", "The second"],
["לחשוב", "to think"],
["הערב", "this evening"],
["מבינה", "Understand"],
["מיד", "immediately"],
["בשבילי", "For me"],
["למעשה", "in fact"],
["אוי", "Woe"],
["הראשון", "the first one"],
["אלי", "to me"],
["תני", "Give"],
["א", "A"],
["חברים", "Friends"],
["בטוחה", "Secure"],
["רבה", "Great"],
["ומה", "What"],
["מאז", "since"],
["ביום", "on the day"],
["במשך", "During"],
["בהחלט", "Definitely"],
["עלינו", "Us"],
["ון", "Wen"],
["לעבוד", "work"],
["השם", "the Name"],
["כולנו", "We all"],
["לאחר", "after the"],
["הראשונה", "First"],
["למען", "address"],
["מניח", "assumes"],
["מוזר", "mozar"],
["בתוך", "Inside"],
["איזו", "What"],
["חזק", "strong"],
["העבודה", "the job"],
["מהם", "from them"],
["לפחות", "at least"],
["אמרה", "saying"],
["האיש", "Man"],
["ביחד", "together"],
["כנראה", "Probably"],
["שיהיה", "Will be"],
["בת", "a girl"],
["אלא", "But rather"],
["הבעיה", "The problem"],
["כאשר", "by the time"],
["ימים", "Days"],
["ואם", "Or"],
["אימא", "Mother"],
["קטנה", "Small"],
["ברגע", "in the moment"],
["אתכם", "you"],
["אעשה", "I will"],
["איני", "I do not"],
["הדלת", "The door"],
["משחק", "Play"],
["חדש", "New"],
["בעוד", "while"],
["סתם", "mere"],
["לבית", "to house"],
["בחזרה", "Back to"],
["לאכול", "eat"],
["להביא", "bring"],
["אתמול", "Yesterday"],
["נורא", "Horrible"],
["תראו", "Look"],
["אדירים", "Christ"],
["יחד", "together"],
["גדולה", "greatness"],
["בעולם", "World"],
["חתיכת", "Piece"],
["לפעמים", "sometimes"],
["מקרה", "case"],
["בפנים", "in"],
["נו", "Nov"],
["עומד", "standing"],
["ברור", "Obviously"],
["אבי", "Avi"],
["הפעם", "Time"],
["ממנו", "from him"],
["שעות", "Hours"],
["שלומך", "How are you"],
["בלילה", "At night"],
["אומרים", "They say"],
["מתכוונת", "Plans"],
["אינך", "You do not"],
["הילד", "the boy"],
["כרגע", "Currently"],
["האחרון", "the last one"],
["ביי", "Bye"],
["הא", "Ha"],
["טובים", "Good"],
["העיר", "City"],
["חיי", "Life"],
["הילדים", "the children"],
["נראית", "Look"],
["חכי", "Wait"],
["יהיו", "Will"],
["למות", "die"],
["מצחיק", "is funny"],
["חוץ", "outside"],
["תורגם", "Translated"],
["שהיה", "Was"],
["חזרה", "return"],
["מאד", "Very"],
["הראש", "the head"],
["רעיון", "idea"],
["הרגע", "calm down"],
["אהבה", "Love"],
["לשאול", "to ask"],
["להישאר", "to stay"],
["שאתם", "You"],
["יקרה", "dear"],
["מושג", "obtained"],
["בלתי", "non"],
["איתה", "With"],
["להשיג", "to reach"],
["ראש", "head"],
["יכולתי", "I could"],
["תחת", "under"],
["עצמי", "myself"],
["מכל", "tank"],
["קוראים", "Call"],
["אליו", "to his"],
["שמעת", "You heard"],
["כ", "about"],
["להיכנס", "to enter"],
["אמיתי", "TRUE"],
["הבן", "the son"],
["תסתכל", "Look"],
["כלומר", "That is"],
["חברה", "Company"],
["עליה", "Increase"],
["והיא", "and she"],
["ילדה", "Girl"],
["לשחק", "to play"],
["העניין", "the matter"],
["ועכשיו", "Now"],
["קשר", "link"],
["הגדול", "Great"],
["לעזוב", "leave"],
["החבר", "the friend"],
["נפלא", "Wonderful"],
["האחרונה", "Latest"],
["חמש", "five"],
["בפעם", "Time"],
["עצור", "under arrest"],
["כפי", "as"],
["לישון", "sleep"],
["שתי", "two"],
["צודק", "right"],
["וגם", "and also"],
["שלושה", "three"],
["ליד", "next to"],
["לחיות", "live"],
["קרוב", "Close"],
["רב", "multi"],
["נגמר", "is over"],
["לקרוא", "to read"],
["שאין", "That"],
["תא", "cell"],
["תדאג", "Worry"],
["יוצא", "outgoing"],
["האדם", "Person"],
["והם", "And"],
["גמור", "finished"],
["בבוקר", "in the morning"],
["קל", "easy"],
["מתה", "Dead"],
["באופן", "In"],
["בשם", "on behalf of"],
["מעט", "A little"],
["הבאה", "Next"],
["יורק", "York"],
["מוכנה", "Ready"],
["היחיד", "Only"],
["לכן", "so"],
["תגידי", "Tell"],
["חי", "live"],
["חצי", "Half"],
["איי", "Islands"],
["לוקח", "Takes"],
["נעים", "Pleasant"],
["נהיה", "yearning"],
["לעצור", "to stop"],
["גרוע", "bad"],
["לפגוש", "meet"],
["נשים", "women"],
["שעה", "hour"],
["נגד", "against"],
["הטוב", "the good"],
["מים", "water"],
["חושבים", "Think"],
["ממה", "What"],
["פנימה", "inside"],
["מרגישה", "Feeling"],
["לפה", "Here"],
["שתיים", "two"],
["וכל", "and all"],
["אסור", "forbidden"],
["פנים", "face"],
["שכל", "cerebro"],
["מתחיל", "starting up"],
["אשר", "which"],
["אותן", "them"],
["היחידה", "Only"],
["שומע", "Hears"],
["כמוך", "Like you"],
["בקרוב", "soon"],
["לנצח", "Win"],
["המכונית", "Car"],
["מחוץ", "Out"],
["בחורה", "girl"],
["חוזר", "circular"],
["להבין", "to understand"],
["הבנתי", "I realised"],
["עלייך", "You"],
["לעבור", "pass"],
["בערך", "About"],
["פעמים", "twice"],
["בחדר", "Room"],
["וואו", "Wow"],
["כאלה", "Like"],
["קיבלתי", "I got"],
["לכי", "Go"],
["חודשים", "Months"],
["אלך", "I will go"],
["ארוחת", "Breakfast"],
["סוג", "Type"],
["מדברת", "Talks"],
["מכירה", "sale"],
["מאמינה", "believe"],
["כה", "so"],
["זקוק", "Need"],
["הקטן", "Small"],
["אידיוט", "idiot"],
["מדהים", "Amazing"],
["מצאתי", "Found"],
["הסיבה", "The reason"],
["אינני", "I do not"],
["בנות", "girls"],
["בתור", "as a"],
["לשמור", "Preserve"],
["החברה", "Company"],
["להמשיך", "continue"],
["התחת", "Ass"],
["כשאני", "When I"],
["שמי", "Semitic"],
["נתראה", "see you later"],
["ימי", "maritime"],
["הסיפור", "Story"],
["שכן", "Neighbor"],
["סיפור", "a story"],
["בצורה", "In"],
["אקח", "Take"],
["סלח", "Forgive"],
["לזוז", "move"],
["רציני", "serious"],
["הכבוד", "Honor"],
["שמישהו", "Someone"],
["פחות", "less"],
["מדברים", "talking"],
["שאלה", "a question"],
["סיכוי", "Chance"],
["מתחת", "Below"],
["אחרים", "others"],
["הללו", "these"],
["נכנס", "Entered"],
["תביא", "Bring"],
["התכוונתי", "I meant"],
["שהייתי", "I"],
["הבוקר", "Breakfast"],
["ראשון", "First"],
["באותו", "in the same"],
["בחורים", "Guys"],
["בהם", "in them"],
["לנסות", "try"],
["להשתמש", "to use"],
["אדון", "sir"],
["במה", "in what"],
["שווה", "Equal"],
["זוכרת", "Remember"],
["טיפש", "Stupid"],
["מיליון", "one million"],
["מוכנים", "Ready"],
["להתחיל", "Begin"],
["להראות", "show"],
["אנג", "Ang"],
["אראה", "Show"],
["מלא", "full"],
["המשפחה", "The family"],
["לפי", "as per"],
["מאשר", "than"],
["פרנק", "franc"],
["מטורף", "crazy"],
["לכך", "This"],
["שבוע", "week"],
["מגניב", "Cool"],
["צא", "go out"],
["ואנחנו", "And we"],
["לתוך", "into"],
["לחכות", "wait"],
["מאיפה", "Where"],
["איתנו", "Us"],
["מחדש", "re"],
["דעתך", "your opinion"],
["שונה", "different"],
["חסר", "short"],
["תוך", "within"],
["נותן", "gives"],
["לקנות", "buy"],
["להכיר", "get to know"],
["הבחורה", "Girl"],
["ינא", "Lina"],
["מחפש", "Looking for"],
["שבו", "sit"],
["ישר", "Straight"],
["חדשות", "news"],
["חדר", "a room"],
["אש", "fire"],
["אפשרי", "possible"],
["מצוין", "excellent"],
["הלא", "Non"],
["ים", "sea"],
["מתוקה", "Sweetheart"],
["עזרה", "help"],
["שאם", "That if"],
["מעולה", "Excellent"],
["כדור", "ball"],
["תירגע", "cool down"],
["אמרו", "Said"],
["באה", "Coming"],
["החדש", "New"],
["בעיות", "Boll"],
["שאנו", "We"],
["המצב", "The situation"],
["הלך", "Gone"],
["לשתות", "drink up"],
["מעבר", "transition"],
["מעל", "above"],
["טעות", "Mistake"],
["כשאתה", "when you are"],
["עבר", "Moved"],
["עליהם", "on them"],
["נשאר", "remaining"],
["ויש", "And"],
["שב", "Again"],
["מייקל", "Michael"],
["אלף", "Thousand"],
["לקח", "Lesson"],
["ארבע", "Four"],
["סיבה", "Reason"],
["מצב", "Situation"],
["מן", "from"],
["מסוגל", "Able"],
["מידי", "from"],
["להרגיש", "to feel"],
["בעל", "husband"],
["משפחה", "Family"],
["שזו", "It"],
["שוטר", "Cop"],
["בחיי", "My life"],
["מעניין", "interesting"],
["ההוא", "that"],
["קפה", "coffee"],
["הזדמנות", "opportunity"],
["כלב", "Dog"],
["כלל", "rule"],
["מקבל", "getting"],
["שונא", "Hate"],
["מחכה", "am waiting"],
["מפני", "because"],
["זין", "dick"],
["תחזור", "Return"],
["שקט", "Quiet"],
["באתי", "I came"],
["מוצא", "exit"],
["אביך", "hazy"],
["ניסיתי", "I tried"],
["תקשיבי", "Listen"],
["חן", "Grace"],
["מצוות", "Commandments"],
["רוח", "Breeze"],
["מוקדם", "early"],
["קפטן", "Captain"],
["תהיי", "Be"],
["מאיתנו", "Us"],
["מבטיח", "promising"],
["מושלם", "perfect"],
["ידעת", "Did you know"],
["עניין", "Interest"],
["כוח", "Force"],
["המון", "Lots"],
["פי", "times"],
["חולה", "Sick"],
["אוהבים", "Like"],
["אינו", "Does not"],
["דם", "blood"],
["הנשיא", "The President"],
["משם", "From"],
["למרות", "Although"],
["גורם", "Factor"],
["לאט", "slowly"],
["כבוד", "respect"],
["ס", "S."],
["בעבר", "Previously"],
["להתקשר", "Contact"],
["אלייך", "to you"],
["משוגע", "crazy"],
["עשר", "ten"],
["ללמוד", "Learn"],
["שטויות", "Nonsense"],
["בנוגע", "About"],
["צוחק", "Laughing"],
["לבדוק", "to check"],
["בצד", "aside"],
["להאמין", "to believe"],
["חדשה", "new"],
["עצמו", "himself"],
["לגרום", "cause"],
["המשחק", "Game"],
["שרה", "Sarah"],
["לעצמך", "Yourself"],
["במיוחד", "especially"],
["המשטרה", "the police"],
["צוות", "Staff"],
["אחזור", "be back"],
["שאמרתי", "I said"],
["גברים", "Men"],
["קורא", "reader"],
["בראש", "in mind"],
["רחוק", "far away"],
["למקום", "Place"],
["לשלם", "pay"],
["להפסיק", "stop"],
["מיוחד", "Special"],
["הז", "Seventh"],
["שמו", "His name"],
["שמחה", "joy"],
["כיף", "fun"],
["אגיד", "Tell"],
["למי", "whom"],
["ניתן", "You can"],
["מאחורי", "Behind"],
["תמשיך", "carry on"],
["כיצד", "how"],
["להוציא", "Remove"],
["מתים", "Dead"],
["כולכם", "All"],
["אצל", "at"],
["חבל", "Too bad"],
["האישה", "Woman"],
["לעצמי", "Myself"],
["גברתי", "Madam"],
["תוכלי", "You can"],
["רואים", "View"],
["דוד", "Uncle"],
["להציל", "to rescue"],
["שצריך", "Properly"],
["בעלי", "With"],
["דוקטור", "Doctor"],
["חג", "Holiday"],
["לעבודה", "for work"],
["בוודאי", "for sure"],
["תעשי", "Do"],
["הוד", "glory"],
["מילה", "Circumcision"],
["ברצינות", "seriously"],
["הארץ", "Country"],
["עשינו", "We did"],
["לאנשים", "People"],
["רצה", "Wanted"],
["www", "www"],
["עזוב", "abandoned"],
["יצא", "went out"],
["נתן", "Nathan"],
["שניות", "Seconds"],
["בעיר", "City"],
["סי", "si"],
["חשבת", "Thought"],
["שאלות", "Questions"],
["אלינו", "to us"],
["ידע", "knowledge"],
["תנו", "Let the"],
["לשים", "to put"],
["שאולי", "Maybe"],
["בכך", "in so doing"],
["יכולת", "ability"],
["אן", "Anne"],
["היד", "Hand"],
["שאוכל", "I can"],
["מין", "sex"],
["דקה", "Minute"],
["לדאוג", "worry"],
["שמה", "her name"],
["תרצה", "Want"],
["ראה", "See"],
["הצילו", "H E L P"],
["נוסף", "additional"],
["החרא", "Shit"],
["אופן", "Manner"],
["כשהוא", "When he"],
["צעיר", "young"],
["הפה", "the mouth"],
["עולה", "Costs"],
["עובדת", "Working"],
["שמך", "Your Name"],
["לתפוס", "to fetch"],
["נמצאת", "Is"],
["כלבה", "bitch"],
["האקדח", "Gun"],
["עדיף", "preferable"],
["הטלפון", "Phone"],
["טום", "Tom"],
["פול", "broad bean"],
["חכו", "Wait"],
["קר", "cold"],
["תלך", "Go"],
["במקרה", "by any chance"],
["יעשה", "Will"],
["שניכם", "you both"],
["הארי", "Harry"],
["זוז", "MOVE"],
["יקירתי", "Darling"],
["בהצלחה", "Successfully"],
["לשבת", "to sit down"],
["אנא", "please"],
["דין", "law"],
["מכיוון", "Because"],
["יד", "Hand"],
["הקטנה", "Small"],
["לבן", "white"],
["בנו", "they built"],
["בעצמי", "myself"],
["יין", "wine"],
["תוריד", "Take off"],
["למישהו", "Someone"],
["מייק", "Mike"],
["מול", "Against"],
["נזוז", "Move"],
["ככל", "As the"],
["הלוואי", "Wish"],
["בעצמך", "Yourself"],
["לרגע", "for a moment"],
["קשור", "Related"],
["בשקט", "quietly"],
["האל", "Hal"],
["ישנה", "There"],
["מעמד", "status"],
["כזאת", "Such a"],
["torec", "torec"],
["רד", "Red"],
["אחורה", "backwards"],
["איכפת", "Cares"],
["איתם", "with them"],
["ממנה", "from her"],
["חם", "hot"],
["מבקש", "Asks"],
["שש", "six"],
["מידע", "information"],
["השנה", "Year"],
["אכן", "indeed"],
["אהבתי", "I liked"],
["בשעה", "At"],
["בסוף", "at the end"],
["שקרה", "Happened"],
["לכו", "Go"],
["אליה", "to her"],
["לבחור", "to choose"],
["תחשוב", "Think"],
["ספק", "Doubt"],
["המים", "the water"],
["הפנים", "Interior"],
["לכולם", "for everyone"],
["תדאגי", "Worry"],
["קחי", "Take"],
["שתוק", "Shut"],
["לברוח", "escape"],
["מתוק", "sweet"],
["ארלי", "Early"],
["התיק", "the bag"],
["שים", "Please"],
["מישהי", "Someone"],
["לקרות", "To happen"],
["לטפל", "handle"],
["לחפש", "to look for"],
["הידיים", "Hands"],
["ח", "Eighth"],
["במצב", "Condition"],
["ואל", "And"],
["צ", "Czech"],
["מניחה", "Puts"],
["לירות", "shoot"],
["ידיים", "hands"],
["שניים", "two"],
["עשרה", "ten"],
["אילו", "which"],
["יוכל", "Could"],
["חמוד", "cute"],
["ריי", "Ray"],
["נשק", "Weapon"],
["בשבוע", "A week"],
["מכונית", "car"],
["זוזו", "Zuzu"],
["פיטר", "Peter"],
["באים", "Coming"],
["לחיים", "for life"],
["להחזיר", "to return"],
["מאחור", "behind"],
["רוב", "majority"],
["הרוחות", "the winds"],
["לנסוע", "travel"],
["לחלוטין", "completely"],
["לחדר", "Room"],
["תזדיין", "Fuck"],
["שנייה", "second"],
["תוכנית", "Program"],
["מסוכן", "dangerous"],
["להסביר", "explain"],
["ורג", "Georgia"],
["עשו", "did"],
["זוהי", "This"],
["היטב", "well"],
["שאמרת", "You said"],
["שמע", "Audio"],
["רבים", "many"],
["בוב", "Bob"],
["הלב", "the heart"],
["לעמוד", "to stand"],
["שבועות", "Weeks"],
["מפחד", "Afraid"],
["באמצע", "in the middle of"],
["אח", "brother"],
["מוות", "Death"],
["לאף", "Any"],
["יימס", "James"],
["ישו", "Jesus"],
["חכם", "smart"],
["נשבע", "Swear"],
["משום", "Because"],
["המלך", "the king"],
["המשפט", "Court"],
["מערכת", "editorial board"],
["פני", "penny"],
["השבוע", "This Week"],
["טובות", "Good"],
["מתאים", "appropriate"],
["ק", "K."],
["המדינה", "Country"],
["רצח", "murder"],
["יי", "Yi"],
["המוות", "Death"],
["למשטרה", "The police"],
["להגן", "protect"],
["אמורה", "Should"],
["להודות", "to thank"],
["טלפון", "phone"],
["שתהיה", "Will be"],
["ישן", "Old"],
["החולים", "Patients"],
["תישאר", "Stay"],
["הודעה", "message"],
["שהיית", "You"],
["הבת", "Daughter"],
["שנינו", "Both"],
["net", "net"],
["ד", "Fourth"],
["אהה", "Aha"],
["באיזה", "What"],
["אתך", "You"],
["ודאי", "certainly"],
["אשתי", "my wife"],
["שכחתי", "I forgot"],
["ברוך", "blessed"],
["אוקי", "Ok"],
["שנוכל", "We can"],
["ועוד", "And more"],
["מיס", "Miss"],
["בסביבה", "Around"],
["מכם", "radar"],
["גר", "G"],
["השאר", "Leave"],
["תעזוב", "Leave"],
["הקטע", "Section"],
["חייך", "Your life"],
["גבוה", "Tall"],
["נדבר", "Talk"],
["תפסיקי", "Stop"],
["יעזור", "will help"],
["בובי", "Bobby"],
["כמוני", "like my"],
["תצטרך", "You will need"],
["הבאתי", "I brought"],
["מתוך", "of"],
["סבתא", "grandmother"],
["מצפה", "Expect"],
["הסרט", "the film"],
["עבורך", "You"],
["אצטרך", "I will have"],
["שמור", "Save"],
["יו", "Yo"],
["הבנת", "Understanding"],
["להשאיר", "leave"],
["בכלא", "in jail"],
["החלק", "Part"],
["לפגוע", "Hurt"],
["נמצאים", "present"],
["מלחמה", "war"],
["סאם", "Sam"],
["לשנות", "To change"],
["קיבלת", "you received"],
["שחור", "black"],
["אקדח", "gun"],
["סקס", "sex"],
["העיניים", "Eyes"],
["התינוק", "the baby"],
["הילדה", "Girl"],
["לבקש", "to ask"],
["שמונה", "eight"],
["סרט", "movie"],
["וני", "Johnny"],
["מקס", "Max"],
["מסתכל", "Look"],
["אדי", "Eddie"],
["רצית", "Wanted"],
["זקוקים", "Need"],
["בערב", "in the evening"],
["ייתכן", "You may"],
["חיה", "an animal"],
["בוס", "boss"],
["אתקשר", "Call"],
["זקן", "an old"],
["ריצ", "Richmond"],
["ז", "Seventh"],
["ההורים", "Parents"],
["השעה", "the hour"],
["הים", "Sea"],
["האמיתי", "the true"],
["הנכון", "Right"],
["שראיתי", "I saw"],
["בכדי", "To"],
["לסיים", "to finish"],
["לפתוח", "open"],
["הבאים", "the following"],
["דני", "Danish"],
["לרקוד", "Dance"],
["שאף", "That"],
["בתחת", "Ass"],
["הכלב", "Dog"],
["גאה", "proud"],
["תשכח", "Forget"],
["המלחמה", "The war"],
["האחרים", "Others"],
["נהדרת", "Great"],
["נצטרך", "We will have"],
["קול", "Voice"],
["ת", "The"],
["כואב", "painful"],
["מסביב", "Around"],
["יגיע", "Arrive"],
["לעלות", "Rise"],
["אוה", "Oh"],
["עמוק", "deep"],
["עובר", "Passes"],
["עובדים", "Working"],
["שלח", "Submit"],
["סמים", "Drugs"],
["ביל", "Bill"],
["החדר", "The room"],
["הגדולה", "Great"],
["שונאת", "Hate"],
["תחזיק", "Hang"],
["להסתכל", "to look"],
["הרג", "killing"],
["כשהייתי", "When I was"],
["תלוי", "dependent"],
["צהריים", "noon"],
["אוו", "Wow"],
["עסקים", "Business"],
["מצאת", "did you find"],
["התחיל", "Started"],
["הלכתי", "I walked"],
["להתמודד", "to cope"],
["בעצם", "Actually"],
["דפוק", "screwed"],
["קום", "get up"],
["אגב", "incidentally"],
["בירה", "beer"],
["שתוכל", "You can"],
["המולד", "Christmas"],
["כזו", "One"],
["פתח", "opening"],
["נתחיל", "Let's start"],
["נעלם", "Disappeared"],
["חברי", "my friend"],
["התוכנית", "the plan"],
["לארוחת", "For"],
["התא", "Cell"],
["הנרי", "Henry"],
["לאל", "Lal"],
["צודקת", "Right"],
["לאחרונה", "recently"],
["מסיבה", "party"],
["צורך", "need"],
["תינוק", "baby"],
["תאמר", "Tamer"],
["מפחיד", "Scary"],
["מכן", "Then"],
["אחותי", "my sister"],
["חזר", "came back"],
["לכתוב", "to write"],
["בשר", "meat"],
["עוזב", "Leaves"],
["רבותיי", "Gentlemen"],
["עולם", "world"],
["עוזר", "assistant"],
["גבירתי", "Madam"],
["הכדור", "the ball"],
["עומדים", "Standing"],
["הרעיון", "The idea"],
["גבירותיי", "Ladies"],
["תפסתי", "I caught"],
["נמאס", "Fed up"],
["מנת", "portion"],
["אור", "light"],
["איננו", "We do not"],
["דיברתי", "I spoke"],
["קרב", "battle"],
["כוס", "glass"],
["תמצא", "Find"],
["ניק", "Nick"],
["ועל", "And"],
["תנסה", "try out"],
["אמורים", "Should"],
["להפוך", "to flip"],
["מעדיף", "Prefer"],
["חדשים", "New"],
["שעבר", "past"],
["שעשית", "You did"],
["עלול", "might"],
["סמל", "symbol"],
["רופא", "doctor"],
["זקוקה", "Needed"],
["המ", "Are"],
["לואיס", "Lewis"],
["מנסים", "trying"],
["מנהל", "Director"],
["עלה", "Increased"],
["החדשה", "New"],
["חופשי", "free"],
["משחקים", "Games"],
["ם", "From"],
["המספר", "Number"],
["אלכס", "Alex"],
["שבע", "seven"],
["זהירות", "Caution"],
["מצא", "Find"],
["מכירים", "Know"],
["נחמדה", "Nice"],
["עבורי", "Me"],
["תתקשר", "Call"],
["פתאום", "Suddenly"],
["החוק", "The law"],
["להחזיק", "to hold"],
["כאב", "Pain"],
["מתחילים", "Begin"],
["עיניים", "Eye"],
["תסתכלי", "Look"],
["להילחם", "Fight"],
["הגיוני", "Makes sense"],
["ברחוב", "in the street"],
["זוג", "Pair"],
["בילי", "Billy"],
["הרגשתי", "I felt"],
["תמונה", "Image"],
["החברים", "the friends"],
["סגן", "Lieutenant"],
["הסוף", "The end"],
["בפני", "To"],
["סיפר", "Told"],
["השנים", "Years"],
["נקרא", "Called"],
["גדולים", "Great"],
["טוני", "Tony"],
["בדיחה", "joke"],
["נוספת", "Another"],
["כתוב", "Write"],
["גנרל", "general"],
["הרכב", "composition"],
["שייך", "belongs"],
["אהרוג", "Kill"],
["לגלות", "Discover"],
["קיי", "Kaye"],
["וחצי", "And half"],
["מצויין", "Excellent"],
["נקי", "net"],
["בלבד", "only"],
["באת", "Bath"],
["כרטיס", "card"],
["נוסע", "passenger"],
["נתתי", "I gave"],
["יוצאים", "Going"],
["עין", "eye"],
["מרי", "Mary"],
["האהבה", "Love"],
["qsubs", "qsubs"],
["מוכר", "Familiar"],
["הרגליים", "Legs"],
["לשלוח", "to send"],
["תיזהר", "Be careful"],
["תפוס", "Catch"],
["שומר", "Guard"],
["לשום", "Any"],
["פעמיים", "Twice"],
["מאות", "Hundreds"],
["דומה", "Similar"],
["הוגן", "fair"],
["הולדת", "birth"],
["עומדת", "Stands"],
["יוצאת", "Leaves"],
["בתי", "Houses"],
["מחפשים", "Looking"],
["לבקר", "visit"],
["בשנה", "Year"],
["יבוא", "will come"],
["הגענו", "We arrived"],
["ראשונה", "First"],
["האוכל", "Food"],
["במכונית", "Car"],
["הבחורים", "The boys"],
["סימן", "sign"],
["להוריד", "pull down"],
["אצלי", "by me"],
["במהירות", "quickly"],
["חלום", "dream"],
["חולים", "Patients"],
["חמודה", "Cutie"],
["בקושי", "barely"],
["עסק", "Business"],
["תעזור", "Help"],
["יקירי", "Darling"],
["בינינו", "between us"],
["תזוז", "Move"],
["עבד", "slave"],
["עוף", "chicken"],
["המוח", "the brain"],
["כוכב", "Star"],
["סבא", "grandfather"],
["טעם", "taste"],
["להעביר", "to convey"],
["ייק", "Jake"],
["קו", "line"],
["ידידי", "Friends"],
["נראים", "Look"],
["טומי", "Tommy"],
["הנשק", "Weapon"],
["רי", "Jerry"],
["פגישה", "Appointment"],
["תה", "tea"],
["בעבודה", "At work"],
["מדובר", "spoken"],
["עסוק", "Busy"],
["לצפות", "Watch"],
["סגור", "closed"],
["הגעת", "Arrival"],
["הבוס", "The Boss"],
["עשתה", "Done"],
["מצליח", "successful"],
["ברירה", "choice"],
["שהיו", "Who"],
["ארוך", "long"],
["הרגל", "habit"],
["שעשיתי", "I did"],
["לחץ", "pressure"],
["אביא", "I will"],
["השאלה", "the question"],
["מוכרח", "forced"],
["שיט", "sailing"],
["בר", "bar"],
["בטלפון", "on the phone"],
["קטנים", "Small"],
["אנשי", "People"],
["ואין", "And no"],
["להתחתן", "marry"],
["נצא", "We will"],
["לרדת", "down"],
["אמריקה", "America"],
["עשרים", "twenty"],
["הכוח", "Power"],
["רגיל", "Regular"],
["משקה", "Beverage"],
["רלי", "Relly"],
["שואל", "Asks"],
["להכניס", "Insert"],
["שיר", "A poem"],
["מבינים", "Understand"],
["לקחתי", "I took"],
["תבוא", "come"],
["הבנות", "Girls"],
["מציע", "Offers"],
["לשעבר", "former"],
["האור", "the light"],
["השמש", "The sun"],
["הדם", "the blood"],
["טועה", "wrong"],
["המפתח", "The key"],
["הפתעה", "a surprise"],
["אספר", "Tell"],
["למכור", "sell"],
["מלאה", "Full"],
["קראתי", "Read"],
["מטר", "meter"],
["חומר", "material"],
["כריס", "Chris"],
["מתנה", "Present"],
["רעב", "hunger"],
["ארבעה", "four"],
["רגל", "Foot"],
["קווין", "Quinn"],
["שיחה", "call"],
["יושב", "Sitting"],
["שליטה", "control"],
["לאהוב", "to love"],
["מראה", "Mirror"],
["לכלא", "Jail"],
["שניה", "Watch"],
["אמיתית", "Real"],
["תתחיל", "Begin"],
["מאה", "century"],
["שכולם", "Everyone"],
["תיתן", "Give"],
["יל", "Jill"],
["מאחר", "Because"],
["לאתר", "locate"],
["במשרד", "Office"],
["קרא", "Read"],
["ניסה", "tried"],
["מלך", "king"],
["הצהריים", "Noon"],
["הגיעו", "Reached"],
["המזל", "Luck"],
["הומו", "Homo"],
["בידי", "By"],
["לכמה", "Some"],
["בקלות", "Easily"],
["אתי", "ethical"],
["מזדיין", "Motherfucker"],
["מגיעה", "Reaches"],
["אדום", "red"],
["המילה", "The word"],
["תמונות", "Photos"],
["אלן", "Alan"],
["שבי", "captivity"],
["תקבל", "Will receive"],
["תוציא", "Get"],
["אנה", "Anna"],
["אשמח", "I'd be happy"],
["להכין", "Prepare"],
["פגשתי", "Met"],
["השולחן", "Table"],
["אמת", "Truth"],
["ט", "ninth"],
["רצינית", "Serious"],
["מיני", "sexual"],
["החדשות", "the news"],
["השנייה", "the second"],
["כלי", "tool"],
["הגעתי", "I got"],
["אחיך", "Brother"],
["ליצור", "create a"],
["הטובים", "Best"],
["נוח", "comfortable"],
["הלאה", "further"],
["בשום", "Any"],
["אישי", "personal"],
["מעוניין", "interested"],
["מגוחך", "ridiculous"],
["שאר", "rest"],
["לבנות", "to build"],
["ברוכים", "Welcome"],
["מבט", "look"],
["מילים", "Count"],
["סטיב", "Steve"],
["נוסעים", "Passengers"],
["האוויר", "Air"],
["שוטרים", "Policemen"],
["מובן", "Of course"],
["קחו", "Take"],
["תהרוג", "Kill"],
["לבצע", "perform"],
["גרם", "gram"],
["מלבד", "Besides"],
["השיר", "The song"],
["קצר", "short"],
["התמונה", "Picture"],
["שאנשים", "People"],
["שאפשר", "Can be"],
["לאמא", "Mother"],
["סם", "drug"],
["מביא", "Brings"],
["הופך", "Makes"],
["עץ", "Wood"],
["ניו", "New"],
["פעולה", "action"],
["אמצא", "Find"],
["הרוח", "Wind"],
["להצטרף", "join"],
["צעד", "step"],
["הגיעה", "arrived"],
["סע", "Article"],
["מחזיק", "holder"],
["לגור", "live"],
["סיימתי", "I finished"],
["הגבר", "Man"],
["תיקח", "Take"],
["שנתיים", "two years"],
["יחזור", "will return"],
["הרכבת", "Train"],
["רוצח", "murderer"],
["מצאנו", "we found"],
["חוקי", "legal"],
["אינה", "Does not"],
["שגם", "That"],
["מבלי", "without"],
["השיער", "Hair"],
["xfc", "xfc"],
["סיפרת", "Tell"],
["טי", "T"],
["חזיר", "pig"],
["לכיוון", "Direction"],
["חושש", "afraid"],
["בגדים", "Swimsuit"],
["המטרה", "The goal"],
["כולו", "All"],
["חזור", "return"],
["להחליף", "Replace"],
["תדבר", "Speak"],
["דייב", "Dave"],
["תיכנס", "Sign in"],
["מגיעים", "Coming"],
["ולי", "Wally"],
["נחזור", "Return"],
["תשמע", "Listen"],
["רבות", "Many"],
["קיים", "Exists"],
["למוות", "Death"],
["הגוף", "The body"],
["כיוון", "Direction"],
["סלחי", "Forgive"],
["לתקן", "Correct"],
["לעיר", "City"],
["המטוס", "Plane"],
["ייקח", "Take"],
["הצלחתי", "I could"],
["חודש", "a month"],
["מזמן", "long ago"],
["מסכים", "agree"],
["מוטב", "better"],
["איבדתי", "I lost"],
["הנשים", "Women"],
["לאבא", "Father"],
["אחוז", "Percent"],
["ניקח", "Taking"],
["שכח", "forgot"],
["הורג", "Killing"],
["שתרצה", "You want"],
["אליהם", "To"],
["תירה", "Shoot"],
["הספינה", "Ship"],
["מאושר", "Happy"],
["אוויר", "Air"],
["שינוי", "Change"],
["במשחק", "Game"],
["חוזרת", "Returns"],
["שבה", "Which"],
["חיות", "Animals"],
["שיכול", "Can"],
["תספר", "Tell"],
["שונים", "Different"],
["צעירה", "young woman"],
["אחריי", "Follow me"],
["כלשהו", "any"],
["האדמה", "Earth"],
["באזור", "Region"],
["חוק", "Law"],
["טרי", "fresh"],
["עצוב", "sad"],
["הבאת", "Bringing"],
["כשהם", "When they"],
["לזמן", "Time"],
["קיבל", "have received"],
["לאסוף", "pick up"],
["אנדי", "Andy"],
["התקשר", "was called"],
["משטרה", "police"],
["במהלך", "during"],
["סונכרן", "Synchronized"],
["תאמין", "have faith"],
["הטובה", "Best"],
["שומעת", "Hears"],
["העסק", "the business"],
["זונות", "Whores"],
["יומיים", "Two days"],
["חמישה", "five"],
["יכולות", "Capabilities"],
["הצוות", "The team"],
["וכך", "And"],
["שותה", "Drink"],
["הייתם", "You"],
["שיער", "Hair"],
["אחראי", "in charge of"],
["מהבית", "from home"],
["בעניין", "About"],
["הרגת", "Killed"],
["יראה", "fear"],
["אצלך", "at your place"],
["ספרי", "Books"],
["התעופה", "Airport"],
["קי", "Ki"],
["באותה", "The same"],
["שינה", "Changed"],
["ידוע", "known"],
["נהג", "Driver"],
["כתב", "Wrote"],
["עדן", "Eden"],
["שכדאי", "Worth"],
["תמות", "Die"],
["אמן", "Artist"],
["וולטר", "Walter"],
["סיפרתי", "I told"],
["פרופסור", "professor"],
["קייט", "Kate"],
["ריק", "blank"],
["תגיע", "Will"],
["הנקודה", "the point"],
["השגת", "Achieving"],
["נסה", "Try"],
["תאונה", "accident"],
["מקשיב", "listening"],
["שמן", "Oil"],
["הראשי", "Primary"],
["האש", "Fire"],
["למיטה", "Bed"],
["דיוויד", "David"],
["מטומטם", "dumb"],
["נתת", "You gave"],
["אשתך", "Your wife"],
["מהיר", "fast"],
["הורד", "taken down"],
["רוברט", "Robert"],
["למשך", "For"],
["מעריך", "Estimates"],
["אלוקים", "Gd"],
["התחלתי", "initial"],
["וסונכרן", "And synchronized"],
["זהב", "gold"],
["הזקן", "Beard"],
["להרוס", "destroy"],
["ההזדמנות", "Opportunity"],
["העניינים", "Things"],
["לאבד", "to lose"],
["הקרב", "Battle"],
["חירום", "emergency"],
["הקשר", "connection"],
["הדין", "Court"],
["בנים", "Boys"],
["עברו", "Passed"],
["מכה", "blow"],
["ומי", "Who"],
["שבועיים", "Two weeks"],
["שחקן", "player"],
["שאלתי", "I asked"],
["בעיניי", "Me"],
["אס", "ace"],
["שישה", "Six"],
["שרק", "whistled"],
["תפסיקו", "Stop"],
["להזמין", "Order"],
["אחריו", "Followed by"],
["סתום", "blocked"],
["לשכוח", "forget"],
["לענות", "to answer"],
["מכתב", "Letter"],
["עתה", "now"],
["למכונית", "Car"],
["מחכים", "waiting"],
["האחרונות", "Years"],
["אמש", "last night"],
["תקשיבו", "Listen"],
["ממשיך", "continue"],
["ע", "By"],
["xff", "xff"],
["ליום", "for the day"],
["מקבלים", "Get"],
["יעבוד", "Will work"],
["לסמוך", "rely"],
["שישי", "sixth"],
["חשבון", "invoice"],
["עזור", "Help"],
["לבלות", "spend"],
["יקר", "Expensive"],
["מצאו", "Found"],
["חייל", "Soldier"],
["הקבוצה", "Group"],
["מגעיל", "disgusting"],
["יא", "K"],
["אינם", "gone"],
["גרה", "Lives"],
["לרוץ", "run"],
["מתחילה", "Starts"],
["רכב", "vehicle"],
["להציע", "offer"],
["הלבן", "White"],
["לחיי", "Life"],
["שימו", "Please"],
["המפתחות", "the keys"],
["ענק", "Huge"],
["אריק", "Eric"],
["ערך", "value"],
["שמתי", "I"],
["חייו", "His life"],
["גנב", "Thief"],
["להניח", "Let"],
["תרצי", "Would you like"],
["הזין", "Dick"],
["כשהיא", "When she"],
["הרופא", "the doctor"],
["שאי", "That"],
["לחבר", "connect"],
["העתיד", "the future"],
["אחות", "Nurse"],
["נכנסת", "Incoming"],
["עיר", "City"],
["העובדה", "The fact that"],
["קולונל", "colonel"],
["אמי", "My mother"],
["הצלחת", "Success"],
["עורך", "editor"],
["דן", "Dan"],
["להוכיח", "prove"],
["לאחור", "behind"],
["המידע", "Information"],
["בטוחים", "Confident"],
["שהן", "They"],
["מחבב", "fond"],
["תוהה", "Wondering"],
["שאומר", "Means"],
["מבטיחה", "Guarantees"],
["במיטה", "Bed"],
["סביב", "around"],
["מרטין", "Martin"],
["משתמש", "user"],
["לשיר", "sing"],
["לפנות", "Turn"],
["הממשלה", "Government"],
["האחרונים", "Latest"],
["לסדר", "Arrange"],
["אטפל", "Take care"],
["יהרוג", "Kill"],
["שזאת", "It was"],
["ין", "yen"],
["להקשיב", "listen"],
["שלם", "whole"],
["נושא", "Topic"],
["המשימה", "Mission"],
["פתוח", "open"],
["ביצים", "Eggs"],
["ואולי", "And possibly"],
["מחפשת", "Looking"],
["נשוי", "Married"],
["עשוי", "made"],
["משמעות", "meaning"],
["הרגשה", "feeling"],
["צרות", "Trouble"],
["הבגדים", "the clothes"],
["יורד", "Descending"],
["בצרות", "Trouble"],
["תקרא", "Call"],
["עצרו", "Arrested"],
["לוקחים", "Take"],
["הצבא", "the army"],
["שניהם", "both"],
["תפתח", "Will open"],
["דה", "De"],
["תהיו", "Will be"],
["בשבילו", "For him"],
["תיק", "Bag"],
["מיוחדת", "Special"],
["אהבת", "Love"],
["ורבותיי", "And Gentlemen"],
["להזדיין", "Screw"],
["עצמה", "herself"],
["תעצור", "Stop"],
["ועם", "And"],
["אד", "Ed"],
["צאו", "Take"],
["וזו", "And that"],
["אישור", "Approval"],
["השוטר", "Policeman"],
["לאורך", "along"],
["שון", "Shawn"],
["דיברנו", "We talked"],
["פחד", "fear"],
["לדעתי", "In my opinion"],
["עונה", "Season"],
["עסקה", "transaction"],
["חזקה", "strong"],
["עזב", "Leave"],
["מודה", "thanking"],
["אליס", "Alice"],
["טיפשי", "stupid"],
["אדמה", "land"],
["לנהוג", "to drive"],
["עליכם", "You"],
["שכמוך", "Bitch"],
["סו", "Sue"],
["להכנס", "enter"],
["לארי", "Larry"],
["קבוצת", "Group"],
["כאלו", "These"],
["בטלוויזיה", "TV"],
["להציג", "display"],
["שמאלה", "left"],
["ביקשתי", "I asked"],
["שעברה", "Last"],
["הימים", "Day"],
["מארק", "Mark"],
["תלכי", "Go"],
["היחידי", "Only"],
["ואיך", "How"],
["ללבוש", "wear"],
["סוכן", "agent"],
["הגב", "Reply"],
["לשחרר", "release"],
["לצד", "Alongside"],
["שקורה", "Happening"],
["קראת", "You read"],
["במשהו", "Something"],
["שלישי", "Third"],
["הרצפה", "Ground"],
["the", "the"],
["מאט", "slows down"],
["פיל", "Phil"],
["סוס", "horse"],
["לשלוט", "control"],
["תתרחק", "back away"],
["משלם", "Pay"],
["מסוגלת", "Capable"],
["להרשות", "allow"],
["תניח", "Place"],
["ישנם", "there are"],
["הלכה", "Gone"],
["זבל", "manure"],
["לאיש", "man"],
["משקר", "Lying"],
["ישמור", "Will keep"],
["קלי", "Kelly"],
["שמת", "Dead"],
["ואי", "Wai"],
["ההיא", "that"],
["המסיבה", "the party"],
["הקול", "Sound"],
["ואן", "Wan"],
["לילדים", "for children"],
["ארוכה", "Long"],
["כולל", "including"],
["שיניים", "Teeth"],
["אפס", "zero"],
["פיט", "Pete"],
["מתקשר", "Calling"],
["אחרות", "Other"],
["גיבור", "Hero"],
["ביקש", "Sought"],
["האחד", "the one"],
["למדתי", "I learned"],
["צבא", "Army"],
["למשהו", "Something"],
["להן", "them"],
["כנס", "conference"],
["הבט", "Look"],
["בינתיים", "Meanwhile"],
["ני", "Ow"],
["מייד", "Immediately"],
["כבד", "liver"],
["כשאת", "When you"],
["אדבר", "Speak"],
["חשב", "accountant"],
["שאל", "Ask"],
["ואתם", "And you"],
["נפל", "Fell"],
["i", "i"],
["הפך", "opposite"],
["מאושרת", "Happy"],
["מפשע", "Innocent"],
["המאמן", "the coach"],
["אבוא", "I will come"],
["כוחות", "Forces"],
["רוץ", "Roach"],
["ארצה", "Ground"],
["יתכן", "Perhaps"],
["לסבול", "To suffer"],
["הביא", "resulted in"],
["מרוצה", "satisfied"],
["דיבר", "Spoke"],
["ממזר", "bastard"],
["יאללה", "Come on"],
["הגברים", "Men"],
["בחורות", "Girls"],
["you", "you"],
["להיראות", "Be visible"],
["לזכור", "remember"],
["סלחו", "Excuse"],
["לגעת", "to touch"],
["קוראת", "Call"],
["אשם", "Guilty"],
["טעים", "tasty"],
["חמור", "Donkey"],
["משפחת", "The"],
["למשרד", "Office"],
["רעה", "evil"],
["שאעשה", "I will"],
["ואף", "And"],
["בגיל", "At the age of"],
["כועס", "angry"],
["בעלך", "your husband"],
["לקחו", "Took"],
["קרובים", "close"],
["אשתו", "His wife"],
["תבין", "Understand"],
["לכבוד", "in honor of"],
["לע", "La"],
["מאמינים", "Believe"],
["במרחק", "Just"],
["תוכלו", "You"],
["מפחדת", "Fear"],
["תשתוק", "shut up"],
["קבוצה", "Group"],
["בעד", "for"],
["דון", "don"],
["חשובה", "important"],
["לוודא", "to ensure"],
["תשמור", "Save"],
["שבאת", "Coming"],
["השיחה", "Conversation"],
["בקרב", "among"],
["החתונה", "the wedding"],
["להרים", "lift"],
["נאמר", "spoken"],
["דג", "A fish"],
["תקווה", "hope"],
["מטוס", "a plane"],
["החומר", "The material"],
["אפשרות", "possibility"],
["תשע", "nine"],
["אשמתי", "my fault"],
["ללמד", "teach"],
["דיי", "Day"],
["הרי", "Mountains"],
["תיגע", "Touching"],
["לוקחת", "Taking"],
["המנהל", "the manager"],
["בסופו", "The end"],
["אמך", "Mother"],
["תפסו", "Caught"],
["השוטרים", "The police"],
["מכוניות", "Cars"],
["תעשו", "Make"],
["לעוף", "fly"],
["הגברת", "Increasing"],
["לנקות", "Clear"],
["יקח", "Take"],
["חזרתי", "I returned"],
["רצתה", "Wanted"],
["וויל", "Will"],
["ויקטור", "Victor"],
["להשאר", "stay"],
["היקר", "Dear"],
["הרגתי", "Killed"],
["גדולות", "Great"],
["הצד", "the side"],
["שר", "minister"],
["שהייתה", "Was"],
["האף", "Nose"],
["עוזבת", "Leaves"],
["החוקים", "Laws"],
["ראו", "See"],
["עבדתי", "I worked"],
["לסגור", "To close"],
["רוי", "Roy"],
["מריח", "Smells"],
];
