const hungarian = [
["a", "the"],
["nem", "no"],
["az", "the"],
["hogy", "that"],
["és", "and"],
["egy", "one"],
["van", "there is"],
["ez", "this"],
["is", "also"],
["meg", "and"],
["de", "but"],
["csak", "just"],
["mi", "what"],
["én", "I"],
["ha", "if"],
["azt", "it"],
["vagy", "obsession"],
["itt", "here"],
["igen", "Yes"],
["volt", "volt"],
["ne", "not"],
["el", "away"],
["már", "already"],
["te", "you"],
["kell", "must"],
["még", "more"],
["ki", "Who"],
["mit", "what"],
["jó", "good"],
["vagyok", "I'm"],
["ezt", "this"],
["most", "now"],
["mint", "as"],
["tudom", "I know"],
["miért", "why"],
["úgy", "business"],
["akkor", "then"],
["ő", "She"],
["jól", "well"],
["nagyon", "very"],
["lesz", "will be"],
["nincs", "no"],
["minden", "all"],
["be", "on"],
["sem", "neither"],
["le", "juice"],
["olyan", "so"],
["rendben", "okay"],
["ott", "there"],
["mert", "because"],
["így", "so"],
["nekem", "me"],
["fel", "up"],
["amit", "what"],
["tudod", "you know"],
["volna", "would be"],
["majd", "then"],
["maga", "itself"],
["hát", "back"],
["köszönöm", "Thanks"],
["hol", "where"],
["valami", "something"],
["lehet", "may"],
["gyerünk", "Come on"],
["mindig", "always"],
["uram", "mister"],
["kis", "small"],
["semmi", "nothing"],
["hé", "hey"],
["oké", "okay"],
["talán", "maybe"],
["ide", "here"],
["neked", "thee"],
["aki", "who"],
["ó", "She"],
["neki", "him"],
["gyere", "come"],
["nagy", "large"],
["amikor", "when"],
["vissza", "back"],
["mr", "mr"],
["hiszem", "I think"],
["valamit", "something"],
["ember", "human"],
["őket", "them"],
["milyen", "what kind of"],
["ma", "today"],
["elég", "enough"],
["egész", "whole"],
["fog", "tooth"],
["ilyen", "such"],
["tudja", "can"],
["rá", "it"],
["vagyunk", "we're"],
["ami", "which"],
["vannak", "are"],
["igaz", "true"],
["lenne", "it would be"],
["biztos", "sure"],
["tényleg", "indeed"],
["vele", "with him"],
["szóval", "so"],
["két", "two"],
["persze", "of course"],
["na", "So"],
["nos", "married"],
["sok", "many"],
["túl", "too"],
["mikor", "when"],
["t", "t"],
["sajnálom", "I'm sorry"],
["aztán", "then"],
["történt", "happened"],
["azért", "therefore"],
["engem", "me"],
["értem", "I understand"],
["ahogy", "as"],
["velem", "with me"],
["kicsit", "a bit"],
["valaki", "someone"],
["mondta", "He told"],
["kérem", "Please"],
["se", "neither"],
["mondtam", "I said"],
["nézd", "look"],
["akarsz", "you want"],
["menj", "go"],
["ugye", "right"],
["pedig", "in turn"],
["szia", "Hello"],
["mindent", "everything"],
["e", "e"],
["voltam", "I've"],
["soha", "never"],
["semmit", "nothing"],
["arra", "to"],
["más", "other"],
["új", "new"],
["szép", "beautiful"],
["akarok", "I want"],
["jobb", "right"],
["erre", "this"],
["veled", "with you"],
["baj", "charm"],
["mindenki", "everybody"],
["nap", "Sun"],
["senki", "no one"],
["kérlek", "please"],
["legyen", "be"],
["rám", "me"],
["akarom", "I want"],
["benne", "in it"],
["ezért", "therefore"],
["akar", "will"],
["ezek", "these"],
["őt", "five"],
["kellett", "needed"],
["több", "more"],
["oh", "oh"],
["innen", "hence"],
["magát", "you"],
["ön", "you"],
["át", "through"],
["emberek", "people"],
["kéne", "should"],
["úr", "Mr."],
["istenem", "dear me"],
["várj", "wait"],
["minket", "U.S"],
["rossz", "bad"],
["első", "first"],
["oda", "there"],
["láttam", "I saw"],
["este", "evening"],
["téged", "you"],
["egyszer", "once"],
["mondja", "says"],
["miatt", "for"],
["isten", "God"],
["igazán", "really"],
["után", "after"],
["tudok", "I know"],
["tessék", "Pardon"],
["mondd", "Tell me"],
["együtt", "together"],
["mintha", "as if"],
["hogyan", "how"],
["szerintem", "I think"],
["megyek", "counties"],
["pár", "par"],
["ja", "ja"],
["érted", "Do you understand"],
["sosem", "never"],
["apa", "father"],
["tudtam", "I knew it"],
["jön", "come"],
["róla", "about him"],
["rajta", "on"],
["másik", "another"],
["figyelj", "pay attention"],
["újra", "again"],
["dolog", "thing"],
["elnézést", "excuse me"],
["három", "three"],
["szerint", "by"],
["magad", "yourself"],
["magam", "myself"],
["megy", "go"],
["mind", "all"],
["inkább", "rather"],
["jobban", "better"],
["néhány", "some"],
["menjünk", "let's go"],
["lenni", "to be"],
["micsoda", "what"],
["annyira", "that"],
["saját", "own"],
["lett", "became"],
["kellene", "should"],
["alatt", "under"],
["tud", "can"],
["amíg", "until"],
["egyik", "one"],
["teljesen", "completely"],
["ebben", "in this"],
["holnap", "tomorrow"],
["hittem", "I believed"],
["akartam", "I wanted"],
["gondoltam", "I thought"],
["vége", "over"],
["anya", "maternal"],
["ezzel", "with this"],
["legjobb", "best"],
["hozzá", "him"],
["egyetlen", "one"],
["tovább", "next"],
["egyedül", "alone"],
["hadd", "let me"],
["épp", "right now"],
["haver", "dude"],
["akarod", "do you want"],
["csinálsz", "you do"],
["ők", "OK"],
["mire", "what"],
["gyorsan", "fast"],
["honnan", "from"],
["voltál", "you were"],
["i", "i"],
["akik", "who"],
["mondani", "to say"],
["nekünk", "us"],
["hagyd", "let"],
["megint", "again"],
["ahol", "where"],
["nő", "woman"],
["idő", "time"],
["azok", "those"],
["látni", "see"],
["lány", "girl"],
["szó", "weave"],
["voltak", "they were"],
["nélkül", "without"],
["egyet", "one"],
["előtt", "before"],
["szeretném", "I would like to"],
["mondom", "I say"],
["látom", "I see"],
["remélem", "hope"],
["mielőtt", "before"],
["ti", "you"],
["kedves", "nice"],
["áll", "stand"],
["jött", "came"],
["tudsz", "you know"],
["leszek", "I will be"],
["francba", "Shit"],
["haza", "home"],
["először", "first"],
["rád", "you"],
["kész", "ready"],
["igazi", "real"],
["menni", "to go"],
["kösz", "dirt"],
["fogok", "I will"],
["ennek", "for this"],
["tűnik", "seems"],
["add", "add"],
["állj", "Stop"],
["pontosan", "exactly"],
["komolyan", "seriously"],
["nekik", "them"],
["sokat", "lot"],
["ben", "in"],
["akarja", "To"],
["később", "later"],
["abba", "into it"],
["helló", "Hello"],
["fogja", "will"],
["szeretnék", "I want"],
["pont", "point"],
["tetszik", "like"],
["utolsó", "last"],
["azonnal", "immediately"],
["beszélni", "speak"],
["tehát", "so"],
["hallottam", "I heard"],
["dr", "Dr."],
["össze", "together"],
["megvan", "has"],
["ugyan", "though"],
["tudni", "to know"],
["nehéz", "hard"],
["csinálni", "do"],
["fiam", "my son"],
["nagyszerű", "That's great"],
["ezen", "on this"],
["férfi", "man"],
["mégis", "in spite of that"],
["remek", "great"],
["pénzt", "money"],
["magának", "himself"],
["erről", "about this"],
["ennyi", "so much"],
["örülök", "I am glad"],
["látod", "you see"],
["ok", "OK"],
["sincs", "no"],
["többet", "More"],
["azzal", "with"],
["fogsz", "will you"],
["hanem", "but also"],
["apám", "my dad"],
["néha", "sometimes"],
["szeretlek", "I love you"],
["fiú", "boy"],
["fogom", "I will"],
["reggel", "morning"],
["boldog", "happy"],
["s", "s"],
["jöjjön", "come"],
["öt", "five"],
["érzem", "I feel"],
["világ", "world"],
["legalább", "at least"],
["bele", "into"],
["fontos", "important"],
["végre", "finally"],
["mrs", "mrs"],
["éve", "year"],
["mennem", "to go"],
["tudjuk", "we know"],
["hova", "where"],
["meghalt", "died"],
["érdekel", "I am interested"],
["viszlát", "Bye bye"],
["szeretem", "I like"],
["hová", "where"],
["többé", "any more"],
["öreg", "old"],
["halott", "dead"],
["es", "and"],
["kurva", "bitch"],
["éves", "annual"],
["összes", "all"],
["ideje", "time"],
["hello", "Hello"],
["perc", "minute"],
["néz", "look"],
["sokkal", "much"],
["mondtad", "you said"],
["miről", "about what"],
["megyünk", "we're going"],
["azon", "the"],
["srácok", "guys"],
["szabad", "free"],
["fiúk", "boys"],
["gondolom", "I think"],
["hely", "place"],
["vagytok", "Are"],
["tenni", "to do"],
["drágám", "Honey"],
["akit", "whom"],
["miss", "miss"],
["beszélsz", "you speak"],
["annak", "to"],
["mindjárt", "anon"],
["éppen", "just"],
["mivel", "because"],
["gyönyörű", "beautiful"],
["légy", "fly"],
["tedd", "do"],
["ezeket", "these"],
["enyém", "mine"],
["kibaszott", "fucking"],
["tegnap", "yesterday"],
["hülye", "stupid"],
["maradj", "stay"],
["vigyázz", "look out"],
["mész", "lime"],
["attól", "from"],
["barátom", "my friend"],
["beszél", "talk"],
["nézze", "Look"],
["nézz", "look"],
["ment", "went"],
["múlva", "Later"],
["hozzám", "Shall I bring it"],
["aha", "aha"],
["ban", "in"],
["szükségem", "I need"],
["gond", "worry"],
["fogd", "grab"],
["velünk", "with us"],
["óra", "hour"],
["valaha", "ever"],
["nak", "s"],
["következő", "following"],
["élet", "life"],
["kérek", "I ask"],
["arról", "about"],
["történik", "happen"],
["fél", "party"],
["találkozunk", "we meet"],
["míg", "while"],
["régi", "old"],
["egyáltalán", "at all"],
["lgen", "Yes"],
["neve", "name"],
["négy", "four"],
["majdnem", "almost"],
["között", "between"],
["mennyi", "How much"],
["nek", "s"],
["óta", "since"],
["éjjel", "night"],
["napot", "day"],
["pénz", "money"],
["helyzet", "state"],
["gondolsz", "think"],
["the", "the"],
["biztosan", "surely"],
["leszel", "you will be"],
["képes", "can"],
["ellen", "against"],
["dolgot", "things"],
["mondott", "said"],
["john", "john"],
["emlékszel", "you remember"],
["jelent", "mean"],
["érte", "for him"],
["jöttem", "I came"],
["abban", "therein"],
["vedd", "pick"],
["uraim", "gentlemen"],
["nyugi", "chill out"],
["ég", "sky"],
["menjen", "go"],
["akár", "will"],
["számít", "calculate"],
["király", "King"],
["jövök", "coming"],
["év", "year"],
["jack", "jack"],
["gondolod", "you think"],
["mond", "tell"],
["csinál", "do"],
["valakit", "someone"],
["kapitány", "captain"],
["folyik", "flow"],
["tőle", "from him"],
["emlékszem", "I remember"],
["előbb", "before"],
["természetesen", "naturally"],
["reggelt", "morning"],
["addig", "until then"],
["embert", "people"],
["fickó", "guy"],
["főnök", "boss"],
["tőlem", "from me"],
["fognak", "will"],
["segíteni", "To help"],
["szépen", "beautifully"],
["new", "new"],
["beszélek", "I speak"],
["valóban", "really"],
["halló", "Hallo"],
["bár", "bar"],
["bocsánat", "Sorry"],
["fenébe", "hell"],
["készen", "ready"],
["fogunk", "we'll"],
["ahhoz", "to it"],
["anyám", "my mother"],
["gyerek", "Child"],
["sose", "never"],
["otthon", "at home"],
["vicces", "funny"],
["tiszta", "clean"],
["való", "to"],
["jaj", "alas"],
["dolgok", "things"],
["elment", "went"],
["hosszú", "long"],
["helyet", "place"],
["hét", "seven"],
["munka", "work"],
["mondod", "you say"],
["egyszerűen", "simply"],
["teljes", "complete"],
["pillanat", "moment"],
["velük", "with them"],
["ilyet", "like this"],
["szerinted", "think"],
["bármit", "anything"],
["dolgokat", "things"],
["hat", "six"],
["annyi", "so much"],
["köszi", "thanks"],
["fehér", "white"],
["helyes", "correct"],
["you", "you"],
["úgyhogy", "so"],
["tudják", "they know"],
["amint", "as"],
["amerikai", "American"],
["eddig", "so far"],
["nevem", "My name"],
["tettem", "I did"],
["jössz", "you come"],
["utána", "after"],
["jár", "go"],
["csináld", "do it"],
["szól", "speak"],
["csodálatos", "wonderful"],
["bocs", "sorry"],
["életben", "alive"],
["rohadt", "rotten"],
["segítség", "help"],
["mást", "else"],
["aggódj", "worry"],
["tökéletes", "perfect"],
["hiszed", "believe it"],
["belőle", "it"],
["vár", "Castle"],
["gyerekek", "kids"],
["várjon", "Wait"],
["ajtót", "door"],
["tart", "hold"],
["sikerült", "succeeded"],
["mennyire", "how"],
["kettő", "two"],
["fogod", "you will"],
["felé", "to"],
["mozgás", "move"],
["mióta", "since when"],
["akart", "wanted"],
["édes", "sweet"],
["szar", "shit"],
["marad", "stay"],
["vettem", "I bought"],
["él", "live"],
["érti", "understand"],
["szüksége", "need"],
["egymást", "each other"],
["melyik", "which"],
["valójában", "in fact"],
["fekete", "black"],
["végül", "finally"],
["ebből", "from this"],
["önnek", "for you"],
["hamarosan", "soon"],
["ismerem", "I know"],
["elő", "live"],
["többi", "other"],
["fiatal", "young"],
["őrült", "crazy"],
["ezelőtt", "ago"],
["láttad", "did you see"],
["előre", "forward"],
["tudta", "he knew"],
["mondják", "they say"],
["bármi", "any"],
["minek", "what for"],
["nézel", "look"],
["közel", "close"],
["életem", "my life"],
["különben", "or else"],
["hívják", "call"],
["segíts", "help"],
["miután", "having"],
["szent", "holy"],
["et", "et"],
["adj", "adj"],
["igaza", "right"],
["belül", "within"],
["furcsa", "strange"],
["ért", "understand"],
["magával", "along"],
["hány", "How many"],
["alá", "below"],
["rólam", "about me"],
["sokáig", "long"],
["jelenti", "means"],
["beteg", "patient"],
["alig", "barely"],
["tett", "deed"],
["maguk", "themselves"],
["jönni", "to come"],
["ötlet", "idea"],
["ehhez", "this"],
["hatalmas", "powerful"],
["maradt", "left"],
["egyszerű", "simple"],
["doktor", "doctor"],
["egyre", "ever"],
["látta", "saw"],
["rosszul", "poorly"],
["frank", "franc"],
["gondolja", "think"],
["asszonyom", "madam"],
["jézusom", "Jesus"],
["legnagyobb", "utmost"],
["apád", "father"],
["kicsi", "small"],
["voltunk", "we're"],
["találtam", "I found"],
["békén", "peace"],
["szívem", "my heart"],
["tette", "did"],
["akarnak", "they want"],
["gyertek", "come"],
["mellett", "next to"],
["második", "second"],
["munkát", "job"],
["lennék", "I'd"],
["félek", "parties"],
["srác", "tad"],
["tíz", "ten"],
["annyit", "that much"],
["érdekes", "interesting"],
["szívesen", "willingly"],
["szegény", "poor"],
["muszáj", "must"],
["mindegy", "never mind"],
["nincsenek", "There are no"],
["azokat", "those"],
["valahol", "somewhere"],
["erős", "strong"],
["viszont", "however"],
["valószínűleg", "probably"],
["jönnek", "they are coming"],
["bennem", "in me"],
["nálam", "me"],
["éjszaka", "night"],
["embereket", "people"],
["élni", "to live"],
["fene", "hell"],
["tele", "full"],
["számára", "for"],
["mindenkinek", "for everyone"],
["különleges", "special"],
["igazság", "truth"],
["kit", "whom"],
["percet", "moments"],
["úton", "on the way"],
["dollár", "dollar"],
["halál", "death"],
["rendőrség", "police"],
["kérdés", "question"],
["igazad", "right"],
["adja", "enter"],
["komoly", "serious"],
["egészen", "quite"],
["múlt", "past"],
["működik", "work"],
["időt", "time"],
["látja", "sees"],
["máris", "now"],
["keresztül", "across"],
["mama", "mother"],
["tőled", "from you"],
["lennie", "be"],
["mondok", "I say"],
["könnyű", "light"],
["tiéd", "yours"],
["köszönjük", "Thank You"],
["ház", "house"],
["dolgozni", "to work"],
["szót", "word"],
["ér", "vein"],
["tudunk", "we know"],
["jézus", "Jesus"],
["út", "beat"],
["lesznek", "will be"],
["szörnyű", "horrible"],
["nagyobb", "bigger"],
["héten", "week"],
["csináltam", "I did"],
["estét", "night"],
["szemét", "trash"],
["ülj", "sit"],
["leszünk", "we will be"],
["probléma", "problem"],
["kölyök", "kid"],
["akinek", "to whom"],
["hagyja", "leave"],
["lányok", "girls"],
["például", "for example"],
["hangzik", "sound"],
["ügy", "business"],
["éjt", "night"],
["kaptam", "I got"],
["kint", "out"],
["merre", "whereabouts"],
["rögtön", "immediately"],
["kifelé", "out"],
["dolgozik", "work"],
["hiszi", "You think"],
["hisz", "think"],
["tom", "tom"],
["and", "and"],
["apja", "father"],
["bent", "inside"],
["magukat", "you"],
["körül", "around"],
["tesz", "do"],
["apu", "dad"],
["víz", "water"],
["picsába", "shit"],
["dehogy", "nope"],
["közben", "during"],
["hozzád", "to you"],
["utat", "the way"],
["jót", "good"],
["anyu", "mum"],
["feleségem", "my wife"],
["charlie", "charlie"],
["george", "george"],
["sam", "sam"],
["szerelem", "love"],
["ennyire", "so"],
["joe", "joe"],
["látszik", "appear"],
["fáj", "species"],
["onnan", "thence"],
["édesem", "Honey"],
["venni", "buy"],
["igazából", "truly"],
["amire", "you"],
["ot", "five"],
["szereti", "loves"],
["anyád", "mother"],
["évvel", "years"],
["ránk", "on us"],
["ketten", "two of us"],
["kicsim", "baby"],
["lassan", "slowly"],
["régen", "long time ago"],
["bébi", "baby"],
["tartsd", "keep"],
["nyisd", "open"],
["seggfej", "asshole"],
["veszélyes", "dangerous"],
["tartani", "keep"],
["adni", "give"],
["háború", "war"],
["kinek", "for who"],
["város", "city"],
["üdv", "Hi"],
["eltűnt", "disappeared"],
["re", "from"],
["bárki", "anyone"],
["mondták", "they said"],
["kívül", "outside"],
["meleg", "warm"],
["emberi", "human"],
["fogják", "will"],
["david", "David"],
["felejtsd", "forget"],
["jöttél", "you came"],
["ölni", "kill"],
["michael", "michael"],
["mennünk", "to go"],
["kemény", "hard"],
["mindenkit", "everyone"],
["kor", "disease"],
["beszélj", "speak"],
["hölgyem", "lady"],
["ezer", "thousand"],
["aludni", "to sleep"],
["lássuk", "let's see"],
["fogjuk", "we will"],
["szükségünk", "we need"],
["drága", "expensive"],
["as", "dig"],
["elnök", "chairman"],
["esetleg", "possibly"],
["millió", "million"],
["mai", "modern"],
["hölgyeim", "ladies"],
["föld", "Earth"],
["szükség", "need"],
["sajnos", "unfortunately"],
["siess", "hurry"],
["ismered", "you know"],
["esküszöm", "I swear"],
["lányt", "girl"],
["senkit", "nobody"],
["fegyvert", "weapon"],
["mindannyian", "we all"],
["része", "part of"],
["éreztem", "I felt"],
["mike", "mike"],
["ba", "into"],
["hátra", "back"],
["mondtál", "you say"],
["akarta", "wanted"],
["hihetetlen", "incredible"],
["vajon", "whether"],
["elmegyek", "I go"],
["kerül", "cost"],
["szart", "shit"],
["késő", "late"],
["ismeri", "know"],
["gondol", "think"],
["tudjátok", "you know"],
["kislány", "baby girl"],
["mondjuk", "let's say"],
["lehetne", "It could be"],
["nektek", "for you"],
["gyilkos", "killer"],
["messze", "far"],
["végig", "through"],
["vagyis", "that is,"],
["ettől", "from"],
["kik", "who"],
["segít", "help"],
["látok", "I see"],
["ra", "to"],
["kapcsolatban", "connection"],
["helyen", "place"],
["lehetséges", "possible"],
["nyomás", "pressure"],
["érzed", "you feel"],
["kedvesem", "my dear"],
["korábban", "earlier"],
["tűz", "fire"],
["hagyj", "leave me"],
["hallgass", "shut up"],
["hallani", "Hear"],
["napon", "on the sun"],
["bizony", "certainly"],
["harry", "Harry"],
["óh", "O"],
["valahogy", "somehow"],
["újabb", "newer"],
["keres", "search"],
["szeret", "love"],
["igazat", "truth"],
["felesége", "his wife"],
["tábornok", "general"],
["titeket", "you"],
["kérsz", "Do you want"],
["találkoztunk", "We met"],
["játszani", "to play"],
["hallom", "I hear"],
["mindketten", "both"],
["hirtelen", "suddenly"],
["to", "lake"],
["tegye", "do"],
["itthon", "home"],
["fia", "son"],
["szállj", "get"],
["mögött", "behind"],
["lehetett", "it could be"],
["val", "with"],
["gondolok", "thinking"],
["adott", "given"],
["napja", "day"],
["beszéltem", "I spoke"],
["hozott", "brought"],
["á", "the"],
["távol", "far"],
["végén", "at the end of"],
["egyébként", "by the way"],
["idióta", "idiot"],
["paul", "paul"],
["maradjon", "stay"],
["kutya", "dog"],
["vidd", "take it"],
["lehetetlen", "impossible"],
["család", "family"],
["véget", "end"],
["beszélt", "spoken"],
["hozd", "bring"],
["magára", "himself"],
["közül", "of"],
["halt", "died"],
["adok", "I give"],
["óvatosan", "cautiously"],
["segíthetek", "Can I help you"],
["senkinek", "anyone"],
["bolond", "fool"],
["hoztam", "I"],
["ám", "However,"],
["városban", "in town"],
["rengeteg", "a lot of"],
["rólad", "about you"],
["egészet", "all"],
["hadnagy", "Lieutenant"],
["világon", "on the world"],
["ugyanaz", "same"],
["ltt", "LTT"],
["életet", "life"],
["bárcsak", "if only"],
["menjetek", "go"],
["okos", "clever"],
["hideg", "cold"],
["amiért", "why"],
["jövő", "future"],
["szeretne", "would"],
["rég", "long ago"],
["önt", "you"],
["tudtad", "did you know"],
["nézzétek", "look"],
["bajod", "your problem"],
["járt", "went"],
["ezredes", "colonel"],
["nyugalom", "calmness"],
["bassza", "fuck"],
["szereted", "you love"],
["gonosz", "evil"],
["hoz", "to"],
["miféle", "what"],
["szükséged", "need"],
["papa", "pope"],
["tűnt", "appeared"],
["kapott", "got"],
["szerencsét", "good luck"],
["került", "cost"],
["fasz", "dick"],
["szét", "apart"],
["nyugodtan", "calmly"],
["engedd", "release"],
["érzés", "feeling"],
["annál", "more"],
["baszd", "fuck"],
["hiszen", "because"],
["nevét", "name"],
["sötét", "dark"],
["bob", "bobsled"],
["éjszakát", "night"],
["barátja", "Friend"],
["hagyjuk", "forget it"],
["nők", "women"],
["szerelmes", "in love"],
["hmm", "hmm"],
["barátok", "friends"],
["éhes", "hungry"],
["vizet", "water"],
["gratulálok", "Congratulations"],
["folyton", "always"],
["legyek", "flies"],
["tartok", "I"],
["csinálja", "doing it"],
["ennél", "more"],
["tudnak", "they know"],
["csodás", "beautiful"],
["it", "it"],
["számomra", "for me"],
["valakinek", "to someone"],
["nézzük", "let's see"],
["játék", "game"],
["csinált", "made"],
["azóta", "ever since"],
["benned", "you"],
["nőt", "woman"],
["csapat", "team"],
["amely", "which"],
["kisasszony", "Ms."],
["időben", "in time"],
["mondanom", "to say"],
["azután", "then"],
["értettem", "I understood"],
["szeretnél", "you want"],
["orvos", "doctor"],
["teszi", "do"],
["dolgom", "my thing"],
["keresel", "looking for"],
["egyes", "individual"],
["csinálok", "I'm doing"],
["házban", "house"],
["bizonyos", "certain"],
["világos", "clear"],
["mutasd", "show"],
["amiket", "what"],
["james", "james"],
["értelme", "meaning"],
["sohasem", "never"],
["legyél", "become"],
["baja", "wrong"],
["nézni", "watch"],
["észre", "notice"],
["kár", "damage"],
["figyeljen", "pay attention"],
["látott", "saw"],
["átkozott", "damned"],
["dolgozom", "I work"],
["életét", "life"],
["maradni", "stay"],
["magas", "high"],
["imádom", "I love it"],
["mennyit", "how much"],
["szerettem", "I"],
["enni", "to eat"],
["egyenesen", "straight"],
["hiányzik", "miss"],
["büszke", "proud"],
["kezd", "start"],
["utoljára", "for the last time"],
["kap", "gets"],
["biztonságban", "safely"],
["kávét", "coffee"],
["ad", "give"],
["harmadik", "third"],
["megölni", "kill"],
["létezik", "exists"],
["max", "up"],
["kapd", "get"],
["csinos", "pretty"],
["nálad", "at you"],
["házat", "house"],
["tehetek", "I can"],
["kék", "blue"],
["ilyesmi", "something like that"],
["dollárt", "dollars"],
["on", "you"],
["vér", "blood"],
["csomó", "knot"],
["mary", "mary"],
["mondj", "say"],
["igenis", "indeed"],
["eléggé", "enough"],
["ö", "She"],
["atyám", "father"],
["maradok", "I stay"],
["magadra", "yourself"],
["hívnak", "they call me"],
["segítsen", "help me"],
["földön", "on the ground"],
["kér", "ask"],
["őrmester", "sergeant"],
["úgyis", "anyway"],
["évben", "year"],
["bocsáss", "forgive"],
["mások", "others"],
["finom", "fine"],
["anyja", "mother"],
["legközelebb", "next time"],
["ah", "ah"],
["uh", "uh"],
["hajó", "ship"],
["ideig", "time"],
["beszélünk", "we are talking"],
["mester", "master"],
["hallottad", "heard"],
["mehet", "it can go"],
["állt", "stood"],
["lennél", "you were"],
["rendes", "normal"],
["akarják", "they want"],
["fent", "above"],
["biztonsági", "safety"],
["fordította", "translated"],
["peter", "Peter"],
["rajtam", "on me"],
["megfelelő", "right"],
["kivéve", "except"],
["elmúlt", "past"],
["érzi", "feeling"],
["szinte", "almost"],
["vörös", "red"],
["titkos", "secret"],
["életemben", "my life"],
["hölgy", "Lady"],
["tudott", "known"],
["jimmy", "jimmy"],
["óriási", "giant"],
["köze", "to do"],
["csináltál", "you did"],
["d", "d"],
["meghalni", "die"],
["jutott", "reached"],
["szeretsz", "Do you love me"],
["hallod", "do you hear"],
["lányom", "my daughter"],
["hey", "hey"],
["normális", "normal"],
["elmondom", "I'll tell you"],
["jut", "come"],
["rosszabb", "worse"],
["rajtad", "on you"],
["lényeg", "essence"],
["fura", "strange"],
["lent", "down"],
["üzenetet", "message"],
["bill", "bill"],
["különös", "strange"],
["rájuk", "them"],
["ennyit", "much"],
["világot", "world"],
["évek", "years"],
["kissé", "a bit"],
["hiszek", "I believe"],
["asszony", "woman"],
["mennek", "I would go"],
["kicsoda", "who"],
["találkoztam", "I met"],
["utálom", "I hate"],
["próbáld", "try"],
["nyugodj", "calm"],
["fantasztikus", "fantastic"],
["helyre", "place"],
["megmondtam", "I told"],
["hogyne", "aye"],
["lettem", "I"],
["miközben", "while"],
["régóta", "long ago"],
["évig", "years"],
["életed", "your life"],
["eljött", "came"],
["gyakran", "often"],
["szomorú", "sad"],
["oka", "reason"],
["henry", "henry"],
["odakint", "out"],
["m", "m"],
["ebbe", "in this"],
["bíró", "judge"],
["közelebb", "closer"],
["többiek", "others"],
["találni", "to find"],
["gyereket", "children"],
["nehogy", "lest"],
["rendbe", "right"],
["sokan", "many"],
["mondjam", "tell"],
["talált", "found"],
["hívja", "call"],
["nyolc", "eight"],
["általában", "usually"],
["kocsit", "car"],
["alex", "alex"],
["nappal", "day"],
["terv", "plan"],
["fogalmam", "idea"],
["állandóan", "constantly"],
["mely", "deep"],
["férjem", "my husband"],
["kezed", "your hand"],
["l", "l"],
["figyelem", "Attention"],
["mármint", "I mean"],
["állat", "animal"],
["tettél", "you did"],
["pofa", "jaw"],
["bocsi", "sorry"],
["álljon", "push"],
["hívd", "call"],
["csinálod", "you do"],
["lakik", "live"],
["módon", "way"],
["csináljuk", "let's do it"],
["me", "me"],
["neved", "your name"],
["jobbra", "right"],
["történet", "history"],
["kocsi", "car"],
["k", "k"],
["őszintén", "honestly"],
["részt", "part"],
["balra", "to the left"],
["üres", "empty"],
["n", "n"],
["hívott", "called"],
["nála", "with him"],
["haragudj", "I'm sorry"],
["tartozik", "belongs to"],
["szemben", "against"],
["üdvözlöm", "welcome"],
["ostoba", "silly"],
["oly", "by"],
["akarunk", "we want to"],
["félre", "aside"],
["ray", "ray"],
["mostanában", "nowadays"],
["hívj", "call me"],
["állsz", "Are you"],
["megölte", "killed"],
["nick", "nick"],
["don", "don"],
["zárva", "closed"],
["pokolba", "hell"],
["kétszer", "twice"],
["bírom", "I can"],
["látlak", "I see you"],
["billy", "billy"],
["emlékszik", "remember"],
["barátod", "your friend"],
["kapsz", "you get"],
["örökké", "ever"],
["mondasz", "you say"],
["foglak", "I will"],
["szeretek", "I like to"],
["szeretné", "want"],
["ajtó", "door"],
["fegyver", "weapon"],
["no", "woman"],
["vel", "with"],
["tudnám", "I could"],
["hír", "news"],
["mondjak", "tell"],
["föl", "up"],
["kezét", "hand"],
["adta", "gave"],
["jöttek", "they came"],
["ismét", "again"],
["hagyom", "leave"],
["magunkat", "ourselves"],
["embernek", "people"],
["elé", "edge"],
["akivel", "with whom"],
["állok", "I stand"],
["hagyni", "leave"],
["maradsz", "stay"],
["johnny", "johnny"],
["úristen", "my God"],
["fenét", "hell"],
["jim", "jim"],
["korán", "early"],
["teszem", "I"],
["adtam", "I gave"],
["mostantól", "from now on"],
["gyorsabban", "faster"],
["percre", "minutes"],
["professzor", "Professor"],
["eszembe", "my mind"],
["bocsánatot", "forgiveness"],
["földre", "down"],
["önök", "you"],
["hozta", "brought"],
["időm", "shape"],
["gazdag", "wealthy"],
["gyors", "fast"],
["emiatt", "Because of this"],
["amivel", "which"],
["kevés", "few"],
["alapján", "Based on"],
["meddig", "how long"],
["szerencsés", "lucky"],
["hála", "gratitude"],
["hozzánk", "to us"],
["látsz", "see"],
["könnyen", "easy"],
["próbáltam", "I tried"],
["franc", "franc"],
["o", "She"],
["vegye", "take"],
["visszajövök", "I am coming back"],
["hónap", "month"],
["parancsnok", "commander"],
["nálunk", "here"],
["kezdjük", "let's start"],
["mentem", "I went to"],
["amúgy", "by the way"],
["doki", "Doc"],
["kapni", "to get"],
["elmondani", "to tell"],
["szólsz", "do you think"],
["jöttünk", "we came"],
["fáradt", "tired"],
["film", "movie"],
["testvér", "brother"],
["barátaim", "my friends"],
["csaj", "chick"],
["hal", "fish"],
["abból", "therefrom"],
["vette", "took"],
["nézek", "I look"],
["állunk", "we are"],
["kíváncsi", "curious"],
["ügynök", "agent"],
["bobby", "bobby"],
["élek", "I live"],
["órát", "hours"],
["nyomozó", "detective"],
["hallasz", "hear"],
["bennünket", "us"],
["zene", "music"],
["lánya", "his daughter"],
["kellemes", "pleasant"],
["tennem", "do"],
["kezdődik", "begin"],
["szerelmére", "sake"],
["név", "name"],
["katona", "soldier"],
["zsaru", "cop"],
["indulás", "Departures"],
["kivel", "with who"],
["nemsokára", "soon"],
["szólj", "tell"],
["képet", "picture"],
["nyitva", "open"],
["baleset", "accident"],
["nevű", "more"],
["csupán", "only"],
["időnk", "time"],
["fejét", "head"],
["üzlet", "business"],
["b", "b"],
["örökre", "forever"],
["várom", "look forward"],
["esik", "fall"],
["szükséges", "required"],
["személyes", "personal"],
["hibám", "my mistake"],
["bal", "ball"],
["tetszett", "I liked it"],
["al", "al"],
["engedj", "let me pass"],
["baby", "baby"],
["sarah", "sarah"],
["ördög", "devil"],
["vezet", "lead"],
["esett", "fell"],
["san", "san"],
["aranyos", "nice"],
["kedvenc", "favourite"],
["legtöbb", "most"],
["vicc", "joke"],
["tudna", "could"],
["bármikor", "anytime"],
["találkozni", "meet"],
["férje", "her husband"],
["várni", "wait"],
["mentek", "you go"],
["minél", "more"],
["hívni", "to call"],
["férfiak", "men"],
["délután", "afternoon"],
["önnel", "with you"],
["tűnj", "beat"],
["tudná", "could"],
["eddie", "eddie"],
["csinálom", "I do"],
["szemed", "your eyes"],
["francia", "French"],
["közt", "between"],
["ügyet", "case"],
["dehogynem", "yes it does"],
["hasonló", "similar"],
["tartja", "holds"],
["elfelejtettem", "I forget"],
["in", "tendon"],
["megértem", "I understand"],
["könyvet", "book"],
["of", "of"],
["c", "c"],
["hónapja", "month"],
["megmutatom", "I show you"],
["csinálunk", "we do"],
["csinálta", "did"],
["önöket", "you"],
["félsz", "you are afraid"],
["hagy", "let"],
["akartál", "wanted"],
["várok", "I'm waiting"],
["segítek", "I help"],
["adom", "I give"],
["megmondom", "tell"],
["által", "by"],
["másodperc", "second"],
["őszinte", "honest"],
["őrnagy", "Maj."],
["beszélnünk", "talk"],
["rohadék", "bastard"],
["mégsem", "not"],
["angol", "English"],
["ideges", "nervous"],
["amiről", "about"],
["hinném", "I think"],
["üljön", "sit"],
["örvendek", "how do you do"],
["jók", "goods"],
["richard", "richard"],
["lehetsz", "can you"],
["akarlak", "I want you"],
["hátul", "behind"],
["híres", "famous"],
["kapok", "I get"],
["jake", "jake"],
["élete", "his life"],
["bocsásson", "excuse"],
["húzd", "pull"],
["várjatok", "wait"],
["tök", "pumpkin"],
["szeretnénk", "to"],
["szeretnéd", "you would like"],
["kurvára", "fucking"],
["nevetséges", "ridiculous"],
["bácsi", "Uncle"],
["indul", "starts"],
["hu", "hu"],
["miattad", "because of you"],
["lát", "see"],
["kelj", "get"],
["szuper", "super"],
["hidd", "trust"],
["elől", "Tires"],
["mehetünk", "we can go"],
["rövid", "short"],
["elhinni", "believe"],
["remekül", "great"],
["választ", "choose"],
["zöld", "green"],
["nevet", "name"],
["valódi", "real"],
["szám", "song"],
["ártatlan", "innocent"],
["filmet", "movie"],
["közepén", "in the middle"],
["levelet", "write"],
["hagyta", "let it"],
["órája", "hours ago"],
["elmegyünk", "go to"],
["csoda", "miracle"],
["pénzem", "my money"],
["jane", "jane"],
["hogyhogy", "how come"],
["vártam", "I expected"],
["szólt", "Commented"],
["hamar", "soon"],
["meghal", "die"],
["valakivel", "with somebody"],
["hagytam", "I left"],
["anna", "Anna"],
["en", "I"],
["beszélnem", "talk to"],
["újság", "newspaper"],
["istennek", "God"],
["német", "German"],
["he", "he"],
["ribanc", "slut"],
["ország", "country"],
["értek", "value"],
["rosszat", "bad"],
["bizonyára", "surely"],
["danny", "danny"],
["akiket", "who"],
["utcán", "on the street"],
["veszi", "takes"],
["jártam", "I went"],
["különösen", "particularly"],
["my", "my"],
["évet", "year"],
["rendőr", "policeman"],
["elmenni", "to go"],
["ígérem", "I promise"],
["száz", "hundred"],
["született", "born"],
["forró", "hot"],
["élő", "live"],
["csináltad", "you do"],
["csináljak", "do"],
["hm", "eh"],
["vált", "change"],
["órán", "in the lesson"],
["mocskos", "filthy"],
["egyszerre", "at the same time"],
["semmilyen", "no"],
["hívom", "call"],
["veletek", "with you"],
["kérdést", "question"],
["keményen", "hard"],
["tommy", "tommy"],
["várjunk", "wait"],
["akartok", "want"],
["szél", "wind"],
["menjek", "I go"],
["sört", "shorts"],
["életbe", "effect"],
["eljön", "will come"],
["ötletem", "idea"],
["főleg", "especially"],
["csinálj", "do"],
["dolgozott", "worked"],
["hozza", "will bring"],
["pillanatban", "moment"],
["közös", "common"],
["tartott", "held"],
["láttál", "did you see"],
["kormány", "government"],
["friss", "fresh"],
["lehetőség", "possibility"],
["ból", "from"],
["ismerek", "I know"],
["kb", "ca."],
["fuss", "run"],
["vinni", "take"],
["megnézem", "I look"],
["hacsak", "unless"],
["láttalak", "I saw you"],
["olyat", "something"],
["tesó", "Bro"],
["keresek", "seeking"],
["anélkül", "without that"],
["halálra", "death"],
["küldött", "sent"],
["darab", "piece"],
["ügyes", "clever"],
["will", "will"],
["csinálnak", "they are doing"],
["gép", "machine"],
["során", "in"],
["szíves", "kind"],
["számodra", "for you"],
["la", "la"],
["azelőtt", "before"],
["törvény", "law"],
["amilyen", "as"],
["esetben", "case"],
["vett", "took"],
["tól", "from"],
["steve", "steve"],
["hozni", "to bring"],
["mik", "what"],
["halni", "die"],
["örömmel", "gladly"],
["tudnék", "I could"],
["írta", "written by"],
["tartsa", "keep"],
["bármilyen", "any"],
["dühös", "angry"],
["tartom", "I"],
["mekkora", "how big"],
["meglátjuk", "we'll see"],
["gyerekeket", "children"],
["ellenére", "despite"],
["idegen", "foreign"],
["menjenek", "go"],
["pillanatra", "moment"],
["helyett", "instead of"],
["tied", "yours"],
["sőt", "moreover"],
["érkezett", "arrived"],
["mindenhol", "everywhere"],
["zsaruk", "cops"],
["szobában", "in the room"],
["használni", "use"],
["álom", "dream"],
["felett", "above"],
["meglepetés", "surprise"],
["fogva", "from"],
["r", "r"],
["arany", "gold"],
["menned", "to go"],
["véletlenül", "accidentally"],
["táncolni", "dance"],
["gyilkosság", "murder"],
["hinni", "to believe"],
["nevében", "on behalf of"],
["bajban", "in trouble"],
["jöjjenek", "come to"],
["inni", "drink"],
["részeg", "drunk"],
["jöhet", "can come"],
["érdekli", "interested in"],
["szoba", "room"],
["tony", "tony"],
["tegyek", "do"],
["akarjuk", "To"],
["istenit", "deify"],
["segítséget", "help"],
["szívességet", "favor"],
["j", "j"],
["nézett", "watched"],
["elmegy", "go away"],
["amik", "what"],
["teszek", "I"],
["biztonságos", "safe"],
["miben", "wherein"],
["embereknek", "for people"],
["chris", "chris"],
["válasz", "answer"],
["amiben", "in which"],
["mitől", "what"],
["nézzen", "look"],
["alszik", "sleep"],
["viccelsz", "are you joking"],
["elegem", "I've had enough"],
["autó", "car"],
["időre", "time"],
["munkám", "my work"],
["kilenc", "nine"],
["olvastam", "I read"],
["felügyelő", "supervisor"],
["eleget", "meet"],
["hiba", "fault"],
["iskolába", "to school"],
["valamilyen", "any"],
["bátor", "brave"],
["magadnak", "for yourself"],
["gondolj", "think"],
["szemem", "my eyes"],
["klassz", "cool"],
["rendesen", "neatly"],
["piros", "red"],
["kínai", "Chinese"],
["katonai", "military"],
["lévő", "being"],
["ölte", "killed"],
["érzek", "sense"],
["kérni", "to ask"],
["férfit", "man"],
["ról", "About"],
["mihez", "what"],
["fizetni", "to pay"],
["legfontosabb", "the most important"],
["magányos", "lonely"],
["tetted", "hast"],
["barát", "friend"],
["telefon", "phone"],
["vén", "old"],
["kép", "picture"],
["hiszik", "think"],
["fickót", "guy"],
["napig", "days"],
["kórházba", "hospital"],
["vacsora", "dinner"],
["dobd", "throw"],
["egymás", "each other"],
["aggódjon", "worry"],
["megölték", "they killed"],
["alkalommal", "time"],
["kértem", "I asked"],
["fény", "light"],
["barom", "beast"],
["fejezd", "finish"],
["helyi", "local"],
["robert", "robert"],
["vegyél", "buy"],
["gyenge", "weak"],
["kiváló", "excellent"],
["hercegnő", "princess"],
["ismertem", "I knew"],
["némi", "some"],
["jerry", "jerry"],
["magamnak", "for me"],
["keresem", "my request"],
["ül", "sit"],
["basszus", "bass"],
["telefont", "phone"],
["közé", "among"],
["mért", "because"],
["további", "further"],
["szeretni", "to love"],
["nál", "at"],
["veszem", "I"],
["buli", "party"],
["felség", "majesty"],
["bátyám", "my elder brother"],
["herceg", "prince"],
["yeah", "yeah"],
["előtte", "before"],
["lenned", "you be"],
["nahát", "Wow"],
["miatta", "about it"],
["függ", "It depends"],
["olyanok", "are"],
["italt", "drink"],
["mozdulj", "Freeze"],
["segítsek", "can I help you"],
["kezem", "I have"],
["lee", "lee"],
["állnak", "are"],
["charles", "charles"],
["igazságot", "truth"],
["könyv", "book"],
["iskola", "school"],
["tudnád", "Can you"],
["esélyt", "chance"],
["fejem", "my head"],
["hátsó", "rear"],
["rendőrséget", "police"],
["sir", "Sir"],
["félj", "Fear"],
["börtönben", "prison"],
["alkalom", "occasion"],
["dolgozol", "you work"],
["messzire", "far"],
["hete", "a week ago"],
["apró", "small"],
["vigyázzon", "look out"],
["írni", "write"],
["tudnál", "could you"],
["találom", "I find"],
["magától", "by himself"],
["szabadon", "free"],
["ingyen", "free"],
["rájöttem", "I realized"],
["élve", "alive"],
["várost", "city"],
["azonban", "However"],
["adjon", "give"],
["nézzék", "look"],
["mehetek", "I can go"],
["andy", "andy"],
["legalábbis", "at least"],
["terhes", "pregnant"],
["dave", "dave"],
["tüzet", "fire"],
["állni", "stand"],
["hagyott", "left"],
["érezni", "feel"],
["írja", "writes"],
["walter", "walter"],
["benneteket", "you"],
["los", "los"],
["köcsög", "jug"],
["faszt", "dick"],
["élt", "lived"],
["lettél", "You"],
["óvatos", "careful"],
["sikerül", "succeed"],
["rendszer", "system"],
["lehetek", "I can be"],
["szerelmem", "my love"],
["baba", "midwife"],
["os", "ancestor"],
["ről", "from"],
["zenét", "music"],
["nővér", "sister"],
["hű", "loyal"],
["től", "from"],
["kórházban", "in hospital"],
["fejed", "head"],
["napra", "day"],
["huh", "huh"],
["találtak", "found"],
["képzelni", "imagine"],
["élnek", "they live"],
["tuti", "sure"],
["futás", "running"],
["ezután", "thereafter"],
["körbe", "around"],
["valamire", "something"],
["várja", "waiting for"],
["hátha", "maybe"],
["ír", "Irish"],
["bíróság", "court"],
["kérdeztem", "I asked"],
["börtönbe", "prison"],
["nincsen", "is not"],
["pokol", "hell"],
["női", "female"],
["amerika", "America"],
["miattam", "because of me"],
["york", "york"],
["ügyvéd", "lawyer"],
["martin", "martin"],
["éljen", "Long live"],
["figyeljetek", "listen"],
["világban", "world"],
["bizonyíték", "evidence"],
["járni", "to walk"],
["túlságosan", "too"],
["végeztem", "I graduated"],
["hall", "hall"],
["hozom", "I bring"],
["mark", "Mark"],
["halála", "her death"],
["levegőt", "breath"],
["hajót", "ship"],
["vigye", "Apply"],
["szólok", "I will speak"],
["mérges", "angry"],
["tulajdonképpen", "actually"],
["vezető", "conductor"],
["szeretett", "lovely"],
["that", "hurt"],
["próbálok", "I'm trying"],
["kevesebb", "less"],
["teszed", "you do"],
["földet", "earth"],
["disznó", "pig"],
["fiút", "boy"],
["másikat", "other"],
["ráadásul", "Moreover"],
["személyesen", "personally"],
["játszik", "play"],
["vezetni", "drive"],
["egymással", "with each other"],
["miénk", "ours"],
["hagyjátok", "leave"],
["büdös", "smelly"],
["kocsiban", "car"],
["lehetnek", "may be"],
["kért", "garden"],
["jelenleg", "currently"],
["megígérem", "I promise"],
["családom", "my family"],
["fordulj", "turn"],
["megtalálni", "to find"],
["tudnom", "I know"],
["lássam", "see"],
["tehetem", "I can"],
["tarts", "hold"],
["íme", "lo"],
["családi", "family"],
["csináljunk", "we do"],
["aznap", "that day"],
["ei", "ei"],
["undorító", "disgusting"],
["személy", "person"],
["tagja", "member"],
["sziasztok", "Hello"],
["nél", "than"],
["megtaláltam", "found it"],
["aminek", "which"],
["szerezni", "get"],
["ismer", "know"],
["élünk", "we live in"],
["illeti", "Concerning"],
["különböző", "different"],
["fele", "half of"],
["segített", "helped"],
["larry", "larry"],
["írtam", "I have written"],
["részét", "part"],
["élsz", "you live"],
["hogyha", "that if"],
["hálás", "grateful"],
["várnak", "expect"],
["fő", "main"],
["ezúttal", "this time"],
["vak", "blind"],
["képesek", "able"],
["városba", "city"],
["próbálom", "I try to"],
["szex", "sex"],
["súlyos", "serious"],
["hős", "hero"],
["hozok", "I will bring"],
["sor", "row"],
["ajándék", "gift"],
["teát", "tea"],
["fajta", "species"],
["megtenni", "to do"],
["csendben", "in silence"],
["beszéljen", "speak"],
["készült", "made"],
["legyenek", "are"],
["érdekében", "to"],
["hozz", "bring"],
["ruhát", "clothes"],
["krisztus", "Christ"],
["lehetőséget", "opportunity"],
["ismersz", "you know me"],
["megőrültél", "crazy"],
["errefelé", "around"],
["válik", "become"],
["hiszel", "you believe"],
["beléd", "with you"],
["dolga", "do"],
["elmész", "you go"],
["művelsz", "doing"],
["olvasni", "read"],
["bántani", "hurt"],
["zsidó", "Jewish"],
["magához", "himself"],
["köztünk", "between us"],
["egyesült", "united"],
["rész", "section"],
["dolgoztam", "I worked"],
["máskor", "another time"],
["tartunk", "Speaking"],
["kérdezd", "ask"],
["kettőt", "two"],
["tökéletesen", "perfectly"],
["ahogyan", "as"],
["kate", "kate"],
["thomas", "thomas"],
["nagyi", "granny"],
["beszélgetni", "to talk"],
["arthur", "arthur"],
["testvérem", "my brother"],
["természetes", "natural"],
["látjuk", "we see"],
["várunk", "we wait"],
["keresni", "to search"],
["pasi", "guy"],
["had", "military"],
["elmentem", "I went to"],
["próbálja", "try"],
["szokott", "he used"],
["semmire", "for nothing"],
["zavar", "confusion"],
["ugyanazt", "the same"],
["hiába", "in vain"],
["orosz", "Russian"],
["öregem", "champ"],
["ig", "up"],
["hallottál", "heard"],
["ekkora", "so much"],
["mindenre", "for everything"],
["beszéljünk", "let's talk"],
["sokszor", "often"],
["hadsereg", "army"],
["orvosi", "medical"],
["oldalon", "page"],
["véletlen", "random"],
["carl", "carl"],
["hibát", "errors"],
["feleségül", "married"],
["hagyjon", "leave"],
["elmondta", "said"],
["szedd", "pick"],
["írt", "wrote"],
["jel", "mark"],
["találtunk", "we found"],
["nyilván", "obviously"],
["beszéltünk", "We spoke"],
["áldozat", "sacrifice"],
["sehol", "nowhere"],
["mellé", "next to"],
["szeme", "his eye"],
["min", "min"],
["durva", "rough"],
["életemet", "my life"],
["hajlandó", "willing"],
["hallotta", "heard"],
["legyünk", "let's be"],
["gáz", "gas"],
["mindez", "all of this"],
["fenn", "up"],
["szembe", "face"],
["hallott", "heard"],
["autót", "car"],
["külön", "separately"],
["kuss", "Shut up"],
["szerencse", "luck"],
["hamis", "false"],
["ágyban", "in bed"],
["gondolta", "thought"],
["veszed", "threat"],
["kapcsolat", "relationship"],
["hazugság", "lie"],
["húzz", "draw"],
["feleséged", "wife"],
["eset", "case"],
["tartozom", "I belong"],
["meglátod", "see"],
["ilyenkor", "this time"],
["dolgod", "business"],
["legjobban", "best"],
["fogadok", "I bet"],
["alak", "form"],
["parancsot", "command"],
["at", "at"],
["hahó", "Hey"],
["mély", "deep"],
["utánam", "me"],
["atya", "father"],
["elvesztettem", "I lost"],
["szintén", "also"],
["ügyben", "in case"],
["hagyják", "leave"],
["talál", "find"],
["esti", "evening"],
["mindet", "all"],
["karácsonyt", "Christmas"],
["we", "we"],
["brian", "brian"],
["ellene", "against"],
["húsz", "twenty"],
["mindkét", "both"],
["belső", "internal"],
["mehetsz", "you can go"],
["továbbra", "continue"],
["hú", "wow"],
["hülyeség", "nonsense"],
["bármelyik", "either"],
["jelen", "present"],
["szobát", "Make"],
["figyeld", "watch"],
["kezdtem", "I began"],
["eszed", "your mind"],
["ugyanúgy", "as well"],
["csendet", "quiet"],
["keresi", "looking"],
];
