
const italian = [
["non", "not"],
["che", "that"],
["di", "of"],
["e", "is"],
["la", "there"],
["il", "the"],
["un", "a"],
["a", "to"],
["è", "is"],
["per", "for"],
["in", "in"],
["una", "a"],
["sono", "I am"],
["mi", "me"],
["ho", "I have"],
["si", "Yes"],
["lo", "the"],
["ma", "but"],
["ti", "you"],
["ha", "has"],
["le", "the"],
["cosa", "thing"],
["con", "with"],
["da", "from"],
["se", "self"],
["come", "how"],
["io", "I"],
["ci", "us"],
["questo", "this"],
["qui", "here"],
["hai", "you have"],
["bene", "well"],
["sei", "six"],
["tu", "you"],
["del", "of the"],
["me", "myself"],
["mio", "my"],
["al", "to the"],
["solo", "only"],
["sì", "Yup"],
["tutto", "all"],
["te", "you"],
["più", "more"],
["della", "of the"],
["era", "era"],
["lei", "she"],
["gli", "the"],
["mia", "my"],
["questa", "this"],
["ne", "neither"],
["fare", "do"],
["quando", "when"],
["essere", "to be"],
["fatto", "done"],
["perché", "because"],
["so", "I know"],
["ora", "Now"],
["o", "or"],
["va", "it goes"],
["mai", "never"],
["chi", "who"],
["detto", "say"],
["così", "so"],
["alla", "a"],
["quello", "one"],
["tutti", "all"],
["oh", "Oh"],
["anche", "also"],
["molto", "very"],
["dei", "of"],
["lui", "he"],
["voglio", "I want"],
["niente", "anything"],
["stato", "state"],
["grazie", "thank you"],
["dove", "where is it"],
["abbiamo", "we have"],
["tuo", "your"],
["nel", "in"],
["allora", "then"],
["sta", "It is"],
["posso", "I can"],
["siamo", "we are"],
["uno", "one"],
["vuoi", "do you want"],
["hanno", "have"],
["noi", "we"],
["prima", "before"],
["suo", "his"],
["stai", "are you"],
["tua", "your"],
["due", "two"],
["ancora", "yet"],
["casa", "home"],
["fa", "does"],
["sua", "her"],
["qualcosa", "something"],
["vero", "true"],
["su", "on"],
["sai", "you know"],
["sia", "be"],
["sempre", "always"],
["dire", "to say"],
["loro", "their"],
["quella", "that"],
["andiamo", "here we go"],
["andare", "to go"],
["delle", "of the"],
["vi", "you"],
["quel", "that"],
["ehi", "Hey"],
["devo", "I must"],
["signore", "lord"],
["nella", "in"],
["ad", "to"],
["tempo", "time"],
["certo", "of course"],
["voi", "you"],
["vita", "life"],
["forse", "perhaps"],
["adesso", "now"],
["fuori", "out"],
["li", "there"],
["davvero", "really"],
["sto", "I am"],
["anni", "years"],
["poi", "then"],
["altro", "other"],
["dio", "God"],
["via", "Street"],
["visto", "seen"],
["proprio", "own"],
["parte", "part"],
["ok", "ok"],
["beh", "Well"],
["puoi", "can"],
["credo", "I think"],
["sul", "on the"],
["ciao", "Hello"],
["volta", "time"],
["cose", "whats this"],
["quanto", "how much"],
["uomo", "man"],
["nessuno", "nobody"],
["padre", "father"],
["dopo", "after"],
["amico", "friend"],
["fai", "do"],
["può", "can he"],
["vuole", "wants"],
["posto", "place"],
["lavoro", "work"],
["qualcuno", "someone"],
["già", "already"],
["meglio", "better"],
["devi", "you have to"],
["ed", "and"],
["giorno", "day"],
["vedere", "see"],
["cazzo", "dick"],
["dai", "come on"],
["cui", "which"],
["cos", "cos"],
["dal", "from"],
["vai", "Go"],
["bisogno", "need"],
["ogni", "every"],
["vieni", "Come"],
["ecco", "here"],
["senza", "without"],
["ce", "there is"],
["male", "bad"],
["stata", "was"],
["troppo", "too much"],
["signor", "Mr"],
["qualche", "some"],
["mamma", "mum"],
["perchè", "why"],
["tanto", "much"],
["dobbiamo", "we have to"],
["avete", "you have"],
["dalla", "from"],
["sarà", "Sara"],
["prego", "You are welcome"],
["modo", "way"],
["grande", "great"],
["tra", "between"],
["ll", "The"],
["miei", "my"],
["guarda", "look"],
["favore", "favor"],
["alle", "to"],
["quindi", "therefore"],
["sembra", "it seems"],
["sa", "know"],
["soldi", "money"],
["parlare", "speak"],
["sulla", "on"],
["sarebbe", "would be"],
["dispiace", "sorry"],
["ai", "to"],
["deve", "needs to"],
["gente", "people"],
["dice", "He says"],
["tre", "three"],
["madre", "mother"],
["momento", "moment"],
["aspetta", "wait up"],
["cosi", "so"],
["altra", "other"],
["questi", "these"],
["siete", "you are"],
["nuovo", "new"],
["successo", "success"],
["mondo", "world"],
["piace", "like it"],
["nostro", "our"],
["aveva", "had"],
["forza", "power"],
["possiamo", "We can"],
["avere", "to have"],
["oggi", "today"],
["dov", "dov"],
["ah", "ha"],
["figlio", "son"],
["dentro", "inside"],
["ragazzi", "boys"],
["penso", "I think"],
["ero", "I was"],
["accordo", "agreement"],
["queste", "these"],
["faccio", "I do"],
["facendo", "doing"],
["degli", "from"],
["fosse", "it were"],
["donna", "woman"],
["giusto", "quite right"],
["avevo", "I had"],
["altri", "others"],
["nome", "first name"],
["avanti", "come on"],
["eh", "huh"],
["subito", "immediately"],
["tutte", "all"],
["signora", "Mrs"],
["basta", "thats enough"],
["notte", "night"],
["farlo", "to do it"],
["sapere", "know"],
["tutta", "all"],
["bella", "beautiful"],
["lì", "there"],
["porta", "door"],
["sicuro", "sure"],
["testa", "head"],
["faccia", "face"],
["vado", "I go"],
["senti", "feeling"],
["persone", "people"],
["nostra", "our"],
["sentito", "heard"],
["stare", "to stay"],
["appena", "as soon as"],
["sotto", "under"],
["uomini", "men"],
["preso", "taken"],
["merda", "shit"],
["tipo", "guy"],
["ragazzo", "boy"],
["morto", "dead"],
["paura", "fear"],
["pronto", "ready"],
["avuto", "had"],
["buona", "good"],
["ragazza", "girl"],
["presto", "soon"],
["erano", "were"],
["moglie", "wife"],
["capito", "I got it"],
["stesso", "same"],
["abbia", "has"],
["é", "is"],
["potrebbe", "could"],
["suoi", "his"],
["pensi", "think"],
["problema", "problem"],
["amore", "love"],
["ii", "ii"],
["insieme", "together"],
["papà", "Pope"],
["tuoi", "your"],
["succede", "It happens"],
["volte", "times"],
["domani", "tomorrow"],
["vorrei", "I would like to"],
["tesoro", "treasure"],
["caso", "case"],
["ragione", "reason"],
["storia", "history"],
["okay", "okay"],
["volevo", "I wanted"],
["qua", "here"],
["prendere", "to take"],
["fino", "till"],
["nulla", "nothing"],
["trovato", "found"],
["bello", "beautiful"],
["dici", "you say"],
["macchina", "machine"],
["venire", "to come"],
["dato", "given"],
["nei", "in"],
["giorni", "days"],
["dico", "I say"],
["mano", "but no"],
["stiamo", "we are"],
["aver", "having"],
["serve", "need"],
["famiglia", "family"],
["buon", "good"],
["vediamo", "we see"],
["terra", "land"],
["fratello", "brother"],
["stanno", "they are"],
["letto", "bed"],
["facciamo", "let's make"],
["scusa", "sorry"],
["piacere", "pleasure"],
["fine", "end"],
["secondo", "second"],
["ciò", "it"],
["aiuto", "Help"],
["avrei", "I would have"],
["amici", "friends"],
["polizia", "police"],
["piano", "plan"],
["capo", "boss"],
["state", "been"],
["diavolo", "Devil"],
["meno", "less"],
["morte", "death"],
["capisco", "I see"],
["vedo", "I see"],
["stati", "States"],
["neanche", "neither"],
["quale", "which"],
["primo", "first"],
["bel", "beautiful"],
["vostro", "your"],
["là", "there"],
["scusi", "sorry"],
["vedi", "you see"],
["strada", "Street"],
["quei", "those"],
["po", "bit"],
["persona", "person"],
["occhi", "eyes"],
["giro", "round"],
["quelle", "those"],
["quasi", "almost"],
["salve", "Hello"],
["credi", "believe"],
["mentre", "while"],
["dollari", "dollars"],
["bambino", "child"],
["sera", "evening"],
["film", "movie"],
["avrebbe", "it would have"],
["ucciso", "killed"],
["indietro", "back"],
["contro", "versus"],
["sento", "I hear"],
["dovuto", "due"],
["tornare", "return"],
["mani", "hands"],
["mie", "my"],
["acqua", "water"],
["nessun", "no"],
["abbastanza", "quite"],
["pensavo", "I thought"],
["minuti", "minutes"],
["bambini", "children"],
["andato", "went"],
["vostra", "your"],
["finito", "finished"],
["cercando", "looking for"],
["tardi", "late"],
["trovare", "to find"],
["stavo", "I was"],
["col", "with the"],
["viene", "it is"],
["veramente", "really"],
["ore", "hours"],
["nostri", "our"],
["chiama", "who loves"],
["far", "to"],
["guerra", "war"],
["piccolo", "small"],
["prendi", "take"],
["anch", "anch"],
["sola", "one"],
["cuore", "heart"],
["nemmeno", "not even"],
["forte", "strong"],
["bravo", "good boy"],
["quelli", "those"],
["giù", "down"],
["stasera", "tonight"],
["parla", "speaks"],
["venuto", "came"],
["sig", "Mr"],
["sue", "its"],
["comunque", "However"],
["numero", "number"],
["punto", "point"],
["roba", "stuff"],
["fanno", "do"],
["stessa", "itself"],
["scuola", "school"],
["felice", "happy"],
["vecchio", "old"],
["perso", "lost"],
["uscire", "go out"],
["città", "city"],
["importa", "it matters"],
["dietro", "behind"],
["invece", "instead"],
["pensato", "thought"],
["fu", "it was"],
["lascia", "leaves"],
["nelle", "in"],
["donne", "women"],
["importante", "important"],
["figlia", "daughter"],
["spero", "hope"],
["chiesto", "asked"],
["poco", "little"],
["verso", "towards"],
["marito", "husband"],
["morire", "to die"],
["dovrebbe", "it should"],
["com", "com"],
["migliore", "best"],
["quattro", "four"],
["puttana", "bitch"],
["cinque", "five"],
["almeno", "at least"],
["ricordi", "memories"],
["sapevo", "I knew"],
["però", "However"],
["sangue", "blood"],
["settimana", "week"],
["potrei", "I could"],
["entrare", "to come in"],
["fate", "you do"],
["colpa", "fault"],
["dottore", "doctor"],
["pensa", "thinks"],
["anno", "year"],
["possibile", "possible"],
["piedi", "feet"],
["vicino", "close"],
["amo", "I love"],
["dovrei", "I should"],
["passato", "past"],
["piccola", "small"],
["messo", "put"],
["capitano", "captain"],
["fatta", "done"],
["ultima", "latest"],
["qual", "what"],
["andata", "going"],
["dovresti", "you should"],
["dammi", "give me"],
["farò", "lighthouse"],
["sentire", "feel"],
["altre", "other"],
["pensare", "to think"],
["vivere", "to live"],
["portato", "brought"],
["eri", "you was"],
["riesco", "I can"],
["gia", "already"],
["ia", "ia"],
["parlando", "speaking"],
["pure", "mashed potato"],
["stanza", "room"],
["telefono", "phone"],
["ascolta", "listen"],
["buongiorno", "good morning"],
["parlato", "spoken"],
["conosco", "I know"],
["nessuna", "none"],
["tue", "your"],
["significa", "it means"],
["chiamato", "called"],
["musica", "music"],
["lasciato", "left"],
["volete", "want"],
["conto", "bill"],
["corpo", "body"],
["dare", "give"],
["ricordo", "I remember"],
["culo", "ass"],
["perdere", "to lose"],
["serio", "serious"],
["be", "well"],
["mezzo", "half"],
["andando", "going"],
["vista", "view"],
["difficile", "hard"],
["stava", "he was"],
["sopra", "above"],
["mangiare", "to eat"],
["prova", "test"],
["ieri", "yesterday"],
["genere", "kind"],
["fuoco", "fire"],
["strano", "strange"],
["ben", "well"],
["paese", "country"],
["signorina", "young lady"],
["parola", "word"],
["figli", "sons"],
["ln", "ln"],
["possa", "can"],
["magari", "maybe"],
["fortuna", "luck"],
["voleva", "she wanted"],
["problemi", "problems"],
["mesi", "months"],
["dimmi", "tell me"],
["potuto", "could"],
["chiamo", "call"],
["dicendo", "saying"],
["quanti", "How many"],
["gioco", "game"],
["possono", "can"],
["signori", "gentlemen"],
["farti", "you"],
["qualsiasi", "any"],
["molti", "lot of"],
["resto", "rest"],
["ragazze", "girls"],
["nuova", "new"],
["sorella", "sister"],
["davanti", "in front of"],
["re", "king"],
["foto", "photo"],
["dica", "tell"],
["torna", "returns"],
["domanda", "demand"],
["pare", "apparently"],
["pace", "peace"],
["tieni", "keep"],
["mente", "mind"],
["sacco", "bag"],
["auto", "car"],
["finita", "over"],
["capire", "to understand"],
["verità", "truth"],
["paio", "pair"],
["cane", "dog"],
["vogliono", "want"],
["attimo", "moment"],
["senso", "sense"],
["dovremmo", "we should"],
["lavorare", "to work"],
["perche", "because"],
["vivo", "I live"],
["stia", "is"],
["dalle", "give her"],
["andate", "go"],
["attenzione", "caution"],
["fra", "between"],
["pistola", "gun"],
["agli", "to"],
["vada", "go"],
["mr", "mr"],
["farmi", "me"],
["festa", "party"],
["saranno", "they will be"],
["vede", "sees"],
["buono", "good"],
["dicono", "they say"],
["presidente", "president"],
["unica", "only"],
["bere", "drinking"],
["passare", "to pass"],
["unico", "single"],
["sapete", "you know"],
["fantastico", "fantastic"],
["affari", "business"],
["dell", "of"],
["cielo", "sky"],
["coraggio", "courage"],
["spiace", "sorry"],
["ufficio", "office"],
["cara", "Dear"],
["agente", "agent"],
["smettila", "stop that"],
["luce", "light"],
["fammi", "let me"],
["dormire", "to sleep"],
["facile", "easy"],
["piu", "more"],
["capisci", "Do you understand"],
["parole", "words"],
["hey", "hey"],
["avessi", "I had"],
["giovane", "young"],
["potete", "you can"],
["divertente", "funny"],
["new", "new"],
["generale", "general"],
["ultimo", "last"],
["entra", "come in"],
["controllo", "control"],
["voce", "voice"],
["lungo", "long"],
["morta", "dead"],
["gran", "great"],
["esatto", "exact"],
["morti", "dead"],
["probabilmente", "probably"],
["cena", "dinner"],
["libro", "book"],
["sappiamo", "we know"],
["siano", "are"],
["arrivato", "arrived"],
["avevi", "you had"],
["squadra", "team"],
["scritto", "written"],
["faremo", "we will"],
["fatti", "facts"],
["credere", "to believe"],
["cristo", "Christ"],
["cerca", "search for"],
["vogliamo", "we want"],
["sulle", "on"],
["nostre", "our"],
["uccidere", "kill"],
["vuol", "wants"],
["farà", "will make"],
["attento", "careful"],
["sarei", "I would be"],
["molte", "many"],
["voglia", "wish"],
["chiedo", "I ask"],
["esattamente", "exactly"],
["pronti", "ready"],
["cura", "care"],
["sui", "on"],
["caro", "Dear"],
["chiaro", "clear"],
["lontano", "far"],
["tratta", "is"],
["pazzo", "crazy"],
["sicura", "safety"],
["stronzo", "asshole"],
["potresti", "could"],
["cercare", "search for"],
["ordine", "order"],
["conosci", "know"],
["parli", "you speak"],
["perfetto", "perfect"],
["sbagliato", "mistaken"],
["quest", "quest"],
["dieci", "ten"],
["restare", "to remain"],
["venite", "you come"],
["prendo", "I take"],
["stupido", "stupid"],
["arrivare", "arrive"],
["aria", "air"],
["credevo", "I thought"],
["passo", "step"],
["motivo", "reason"],
["prossima", "next"],
["sarai", "you will be"],
["farai", "do"],
["alcuni", "some"],
["chiami", "who do you Love"],
["lasciami", "leave me"],
["sarò", "I ll be"],
["fermo", "stationary"],
["eravamo", "we were"],
["aspettare", "wait"],
["viaggio", "travel"],
["finché", "as long as"],
["mettere", "to put"],
["resta", "remains"],
["arriva", "arrives"],
["aspetto", "appearance"],
["avresti", "you would have"],
["campo", "field"],
["papa", "Pope"],
["arrivo", "arrival"],
["dello", "of the"],
["minuto", "minute"],
["portare", "bring"],
["guardare", "to watch"],
["camera", "room"],
["benissimo", "very well"],
["milioni", "millions"],
["lasciare", "to leave"],
["diventare", "become"],
["ospedale", "Hospital"],
["venga", "come"],
["zio", "uncle"],
["soltanto", "only"],
["bocca", "mouth"],
["né", "neither"],
["zitto", "Shut up"],
["continua", "go on"],
["bagno", "bathroom"],
["durante", "during"],
["ricevuto", "received"],
["bisogna", "need"],
["idiota", "idiot"],
["negli", "in"],
["bambina", "child"],
["colpo", "blow"],
["fretta", "hurry"],
["dottor", "Dr."],
["metti", "put"],
["causa", "cause"],
["inizio", "Start"],
["giocare", "play"],
["voluto", "would"],
["trova", "find"],
["vanno", "they go"],
["permesso", "permit"],
["armi", "weapons"],
["bastardo", "Bastard"],
["devono", "must"],
["crede", "you think"],
["succedendo", "happening"],
["guardate", "watch"],
["tornato", "got back"],
["potremmo", "we could"],
["dovete", "you have to"],
["venuta", "coming"],
["vostri", "your"],
["sole", "Sun"],
["torno", "I return"],
["gruppo", "group"],
["genitori", "parents"],
["situazione", "situation"],
["dirmi", "tell me"],
["lasci", "leave"],
["the", "the"],
["denaro", "money"],
["settimane", "weeks"],
["alto", "tall"],
["preoccuparti", "worry"],
["grandi", "great"],
["onore", "honor"],
["piacerebbe", "would like to"],
["sogno", "dream"],
["giornata", "day"],
["deciso", "decided"],
["capelli", "hair"],
["pezzo", "piece"],
["disse", "She said"],
["tom", "tom"],
["porto", "port"],
["chiamare", "to call"],
["addio", "goodbye"],
["york", "york"],
["allo", "the"],
["fondo", "background"],
["aspetti", "wait"],
["traduzione", "translation"],
["mandato", "mandate"],
["guardi", "look"],
["ormai", "by now"],
["piuttosto", "Rather"],
["oltre", "over"],
["matrimonio", "marriage"],
["circa", "about"],
["brava", "good"],
["vattene", "get out"],
["grae", "grae"],
["avesse", "had"],
["qualunque", "whatever"],
["www", "www"],
["frank", "frank"],
["vera", "real"],
["futuro", "future"],
["do", "do"],
["joe", "joe"],
["prende", "he takes"],
["sicurezza", "safety"],
["vengo", "I come"],
["potere", "power"],
["tanti", "many"],
["scelta", "choice"],
["legge", "law"],
["odio", "hate"],
["cibo", "food"],
["fame", "hunger"],
["prigione", "prison"],
["guai", "trouble"],
["mattina", "morning"],
["quell", "that"],
["semplice", "simple"],
["chiunque", "anyone"],
["vecchia", "old"],
["brutto", "ugly"],
["usare", "use"],
["saperlo", "know"],
["mese", "month"],
["occhio", "eye"],
["speciale", "special"],
["provare", "try out"],
["cambiare", "to change"],
["domande", "questions"],
["piacciono", "like"],
["funziona", "it works"],
["sistema", "system"],
["natale", "Christmas"],
["prossimo", "next one"],
["messaggio", "message"],
["incidente", "accident"],
["radio", "radio"],
["aereo", "plane"],
["buonanotte", "good night"],
["finalmente", "finally"],
["assolutamente", "absolutely"],
["sam", "sam"],
["ottimo", "great"],
["solito", "usual"],
["avvocato", "lawyer"],
["compagnia", "company"],
["ve", "you"],
["nave", "ship"],
["glielo", "him"],
["gentile", "kind"],
["peccato", "sin"],
["servizio", "service"],
["scena", "scene"],
["incredibile", "unbelievable"],
["michael", "michael"],
["tv", "TV"],
["specie", "species"],
["spesso", "often"],
["dirlo", "tell"],
["david", "david"],
["pensando", "thinking"],
["entrambi", "both"],
["finire", "to end"],
["veloce", "rapid"],
["intorno", "around"],
["addosso", "on"],
["parti", "set off"],
["avrai", "you will have"],
["tante", "many"],
["provato", "tried"],
["poteva", "he could"],
["pagare", "to pay"],
["calma", "calm"],
["conosce", "know"],
["sanno", "know"],
["tizio", "someone"],
["sette", "seven"],
["segreto", "secret"],
["pieno", "full"],
["doveva", "where you go"],
["carino", "cute"],
["dirti", "tell you"],
["arrivederci", "see you later"],
["amica", "friend"],
["quali", "Which"],
["ritardo", "delay"],
["faceva", "it was"],
["vederti", "see you"],
["poter", "can"],
["grosso", "big"],
["giuro", "I swear"],
["esercito", "army"],
["occhiata", "look"],
["freddo", "cold"],
["vestiti", "clothes"],
["avrà", "will"],
["santo", "holy"],
["scusami", "Im sorry"],
["libero", "free"],
["centro", "center"],
["dimenticato", "Forgot"],
["america", "America"],
["lettera", "letter"],
["cavallo", "horse"],
["grado", "degree"],
["cercato", "looked for"],
["chiave", "key"],
["andrà", "will"],
["fallo", "just do it"],
["mare", "sea"],
["fermi", "firm"],
["nello", "in"],
["treno", "train"],
["sinistra", "left"],
["completamente", "completely"],
["saputo", "known"],
["scoperto", "discovered"],
["scusate", "sorry"],
["avevano", "they had"],
["caffè", "coffee"],
["tempi", "times"],
["rumore", "noise"],
["sesso", "sex"],
["silenzio", "silence"],
["uh", "uh"],
["intenzione", "intention"],
["laggiù", "over there"],
["arrivando", "coming"],
["chiedere", "to ask"],
["rapporto", "relationship"],
["sente", "hears"],
["apri", "you open"],
["servono", "serve"],
["ricorda", "remember"],
["trovo", "I find"],
["maestro", "master"],
["terribile", "terrible"],
["fronte", "front"],
["otto", "eight"],
["pubblico", "public"],
["cervello", "brain"],
["interessa", "interest"],
["tranquillo", "quiet"],
["rispetto", "respect"],
["destra", "right"],
["quante", "how much it is"],
["aiutare", "to help"],
["nero", "black"],
["mille", "one thousand"],
["diritto", "right"],
["accidenti", "damn"],
["saremo", "we will be"],
["peggio", "worse"],
["realtà", "reality"],
["consiglio", "Advice"],
["dovevo", "I had to"],
["stanotte", "tonight"],
["diverso", "different"],
["dolore", "ache"],
["pronta", "ready"],
["impossibile", "impossible"],
["anima", "soul"],
["prove", "evidence"],
["omicidio", "murder"],
["alcune", "some"],
["vestito", "dress"],
["risposta", "reply"],
["siediti", "sit down"],
["cambiato", "changed"],
["ferma", "stop"],
["governo", "government"],
["aspettando", "waiting for"],
["linea", "line"],
["normale", "normal"],
["tenente", "lieutenant"],
["ragae", "ragae"],
["sorpresa", "surprise"],
["colonnello", "colonel"],
["dí", "of"],
["vengono", "are"],
["porti", "ports"],
["farci", "make us"],
["partita", "game"],
["guardia", "guard"],
["chiuso", "closed"],
["direi", "Id say"],
["soli", "just"],
["sapeva", "He knew"],
["fin", "from"],
["manca", "it lacks"],
["cavolo", "cabbage"],
["base", "basis"],
["diceva", "he said"],
["harry", "harry"],
["san", "St."],
["vale", "worth"],
["duro", "hard"],
["chiamata", "call"],
["george", "george"],
["ordini", "orders"],
["tenere", "to keep"],
["presa", "socket"],
["charlie", "charlie"],
["mike", "mike"],
["riguardo", "about"],
["luogo", "place"],
["paul", "paul"],
["personale", "staff"],
["incontro", "meeting"],
["volevi", "you wanted"],
["vinto", "won"],
["conosciuto", "known"],
["dagli", "by"],
["interessante", "Interesting"],
["sergente", "sergeant"],
["sparato", "shot"],
["oro", "gold"],
["dl", "dl"],
["dà", "from"],
["avevamo", "we had"],
["sembrava", "It seemed"],
["altrimenti", "otherwise"],
["aspettate", "expect"],
["posizione", "position"],
["caldo", "hot"],
["nonno", "not no"],
["potevo", "I could"],
["immagino", "I imagine"],
["migliori", "best"],
["inferno", "hell"],
["nonna", "grandmother"],
["dolce", "sweet"],
["vive", "lives"],
["notizie", "news"],
["luna", "moon"],
["miss", "miss"],
["semplicemente", "simply"],
["medico", "doctor"],
["esiste", "exists"],
["esempio", "example"],
["zona", "area"],
["proposito", "purpose"],
["uniti", "united"],
["pezzi", "pieces"],
["trovi", "find"],
["inglese", "English"],
["parlo", "I speak"],
["errore", "mistake"],
["maggiore", "greater"],
["continuare", "to continue"],
["scappare", "to run away"],
["seconda", "second"],
["oddio", "oh God"],
["eccolo", "there he is"],
["gesù", "Jesus"],
["attraverso", "through"],
["programma", "program"],
["perciò", "therefore"],
["riesci", "are able"],
["net", "net"],
["chiudi", "close"],
["gamba", "leg"],
["vostre", "your"],
["saresti", "would you be"],
["passi", "steps"],
["verrà", "it will come"],
["salute", "health"],
["birra", "beer"],
["comandante", "commander"],
["assassino", "murderess"],
["simile", "similar"],
["possibilità", "possibility"],
["rimasto", "remained"],
["caccia", "hunting"],
["poliziotto", "policeman"],
["questione", "question"],
["carta", "paper"],
["lavora", "working"],
["controllare", "to check"],
["spettacolo", "show"],
["naturalmente", "of course"],
["scrivere", "to write"],
["jimmy", "jimmy"],
["contento", "happy"],
["volo", "flight"],
["promesso", "promised"],
["stessi", "themselves"],
["passa", "passes"],
["insomma", "in conclusion"],
["chiesa", "church"],
["partire", "start"],
["oppure", "or"],
["carne", "meat"],
["pranzo", "lunch"],
["studio", "study"],
["entro", "within"],
["appuntamento", "appointment"],
["sembri", "you look"],
["pena", "punishment"],
["bianco", "White"],
["secondi", "seconds"],
["missione", "mission"],
["usa", "USA"],
["dia", "dia"],
["arrivati", "arrived"],
["fermati", "stopped"],
["calmati", "take it easy"],
["forma", "form"],
["giusta", "right"],
["compleanno", "birthday"],
["rimanere", "stay"],
["palle", "balls"],
["barca", "boat"],
["affare", "deal"],
["ie", "ie"],
["de", "de"],
["esserci", "occur"],
["peter", "peter"],
["max", "max"],
["coi", "with"],
["nord", "north"],
["leggere", "to read"],
["uscita", "Exit"],
["cioè", "that is"],
["ascoltami", "listen to me"],
["braccio", "arm"],
["informazioni", "information"],
["certamente", "of course"],
["direttore", "director"],
["canzone", "song"],
["maledizione", "curse"],
["scarpe", "shoes"],
["colpito", "hit it"],
["schifo", "disgust"],
["pericolo", "danger"],
["andati", "gone"],
["mica", "not"],
["necessario", "necessary"],
["umano", "human"],
["bellissima", "gorgeous"],
["rosso", "red"],
["soldato", "soldier"],
["don", "Don"],
["fossero", "they were"],
["dite", "of you"],
["corso", "course"],
["regalo", "gift"],
["rubato", "stolen"],
["carina", "nice"],
["dunque", "therefore"],
["bar", "bar"],
["figliolo", "son"],
["classe", "class"],
["stronzate", "bullshit"],
["brutta", "ugly"],
["scherzando", "joking"],
["lunga", "long"],
["benvenuto", "welcome"],
["banca", "bank"],
["negozio", "shop"],
["sogni", "dreams"],
["sud", "south"],
["spalle", "shoulders"],
["mostro", "monster"],
["pochi", "few"],
["intendo", "I mean"],
["dura", "tough"],
["triste", "sad"],
["buonasera", "good evening"],
["attacco", "attack"],
["bob", "bobsleigh"],
["james", "james"],
["tocca", "touching"],
["muoviti", "move"],
["dirò", "I will say"],
["potrebbero", "they might"],
["affatto", "at all"],
["sala", "room"],
["lavori", "works"],
["piena", "full"],
["vedrai", "you will see"],
["sappia", "know"],
["comprare", "to buy"],
["qualcun", "someone"],
["belle", "beautiful"],
["metri", "meters"],
["scelto", "chosen"],
["professore", "teacher"],
["sbrigati", "hurry up"],
["jim", "jim"],
["adoro", "I adore"],
["aiuti", "aid"],
["parigi", "Paris"],
["vivi", "alive"],
["comando", "command"],
["pericoloso", "dangerous"],
["dannazione", "damnation"],
["scommetto", "I bet"],
["occasione", "opportunity"],
["mary", "mary"],
["metà", "half"],
["spazio", "space"],
["regole", "rules"],
["contatto", "contact"],
["spirito", "spirit"],
["povero", "poor"],
["senta", "hear"],
["appartamento", "flat"],
["gambe", "legs"],
["parliamo", "let's talk"],
["pelle", "skin"],
["riuscito", "succeeded"],
["cucina", "kitchen"],
["bomba", "bomb"],
["combattere", "fight"],
["pomeriggio", "afternoon"],
["pianeta", "planet"],
["diventato", "become"],
["avremo", "we ll have"],
["ehm", "hum"],
["viva", "Viva"],
["stavi", "you were"],
["conoscere", "know"],
["mangia", "it eats"],
["visita", "visit"],
["soldati", "soldiers"],
["cattivo", "bad"],
["aiutami", "help me"],
["prometto", "I promise"],
["sposato", "married"],
["ovunque", "everywhere"],
["ama", "loves"],
["stupida", "stupid"],
["bill", "bill"],
["rotto", "Broken"],
["tale", "such"],
["fiume", "river"],
["fratelli", "brothers"],
["nemico", "enemy"],
["ovviamente", "obviously"],
["arma", "weapon"],
["lingua", "tongue"],
["borsa", "bag"],
["uscito", "released"],
["vino", "wine"],
["libri", "books"],
["destino", "destiny"],
["sicuramente", "certainly"],
["maria", "Mary"],
["piangere", "to cry"],
["dovrai", "you"],
["reale", "real"],
["palla", "ball"],
["preoccupare", "worry"],
["ballo", "dance"],
["venuti", "came"],
["iniziato", "started"],
["arrivata", "arrived"],
["usato", "used"],
["sentite", "feeling"],
["urla", "yell out"],
["cerco", "I look for"],
["nato", "born"],
["alzati", "get up"],
["aperto", "open"],
["ritorno", "return"],
["nove", "nine"],
["molta", "much"],
["salvare", "to save"],
["salvato", "saved"],
["capisce", "understands"],
["ê", "is"],
["principe", "prince"],
["lista", "list"],
["intero", "full"],
["avremmo", "we would"],
["popolo", "people"],
["passaggio", "passage"],
["finestra", "window"],
["alex", "alex"],
["ricerca", "Research"],
["differenza", "difference"],
["saltare", "jump"],
["torni", "return"],
["tavolo", "table"],
["quegli", "those"],
["ridere", "to laugh"],
["codice", "code"],
["notizia", "news"],
["avrebbero", "would"],
["vento", "wind"],
["libera", "free"],
["speranza", "hope"],
["pagato", "paid"],
["diciamo", "let's say"],
["posti", "seats"],
["ufficiale", "official"],
["frega", "cares"],
["costa", "it costs"],
["sparare", "shoot"],
["animali", "animals"],
["buone", "good"],
["farebbe", "would do"],
["libertà", "freedom"],
["farsi", "get"],
["incontrato", "met"],
["pesce", "fish"],
["serata", "evening"],
["certa", "certain"],
["all", "all"],
["società", "society"],
["francese", "French"],
["temo", "I fear"],
["livello", "level"],
["stazione", "railway station"],
["americano", "American"],
["computer", "computer"],
["droga", "drug"],
["digli", "say to Him"],
["prenda", "take"],
["detective", "detective"],
["lato", "side"],
["lasciate", "leave"],
["ami", "do you love"],
["vecchi", "old people"],
["guardando", "watching"],
["hotel", "hotel"],
["ultimi", "last"],
["sceriffo", "sheriff"],
["lascio", "leave"],
["americani", "American"],
["sezione", "section"],
["imparato", "learned"],
["you", "you"],
["regina", "Queen"],
["tommy", "tommy"],
["ballare", "to dance"],
["bellissimo", "very beautifull"],
["cominciare", "begin"],
["vederlo", "see him"],
["averlo", "have it"],
["esci", "go out"],
["scorsa", "last"],
["tony", "tony"],
["riguarda", "it concerns"],
["star", "star"],
["naso", "nose"],
["bobby", "bobby"],
["padrone", "master"],
["andremo", "we will go"],
["danny", "danny"],
["alta", "high"],
["comprato", "bought"],
["vorrebbe", "he would"],
["metto", "I put"],
["seguito", "following"],
["aprire", "to open"],
["correre", "to run"],
["farei", "I would do"],
["dovrebbero", "they should"],
["alcun", "any"],
["fiori", "flowers"],
["inutile", "useless"],
["danno", "damage"],
["stesse", "same"],
["corri", "run"],
["sí", "Yes"],
["casino", "casino"],
["imparare", "learn"],
["torniamo", "we return"],
["natura", "nature"],
["lavorato", "worked"],
["cliente", "customer"],
["rende", "makes"],
["londra", "London"],
["riesce", "succeeds"],
["immediatamente", "immediately"],
["giovani", "Young people"],
["guida", "guide"],
["biglietto", "ticket"],
["stavamo", "we were"],
["zia", "aunt"],
["razza", "race"],
["cani", "dogs"],
["stamattina", "This morning"],
["intelligente", "intelligent"],
["blu", "blue"],
["effetti", "effects"],
["cominciato", "started"],
["avrò", "I will"],
["cambio", "exchange"],
["chiavi", "keys"],
["intera", "whole"],
["taxi", "Taxi"],
["gay", "gay"],
["fortunato", "lucky"],
["corsa", "race"],
["jake", "jake"],
["giudice", "judge"],
["accanto", "next"],
["villaggio", "village"],
["cinema", "cinema"],
["stanco", "tired out"],
["lezione", "lesson"],
["decisione", "decision"],
["bianca", "white"],
["eddie", "eddie"],
["bordo", "board"],
["ray", "ray"],
["segno", "sign"],
["ponte", "bridge"],
["club", "club"],
["nuovi", "new"],
["umani", "human"],
["muro", "wall"],
["interno", "internal"],
["energia", "power"],
["aiutarti", "help you"],
["sapevi", "Did you know"],
["darmi", "me"],
["trovata", "stunt"],
["seduto", "sitting"],
["spada", "sword"],
["andrò", "I will go"],
["presente", "here I am"],
["guardami", "watch me"],
["processo", "process"],
["scoprire", "to discover"],
["faranno", "will"],
["piccoli", "little ones"],
["segnale", "signal"],
["ferito", "injured"],
["farla", "it"],
["battaglia", "battle"],
["meraviglioso", "wonderful"],
["scherzo", "joke"],
["it", "it"],
["cavalli", "horses"],
["paga", "pay"],
["ride", "laughs"],
["porca", "ridge"],
["chiedi", "ask"],
["mangiato", "eat"],
["ascolti", "you listen"],
["ringrazio", "I thank"],
["comincia", "it starts"],
["mette", "puts"],
["prezzo", "price"],
["grave", "serious"],
["dovevi", "you had to"],
["tanta", "so much"],
["billy", "billy"],
["infatti", "indeed"],
["strana", "strange"],
["eroe", "hero"],
["and", "and"],
["suono", "sound"],
["iniziare", "to start"],
["fece", "he made"],
["documenti", "documents"],
["collo", "neck"],
["comune", "common"],
["denti", "teeth"],
["sarebbero", "would"],
["vincere", "to win"],
["lavorando", "working"],
["vedete", "you see"],
["pensate", "think"],
["intendi", "you mean"],
["los", "los"],
["storie", "stories"],
["memoria", "memory"],
["data", "date"],
["terzo", "third"],
["buoni", "good"],
["aiutarmi", "help"],
["massimo", "maximum"],
["miglior", "best"],
["buio", "dark"],
["colore", "color"],
["matto", "crazy"],
["prendete", "take"],
["vederla", "see her"],
["carte", "cards"],
["suona", "it sounds"],
["rispondere", "reply"],
["cerchi", "circles"],
["cellulare", "cell phone"],
["soprattutto", "mostly"],
["sarah", "sarah"],
["italianshare", "italianshare"],
["diventa", "becomes"],
["difesa", "defence"],
["corte", "court"],
["suppongo", "I presume"],
["maledetto", "cursed"],
["potrà", "will"],
["opera", "Opera"],
["partito", "party"],
["attenti", "careful"],
["pazza", "crazy"],
["persino", "even"],
["scendere", "alight"],
["fede", "wedding ring"],
["esperienza", "experience"],
["vorresti", "would you"],
["parlarti", "talk to you"],
["gliel", "vaccum"],
["bacio", "kiss"],
["farcela", "do it"],
["responsabile", "responsible"],
["enorme", "huge"],
["chiamano", "they call"],
["messa", "mass"],
["ex", "former"],
["fiducia", "confidence"],
["ognuno", "each one"],
["periodo", "period"],
["dovere", "duty"],
["albero", "tree"],
["verde", "green"],
["steve", "steve"],
["smettere", "stop"],
["darti", "give you"],
["azione", "action"],
["odore", "smell"],
["rispondi", "Reply"],
["locale", "local"],
["latte", "milk"],
["bellezza", "beauty"],
["vittima", "victim"],
["vicini", "neighbors"],
["cae", "cae"],
["visti", "visas"],
["entrato", "entered"],
["congratulazioni", "congratulations"],
["felici", "happy"],
["nell", "in"],
["prendiamo", "we take"],
["tira", "pulls"],
["nomi", "names"],
["nick", "nick"],
["colazione", "Breakfast"],
["íl", "the"],
["tornata", "returned"],
["ottima", "Great"],
["idee", "ideas"],
["isola", "island"],
["fila", "row"],
["farle", "them"],
["contrario", "contrary"],
["sveglia", "Wake Up"],
["lee", "lee"],
["maggior", "greatest"],
["leggi", "read"],
["chissà", "who knows"],
["sembrano", "they seem"],
["roma", "Rome"],
["dubbio", "doubt"],
["camion", "truck"],
["braccia", "arms"],
["sissignore", "yes sir"],
["lasciatemi", "let me"],
["stella", "star"],
["malato", "sick"],
["nascosto", "hidden away"],
["citta", "city"],
["rischio", "risk"],
["averti", "have you"],
["pressione", "pressure"],
["orribile", "horrible"],
["edificio", "building"],
["progetto", "project"],
["portata", "flow"],
["età", "age"],
["diversi", "different"],
["parlarne", "talk about"],
["sara", "Sara"],
["camminare", "to walk"],
["lascialo", "leave him"],
["capace", "to be able"],
["dott", "Dr."],
["piede", "foot"],
["calmo", "calm"],
["chiusa", "closed"],
["principessa", "princess"],
["dimenticare", "forget"],
["zitta", "shut up"],
["attenta", "careful"],
["potrai", "you"],
["sali", "salts"],
["scopo", "purpose"],
["dipende", "It depends"],
["grida", "shout"],
["sii", "Yay"],
["show", "show"],
["abbiano", "have"],
["vorrà", "will want"],
["andava", "He was"],
["piaciuto", "liked"],
["stampa", "press"],
["viso", "face"],
["ottenere", "obtain"],
["segreti", "secrets"],
["stelle", "stars"],
["rosa", "pink"],
["nuove", "new"],
["salire", "to go up"],
["pensiero", "thought"],
["dappertutto", "everywhere"],
["ristorante", "restaurant"],
["potesse", "could"],
["conta", "counts"],
["giornale", "newspaper"],
["serie", "series"],
["test", "test"],
["luci", "lights"],
["chiudere", "to close"],
["gatto", "cat"],
["aiutarla", "help"],
["giustizia", "justice"],
["tranne", "except"],
["albergo", "hotel"],
["ascoltare", "to listen"],
["tiro", "shot"],
["relazione", "report"],
["basso", "bass"],
["resti", "remains"],
["compagno", "partner"],
["stavolta", "this time"],
["crimine", "crime"],
["tengo", "tengo"],
["angolo", "angle"],
["dovremo", "we will"],
["cappello", "hat"],
["operazione", "operation"],
["fore", "fore"],
["chiamate", "calls"],
["estate", "summer"],
["desiderio", "desire"],
["mercato", "market"],
["preoccupi", "worry"],
["incinta", "pregnant"],
["rilassati", "take it easy"],
["clienti", "customers"],
["sposa", "bride"],
["arte", "art"],
["coltello", "knife"],
["strade", "roads"],
["continui", "continues"],
["mossa", "move"],
["macchine", "cars"],
["preferisco", "I prefer"],
["rose", "rose"],
["vite", "lives"],
["certe", "certain"],
["son", "son"],
["toccare", "to touch"],
["milione", "million"],
["buco", "hole"],
["centrale", "central"],
["lassù", "up there"],
["tranquilla", "Quiet"],
["carriera", "career"],
["anello", "ring"],
["uso", "use"],
["stile", "style"],
["metta", "put"],
["contratto", "contract"],
["compito", "task"],
["faresti", "would you do"],
["paradiso", "paradise"],
["provi", "try"],
["forze", "Strength"],
["indirizzo", "address"],
["domattina", "tomorrow morning"],
["anzi", "rather"],
["poliziotti", "policemen"],
["finta", "fake"],
["riunione", "meeting"],
["effetto", "effect"],
["punti", "points"],
["torta", "cake"],
["scorso", "last"],
["troia", "slut"],
["animale", "animal"],
["qualcos", "qualcos"],
["to", "to"],
["faccenda", "affair"],
["darò", "I will give"],
["lettere", "letters"],
["chiede", "asks"],
["notato", "noted"],
["particolare", "particular"],
["inoltre", "Moreover"],
["offerta", "offer"],
["prendermi", "take"],
["campione", "sample"],
["fermare", "stop"],
["aperta", "open"],
["agenti", "agents"],
["sembrare", "to seem"],
["politica", "policy"],
["colpevole", "guilty"],
["scegliere", "to choose"],
["rimane", "remains"],
["vedremo", "we ll see"],
["ghiaccio", "ice"],
["washington", "Washington"],
["dovrà", "will"],
["finisce", "ends"],
["fucile", "rifle"],
["colpi", "shots"],
["utile", "helpful"],
["averla", "have it"],
["voci", "voices"],
["perfetta", "perfect"],
["ispettore", "inspector"],
["autobus", "bus"],
["dati", "data"],
["ridicolo", "ridiculous"],
["will", "will"],
["potessi", "I could"],
["altezza", "height"],
["guidare", "to drive"],
["primi", "first"],
["decidere", "to decide"],
["sottofondo", "background"],
["volare", "to fly"],
["valore", "value"],
["campagna", "countryside"],
["tè", "you"],
["tornate", "return"],
["vendere", "to sell"],
["muore", "dies"],
["charles", "charles"],
["bevi", "Frequency"],
["eccola", "here she is"],
["cadere", "fall"],
["scatola", "box"],
["peso", "weight"],
["magnifico", "magnificent"],
["ragazzino", "little boy"],
["prendendo", "taking"],
["ubriaco", "drunk"],
["mentito", "lied"],
["santa", "holy"],
["egli", "he"],
["tenga", "takes"],
["martin", "martin"],
["sensazione", "sensation"],
["principale", "main"],
["saremmo", "we would"],
["schiena", "back"],
["caduto", "fallen"],
["girare", "turn"],
["contenta", "happy"],
["piaceva", "He liked"],
["orologio", "clock"],
["insegnato", "taught"],
["sbaglio", "mistake"],
["entri", "enter"],
["porte", "doors"],
["cioe", "ie"],
["maestà", "majesty"],
["arrivano", "they arrive"],
["conti", "accounts"],
["cantare", "to sing"],
["bevuto", "drunk"],
["angelo", "angel"],
["sparo", "shot"],
["creato", "created"],
["dimmelo", "tell me"],
["naturale", "natural"],
["importanza", "importance"],
["baby", "baby"],
["case", "houses"],
["manda", "sends"],
["fumo", "smoke"],
["domenica", "Sunday"],
["uccisa", "killed"],
["umana", "Human"],
["verita", "truth"],
["cento", "one hundred"],
["rotta", "route"],
["nipote", "grandson"],
["date", "at your place"],
["teatro", "theater"],
["militare", "military"],
["povera", "poor"],
["andartene", "leave"],
["pensano", "they think"],
["muoversi", "move"],
["palazzo", "palace"],
["convinto", "convinced"],
["ascoltate", "listen"],
["innocente", "innocent"],
["finale", "the final"],
["purtroppo", "Unfortunately"],
["giochi", "games"],
["innamorato", "in love"],
["gira", "runs"],
["breve", "short"],
["dall", "from"],
["crederci", "believe it"],
["turno", "round"],
["stavano", "they were"],
["uccidermi", "kill myself"],
["emergenza", "emergency"],
["benvenuti", "welcome"],
["improvviso", "sudden"],
["andarci", "go there"],
["tetto", "roof"],
["montagna", "mountain"],
["dirle", "tell"],
["diverse", "different"],
["tiene", "keeps"],
["dovrò", "I will have to"],
["bottiglia", "bottle"],
["andrai", "you will go"],
["chiedendo", "asking"],
["nera", "Black"],
["pane", "bread"],
["muovetevi", "move"],
["preoccupato", "worried"],
["venne", "it was"],
["ricco", "rich"],
["stanca", "weary"],
["richard", "richard"],
["mark", "mark"],
["chiamami", "Call me"],
["discorso", "speech"],
["mandare", "send"],
["evitare", "to avoid"],
["accettare", "to accept"],
["immagini", "images"],
["giornali", "newspapers"],
["sir", "sir"],
["ministro", "minister"],
["momenti", "moments"],
["simon", "simon"],
["mantenere", "to maintain"],
["giardino", "garden"],
["lotta", "fight"],
["distrutto", "destroyed"],
["pò", "bit"],
["antonio", "antonio"],
["retro", "back"],
["cerchiamo", "try"],
["bicchiere", "glass"],
["pantaloni", "trousers"],
["siate", "you are"],
["tribunale", "court"],
["lasciamo", "we leave"],
["gioia", "joy"],
["bastardi", "bastards"],
["paziente", "patient"],
["dr", "dr"],
["controlla", "check it out"],
["arrabbiato", "angry"],
["avermi", "me"],
["genio", "genius"],
["saprei", "know"],
["giu", "down"],
["debole", "weak"],
["piani", "plans"],
["coppia", "couple"],
["arresto", "arrest"],
["scusatemi", "excuse me"],
["mettiti", "put yourself"],
["allarme", "alarm"],
["sarete", "you will be"],
["seguire", "follow"],
["est", "East"],
["ricordare", "to remember"],
["incontrare", "meet"],
["talento", "talent"],
["vissuto", "lived"],
["furono", "they were"],
["condizioni", "conditions"],
["cattiva", "bad"],
["cinese", "Chinese"],
["aiutato", "helped"],
["malattia", "disease"],
["suonare", "play"],
["tipi", "types"],
["dito", "finger"],
["laboratorio", "laboratory"],
["preferito", "favorite"],
["nemici", "enemies"],
["vittoria", "victory"],
["potevi", "you could"],
["dritto", "straight ahead"],
["ferita", "wound"],
["svegliati", "wake up"],
["unità", "unit"],
["francia", "France"],
["diamo", "let's"],
["grossa", "gross"],
["creare", "create"],
["direzione", "direction"],
["propria", "own"],
["sposata", "married"],
["migliaia", "thousand"],
["mal", "ache"],
["rimani", "stay"],
["occupato", "busy"],
["sabato", "Saturday"],
["mattino", "morning"],
["morendo", "dying"],
["canta", "sings"],
["provo", "I try"],
["sentimenti", "feelings"],
["sene", "sene"],
["bei", "beautiful"],
["vuoto", "empty"],
["spiaggia", "beach"],
["testimone", "witness"],
["dita", "fingers"],
["esce", "goes out"],
["jerry", "jerry"],
["isubs", "isubs"],
["cambia", "change"],
["troviamo", "we find"],
["gas", "gas"],
["dipartimento", "department"],
["chris", "chris"],
["amor", "sake"],
["thomas", "thomas"],
["lucy", "lucy"],
["miglia", "miles"],
["smesso", "stopped"],
["facevo", "I did"],
["sedia", "chair"],
["corrente", "current"],
["cadavere", "dead body"],
["andarmene", "leave"],
["victor", "victor"],
["importanti", "important"],
["jane", "jane"],
["obiettivo", "target"],
["fianco", "side"],
["entrate", "revenue"],
["conosciamo", "we know"],
["fantastica", "fantastic"],
["furgone", "van"],
["amato", "beloved"],
["iscrew", "iscrew"],
["motore", "engine"],
["inizia", "it begins"],
["presento", "present"],
["ladro", "thief"],
["soluzione", "solution"],
["matt", "matt"],
["sguardo", "look"],
["parlano", "they talk"],
["fantasma", "ghost"],
["sposare", "to marry"],
["spiegare", "explain"],
["pensarci", "think about it"],
["immagine", "image"],
["entrata", "entry"],
["pioggia", "rain"],
["eppure", "but yet"],
["immaginare", "to imagine"],
["potente", "powerful"],
["rock", "rock"],
["sé", "self"],
["vittime", "victims"],
["famoso", "famous"],
["uccello", "bird"],
["scendi", "get off"],
["accaduto", "happened"],
["giacca", "jacket"],


 ['rimanda', 'postpone'],
 ['costellazione', 'constellation'],
 ['pagina', 'page'],
 ['priva', 'private'],
 ['carente', 'lacking'],
 ['riferimenti', 'references'],
 ['puntuali', 'punctual'],
 ['Sebbene', 'While'],
 ['collegamenti', 'connections'],
 ['esterni', 'external'],
 ['fonti', 'sources'],
 ['provenienza', 'provenance'],
 ['migliorare', 'improve'],
 ['siccome', 'since'],
 ['contengono', 'contain'],
 ['Avvolgimenti', 'Windings'],
 ['progetti', 'projects'],
 ['cicloconvertitori', 'cycloconverters'],
 ['chopper', 'chopper'],
 ['avvolgimenti', 'windings'],
 ['flussi', 'flows'],
 ['impiegati', 'employees'],
 ['dannose', 'harmful'],
 ['porre', 'put'],
 ['nucleo', 'nucleus'],
 ['lamierini', 'sheet metal'],
 ['tenuti', 'kept'],
 ['adatto', 'suited'],
 ['ventola', 'fan'],
 ['eccezione', 'exception'],
 ['detti', 'sayings'],
 ['gabbia', 'cage'],
 ['sottoposti', 'subjected'],
 ['alberi', 'trees'],
 ['cuscinetti', 'bearings'],
 ['leghe', 'leagues'],
 ['ossia', 'or'],
 ['ghisa', 'cast iron'],
 ['grigia', 'grey'],
 ['spessore', 'thickness'],
 ['complessa', 'complex'],
 ['spinte', 'pushes'],
 ['impiegati', 'employees'],
 ['acciai', 'steels'],
 ['gabbia', 'cage'],
 ['scambio', 'exchange'],
 ['didattico', 'educational'],
 ['distinzione', 'distinction'],
 ['nascono', 'they are born'],
 ['ulteriori', 'more'],

 ['coinvolgono', 'involve'],
 ['ricorrere', 'resort'],
 ['percorsi', 'routes'],
 ['essendo', 'being'],
 ['sede', 'site'],
 ['impacchettati', 'packed'],
 ['viti', 'screws'],
 ['passanti', 'passers-by'],
 ['muovere', 'move'],
 ['indotti', 'induced'],
 ['i', 'the'],
 ['ovvero', 'that is to say'],

 ['battesimo', 'baptismo'],
 ['festeggiato', 'celebrated'],
 ['quartiere', 'quarter'],
 ['prati', 'meadows'],
 ['acquistata', 'purchased'],
 ['riscatto', 'ransom'],
 ["vent'anni", 'twenty years'],
 ['posa', 'pose'],
 ['poltrona', 'armchair'],
 ['infilato', 'inserted'],
 ['precariamente', 'precariously'],
 ['adelina', 'adelina'],
 ['domestica', 'housekeeper'],
 ['intravede', 'glimpses'],
 ['celesti', 'heavenly'],
 ['sposarsi', 'to get married'],
 ['studiava', 'he studied'],
 ['addormentare', 'fall asleep'],
 ['solite', 'usual'],
 ['ninne', 'lullabies'],
 ['nanne', 'sleeps'],
 ['romanze', 'romances'],
 ['arie', 'arias'],
 ['opere', 'works'],
 ['liriche', 'lyrics'],
 ['millina', 'millina'],
 ['margherita', 'margherita pizza'],
 ['luisa', 'he knows'],
 ['sorelle', 'sisters'],
 ['nobili', 'nobles'],
 ['giordani', 'Jordanians'],
 ['scapolo', 'bachelor'],
 ["all'università", 'at the University'],
 ['rigoroso', 'strict'],
 ['dilettante', 'amateur'],
 ['fiero', 'proud'],
 ['trattore', 'tractor'],
 ['carducci', 'carducci'],
 ['ripetere', 'repeat'],
 ['leone', 'Lion'],
 ['repubblicano', 'Republican'],
 ['barboncino', 'poodle'],
 ['reggina', 'reggina'],
 ['diventerà', 'will become'],
 ['diventerà', 'will become'],
 ['modesta', 'modest'],
 ['attiverà', 'she will activate'],
 ['pancia', 'belly'],
 ['febbre', 'fever'],
 ['elencando', 'listing'],
 ['malanni', 'ailments'],
 ['eccesso', 'excess'],
 ['nicolino', 'nicolino'],
 ['macerata', 'macerated'],
 ["l'occasione", 'the occasion'],
 ['adelina', 'adelina'],
 ['imboccare', 'take'],
 ['cugino', 'cousin'],
 ['enrico', 'Henry'],
 ['festeggiarmi', 'celebrate me'],
 ['michele', 'Michele'],
 ['cia', 'CIA'],
 ['ersilia', 'ersilia'],
 ['cairoli', 'cairoli'],
 ['carlo', 'Carlo'],
 ['germanico', 'Germanic'],
 ['karl', 'karl'],
 ['ricordagli', 'remind him'],
 ['infine', 'In the end'],
 ['funzionario', 'officer'],
 ['ministero', 'ministry'],
 ["dell'istruzione", 'of education'],
 ['pubblica', 'public'],
 ['lancio', 'launch'],
 ['inclinazione', 'inclination'],
 ['artistica', 'artistic'],
 ['dedica', 'dedication'],
 ['pittura', 'painting'],
 ['fanciulla', 'girl'],
 ['frutta', 'fruit'],
 ['giordani', 'Jordanians'],
 ['apprezzare', 'appreciate'],
 ['appunto', 'precisely'],
 ['tolto', 'taken out'],
 ['compiuto', 'accomplished'],
 ['unione', 'Union'],
 ['cugino', 'cousin'],
 ['enrico', 'Henry'],
 ['berretto', 'cap'],
 ['fanteria', 'infantry'],
 ['michele', 'Michele'],
 ['licenza', 'license'],
 ['gravi', 'serious'],
 ['motivi', 'reasons'],
 ['filmato', 'movie'],
 ['mezzi', 'means'],
 ['seduta', 'sitting'],
 ['aristide', 'aristide'],
 ['piumino', 'down filled comforter'],
 ['salto', 'jump'],
 ['gaga', 'gaga'],
 ['hunter', 'hunter'],
 ['ringraziarla', 'thank her'],
 ['vettore', 'vector'],
 ['negazione', 'denial'],
 ['affezionato', 'fond'],
 ['grati', 'grateful'],
 ['scienza', 'science'],
 ['committeri', 'committers'],
 ['piove', 'rains'],
 ['dirotto', 'I digress'],
 ['farvi', 'make you'],
 ['similarly', 'similarly'],
 ['vedervi', 'seeing you'],
 ['trovarci', 'find us'],
 ["senz'altro", 'certainly'],
 ['raccomando', 'I recommend'],
 ["l'esempio", 'the example'],
 ["d'arrivederci", 'goodbye'],
 ['adelina', 'adelina'],
 ['impari', 'you learn'],
 ['cipriani', 'cipriani'],
 ['cipria', 'face powder'],
 ['bertozzini', 'bertozzini'],
 ['figurati', 'Forget about it'],
 ['confessa', 'confess'],
 ['inventi', 'invent'],
 ['cafarella', 'cafarella'],
 ['volessi', 'I wanted'],
 ['genitore', 'parent'],
 ['staccato', 'detached'],
 ['rai', 'rai'],
 ['scaricava', 'downloaded'],
 ['chieti', 'you ask'],
 ['cia', 'CIA'],
 ['ace', 'ace'],
 ["c'è", 'there is'],
 ['zitella', 'spinster'],
 ['basterebbe', 'it would be enough'],
 ['appaia', 'appear'],
 ['giordani', 'Jordanians'],
 ['capannone', 'shed'],
 ['scivolose', 'slippery'],
 ['osano', 'they dare'],
 ['causano', 'they cause'],
 ['ammazzo', "I'll kill"],
 ['fatele', 'do them'],
 ['matter', 'matter'],
 ['giulietto', 'giulietto'],
 ['carletto', 'carletto'],

 ['sbarazzato', 'got rid'],
 ['demonizzato', 'demonized'],
 ['riga', 'line'],
 ['prepotenza', 'arrogance'],
 ['vedermi', 'see me'],
 ['usando', 'using'],
 ['assumo', 'I assume'],
 ['giulio', 'Giulio'],
 ['tavola', 'table'],
 ['ladroni', 'thieves'],
 ['rino', 'rino'],
 ['mettono', 'they put'],
 ['potenti', 'powerful'],
 ['vergognato', 'ashamed'],
 ['amatissimo', 'dearly loved'],
 ["l'altra", 'the other one'],
 ['uscendo', 'going out'],
 ['rischiato', 'risked'],
 ['carabinieri', 'carabinieri'],
 ['chiamati', 'called'],
 ['fattorino', 'delivery man'],
 ['sprovvisto', 'without'],
 ['acquistare', 'acquire'],
 ['derubato', 'robbed'],
 ['lira', 'lira'],
 ['portamonete', 'purse'],
 ['mezzani', 'middlemen'],
 ['mezza', 'half'],
 ['lira', 'lira'],
 ['vergogna', 'shame'],
 ['disonore', 'dishonor'],
 ["anch'io", 'Me too'],
 ['restituiremo', 'we will return'],
 ['mezza', 'half'],
 ['lira', 'lira'],
 ['scuse', 'apologies'],
 ['spesa', 'expense'],
 ['giulio', 'Giulio'],
 ['civile', 'civil'],
 ['rendere', 'give'],
 ['confessione', 'confession'],
 ['scappata', 'escaped'],
 ['merito', 'merit'],
 ['leale', 'fair'],
 ['bugiardo', 'liar'],
 ['sandra', 'sandra'],
 ['cassata', 'dismissed'],
 ['piazza', 'square'],
 ['sagre', 'festivals'],
 ['giuliani', 'giuliani'],
 ['figura', 'figure'],
 ['cina', 'China'],
 ['arrestato', 'arrested'],
 ['carabinieri', 'carabinieri'],
 ['pinocchio', 'Pinocchio'],
 ['vigliacco', 'coward'],
 ['scemo', 'stupid'],
 ['discussione', 'discussion'],
 ['paragoni', 'comparisons'],
 ['ringraziamento', 'thanks'],
 ['tubi', 'tubes'],
 ['tondi', 'round'],
 ['rubati', 'stolen'],
 ['lasciavano', 'they left'],
 ['vivendo', 'living'],
 ['mirino', 'viewfinder'],
 ['capi', 'leaders'],
 ['saliti', 'gone up'],
 ['cottini', 'cooked'],
 ['invecchiano', 'they grow old'],
 ['ingressi', 'entrances'],
 ['creda', 'believe it'],
 ['merito', 'merit'],
 ['linee', 'lines'],
 ['zafferano', 'saffron'],
 ['guidano', 'they drive'],
 ["l'ippodromo", "the racecourse"],
 ['assai', 'a lot'],
 ['rado', 'rarely'],
 ['qualità', 'quality'],
 ['tenuto', 'held'],
 ['rispettare', 'respect'],
 ['orario', 'hours'],
 ['fisso', 'fixed'],
 ['pomeriggi', 'afternoons'],
 ['dipingere', 'PAINT'],
 ['ritratto', 'portrait'],
 ['intanto', 'meanwhile'],
 ['scrive', 'writes'],
 ['lunghe', 'long'],
 ["un'incognita", 'an unknown'],
 ['punta', 'tip'],
 ['finirò', "I'll finish"],
 ["l'università", 'the University'],
 ['ripetizione', 'repetition'],
 ['santis', 'santis'],
 ['stabilire', 'to establish'],
 ['nesso', 'link'],
 ['letteratura', 'literature'],
 ['civile', 'civil'],
 ['stabilire', 'to establish'],
 ['stabilito', 'established'],
 ['spiegato', 'explained'],
 ['filosofia', 'philosophy'],
 ['pervenne', 'arrived'],
 ['concetto', 'concept'],
 ['dialetti', 'dialects'],
 ["dell'arte", 'of art'],
 ["l'uomo", 'the man'],
 ['tabanelli', 'tabanelli'],
 ["dell'arte", 'of art'],
 ['nazione', 'nation'],
 ['tabanelli', 'tabanelli'],
 ['stabilire', 'to establish'],
 ['stabilisce', 'establishes'],
 ['nesso', 'link'],
 ['letteratura', 'literature'],
 ['civile', 'civil'],
 ['baffi', 'moustache'],
 ['rica', 'rica'],
 ['professoressa', 'professor'],
 ['insegnare', 'teach'],
 ['vorrebbero', 'they would like'],
 ['troviate', 'you find'],
 ['cioccolato', 'chocolate'],
 ["l'aggredisce", 'he attacks her'],
 ['zabaione', 'eggnog'],
 ['biscotti', 'cookies'],
 ['gentilini', 'gentlemen'],
 ['tech', 'tech'],
 ['tubercolosi', 'tuberculosis'],
 ['nutrizione', 'nutrition'],
 ['pneumatorace', 'pneumathorax'],
 ['guarito', 'healed'],
 ['perfettamente', 'perfectly'],
 ['scemo', 'stupid'],
 ['biondina', 'blonde'],
 ['clavata', 'clubbed'],
 ['piazza', 'square'],
 ['bra', 'bra'],
 ['ciglio', 'eyelash'],
 ['amatrice', 'amateur'],
 ['ricoverare', 'hospitalize'],
 ['mingazzini', 'mingazzini'],
 ['croccante', 'Crisp'],
 ['liquori', 'liquors'],
 ['pensiamo', 'we think'],
 ['colleghi', 'colleagues'],
 ['camerieri', 'waiters'],
 ['camerino', 'changing room'],
 ['fascisti', 'fascists'],
 ['mestiere', 'craft'],
 ['scopriamo', "let's find out"],
 ['filosofi', 'philosophers'],
 ['isolato', 'isolated'],
 ['bacino', 'pelvis'],
 ['sottomette', 'submits'],
 ['volontà', 'will'],
 ['moltitudine', 'multitude'],
 ['detta', 'said'],
 ['generazione', 'generation'],
 ['leviatano', 'Leviathan'],
 ['rannicchiati', 'curl up'],
 ['zampe', 'legs'],
 ['speriamo', 'We hope'],
 ['muoia', 'die'],
 ['muoia', 'die'],
 ['giulio', 'Giulio'],
 ['agree', 'agree'],
 ['fumare', 'to smoke'],
 ['vitt', 'vict'],
 ['compagni', 'companions'],
 ['corti', 'short'],
 ['corta', 'short'],
 ['corto', 'short'],
 ['danze', 'dances'],
 ['aspettiamo', "let's wait"],
 ['regge', 'holds'],
 ['adriana', 'adriana'],
 ['beatrice', 'beatrice'],
 ['fed', 'fed'],
 ['lele', 'lele'],
 ['sedersi', 'Sit'],
 ['volentieri', "I'd love that"],
 ["l'ho", 'I have it'],
 ['beatrice', 'beatrice'],
 ['progressi', 'progress'],
 ['copiato', 'copied'],
 ['insegnarle', 'teach her'],
 ['osservazione', 'observation'],
 ['appropriazione', 'appropriation'],
 ['osservarti', 'observe you'],
 ['inventare', 'to invent'],
 ['gioachino', 'Gioachino'],
 ['rossini', 'Rossini'],
 ['stupito', 'amazed'],
 ['musicista', 'musician'],
 ['occupi', 'occupy'],
 ['musicista', 'musician'],
 ['decimarli', 'decimate them'],
 ['merenda', 'snack'],
 ['noioso', 'boring'],
 ['spiritoso', 'humorous'],
 ['calunnia', 'slander'],
 ['innamorata', 'in love'],
 ['ragazzina', 'little girl'],
 ['scemi', 'idiots'],
 ['tool', 'tools'],
 ['permette', 'allows'],
 ['giulio', 'Giulio'],
 ['sciacquette', 'rinse'],
 ['battista', 'Baptist'],
 ['chiamiamo', "let's call"],
 ["l'attività", 'the activity'],
 ['balla', 'dance'],
 ['costruito', 'built'],
 ['personaggio', 'character'],
 ['news', 'news'],
 ['superiore', 'superior'],
 ['vali', 'you are worth it'],
 ['applichi', 'apply'],
 ['turi', 'turi'],
 ['ripetizioni', 'repetitions'],
 ['definizione', 'definition'],
 ['fatte', 'done'],
 ['fascia', 'band'],
 ['bari', 'cheaters'],
 ['spazi', 'spaces'],
 ['spazi', 'spaces'],
 ['scatta', 'snap'],
 ['amava', 'he loved'],
 ["l'avete", 'you have it'],
 ['christie', 'christie'],
 ['christie', 'christie'],
 ['buchi', 'holes'],
 ['dimetta', 'resign'],
 ['mammadova', 'mammadova'],
 ['scherza', 'he jokes'],
 ['patate', 'potatoes'],
 ['spegnete', 'turn off'],
 ['tormenti', 'torments'],
 ["anch'io", 'Me too'],
 ['lunghe', 'long'],
 ['adriana', 'adriana'],
 ['corro', 'I run'],
 ['scrivo', 'I write'],
 ['ceti', 'classes'],
 ['soffrirebbe', 'would suffer'],
 ['adriana', 'adriana'],
 ['domando', 'I ask'],

 ['tenendo', 'holding'],
 ['liti', 'quarrels'],
 ['incomprensioni', 'misunderstandings'],
 ['colpe', 'faults'],
 ['geloso', 'jealous'],
 ['egoista', 'selfish'],
 ['troppa', 'too much'],
 ['pazienza', 'patience'],
 ['pietro', 'Peter'],
 ['incompiuto', 'unfinished'],
 ['disciplinata', 'disciplined'],
 ['modella', 'model'],
 ['finirlo', 'finish it'],
 ['accomodi', 'take a seat'],
 ['compiangere', 'to mourn'],
 ['togli', 'remove'],
 ['erba', 'grass'],
 ['bagnata', 'wet'],
 ['innamorarsi', 'to fall in love'],
 ["l'amore", 'the love'],
 ['assistere', 'assist'],
 ['studiare', 'study'],
 ['perfezionamento', 'improvement'],
 ['margarito', 'margarito'],
 ['lametina', 'lametina'],
 ['milan', 'milan'],
 ["l'odio", 'hatred'],
 ['roster', 'roster'],
 ['ammessi', 'allowed'],
 ['aiutarlo', 'help him'],
 ['marguerite', 'marguerite'],
 ['impedisce', 'prevents'],
 ["l'alto", 'the top'],
 ['separarci', 'separate us'],
 ['accompagna', 'accompanies'],
 ['semi', 'seeds'],
 ['perde', 'lose'],
 ['gridare', 'scream'],
 ['perdente', 'loser'],
 ['diretta', 'direct'],
 ['leonardo', 'leonardo'],
 ['mettiamo', 'we put'],
 ['rientro', 'come back in'],
 ['saltate', 'jump'],
 ['mappe', 'maps'],
 ['cammino', 'I walk'],
 ['castagna', 'chestnut'],
 ['paolino', 'Pauline'],
 ['maddalena', 'magdalena'],
 ['insegno', 'I teach'],
 ['latino', 'Latin'],
 ['liceo', 'Lyceum'],
 ['umberto', 'umberto'],
 ['berlina', 'sedan'],
 ['cammino', 'I walk'],
 ['assegni', 'checks'],
 ["dall'automobile", 'from the car'],
 ['solarelli', 'solarilli'],
 ['pulito', 'clean'],
 ['bui', 'dark'],
 ['somarelli', 'donkeys'],
 ['divertire', 'amuse'],
 ['pochino', 'a little'],
 ['studiare', 'study'],
 ['filologia', 'philology'],
 ['romanza', 'romance'],
 ['feriti', 'wounded'],
 ['caringi', 'caring'],
 ['ascolto', 'I listen'],
 ['periti', 'experts'],
 ["l'abbiamo", 'we have it'],
 ['chiude', 'closes'],
 ["l'esame", 'the exam'],
 ['bre', 'bre'],
 ['ottobre', 'October'],
 ['febbraio', 'February'],
 ['concerto', 'concert'],
 ['trasmettono', 'they transmit'],
 ['sechi', 'dry'],
 ['errico', 'errico'],
 ['clotilde', 'clothilde'],
 ['filo', 'row'],
 ['vabbè', 'alright'],
 ['geografia', 'geography'],
 ['tipografia', 'typography'],
 ['presentato', 'introduced'],
 ['italiani', 'Italians'],
 ['rifugiati', 'refugees'],
 ['politici', 'politicians'],
 ['anina', 'anina'],
 ['segna', 'scores'],
 ['boulevard', 'boulevard'],
 ['sony', 'sony'],
 ['boulevard', 'boulevard'],
 ['meravigliosa', 'wonderful'],
 ['mastai', 'mastai'],
 ['bagnato', 'wet'],
 ["l'idolo", 'the idol'],
 ['facce', 'faces'],
 ["un'aria", 'an air'],
 ['allegri', 'cheerful'],
 ['doppiato', 'dubbed'],
 ['susanna', 'susanna'],
 ['miccoli', 'little ones'],
 ['belli', 'beautiful'],
 ['combini', 'combine'],
 ['ballerino', 'dancer'],
 ['diritti', 'rights'],
 ['borghi', 'villages'],
 ['nicola', 'nicola'],
 ['mostri', 'monsters'],
 ['modellino', 'model'],
 ['segretari', 'secretaries'],
 ['comunali', 'municipal'],
 ['provenienti', 'from'],
 ['riuniti', 'reunited'],
 ['pardo', 'pardo'],
 ['marcia', 'gear'],
 ['renault', 'renault'],
 ['inaspettati', 'unexpected'],
 ['locare', 'locate'],
 ['herbie', 'herbie'],
 ["l'ha", 'It has'],
 ['decorso', 'course'],
 ['compiaciuto', 'pleased'],
 ['teoriche', 'theoretical'],
 ['compiaciuto', 'pleased'],
 ['assodato', 'established'],
 ['nicola', 'nicola'],
 ['programmi', 'programs'],
 ['dicevo', 'I said'],
 ['segretario', 'secretary'],
 ['comunale', 'municipal'],
 ['eccellenza', 'excellence'],
 ['capita', 'it happens'],
 ['segretario', 'secretary'],
 ['comunale', 'municipal'],
 ['consigliato', 'advised'],
 ["dall'averlo", 'from having it'],
 ['rimango', 'I stay'],
 ['budan', 'budan'],
 ['miccoli', 'little ones'],
 ['involtino', 'roll'],
 ['fargli', 'do it'],
 ['iscriversi', 'to sign up'],
 ['iscriversi', 'to sign up'],
 ['sostenere', 'hold up'],
 ["d'accordo", 'agree'],
 ['allerta', 'alert'],
 ['risate', 'laughs'],
 ['spieghi', 'explain'],
 ['obbligatorio', 'obligatory'],
 ['tenersi', 'keep'],
 ['ridursi', 'reduce'],
 ['solido', 'solid'],
 ['fontaine', 'fountains'],
 ["c'e", 'there is'],
 ['scusato', 'sorry'],
 ["c'entri", 'you have something to do with it'],
 ['pacchia', 'tacky'],
 ['nata', 'born'],
 ['chiederei', 'I would ask'],
 ['tantinello', 'a lot'],
 ['miccoli', 'little ones'],
 ['barbara', 'barbara'],
 ['motegi', 'motegi'],
 ['giulia', 'Giulia'],
 ["d'accordo", 'agree'],
 ['compiaciuto', 'pleased'],
 ['giochetto', 'little game'],
 ['paolino', 'Pauline'],
 ['giocavo', 'I was playing'],
 ['paolini', 'Paulines'],
 ['valido', 'valid'],
 ['tenda', 'curtain'],
 ['ragazzini', 'kids'],
 ['compatto', 'compact'],
 ['bomber', 'bomber'],
 ['gioca', 'plays'],
 ['giampaolino', 'giampaolino'],
 ['calcoli', 'calculations'],
 ['trondheim', 'trondheim'],
 ['riporto', 'carryover'],
 ['tritolo', 'TNT'],
 ['proposta', 'proposal'],
 ['camicia', 'Shirt'],
 ['giubilo', 'jubilation'],
 ['stirata', 'stretched'],
 ['soffrire', 'suffer'],
 ['ricevo', 'I receive'],
 ['giovino', 'young'],
 ['scriverlo', 'write it'],
 ['moretti', 'moretti'],
 ['vincitore', 'winner'],
 ['recco', 'recco'],
 ['adrian', 'adrian'],
 ['spagna', 'Spain'],
 ['guadagnano', 'they earn'],
 ["dall'india", 'from India'],
 ['prigioniero', 'Prisoner'],
 ['riavuto', 'got it back'],
 ['liceo', 'Lyceum'],
 ['assistente', 'assistant'],
 ['universitario', 'university'],
 ["cattedra", "teacher's desk"],
 ['sapegno', 'I know'],
 ['guadagno', 'I earn'],
 ['comprerà', 'will buy'],
 ['segnate', 'marked'],
 ['tonetto', 'tonetto'],
 ['tumori', 'tumors'],
 ['dispiaceva', 'he was sorry'],
 ['allunga', 'lengthen'],
 ['amber', 'amber'],
 ['chilo', 'kilo'],
 ['ciofeca', 'crap'],
 ['sacrificarsi', 'sacrifice yourself'],
 ['gola', 'throat'],
 ['fortissimo', 'very strong'],
 ['disturbo', 'I disturb'],
 ['buffone', 'buffoon'],
 ['allarmarti', 'alarm you'],
 ['fidanzato', 'fiancé'],
 ['piazze', 'squares'],
 ['silvio', 'silvio'],
 ['pellico', 'pellicle'],
 ['prigioni', 'prisons'],
 ['libraio', 'bookseller'],
 ['avventure', 'adventures'],
 ['birichino', 'naughty'],
 ['luigi', 'louis'],
 ['pulsionale', 'instinctual'],
 ['grandioso', 'great'],
 ['ammazza', 'kill'],
 ['menean', 'menean'],
 ['editrice', 'publisher'],
 ['illustrazioni', 'illustrations'],
 ['originali', 'originals'],
 ['ambiti', 'areas'],
 ['capitolo', 'chapter'],
 ['cresciuti', 'grown up'],
 ['iniziarlo', 'start it'],
 ['zucchero', 'sugar'],
 ['pagheremo', 'we will pay'],
 ["parliamone", "let's talk about"],
 ["d'argento", 'silver'],
 ['omettere', 'omit'],
 ['arance', 'oranges'],
 ['delibera', 'decides'],
 ['venduta', 'sold'],
 ['potevamo', 'we could'],
 ['avendo', 'having'],
 ['affittato', 'rented'],
 ['bombardata', 'bombed'],
 ['trasferite', 'transferred'],
 ['saluterò', 'I will say hello'],
 ['teti', 'teti'],
 ['sembravano', 'they seemed'],
 ['maleducate', 'rude'],
 ['maleducata', 'rude'],
 ['impegno', 'I commit'],
 ['storico', 'historical'],
 ['riina', 'riina'],
 ['salutare', 'greet'],
 ['salutarlo', 'greet him'],
 ['perina', 'perina'],
 ['chigi', 'chigi'],
 ['aprile', 'April'],
 ['piero', 'piero'],
 ['miglioravo', 'I improved'],
 ['cucinare', 'cooked'],
 ['marchio', 'brand name'],
 ['eni', 'eni'],
 ['passarono', 'they passed'],
 ['rassicurare', 'reassure'],
 ['birichino', 'naughty'],
 ['scorta', 'buffer stock'],
 ['cominciavano', 'they began'],
 ['spiego', 'I explain'],
 ['marinaio', 'sailor Man'],
 ['capitolo', 'chapter'],
 ['schiavi', 'slaves'],
 ['bestiame', 'livestock'],
 ['divina', 'divine'],
 ['contrattempo', 'mishap'],
 ['grandezza', 'size'],
 ['decadenza', 'decadence'],
 ['monarca', 'monarch'],
 ['fricano', 'Frican'],
 ['europei', 'Europeans'],
 ['contrasti', 'contrasts'],
 ['sociali', 'social'],
 ['politici', 'politicians'],
 ['dividono', 'they divide'],
 ['tensione', 'voltage'],
 ['spinta', 'push'],
 ['osservatorio', 'observatory'],
 ['superficiale', 'superficial'],
 ['confusi', 'confused'],
 ['bagarre', 'brawl'],
 ['discutere', 'discuss'],
 ['dibattere', 'debate'],
 ['partiti', 'parties'],
 ['costretti', 'forced'],

 ['tranquillamente', 'quietly'],
 ['rossetto', 'lipstick'],
 ['quanta', 'how much'],
 ['popolazione', 'population'],
 ['voluti', 'wanted'],
 ['loredana', 'loredana'],
 ['crisi', 'crisis'],
 ['infiltrato', 'infiltrated'],
 ['nipotino', 'nephew'],
 ['eccoci', 'here we are'],
 ['sorda', 'deaf'],
 ['chiamando', 'calling'],
 ['peggiore', 'worse'],
 ['vecchiaia', 'old age'],
 ['granché', 'very much'],
 ['chievo', 'chievo'],
 ['famiglie', 'families'],
 ['insistevano', 'they insisted'],
 ['insistito', 'insisted'],
 ['sincero', 'sincere'],
 ['ipocrita', 'hypocritical'],
 ['confessarmi', 'confess'],
 ['confessarti', 'confess'],
 ['confessare', 'to confess'],
 ['pochetto', 'little'],
 ['mortacci', 'damn'],
 ['modificato', 'modified'],
 ['copie', 'copies'],
 ["all'autore", 'to the author'],
 ['diecimila', 'ten thousand'],
 ['copertina', 'cover'],
 ['copie', 'copies'],
 ['mila', 'thousands'],
 ['esaltare', 'exalt'],
 ['esageriamo', 'we exaggerate'],
 ['scrittore', 'writer'],
 ['grandissimo', 'very big'],
 ['patrie', 'homelands'],
 ['privato', 'private'],
 ['parliamoci', "let's talk"],
 ['carli', 'carli'],
 ['sottovalutato', 'underrated'],
 ['raffinatezza', 'refinement'],
 ['sensibilità', 'sensitivity'],
 ['soppalco', 'mezzanine'],
 ['fiera', 'fair'],
 ['ritrovato', 'found'],
 ['disprezzato', 'despised'],
 ['mito', 'myth'],
 ['crollo', 'collapse'],
 ["dell'autore", 'of the author'],
 ['conoscenza', 'knowledge'],
 ['basavo', 'I based'],
 ["l'avevo", 'I had it'],
 ['sgrammaticato', 'ungrammatical'],
 ['inconsistente', 'inconsistent'],
 ['trovavo', 'I found'],
 ['sperpero', 'I waste'],
 ['manoscritto', 'manuscript'],
 ['dessero', 'they gave'],
 ['atti', 'acts'],
 ['confessarti', 'confess'],
 ['giocarle', 'play them'],
 ['brevi', 'short'],
 ['usava', 'used'],
 ['moltissimo', 'very very much'],
 ['calato', 'dropped'],
 ['juliette', 'juliette'],
 ['delitto', 'crime'],
 ['cazzato', 'fucked'],
 ['tesa', 'tense'],
 ['mazzo', 'deck'],
 ['gasco', 'gasco'],
 ['fratellastro', 'step brother'],
 ['marines', 'marines'],
 ['tecnico', 'technician'],
 ['marina', 'navy'],
 ['chiudersi', 'close'],
 ['tenerli', 'keep them'],
 ['delineando', 'outlining'],
 ['berlusconiano', 'Berlusconian'],
 ['gemelline', 'twins'],
 ['capezzone', 'bighead'],
 ['attendeva', 'was waiting'],
 ['portasse', 'brought'],
 ['portasse', 'brought'],
 ['guardavo', 'I looked'],
 ['eccoci', 'here we are'],
 ['gobbi', 'gobbi'],
 ['aggravato', 'aggravated'],
 ['ebbene', 'well'],
 ['berretti', 'caps'],
 ['casomai', 'just in case'],
 ['rifarsi', 'make up for it'],
 ['incrocio', 'intersection'],
 ['brodo', 'broth'],
 ['marmellata', 'jam'],
 ['cannelloni', 'cannelloni'],
 ['preparando', 'preparing'],
 ['marika', 'marika'],
 ['unire', 'unite'],
 ['insensato', 'senseless'],
 ['ugualmente', 'equally'],
 ['rancore', 'rancor'],
 ['lega', 'League'],
 ["dell'amore", 'of love'],
 ["l'insofferenza", 'intolerance'],
 ['litighiamo', 'we argue'],
 ['preoccupa', 'worries'],
 ['sciupato', 'worn'],
 ['rivederla', 'see her again'],
 ['emiliano', 'Emilian'],
 ['scipione', 'scipio'],
 ['trovati', 'found'],
 ['mentasti', 'you lied'],
 ['contagio', 'infection'],
 ["l'arteriosclerosi", 'arteriosclerosis'],
 ['luthi', 'luthi'],
 ['andatevene', 'go away'],
 ['teneri', 'cute'],
 ['cattiveria', 'badness'],
 ['applausi', 'applause'],
 ['veniva', 'he was coming'],
 ['esistito', 'existed'],
 ["l'inferno", 'the hell'],
 ['novità', 'novelty'],
 ['odiati', 'hate yourself'],
 ['lasciati', 'left'],
 ['ripresi', 'I resumed'],
 ['infelici', 'unhappy'],
 ['severo', 'severe'],
 ['zitti', 'shut up'],
 ['perderti', 'lose you'],
 ['intuito', 'intuition'],
 ["cos'è", 'things'],
 ['dicembre', 'December'],
 ['parlai', 'I spoke'],
 ['dubbi', 'doubts'],
 ["l'hai", 'you have it'],
 ['invecchia', 'gets old'],
 ['oltretutto', 'Moreover'],
 ['stufata', 'tired'],
 ['fresco', 'fresh'],
 ['schifosa', 'disgusting'],
 ['reso', 'made'],
 ['cambieranno', 'they will change'],
 ['sinceri', 'sincere'],
 ['apposto', 'okay'],
 ['ritmo', 'rhythm'],
 ['entry', 'entry'],
 ['bingde', 'bingde'],
 ['frutto', 'fruit'],
 ['stagione', 'season'],
 ['divertiva', 'it was fun'],
 ['paradossi', 'paradoxes'],
 ['sarti', 'tailors'],
 ['comuni', 'common'],
 ['luoghi', 'places'],
 ['frattempo', 'in the meantime'],
 ['inventarne', 'invent'],
 ['cercano', 'they seek'],
 ['desideri', 'desires'],
 ['contentano', 'they are happy'],
 ['tenerlo', 'keep it'],
 ['piaciuta', 'liked it'],
 ['tiri', 'throw'],
 ['abbonato', 'subscriber'],
 ['juve', 'juve'],
 ['pensione', 'pension'],
 ['erboristeria', 'herbalist'],
 ['gestiscono', 'they manage'],
 ["all'ingrosso", 'wholesale'],
 ['magazzino', 'warehouse'],
 ['occupata', 'busy'],
 ['funerale', 'funeral'],
 ['pensieri', 'thoughts'],
 ['dedicano', 'dedicate'],
 ['occupati', 'busy'],
 ['sparlare', 'gossip'],
 ['feste', 'parties'],
 ["un'azione", 'an action'],
 ['cazzone', 'dick'],
 ['studenti', 'students'],
 ['magna', 'great'],
 ['compatito', 'pitied'],
 ['olo', 'holo'],
 ['litigato', 'argued'],
 ['lealisti', 'loyalists'],
 ['giurato', 'sworn'],
 ['veniva', 'he was coming'],
 ['razzi', 'rockets'],
 ['kacin', 'kacin'],
 ['esprime', 'expresses'],
 ['arrabbiare', 'get angry'],
 ["l'avrebbe", 'he would have it'],
 ['gigliola', 'lily'],
 ['sceglie', 'chooses'],
 ['rene', 'kidney'],
 ['fegato', 'liver'],
 ["d'acqua", 'of water'],
 ['bicchier', 'glass'],
 ["all'ossario", 'to the ossuary'],
 ['tomba', 'tomb'],
 ['sfinisce', 'exhausts'],
 ['togliermelo', 'take it away from me'],
 ['rialzo', 'rise'],
 ["l'oro", 'They'],
 ["d'oro", 'golden'],
 ['scalare', 'climb'],
 ['debbo', 'I have to'],
 ['recate', 'bring'],
 ['sistemare', 'tidy up'],
 ['risistemiamo', "let's rearrange"],
 ['glieli', 'give them to him'],
 ['topolino', 'baby mouse'],
 ['annate', 'vintages'],
 ['venduto', 'sold'],
 ['mila', 'thousands'],
 ['guadagnato', 'earned'],
 ['ripeto', 'I repeat'],
 ['cammina', 'walk'],
 ['rumeno', 'Romanian'],
 ['bravi', 'good'],
 ['vantaggio', 'advantage'],
 ['domandato', 'asked'],
 ['giovanni', 'John'],
 ['camminata', 'walk'],
 ['volando', 'flying'],
 ['temi', 'themes'],
 ['difficili', 'difficult'],
 ['canna', 'cane'],

 ['risposto', 'answered'],
 ['cari', 'Dear'],
 ["l'europa", 'Europe'],
 ['adriano', 'adrian'],
 ['rese', 'yields'],
 ['mancio', 'mancio'],
 ['seguendoli', 'following them'],
 ['architetto', 'architect'],
 ['ascoltando', 'listening'],
 ['esaltante', 'exhilarating'],
 ['francesi', 'French'],
 ['situazioni', 'situations'],
 ['italiane', 'Italian'],
 ['esaltanti', 'exhilarating'],
 ["tutt'altra", 'quite another'],
 ['attraversando', 'crossing'],
 ['doloroso', 'painful'],
 ['costruttivo', 'constructive'],
 ['autentiche', 'authentic'],
 ['tensioni', 'tensions'],
 ['morali', 'moral'],
 ['giustamente', 'rightly'],
 ['compri', 'buy'],
 ['compra', 'buy'],
 ['capiamo', 'we understand'],
 ["nell'inter", 'in the inter'],
 ['leccese', 'Leccese'],
 ['scorrere', 'slide'],
 ['salasso', 'bloodletting'],
 ['saldo', 'balance'],
 ['ricchi', 'rich'],
 ['rimasti', 'remained'],
 ['intronati', 'enthroned'],
 ['cambiamento', 'change'],
 ['confrontandoci', 'comparing ourselves'],
 ['co', 'co'],
 ['parecchi', 'several'],
 ['troppe', 'too many'],
 ['caranti', 'dear'],
 ['fondamentalmente', 'basically'],
 ['permetta', 'allow'],
 ['euphoria', 'euphoria'],
 ['allegria', 'cheerfulness'],
 ['allegro', 'cheerful'],
 ['parevano', 'they seemed'],
 ["tutt'oggi", 'still today'],
 ['fasce', 'bands'],
 ['scontento', 'dissatisfied'],
 ['incazzato', 'angry'],
 ['pallo', 'ball'],
 ['qualunquista', 'indifferent'],
 ['appartengo', 'I belong'],
 ["d'azione", 'of action'],
 ["l'esattezza", 'the accuracy'],
 ['ceduto', 'surrendered'],
 ['contribuito', 'contributed'],
 ['rinnovamento', 'renovation'],
 ['integrale', 'whole wheat'],
 ['ciancia', 'babble'],
 ['saperne', 'know'],
 ['rigore', 'rigor'],
 ['combattività', 'combativeness'],
 ['francesi', 'French'],
 ['sorvolare', 'fly over'],
 ['particolari', 'details'],
 ['sinceramente', 'sincerely'],
 ['difficoltà', 'difficulty'],
 ['seguirla', 'follow her'],
 ['ritenere', 'consider'],
 ['condizionato', 'conditioned'],
 ['privati', 'private'],
 ['nazionali', 'national'],
 ["l'inter", 'the inter'],
 ['attuale', 'current'],
 ['categoria', 'category'],
 ['scontenti', 'dissatisfied'],
 ['cronici', 'chronic'],
 ['arci', 'arch'],
 ['contentissimo', 'very happy'],
 ['dimostrarmi', 'prove myself'],
 ['francesi', 'French'],
 ['congiunto', 'joint'],
 ["dall'intento", 'from intent'],
 ['annunciato', 'announced'],
 ['proponi', 'propose'],
 ['tore', 'bull'],
 ['propone', 'proposes'],
 ['aspira', 'aspire'],
 ['seguiva', 'followed'],
 ['dicessi', 'I said'],
 ['risponde', 'he replies'],
 ['moda', 'fashion'],
 ['scala', 'stairs'],
 ['emozionante', 'thrilling'],
 ['toscani', 'Tuscans'],
 ["un'esperienza", 'an experience'],
 ['indimenticabile', 'unforgettable'],
 ['cambiamo', "let's change"],
 ['alleggerire', 'lighten'],
 ["l'imbarazzante", 'the embarrassing'],
 ['stranieri', 'foreigners'],
 ['nervosissimo', 'very nervous'],
 ["dell'attenzione", 'of attention'],
 ['susan', 'Susan'],
 ['architetto', 'architect'],
 ['tichetti', 'tichetti'],
 ['scuro', 'dark'],
 ['tichetti', 'tichetti'],
 ['rendi', 'make'],
 ['imbecilli', 'imbeciles'],
 ["all'architetto", 'to the architect'],
 ['esclusi', 'excluded'],
 ['calzetta', 'sock'],
 ['indicato', 'indicated'],
 ['accorto', 'shrewd'],
 ['darsi', 'give yourself'],
 ['beatrici', 'beatrices'],
 ["dell'imbecille", 'of the imbecile'],
 ['perdonami', 'Excuse me'],
 ['zero', 'zero'],
 ['simpatico', 'friendly'],
 ["d'artisti", 'of artists'],
 ['sposati', 'married'],
 ['abitano', 'they live'],
 ['emanuele', 'emanuel'],
 ['filiberto', 'filibert'],
 ['adottato', 'adopted'],
 ['laureato', 'graduate'],
 ['partecipa', 'participate'],
 ["un'infinità", 'an infinity'],
 ['concorsi', 'competitions'],
 ['vince', 'wins'],
 ['rifiuta', 'refuse'],
 ['valigie', 'suitcases'],
 ['valigia', 'suitcase'],
 ['pronte', 'ready'],
 ["l'ingresso", 'the entrance'],
 ['pronte', 'ready'],
 ['controllatina', 'check it out'],
 ['chiuse', 'closed'],
 ['finestre', 'windows'],
 ['diventati', 'become'],
 ['intensi', 'intense'],
 ['vedono', 'they see'],
 ['sentono', 'they feel'],
 ['pregare', 'pray'],
 ['torino', 'Turin'],
 ['scrivania', 'desk'],
 ['leggerlo', 'read it'],
 ['esami', 'exams'],
 ['finali', 'finals'],
 ['marinella', 'marinella'],
 ['finiscono', 'they end'],
 ['doverne', 'having to'],
 ["l'esterno", 'the outside'],
 ['forse', 'Perhaps'],
 ['milito', 'soldier'],
 ['animato', 'animated'],
 ['nuti', 'nuts'],
 ['elmo', 'helmet'],
 ['avventura', 'adventure'],
 ['casini', 'messes'],
 ['ferragosto', 'mid-August'],
 ['locali', 'locals'],
 ['tintoria', 'dry cleaner'],
 ['automatica', 'automatic'],
 ['pedonale', 'pedestrian'],
 ['apriremo', 'we will open'],
 ['zama', 'zama'],
 ['lavagetto', 'washer'],
 ['tattico', 'tactical'],
 ['scrittura', 'writing'],
 ['eccitanti', 'exciting'],
 ['dante', 'dante'],
 ['corporazione', 'guild'],
 ['finora', 'until now'],
 ['accettiamo', 'we accept'],
 ['ignoranti', 'ignorant'],
 ['vestire', 'to dress'],
 ['partiamo', "let's go"],
 ['terminillo', 'finish it'],
 ['debba', 'must'],
 ['titolo', 'title'],
 ['vende', 'sells'],
 ['giochiamo', "let's play"],
 ['aziende', 'companies'],
 ['giardinetta', 'station wagon'],
 ['scacchi', 'chess'],
 ['scarabeo', 'scarab'],
 ['scala', 'stairs'],
 ['tubo', 'tube'],
 ["el'acqua", 'and water'],
 ['piante', 'plant'],
 ["d'ingresso", 'of entrance'],
 ['cala', 'drops'],
 ["dell'invito", 'of the invitation'],
 ['approfitterò', 'I will take advantage'],
 ['potrò', 'I will be able'],
 ['trovarvi', 'find you'],
 ['marinella', 'marinella'],
 ["l'audizione", 'the audition'],
 ['genova', 'Genoa'],
 ['marsiglia', 'Marseille'],
 ['suina', 'swine'],
 ['belve', 'beasts'],
 ['doria', 'doria'],
 ['suv', 'suv'],
 ['vetri', 'glasses'],
 ['allievi', 'students'],
 ['esami', 'exams'],
 ['duemila', 'two-thousand'],
 ['versione', 'version'],
 ['salvate', 'save'],
 ['vedetta', 'lookout'],
 ['costiera', 'coastal'],
 ['trasmette', 'transmits'],
 ['andrea', 'Andrew'],
 ['doria', 'doria'],
 ['gorgo', 'whirlpool'],
 ["l'assemblea", 'the assembly'],
 ['fortemente', 'strongly'],
 ['nazionale', 'national'],
 ['polemico', 'polemical'],
 ["l'inter", 'the inter'],
 ['democratica', 'democratic'],
 ['tondo', 'round'],
 ['cerone', 'greasepaint'],
 ['gettate', 'throw'],
 ['urne', 'urns'],
 ['livelli', 'levels'],
 ['peccaminose', 'sinful'],
 ['fuggiti', 'Escaped'],
 ['studi', 'Education'],
 ['rifugia', 'refuge'],
 ['zanzara', 'mosquito'],
 ['salva', 'save'],
 ['temporale', 'storm'],
 ['rieccola', 'here it is again'],
 ['schiaffo', 'slap'],
 ['perdonato', 'forgiven'],
 ['perdono', 'pardon'],
 ['schiaffo', 'slap'],
 ['heroes', 'heroes'],
 ['immediato', 'immediate'],
 ['moscato', 'muscat'],
 ['tassisti', 'taxi drivers'],
 ['accompagnati', 'accompanied'],
 ['eliana', 'eliana'],
 ['ricominciare', 'start again'],
 ['clandestina', 'clandestine'],
 ["l'emiliano", 'the Emilian'],
 ['fabriano', 'fabriano'],
 ['cambiano', 'they change'],
 ['pensavi', 'thought'],
 ['ritroviamo', "let's meet again"],
 ["un'altra", 'another one'],
 ['andasti', 'you went'],
 ['temporale', 'storm'],
 ['comodo', 'comfortable'],
 ['cocomero', 'watermelon'],
 ['appagato', 'satisfied'],
 ['rottura', 'break'],
 ['divertivi', 'have fun'],
 ['cretino', 'cretin'],
 ['armando', 'arming'],
 ['smaniosa', 'eager'],
 ['smaniosa', 'eager'],
 ['maniaco', 'maniac'],
 ['usati', 'used'],
 ['adriano', 'adrian'],
 ['socialisti', 'socialists'],
 ['chamorro', 'chamorro'],
 ['ferro', 'iron'],
 ['dimetterti', 'resign'],
 ['diversamente', 'otherwise'],
 ['insoddisfazione', 'dissatisfaction'],
 ['dialettica', 'dialectic'],
 ['frugato', 'searched'],
 ['etienne', 'etienne'],
 ['armando', 'arming'],
 ['calo', 'decline'],
 ['finanziatori', 'financiers'],
 ['fidanzati', 'fiancés'],
 ['fidanza', 'girlfriend'],
 ['fidandomi', 'trusting'],
 ['sposta', 'move'],
 ['università', 'university'],
 ['guadagnare', 'earn'],
 ['costruirsi', 'build yourself'],
 ['indipendenza', 'independence'],
 ['eventuale', 'possible'],
 ["un'ottica", 'an optic'],
 ['passione', 'passion'],
 ['rischia', 'risks'],
 ['impegna', 'engage'],
 ['mancava', 'was missing'],
 ['rendi', 'make'],
 ['tratteggiato', 'dashed'],
 ['ricatto', 'blackmail'],
 ['ragionare', 'reason'],
 ['intelligenza', 'intelligence'],
 ['sennò', 'otherwise'],
 ['avvelena', 'poisons'],
 ['butti', 'throw'],
 ['porterà', 'will bring'],
 ['bestià', 'beast'],
 ['migliorate', 'improve'],
 ['intelligenti', 'intelligent'],
 ['scema', 'idiot'],
 ["quest'ora", 'this hour'],
 ['generico', 'generic'],
 ['buccia', 'peel'],
 ["dall'acqua", 'from the water'],
 ['territori', 'territories'],
 ['vecchietto', 'old man'],
 ['peggiori', 'worse'],
 ['frase', 'phrase'],
 ['sommato', 'added up'],
 ['brutti', 'ugly'],
 ['contorto', 'twisted'],
 ['melo', 'Apple tree'],
 ['ebete', 'idiot'],
 ["l'ultima", 'the last one'],
 ['cesti', 'baskets'],
 ['ridarmi', 'give me back'],
 ['meritava', 'deserved it'],
 ['sindacalista', 'trade unionist'],
 ['allegria', 'cheerfulness'],
 ['sindacalisti', 'trade unionists'],
 ['poveri', 'poor'],
 ['spalatori', 'shovelers'],
 ['stima', 'esteem'],
 ['fiore', 'flower'],
 ['nasce', 'is born'],

 ['godere', 'enjoy'],
 ['invita', 'invite'],
 ['cassa', 'earnings'],
 ['incanta', 'enchants'],
 ['scopre', 'discovers'],
 ['violetta', 'Violet'],
 ['ignora', 'ignore'],
 ['godiamo', "let's enjoy"],
 ['tazza', 'cup'],
 ['avvenga', 'happen'],
 ['scopra', 'find out'],
 ["all'altra", 'to the other'],
 ['gradireste', 'you would like'],
 ['accendiamo', "let's turn it on"],
 ['usciamo', "let's go out"],
 ['colta', 'cultured'],
 ['mezzogiorno', 'noon'],
 ['certi', 'certain'],
 ['introna', 'introna'],
 ['puccio', 'puccio'],
 ['barman', 'barman'],
 ['andò', 'he went'],
 ["l'africa", 'africa'],
 ['aprico', 'aprico'],
 ['teodorico', 'theodoric'],
 ['concerti', 'concerts'],
 ['insegna', 'sign'],
 ['clinica', 'clinic'],
 ['intervento', 'intervention'],
 ['rimandava', 'he put it off'],
 ['impensierirla', 'worry her'],
 ['massiche', 'massive'],
 ['cenno', 'nod'],
 ['sposo', 'groom'],
 ["l'aspettavi", 'you were expecting it'],
 ['tenera', 'tender'],
 ['cieco', 'blind'],
 ['temete', 'fear'],
 ['solitudine', 'loneliness'],
 ['sposatevi', 'get married'],
 ['sposo', 'groom'],
 ['disegnatore', 'designer'],
 ['tenero', 'tender'],
 ['trasporta', 'transports'],
 ['teodorico', 'theodoric'],
 ['diverranno', 'they will become'],
 ['tornerà', 'will come back'],
 ["l'aspetta", 'waits for it'],
 ['poesia', 'poetry'],
 ['litigava', 'he argued'],
 ['trovino', 'they find'],
 ['ciavolino', 'ciavolino'],
 ['toccò', 'touch'],
 ['vergine', 'virgin'],
 ['ritornerò', "I'll come back"],
 ['becchi', 'beaks'],
 ['cucine', 'kitchens'],
 ['carriere', 'careers'],
 ['quadri', 'paintings'],
 ['senatrice', 'senator'],
 ['piccolina', 'little one'],
 ['nascondere', 'HIDE'],
 ['costruisce', 'builds'],
 ['favoriti', 'favorites'],
 ['sfascia', 'wreck'],
 ['scherzi', 'jokes'],
 ['felicità', 'happiness'],
 ['rinunziare', 'give up'],
 ['ragiona', 'reason'],
 ['carlito', 'carlito'],
 ['ufficialmente', 'officially'],
 ['presi', 'taken'],
 ['dimenticherò', 'I will forget'],
 ['dhabi', 'dhabi'],
 ['innocenti', 'innocent'],
 ['veratour', 'veratour'],
 ['giradischi', 'record player'],
 ['regalato', 'given away'],
 ['portano', 'they bring'],
 ['pieni', 'full'],
 ['televisione', 'television'],
 ['chiamavo', 'I called'],
 ['turni', 'shifts'],
 ['compie', 'accomplishes'],
 ['vedova', 'widow'],
 ['liete', 'happy'],
 ['giulietta', 'Juliet'],
 ['aic', 'aic'],
 ['biglietti', 'tickets'],
 ['luciano', 'Luciano'],
 ['eletto', 'elected'],
 ['ferite', 'wounds'],
 ["d'ambito", 'of scope'],
 ['capello', 'hair'],
 ['maschietti', 'boys'],
 ['femminucce', 'sissies'],
 ['cominciano', 'they begin'],
 ['cominciamo', "let's start"],
 ['lio', 'l'],
 ['regali', 'gifts'],
 ['grandissimi', 'very big'],
 ['strega', 'witch'],
 ['carapace', 'carapace'],
 ['increduli', 'incredulous'],
 ['todt', 'todt'],
 ['libia', 'Libya'],
 ['essi', 'they'],
 ['annunciarmi', 'announce me'],
 ['capivo', 'I understood'],
 ['nascita', 'birth'],
 ['luisi', 'luisi'],
 ['limone', 'lemon'],
 ['certi', 'certain'],
 ['complimenti', 'Well done'],
 ['ariston', 'ariston'],
 ['piacevano', 'they liked it'],
 ['gusti', 'tastes'],
 ['astronauta', 'astronaut'],
 ['condurre', 'drive'],
 ['premiazione', 'awards ceremony'],
 ["l'abbigliamento", 'clothing'],
 ['grossista', 'wholesaler'],
 ['articoli', 'articles'],
 ['sasso', 'stone'],
 ['debiti', 'debts'],
 ['ragionier', 'accountant'],
 ['sensi', 'senses'],
 ['scaduti', 'expired'],
 ['metterò', 'I will put'],
 ['girata', 'turn'],
 ['carol', 'carol'],
 ['ragioniere', 'accountant'],
 ['terracciano', 'terracciano'],
 ['setta', 'sect'],
 ['allegra', 'cheerful'],
 ['chiamò', 'he called'],
 ["un'inter", 'an inter'],
 ['vana', 'vain'],
 ['rallegro', 'I rejoice'],
 ['figlioli', 'children'],
 ['ragioniere', 'accountant'],
 ['cambiale', 'promissory note'],
 ['dopodomani', 'the day after tomorrow'],
 ['nipotini', 'nephews'],
 ['cambiale', 'promissory note'],
 ['dopodomani', 'the day after tomorrow'],
 ['genera', 'generates'],
 ['piccinato', 'tiny'],
 ['johnson', 'johnson'],
 ['legnate', 'beat'],
 ['magnate', 'magnate'],
 ['incontrerete', 'you will meet'],
 ['noterete', 'you will notice'],
 ['sappiate', 'know'],
 ['essi', 'they'],
 ['inseparabili', 'inseparable'],
 ['conoscevo', 'I knew'],
 ['fiabe', 'fairy tales'],
 ['ungheresi', 'Hungarians'],
 ['antico', 'ancient'],
 ['magiara', 'Magyar'],
 ['salotti', 'living rooms'],
 ['beige', 'beige'],
 ['funebre', 'funeral'],
 ['secolo', 'century'],
 ['salotto', 'living room'],
 ['cuscino', 'cushion'],
 ['gancia', 'hook'],
 ['guggen', 'guggen'],
 ['bogans', 'bogans'],
 ['hogan', 'hogan'],
 ['karima', 'karima'],
 ['quinte', 'fifths'],
 ['ungherese', 'Hungarian'],
 ['falli', 'fouls'],
 ['enti', 'entities'],
 ['lenticchie', 'lentils'],
 ['ungherese', 'Hungarian'],
 ['plachi', 'calm down'],
 ['semplici', 'simple'],
 ['platts', 'platts'],
 ['plaid', 'plaid'],
 ['lenticchie', 'lentils'],
 ['ragioni', 'reasons'],
 ['ragionieri', 'accountants'],
 ['rateizza', 'pay in installments'],
 ['interessi', 'interests'],
 ['interessi', 'interests'],
 ['ladri', 'thieves'],
 ['cambiali', 'bills of exchange'],
 ['firmato', 'signed'],
 ['paracetamolo', 'paracetamol'],
 ['sciopero', 'strike'],
 ['sincera', 'sincere'],
 ['trono', 'throne'],
 ['galli', 'roosters'],
 ['potevano', 'they could'],
 ["dell'opzione", 'of the option'],
 ['sapevano', 'they knew'],
 ['piomba', 'swoops'],
 ['fatevi', 'do it'],
 ['consigliare', 'recommend'],



];
