const lang_0 = [

["estaba", "be (past)"],
["tenía", "have (past)"],
["fui", "go (past)"],
["hice", "do (past)"],
["me gustó", "like (past)"],
["quería", "want (past)"],
["necesité", "need (past)"],
["tenía que", "have to (past)"],
["podía", "be able to (past)"],
["traté de", "try to (past)"],

["estoy", "be (present)"],
["tengo", "have (present)"],
["voy", "go (present)"],
["hago", "do (present)"],
["me gusta", "like (present)"],
["quiero", "want (present)"],
["necesito", "need (present)"],
["tengo que", "have to (present)"],
["puedo", "be able to (present)"],
["trato de", "try to (present)"],

["voy a estar", "be (future)"],
["voy a tener", "have (future)"],
["voy a ir", "go (future)"],
["voy a hacer", "do (future)"],
["me va a gustar", "like (future)"],
["voy a querer", "want (future)"],
["voy a necesitar", "need (future)"],
["voy a tener que", "have to (future)"],
["voy a poder", "be able to (future)"],
["voy a tratar de", "try to (future)"],

["estaría", "be (conditional)"],
["tendría", "have (conditional)"],
["iría", "go (conditional)"],
["haría", "do (conditional)"],
["me gustaría", "like (conditional)"],
["querría", "want (conditional)"],
["necesitaría", "need (conditional)"],
["tendría que", "have to (conditional)"],
["podría", "be able to (conditional)"],
["trataría de", "try to (conditional)"],

["antes", "hour (past)"],
["ayer", "day (past)"],
["anoche", "night (past)"],
["la semana pasada", "week (past)"],
["el fin de semana pasada", "weekend (past)"],
["el mes pasado", "month (past)"],
["el año pasado", "year (past)"],
["la última vez", "time (past)"],
["ahora", "hour (present)"],
["hoy", "day (present)"],
["esta noche", "night (present)"],
["esta semana", "week (present)"],
["este fin de semana", "weekend (present)"],
["este mes", "month (present)"],
["este año", "year (present)"],
["esta vez", "time (present)"],
["después", "hour (future)"],
["mañana", "day (future)"],
["mañana en la noche", "night (future)"],
["la semana que viene", "week (future)"],
["el fin de semana que viene", "weekend (future)"],
["el mes que viene", "month (future)"],
["el año que viene", "year (future)"],
["la próxima vez", "time (future)"],
["¿Cómo?", "How?"],
["¿Dónde?", "where?"],
["¿Qué?", "What?"],
["¿Cuándo?", "When?"],
["¿Quién?", "Who?"],
["¿Por qué?", "Why?"],
["¿Cuánto?", "How much?"],


["pero", "but"],
["y", "and"],
["o", "or"],
["porque", "because"],
["entonces", "so, then"],


["siempre", "always"],
["a veces", "sometimes"],
["nunca", "never"],


["todos", "everyone"],
["alguien", "someone"],
["nadie", "noone"],
["toda parte", "everywhere"],
["alguna parte", "somewhere"],
["ninguna parte", "nowhere"],
["todo", "everything"],
["algo", "something"],
["nada", "nothing"],
["estava", "be (past)"],
["tinha", "have (past)"],
["fui", "go (past)"],
["fiz", "do (past)"],
["gostei de", "like (past)"],
["queria", "want (past)"],
["tinha que", "have to (past)"],
["podia", "be able to (past)"],
["estou", "be (present)"],
["tenho", "have (present)"],
["vou", "go (present)"],
["faço", "do (present)"],
["gosto de", "like (present)"],
["quero", "want (present)"],
["tenho que", "have to (present)"],
["posso", "be able to (present)"],
["vou estar", "be (future)"],
["vou ter", "have (future)"],
["vou", "go (future)"],
["vou fazer", "do (future)"],
["vou gostar de", "like (future)"],
["vou querer", "want (future)"],
["vou ter que", "have to (future)"],
["vou poder", "be able to (future)"],
["estaria", "be (conditional)"],
["teria", "have (conditional)"],
["iria", "go (conditional)"],
["faria", "do (conditional)"],
["gostaria de", "like (conditional)"],
["queria", "want (conditional)"],
["teria que", "have to (conditional)"],
["poderia", "be able to (conditional)"],


["antes", "hour (past)"],
["ontem", "day (past)"],
["ontem à noite", "night (past)"],
["a semana passada", "week (past)"],
["o fim de semana passada", "weekend (past)"],
["o mês passado", "month (past)"],
["o ano passado", "year (past)"],
["a última vez", "time (past)"],
["agora", "hour (present)"],
["hoje", "day (present)"],
["hoje à noite", "night (present)"],
["esta semana", "week (present)"],
["este fim da semana", "weekend (present)"],
["este mês", "month (present)"],
["este ano", "year (present)"],
["esta vez", "time (present)"],
["depois", "hour (future)"],
["amanhá", "day (future)"],
["amanhá à noite", "night (future)"],
["a semana que vem", "week (future)"],
["o fim da semana que vem", "weekend (future)"],
["o mês que vem", "month (future)"],
["o ano que vem", "year (future)"],
["a próxima vez", "time (future)"],

["Como?", "How?"],
["Onde?", "where?"],
["O que?", "What?"],
["Quando?", "When?"],
["Quem?", "Who?"],
["Por que?", "Why?"],
["Quanto?", "How much?"],

["mas", "but"],
["e", "and"],
["ou", "or"],
["poraue", "because"],
["então", "so, then"],

["sempre", "always"],

["muito", "often"],

["as vezes", "sometimes"],

["nunca", "never"],

["todo mundo", "everyone"],
["alguém", "someone"],
["ninguém", "noone"],
["toda parte", "everywhere"],
["algum lugar", "somewhere"],
["nenhum lugar", "nowhere"],
["todo", "everything"],
["alguma coisa", "something"],
["nada", "nothing"],

["ero", "be (past)"],
["avevo", "have (past)"],
["sono andato", "go (past)"],
["ho fatto", "do (past)"],
["mi è piaciuto", "like (past)"],
["volevo", "want (past)"],
["dovevo", "have to (past)"],
["ho potuto", "be able to (past)"],
["sono", "be (present)"],
["ho", "have (present)"],
["vado", "go (present)"],
["faccio", "do (present)"],
["mi piace", "like (present)"],
["voglio", "want (present)"],
["devo", "have to (present)"],
["posso", "be able to (present)"],
["sarò", "be (future)"],
["avrò", "have (future)"],
["andrò", "go (future)"],
["farò", "do (future)"],
["mi piacerà", "like (future)"],
["vorrò", "want (future)"],
["dovrò", "have to (future)"],
["(?)", "be able to (future)"],
["sarei", "be (conditional)"],
["avrei", "have (conditional)"],
["andrei", "go (conditional)"],
["farei", "do (conditional)"],
["mi piacerebbe", "like (conditional)"],
["vorrei", "want (conditional)"],
["avrei dovuto", "have to (conditional)"],
["sarei capace di", "be able to (conditional)"],


["prima", "hour (past)"],
["ieri", "day (past)"],
["la notte scorsa", "night (past)"],
["la settimana scorsa", "week (past)"],
["lo scorso fine settimana", "weekend (past)"],
["lo scorso mese", "month (past)"],
["l'anno scorso", "year (past)"],
["ultima volta", "time (past)"],
["adesso", "hour (present)"],
["oggi", "day (present)"],
["stasera", "night (present)"],
["questa settimana", "week (present)"],
["questo fine settimana", "weekend (present)"],
["questo mese", "month (present)"],
["quest'anno", "year (present)"],
["questa volta", "time (present)"],
["dopo", "hour (future)"],
["domani", "day (future)"],
["domani notte", "night (future)"],
["la prossima settimana", "week (future)"],
["il prossimo fine settimana", "weekend (future)"],
["il prossimo mese", "month (future)"],
["l'anno prossimo", "year (future)"],
["la prossima volta", "time (future)"],

["Come?", "How?"],
["Dove?", "where?"],
["Cosa?", "What?"],
["Quando?", "When?"],
["Chi?", "Who?"],
["Perché?", "Why?"],
["Quanto?", "How much?"],


["ma", "but"],
["e", "and"],
["o", "or"],
["perche", "because"],
["allora", "so, then"],


["sempre", "always"],
["avolte", "sometime"],
["mai", "never"],


["tutti", "everyone"],
["qualcuno", "someone"],
["nessuno", "noone"],
["ovunque", "everywhere"],
["qualche parte", "somewhere"],
["nessuna parte", "nowhere"],
["tutto", "everything"],
["qualcosa", "something"],
["niente", "nothing"],

["j'étais", "être (past)"],
["j'ai eu / j'avais", "avoir (past)"],
["je suis allé(e)", "aller (past)"],
["j'ai fait", "faire (past)"],
["j'ai aimé", "aimer (past)"],
["je voulais", "vouloir (past)"],
["j'ai dû", "devoir (past)"],
["j'ai pu", "pouvoir (past)"],

["je suis", "être (present)"],
["j'ai", "avoir (present)"],
["je vais", "aller (present)"],
["je fais", "faire (present)"],
["j'aime", "aimer (present)"],
["je veux", "vouloir (present)"],
["je devrais", "devoir (present)"],
["je peut", "pouvoir (present)"],

["je serai", "être (future)"],
["j'aurai", "avoir (future)"],
["j'irai", "aller (future)"],
["je ferai", "faire (future)"],
["j'aimerai", "aimer (future)"],
["je voudrai", "vouloir (future)"],
["?", "devoir (future)"],
["je pourrai", "pouvoir (future)"],

["je serais", "être (conditional)"],
["j'aurais", "avoir (conditional)"],
["j'irais", "aller (conditional)"],
["je ferais", "faire (conditional)"],
["j'aimerais", "aimer (conditional)"],
["je voudrais", "vouloir (conditional)"],
["?", "devoir (conditional)"],
["je pourrais", "pouvoir (conditional)"],


["plus tôt", "hour (past)"],
["hier", "day (past)"],
["hier soir", "night (past)"],
["la semaine derniere", "week (past)"],
["le week-end dernier", "weekend (past)"],
["le mois dernier", "month (past)"],
["l'année dernière", "year (past)"],
["la dernière fois", "time (past)"],

["maintenant", "hour (present)"],
["aujourd-hui", "day (present)"],
["ce soir", "night (present)"],
["cette semaine", "week (present)"],
["ce week-end", "weekend (present)"],
["ce mois", "month (present)"],
["cette année", "year (present)"],
["cette fois", "time (present)"],

["plus tard", "hour (future)"],
["demain", "day (future)"],
["demain soir", "night (future)"],
["la semaine prochaine", "week (future)"],
["le week-end prochain", "weekend (future)"],
["le mois prochain", "month (future)"],
["l'année prochaine", "year (future)"],
["la prochaine fois", "time (future)"],

["Comment?", "How?"],
["Où?", "where?"],
["Quoi?", "What?"],
["Quand?", "When?"],
["Qui?", "Who?"],
["Pourquoi?", "Why?"],
["Combien?", "How much?"],
["mais", "but"],
["et", "and"],
["ou", "or"],
["parce que", "because"],
["alors", "so, then"],
["toujours", "always"],
["parfois", "sometimes"],
["jamais", "never"],
["tout le monde", "everyone"],
["quelqu'un", "someone"],
["personne", "noone"],
["partout", "everywhere"],
["quelque part", "somewhere"],
["nulle part", "nowhere"],
["tout", "everything"],
["quelque chose", "something"],
["rien", "nothing"],

];

