const portuguese = [
 ["que", "what"],
 ["o", "The"],
 ["a", "The"],
 ["não", "no"],
 ["de", "in"],
 ["é", "It's"],
 ["e", "and"],
 ["um", "one"],
 ["eu", "me"],
 ["para", "for"],
 ["se", "if"],
 ["me", "me"],
 ["uma", "an"],
 ["está", "it is"],
 ["com", "with"],
 ["por", "per"],
 ["do", "of"],
 ["te", "you"],
 ["os", "the"],
 ["em", "in"],
 ["ele", "him"],
 ["bem", "good"],
 ["isso", "that"],
 ["mas", "but"],
 ["como", "as"],
 ["da", "gives"],
 ["você", "you"],
 ["sim", "yea"],
 ["no", "at the"],
 ["as", "at"],
 ["mais", "more"],
 ["meu", "my"],
 ["aqui", "on here"],
 ["na", "at"],
 ["muito", "much"],
 ["vamos", "let's go"],
 ["foi", "was"],
 ["estou", "I am"],
 ["ela", "she"],
 ["vai", "go"],
 ["fazer", "do"],
 ["tem", "have"],
 ["isto", "this"],
 ["já", "already"],
 ["minha", "my"],
 ["tudo", "all"],
 ["só", "only"],
 ["nos", "we"],
 ["ser", "to be"],
 ["ao", "to"],
 ["tenho", "have"],
 ["agora", "now"],
 ["tu", "you"],
 ["vou", "I'm going"],
 ["à", "the"],
 ["sei", "know"],
 ["quando", "when"],
 ["lá", "over there"],
 ["há", "there is"],
 ["porque", "because"],
 ["onde", "where"],
 ["nada", "anything"],
 ["seu", "your"],
 ["estás", "these"],
 ["quem", "who"],
 ["então", "so"],
 ["era", "was"],
 ["sua", "your"],
 ["ou", "or"],
 ["lhe", "you"],
 ["quero", "I want"],
 ["sou", "am"],
 ["nós", "we"],
 ["coisa", "thing"],
 ["são", "are"],
 ["ter", "Tue"],
 ["dizer", "tell"],
 ["eles", "they"],
 ["pode", "can"],
 ["esta", "it is"],
 ["bom", "good"],
 ["mesmo", "same"],
 ["todos", "all"],
 ["mim", "me"],
 ["dos", "from"],
 ["estava", "was"],
 ["posso", "can"],
 ["este", "this one"],
 ["ver", "to see"],
 ["nunca", "never"],
 ["assim", "like this"],
 ["estão", "they are"],
 ["casa", "house"],
 ["lo", "it"],
 ["até", "up until"],
 ["disse", "said"],
 ["quer", "would you like"],
 ["temos", "we have"],
 ["tempo", "time"],
 ["acho", "think"],
 ["ir", "go"],
 ["obrigado", "thank you"],
 ["também", "also"],
 ["tens", "hast"],
 ["deus", "God"],
 ["quê", "what"],
 ["ainda", "still"],
 ["vez", "turn"],
 ["noite", "night"],
 ["pai", "dad"],
 ["tão", "so"],
 ["teu", "your"],
 ["falar", "speak"],
 ["tua", "your"],
 ["melhor", "best"],
 ["dia", "day"],
 ["sobre", "about"],
 ["certo", "right"],
 ["sempre", "ever"],
 ["sabe", "You know"],
 ["és", "are"],
 ["depois", "after"],
 ["vida", "life"],
 ["mãe", "mom"],
 ["oh", "oh"],
 ["nem", "nor"],
 ["senhor", "Mr"],
 ["estamos", "we are"],
 ["anos", "years"],
 ["olá", "hi"],
 ["talvez", "perhaps"],
 ["sr", "Mr."],
 ["homem", "man"],
 ["sem", "without"],
 ["sabes", "know"],
 ["alguém", "someone"],
 ["das", "of"],
 ["boa", "good"],
 ["algo", "something"],
 ["ti", "you"],
 ["alguma", "some"],
 ["vocês", "you"],
 ["coisas", "things"],
 ["tinha", "had"],
 ["dois", "two"],
 ["dele", "his"],
 ["claro", "clear"],
 ["vais", "going"],
 ["estar", "be"],
 ["ficar", "stay"],
 ["aí", "there"],
 ["pelo", "fur"],
 ["pessoas", "people"],
 ["queres", "want"],
 ["essa", "that"],
 ["esse", "that"],
 ["verdade", "truth"],
 ["faz", "does"],
 ["parece", "looks"],
 ["grande", "big"],
 ["antes", "before"],
 ["dinheiro", "money"],
 ["ninguém", "nobody"],
 ["apenas", "only"],
 ["pouco", "little"],
 ["preciso", "need"],
 ["la", "over there"],
 ["comigo", "with me"],
 ["outra", "other"],
 ["trabalho", "job"],
 ["merda", "shit"],
 ["tipo", "type"],
 ["vão", "vain"],
 ["fora", "out"],
 ["vá", "go"],
 ["espera", "wait"],
 ["qualquer", "any"],
 ["hoje", "today"],
 ["qual", "what"],
 ["todo", "all"],
 ["olha", "looks"],
 ["pela", "through the"],
 ["podes", "can"],
 ["saber", "to know"],
 ["toda", "all"],
 ["deve", "should"],
 ["daqui", "from here"],
 ["podemos", "we can"],
 ["filho", "son"],
 ["mulher", "woman"],
 ["mundo", "world"],
 ["disso", "of this"],
 ["meus", "my"],
 ["seus", "their"],
 ["nome", "name"],
 ["dar", "to give"],
 ["cá", "here"],
 ["seja", "be"],
 ["outro", "other"],
 ["nosso", "our"],
 ["pois", "because"],
 ["diz", "says"],
 ["num", "on one"],
 ["nossa", "wow"],
 ["quanto", "how much"],
 ["ei", "hey"],
 ["sair", "get out"],
 ["queria", "I wanted"],
 ["vem", "comes"],
 ["volta", "return"],
 ["amigo", "friend"],
 ["novo", "new"],
 ["embora", "although"],
 ["lugar", "place"],
 ["será", "will be"],
 ["certeza", "assurance"],
 ["três", "three"],
 ["sério", "seriously"],
 ["mal", "bad"],
 ["têm", "have"],
 ["desculpa", "excuse"],
 ["carro", "car"],
 ["às", "at"],
 ["problema", "problem"],
 ["menos", "any less"],
 ["passa", "goes by"],
 ["vezes", "times"],
 ["nas", "at the"],
 ["ali", "there"],
 ["dela", "her"],
 ["dentro", "inside"],
 ["aconteceu", "It happened"],
 ["querida", "Dear"],
 ["primeiro", "first"],
 ["amor", "love"],
 ["pensar", "think"],
 ["todas", "all"],
 ["cara", "guy"],
 ["lado", "side"],
 ["fez", "did"],
 ["contigo", "with you"],
 ["aos", "to"],
 ["parte", "part"],
 ["consigo", "I can"],
 ["anda", "walking"],
 ["algum", "some"],
 ["numa", "in"],
 ["aquele", "that"],
 ["hora", "hour"],
 ["voltar", "come back"],
 ["homens", "men"],
 ["dias", "days"],
 ["gente", "people"],
 ["tentar", "try"],
 ["gosto", "taste"],
 ["porquê", "because"],
 ["vi", "saw"],
 ["tarde", "evening"],
 ["pensei", "thought"],
 ["entre", "in between"],
 ["suas", "your"],
 ["los", "them"],
 ["duas", "two"],
 ["obrigada", "thanks"],
 ["desculpe", "excuse me"],
 ["sabia", "I knew"],
 ["fui", "went"],
 ["podem", "can"],
 ["atrás", "behind"],
 ["uns", "some"],
 ["cabeça", "head"],
 ["fica", "stay"],
 ["somos", "are"],
 ["pra", "for"],
 ["frente", "front"],
 ["cidade", "city"],
 ["amanhã", "tomorrow"],
 ["cima", "top"],
 ["momento", "time"],
 ["razão", "reason"],
 ["nenhum", "none"],
 ["família", "family"],
 ["amigos", "friends"],
 ["desde", "since"],
 ["vos", "you"],
 ["tal", "such"],
 ["horas", "hours"],
 ["sinto", "I"],
 ["acha", "think"],
 ["achas", "think"],
 ["polícia", "police"],
 ["outros", "others"],
 ["foram", "were"],
 ["tenha", "has"],
 ["seria", "would be"],
 ["medo", "fear"],
 ["tanto", "so much"],
 ["pronto", "ready"],
 ["precisa", "need"],
 ["entrar", "log in"],
 ["nova", "new"],
 ["deles", "their"],
 ["forma", "form"],
 ["aquilo", "that"],
 ["passar", "pass"],
 ["chegar", "to arrive"],
 ["quase", "almost"],
 ["história", "history"],
 ["deixar", "leave"],
 ["porta", "door"],
 ["cuidado", "caution"],
 ["cada", "each"],
 ["ia", "would"],
 ["podia", "could"],
 ["ah", "ah"],
 ["fiz", "I did"],
 ["pessoa", "person"],
 ["lhes", "them"],
 ["realmente", "really"],
 ["ideia", "idea"],
 ["fosse", "was"],
 ["irmão", "brother"],
 ["morrer", "die"],
 ["devia", "should"],
 ["alguns", "some"],
 ["morto", "dead"],
 ["minhas", "my"],
 ["adeus", "goodbye"],
 ["feliz", "happy"],
 ["minutos", "minutes"],
 ["primeira", "first"],
 ["ajudar", "to help"],
 ["caso", "case"],
 ["contra", "against"],
 ["sorte", "luck"],
 ["aquela", "that"],
 ["ano", "year"],
 ["encontrar", "meet"],
 ["vir", "come over"],
 ["caminho", "way"],
 ["rapaz", "boy"],
 ["ouvir", "hear"],
 ["enquanto", "while"],
 ["näo", "no"],
 ["maneira", "way"],
 ["olhos", "eyes"],
 ["estes", "these"],
 ["espero", "I expect"],
 ["sido", "been"],
 ["poderia", "could"],
 ["semana", "week"],
 ["desta", "this"],
 ["trabalhar", "to work"],
 ["água", "water"],
 ["matar", "kill"],
 ["durante", "during"],
 ["quarto", "bedroom"],
 ["conta", "account"],
 ["senhora", "lady"],
 ["morte", "death"],
 ["tive", "I had"],
 ["neste", "in this"],
 ["terra", "Earth"],
 ["logo", "soon"],
 ["ajuda", "help"],
 ["guerra", "war"],
 ["estas", "these"],
 ["dá", "gives"],
 ["rápido", "fast"],
 ["feito", "done"],
 ["pára", "for"],
 ["querido", "Dear"],
 ["levar", "take along"],
 ["óptimo", "optimum"],
 ["mãos", "hands"],
 ["jogo", "game"],
 ["manhã", "morning"],
 ["arma", "weapon"],
 ["querem", "they want"],
 ["fala", "speaks"],
 ["perto", "close"],
 ["for", "is"],
 ["nossos", "our"],
 ["importante", "important"],
 ["algumas", "some"],
 ["faço", "I do"],
 ["poder", "power"],
 ["cinco", "five"],
 ["pessoal", "folks"],
 ["calma", "calm"],
 ["teus", "your"],
 ["precisamos", "we need"],
 ["rapazes", "boys"],
 ["á", "The"],
 ["juntos", "together"],
 ["acontecer", "to happen"],
 ["comer", "eat"],
 ["filha", "daughter"],
 ["fim", "end"],
 ["faça", "knife"],
 ["acredito", "I believe"],
 ["diga", "say it"],
 ["baixo", "low"],
 ["venha", "come on"],
 ["causa", "cause"],
 ["sra", "Mrs."],
 ["espere", "hang on"],
 ["escola", "school"],
 ["meio", "means"],
 ["maior", "bigger"],
 ["umas", "some"],
 ["vê", "see"],
 ["mão", "hand"],
 ["problemas", "problems"],
 ["vejo", "watch"],
 ["nisso", "in that"],
 ["mesma", "same"],
 ["começar", "begin"],
 ["chefe", "boss"],
 ["dormir", "to sleep"],
 ["velho", "old"],
 ["havia", "there were"],
 ["acabou", "ended"],
 ["disto", "from this"],
 ["dr", "dr"],
 ["mulheres", "women"],
 ["idiota", "moron"],
 ["única", "only"],
 ["última", "last"],
 ["sabem", "know"],
 ["nenhuma", "none"],
 ["viu", "saw"],
 ["dólares", "dollars"],
 ["difícil", "difficult"],
 ["quatro", "four"],
 ["coração", "heart"],
 ["número", "number"],
 ["deste", "this"],
 ["lamento", "am sorry"],
 ["viver", "to live"],
 ["prazer", "pleasure"],
 ["sai", "leaves"],
 ["crianças", "children"],
 ["olhe", "look"],
 ["ouve", "hears"],
 ["segundo", "second"],
 ["chega", "arrives"],
 ["eram", "they were"],
 ["fazendo", "doing"],
 ["andar", "walk"],
 ["capitão", "captain"],
 ["muitas", "many"],
 ["ouvi", "I heard"],
 ["muitos", "many"],
 ["elas", "they"],
 ["sangue", "blood"],
 ["estado", "state"],
 ["importa", "it matters"],
 ["corpo", "body"],
 ["teve", "had"],
 ["penso", "I think"],
 ["parar", "stop"],
 ["gostaria", "would"],
 ["mil", "thousand"],
 ["usar", "use"],
 ["ontem", "yesterday"],
 ["rapariga", "girl"],
 ["significa", "means"],
 ["festa", "party"],
 ["deixa", "cue"],
 ["pequeno", "small"],
 ["devo", "I"],
 ["mau", "bad"],
 ["força", "force"],
 ["longe", "far"],
 ["filhos", "children"],
 ["depressa", "quickly"],
 ["morreu", "died"],
 ["marido", "husband"],
 ["olhar", "look"],
 ["presidente", "president"],
 ["tomar", "to take"],
 ["essas", "these"],
 ["nesta", "in this"],
 ["demais", "too much"],
 ["meses", "months"],
 ["gosta", "like"],
 ["esses", "those"],
 ["muita", "lots of"],
 ["pena", "pity"],
 ["pensa", "think"],
 ["perder", "lose"],
 ["veio", "came"],
 ["trás", "back"],
 ["esperar", "wait"],
 ["contar", "tell"],
 ["buscar", "search"],
 ["paz", "peace"],
 ["procura", "demand"],
 ["irmã", "sister"],
 ["disseste", "said"],
 ["raio", "lightning"],
 ["teria", "it would have"],
 ["pais", "parents"],
 ["altura", "height"],
 ["digo", "I say"],
 ["menina", "girl"],
 ["estavam", "they were"],
 ["errado", "wrong"],
 ["tivesse", "had"],
 ["fazes", "you do"],
 ["vindo", "coming"],
 ["filme", "movie"],
 ["fácil", "easy"],
 ["acordo", "wake up"],
 ["nao", "no"],
 ["pergunta", "question"],
 ["possível", "possible"],
 ["vivo", "live"],
 ["cama", "bed"],
 ["dizem", "say"],
 ["acabar", "end"],
 ["suficiente", "enough"],
 ["fizeste", "did"],
 ["estranho", "weird"],
 ["sabemos", "we know"],
 ["segurança", "safety"],
 ["puta", "hooker"],
 ["brincar", "play"],
 ["licença", "license"],
 ["além", "beyond"],
 ["conseguir", "get"],
 ["livro", "book"],
 ["tirar", "take"],
 ["país", "parents"],
 ["jantar", "dinner"],
 ["palavra", "word"],
 ["seis", "six"],
 ["conheço", "I know"],
 ["deu", "He gave"],
 ["nossas", "our"],
 ["passado", "past"],
 ["fique", "stay"],
 ["boca", "mouth"],
 ["outras", "others"],
 ["comida", "food"],
 ["falta", "lack"],
 ["armas", "weapons"],
 ["ficou", "stayed"],
 ["fazem", "make"],
 ["bastante", "quite"],
 ["sozinho", "alone"],
 ["deveria", "should"],
 ["ai", "there"],
 ["minuto", "minute"],
 ["pelos", "by"],
 ["luz", "light"],
 ["ar", "air"],
 ["tuas", "your"],
 ["música", "music"],
 ["pagar", "pay"],
 ["fogo", "fire"],
 ["próprio", "own"],
 ["atenção", "attention"],
 ["chegou", "has arrived"],
 ["quiser", "want"],
 ["forte", "strong"],
 ["existe", "exist"],
 ["possa", "be likely to"],
 ["pedir", "ask"],
 ["sentir", "to feel"],
 ["acreditar", "to believe"],
 ["partir", "leave"],
 ["continua", "to be continued"],
 ["mudar", "to change"],
 ["toma", "takes"],
 ["rei", "king"],
 ["direito", "right"],
 ["jovem", "young"],
 ["único", "single"],
 ["café", "coffee"],
 ["diferente", "different"],
 ["vossa", "yours"],
 ["culpa", "fault"],
 ["plano", "plan"],
 ["rua", "street"],
 ["foste", "wast"],
 ["milhões", "millions"],
 ["consegue", "can"],
 ["pé", "foot"],
 ["correr", "run"],
 ["próxima", "next"],
 ["devias", "You should"],
 ["equipa", "team"],
 ["pequena", "small"],
 ["linda", "beautiful"],
 ["pare", "stop"],
 ["sequer", "even"],
 ["jogar", "play"],
 ["fico", "I get"],
 ["provavelmente", "most likely"],
 ["exactamente", "exactly"],
 ["passou", "passed on"],
 ["casamento", "marriage"],
 ["deixe", "leave"],
 ["aqueles", "those"],
 ["especial", "special"],
 ["ganhar", "win"],
 ["sala", "living room"],
 ["grandes", "big ones"],
 ["semanas", "weeks"],
 ["resto", "rest"],
 ["houve", "there was"],
 ["pior", "worse"],
 ["esteja", "is"],
 ["esposa", "wife"],
 ["natal", "Christmas"],
 ["mr", "mr"],
 ["continuar", "continue"],
 ["quis", "wanted"],
 ["veja", "look"],
 ["dez", "ten"],
 ["bonito", "pretty"],
 ["precisas", "accurate"],
 ["ponto", "score"],
 ["cão", "dog"],
 ["visto", "visa"],
 ["médico", "doctor"],
 ["estavas", "wast"],
 ["estive", "I have been"],
 ["criança", "kid"],
 ["vim", "I came"],
 ["louco", "crazy"],
 ["raios", "rays"],
 ["queremos", "we want"],
 ["amo", "master"],
 ["devem", "should"],
 ["beber", "drink"],
 ["agente", "agent"],
 ["seguir", "follow"],
 ["negócio", "business"],
 ["alto", "high"],
 ["irá", "will"],
 ["gostava", "I liked"],
 ["las", "them"],
 ["último", "last"],
 ["modo", "mode"],
 ["oi", "hi"],
 ["demasiado", "too"],
 ["haver", "be"],
 ["sentido", "sense"],
 ["bonita", "beautiful"],
 ["chamar", "to call"],
 ["acontece", "it happens"],
 ["senhores", "gentlemen"],
 ["lindo", "pretty"],
 ["boas", "good"],
 ["comprar", "purchase"],
 ["matou", "killed"],
 ["sol", "Sun"],
 ["devemos", "we must"],
 ["vosso", "your"],
 ["entra", "goes into"],
 ["vês", "you see"],
 ["falando", "speaking"],
 ["consegues", "can you"],
 ["cedo", "early"],
 ["chama", "flame"],
 ["tom", "tone"],
 ["entendo", "I understand"],
 ["frank", "frank"],
 ["viste", "you saw"],
 ["esteve", "was"],
 ["livre", "free"],
 ["prisão", "prison"],
 ["viagem", "trip"],
 ["doutor", "doctor"],
 ["palavras", "words"],
 ["querer", "want"],
 ["sistema", "system"],
 ["tio", "uncle"],
 ["oportunidade", "opportunity"],
 ["campo", "field"],
 ["banho", "shower"],
 ["novamente", "again"],
 ["seguro", "safe"],
 ["pôr", "per"],
 ["próximo", "next"],
 ["conhece", "knows"],
 ["preocupes", "worry"],
 ["vontade", "will"],
 ["sexo", "sex"],
 ["sob", "under"],
 ["mortos", "dead"],
 ["barco", "boat"],
 ["adoro", "love"],
 ["respeito", "respect"],
 ["grupo", "group"],
 ["professor", "teacher"],
 ["descobrir", "to discover"],
 ["cabelo", "hair"],
 ["chão", "floor"],
 ["fazemos", "We do"],
 ["certa", "certain"],
 ["ligar", "turn on"],
 ["manter", "keep"],
 ["perfeito", "perfect"],
 ["miúdo", "kid"],
 ["terá", "will have"],
 ["capaz", "able"],
 ["portanto", "therefore"],
 ["situação", "situation"],
 ["arranjar", "get"],
 ["avião", "airplane"],
 ["começou", "started"],
 ["simples", "simple"],
 ["finalmente", "finally"],
 ["ordem", "order"],
 ["futuro", "future"],
 ["própria", "own"],
 ["dessa", "of that"],
 ["bebé", "baby"],
 ["george", "george"],
 ["connosco", "us"],
 ["linha", "line"],
 ["deves", "must"],
 ["sítio", "site"],
 ["encontro", "meeting"],
 ["vista", "view"],
 ["saia", "skirt"],
 ["charlie", "charlie"],
 ["questão", "question"],
 ["gostas", "like"],
 ["precisar", "need"],
 ["achei", "I found"],
 ["david", "david"],
 ["sinal", "signal"],
 ["desse", "of this"],
 ["deixou", "left"],
 ["aonde", "where"],
 ["emprego", "job"],
 ["completamente", "completely"],
 ["sam", "sam"],
 ["dê", "in"],
 ["local", "local"],
 ["vale", "Valley"],
 ["droga", "damn it"],
 ["perguntar", "to ask"],
 ["creio", "I think"],
 ["idade", "age"],
 ["pelas", "by"],
 ["the", "the"],
 ["nisto", "on this"],
 ["estávamos", "we were"],
 ["bocado", "bit"],
 ["casar", "marry"],
 ["nessa", "in that"],
 ["lutar", "fight"],
 ["hey", "hey"],
 ["carta", "letter"],
 ["apanhar", "take"],
 ["leva", "takes"],
 ["peço", "I ask"],
 ["pensas", "think"],
 ["jeito", "way"],
 ["fundo", "bottom"],
 ["tinham", "they had"],
 ["céu", "sky"],
 ["mesa", "table"],
 ["assunto", "subject matter"],
 ["fome", "hunger"],
 ["exército", "army"],
 ["ler", "read"],
 ["roupa", "clothing"],
 ["perguntas", "questions"],
 ["nesse", "in that"],
 ["sonho", "dream"],
 ["gajo", "dude"],
 ["amiga", "friend"],
 ["notícias", "news"],
 ["miúda", "girl"],
 ["quiseres", "want"],
 ["interessa", "interest"],
 ["doente", "sick"],
 ["governo", "government"],
 ["conhecer", "to know"],
 ["estúpido", "stupid"],
 ["estiver", "is"],
 ["melhores", "best"],
 ["bons", "good"],
 ["daí", "so"],
 ["faria", "would make"],
 ["mostrar", "show"],
 ["joe", "joe"],
 ["pegar", "take"],
 ["fiquei", "I stayed"],
 ["tipos", "types"],
 ["estrada", "road"],
 ["banco", "bank"],
 ["verdadeiro", "true"],
 ["povo", "people"],
 ["sozinha", "alone"],
 ["escritório", "office"],
 ["tocar", "touch"],
 ["sete", "seven"],
 ["indo", "going"],
 ["engraçado", "funny"],
 ["iria", "would go"],
 ["nele", "in him"],
 ["lei", "law"],
 ["padre", "priest"],
 ["trouxe", "brought"],
 ["fizeram", "made"],
 ["dito", "said"],
 ["tá", "OK"],
 ["simplesmente", "simply"],
 ["tratar", "treat"],
 ["programa", "program"],
 ["diabo", "devil"],
 ["mente", "mind"],
 ["serviço", "service"],
 ["voz", "voice"],
 ["acredita", "believes"],
 ["encontrei", "found it"],
 ["presente", "gift"],
 ["após", "after"],
 ["resposta", "answer"],
 ["mensagem", "message"],
 ["fugir", "to run away"],
 ["quantos", "how many"],
 ["quente", "hot"],
 ["companhia", "company"],
 ["chamada", "call"],
 ["volto", "back"],
 ["mike", "mike"],
 ["facto", "fact that"],
 ["conversa", "conversation"],
 ["mamã", "mom"],
 ["através", "through"],
 ["acabei", "I have finished"],
 ["tinhas", "you had"],
 ["consegui", "I got it"],
 ["olhem", "look"],
 ["normal", "normal"],
 ["espaço", "space"],
 ["escrever", "write"],
 ["senhoras", "ladies"],
 ["incrível", "incredible"],
 ["dizes", "say"],
 ["viva", "alive"],
 ["bela", "beautiful"],
 ["esquerda", "left"],
 ["breve", "short"],
 ["preso", "stuck"],
 ["abrir", "open"],
 ["procurar", "search for"],
 ["preocupe", "worry"],
 ["faças", "do"],
 ["feira", "market"],
 ["direita", "right"],
 ["inferno", "hell"],
 ["gostar", "to like"],
 ["ataque", "attack"],
 ["acidente", "accident"],
 ["cabo", "cable"],
 ["saiu", "exited"],
 ["idéia", "idea"],
 ["fixe", "cool"],
 ["assassino", "killer"],
 ["tempos", "time"],
 ["segundos", "the 2nd"],
 ["estivesse", "was"],
 ["costas", "back"],
 ["graças", "thanks"],
 ["olho", "eye"],
 ["mar", "sea"],
 ["papel", "paper"],
 ["chamado", "called"],
 ["fomos", "we"],
 ["salvar", "to save"],
 ["ambos", "both"],
 ["dor", "pain"],
 ["frio", "cold"],
 ["esperem", "expect"],
 ["missão", "mission"],
 ["diabos", "hell"],
 ["pensava", "thought"],
 ["ouça", "listen"],
 ["pés", "foot"],
 ["imediatamente", "immediately"],
 ["cair", "fall"],
 ["ouro", "gold"],
 ["tenente", "lieutenant"],
 ["escuta", "listening"],
 ["chave", "key"],
 ["mês", "month"],
 ["luta", "fight"],
 ["crime", "crime"],
 ["bebida", "beverage"],
 ["maldito", "damn you"],
 ["venham", "will"],
 ["ora", "now"],
 ["centro", "center"],
 ["bola", "ball"],
 ["ótimo", "great"],
 ["sente", "feels"],
 ["cavalo", "horse"],
 ["lembro", "I remember"],
 ["fantástico", "fantastic"],
 ["norte", "north"],
 ["velha", "old woman"],
 ["parabéns", "congratulations"],
 ["guarda", "guard"],
 ["caixa", "cashier"],
 ["aposto", "bet"],
 ["segunda", "Monday"],
 ["relação", "relationship"],
 ["disseram", "they said"],
 ["coronel", "colonel"],
 ["excelente", "great"],
 ["conseguiu", "got"],
 ["trazer", "bring"],
 ["metade", "half"],
 ["menino", "boy"],
 ["sendo", "being"],
 ["alma", "soul"],
 ["juro", "swear"],
 ["má", "bad"],
 ["loja", "store"],
 ["estará", "will be"],
 ["parem", "stop"],
 ["almoço", "lunch"],
 ["advogado", "lawyer"],
 ["sul", "south"],
 ["mestre", "master"],
 ["cheio", "full"],
 ["surpresa", "surprise"],
 ["garota", "girl"],
 ["lista", "list"],
 ["abre", "opens"],
 ["acerca", "about"],
 ["ordens", "instructions"],
 ["oito", "eight"],
 ["morta", "dead"],
 ["paul", "paul"],
 ["erro", "error"],
 ["namorada", "girlfriend"],
 ["começa", "begins"],
 ["américa", "America"],
 ["pobre", "poor"],
 ["dançar", "to dance"],
 ["fazia", "was"],
 ["saiam", "leave"],
 ["carne", "beef"],
 ["cena", "scene"],
 ["falou", "said"],
 ["impossível", "impossible"],
 ["conversar", "talk"],
 ["escolha", "choice"],
 ["informação", "information"],
 ["animais", "animals"],
 ["interessante", "interesting"],
 ["posição", "position"],
 ["branco", "white"],
 ["legal", "cool"],
 ["rio", "river"],
 ["voltou", "came back"],
 ["digas", "tell"],
 ["realidade", "reality"],
 ["belo", "beautiful"],
 ["devíamos", "should"],
 ["tiro", "shot"],
 ["comandante", "commander"],
 ["aprender", "learn"],
 ["dizendo", "saying"],
 ["prova", "test"],
 ["harry", "harry"],
 ["soube", "I knew"],
 ["ouviu", "heard"],
 ["negócios", "business"],
 ["vestido", "dress"],
 ["sargento", "sergeant"],
 ["destino", "destiny"],
 ["tivemos", "we had"],
 ["abaixo", "below"],
 ["hei", "hei"],
 ["honra", "honor"],
 ["energia", "energy"],
 ["falo", "I speak"],
 ["fizemos", "we did"],
 ["igreja", "church"],
 ["trabalha", "works"],
 ["passo", "step"],
 ["ben", "ben"],
 ["vidas", "lives"],
 ["funciona", "it works"],
 ["falei", "I spoke"],
 ["liberdade", "freedom"],
 ["socorro", "help"],
 ["vêm", "comes"],
 ["vive", "lives"],
 ["parecia", "It looked"],
 ["cerca", "about"],
 ["esquece", "forgets"],
 ["tenham", "have"],
 ["conseguimos", "we can"],
 ["câmara", "chamber"],
 ["papai", "dad"],
 ["bar", "Pub"],
 ["tira", "strip"],
 ["horrível", "horrible"],
 ["pá", "Pan"],
 ["segredo", "secret"],
 ["maravilhoso", "wonderful"],
 ["cerveja", "beer"],
 ["precisam", "need"],
 ["divertido", "funny"],
 ["naquela", "at that"],
 ["basta", "enough"],
 ["ouviste", "heard"],
 ["reunião", "meeting"],
 ["contente", "happy"],
 ["volte", "come back"],
 ["regras", "rules"],
 ["miúdos", "kids"],
 ["peter", "peter"],
 ["planeta", "planet"],
 ["triste", "sad"],
 ["piada", "joke"],
 ["ihe", "ihe"],
 ["vejam", "see"],
 ["entender", "understand"],
 ["prometo", "promise"],
 ["passada", "last"],
 ["jimmy", "jimmy"],
 ["aniversário", "birthday"],
 ["pudesse", "could"],
 ["exemplo", "example"],
 ["tiver", "have"],
 ["eras", "ages"],
 ["acaba", "ends"],
 ["perdi", "I've lost"],
 ["tenta", "try"],
 ["fato", "fact"],
 ["debaixo", "under"],
 ["sejas", "thou be"],
 ["prontos", "ready"],
 ["tentei", "I tried"],
 ["serão", "will be"],
 ["explicar", "explain"],
 ["americano", "American"],
 ["avó", "grandfather"],
 ["levou", "it took"],
 ["meia", "sock"],
 ["totalmente", "totally"],
 ["delas", "from them"],
 ["receber", "to receive"],
 ["perigo", "danger"],
 ["saúde", "cheers"],
 ["máquina", "machine"],
 ["tentando", "trying"],
 ["namorado", "boyfriend"],
 ["diria", "would say"],
 ["conheci", "met"],
 ["cristo", "Christ"],
 ["quantas", "how many"],
 ["tínhamos", "we had"],
 ["saída", "output"],
 ["tenhas", "you've"],
 ["maioria", "majority"],
 ["bater", "hit"],
 ["bolas", "balls"],
 ["apartamento", "apartment"],
 ["diferentes", "many different"],
 ["negro", "black"],
 ["podias", "you could"],
 ["estarei", "will be"],
 ["desejo", "wish"],
 ["perdeu", "lost"],
 ["garoto", "boy"],
 ["naquele", "that"],
 ["tanta", "so"],
 ["livros", "books"],
 ["năo", "no"],
 ["leve", "light"],
 ["diferença", "difference"],
 ["fale", "speak"],
 ["destes", "of these"],
 ["base", "base"],
 ["perceber", "to perceive"],
 ["humano", "human"],
 ["esquecer", "forget"],
 ["quais", "which are"],
 ["irei", "I will go"],
 ["terrível", "terrible"],
 ["mamãe", "mom"],
 ["duro", "hard"],
 ["mandar", "send"],
 ["janela", "window"],
 ["junto", "together"],
 ["vender", "sell"],
 ["ama", "love"],
 ["público", "public"],
 ["ás", "at"],
 ["nave", "nave"],
 ["sonhos", "dreams"],
 ["põe", "put"],
 ["tradução", "translation"],
 ["provas", "evidences"],
 ["entendido", "understood"],
 ["tribunal", "court"],
 ["monte", "hill"],
 ["meninas", "girls"],
 ["área", "area"],
 ["conheces", "know"],
 ["bomba", "bomb"],
 ["farei", "I will"],
 ["perigoso", "dangerous"],
 ["experiência", "experience"],
 ["bill", "bill"],
 ["acima", "above"],
 ["percebo", "I realize"],
 ["existem", "exist"],
 ["pernas", "legs"],
 ["lua", "moon"],
 ["graça", "grace"],
 ["acaso", "chance"],
 ["peça", "piece"],
 ["estaria", "would"],
 ["decisão", "decision"],
 ["odeio", "I hate"],
 ["par", "pair"],
 ["sabias", "knew"],
 ["pronta", "ready"],
 ["metros", "meters"],
 ["silêncio", "silence"],
 ["humanos", "humans"],
 ["seguinte", "following"],
 ["subir", "ride up"],
 ["devagar", "slowly"],
 ["espécie", "species"],
 ["clube", "club"],
 ["oficial", "official"],
 ["dei", "I gave"],
 ["percebi", "I noticed"],
 ["senão", "if no"],
 ["compreendo", "I understand"],
 ["verão", "summer"],
 ["enorme", "huge"],
 ["avô", "grandfather"],
 ["cérebro", "brain"],
 ["televisão", "television"],
 ["propósito", "purpose"],
 ["resolver", "solve"],
 ["últimos", "last"],
 ["inglês", "English"],
 ["esperança", "hope"],
 ["trata", "treats"],
 ["maluco", "crazy"],
 ["irmãos", "brothers"],
 ["apesar", "although"],
 ["dessas", "these"],
 ["poderá", "can"],
 ["contrário", "contrary"],
 ["rainha", "queen"],
 ["igual", "equal"],
 ["parecer", "seem"],
 ["suponho", "I suppose"],
 ["dúvida", "doubt"],
 ["achar", "find"],
 ["doce", "sweet"],
 ["danny", "danny"],
 ["ilha", "island"],
 ["repente", "suddenly"],
 ["conselho", "advice"],
 ["colocar", "put on"],
 ["aquelas", "those"],
 ["espírito", "spirit"],
 ["tome", "take"],
 ["corre", "run"],
 ["cartas", "cards"],
 ["raparigas", "girls"],
 ["vossos", "your"],
 ["encontrou", "found"],
 ["saco", "bag"],
 ["empresa", "company"],
 ["foto", "photograph"],
 ["loucura", "madness"],
 ["acham", "they find"],
 ["sejam", "are"],
 ["controlo", "control"],
 ["voce", "you"],
 ["pensando", "thinking"],
 ["azul", "blue"],
 ["comboio", "train"],
 ["vermelho", "red"],
 ["hipótese", "hypothesis"],
 ["destas", "these"],
 ["roupas", "clothes"],
 ["inteligente", "smart"],
 ["afinal", "after all"],
 ["estrela", "star"],
 ["filmes", "movies"],
 ["gelo", "ice"],
 ["principal", "main"],
 ["chá", "tea"],
 ["parecem", "look"],
 ["terminar", "finish"],
 ["motivo", "reason"],
 ["desculpem", "sorry"],
 ["soldados", "soldiers"],
 ["teres", "esters"],
 ["vinho", "wine"],
 ["americanos", "American"],
 ["longo", "long"],
 ["dizia", "said"],
 ["chorar", "cry"],
 ["universidade", "university"],
 ["certamente", "certainly"],
 ["usa", "uses"],
 ["perdido", "lost"],
 ["defesa", "defense"],
 ["buraco", "hole"],
 ["teste", "test"],
 ["preço", "price"],
 ["roubar", "to steal"],
 ["braço", "arm"],
 ["fotos", "photos"],
 ["inteiro", "all"],
 ["teremos", "will"],
 ["xerife", "sheriff"],
 ["comando", "command"],
 ["carros", "cars"],
 ["mentir", "to lie"],
 ["cantar", "sing"],
 ["cozinha", "kitchen"],
 ["porcaria", "filth"],
 ["zona", "zone"],
 ["lembrar", "remember"],
 ["desapareceu", "disappeared"],
 ["toca", "burrow"],
 ["necessário", "required"],
 ["justo", "fair"],
 ["confiar", "trust"],
 ["nick", "nick"],
 ["façam", "make"],
 ["coragem", "courage"],
 ["controle", "control"],
 ["vós", "you"],
 ["pareces", "seem"],
 ["entende", "you see"],
 ["nove", "nine"],
 ["traz", "brings"],
 ["proteger", "protect"],
 ["aparecer", "appear"],
 ["fiquem", "becomes"],
 ["inimigo", "enemy"],
 ["pele", "skin"],
 ["percebes", "barnacles"],
 ["contas", "accounts"],
 ["tia", "aunt"],
 ["deixei", "I left"],
 ["saiba", "know"],
 ["voar", "fly"],
 ["nível", "level"],
 ["desses", "these"],
 ["lixo", "trash"],
 ["tentou", "he tried"],
 ["beleza", "beauty"],
 ["suposto", "supposed"],
 ["srta", "MS"],
 ["preparar", "prepare"],
 ["noites", "nights"],
 ["dança", "dance"],
 ["sapatos", "shoes"],
 ["cuidar", "take care"],
 ["soldado", "soldier"],
 ["gostei", "liked it"],
 ["novos", "new"],
 ["come", "eats"],
 ["segura", "secure"],
 ["lembra", "remember"],
 ["entrada", "input"],
 ["entrou", "came in"],
 ["arte", "art"],
 ["peixe", "fish"],
 ["pense", "think"],
 ["chance", "chance"],
 ["cheia", "flood"],
 ["opinião", "opinion"],
 ["podíamos", "could"],
 ["rabo", "tail"],
 ["serei", "will be"],
 ["senti", "felt"],
 ["alta", "high"],
 ["esperando", "waiting"],
 ["aceitar", "accept"],
 ["som", "sound"],
 ["querias", "wanted"],
 ["ficam", "are"],
 ["ficas", "you stay"],
 ["pega", "catch"],
 ["férias", "vacation"],
 ["esqueça", "forget"],
 ["exatamente", "exactly"],
 ["precisava", "needed"],
 ["cabrão", "bastard"],
 ["nela", "it"],
 ["animal", "animal"],
 ["pediu", "asked"],
 ["planos", "plans"],
 ["sarah", "sarah"],
 ["cheiro", "smell"],
 ["herói", "hero"],
 ["acontecendo", "going"],
 ["funcionar", "function"],
 ["passei", "I spent"],
 ["código", "code"],
 ["perna", "leg"],
 ["londres", "London"],
 ["drogas", "drugs"],
 ["queira", "want"],
 ["unidos", "United"],
 ["lugares", "places"],
 ["perdão", "pardon"],
 ["vossas", "yours"],
 ["estiveste", "you were"],
 ["dentes", "teeth"],
 ["contacto", "contact"],
 ["viram", "seen"],
 ["ideias", "ideas"],
 ["espectáculo", "show"],
 ["novas", "new"],
 ["provar", "prove"],
 ["nariz", "nose"],
 ["vergonha", "shame"],
 ["criar", "create"],
 ["chaves", "keys"],
 ["estados", "states"],
 ["estrelas", "stars"],
 ["louca", "crazy"],
 ["fará", "will make"],
 ["natureza", "nature"],
 ["vens", "come"],
 ["cliente", "client"],
 ["ocupado", "occupied"],
 ["iorque", "york"],
 ["jovens", "young"],
 ["começo", "beginning"],
 ["estação", "station"],
 ["vendo", "seeing"],
 ["preto", "black"],
 ["preocupado", "worried"],
 ["dum", "of a"],
 ["mudou", "has changed"],
 ["liga", "turns on"],
 ["caras", "faces"],
 ["copo", "cup"],
 ["cor", "color"],
 ["tamanho", "size"],
 ["cu", "ass"],
 ["caiu", "dropped down"],
 ["princesa", "princess"],
 ["pedra", "stone"],
 ["corrida", "running"],
 ["nomes", "names"],
 ["fé", "faith"],
 ["branca", "white"],
 ["escute", "listen"],
 ["monstro", "monster"],
 ["época", "time"],
 ["brilhante", "bright"],
 ["ficará", "will"],
 ["terei", "I will have"],
 ["direcção", "direction"],
 ["daquele", "that"],
 ["vento", "wind"],
 ["dou", "I give"],
 ["haverá", "there will be"],
 ["casaco", "coat"],
 ["chamas", "flames"],
 ["início", "start"],
 ["cansado", "tired out"],
 ["mala", "suitcase"],
 ["tiveste", "you had"],
 ["árvore", "tree"],
 ["mentira", "lie"],
 ["batalha", "battle"],
 ["continue", "continues"],
 ["pegue", "take it"],
 ["esperava", "expected"],
 ["serve", "it suits"],
 ["rico", "rich"],
 ["charles", "charles"],
 ["dado", "given away"],
 ["eua", "USA"],
 ["verdadeira", "real"],
 ["cheguei", "I arrived"],
 ["costumava", "I used to"],
 ["majestade", "majesty"],
 ["tente", "try"],
 ["ido", "gone"],
 ["sucesso", "success"],
 ["céus", "heavens"],
 ["pedido", "order"],
 ["alvo", "target"],
 ["rosto", "face"],
 ["termos", "terms"],
 ["classe", "class"],
 ["cães", "dogs"],
 ["velocidade", "velocity"],
 ["saudades", "miss you"],
 ["forças", "forces"],
 ["santo", "holy"],
 ["canção", "song"],
 ["calças", "pants"],
 ["cabra", "goat"],
 ["pensam", "think"],
 ["departamento", "department"],
 ["maldita", "damn"],
 ["limpar", "to clean"],
 ["cartão", "card"],
 ["relatório", "report"],
 ["navio", "ship"],
 ["velhos", "old"],
 ["barulho", "noise"],
 ["flores", "flowers"],
 ["ê", "and"],
 ["steve", "steve"],
 ["detective", "detective"],
 ["visita", "visit"],
 ["lidar", "to deal"],
 ["atrasado", "late"],
 ["pedi", "I asked"],
 ["gato", "cat"],
 ["emergência", "emergency"],
 ["disparar", "shoot"],
 ["parede", "wall"],
 ["operação", "operation"],
 ["jamais", "never"],
 ["tornar", "become"],
 ["longa", "long"],
 ["milhares", "thousands"],
 ["cavalheiros", "gentlemen"],
 ["absolutamente", "absolutely"],
 ["sentes", "feel"],
 ["lsso", "that"],
 ["gostam", "like"],
 ["vimos", "saw"],
 ["destruir", "to destroy"],
 ["beijo", "kiss"],
 ["risco", "risk"],
 ["preparado", "prepared"],
 ["seres", "beings"],
 ["ha", "there is"],
 ["comum", "common"],
 ["computador", "computer"],
 ["cavalos", "horses"],
 ["falamos", "speak"],
 ["restaurante", "restaurant"],
 ["cinema", "movie theater"],
 ["prefiro", "I prefer"],
 ["responsável", "responsible"],
 ["vinte", "twenty"],
 ["jornal", "newspaper"],
 ["li", "I read"],
 ["descer", "go down"],
 ["esperto", "clever"],
 ["esconder", "to hide"],
 ["daquela", "that"],
 ["somente", "only"],
 ["movimento", "movement"],
 ["caro", "expensive"],
 ["pista", "track"],
 ["porco", "pig"],
 ["doido", "crazy"],
 ["rir", "laugh"],
 ["praia", "beach"],
 ["estilo", "style"],
 ["acção", "action"],
 ["ajude", "help"],
 ["cortar", "cut"],
 ["escolher", "to choose"],
 ["maldição", "curse"],
 ["vieram", "they came"],
 ["imaginar", "to imagine"],
 ["irão", "will"],
 ["luzes", "lights"],
 ["histórias", "stories"],
 ["abra", "open it"],
 ["língua", "language"],
 ["distância", "distance"],
 ["fechar", "close"],
 ["evitar", "avoid"],
 ["príncipe", "prince"],
 ["total", "total"],
 ["errada", "wrong"],
 ["conhecido", "known"],
 ["toque", "touch"],
 ["discutir", "to discuss"],
 ["juiz", "judge"],
 ["pressão", "pressure"],
 ["informações", "information"],
 ["especialmente", "especially"],
 ["estranha", "strange"],
 ["cadeia", "jail"],
 ["banda", "band"],
 ["devido", "due"],
 ["justiça", "justice"],
 ["verde", "green"],
 ["puder", "can"],
 ["quieto", "quiet"],
 ["milhão", "million"],
 ["duma", "of"],
 ["pescoço", "neck"],
 ["mandou", "sent"],
 ["imagem", "image"],
 ["conhecemos", "we know"],
 ["memória", "memory"],
 ["ponte", "bridge"],
 ["máximo", "maximum"],
 ["meninos", "boys"],
 ["futebol", "soccer"],
 ["responder", "answer"],
 ["desculpas", "apologies"],
 ["braços", "arms"],
 ["deixes", "leave"],
 ["agradável", "nice"],
 ["porreiro", "cool"],
 ["manda", "sends"],
 ["ligação", "link"],
 ["tchau", "bye"],
 ["oeste", "west"],
 ["venho", "I come"],
 ["alô", "hello"],
 ["ó", "the"],
 ["pago", "paid out"],
 ["nervoso", "nervous"],
 ["vindos", "coming"],
 ["sociedade", "society"],
 ["calor", "heat"],
 ["falas", "words"],
 ["confiança", "confidence"],
 ["noiva", "bride"],
 ["relógio", "clock"],
 ["casas", "houses"],
 ["edifício", "building"],
 ["casado", "married"],
 ["parque", "park"],
 ["nacional", "national"],
 ["ridículo", "ridiculous"],
 ["fotografia", "photography"],
 ["washington", "washington"],
 ["espada", "sword"],
 ["felizes", "happy"],
 ["partido", "broken"],
 ["pequenos", "small"],
 ["tire", "remove"],
 ["humana", "human"],
 ["valor", "value"],
 ["levantar", "rise"],
 ["aula", "class"],
 ["tido", "had"],
 ["meter", "put"],
 ["caramba", "damn it"],
 ["morre", "dies"],
 ["autocarro", "bus"],
 ["inglaterra", "England"],
 ["diante", "against"],
 ["central", "central"],
 ["iremos", "we will"],
 ["cadeira", "chair"],
 ["chapéu", "hat"],
 ["idiotas", "idiots"],
 ["pontos", "points"],
 ["serem", "being"],
 ["deviam", "should"],
 ["trato", "tract"],
 ["faca", "knife"],
 ["ligou", "called"],
 ["andando", "walking"],
 ["acorda", "wake up"],
 ["investigação", "investigation"],
 ["ponha", "put"],
 ["calhar", "handy"],
 ["processo", "process"],
 ["imenso", "immense"],
 ["apareceu", "appeared"],
 ["sentado", "seated"],
 ["escuro", "dark"],
 ["uau", "wow"],
 ["posto", "post"],
 ["comecei", "started"],
 ["aulas", "classes"],
 ["inteira", "entire"],
 ["dados", "dice"],
 ["acabado", "finished"],
 ["corte", "cut"],
 ["baixa", "low"],
 ["treinador", "coach"],
 ["limpo", "clean"],
 ["voo", "flight"],
 ["várias", "various"],
 ["combate", "combat"],
 ["conduzir", "drive"],
 ["gritar", "shout out"],
 ["deixem", "leave"],
 ["atirar", "shoot"],
 ["ficamos", "we"],
 ["portas", "doors"],
 ["carreira", "career"],
 ["perdemos", "we lost"],
 ["descansar", "rest"],
 ["leite", "milk"],
 ["bordo", "maple"],
 ["simpático", "nice"],
 ["chuva", "rain"],
 ["fumar", "smoke"],
 ["faremos", "we will"],
 ["visão", "eyesight"],
 ["ouvido", "heard"],
 ["ruas", "streets"],
 ["policia", "police"],
 ["pensou", "thought"],
 ["política", "policy"],
 ["universo", "universe"],
 ["tantas", "many"],
 ["líder", "leader"],
 ["mapa", "map"],
 ["conseguia", "could"],
 ["normalmente", "normally"],
 ["dono", "owner"],
 ["gozar", "enjoy"],
 ["mercado", "market"],
 ["uso", "use"],
 ["salvo", "saved"],
 ["dedos", "fingers"],
 ["infelizmente", "unfortunately"],
 ["jogos", "games"],
 ["troca", "exchange"],
 ["inocente", "innocent"],
 ["militar", "military"],
 ["aspecto", "aspect"],
 ["escapar", "escape"],
 ["entendi", "understand"],
 ["bebê", "baby"],
 ["vieste", "you came"],
 ["conseguiste", "did you get"],
 ["série", "series"],
 ["apoio", "support"],
 ["matei", "killed"],
 ["clientes", "customers"],
 ["orgulho", "proud"],
 ["éramos", "we were"],
 ["verificar", "check"],
 ["conseguem", "can"],
 ["vêem", "see"],
 ["vemos", "we see"],
 ["números", "numbers"],
 ["julgamento", "judgment"],
 ["terem", "have"],
 ["depende", "It depends"],
 ["respirar", "breathe"],
 ["teoria", "theory"],
 ["larga", "wide"],
 ["laboratório", "laboratory"],
 ["larry", "larry"],
 ["correcto", "correct"],
 ["rapidamente", "quickly"],
 ["mudança", "change"],
 ["faculdade", "college"],
 ["pedaço", "piece"],
 ["rosa", "pink"],
 ["maiores", "higher"],
 ["sacana", "bastard"],
 ["tiveram", "they had"],
 ["preocupar", "bother"],
 ["anel", "ring"],
 ["patrão", "boss"],
 ["vítima", "victim"],
 ["encontramos", "found"],
 ["grávida", "pregnant"],
 ["entanto", "however"],
 ["bebe", "baby"],
 ["confusão", "confusion"],
 ["terceiro", "third"],
 ["andy", "andy"],
 ["busca", "search"],
 ["lago", "lake"],
 ["possamos", "can"],
 ["procurando", "searching"],
 ["escrito", "written"],
 ["frança", "France"],
 ["vários", "several"],
 ["pude", "I could"],
 ["corpos", "bodies"],
 ["escreveu", "wrote"],
 ["montanha", "mountain"],
 ["aeroporto", "airport"],
 ["estúpida", "stupid"],
 ["mata", "woods"],
 ["andado", "been"],
 ["miúdas", "girls"],
 ["passe", "pass"],
 ["sobreviver", "survive"],
 ["bala", "bullet"],
 ["prestes", "ready"],
 ["dever", "to owe"],
 ["excepto", "except"],
 ["pressa", "hurry"],
 ["suspeito", "suspect"],
 ["marca", "brand"],
 ["poucos", "few"],
 ["brian", "brian"],
 ["director", "director"],
 ["acreditas", "believe"],
 ["controlar", "to control"],
 ["antigo", "old"],
 ["interesse", "interest"],
 ["mexer", "stir"],
 ["unidade", "unity"],
 ["chame", "call"],
 ["material", "material"],
 ["perfeita", "perfect"],
 ["construir", "ramp up"],
 ["notícia", "news"],
 ["telemóvel", "phone"],
 ["correu", "ran"],
 ["apresentar", "to present"],
 ["ouçam", "listen"],
 ["carrinha", "van"],
 ["más", "but"],
 ["acordar", "wake up"],
 ["floresta", "forest"],
 ["ando", "walk"],
 ["costa", "coast"],
 ["amar", "love"],
 ["geral", "general"],
 ["dedo", "finger"],
 ["sentimentos", "feelings"],
 ["parceiro", "partner"],
 ["bolsa", "handbag"],
 ["profissional", "professional"],
 ["merdas", "shits"],
 ["morreram", "died"],
 ["encontrado", "found"],
 ["feita", "done"],
 ["doença", "disease"],
 ["mostra", "show"],
 ["martin", "martin"],
 ["crescer", "grow up"],
 ["imbecil", "asshole"],
 ["ferido", "injured"],
 ["leste", "east"],
 ["regressar", "return"],
 ["queiras", "wanna"],
 ["neve", "snow"],
 ["peso", "Weight"],
 ["baile", "prom"],
 ["sentar", "to sit"],
 ["mundial", "worldwide"],
 ["médicos", "doctors"],
 ["dão", "give"],
 ["judeus", "Jews"],
 ["contou", "said"],
 ["campeão", "champion"],
 ["ovos", "eggs"],
 ["importo", "care"],
 ["servir", "serve"],
 ["óptima", "great"],
 ["garrafa", "bottle"],
 ["momentos", "moments"],
 ["deseja", "want"],
 ["agentes", "agents"],
 ["imprensa", "press"],
 ["aberta", "opening"],
 ["quão", "how"],
 ["recebi", "I received"],
 ["ganhou", "has won"],
 ["mano", "bro"],
 ["maravilhosa", "wonderful"],
 ["atacar", "attack"],
 ["desistir", "give up"],
 ["aldeia", "village"],
 ["parecido", "like"],
 ["entregar", "deliver"],
 ["disser", "says"],
 ["rock", "rock"],
 ["partida", "match"],
 ["acesso", "access"],
 ["tantos", "many"],
 ["decidir", "decide"],
 ["homicídio", "murder"],
 ["entendes", "understand"],
 ["chamam", "call"],
 ["instante", "moment"],
 ["vivos", "living"],
 ["soubesse", "knew"],
 ["deixado", "left"],
 ["obviamente", "obviously"],
 ["chegaram", "they arrived"],
 ["viemos", "we came"],
 ["culpado", "guilty"],
 ["resultado", "result"],
 ["direitos", "rights"],
 ["desaparece", "fades away"],
 ["jardim", "garden"],
 ["deserto", "desert"],
 ["nâo", "no"],
 ["ficaria", "would"],
 ["ruim", "bad"],
 ["paga", "pay"],
 ["próprios", "own"],
 ["lixar", "sanding"],
 ["interessado", "interested"],
 ["ouvidos", "ears"],
 ["fantasma", "ghost"],
 ["estudar", "to study"],
 ["domingo", "Sunday"],
 ["entrem", "enter"],
 ["oferta", "offer"],
 ["notas", "grades"],
 ["contrato", "contract"],
 ["encontraram", "found"],
 ["brincadeira", "just kidding"],
 ["sábado", "Saturday"],
 ["tempestade", "storm"],
 ["bolo", "cake"],
 ["lar", "home"],
 ["gabinete", "cabinet"],
 ["colega", "classmate"],
 ["companheiro", "companion"],
 ["demorar", "delay"],
 ["gás", "gas"],
 ["agradecer", "to thank"],
 ["thomas", "thomas"],
 ["data", "date"],
 ["tendo", "by having"],
 ["fizer", "do"],
 ["bêbado", "drunk"],
 ["estaremos", "will be"],
 ["acredite", "believe"],
 ["enviar", "submit"],
 ["bilhete", "ticket"],
 ["pessoalmente", "in person"],
 ["reino", "kingdom"],
 ["propriedade", "property"],
 ["ministro", "minister"],
 ["entendeu", "understood"],
 ["aparece", "pops up"],
 ["receio", "fear"],
 ["visitar", "visit"],
 ["crer", "believe"],
 ["daqueles", "those"],
 ["francês", "French"],
 ["viajar", "travel"],
 ["recuperar", "to recover"],
 ["responsabilidade", "responsibility"],
 ["voltas", "turns"],
 ["mel", "honey"],
 ["carl", "carl"],
 ["alemães", "German"],
 ["garotas", "girls"],
 ["pro", "pro"],
 ["testemunha", "witness"],
 ["equipe", "team"],
 ["simon", "simon"],
 ["queriam", "they wanted"],
 ["pão", "bread"],
 ["pequenas", "small"],
 ["califórnia", "California"],
 ["senhorita", "Ms"],
 ["conhecimento", "knowledge"],
 ["primo", "cousin"],
 ["europa", "Europe"],
 ["méxico", "Mexico"],
 ["peito", "chest"],
 ["fugiu", "ran away"],
 ["sensação", "sensation"],
 ["william", "william"],
 ["poderoso", "powerful"],
 ["podiam", "could"],
 ["centenas", "hundreds"],
 ["inimigos", "enemies"],
 ["hein", "huh"],
 ["ganha", "wins"],
 ["mantém", "keeps"],
 ["farto", "tired"],
 ["magia", "magic"],
 ["agradeço", "appreciate"],
 ["aberto", "open"],
 ["vitória", "victory"],
 ["achou", "found"],
 ["voltem", "return"],
 ["partes", "parts"],
 ["assassinato", "murder"],
 ["massa", "pasta"],
 ["fecha", "closes"],
 ["bravo", "angry"],
 ["ligue", "call"],
 ["ligado", "switched on"],
 ["boleia", "hitchhiking"],
 ["vinha", "came"],
 ["efeito", "It is made"] ];
