let romanian = [["de", "of"],
["nu", "not"],
["să", "to"],
["o", "a"],
["a", "of"],
["e", "e"],
["ce", "what the"],
["am", "I have"],
["şi", "and"],
["în", "into the"],
["la", "to"],
["că", "that"],
["pe", "on"],
["cu", "with"],
["un", "a"],
["mai", "May"],
["te", "yourself"],
["ai", "you"],
["asta", "to stay"],
["pentru", "for"],
["ca", "that"],
["sunt", "are"],
["da", "Yes"],
["bine", "good"],
["mă", "me"],
["este", "It is"],
["sa", "to"],
["se", "it"],
["dar", "but"],
["din", "from"],
["aici", "here"],
["care", "which"],
["i", "and"],
["eu", "I"],
["fi", "be"],
["si", "and"],
["fost", "former"],
["trebuie", "must"],
["ar", "would"],
["dacă", "if"],
["va", "will"],
["tu", "you"],
["cum", "How"],
["aşa", "so"],
["acum", "now"],
["mi", "mi"],
["au", "have"],
["eşti", "you"],
["ne", "us"],
["ceva", "something"],
["l", "it"],
["mine", "me"],
["tine", "you"],
["vă", "yourself"],
["doar", "just"],
["lui", "his"],
["când", "When"],
["in", "into the"],
["el", "he"],
["îmi", "I"],
["pot", "can"],
["cred", "I guess"],
["unde", "where"],
["poate", "may be"],
["voi", "you"],
["ei", "They"],
["mea", "my"],
["face", "do what"],
["ţi", "and"],
["ştiu", "know"],
["vreau", "I want"],
["meu", "my"],
["vrei", "want"],
["spus", "said"],
["acolo", "there"],
["tot", "all"],
["foarte", "very"],
["mult", "a lot"],
["le", "they"],
["bună", "Hi"],
["faci", "do"],
["sau", "or"],
["chiar", "even"],
["nici", "neither"],
["noi", "we"],
["nimic", "nothing"],
["pare", "seems"],
["era", "It was"],
["ta", "your"],
["despre", "about"],
["cine", "who"],
["are", "It has"],
["ea", "she"],
["ştii", "Know"],
["fac", "do"],
["ma", "me"],
["făcut", "made"],
["rog", "Please"],
["îţi", "you"],
["fie", "or"],
["putea", "can"],
["rău", "bad"],
["al", "of"],
["spun", "I say"],
["trebui", "have"],
["poţi", "You can"],
["haide", "Come on"],
["nevoie", "need"],
["atunci", "then"],
["avem", "we"],
["mulţumesc", "thank you"],
["prea", "too"],
["tău", "your"],
["aş", "I would"],
["spune", "say"],
["îl", "him"],
["timp", "time"],
["după", "after"],
["ani", "years"],
["cineva", "someone"],
["domnule", "mister"],
["vor", "will"],
["vom", "we will"],
["îi", "him"],
["hei", "Hey"],
["bun", "good"],
["vei", "you"],
["ăsta", "to stay"],
["vrea", "like"],
["oh", "Oh"],
["cel", "the"],
["stai", "stay"],
["toate", "all"],
["asa", "so"],
["mare", "big"],
["suntem", "we are"],
["sigur", "sure"],
["crezi", "believe"],
["esti", "you"],
["hai", "let's"],
["totul", "all"],
["până", "until"],
["venit", "income"],
["cât", "How"],
["iar", "and"],
["deci", "so"],
["spui", "say"],
["aţi", "you"],
["place", "like"],
["mergem", "Go"],
["avea", "have"],
["încă", "yet"],
["văzut", "seen"],
["daca", "if"],
["regulă", "rule"],
["naiba", "heck"],
["niciodată", "never"],
["atât", "so much"],
["mama", "mother"],
["acest", "this"],
["putem", "can"],
["fel", "kind"],
["fără", "free"],
["vezi", "see"],
["avut", "had"],
["uite", "look"],
["nimeni", "no one"],
["fii", "sons"],
["puţin", "little bit"],
["decât", "than"],
["văd", "I'm seeing"],
["aia", "that"],
["ia", "takes"],
["loc", "place"],
["jos", "down"],
["toţi", "all"],
["toată", "all"],
["unul", "one"],
["astea", "these"],
["prin", "through"],
["facem", "we make"],
["ti", "you"],
["ceea", "what"],
["lumea", "the world"],
["zi", "day"],
["oameni", "people"],
["lucru", "working"],
["înainte", "before"],
["dat", "given"],
["acasă", "the home"],
["apoi", "then"],
["nişte", "some"],
["întâmplat", "happened"],
["stiu", "know"],
["timpul", "time"],
["vino", "come over"],
["auzit", "heard"],
["doi", "two"],
["fiu", "son"],
["multe", "many"],
["nou", "new"],
["oamenii", "people"],
["fiecare", "every"],
["doamne", "gosh"],
["două", "two"],
["cei", "the"],
["om", "man"],
["orice", "anything"],
["dle", "Mr."],
["peste", "over"],
["duc", "lead"],
["numele", "name"],
["cea", "the"],
["trei", "three"],
["gata", "ready"],
["ok", "ok"],
["omule", "man"],
["înapoi", "back"],
["numai", "no more"],
["bani", "money"],
["luat", "taken"],
["repede", "quick"],
["viaţa", "life"],
["zis", "said"],
["lor", "their"],
["vedem", "see"],
["mele", "my"],
["merge", "go"],
["dau", "give"],
["ziua", "day"],
["vin", "wine"],
["grijă", "care"],
["una", "one"],
["parte", "part"],
["serios", "seriously"],
["vrut", "wanted"],
["afară", "outside"],
["vine", "it's coming"],
["vorbesc", "I'm talking"],
["noapte", "night"],
["fata", "face"],
["cam", "about"],
["dintre", "from"],
["eram", "we were"],
["imi", "I"],
["aproape", "close"],
["stii", "Know"],
["deja", "already"],
["dată", "date"],
["această", "This one"],
["sunteţi", "you"],
["casa", "House"],
["destul", "enough"],
["adevărat", "TRUE"],
["singur", "single"],
["iau", "I take"],
["locul", "the place"],
["cand", "When"],
["banii", "the money"],
["ori", "or"],
["spre", "to"],
["câteva", "some"],
["iubesc", "I love"],
["nostru", "our"],
["seara", "in the evening"],
["ăla", "that"],
["tale", "your"],
["prima", "first"],
["imediat", "immediate"],
["ajuns", "made"],
["dracu", "hell"],
["tatăl", "father"],
["înseamnă", "means"],
["tata", "father"],
["ştie", "know"],
["exact", "exact"],
["azi", "today"],
["găsit", "found"],
["aceasta", "This one"],
["scuze", "Sorry"],
["copii", "children"],
["drumul", "the road"],
["simt", "sense"],
["acesta", "this"],
["buna", "Hi"],
["poti", "You can"],
["treaba", "the job"],
["terminat", "finished"],
["partea", "the"],
["noastră", "Our"],
["dumnezeu", "God"],
["lucruri", "things"],
["întâmplă", "happen"],
["târziu", "Late"],
["plec", "I am leaving"],
["as", "I would"],
["trebuia", "had"],
["frumos", "beautiful"],
["sus", "up"],
["zile", "days"],
["mie", "thousand"],
["tocmai", "just"],
["multumesc", "thank you"],
["tată", "father"],
["mereu", "always"],
["dreptate", "justice"],
["aveţi", "you have"],
["adică", "namely"],
["mâine", "tomorrow"],
["putut", "could"],
["mei", "my"],
["fapt", "fact"],
["aşteaptă", "Wait"],
["tare", "loud"],
["dai", "you"],
["dumnezeule", "Dear good"],
["unui", "a"],
["plecat", "gone"],
["trecut", "last"],
["facă", "make"],
["probabil", "probable"],
["pierdut", "lost"],
["lucrurile", "the things"],
["măcar", "even"],
["mamă", "mother"],
["cele", "the"],
["dvs", "you"],
["păi", "Well"],
["departe", "far away"],
["sub", "under the"],
["început", "beginning"],
["viaţă", "life"],
["minute", "minutes"],
["împreună", "together"],
["există", "there is"],
["aceea", "that"],
["data", "date"],
["sper", "hope"],
["crezut", "thought"],
["ba", "nay"],
["minunat", "wonderful"],
["vreo", "some"],
["problema", "problem"],
["murit", "died"],
["duci", "go"],
["femeie", "woman"],
["vorba", "words"],
["facut", "made"],
["băieţi", "boys"],
["tipul", "type"],
["înţeleg", "I see"],
["erau", "They were"],
["ajutor", "help"],
["ale", "of"],
["merg", "go"],
["camera", "the room"],
["rau", "bad"],
["mort", "dead"],
["poftim", "here you go"],
["înţeles", "meaning"],
["greu", "hard"],
["vii", "are you coming"],
["iti", "you"],
["desigur", "Of course"],
["vorbeşti", "talk"],
["rahat", "bullshit"],
["ul", "the"],
["noaptea", "the night"],
["idee", "idea"],
["ati", "you"],
["griji", "worry"],
["vedea", "see"],
["trebuit", "had"],
["ultima", "last"],
["dus", "shower"],
["primul", "the first"],
["bune", "good"],
["îşi", "their"],
["aceste", "these"],
["ajunge", "that's enough"],
["întotdeauna", "ever"],
["noastre", "our"],
["ascultă", "listen"],
["iei", "take"],
["mergi", "go"],
["simţi", "feel"],
["copil", "child"],
["duce", "lead"],
["seama", "out"],
["tip", "type"],
["pus", "put"],
["cap", "head"],
["credeam", "I thought"],
["lume", "world"],
["ochii", "the eyes"],
["salut", "Hello"],
["oricum", "anyway"],
["probleme", "problems"],
["adus", "brought"],
["dl", "Mister"],
["ajuta", "it helps"],
["n", "n"],
["tau", "your"],
["maşina", "car"],
["cer", "heaven"],
["pune", "put"],
["faceţi", "do"],
["uitat", "forgotten"],
["zici", "about"],
["moment", "time"],
["cauza", "Cause"],
["dolari", "USD"],
["cunosc", "know"],
["dragă", "Dear"],
["pic", "bit"],
["faţă", "face"],
["alo", "Hello"],
["taci", "remain silent"],
["problemă", "problem"],
["lua", "take"],
["gândit", "thought"],
["vreodată", "ever"],
["faţa", "face"],
["odată", "once time"],
["ele", "they"],
["mulţi", "many"],
["ciudat", "strange"],
["ore", "hours"],
["viata", "life"],
["dupa", "after"],
["s", "s"],
["unei", "of a"],
["joc", "game"],
["veni", "come"],
["casă", "House"],
["luni", "months"],
["vorbim", "talk"],
["fată", "face"],
["între", "between"],
["pleacă", "leaves"],
["altceva", "something else"],
["grozav", "that's great"],
["maşină", "car"],
["fiul", "son"],
["crede", "believe"],
["il", "it"],
["puteţi", "you can"],
["prieten", "friend"],
["pleci", "leave"],
["uşor", "Easy"],
["prins", "caught"],
["omul", "the man"],
["corect", "correct"],
["cinci", "five"],
["telefon", "phone"],
["mâna", "hand"],
["patru", "four"],
["stau", "stay"],
["ora", "hour"],
["ales", "chosen"],
["bucur", "glad"],
["lângă", "by"],
["fratele", "brother"],
["doamnă", "Ms"],
["câte", "by"],
["doua", "two"],
["urmă", "follow"],
["familia", "the family"],
["pun", "put"],
["frumoasă", "beautiful"],
["domnul", "Mr"],
["pace", "peace"],
["auzi", "hear"],
["cale", "way"],
["înţelegi", "understand"],
["altă", "other"],
["vorbit", "spoken"],
["important", "important"],
["revedere", "revision"],
["aveam", "I used to have"],
["prieteni", "friends"],
["fă", "do"],
["singură", "one"],
["toti", "all"],
["siguranţă", "safety"],
["încercat", "tried"],
["inima", "heart"],
["capul", "head"],
["simplu", "simple"],
["putin", "little bit"],
["mersi", "thanks"],
["jack", "jack"],
["john", "john"],
["vina", "fault"],
["chestia", "the thing"],
["drum", "road"],
["spate", "back"],
["ii", "ii"],
["oraş", "Town"],
["lăsat", "dropped off"],
["mic", "little"],
["las", "coward"],
["ştiţi", "you know"],
["veţi", "will you"],
["bărbat", "man"],
["zic", "say"],
["acord", "agreement"],
["plecăm", "leave"],
["uita", "forget"],
["treabă", "the job"],
["noroc", "luck"],
["ieşi", "go out"],
["dimineaţa", "morning"],
["arată", "to miss"],
["încredere", "trust"],
["prietenul", "the friend"],
["frate", "brother"],
["nebun", "crazy"],
["plac", "liking"],
["pleca", "leave"],
["curând", "soon"],
["dr", "Dr."],
["ucis", "killed"],
["minte", "mind"],
["apă", "the water"],
["sã", "to"],
["vreţi", "want"],
["pasă", "pasha"],
["pui", "chicken"],
["singura", "one"],
["pa", "bye"],
["vorbi", "speak"],
["întorc", "return"],
["nouă", "nine"],
["soţia", "wife"],
["vazut", "seen"],
["mari", "big"],
["asemenea", "also"],
["primit", "received"],
["aduc", "bring"],
["deloc", "not at all"],
["alte", "other"],
["tăi", "thy"],
["ţine", "keep"],
["caz", "case"],
["parcă", "park"],
["întoarce", "turn"],
["încearcă", "try"],
["către", "by"],
["sta", "stay"],
["sunat", "call"],
["acel", "that"],
["nume", "name"],
["aud", "I hear"],
["spatele", "the back"],
["perfect", "perfect"],
["ajut", "help"],
["întors", "returned"],
["acela", "that"],
["niciodata", "never"],
["haideţi", "come on"],
["ştiam", "I knew"],
["rămâne", "remain"],
["întâmpla", "happen"],
["fara", "free"],
["buni", "Top"],
["naibii", "hell"],
["vreme", "times"],
["pana", "until"],
["domnilor", "gentlemen"],
["fericit", "happy"],
["singurul", "the only one"],
["contează", "counts"],
["astăzi", "today"],
["niste", "some"],
["an", "year"],
["draga", "Dear"],
["drăguţ", "cute"],
["începe", "you start"],
["ăştia", "these"],
["copiii", "the kids"],
["numărul", "number"],
["afara", "outside"],
["trimis", "sent"],
["erai", "you were"],
["doamna", "Ms"],
["the", "the"],
["nicio", "any"],
["abia", "only"],
["alt", "other"],
["încerc", "try"],
["urma", "follow"],
["înăuntru", "in"],
["prost", "dumbass"],
["gura", "the mouth"],
["lăsa", "leave"],
["găsi", "find"],
["alea", "those"],
["mâinile", "hands"],
["astfel", "so"],
["mică", "small"],
["vad", "I'm seeing"],
["cumva", "perhaps"],
["legătură", "link"],
["uşa", "door"],
["gândesc", "I think"],
["new", "new"],
["rămas", "remaining"],
["ştim", "we know"],
["copilul", "the child"],
["regula", "rule"],
["vreun", "any"],
["adevărul", "truth"],
["foc", "fire"],
["deschide", "open"],
["undeva", "somewhere"],
["sun", "call"],
["întreb", "I'm asking"],
["familie", "family"],
["zice", "say"],
["inca", "yet"],
["mod", "mode"],
["drept", "Right"],
["moarte", "death"],
["altfel", "otherwise"],
["toata", "all"],
["vină", "guilt"],
["oră", "hour"],
["arăţi", "show"],
["restul", "the rest"],
["cunoscut", "known"],
["jumătate", "half"],
["amintesc", "remember"],
["sora", "sister"],
["intrat", "entered"],
["devreme", "early"],
["jur", "around"],
["arma", "weapon"],
["cazul", "case"],
["fim", "be"],
["cheamă", "call"],
["cat", "How"],
["împotriva", "against"],
["ah", "Ah"],
["acea", "that"],
["luăm", "take"],
["frică", "fear"],
["lasă", "leave"],
["asupra", "on"],
["voastră", "your"],
["poliţia", "the police"],
["vrem", "we want"],
["dumneavoastră", "your"],
["milioane", "millions"],
["scris", "written"],
["întâi", "first"],
["găsesc", "I find"],
["unu", "one"],
["reuşit", "successful"],
["acelaşi", "same"],
["vadă", "will give"],
["amice", "pal"],
["mers", "walking"],
["amândoi", "both"],
["dă", "Yes"],
["fugi", "run"],
["sfârşit", "the end"],
["ultimul", "the last one"],
["vorbeşte", "speaks"],
["dimineaţă", "morning"],
["intră", "get in"],
["pat", "bed"],
["uit", "look"],
["fiica", "daughter"],
["exista", "there is"],
["posibil", "possible"],
["motiv", "reason"],
["apa", "the water"],
["dragoste", "love"],
["treci", "pass"],
["genul", "kind"],
["său", "or"],
["pământ", "earth"],
["băiat", "boy"],
["stat", "state"],
["gând", "thinking"],
["sună", "sounds"],
["femei", "women"],
["tuturor", "all"],
["ci", "but"],
["dracului", "hell"],
["aduce", "bring"],
["bineînţeles", "of course"],
["arăt", "show"],
["felul", "the kind"],
["prietenii", "friends"],
["trage", "shoot"],
["prietene", "friend"],
["multă", "much"],
["sunteti", "are"],
["sigură", "secure"],
["dea", "give"],
["ochi", "eyes"],
["film", "movie"],
["niciun", "none"],
["momentul", "time"],
["joe", "joe"],
["război", "war"],
["iubito", "baby"],
["omorât", "killed"],
["plăcere", "pleasure"],
["echipa", "team"],
["trece", "pass"],
["devenit", "became"],
["plăcut", "pleasant"],
["moartea", "the death"],
["şcoală", "school"],
["scrie", "write"],
["totuşi", "however"],
["ştiut", "knew"],
["acasa", "the home"],
["muri", "die"],
["schimbat", "changed"],
["intra", "get in"],
["îti", "you"],
["grija", "care"],
["frank", "frank"],
["george", "George"],
["liber", "free"],
["amuzant", "funny"],
["ajung", "get"],
["doctor", "doctor"],
["masina", "car"],
["sam", "Sat."],
["altcineva", "someone else"],
["laşi", "leave"],
["picioare", "legs"],
["sânge", "blood"],
["direct", "direct"],
["petrecere", "party"],
["ţie", "to you"],
["staţi", "stay"],
["sînt", "are"],
["cameră", "the room"],
["voie", "will"],
["charlie", "charlie"],
["ieri", "yesterday"],
["pur", "pure"],
["viitoare", "upcoming"],
["normal", "normal"],
["greşit", "wrong"],
["mor", "I am dying"],
["şase", "six"],
["persoană", "the person"],
["traducerea", "translation"],
["aştept", "look"],
["special", "special"],
["toţii", "all"],
["atat", "both"],
["fiule", "sonny"],
["cerut", "asked for"],
["atâta", "so much"],
["anul", "the year"],
["unii", "some"],
["sex", "sex"],
["lovit", "hit"],
["aer", "air"],
["povestea", "the story"],
["omor", "murder"],
["ideea", "idea"],
["minut", "minute"],
["ieşit", "out"],
["aminteşti", "remember"],
["săptămâni", "weeks"],
["afla", "find out"],
["uneori", "sometimes"],
["faptul", "the fact"],
["domnului", "Mr."],
["mâncare", "food"],
["york", "york"],
["tom", "tome"],
["stie", "know"],
["spună", "tell"],
["dori", "like"],
["băiete", "boy"],
["aibă", "have"],
["şansă", "chance"],
["doctore", "Doctor"],
["aflat", "found"],
["seară", "in the evening"],
["asculta", "listen"],
["michael", "michael"],
["atent", "careful"],
["zece", "ten"],
["dăm", "give"],
["munca", "the work"],
["soţul", "husband"],
["alta", "other"],
["uiţi", "look"],
["clar", "clear"],
["obicei", "custom"],
["plus", "addition"],
["caut", "I search"],
["aminte", "remember"],
["afaceri", "business"],
["veniţi", "coming"],
["cafea", "coffee"],
["decat", "than"],
["david", "david"],
["plăcea", "like"],
["dragostea", "love"],
["inainte", "before"],
["ceilalţi", "the others"],
["cunoşti", "know"],
["dreapta", "right"],
["gură", "the mouth"],
["oricine", "anybody"],
["aduci", "bring"],
["prietena", "girlfriend"],
["muncă", "the work"],
["trecută", "last"],
["ordine", "order"],
["priveşte", "look"],
["aveti", "you have"],
["încât", "that"],
["noua", "nine"],
["spital", "hospital"],
["celor", "the"],
["promit", "I promise"],
["şti", "know"],
["gândeam", "thinking"],
["cui", "nail"],
["foame", "hunger"],
["intre", "between"],
["gândeşti", "think"],
["întâlnit", "met"],
["băiatul", "boy"],
["rămâi", "stay"],
["sale", "its"],
["lucrez", "I'm working"],
["doamnelor", "Ladies"],
["vroiam", "I wanted"],
["uh", "uh"],
["poveste", "story"],
["hey", "hey"],
["cartea", "book"],
["puterea", "the power"],
["anume", "certain"],
["crăciun", "Christmas"],
["învăţat", "learned"],
["m", "m"],
["fete", "girls"],
["rost", "sense"],
["puternic", "strong"],
["termină", "finish"],
["c", "c"],
["luptă", "the fight"],
["găsim", "find"],
["mamei", "mother"],
["mână", "hand"],
["sincer", "sincere"],
["fiţi", "be"],
["lupta", "the fight"],
["complet", "completely"],
["însă", "but"],
["opri", "stop"],
["voiam", "wanted"],
["închisoare", "prison"],
["lumina", "the light"],
["mii", "thousands"],
["pregătit", "prepared"],
["masa", "table"],
["mike", "mike"],
["ţii", "keep"],
["dreptul", "the right"],
["biroul", "the desk"],
["femeia", "woman"],
["acestea", "these"],
["plece", "leave"],
["super", "Super"],
["speriat", "scared"],
["fundul", "ass"],
["întrebat", "questioned"],
["schimb", "change"],
["oamenilor", "people"],
["femeile", "the women"],
["vedeţi", "see"],
["pai", "Well"],
["carte", "book"],
["bravo", "Bravo"],
["fiindcă", "because"],
["clipă", "moment"],
["întrebare", "question"],
["dispărut", "missing"],
["stă", "stands"],
["încerca", "try"],
["furat", "stealing"],
["intamplat", "happened"],
["suna", "sounds"],
["fetele", "girls"],
["urăsc", "I hate"],
["încerci", "try"],
["adevarat", "TRUE"],
["tati", "Daddy"],
["dimineata", "morning"],
["dormi", "are you sleeping"],
["dor", "longing"],
["iisuse", "Jesus"],
["absolut", "absolute"],
["cauţi", "look"],
["stare", "condition"],
["ţin", "I hold"],
["ajutorul", "help"],
["atenţie", "Careful"],
["părinţii", "the parents"],
["vechi", "old"],
["oraşul", "the city"],
["baie", "bathroom"],
["you", "you"],
["săptămână", "week"],
["adaptarea", "the adaptation"],
["vostru", "your"],
["omoare", "kill"],
["ucide", "kill"],
["intampla", "happen"],
["ies", "out"],
["america", "America"],
["telefonul", "phone"],
["puteam", "could"],
["citit", "read"],
["nenorocit", "wretched"],
["căpitane", "Captain"],
["ajute", "help"],
["negru", "black"],
["spunem", "tell"],
["regele", "The King"],
["întâlnire", "meeting"],
["vremea", "the weather"],
["slujba", "job"],
["luaţi", "take"],
["personal", "personal"],
["www", "www"],
["arata", "to miss"],
["luna", "month"],
["noştri", "our"],
["bea", "drink"],
["unele", "some"],
["accident", "accident"],
["ăia", "that"],
["câine", "dog"],
["mici", "small"],
["schimba", "change"],
["caută", "search for"],
["spuneţi", "tell"],
["masă", "table"],
["ro", "ro"],
["harry", "harry"],
["continuă", "keep going"],
["bob", "grain"],
["adevăr", "truth"],
["inapoi", "back"],
["zona", "area"],
["băut", "drinking"],
["află", "find out"],
["mori", "die"],
["stea", "star"],
["secunde", "seconds"],
["folosit", "used"],
["nebunie", "madness"],
["ala", "that"],
["scumpo", "sweetheart"],
["uită", "forget"],
["teamă", "the fear"],
["tai", "your"],
["linişte", "Quiet"],
["totdeauna", "always"],
["câştigat", "won"],
["aceeaşi", "same"],
["birou", "office"],
["oară", "time"],
["ajungem", "get"],
["doresc", "I want"],
["credeţi", "think"],
["pierde", "lose"],
["cina", "dinner"],
["suficient", "sufficient"],
["arme", "arms"],
["secret", "secret"],
["meargă", "go"],
["drăguţă", "sweetheart"],
["dv", "your"],
["paul", "paul"],
["spunea", "said"],
["simţit", "felt"],
["fund", "background"],
["picioarele", "legs"],
["plan", "plan"],
["plin", "full"],
["întrebări", "questions"],
["mesaj", "message"],
["mda", "mda"],
["şeful", "head"],
["salvat", "saved"],
["cã", "that"],
["doare", "it hurts"],
["plecaţi", "leave"],
["precum", "like"],
["jimmy", "jimmy"],
["trimite", "send"],
["ajungi", "get"],
["ben", "ben"],
["vedere", "view"],
["continua", "keep going"],
["vieţii", "life"],
["muzica", "the music"],
["termina", "finish"],
["lasa", "leave"],
["poliţie", "police"],
["simte", "feels"],
["jurul", "around"],
["încoace", "here"],
["intru", "enter"],
["promis", "promised"],
["cealaltă", "other"],
["vede", "sees"],
["altul", "another"],
["încet", "slow"],
["putere", "power"],
["săptămâna", "week"],
["avion", "plane"],
["întorci", "return"],
["alături", "together"],
["oprit", "torn off"],
["băieţii", "boys"],
["lună", "month"],
["lucrat", "wrought"],
["mary", "mary"],
["găseşti", "find"],
["lumii", "world"],
["asteapta", "Wait"],
["aur", "gold"],
["noastra", "Our"],
["închis", "closed"],
["tatal", "father"],
["ha", "Ha"],
["scoate", "take out"],
["cuvânt", "word"],
["crescut", "grown"],
["răspunde", "reply"],
["cere", "ask"],
["doctorul", "doctor"],
["ocup", "deal"],
["ocupat", "busy"],
["căzut", "fell"],
["imposibil", "impossible"],
["potrivit", "right"],
["deschis", "open"],
["calea", "path"],
["tatălui", "father"],
["d", "d"],
["începem", "Started"],
["micul", "Breakfast"],
["planul", "the plan"],
["voastre", "your"],
["omori", "kill"],
["joci", "play"],
["gasit", "found"],
["james", "james"],
["general", "general"],
["fericită", "happy"],
["henry", "henry"],
["câţiva", "a few"],
["ajuţi", "help"],
["presupun", "I suppose"],
["interesant", "interesting"],
["chestii", "things"],
["peter", "peter"],
["deasupra", "on top"],
["multi", "many"],
["vorbesti", "talk"],
["aceşti", "these"],
["câţi", "how many"],
["prinde", "catch"],
["printre", "through"],
["noul", "the new"],
["atinge", "achieve"],
["mintea", "minds"],
["max", "max"],
["întreaga", "around"],
["control", "control"],
["pierd", "lose"],
["cuvinte", "words"],
["unchiul", "uncle"],
["hotel", "hotel"],
["poliţist", "policeman"],
["acestui", "this"],
["slujbă", "job"],
["simti", "feel"],
["sufletul", "soul"],
["folosi", "use"],
["deoarece", "because"],
["tem", "fear"],
["trec", "I pass"],
["rând", "row"],
["mişcă", "move"],
["conduce", "lead"],
["echipă", "team"],
["situaţia", "the situation"],
["minunată", "wonderful"],
["celălalt", "the other one"],
["încep", "start"],
["fiind", "being"],
["stăm", "stay"],
["periculos", "dangerous"],
["acestei", "this"],
["faceti", "make"],
["trag", "shoot"],
["vis", "dream"],
["bere", "beer"],
["dna", "Ms"],
["lucrezi", "You work"],
["armă", "weapon"],
["opt", "eight"],
["rapid", "fast"],
["ºi", "and"],
["petrece", "spend"],
["nord", "north"],
["acele", "those"],
["par", "hair"],
["lucrează", "work"],
["rece", "cold"],
["iubeşti", "love"],
["b", "b"],
["tras", "fired"],
["droguri", "drugs"],
["păcat", "sin"],
["iubit", "beloved"],
["incredibil", "incredible"],
["stânga", "Left"],
["billy", "billy"],
["născut", "born"],
["faca", "make"],
["succes", "success"],
["prostii", "Nonsense"],
["rănit", "injured"],
["alb", "white"],
["serviciu", "service"],
["jocul", "the game"],
["conduc", "I am driving"],
["rămân", "remain"],
["greşeală", "mistake"],
["oare", "really"],
["strada", "the street"],
["fetelor", "girls"],
["american", "American"],
["frumoasa", "beautiful"],
["evident", "obvious"],
["morţi", "dead"],
["răspuns", "answer"],
["punct", "point"],
["exemplu", "example"],
["usor", "Easy"],
["puteti", "you can"],
["trăiesc", "I'm alive"],
["usa", "door"],
["scăpat", "got rid"],
["na", "N / A"],
["mergeţi", "go"],
["domnişoară", "Ms."],
["câteodată", "sometimes"],
["pericol", "danger"],
["of", "of"],
["întoarcem", "return"],
["bill", "bill"],
["ray", "ray"],
["felicitări", "congratulations"],
["mâncat", "eat"],
["persoane", "people"],
["închide", "hang up"],
["vorbească", "speak"],
["eddie", "eddie"],
["cină", "dinner"],
["legătura", "link"],
["sud", "south"],
["aflu", "find"],
["scos", "out"],
["folosesc", "use"],
["idiot", "idiotic"],
["iubire", "love"],
["bate", "beat"],
["împuşcat", "shot"],
["corpul", "the body"],
["interesează", "interested"],
["înţelege", "understand"],
["punem", "we"],
["primi", "receive"],
["rea", "bad"],
["metri", "meters"],
["diseară", "tonight"],
["scot", "out"],
["baieti", "boys"],
["fugit", "fled"],
["alex", "alex"],
["johnny", "johnny"],
["cuvântul", "the word"],
["numesc", "call"],
["ţară", "the country"],
["scuzaţi", "excuse"],
["pierzi", "You lose"],
["arăta", "to miss"],
["armata", "army"],
["macar", "even"],
["viitor", "future"],
["atac", "attack"],
["nick", "nick"],
["distrus", "destroyed"],
["frumoase", "beautiful"],
["şapte", "seven"],
["ţara", "the country"],
["moară", "mill"],
["permite", "Enable"],
["nenorocitule", "motherfucker"],
["sergent", "sergeant"],
["proastă", "stupid"],
["piciorul", "leg"],
["mişca", "move"],
["maine", "tomorrow"],
["adica", "meaning"],
["opreşte", "stops"],
["dorit", "wanted"],
["zilele", "days"],
["sfârşitul", "end"],
["aştepta", "wait"],
["hainele", "the clothes"],
["plătit", "paid"],
["deveni", "become"],
["supărat", "upset"],
["and", "and"],
["paris", "Paris"],
["tânăr", "young man"],
["întâmple", "happen"],
["rege", "king"],
["apărut", "published"],
["plină", "full"],
["port", "I'm wearing"],
["daţi", "give"],
["diferit", "different"],
["sir", "row"],
["persoana", "the person"],
["frica", "fear"],
["sosit", "arrived"],
["adevărată", "TRUE"],
["intri", "get"],
["trimit", "send"],
["întâlnim", "meet"],
["grămadă", "heap"],
["bolnav", "sick"],
["jim", "jim"],
["mami", "Mommy"],
["aştepţi", "wait"],
["părul", "the hair"],
["afacere", "business"],
["ajutat", "helped"],
["chestie", "stuff"],
["inseamna", "means"],
["oriunde", "anywhere"],
["aseară", "last night"],
["trezit", "woken up"],
["uşă", "door"],
["aşteptaţi", "wait"],
["final", "final"],
["tony", "tony"],
["baza", "the base"],
["glumeşti", "You're kidding"],
["secundă", "second"],
["armele", "weapons"],
["sens", "sense"],
["aruncat", "threw"],
["minţi", "lying"],
["petrecerea", "party"],
["okay", "okay"],
["veti", "will you"],
["încetează", "ends"],
["moartă", "dead"],
["privire", "look"],
["decis", "determined"],
["beau", "I drink"],
["cadou", "gift"],
["tarziu", "Late"],
["t", "t"],
["cheia", "the key"],
["plătesc", "I pay"],
["singuri", "themselves"],
["mişto", "cool"],
["or", "or"],
["mica", "small"],
["grea", "tough"],
["avocat", "lawyer"],
["deranjează", "disturb"],
["lăsăm", "leave"],
["crimă", "crime"],
["familiei", "family"],
["marea", "the sea"],
["alţii", "others"],
["vorbă", "words"],
["mr", "mr"],
["cumpărat", "bought"],
["cal", "horse"],
["companie", "company"],
["numit", "appointed"],
["depinde", "depends"],
["sistemul", "the system"],
["marele", "great"],
["sint", "are"],
["san", "breast"],
["merită", "deserve"],
["locuri", "seats"],
["filmul", "the movie"],
["sângele", "blood"],
["părea", "look"],
["soldat", "soldier"],
["joacă", "play"],
["următorul", "next"],
["ştiai", "you know"],
["doilea", "second"],
["sarah", "sarah"],
["semn", "signal"],
["poartă", "gate"],
["bobby", "bobby"],
["suni", "call"],
["petrecut", "spent"],
["pariu", "bet"],
["stiti", "know"],
["ducem", "take"],
["bărbaţi", "men"],
["apropo", "by the way"],
["propria", "own"],
["magazin", "store"],
["nimănui", "anyone"],
["mulţumim", "thank you"],
["placă", "plate"],
["bătut", "beaten"],
["ultimele", "latest"],
["glumă", "joke"],
["carne", "meat"],
["excelent", "excellent"],
["jake", "jake"],
["părinte", "parent"],
["dorm", "I'm sleeping"],
["agent", "agent"],
["onoare", "honor"],
["ceai", "what do you have"],
["porţi", "gates"],
["londra", "London"],
["avionul", "the airplane"],
["respect", "respect"],
["devine", "gets"],
["uitaţi", "Remember"],
["pari", "you seem"],
["don", "don"],
["real", "real"],
["ascuns", "hidden"],
["inceput", "beginning"],
["mănâncă", "eat"],
["ştia", "knew"],
["sotia", "wife"],
["est", "east"],
["iesi", "out"],
["preşedinte", "chairman"],
["întârziat", "delayed"],
["lăsaţi", "leave"],
["pas", "step"],
["huh", "huh"],
["tv", "tv"],
["cateva", "some"],
["viitorul", "the future"],
["des", "frequently"],
["doreşti", "want"],
["bătrân", "old"],
["majoritatea", "most of them"],
["to", "to"],
["radio", "radio"],
["ceasul", "the clock"],
["zbor", "flight"],
["richard", "richard"],
["primesc", "I'm getting"],
["danny", "danny"],
["chemat", "called"],
["nicăieri", "nowhere"],
["prezint", "present"],
["surpriză", "surprise"],
["capăt", "end"],
["iubeşte", "loves"],
["iubitule", "boyfriend"],
["diferite", "different"],
["părăsit", "abandoned"],
["câinele", "dog"],
["scriu", "write"],
["pământul", "earth"],
["mijlocul", "middle"],
["oras", "Town"],
["scrisoare", "letter"],
["obosit", "tired"],
["steve", "steve"],
["compania", "company"],
["cuiva", "someone"],
["întrebi", "ask"],
["curat", "clean"],
["trăi", "live"],
["jucat", "played"],
["baltă", "puddle"],
["informaţii", "information"],
["vreti", "want"],
["descoperit", "found"],
["tommy", "tommy"],
["aveai", "had"],
["părere", "opinion"],
["urât", "ugly"],
["mana", "hand"],
["trecem", "get"],
["dragul", "dear"],
["războiul", "the war"],
["clasa", "class"],
["cheile", "keys"],
["inteleg", "understand"],
["ului", "community"],
["termin", "finish"],
["dulce", "sweet"],
["ajungă", "reach"],
["charles", "charles"],
["aşteptăm", "we are waiting"],
["spectacol", "show"],
["vi", "you"],
["iată", "there it is"],
["deşi", "although"],
["dans", "dance"],
["unchiule", "uncle"],
["juca", "play"],
["habar", "idea"],
["nava", "vessel"],
["stop", "Stop"],
["cînd", "when"],
["celelalte", "other"],
["odata", "once time"],
["haine", "clothes"],
["impreuna", "together"],
["căpitanul", "the captain"],
["rândul", "row"],
["bar", "bar"],
["stradă", "the street"],
["nebună", "madwoman"],
["focul", "fire"],
["hmm", "hmm"],
["indiferent", "indifferent"],
["sute", "hundreds"],
["pasa", "pasha"],
["bei", "bey"],
["săturat", "saturating"],
["filme", "movies"],
["regina", "Queen"],
["sti", "know"],
["frig", "cold"],
["funcţionează", "working"],
["linia", "the line"],
["veche", "old"],
["doriţi", "want"],
["prostie", "folly"],
["afacerea", "business"],
["urmează", "it follows"],
["pt", "for"],
["observat", "noticed"],
["iese", "out"],
["lista", "list"],
["com", "com"],
["dnă", "Mrs."],
["voia", "will"],
["legat", "tied up"],
["alege", "choose"],
["mulţime", "crowd"],
["aşteptat", "waiting"],
["club", "club"],
["ni", "us"],
["încercăm", "we try"],
["dra", "Miss"],
["prietenă", "girlfriend"],
["puţină", "some"],
["dejun", "breakfast"],
["mănânci", "eat"],
["adresa", "Address"],
["ruşine", "shame"],
["ieşim", "out"],
["legea", "the law"],
["şcoala", "school"],
["apropie", "approaching"],
["oferit", "given"],
["devin", "are"],
["tragi", "shoot"],
["număr", "number"],
["mâncarea", "the food"],
["misiune", "mission"],
["it", "it"],
["inteles", "meaning"],
["preşedintele", "the president"],
["scoala", "school"],
["isi", "their"],
["prind", "catch"],
["mutat", "moved"],
["cald", "warm"],
["limba", "language"],
["explic", "explain"],
["cărţi", "books"],
["punctul", "the point"],
["bunica", "grandmother"],
["fa", "fa"],
["ajută", "it helps"],
["purta", "wear"],
["milion", "million"],
["ascult", "listen"],
["tipii", "guys"],
["j", "j"],
["grup", "group"],
["recunosc", "Recognize"],
["vest", "west"],
["soarele", "sun"],
["ascultaţi", "listen"],
["mingea", "the ball"],
["idiotule", "idiot"],
["importantă", "importance"],
["stiam", "I knew"],
["asculţi", "listen"],
["rupt", "torn"],
["numeşte", "called"],
["distruge", "destroy"],
["iad", "hell"],
["lungă", "long"],
["vreodata", "ever"],
["centrul", "the center"],
["ducă", "lead"],
["miroase", "smells"],
["datoria", "duty"],
["aveau", "had"],
["vocea", "the voice"],
["târfă", "slut"],
["salva", "save"],
["pleaca", "leaves"],
["nenorocitul", "wretched"],
["căutat", "looked up"],
["unite", "united"],
["credem", "think"],
["sala", "Hall"],
["norocos", "lucky"],
["ascunde", "hide"],
["lucra", "work"],
["acuma", "now"],
["siguranta", "safety"],
["descurc", "handle"],
["întâlnesc", "meet"],
["lumină", "the light"],
["omorî", "kill"],
["opresc", "stop"],
["p", "p"],
["apartamentul", "apartment"],
["ţinut", "land"],
["arestat", "arrested"],
["nă", "N / A"],
["tipi", "guys"],
["tara", "the country"],
["începi", "start"],
["jane", "jane"],
["atâtea", "many"],
["afli", "are"],
["poarta", "gate"],
["câştiga", "win"],
["veşti", "news"],
["soţie", "wife"],
["total", "total"],
["rahatul", "shit"],
["apare", "appear"],
["pahar", "glass"],
["controlul", "control"],
["invitat", "guest"],
["regulile", "rules"],
["vârsta", "age"],
["taxi", "taxi"],
["groaznic", "terrible"],
["ratat", "lame duck"],
["animale", "animals"],
["lung", "long"],
["lee", "lee"],
["rugat", "asked"],
["îndrăgostit", "lover"],
["motivul", "the reason"],
["inimă", "heart"],
["verde", "green"],
["profesor", "professor"],
["lucrul", "working"],
["meci", "match"],
["stricat", "broken"],
["intotdeauna", "always"],
["scurt", "short"],
["chestiile", "things"],
["gândi", "think"],
["robert", "robert"],
["larry", "larry"],
["stim", "We know"],
["plăcută", "pleasant"],
["aşteptam", "we are waiting"],
["bătaie", "beat"],
["distractiv", "entertaining"],
["discutăm", "discuss"],
["căsătorit", "married"],
["unor", "of"],
["asigur", "assure"],
["bărbaţii", "men"],
["maria", "maria"],
["citesc", "I read"],
["continuare", "continuation"],
["iubirea", "love"],
["dispari", "get lost"],
["ridicol", "ridiculous"],
["trăieşti", "live"],
["angajat", "employee"],
["will", "Will"],
["gol", "naked"],
["adu", "get"],
["durere", "pain"],
["făcea", "was"],
["nunta", "Wedding"],
["perfectă", "perfect"],
["mark", "mark"],
["ofiţer", "officer"],
["oprim", "stop"],
["dragule", "dear"],
["mişcare", "motion"],
["bem", "we drink"],
["chris", "chris"],
["casei", "house"],
["scape", "escape"],
["trăieşte", "lives"],
["cuvintele", "words"],
["plimbare", "walk"],
["picior", "foot"],
["bunicul", "the grandfather"],
["dincolo", "beyond"],
["propriul", "own"],
["formă", "form"],
["roşu", "Red"],
["conduci", "lead"],
["superi", "upset"],
["fierbinte", "hot"],
["mândru", "proud"],
["jerry", "jerry"],
["trenul", "the train"],
["acelasi", "same"],
["viu", "alive"],
["morţii", "death"],
["comanda", "command"],
["hotărât", "decided"],
["iasă", "out"],
["nr", "No"],
["km", "km"],
["minţit", "lied"],
["luam", "take"],
["maşini", "machinery"],
["dormit", "sleep"],
["somn", "sleep"],
["călătorie", "travel"],
["cunoştinţă", "acquaintance"],
["plăti", "payment"],
["aruncă", "throw"],
["cunoaşte", "know"],
["muzică", "the music"],
["criminal", "criminal"],
["haideti", "come on"],
["mâini", "hands"],
["jucăm", "play"],
["legatura", "link"],
["plecam", "leave"],
["uşurel", "gently"],
["erou", "hero"],
["favoare", "favor"],
["animal", "animal"],
["li", "them"],
["vinovat", "guilty"],
["mã", "me"],
["puternică", "strong"],
["păţit", "happened"],
["banca", "the bank"],
["băgat", "involved"],
["clipa", "moment"],
["problemele", "problems"],
["yeah", "yeah"],
["misiunea", "mission"],
["spuneam", "said"],
["mănânc", "eat"],
["convins", "convinced"],
["vorbeam", "talking"],
["necesar", "necessary"],
["moare", "dies"],
["adam", "adam"],
["isuse", "Jesus"],
["părut", "thought"],
["schimbă", "change"],
["thomas", "thomas"],
["mile", "miles"],
["creat", "made"],
["intraţi", "come in"],
["urcă", "get on"],
["trăiască", "live"],
["barbat", "man"],
["public", "public"],
["energie", "energy"],
["dura", "last"],
["vinde", "sell"],
["pistolul", "gun"],
["bat", "knock on"],
["următoarea", "following"],
["suflet", "soul"],
["lase", "leave"],
["teren", "ground"],
["puteai", "could"],
["vorbeste", "speaks"],
["trăit", "lived"],
["cont", "account"],
["chem", "call"],
["grozavă", "great"],
["cutie", "box"],
["pauză", "pause"],
["guvernul", "government"],
["uri", "hate"],
["pună", "put"],
["răspunsul", "the answer"],
["copiilor", "children"],
["intrăm", "enter"],
["brian", "brian"],
["mânca", "eat"],
["televizor", "TV"],
["nasul", "nose"],
["team", "team"],
["modul", "module"],
["barca", "the boat"],
["încântat", "Pleased"],
["beat", "drunk"],
["liberă", "free"],
["neagră", "black"],
["cind", "when"],
["vorbiţi", "do you speak"],
["curaj", "Courage"],
["ordin", "order"],
["ceri", "ask"],
["soare", "sun"],
["trist", "sad"],
["politia", "the police"],
["oferi", "offer"],
["anna", "anna"],
["bogat", "rich"],
["washington", "Washington"],
["pete", "spots"],
["apartament", "apartment"],
["praf", "dust"],
["vineri", "Friday"],
["martin", "martin"],
["verificat", "verified"],
["atins", "touched"],
["urmărit", "followed"],
["fotbal", "football"],
["walter", "walter"],
["descurci", "deal"],
["lovitură", "coup"],
["zonă", "area"],
["treacă", "pass"],
["liniştit", "quiet"],
["tren", "train"],
["totusi", "however"],
["vorbind", "speaking"],
["pierdem", "lose"],
["lasat", "dropped off"],
["armată", "army"],
["r", "r"],
["condus", "driving"],
["porc", "pig"],
["pregătiţi", "prepared"],
["culcare", "sleep"],
["poată", "can"],
["păr", "hair"],
["permis", "allowed"],
["kate", "kate"],
["patul", "the bed"],
["venim", "come"],
["dave", "dave"],
["intelegi", "understand"],
["by", "by"],
["milă", "mercy"],
["uimitor", "amazing"],
["gheaţă", "ice"],
["şef", "head"],
["şefu", "boss"],
["căutăm", "we are looking for"],
["adio", "Farewell"],
["dră", "Miss"],
["reusit", "successful"],
["fantastic", "fantastic"],
["întuneric", "darkness"],
["arătat", "showed"],
["kevin", "kevin"],
["foloseşti", "use"],
["dur", "rough"],
["plânge", "cry"],
["vai", "Oh my"],
["arate", "show"],
["realitate", "reality"],
["dificil", "difficult"],
["carl", "carl"],
["matt", "matt"],
["oraşului", "city"],
["cumpăr", "I buy"],
["rugăm", "Please"],
["istoria", "the history"],
["anglia", "England"],
["ocazia", "opportunity"],
["arunca", "throw"],
["motive", "reasons"],
["întrebam", "wondering"],
["zeu", "god"],
["înaintea", "prior to"],
["aranjat", "trim"],
["acestor", "these"],
["sistem", "system"],
["treia", "third"],
["înnebunit", "mad"],
["miss", "miss"],
["ridica", "pick up"],
["şansa", "chance"],
["oricând", "whenever"],
["durerea", "pain"],
["andy", "andy"],
["urgenţă", "expedite"],
["găsească", "find"],
["ridicat", "picked up"],
["ocupa", "busy"],
["necazuri", "trouble"],
["vizită", "visit"],
["corp", "body"],
["albă", "white"],
["costum", "costume"],
["foloseşte", "uses"],
["bărbatul", "man"],
["gunoi", "trash"],
["vroia", "wanted"],
["flori", "flowers"],
["încolo", "away"],
["anii", "years"],
["verific", "check"],
["visul", "the dream"],
["bord", "board"],
["ofer", "I offer"],
["astazi", "today"],
["bag", "bag"],
["dragut", "cute"],
["culcat", "lying down"],
["locuiesc", "I live"],
["astia", "these"],
["sansa", "chance"],
["poze", "pictures"],
["me", "me"],
["stiut", "know"],
["scenă", "scene"],
["înţelegere", "understanding"],
["bancă", "the bank"],
["ambele", "both"],
["parca", "park"],
["rock", "rock"],
["catre", "by"],
["linie", "line"],
["securitate", "security"],
["rezolva", "solve"],
["nopţii", "night"],
["tinere", "young"],
["scăpa", "get rid"],
["deştept", "smart"],
["istorie", "history"],
["rele", "bad"],
["continui", "continue"],
["scrii", "write"],
["lapte", "milk"],
["aşadar", "therefore"],
["distracţie", "fun"],
["dovezi", "evidence"],
["zilei", "day"],
["roma", "Rome"],
["aflăm", "are"],
["privinţa", "regard"],
["înveţi", "learn"],
["pielea", "skin"],
["tie", "to you"],
["suport", "support"],
["oricare", "either one"],
["fred", "fred"],
["importante", "important"],
["întrebarea", "the question"],
["dan", "dan"],
["bază", "the base"],
["situaţie", "situation"],
["priviţi", "look"],
["u", "u"],
["vândut", "sold"],
["merci", "thanks"],
["scapi", "Lose"],
["poză", "picture"],
["vara", "summer"],
["restaurant", "restaurant"],
["interesat", "interested"],
["biserica", "the church"],
["acei", "those"],
["datorită", "due to"],
["costă", "cost"],
["proces", "trial"],
["luptat", "fought"],
["culoare", "color"],
["crima", "crime"],
["calul", "the horse"],
["chef", "binge"],
["făceam", "doing"],
["dumneavoastra", "your"],
["detectiv", "detective"],
["scumpule", "deary"],
["pariez", "bet"],
["peşte", "over"],
["secrete", "secret"],
["creierul", "brains"],
["gresit", "wrong"],
["bănuiesc", "I presume"],
["langa", "Besides"],
["calm", "calm"],
["gust", "taste"],
["puştiule", "kid"],
["arthur", "arthur"],
["nebuni", "crazy"],
["iisus", "Jesus"],
["autobuz", "bus"],
["biserică", "the church"],
["rămână", "stay"],
["apreciez", "I appreciate"],
["nevasta", "wife"],
["nuntă", "Wedding"],
["cai", "horses"],
["făcută", "made"],
["programul", "program"],
["lucy", "lucy"],
["alţi", "other"],
["amin", "Amen"],
["cinste", "honor"],
["insula", "the island"],
["tânără", "girl"],
["cutia", "box"],
["aducă", "bring"],
["regret", "regret"],
["william", "william"],
["fericire", "happiness"],
["nervos", "nervous"],
["ucid", "kill"],
["gandit", "thought"],
["veniti", "coming"],
["liceu", "high school"],
["poza", "picture"],
["extraordinar", "extraordinary"],
["durează", "takes"],
["gratis", "gratis"],
["ordinele", "orders"],
["uităm", "look"],
["cumperi", "buy"],
["scena", "scene"],
["primeşti", "you get"],
["annie", "annie"],
["sotul", "husband"],
["curtea", "court"],
["sticlă", "glass"],
["pâna", "until"],
["degrabă", "rather"],
["reuşi", "succeed"],
["afle", "learn"],
["lasi", "leave"],
["lovitura", "coup"],
["bucătărie", "kitchen"],
["poliţiei", "police"],
["magazinul", "shop"],
["tăiat", "cut"],
["mâncăm", "eat"],
["geanta", "bag"],
["băutură", "drink"],
["omoară", "killing"],
["prânz", "Lunch"],
["cauză", "Cause"],
["taie", "cut"],
["rezolvat", "solved"],
["claire", "claire"],
["misca", "move"],
["seamănă", "resembles"],
["scoatem", "out"],
["stati", "stay"],
];
