
const spanishQ = [
["¿Estás listo? ¡Vamos!", "Are you ready? Let's go!"],
["Who?", "¿Quién?"],
["De quién", "Whose"],
["¿Quién es?", "Who is it?"],
["¿Quiénes son?", "Who are they?"],
["¿De quién son estos libros?", "Whose books are these?"],
["What?", "¿Qué?"], 
["Which", "¿Cuál?"],
["¿Qué haces ahora?", "What are you doing right now?"],
["¿Qué es esto?", "What’s that?"],
["¿Cuál es tu favorito?", "Which is your favourite?"],
["¿Cuál es tu película favorita?", "What is your favourite movie?"],
["When?", "¿Cuándo?"],
["¿A qué hora es la película?", "What time is the movie?"],
["¿Cuándo es tu cumpleaños?", "When is your birthday?"],
["¿Cuándo vas a ir?", "When will you go?"],
["Where?", "¿Dónde"],
["¿Dónde vives?", "Where do you live?"],
["¿A dónde vas?", "To where are you going?"],
["¿De dónde eres?", "Where are you from?"],
["from where", "de dónde"],
["¿Por qué? / ¿Para qué?", "Why?"],
["¿Por qué dices eso?", "Why do you say that?"],
["¿Para qué estás aprendiendo español?", 
				"What are you learning Spanish for?"],
["¿Cómo?", "How?"],
["¿Cómo está usted?", "How are you?"],
["¿Cómo hiciste eso?", "How did you do that?"],
["¿Cuántos? / ¿Cuánto? / ¿Cuántas? / ¿Cuánta?", "How many? / How much?"],
["¿Cuántas manzanas?", "How many apples?"],
["¿Cuántos aguacates?", "How many avocados?"],
["¿Cuánta agua?", "How much water?"],
["¿Cuánto té?", "How much tea?"],
["Bueno, ¿qué hay de la cena?", "Well, what’s for dinner?"],
["Tengo una pregunta", "I have a question"],
["¿Puedo hacerte una pregunta?", "Can I ask you a question?"],
["Tengo una pregunta para ti", "I have one question for you."],
["Tengo dos preguntas para ti", "I have two questions for you."],
["¿Puedo preguntarte algo?", "May I ask you something?"],
["Hola, ¿cómo te llamas?", "Hello, what’s your name?"],
["Soy Benny.", "I’m Benny."],
["¿Que tal?", "How’re you?"],
["Muy bien, gracias. ¿Y tu?", "I’m great, thanks. And you?"],
["¿Cuántos años tienes?", "How old are you?"],
["Tengo treinta años.", "I am 30 years old."],
["¿A qué te dedicas?", "What do you do for a living?"],
["Soy escritor y orador.", "I am a writer and speaker."],
["¿Donde trabajas?", "Where do you work?"],
["Trabajo en un restaurante.", "I work at a restaurant."],
["¿Cuáles son tus aficiones?", "What are your hobbies?"],
["Me gusta leer libros y ver películas.", 
			"I like to read books and watch movies."],
["¿De donde eres?", "Where are you from?"],
["Soy de Irlanda.", "I’m from Ireland."],

["¿Cuál es tu película favorita?", "What’s your favourite movie?"],
["Me encanta Star Wars.", "I love Star Wars."],
["¿Desde cuándo aprendes español?", 
			"How long have you been learning Spanish?"],
["Aprendo español desde hace tres meses.", 
				"I’ve been learning Spanish for 3 months."],
["¿Cuál es tu color favorito?", "What is your favourite colour?"],
["Me gusta el verde.", "I like green."],
["¿Hablas otros idiomas?", "Do you speak other languages?"],
["Sí, hablo inglés y francés.", "Yes, I speak English and French."],
["¿Tienes hermanos?", "Do you have any siblings?"],
["Sí, una hermana.", "Yes, one sister."],
["¿Tienes hijos?", "Do you have any kids?"],
["No, no tengo hijos.", "No, I don’t have kids."],
["¿Cuántos en tu familia?", "How many in your family?"],
["Tres. Yo, mi mujer y mi perrito.", "Me, my wife, and my puppy."],
["¿Tienes alguna mascota?", "Do you have a pet?"],
["Sí, tengo un perro.", "Yes, I have a dog."],
["¿Cuál es el nombre de tu hermano/hermana?",
					"What is your brother’s/sister’s name?"],


["El nombre de mi hermano/hermana es…", "My brother’s/sister’s name is…"],
["¿Qué hacen tus padres?", "What do your parents do?"],
["Mi padre es ingeniero y mi madre es enfermera.", 
			"My dad is an engineer and my mom is a nurse."],
["¿Dónde creciste?", "Where did you grow up?"],
["Yo crecí en…", "I grew up in…"],
["¿Que hora es?", "What time is it?"],
["Es la una.", "It’s 1 o’clock."],
["¿Qué día es?", "What day is it?"],
["Es viernes.", "It’s Friday."],
["¿A dónde vas?", "Where are you going?"],
["Me voy a trabajar.", "I’m going to work."],
["¿Qué haces?", "What are you doing?"],
["Estoy estudiando español.", "I’m studying Spanish."],
["¿Estás de acuerdo?", "Do you agree?"],
["Pues… yo no sé.", "Well… I don’t know."],
["¿Qué piensas?", "What do you think?"],
["Creo que esta bien.", "I think it’s good."],
["¿Qué has dicho?", "What did you say?"],
["Dije…", "I said…"],
["¿Dónde está el baño?", "Where’s the bathroom?"],
["Por ahí.", "Over there."],
["Hola, soy Benny.", "Hi, I'm Benny."],
["Holo, ¿cómo te llamas?", "Hi, what's your name?"],
["¿Está desocupada esta silla?", "Is this seat taken"],
["¿Sabe qué hora es?", "Do you know what the time is?"],
["¿Sabe a qué hora cierra este lugar?", "Do you know what time this place closes?"],
["¿Sabe dónde está el/la [place]?", "Do you know where the [place] is?"],
["¿De dónde eres?", "Where are you from?"],
["¿A qué te dedicas?", "What do you do for a living?"],
["¿Qué estudias?", "What do you study/What's your major?"],
["¿Qué te trae por aquí?", "What brings you here?"],
["¿Cuánto tiempo llevas aquí?", "How long have you been here?"],
["¿Cómo conoces a José?", "How do you know José?"],
["¿A quién conoces aquí?", "Who do you know here?"],
["¿Con quién estás aquí?", "Who are you here with?"],
["¿Vienes seguido por aquí?", "Do you come here often?"],
["¿Tienes hermanos/hijos?", "Do you have any siblings/children?"],
["¿Qué edad tienen?", "How old are they?"],
["¿Qué hacen tus padres?", "What do your parents do?"],
["¿Donde creciste?", "Where did you grow up?"],
["¿Ves a menudo a tus abuelos?", "Do you see your grandparents often?"],
["¿Eres cercano/a sus padres?", "Are you close with your parents?"],
["¿Cómo es tu pueblo natal?", "What's your hometown like?"],
["¿Tienes alguna mascota?", "Do you have any pets?"],
["¿Qué raza es tu perro/gato?", "What breed is your dog/cat?"],


["¿Te gusta viajar?", "Do you like to travel?"],
["¿Cuál es el lugar favorito en que has estado?", "What's your favourite place you've been to?"],
["¿En qué países has estado?", "Which countries have you been to?"],
["¿Has estado en [Roma]?", "Have you been to [Rome]?"],
["¿Querrías ir a [Barcelona]?", "Would you like to go to [Barcelona]?"],
["Si pudieras viajar a cualquier lugar, ¿dónde viajarías?", "If you could travel anywhere, where would you go?"],
["¿Hablas otros idiomas?", "Do you speak any other languages?"],
["¿A dónde fuiste la ultima vez de vacaciones?", "Where was the last place you went on holiday?"],
["¿Cuándo empezaste a aprender [español]?", "When did you start learning [Spanish]?"],
["¿Qué te hizo convertirte en [médico]?", "Why did you become a [doctor]?"],
["¿Te gusta tu trabajo?", "Do you like your job?"],
["¿Qué es lo que más te gusta de tu trabajo?", "What do you like the most about your job?"],
["¿Qué es la cosa más difícil sobre tu trabajo?", "What's the most difficult thing about your job?"],
["¿Fuiste a la universidad?", "Did you go to university?"],
["¿La disfrutaste?", "Did you enjoy it?"],



["¿Qué consejo le darías a alguien que quiere convertirse en [programador]?", "What advice would you give to someone who wants to become a [programmer]?"],
["¿Si pudieras volver atrás en el tiempo, estudiarías [psicología] de nuevo?", "If you could go back in time, would you study [psychology] again?"],
["¿Te gusta cocinar?", "Do you like to cook?"],
["¿Cuál es tu comida favorita?", "What's your favourite food?"],
["¿Te gusta la comida [italiana]?", "Do you like [Italian] food?"],
["¿Puedes recomendarme un buen restaurante cerca de aquí?", "Can you recommend me a good restaurant near here?"],
["¿Qué comen en su país?", "What do they eat in your country?"],
["¿Qué haces para divertirte?", "What do you like to do for fun?"],
["¿Te gusta [leer]?", "Do you like to [read]?"],
["¿Cuál tipo de música te gusta más?", "What's your favourite type of music?"],
["¿Cuál es tu [película/libro/banda] favorita?", "What's your favourite [film/book/band]?"],
["¿Tocas un instrumento?", "Do you play an instrument?"],



["¿Cuál es la peor película que has visto?", "What's the worst film you've seen?"],
["¿Practicas algún deporte?", "Do you play a sport?"],
["¿De qué equipo eres?", "What team do you support?"],
["¿Estás de acuerdo?", "Do you agree?"],
["¿Qué piensas tú sobre [X]?", "What do you think about [X]?"],
["Háblame/Cuéntame más de [X]", "Tell me more about [X]."],
["Si no te importa que te pregunte…", "If you don't mind me asking…"],
["Alguien me dijo que…", "Someone told me that…"],
["Escuché que…", "I heard that…"],
["¿Estás de acuerdo en que…?", "Would you agree that… ?"],
["Eso me recuerda…", "That reminds me…"],
["Hablando de eso…", "Speaking of which…"],
["Por otra parte…", "On another note…"],

["Estoy cambiando de tema, pero…", "I'm changing the subject, but…"],
["Me preguntaba…", "I was wondering…"],
["Te voy a decir una cosa…", "Let me tell you something"],
["¡Por supuesto! or ¡Claro que si!", "Of course!"],
["¿En serio?", "Really? / Seriously?"],
["¡Oye!", "Hey! (literally, 'listen!')"],
["¡Hostia!", "Damn!"],
["¡Ostras!", "A family-friendly version of '¡hostia!'."],
["¡Dios mio!", "Oh my god!"],
["A ver…", "Let’s see…"],

["¡No me digas!", "No way! (Literally: don’t tell me!)"],
["¡Vale!", "Okay! (Used in Spain, “dale” is more common in the Americas.)"],
["Qué yo sepa", "As far as I know."],
["Digo…", "Literally “I say”, but you can use this to correct yourself after you misspeak. “Somos dos… digo, tres personas.”"],
["O sea", "I mean…/Or rather…."],
["¿Sabes?", "You know?"],
["Una pregunta…", "a question"],



["spring", "la primavera"],
["summer", "el verano"],
["autumn/fall", "el otoño"],
["winter", "el invierno"],
["la estación lluviosa", "the rainy season"],
["la estación seca", "the dry season"],
["Es verano.", "It’s summer."],
["Nos vamos en primavera", "We’re leaving in the spring."],
["Es una fiesta de invierno", "It’s a winter party."],
["la flor", "flower/blossom"],
["florecer", "to bloom"],
["la oruga", "caterpillar"],
["la mariposa", "butterfly"],
["el pájaro", "bird"],
["la mariquita", "ladybug"],
["la semilla", "seed"],
["la planta", "plant"],
["el ramo", "bouquet"],
["clima templado", "temperate weather"],
["temperatura fresca", "cool temperature"],
["lloviznar", "to drizzle"],
["la brisa", "breeze"],


["Tengo un poco de frío", "I’m a bit cold"],
["sembrar", "to sow/to plant"],
["ir de picnic", "to have a picnic"],
["la limpieza de primavera", "spring cleaning"],
["el mar", "sea"],
["la arena", "sand"],
["el campo", "the country"],
["los mosquitos", "mosquitoes"],
["la fruta", "fruits"],
["la sandía", "watermelon"],
["la piña", "pineapple"],
["una barbacoa", "a barbecue"],
["el chicle", "chewing gum"],
["el helado", "ice cream"],
["colores vivos", "vibrant colors"],
["colores llamativos", "flashy colors"],
["azul", "blue"],
["amarillo", "yellow"],
["El clima", "the weather"],


["clima templado", "temperate weather"],
["temperaturas altas", "high temperatures"],
["el sol", "sun"],
["un día soleado", "a sunny day"],
["días largos", "long days"],
["noches cortas", "short nights"],
["Actividades", "activities"],

["las vacaciones de verano", "summer vacations"],
["tomar helado", "to have ice cream"],
["ir a la playa", "to go to the beach"],
["nadar", "to swim"],
["ir de viaje", "to go on a trip"],
["acampar, ir de acampada, or ir de camping", "to go camping"],
["una excursión", "a hike/a field trip"],
["relajarse", "to relax"],
["divertirse", "to have fun"],
["la Noche de San Juan", "Saint John’s Night"],


["El Día de los Padres", "Father’s Day"],
["fiestas", "parties"],
["La naturaleza", "nature"],

["la hoja", "leaf"],
["el árbol", "tree"],
["el tronco", "trunk"],
["el caracol", "snail"],
["el barro or el lodo", "mud"],
["cosecha", "harvest"],
["los colores", "colors"],

["marrón", "brown"],
["rojo", "red"],
["naranja or anaranjado", "orange"],
["colores cálidos", "warm colors"],
["el clima", "the weather"],

["el viento", "wind"],
["temperaturas en caída", "falling temperatures"],
["el cielo gris", "grey sky"],
["la tormenta", "storm"],
["La comida", "food"],

["el vino", "wine"],
["la manzana", "apple"],
["el maíz", "corn"],
["la calabaza", "pumpkin"],
["Actividades", "activities"],

["recoger hojas", "gather up leaves"],
["saltar en charcos", "jump into puddles"],
["bricolaje", "DIY"],
["hacer una fogata", "to build a bonfire"],
["La Fiesta de la Hispanidad", "Spanish Culture Day/October 12th"],

["Día de los Muertos", "Day of the Dead"],
["pureza", "purity"],


["La naturaleza", "nature"],

["la montaña", "mountain"],
["el muérdago", "mistletoe"],
["hibernación", "hibernation"],
["el pino", "pine"],
["Los colores", "colors"],

["colores fríos", "cold colors"],
["white", "blanco"],
["gris", "grey"],
["plata", "silver"],
["dorado", "golden"],
["El clima", "the weather"],

["temperaturas bajas", "low temperatures"],
["la nieve", "snow"],
["el hielo", "ice"],
["la escarcha", "frost"],
["las nubes", "clouds"],



["la bufanda", "scarf"],
["las medias/lo calcetines", "socks"],
["el abrigo", "coat"],
["las botas", "boots"],
["el gorro", "coat"],
["los guantes", "gloves"],
["La comida", "food"],

["la cena", "dinner"],
["chocolate a la taza/chocolate caliente", "hot chocolate"],
["bebidas calientes", "hot drinks"],
["la sopa", "soup"],
["Actividades", "activities"],

["hacer un muñeco/hombre de nieve", "to build a snowman"],
["tirar bolas de nieve", "to play snowballs"],
["vuna vuelta en trineo", "a sleigh ride"],
["celebrar", "to celebrate"],
["esquiar", "to ski"],
["patinar sobre hielo", "to ice skate"],
["snowboard", "to snowboard"],

["La ropa", "clothes"],
["la Navidad", "Christmas"],
["Nochebuena", "Christmas Eve/Good Night"],
["Nochevieja", "New Year’s Eve/Old Night"],
["Día de Año Nuevo", "New Year’s Day"],
["la Epifanía", "Epiphany"],
["Día de Reyes", "Day of the Kings"],
["Reyes Magos", "Three Wise Men"],
["San Valentín", "Valentine’s Day"],
["el Carnaval", "Carnival"],


["Jueves Lardero, Jueves Gordo, Jueves Graso, Jueves de Carnival", "Fat Thursday / Carnival Thursday"],
["El Miércoles de Cenizas", "Ash Wednesday"],
["¿Cuál es tu estación favorita?", "What’s your favorite season?"], 
["Mi estación favorita es…", "My favorite season is…"],
["¿Cuál es la estación que te gusta más?", "Which season do you like the most?"],
["La estación que más me gusta es…", "The season I like the most is…"],
["¿Cuál es la estación que te gusta menos?", "Which season do you like the least?"],
["La estación que menos me gusta es…", "The season I like the least is…"],
["Prefieres (el otoño) o (la primavera)?", "Do you prefer (autumn) or (spring)?"],
["Prefiero (el otoño), porque me gusta (el clima)", "I prefer (autumn) because I like (the weather)"],

["¿Qué te gusta más (del otoño)? / ¿Qué es lo que te gusta más (del otoño)?", "What do you like the most about (autumn)?"],
["Lo que me gusta más (del otoño) es…", "What I like the most about (autumn) is…"],
["Month", "Mes"],
["tres meses", "three months"],
["enero", "January"],
["febrero", "February"],
["marzo", "March"],
["abril", "April"],
["mayo", "May"],
["junio", "June"],
["julio", "July"],
["agosto", "August"],
["septiembre", "September"],
["octubre", "October"],
["noviembre", "November"],
["diciembre", "December"],
["un Junio caluroso", "a hot June"],
["un Diciembre frío", "a cold December"],

["in June", "en junio"],
["in December", "en diciembre"],
["el clima", "the weather"],
["hace frio", "“does cold”"],
["Hace calor/frío/fresco", "It’s hot/cold/cool"],
["Hace buen/mal tiempo", "The weather is good/bad"],
["Está soleado", "It’s sunny"],
["Está lloviendo", "It’s raining"],
["Está nevando", "It’s snowing"],
["Hay sol", "There’s sun"],
["Hay viento", "There’s wind"],
["”Hello” en español es “hola", "Hello in Spanish is hola"],
["Genial, ¡vamos!", "Great, let’s go!"],

["How Are You?", "¿Cómo estás?"],
["Hello, how are you?", "Hola, ¿cómo estás?"],
["How are you today?", "¿Cómo estás hoy?"],
["How Are You Doing?", "¿Cómo te va?"],
["Good, and you", "Bien, ¿y tú?"],
["Very well, thanks", "Muy bien, gracias"],
["Así así", "so-so"],
["Más o menos", "so-so"],
["Normal", "okay"],
["No tan bien", "Not so good"],
["No muy bien", "Not very well"],
["Mal", "bad"],
["Fatal", "awful"],
["What's Up", "¿Qué tal?"],

["¿Qué más?", "What else?"],
["¿Qué hay?", "What is there?/What’s happening?"],
["¿Qué hubo?", "What happened/ ¿Qué hay?"],
["¿Qué hay de nuevo?", "What’s new?"],
["¿Qué haces?", "What are you doing?"],
["Good Morning", "¡Buenos días!"],
["Good Afternoon", "¡Buenas tardes!"],
["Good Evening", "¡Buenas noches!"],
["Mucho gusto", "much pleasure/ Nice to Meet You"],
["Encantado/a", "glad/ Nice to Meet You"],
["¿Cómo te llamas?", "What’s your name?"],
["¿Cuál es tu nombre?", "What’s your name?"],
["Mi nombre es…", "My name is…"],
["Soy…", "I am…"],
["Me llamo…", "I am called…"],
["¡Bienvenido!/a", "Welcome"],
["Estimado/a Señor/Señora/Señorita", "Dear Sir/Mrs./Ms."],
["Distinguido/a Señor/Señora/Señorita", "Distinguished Sir/Mrs./Ms."],
["Querido/a…", "Dear…"],
["A quien corresponda", "To Whom it May Concern"],
["Gracias por llamar…", "Thank you for calling…"],
["En que le puedo ayudar?", "How may I help you?"],
["cordiales saludos", "best regards"],
["Dile hola a tu hermana", "Say hi to your sister"],
["Diles hola a tus primos", "Say hi to your cousins"],
["héroe/protagonista", "Hero"],
["el guerrero / la guerrera", "Warrior"],
["caballero de brillante armadura", "Knight in shining armor"],
["un dios / una diosa", "A god or goddess"],
["el semidiós / la semidiosa", "Demigod"],
["el soldado", "Soldier"],
["pacificadora", "Peacekeeper"],
["el campeón / la campeona", "Champion"],
["el capitán / la capitana", "Captain"],
["el prefesor / la profesora", "Professor"],
["los mutantes", "Mutants"],
["el vengador / la vengadora", "Avenger"],

["Thor, dios del trueno", "Thor, God of Thunder"],
["El Soldado de Invierno", "The Winter Sollder"],
["maestro jedi", "jedi master"],
["mi héroe", "my hero"],
["Los Vengadores", "The Avengers"],
["Hawkeye", "Ojo de Halcón"],
["Viuda Negra", "Black Widow"],
["Máquina de Guerra", "War Machine"],
["Pantera Negra", "Black Panther"],
["La Avispa", "The Wasp"],
["miembros del equipo", "team members"],



["Identidad secreta", "Secret identity"],
["La máscara", "Mask"],
["Capa", "Cape"],
["Enemigo / Enemiga", "Enemy"],
["Origen", "Origin"],
["El centro de comando", "Command center"],
["El compañero / La compañera", "Sidekick"],
["El universo", "Universe"],
["La galaxia", "Galaxy"],
["La astronave", "Spaceship"],
["La batalla", "Battle"],
["La guerra", "War"],
["Los inmortales", "Immortals"],
["El poder", "Power"],
["La responsabilidad", "Responsibility"],
["El deber", "Duty"],
["El villano malvado / La villana malvada", "Evil Villain"],
["Rescatar", "Rescue"],
["Salvar", "Save"],
["Proteger", "Protect"],
["Guardar", "Guard"],
["Luchar", "Fight"],


["cine / película", "movie"],
["el libro cómico", "comic book"],
["Me encantan las películas de superhéroes", "I love superhero movies"],




["ladrar", "to bark"],

["El perro seguía ladrando", "The dog kept barking"],
["Hubo una fuerte explosión, como ¡PATAPLUM!", "There was a loud explosion, like ‘BOOM!’"],


["Pataplum", "Boom"],
["Ñeec", "Squeak"],
["Zasca", "Bang"],
["Zas", "Zap"],
["Plaf", "Splash"],
["Pum", "Pow"],
["Ñam, ñam", "Om nom nom"],
["Jajaja", "Hahaha"],
["Rin", "Ding"],
["Achí", "Achoo"],
["Chinchín", "Clink"],
["Siseo", "Hiss"],
["Tan, tan", "Clank, clank"],
["Toc toc", "Knock knock"],
["Crag", "Crack"],



["Araña", "Spidergirl"],


["¿Cómo te llamas?", "What’s your name?"],

["Me llamo David. ¿Y tú, cómo te llamas?", "My name is David. And you, what is your name?"],
["¡ Hola! Mucho gusto. ¿Cómo te llamas?", "Hi ! Nice to meet you. What is your name?"],

 

["¿Puedes ayudarme, por favor?", "Could you help me, please?"],

 

["¿De dónde eres?", "Where are you from?"],

["No reconozco su acento. ¿De dónde es usted?", "I don’t recognize your accent.  Where are you from?"],

["Yo soy de Venezuela. ¿De dónde eres tú?", "I’m from Venezuela. Where are you from?"],

 

["¿Hablas inglés?", "Do you speak English?"],
["¿Hablas inglés en la casa?", "Do you speak English at home?"],
["¿Dónde está el baño?", "Where is the washroom?"],

["¿Estás bien?", "Are you alright?"],
["Te ves pálido", "You look pale"],
["¿Dónde está el baño?", "Where’s the toilet?"],
["¿Dónde vives?", "Where do you live?"],
["Te llevaré a casa", "I will drive you home"],
["¿Cuántos años tienes?", "How old are you?"],
["Tengo trenta años", "I’m thirty years old"],
["¿Te gusta _______?", "Do you like _______?"],
["¿Te gusta este cancion?", "Do you like this song?"],
["¿Cuál es tu _______?", "Which/What is your ______?"],
["¿Cuál es tu película favorita?", "Which/What is your favorite movie?"],
["Cuál es su número de teléfono?", "What’s your telephone number?"],
["¿Que haces ________?", "What are you doing ______?"],
["¿Que haces esta noche?", "What are you doing tonight?"],
["Por qué no?", "Why not?"],
["¿Y usted?", "And you?"],
["¿Qué hora es?", "What time is it?"],
["Es la una de la tarde", "It’s one in the afternoon"],
["Disculpe, ¿sabe usted qué hora es?", "Excuse me, do you know what time it is?"],
["¿Hay un(a) ______ cerca?", "Is there a ______ close by?"],
["¿Hay un banco cerca?", "Is there a bank nearby?"],
["¿Como llego a el/la ______?", "How do I get to ______?"],
["¿Como llego a el aeropuerto?", "How do I get to the airport?"],
["¿Como llego a la playa?", "How do I get to the beach?"],
["¿Qué significa esta palabra?", "What does this word mean?"],
["Qué tiempo hace?", "What’s the weather like?"],
["¿Qué tiempo hace? Hace sol y bastante calor", "What’s the weather like? It’s sunny and quite hot"],
["Quiero un/una _______", "I would like a ________"],
["Quiero una cerveza", "I would like a beer"],
["Quiero un café", "I would like a coffee"],
["¿Cuánto es?", "How much is that?"],
["¿Quieren pagar juntos o por separado?", "Do you want to pay together or separately?"],
["¿Tienes un/una______?", "Do you have a ________?"],
["¿Tienes chicle?", "Do you have gum?"],
["¿Dispone usted de información más precisa sobre este tema?", "Do you have more precise information on this subject?"],
["¿Quién es?", "Who’s there?"],
["¿Comprende?", "Do you understand?"],
["¿Adónde va usted?", "Where are you going?"],
["Where are you going? You have to leave in ten minutes!", "¿Para dónde vas? ¡Te tienes que ir en diez minutos!"],
["What are you waiting for?", "¡Vamos!"],
["Al Mal Tiempo, Buena Cara", "When the Going Gets Rough, the Tough Gets Going"],
["Mas Vale Pájaro en Mano Que Cien Volando", "A Bird in the Hand is Worth Two in the Bush"],
["A los Tontos No les Dura el Dinero", "A Fool and his Money Are Soon Parted"],
["La Verdad Adelgaza, pero No Quiebra", "The Truth May Be Stretched Thin, but It Never Breaks"],
["Errar Es Humano, pero Más Lo Es Culpar de Ello a Otros", "To Err Is Human, but It Is Even More So to Blame Others for It"],
["Haciendo y Deshaciendo Se Va Aprendiendo", "It’s By Doing and Undoing That We Learn"],
["El Que No Arriesga, No Gana", "He Who Doesn’t Risk Doesn’t Gain Anything"],
["La Acción Es la Clave Fundamental para Todo Éxito", "Action Is the Foundational Key to All Success"],
["El Hombre Que Se Levanta Es Aún Más Grande Que El Que No Ha Caído", "The Man Who Stands Up Is Greater Than the One Who Hasn’t Fallen"],
["El Arte de Vencer se Aprende en las Derrotas", "The Art of Winning is Learnt Through Losses"],
["Tal Vez Sea Verdad: Que un Corazón Es lo Que Mueve el Mundo", "Perhaps It Is True: It Is a Heart Which Moves the World"],
["El Amor Todo lo Puede", "Love Conquers All"],
["La Belleza Que Atrae Rara Vez Coincide Con la Belleza Que Enamora", "The Beauty That Attracts Rarely Matches The Beauty That Makes You Fall In Love"],
["El Amor No Respeta la Ley, Ni Obedece a Rey", "Love Laughs at Locksmiths"],
["De Tal Palo, Tal Astilla", "Like Father/Mother, Like Son/Daughter"],
["Lo Importante En una Familia No Es Estar Juntos Sino Estar Unidos", "What’s Important In a Family Is Not to Be Together, It’s to Be United"],
["Dime Con Quién Andas y Te Diré Quien Eres", "You Are the Company You Keep"],
["La Soledad Es Muy Hermosa… Cuando Se Tiene Alguien a Quien Decírselo", "Solitude Is Very Beautiful… When You Have Someone Whom to Tell It To"],
["Hoy Por Ti, Mañana Por Mí", "You Scratch My Back, I’ll Scratch Yours"],
["Más Vale Prevenir Que Curar", "Better Safe Than Sorry"],
["El Tiempo Todo Lo Cura", "Time Heals Everything"],
["A Lo Hecho, Pecho", "What Is Done Is Done"],
["El Amor Es Como Don Quijote: Cuando Recobra el Juicio Es que Está Para Morir", "Love Is Like Don Quixote: When It Regains Its Judgement, It’s About to Die"],
["Si Hay Trato, Pueden Ser Amigos Perro y Gato", "If There Is a Deal, Even a Dog and a Cat Can Be Friends"],
["Dame Pan y Dime Tonto", "Give Me Bread and Call Me a Fool"],
["Donde No Puedas Amar, No Te Demores", "Where You Can't Love, Don't Stay Too Long"],
["Enamórate de Ti, de la Vida y Luego de Quien Tú Quieras", "Fall in Love With Yourself, With Life and Then With Whoever You Want"],
["Si Actúas Como Si Supieras Lo Que Estás Haciendo, Puedes Hacer Lo Que Quieras", "If You Act as if You Knew What You Were Doing, You Can Do Whatever You Want"],
["La Historia Nunca Dice “Adiós”. Lo Que Dice Siempre Es un “Hasta Luego”", "History Never Says ‘Farewell’. What It Always Says is Goodbye"],

 
];

