let spanish = [ ["de", "of"],
["que", "what"],
["no", "not"],
["a", "to"],
["la", "the"],
["el", "he"],
["es", "is"],
["en", "in"],
["lo", "the"],
["un", "a"],
["por", "by"],
["qué", "what"],
["me", "I"],
["una", "a"],
["te", "tea"],
["se", "I know"],
["los", "the"],
["con", "with"],
["para", "for"],
["mi", "me"],
["está", "this"],
["si", "yes"],
["sí", "yes"],
["pero", "but"],
["las", "the"],
["bien", "good"],
["yo", "me"],
["su", "his"],
["eso", "that"],
["aquí", "here"],
["del", "of the"],
["al", "to the"],
["como", "how"],
["le", "you"],
["tu", "you"],
["más", "plus"],
["todo", "all"],
["ya", "already"],
["muy", "very"],
["esto", "this"],
["vamos", "Lets go"],
["ha", "he has"],
["ahora", "now"],
["esta", "this"],
["hay", "there are"],
["estoy", "am"],
["algo", "something"],
["tú", "you"],
["tengo", "I have"],
["así", "So"],
["nada", "nothing"],
["nos", "us"],
["cuando", "when"],
["cómo", "how"],
["él", "he"],
["sé", "I know"],
["estás", "these"],
["sólo", "single"],
["o", "or"],
["quiero", "I want"],
["este", "this"],
["tiene", "have"],
["gracias", "thanks"],
["he", "I"],
["puedo", "may l"],
["bueno", "good"],
["soy", "I am"],
["era", "was"],
["ser", "to be"],
["vez", "time"],
["hacer", "do"],
["todos", "everybody"],
["ella", "she"],
["son", "They are"],
["fue", "it was"],
["eres", "you are"],
["usted", "you"],
["tienes", "you have"],
["puede", "may"],
["señor", "Sir"],
["ese", "that"],
["voy", "I go"],
["quién", "who"],
["casa", "house"],
["creo", "I think"],
["porque", "why"],
["tan", "so"],
["hola", "hello"],
["dónde", "where"],
["nunca", "never"],
["sus", "their"],
["sabes", "you know"],
["dos", "two"],
["verdad", "true"],
["quieres", "you want"],
["mucho", "a lot"],
["entonces", "so"],
["estaba", "I was"],
["tiempo", "weather"],
["mí", "me"],
["esa", "that"],
["mejor", "best"],
["hombre", "man"],
["hace", "does"],
["va", "goes"],
["dios", "God"],
["también", "too"],
["has", "you"],
["vida", "lifetime"],
["sin", "without"],
["están", "is it so"],
["ver", "watch"],
["sr", "Mr"],
["siempre", "always"],
["oh", "oh"],
["hasta", "until"],
["ti", "you"],
["ahí", "there"],
["siento", "sorry"],
["puedes", "you may"],
["decir", "tell"],
["ni", "neither"],
["sobre", "on"],
["años", "years"],
["tenemos", "we have"],
["uno", "one"],
["día", "day"],
["noche", "night"],
["cosas", "stuff"],
["alguien", "someone"],
["antes", "before"],
["mis", "my"],
["ir", "go"],
["poco", "little bit"],
["otra", "other"],
["quiere", "wants"],
["solo", "alone"],
["nadie", "nobody"],
["nosotros", "us"],
["padre", "father"],
["gente", "people"],
["parece", "It seems"],
["dinero", "money"],
["estar", "to be"],
["hecho", "done"],
["les", "them"],
["mismo", "same"],
["sea", "be"],
["estamos", "we are"],
["mira", "look"],
["pasa", "pass"],
["trabajo", "job"],
["dijo", "He said"],
["ellos", "they"],
["vas", "you go"],
["claro", "Sure"],
["mañana", "tomorrow"],
["han", "They have"],
["otro", "other"],
["después", "then"],
["desde", "since"],
["mundo", "world"],
["hablar", "talk"],
["tal", "such"],
["había", "there were"],
["sabe", "knows"],
["acuerdo", "agreement"],
["momento", "moment"],
["donde", "where"],
["fuera", "outside"],
["hijo", "son"],
["podría", "might"],
["seguro", "sure"],
["mujer", "woman"],
["amigo", "friend"],
["días", "days"],
["madre", "mother"],
["allí", "there"],
["cosa", "thing"],
["tus", "your"],
["lugar", "place"],
["dice", "He says"],
["gusta", "like"],
["será", "will be"],
["gran", "great"],
["mierda", "shit"],
["tenía", "I had"],
["mamá", "mom"],
["papá", "dad"],
["espera", "wait"],
["hoy", "today"],
["tener", "to have"],
["ven", "come"],
["buena", "good"],
["estado", "state"],
["nuevo", "new"],
["luego", "then"],
["podemos", "we can"],
["tres", "three"],
["dije", "said"],
["nuestro", "our"],
["sido", "been"],
["menos", "less"],
["debe", "should"],
["tipo", "type"],
["buen", "good"],
["conmigo", "with me"],
["mal", "evil"],
["todas", "all"],
["nombre", "Name"],
["haciendo", "doing"],
["crees", "think"],
["toda", "all"],
["amor", "love"],
["mío", "Own"],
["visto", "viewed"],
["estas", "these"],
["quería", "wanted to"],
["eh", "Hey"],
["tarde", "late"],
["importa", "matters"],
["parte", "part"],
["aún", "yet"],
["nuestra", "our"],
["tienen", "they have"],
["tanto", "so much"],
["cada", "each"],
["hora", "time"],
["veces", "times"],
["necesito", "needed"],
["contigo", "with you"],
["ve", "go"],
["haber", "to have"],
["buenas", "good"],
["dicho", "saying"],
["quien", "who"],
["hacerlo", "do what"],
["demasiado", "too"],
["oye", "hears"],
["haces", "do"],
["hombres", "mens"],
["saber", "to know"],
["entre", "between"],
["adiós", "goodbye"],
["problema", "trouble"],
["unos", "some"],
["vaya", "go"],
["hemos", "we have"],
["cierto", "true"],
["debo", "I must"],
["razón", "reason"],
["alguna", "any"],
["esos", "those"],
["pues", "well"],
["veo", "I see"],
["idea", "idea"],
["chica", "girl"],
["realmente", "Really"],
["policía", "policeman"],
["hizo", "did"],
["estos", "these"],
["amigos", "friends"],
["ustedes", "your"],
["quizá", "maybe"],
["serio", "I laughed"],
["cabeza", "head"],
["hermano", "brother"],
["digo", "I say"],
["van", "go"],
["pasado", "past"],
["salir", "get out"],
["cuenta", "account"],
["familia", "family"],
["cariño", "sweetie"],
["vale", "okay"],
["algún", "some"],
["muchas", "many"],
["señora", "Ms"],
["somos", "we are"],
["pueden", "they can"],
["noches", "nights"],
["muerto", "dead"],
["ud", "you"],
["todavía", "still"],
["rápido", "quick"],
["viejo", "old"],
["lado", "side"],
["debería", "should"],
["ves", "you see"],
["sabía", "I knew"],
["suerte", "luck"],
["cuidado", "watch out"],
["buenos", "good ones"],
["sería", "would"],
["da", "gives"],
["mientras", "while"],
["miedo", "fear"],
["primera", "first"],
["contra", "against"],
["puerta", "door"],
["pronto", "soon"],
["e", "and"],
["casi", "almost"],
["nueva", "new"],
["espero", "I hope"],
["cualquier", "any"],
["esas", "those"],
["agua", "water"],
["os", "you"],
["chico", "boy"],
["cuánto", "how much"],
["niños", "children"],
["venga", "come on"],
["camino", "road"],
["primero", "first"],
["hacia", "toward"],
["pensé", "I thought"],
["dentro", "inside"],
["pasó", "he passed"],
["debes", "you must"],
["ciudad", "city"],
["historia", "history"],
["año", "year"],
["viene", "comes"],
["deja", "let"],
["durante", "during"],
["forma", "shape"],
["volver", "return"],
["feliz", "happy"],
["ojos", "eyes"],
["guerra", "war"],
["caso", "case"],
["chicos", "boys"],
["esposa", "wife"],
["adelante", "ahead"],
["cuál", "which one"],
["mano", "hand"],
["hice", "I did"],
["vi", "saw"],
["gustaría", "would like"],
["muerte", "death"],
["allá", "there"],
["mas", "more"],
["loco", "crazy"],
["supuesto", "supposed"],
["toma", "taking"],
["minutos", "minutes"],
["haré", "I will do"],
["entiendo", "I get it"],
["pasar", "pass"],
["iba", "I was going"],
["corazón", "heart"],
["semana", "week"],
["jefe", "boss"],
["venir", "come"],
["manos", "hands"],
["ayuda", "help"],
["problemas", "problems"],
["juntos", "together"],
["supongo", "I suppose"],
["déjame", "let me"],
["importante", "important"],
["vete", "go away"],
["niño", "child"],
["arriba", "up"],
["hija", "daughter"],
["otros", "others"],
["sra", "Mrs"],
["personas", "people"],
["tierra", "land"],
["manera", "way"],
["hablando", "talking"],
["fin", "end"],
["mujeres", "women"],
["cara", "face"],
["grande", "big"],
["ningún", "any"],
["nuestros", "our"],
["cinco", "five"],
["llama", "call"],
["hey", "hey"],
["habla", "speaks"],
["bajo", "low"],
["dices", "say"],
["poder", "power"],
["cuándo", "when"],
["quizás", "maybe"],
["escucha", "listens"],
["persona", "person"],
["horas", "hours"],
["tío", "uncle"],
["aunque", "although"],
["io", "io"],
["único", "only"],
["dijiste", "said"],
["siquiera", "at least"],
["quieren", "they want"],
["ninguna", "none"],
["cerca", "close"],
["pequeño", "little"],
["debemos", "we must"],
["cree", "cree"],
["dame", "give to me"],
["sigue", "follow"],
["auto", "car"],
["cuatro", "four"],
["dejar", "leave"],
["muchos", "Many"],
["igual", "same"],
["hago", "I make"],
["listo", "ready"],
["significa", "it means"],
["capitán", "captain"],
["clase", "class"],
["llegar", "to get"],
["suficiente", "enough"],
["tomar", "drink"],
["vivir", "to live"],
["joven", "young"],
["trabajar", "to work"],
["haya", "beech"],
["abajo", "down"],
["hubiera", "had"],
["primer", "first"],
["genial", "great"],
["justo", "fair"],
["pensar", "think"],
["misma", "same"],
["puta", "bitch"],
["comer", "eat"],
["necesita", "needs to"],
["conozco", "I know"],
["fui", "I was"],
["algunos", "some"],
["entrar", "get in"],
["fuerte", "strong"],
["número", "number"],
["srta", "Ms"],
["morir", "To die"],
["basta", "Enough"],
["dar", "give"],
["bastante", "quite"],
["amo", "love"],
["atrás", "behind"],
["dicen", "say"],
["difícil", "difficult"],
["éste", "this"],
["pueda", "can"],
["punto", "point"],
["vino", "wine"],
["hermana", "sister"],
["hijos", "sons"],
["unas", "nail"],
["final", "final"],
["escuela", "school"],
["podía", "I could"],
["pueblo", "village"],
["haga", "make"],
["sangre", "blood"],
["meses", "months"],
["coche", "car"],
["juego", "game"],
["encontrar", "find"],
["realidad", "reality"],
["cuerpo", "body"],
["mayor", "higher"],
["última", "last"],
["eran", "they were"],
["queda", "remains"],
["ok", "okay"],
["paz", "peace"],
["dime", "tell me"],
["vuelta", "return"],
["hiciste", "did"],
["tenido", "had"],
["sola", "alone"],
["hacen", "make"],
["ido", "gone"],
["querida", "Dear"],
["iré", "I will go"],
["culpa", "guilt"],
["malo", "bad"],
["chicas", "girls"],
["comida", "food"],
["dólares", "dollars"],
["dr", "dr"],
["saben", "they know"],
["fácil", "easy"],
["alto", "high"],
["posible", "possible"],
["maldito", "damned"],
["dormir", "sleep"],
["deberías", "you should"],
["maldita", "damn"],
["pregunta", "question"],
["incluso", "even"],
["fiesta", "party"],
["tampoco", "neither"],
["cama", "bed"],
["lejos", "far"],
["medio", "means, medium"],
["preocupes", "worry"],
["ay", "Oh"],
["teléfono", "phone"],
["diga", "tell"],
["ei", "ei"],
["trata", "about"],
["equipo", "team"],
["palabra", "word"],
["cuanto", "how much"],
["idiota", "moron"],
["esté", "this"],
["luz", "light"],
["tuve", "I had"],
["país", "country"],
["segundo", "second"],
["querido", "Dear"],
["diablos", "devils"],
["hagas", "you do"],
["señorita", "miss"],
["oportunidad", "opportunity"],
["matar", "kill"],
["algunas", "some"],
["esperando", "waiting"],
["necesitamos", "we need"],
["adónde", "where"],
["verte", "to see you"],
["estará", "will be"],
["venido", "I come"],
["estabas", "you were"],
["fueron", "were"],
["seis", "six"],
["tenga", "have"],
["cuarto", "room"],
["cielo", "heaven"],
["vivo", "alive"],
["recuerdo", "memory"],
["perdón", "sorry"],
["falta", "lack"],
["pequeña", "little"],
["oído", "ear"],
["creer", "believe"],
["pienso", "I think"],
["ésta", "this"],
["esperar", "wait"],
["necesitas", "you need"],
["aqui", "here"],
["película", "movie"],
["además", "further"],
["marido", "husband"],
["perro", "dog"],
["general", "general"],
["calle", "Street"],
["exactamente", "exactly"],
["rey", "king"],
["padres", "parents"],
["lista", "list"],
["habrá", "there will be"],
["habitación", "room"],
["pensando", "thinking"],
["par", "pair"],
["fuego", "fire"],
["niña", "girl"],
["seguir", "follow"],
["música", "music"],
["di", "gave"],
["habría", "there would be"],
["mucha", "a lot"],
["paso", "He passed"],
["sentido", "sense"],
["diré", "I will say"],
["podrías", "could you"],
["afuera", "outside"],
["digas", "you say"],
["ia", "ia"],
["mía", "mine"],
["murió", "died"],
["dio", "it gave"],
["café", "coffee"],
["entiendes", "You understand"],
["nuestras", "our"],
["piensa", "think"],
["ello", "it"],
["lleva", "carries"],
["estuvo", "he was"],
["último", "latest"],
["diciendo", "saying"],
["grandes", "big"],
["sitio", "site"],
["libro", "book"],
["buscando", "searching"],
["bebé", "baby"],
["cállate", "shut up"],
["vuelve", "returns"],
["jamás", "Never"],
["minuto", "minute"],
["arma", "weapon"],
["viaje", "travel"],
["única", "only"],
["muchachos", "boys"],
["perdido", "lost"],
["jugar", "to play"],
["diez", "ten"],
["vemos", "we see"],
["dado", "dice"],
["sabemos", "we know"],
["mil", "thousand"],
["demás", "the rest"],
["gusto", "taste"],
["peor", "worst"],
["irme", "leave"],
["estaban", "They were"],
["orden", "order"],
["pasando", "going"],
["cambio", "change"],
["extraño", "strange"],
["pobre", "poor"],
["ropa", "clothing"],
["queremos", "we want"],
["oficina", "office"],
["sino", "if not"],
["modo", "mode"],
["ocurre", "occurs"],
["muchacho", "boy"],
["otras", "other"],
["hará", "will"],
["libre", "free"],
["conoces", "know"],
["piensas", "think"],
["presidente", "President"],
["especial", "special"],
["anoche", "last night"],
["millones", "millions"],
["acerca", "about"],
["derecho", "law"],
["negro", "black"],
["acá", "here"],
["caballeros", "gentlemen"],
["semanas", "weeks"],
["palabras", "words"],
["buscar", "search for"],
["segura", "safe"],
["correcto", "Right"],
["frente", "front"],
["hacemos", "we make"],
["seas", "be"],
["detrás", "behind"],
["puesto", "Market Stall"],
["asunto", "affair"],
["duro", "Lasted"],
["sucede", "happens"],
["llamar", "to call"],
["disculpe", "sorry"],
["boca", "mouth"],
["atención", "Attention"],
["mire", "Look"],
["armas", "weapons"],
["encima", "over"],
["demonios", "got damn"],
["mala", "bad"],
["llevar", "wear"],
["cual", "which one"],
["odio", "hate"],
["deben", "should"],
["sueño", "dream"],
["quieras", "want"],
["resto", "rest"],
["llamo", "I call"],
["perder", "to lose"],
["llamado", "called"],
["perfecto", "perfect"],
["estaré", "I will be"],
["tranquilo", "quiet"],
["seguridad", "security"],
["ayudar", "help"],
["tuvo", "He had"],
["largo", "long"],
["pena", "pain"],
["probablemente", "probably"],
["ayer", "yesterday"],
["dile", "tell him"],
["prueba", "proof"],
["siendo", "being"],
["bonito", "beautiful"],
["recuerdas", "remember"],
["haz", "make"],
["real", "real"],
["veras", "youll see"],
["increíble", "amazing"],
["quisiera", "I would like"],
["tonto", "fool"],
["simplemente", "simply"],
["vámonos", "Lets go"],
["haría", "would do"],
["preguntas", "questions"],
["aire", "air"],
["conoce", "known"],
["fuerza", "strength"],
["carta", "letter"],
["trato", "treatment"],
["plan", "plan"],
["ése", "that"],
["verlo", "see him"],
["hambre", "hungry"],
["vuelto", "turned"],
["empezar", "start"],
["campo", "countryside"],
["acaba", "just"],
["hablas", "speak"],
["vive", "lives"],
["barco", "ship"],
["hotel", "hotel"],
["poner", "set"],
["grupo", "group"],
["creí", "thought"],
["sol", "Sun"],
["tuyo", "of yours"],
["pase", "pass"],
["joe", "joe"],
["voz", "voice"],
["baño", "bathroom"],
["usar", "use"],
["conseguir", "get"],
["placer", "pleasure"],
["llegado", "arrived"],
["decirte", "tell you"],
["profesor", "Teacher"],
["noticias", "news"],
["lamento", "lament"],
["decirle", "tell"],
["blanco", "white"],
["quédate", "stay"],
["estuve", "I was"],
["pie", "foot"],
["anda", "anda"],
["espere", "Wait"],
["edad", "age"],
["secreto", "secret"],
["podríamos", "we could"],
["compañía", "company"],
["tren", "train"],
["recuerda", "remember"],
["tras", "after"],
["siéntate", "Sit down"],
["prisa", "rush"],
["vista", "view"],
["hermosa", "beautiful"],
["negocio", "deal"],
["deberíamos", "we should"],
["gustan", "like"],
["pagar", "pay"],
["george", "george"],
["futuro", "future"],
["silencio", "silence"],
["siente", "feels"],
["médico", "doctor"],
["maestro", "teacher"],
["quiera", "want"],
["llegó", "I arrive"],
["loca", "crazy"],
["cambiar", "change"],
["frank", "frank"],
["sal", "salt"],
["control", "control"],
["raro", "rare"],
["viste", "dresses"],
["novia", "girlfriend"],
["diferente", "different"],
["imposible", "impossible"],
["amiga", "friend"],
["enseguida", "right away"],
["llamada", "call"],
["dan", "give"],
["dejó", "left"],
["mes", "month"],
["llevo", "I wear"],
["avión", "plane"],
["pelo", "hair"],
["the", "the"],
["error", "error"],
["haremos", "will"],
["tendrá", "will have"],
["propia", "own"],
["siguiente", "following"],
["ganar", "win"],
["ley", "law"],
["dolor", "pain"],
["oro", "gold"],
["ten", "ten"],
["acabó", "finished"],
["maldición", "damn"],
["oficial", "official"],
["situación", "situation"],
["daño", "hurt"],
["sientes", "you feel"],
["entendido", "it is understood"],
["deseo", "wish"],
["mente", "mind"],
["ejército", "army"],
["comprar", "to buy"],
["muertos", "dead"],
["pensaba", "thought"],
["darle", "give him"],
["estúpido", "stupid"],
["decía", "He said"],
["acabo", "finished"],
["suena", "it sounds"],
["mitad", "half"],
["caballo", "horse"],
["asesino", "assassin"],
["vio", "he saw"],
["permiso", "excuse me"],
["ellas", "they"],
["trabajando", "working"],
["maravilloso", "wonderful"],
["mesa", "table"],
["divertido", "funny"],
["mejores", "top"],
["próxima", "next"],
["entra", "enters"],
["tom", "tom"],
["mar", "sea"],
["siete", "seven"],
["hacía", "toward"],
["sexo", "sex"],
["encanta", "love"],
["amable", "nice"],
["mensaje", "message"],
["información", "information"],
["traje", "suit"],
["alma", "soul"],
["encontrado", "found"],
["coronel", "colonel"],
["dale", "go ahead"],
["san", "saint"],
["cena", "dinner"],
["encontré", "I found"],
["charlie", "charlie"],
["tendrás", "you will have"],
["eras", "ages"],
["propio", "own"],
["culo", "ass"],
["asi", "so"],
["adentro", "indoors"],
["canción", "song"],
["gobierno", "government"],
["sam", "sam"],
["temo", "fear"],
["abre", "opens"],
["dijeron", "they said"],
["fuiste", "you were"],
["media", "half"],
["das", "you give"],
["estábamos", "we were"],
["estaría", "It would"],
["daré", "I will give"],
["vosotros", "you"],
["frío", "cold"],
["foto", "photo"],
["accidente", "accident"],
["derecha", "right"],
["funciona", "works"],
["vayas", "go"],
["centro", "center"],
["necesario", "necessary"],
["miren", "look"],
["bonita", "pretty"],
["ante", "before"],
["terrible", "terrible"],
["pude", "I could"],
["teniente", "lieutenant"],
["luna", "moon"],
["izquierda", "left"],
["uds", "You"],
["doy", "I give"],
["servicio", "service"],
["llamas", "calls"],
["normal", "normal"],
["junto", "together"],
["tienda", "store"],
["navidad", "Christmas"],
["dirección", "direction"],
["abuela", "grandmother"],
["alrededor", "around"],
["vine", "came"],
["tendré", "I will have"],
["libertad", "freedom"],
["sale", "comes out"],
["línea", "line"],
["abogado", "attorney"],
["pies", "feet"],
["honor", "honor"],
["tratando", "trying"],
["regresar", "to return"],
["hablo", "I speak"],
["vieja", "old woman"],
["papel", "paper"],
["terminado", "finished"],
["dejado", "left"],
["juro", "I swear"],
["hermoso", "beautiful"],
["dulce", "candy"],
["sentir", "feel"],
["principio", "beginning"],
["interesante", "interesting"],
["caja", "box"],
["cualquiera", "anyone"],
["ocho", "eight"],
["horrible", "horrible"],
["respuesta", "answer"],
["perra", "female dog"],
["gracioso", "funny"],
["trae", "brings"],
["personal", "personal"],
["mató", "he killed"],
["completamente", "completely"],
["paul", "paul"],
["vienen", "they come"],
["sean", "are"],
["llega", "arrives"],
["abuelo", "grandfather"],
["tengas", "you have"],
["linda", "cute"],
["tendremos", "we will have"],
["michael", "Michael"],
["partes", "parts"],
["cárcel", "jail"],
["hubo", "there was"],
["sistema", "system"],
["lindo", "cute"],
["director", "director"],
["hazlo", "do it"],
["hicieron", "they made"],
["tía", "aunt"],
["busca", "search"],
["don", "Don"],
["baja", "low"],
["pudo", "could"],
["salud", "health"],
["listos", "ready"],
["cita", "appointment"],
["tenías", "had"],
["negocios", "business"],
["tipos", "types"],
["cámara", "camera"],
["agente", "agent"],
["verás", "youll see"],
["infierno", "hell"],
["regalo", "present"],
["río", "river"],
["través", "through"],
["carne", "meat"],
["totalmente", "totally"],
["decirme", "tell me"],
["piso", "floor"],
["esposo", "husband"],
["oír", "hear"],
["harry", "harry"],
["sargento", "sergeant"],
["deje", "leave"],
["tuya", "yours"],
["ambos", "both of them"],
["beber", "to drink"],
["calma", "calm"],
["vestido", "dress"],
["salvo", "except"],
["ésa", "that"],
["verdadero", "true"],
["basura", "garbage"],
["suelo", "floor"],
["carrera", "career"],
["cumpleaños", "birthday"],
["rato", "little while"],
["iremos", "we ll go"],
["universidad", "college"],
["bailar", "dance"],
["triste", "sad"],
["iglesia", "church"],
["delante", "in front of"],
["nena", "baby"],
["banco", "bank"],
["cuántos", "how many"],
["encuentra", "find"],
["supone", "supposed"],
["existe", "exists"],
["programa", "program"],
["alegro", "glad"],
["santo", "holy"],
["porqué", "why"],
["novio", "boyfriend"],
["broma", "joke"],
["diría", "would say"],
["salió", "he left"],
["jesús", "Jesus"],
["prometo", "I promise"],
["partido", "match"],
["pregunto", "I ask"],
["radio", "radio"],
["vuelva", "return"],
["cenar", "dinner"],
["ocurrió", "occurred"],
["creía", "thought"],
["corre", "run"],
["disculpa", "excuse"],
["vienes", "you come"],
["cerveza", "beer"],
["muerta", "dead"],
["pensado", "thought-out"],
["destino", "destination"],
["bob", "bob"],
["matrimonio", "marriage"],
["fotos", "photos"],
["diablo", "devil"],
["volveré", "I will be back"],
["saberlo", "I know"],
["cielos", "heavens"],
["norte", "north"],
["sala", "room"],
["órdenes", "orders"],
["según", "according"],
["harás", "you will do"],
["ataque", "attack"],
["parís", "Paris"],
["ejemplo", "example"],
["sorpresa", "surprise"],
["té", "tea"],
["pudiera", "could"],
["baile", "dance"],
["club", "club"],
["temprano", "early"],
["público", "public"],
["tí", "you"],
["oí", "heard"],
["mirando", "looking"],
["ventana", "window"],
["conocido", "known"],
["duda", "doubt"],
["boda", "wedding"],
["peligro", "danger"],
["trabaja", "working"],
["quise", "I wanted"],
["querías", "wanted"],
["caliente", "hot"],
["escribir", "to write"],
["reina", "queen"],
["esperaba", "I expected"],
["embargo", "embargo"],
["sur", "south"],
["enfermo", "sick"],
["excelente", "Excellent"],
["pone", "places"],
["escena", "scene"],
["encuentro", "meeting"],
["asesinato", "murder"],
["mike", "mike"],
["obra", "work"],
["veré", "I will see"],
["llamó", "I call"],
["aquel", "that"],
["terminar", "finish"],
["ganas", "forward"],
["conocer", "know"],
["pruebas", "tests"],
["señores", "Sirs"],
["vos", "you"],
["escúchame", "listen to me"],
["veamos", "lets see"],
["creen", "believe"],
["aun", "yet"],
["ninguno", "none"],
["parecía", "looked like"],
["mary", "mary"],
["viva", "live"],
["apenas", "barely"],
["segunda", "second"],
["bill", "bill"],
["llave", "key"],
["regreso", "Return"],
["trasero", "rear"],
["ojalá", "hopefully"],
["veremos", "we will see"],
["simple", "simple"],
["seré", "I will be"],
["irse", "leave"],
["cartas", "letters"],
["libros", "books"],
["apuesto", "handsome"],
["leer", "read"],
["imbécil", "fool"],
["opinión", "opinion"],
["cambiado", "changed"],
["sucedió", "it happened"],
["señal", "signal"],
["habían", "they had"],
["agradable", "nice"],
["cocina", "kitchen"],
["relación", "relationship"],
["sueños", "dreams"],
["segundos", "seconds"],
["corte", "cut"],
["escuchar", "hear"],
["cerebro", "brain"],
["locura", "madness"],
["peligroso", "dangerous"],
["hermanos", "siblings"],
["entender", "understand"],
["cine", "movie theater"],
["dejes", "leave"],
["reunión", "meeting"],
["tendría", "would have"],
["verla", "see it"],
["duele", "it hurt"],
["hicimos", "we did"],
["londres", "London"],
["tocar", "play"],
["mirar", "look at"],
["verme", "see me"],
["ben", "ben"],
["suyo", "yours"],
["causa", "cause"],
["pelea", "fight"],
["prisión", "prison"],
["jim", "jim"],
["mayoría", "most"],
["fondo", "background"],
["acaso", "perhaps"],
["vuelvo", "I come back"],
["serán", "will be"],
["montón", "heap"],
["toca", "plays"],
["comandante", "commander"],
["tome", "take"],
["éxito", "success"],
["misión", "mission"],
["vidas", "lifes"],
["decisión", "decision"],
["hogar", "home"],
["rico", "rich"],
["trago", "drink"],
["capaz", "able"],
["cargo", "position"],
["unidos", "United"],
["lleno", "full"],
["bar", "pub"],
["estrella", "star"],
["posición", "position"],
["estación", "station"],
["interesa", "interested"],
["uh", "uh"],
["edificio", "building"],
["vayan", "go"],
["consejo", "advice"],
["pistola", "gun"],
["humano", "human"],
["irnos", "leave"],
["fantástico", "fantastic"],
["ojo", "eye"],
["jóvenes", "young boys"],
["zapatos", "shoes"],
["majestad", "majesty"],
["lee", "read"],
["flores", "flowers"],
["ocupado", "occupied"],
["bienvenido", "welcome"],
["zona", "zone"],
["contacto", "Contact"],
["sacar", "take"],
["podrían", "could"],
["jimmy", "jimmy"],
["tema", "theme"],
["matado", "killed"],
["soldado", "soldier"],
["sabías", "You know"],
["pido", "I ask"],
["cierra", "closes"],
["peter", "peter"],
["intento", "tried"],
["irá", "go to"],
["calor", "hot"],
["finalmente", "finally"],
["equivocado", "wrong"],
["animales", "animals"],
["departamento", "department"],
["enemigo", "enemy"],
["caballero", "gentleman"],
["color", "colour"],
["necesitan", "need"],
["empieza", "starts"],
["soldados", "soldiers"],
["vea", "see"],
["entiende", "understands"],
["valor", "value"],
["azul", "blue"],
["miles", "thousands"],
["espacio", "space"],
["estarás", "you will"],
["mantener", "keep"],
["aprender", "to learn"],
["inteligente", "intelligent"],
["serás", "you will"],
["arte", "art"],
["respeto", "respect"],
["pedir", "ask"],
["puso", "put"],
["llaman", "call"],
["oiga", "Listen"],
["juez", "judge"],
["inglés", "English"],
["precio", "price"],
["rojo", "red"],
["formas", "shapes"],
["hagan", "make"],
["verano", "summer"],
["podido", "I have"],
["piernas", "legs"],
["isla", "island"],
["darme", "give me"],
["damas", "ladies"],
["guardia", "guard"],
["espalda", "back"],
["vengan", "come"],
["parar", "stop"],
["llevas", "take"],
["banda", "band"],
["quedarme", "stay"],
["habéis", "have"],
["marcha", "March"],
["luces", "lights"],
["estuviera", "was"],
["crimen", "crime"],
["dejo", "left"],
["ayudarte", "help you"],
["esperen", "expect"],
["teníamos", "we had"],
["diferencia", "difference"],
["llamaré", "I will call"],
["ama", "love"],
["conocí", "I met"],
["tiempos", "time"],
["déjalo", "leave it alone"],
["debajo", "under"],
["compañero", "partner"],
["dejé", "leave"],
["come", "eat"],
["déjeme", "let me"],
["molesta", "upset"],
["contar", "tell"],
["dejaré", "I ll leave"],
["hablamos", "We speak"],
["cansado", "tired"],
["ganado", "won"],
["pareces", "look"],
["juicio", "judgment"],
["hablado", "spoken"],
["estilo", "style"],
["ayúdame", "Help me"],
["sepa", "know"],
["viendo", "seeing"],
["salida", "departure"],
["alegra", "happy"],
["despierta", "awake"],
["estupendo", "great"],
["darte", "to give you"],
["estados", "state"],
["quedan", "are"],
["próximo", "next"],
["nota", "note"],
["llevó", "I wear"],
["puedas", "can"],
["podrá", "you can"],
["james", "James"],
["nave", "ship"],
["base", "base"],
["tenían", "They had"],
["sube", "goes up"],
["vuelo", "flight"],
["excepto", "except"],
["golpe", "knock"],
["viento", "wind"],
["estaremos", "we will be"],
["acción", "action"],
["tonterías", "silly stuff"],
["respecto", "respect"],
["desea", "you want"],
["sigues", "are you still"],
["debía", "should"],
["vendrá", "will come"],
["encontramos", "we find"],
["beso", "kiss"],
["cuestión", "question"],
["volvió", "went back"],
["reglas", "rules"],
["ruido", "noise"],
["acabado", "finish"],
["salga", "out"],
["olvidado", "forgotten"],
["mentira", "lie"],
["brazo", "arm"],
["empezó", "it started"],
["cálmate", "take it easy"],
["caballos", "horses"],
["experiencia", "experience"],
["tranquila", "quiet"],
["quedar", "stay"],
["esperanza", "hope"],
["irte", "leave"],
["vd", "you"],
["perros", "dogs"],
["casado", "married"],
["llegue", "I arrived"],
["drogas", "drugs"],
["pidió", "he asked"],
["espíritu", "spirit"],
["vacaciones", "holidays"],
["copa", "cup"],
["investigación", "investigation"],
["prefiero", "I prefer"],
["solía", "used to"],
["llevaré", "I ll take"],
["menudo", "often"],
["partir", "from"],
["visita", "visit"],
["alta", "high"],
["abrir", "open"],
["tony", "tony"],
["nueve", "nine"],
["bomba", "bomb"],
["energía", "energy"],
["bolsa", "bag"],
["hacerte", "make"],
["santa", "St."],
["pan", "bread"],
["piel", "skin"],
["usa", "uses"],
["metros", "meters"],
["perdona", "forgives"],
["escrito", "written"],
["exacto", "exact"],
["jugando", "playing"],
["cuello", "neck"],
["larga", "long"],
["escapar", "escape"],
["salvar", "save"],
["escuche", "I listened"],
["perdone", "forgive"],
["sirve", "it serves"],
["preocupe", "worry"],
["especie", "species"],
["aquella", "that"],
["verá", "you will see"],
["brazos", "arms"],
["llena", "full"],
["subir", "rise"],
["blanca", "white"],
["fe", "faith"],
["steve", "steve"],
["modos", "modes"],
["traído", "brought"],
["películas", "films"],
["dama", "Lady"],
["suya", "hers"],
["decirlo", "I say"],
["doble", "double"],
["inmediatamente", "immediately"],
["culpable", "guilty"],
["preocupa", "worries"],
["tardes", "afternoons"],
["vengo", "I come"],
["bosque", "forest"],
["perdí", "I missed"],
["max", "max"],
["volverá", "to return to"],
["taxi", "cab"],
["volar", "fly"],
["debido", "due"],
["repente", "suddenly"],
["bromeando", "joking"],
["ios", "ios"],
["viejos", "old"],
["planeta", "planet"],
["leche", "milk"],
["nick", "nick"],
["tanta", "so much"],
["tuviera", "had"],
["encantado", "charmed"],
["cabrón", "dumbass"],
["correr", "run"],
["depende", "It depends"],
["eddie", "eddie"],
["común", "common"],
["informe", "report"],
["billy", "billy"],
["solamente", "only"],
["máquina", "machine"],
["muere", "go dead"],
["principal", "principal"],
["ridículo", "ridiculous"],
["entrada", "entry"],
["encontró", "he found"],
["podamos", "we can"],
["acabar", "finish"],
["américa", "America"],
["regresa", "came back"],
["probar", "try out"],
["príncipe", "the prince"],
["mr", "mr"],
["preparado", "prepared"],
["pedido", "order"],
["propósito", "purpose"],
["dieron", "they gave"],
["salido", "stepped out"],
["cliente", "client"],
["árbol", "tree"],
["absoluto", "absolute"],
["dejas", "you let"],
["quiénes", "who"],
["habías", "had"],
["parecen", "they look like"],
["belleza", "beauty"],
["llame", "I called"],
["intenta", "try"],
["humanos", "humans"],
["tratar", "try"],
["vuestra", "your"],
["hayas", "have"],
["princesa", "Princess"],
["sigo", "I follow"],
["quedarse", "stay"],
["oeste", "West"],
["traer", "bring"],
["olvídalo", "forget this"],
["francia", "France"],
["tuvimos", "we had"],
["ayudarme", "help me"],
["deprisa", "quickly"],
["llaves", "keys"],
["tiro", "threw"],
["cerdo", "pork"],
["gato", "cat"],
["inglaterra", "England"],
["vistazo", "glance"],
["cuántas", "how many"],
["defensa", "defending"],
["nuevos", "new"],
["últimos", "latest"],
["reloj", "watch"],
["fuimos", "we went"],
["batalla", "battle"],
["hable", "I talked"],
["caminar", "walk"],
["hacerle", "make"],
["vayamos", "we go"],
["interior", "inside"],
["bella", "beautiful"],
["felices", "happy"],
["intentando", "trying"],
["apartamento", "apartment"],
["teatro", "theater"],
["hacerme", "me"],
["papi", "daddy"],
["asuntos", "issues"],
["confiar", "trust"],
["hielo", "ice"],
["detective", "detective"],
["deberían", "should"],
["cantar", "sing"],
["bajar", "go down"],
["vuestro", "your"],
["pelear", "fight"],
["locos", "locos"],
["paga", "pay"],
["oyes", "hear"],
["completo", "full"],
["lucha", "fight"],
["fuerzas", "forces"],
["ideas", "Ideas"],
["borracho", "drunk"],
["héroe", "hero"],
["camión", "truck"],
["cabo", "cape"],
["dientes", "teeth"],
["verde", "green"],
["despacio", "slowly"],
["decidido", "decided"],
["sociedad", "society"],
["pareja", "partner"],
["dígame", "tell me"],
["estuviste", "you were"],
["nariz", "nose"],
["vergüenza", "shame"],
["caer", "fall out"],
["herido", "injured"],
["cuentas", "accounts"],
["pista", "track"],
["siéntese", "sit down"],
["bebe", "baby"],
["sonido", "sound"],
["estrellas", "stars"],
["sombrero", "hat"],
["cayó", "it fell"],
["evitar", "avoid"],
["pasará", "it will happen"],
["memoria", "memory"],
["solos", "alone"],
["llorar", "cry"],
["nervioso", "nervous"],
["lástima", "pity"],
["haberlo", "I have"],
["época", "epoch"],
["naturaleza", "nature"],
["vender", "to sell"],
["política", "politics"],
["levántate", "get up"],
["estudio", "study"],
["brillante", "sparkly"],
["nivel", "level"],
["diferentes", "different"],
["dando", "giving"],
["hubiese", "had"],
["permite", "It allows"],
["justicia", "Justice"],
["planes", "plans"],
["mírame", "look at me"],
["llegamos", "we arrived"],
["roma", "Rome"],
["seguramente", "surely"],
["papa", "dad"],
["parecer", "seem"],
["terminó", "finished"],
["pierna", "leg"],
["quienes", "who"],
["ray", "ray"],
["millón", "million"],
["enorme", "huge"],
["charles", "charles"],
["inocente", "innocent"],
["mismos", "same"],
["pantalones", "pants"],
["ministro", "minister"],
["bienvenida", "welcome"],
["u", "or"],
["refiero", "I mean"],
["nombres", "names"],
["mando", "I send"],
["ponte", "put"],
["preciosa", "precious"],
["quedó", "it was"],
["podrás", "you can"],
["pesar", "to weigh"],
["animal", "animal"],
["enferma", "sick"],
["extraña", "strange"],
["enamorado", "in love"],
["autobús", "bus"],
["recordar", "remember"],
["estáis", "you are"],
["pequeños", "little ones"],
["luchar", "to struggle"],
["date", "date"],
["contrario", "contrary"],
["tomado", "taken"],
["sois", "you are"],
["movimiento", "movement"],
["estan", "is it so"],
["sentado", "seated"],
["gana", "desire"],
["estén", "are"],
["motivo", "reason"],
["absolutamente", "absolutely"],
["dé", "of"],
["puente", "bridge"],
["comprendo", "I understand"],
["huevos", "eggs"],
["tomó", "I take"],
["cuento", "story"],
["botella", "bottle"],
["cuesta", "cost"],
["detente", "stop"],
["corriendo", "running"],
["confianza", "trust"],
["felicidad", "happiness"],
["espada", "sword"],
["silla", "chair"],
["bobby", "bobby"],
["noticia", "news"],
["casas", "houses"],
["televisión", "television"],
["acuerdas", "remember"],
["necesitaba", "needed"],
["pared", "wall"],
["aquellos", "those"],
["prensa", "press"],
["trampa", "trap"],
["presente", "present"],
["estarán", "will be"],
["jardín", "yard"],
["cabello", "hair"],
["espectáculo", "show"],
["podré", "I will be able"],
["grave", "serious"],
["bastardo", "bastard"],
["dará", "give to"],
["siga", "follow"],
["periódico", "newspaper"],
["coño", "cone"],
["danny", "danny"],
["negros", "black"],
["alguno", "any"],
["anillo", "ring"],
["monstruo", "monster"],
["total", "total"],
["tommy", "tommy"],
["piedra", "stone"],
["contento", "happy"],
["quedarte", "stay"],
["tengan", "have"],
["oigan", "hear"],
["sentí", "felt"],
["debí", "should"],
["ahi", "there"],
["policías", "police"],
["lugares", "places"],
["contrato", "contract"],
["playa", "beach"],
["costa", "coast"],
["puertas", "doors"],
["asiento", "seat"],
["tarjeta", "card"],
["restaurante", "restaurant"],
["quede", "stay"],
["paseo", "walk"],
["hechos", "acts"],
["hagamos", "lets do"],
["maravillosa", "wonderful"],
["pon", "put"],
["inspector", "inspector"],
["domingo", "Sunday"],
["especialmente", "especially"],
["velocidad", "speed"],
["negra", "black"],
["richard", "richard"],
["intentar", "try"],
["proyecto", "draft"],
["clientes", "customers"],
["victoria", "victory"],
["encantaría", "love"],
["operación", "operation"],
["perdió", "lost"],
["tonta", "dumb"],
["imagen", "image"],
["lleve", "I carried"],
["amas", "love"],
["responsable", "responsable"],
["gustaba", "He liked"],
["aspecto", "appearance"],
["tantos", "many"],
["sentimientos", "feelings"],
["creerlo", "I believe it"],
["objetivo", "objective"],
["llevan", "they carry"],
["malas", "bad"],
["red", "net"],
["dejen", "leave"],
["nuevas", "news"],
["muchacha", "girl"],
["dormido", "asleep"],
["and", "and"],
["historias", "stories"],
["arreglar", "fix"],
["turno", "turn"],
["yendo", "going"],
["tuviste", "You saw"],
["ponga", "put"],
["olvides", "forget"],
["escuché", "I listened"],
["pasada", "pass"],
["mata", "bush"],
["tantas", "many"],
["montaña", "Montana"],
["gracia", "grace"],
["enfermedad", "disease"],
["dedos", "fingers"],
["guapa", "beautiful"],
["querer", "want"],
["ocurrido", "happened"],
["pocos", "few"],
["deber", "must"],
["refieres", "mean"],
["viernes", "Friday"],
["preocupado", "worried"],
["clases", "lessons"],
["rayos", "ray"],
["inútil", "useless"],
["washington", "Washington"],
["abierto", "open"],
["haberte", "sorry"],
["oscuridad", "darkness"],
["verdadera", "real"],
["americano", "American"],
["trajo", "brought"],
["gustó", "taste"],
["primo", "cousin"],
["nacional", "national"],
["supe", "I knew"],
["colegio", "school"],
["malditos", "accursed"],
["cuchillo", "knife"],
["ibas", "going"],
["llegué", "I arrived"],
["sir", "sir"],
["diario", "diary"],
["francés", "French"],
["quedo", "I remain"],
["podremos", "we will can"],
["orgulloso", "proud"],
["ladrón", "thief"],
["preguntar", "ask"],
["pedí", "I asked"],
["central", "central"],
["voluntad", "Will"],
["harán", "will"],
["jake", "jake"],
["www", "www"],
["militar", "military"],
["agradezco", "I appreciate"],
["llevaba", "He wore"],
["mami", "mommy"],
["lluvia", "rain"],
["éramos", "we were"],
["natural", "natural"],
["calles", "streets"],
["cien", "one hundred"],
["lengua", "language"],
["china", "China"],
["testigo", "witness"],
["ayude", "help"],
["quiso", "He wanted"],
["cansada", "tired"],
["puse", "I put"],
["irás", "you will go"],
["alemanes", "German"],
["pago", "payment"],
["mirada", "look"],
["momentos", "moments"],
["quieto", "still"],
["sentía", "felt"],
["escuchen", "listen"],
["descansar", "rest"],
["mercado", "market"],
["dura", "hard"],
["humana", "human"],
["estúpida", "stupid"],
["humor", "humor"],
["bienvenidos", "welcome"],
["conocía", "he knew"],
["entero", "whole"],
["roja", "red"],
["llamaba", "He called"],
["tomas", "shots"],
["dueño", "owner"],
["echar", "throw"],
["emergencia", "emergency"],
["roto", "broken"],
["actuar", "act"],
["mark", "mark"],
["inmediato", "righ now"],
["puntos", "points"],
["paciente", "patient"],
["olvidé", "forgot"],
["hables", "talk"],
["varios", "various"],
["polvo", "dust"],
["ángeles", "angels"],
["coger", "take"],
["distancia", "distance"],
["europa", "Europe"],
["mataron", "they killed"],
["tomando", "taking"],
["verle", "see"],
["señoría", "lordship"],
["casarse", "get marry"],
["toque", "I touched"],
["toques", "touches"],
["ángel", "Angel"],
["amante", "lover"],
["habló", "I speak"],
["saca", "pulls out"],
["digamos", "let's say"],
["perfecta", "perfect"],
["rosa", "rose"],
["llámame", "giving me a call"],
["nosotras", "we"],
["peso", "weight"],
["carga", "load"],
["acto", "act"],
["robar", "steal"],
["dejaste", "you left"],
["desastre", "disaster"],
["bote", "boat"],
["huele", "smells"],
["embarazada", "pregnant"],
["muestra", "sample"],
["gordo", "fat"],
["sheriff", "sheriff"],
["viviendo", "living"],
["cerrar", "to close"],
["papeles", "papers"],
["valiente", "brave"],
["gloria", "glory"],
["aceptar", "to accept"],
["perdóname", "excuse me"],
["perfectamente", "perfectly"],
["oscuro", "dark"],
["cuidar", "look after"],
["dedo", "finger"],
["ruego", "I beg"],
["pareció", "it seemed"],
["tumba", "tomb"],
["coge", "picks"],
["resulta", "result"],
["dejarlo", "leave"],
["comenzar", "start"],
["área", "area"],
["metido", "I got"],
["limpio", "cleansed"],
["descanso", "break"],
["lados", "sides"],
["posibilidad", "possibility"],
["jerry", "jerry"],
["guapo", "handsome"],
["uso", "use"],
["talento", "talent"],
["matarme", "kill me"],
["continuar", "continue"],
["código", "code"],
["comenzó", "started"],
["duerme", "sleeps"],
["definitivamente", "definitely"],
["directo", "direct"],
["vuelvas", "return"],
["dia", "day"],
["demonio", "demon"],
["parque", "park"],
["cambia", "change"],
["olvidar", "to forget"],
["cinta", "headband"],
["famoso", "famous"],
["mataré", "I will kill"],
["siguen", "follow"],
["saliendo", "coming out"],
["muevas", "move"],
["señoras", "ladies"],
["disparar", "shoot"],
["sóio", "only"],
["pide", "requests"],
["debió", "he must have"],
["empresa", "company"],
["precioso", "beautiful"],
["termina", "ends"],
["intención", "intention"],
["tambien", "too"],
["recibir", "to receive"],
["hubieras", "had"],
["abrigo", "coat"],
["encuentras", "you find"],
["diste", "you gave"],
["tendrán", "will"],
["cerrado", "closed"],
["conocerte", "meet"],
["hablé", "I talked"],
["menor", "less"],
["querría", "I would want"],
["imagino", "I imagine"],
["genio", "genius"],
["profesional", "professional"],
["oigo", "hear"],
["pongo", "I put"],
["niñas", "girls"],
["muévete", "move on"],
["opción", "option"],
["tribunal", "court"],
["tenéis", "you have"],
["lago", "lake"],
["unidad", "unit"],
["abierta", "open"],
["efecto", "effect"],
["presión", "pressure"],
["varias", "several"],
["robo", "Stole"],
["saldrá", "will"],
["veía", "He looked"],
["quedado", "left"],
["alcalde", "mayor"],
["empleo", "job"],
["pollo", "chicken"],
["whisky", "whiskey"],
["california", "California"],
["carretera", "highway"],
["sábado", "Saturday"],
["aeropuerto", "airport"],
["pobres", "poor"],
["medicina", "medicine"],
["llevará", "carry"],
["gratis", "free"],
["cae", "falls off"],
["fortuna", "fortune"],
["castillo", "castle"],
["nieve", "snow"],
["busco", "I search"],
["riesgo", "risk"],
["alemán", "German"],
["sucio", "dirty"],
["idiotas", "idiots"],
["conversación", "conversation"],
["fuese", "it was"],
["comienzo", "start"],
["pasé", "pass"],
["encontraron", "they found"],
["elección", "choice"],
["salgan", "leave"],
["carro", "car"],
["piensan", "they think"],
["rostro", "face"],
["razones", "reasons"],
["fué", "it was"],
["propiedad", "property"],
["mundial", "world"],
["familiar", "family"],
["libras", "pounds"],
["hablemos", "let's talk"],
["pedazo", "piece"],
["continúa", "keep going"],
["cola", "tail"],
["enemigos", "enemies"],
["marca", "brand"],
["líder", "Leader"],
["hablan", "speak"],
["durmiendo", "sleeping"],
["socorro", "help"],
["fútbol", "football"],
["detalles", "details"],
["hiciera", "do"],
["recibido", "received"],
["tesoro", "treasure"],
["camisa", "shirt"],
["thomas", "thomas"],
["comienza", "begins"],
["conducir", "drive"],
["andar", "walk"],
];


let spanish001 = [
["vale", "okay"],
["bueno", "okay"],
["bien", "okay"],
["de acuerdo", "okay"],
["tal vez", "maybe"],
["quizás", "maybe"],
["quizá", "maybe"],
["por supuesto", "of course"],
["ciertamente", "of course"],
["por cierto", "of course"],
["claro", "of course"],
["desde luego", "of course"],
["¿cómo no?", "of course"],
["encantado", "nice to meet you"],
["es un placer", "nice to meet you"],
["mucho gusto", "nice to meet you"],
["guay", "cool"],
["chévere", "cool"],
["suave", "cool"],
["genial", "cool"],
["bello", "beautiful"],
["guapo", "beautiful"],
["precioso", "beautiful"],
["bonito", "beautiful"],
["lindo", "beautiful"],
["maravilloso", "beautiful"],
["diferente", "different"],
["distinto", "different"],
["amable", "kind"],
["agradable", "kind"],
["simpático", "kind"],
["cariñoso", "kind"],
["bueno", "kind"],
["desagradable", "unpleasant"],
["antipático", "unpleasant"],
["duro", "difficult"],
["difícil", "difficult"],
["grande", "large"],
["gran", "large"],
["fuerte", "large"],
["pequeño", "small"],
["minúsculo", "small"],
["diminuto", "small"],
["chico", "small"],
["ahora", "now"],
["actualmente", "now"],
["hoy día", "now"],
["al presente", "now"],
["lengua", "language"],
["idioma", "language"],
["estudiante", "student"],
["alumno", "student"],
["trabajo", "job"],
["empleo", "job"],
["tarea", "job"],
["oficina", "office"],
["despacho", "office"],
["ropa", "clothes"],
["vestido", "clothes"],
["gafas", "glasses"],
["anteojos", "glasses"],
["lentes", "glasses"],
["mandar", "to send"],
["enviar", "to send"],
["caminar", "to walk"],
["andar", "to walk"],
["pasear", "to walk"],
["recorrer", "to walk"],
["marchar", "to walk"],
["elegir", "to choose"],
["escoger", "to choose"],
["seleccionar", "to choose"],
["decir", "to say"],
["afirmar", "to say"],
["expresar", "to say"],
["ver", "to watch/to see"],
["mirar", "to watch/to see"],
["observar", "to watch/to see"],
["contemplar", "to watch/to see"]
];


let spanishSynonims = [
"casa : morada, vivienda, hogar, domicilio, residencia, mansión, habitación, palacio, estancia, paradero, señas, dirección, edificio, inmueble, obra, edificación, construcción, refugio, nido, cobijo, techo, albergue, alojamiento, posada, piso, apartamento, departamento, despacho,  firma, empresa, sociedad, compañía, asociación, comercio, corporación, entidad, consorcio, razón social,  prosapia, cepa, sangre, abolengo, blasón, linaje, casta, familia, raza, estirpe, progenie, descendencia,  quinta, cortijo, finca, alquería, casería, palacete, villa, caserón",
"bueno : humano, caritativo, compasivo, piadoso, bienhechor, misericordioso, clemente, sensible, desprendido, generoso, sacrificado, benévolo, benigno, bondadoso, indulgente, comprensivo, virtuoso, honesto,  afable, servicial, agradable, afectuoso, divertido, cordial, tierno,  cándido, simple, bonachón, inocente, crédulo, buenazo, provechoso, ventajoso, beneficioso, valioso, fructuoso, productivo, adecuado, conveniente, utilizable, servible, favorable, propicio,  justo, estricto, exacto, riguroso,  sano, saludable, benéfico, robusto,  excelente, óptimo, grande, elevado, distinguido, escogido,  bastante, suficiente, basta, hábil ",
"mal: enfermedad, dolencia, indisposición, achaque, morbo, trastorno, desarreglo, complicación, dificultad.  ofensa, ignominia, infamia, inconveniencia, maldición, traición, ganga, bajeza, vileza, indignidad, mezquindad, jugada, faena, vicio, depravación, inmoralidad, deshonestidad, maldad, iniquidad, perversidad, malignidad, crueldad, ferocidad, abuso, injusticia, delito.  desgracia, molestia, adversidad, desventura, contrariedad, fatalidad, dolor, pena, aflicción, tristeza, desolación, amargura, padecimiento, sufrimiento, malestar, tormento.  calamidad, pérdida, ruina, destrucción, catástrofe, desastre, estrago, plaga, peste, daño, perjuicio, deterioro, menoscabo, detrimento, desventaja, imperfección, lacra, tara.",
"muy : estrechamente, tremendamente, terriblemente, exageradamente, desmesuradamente, inmensamente, grandemente, enormemente, considerablemente, extraordinariamente.",
"hacer : crear, formar, inventar, forjar, concebir, descubrir, innovar, imaginar, urdir, elaborar, fabricar, confeccionar, manufacturar, armar, producir, engendrar, causar, originar, ocasionar, criar.  obrar, trabajar, practicar, proceder, ejercer, actuar, intervenir, desempeñar.  realizar, efectuar, ejecutar, cumplir, verificar, acabar, concluir, plasmar, perpetrar, caber, consumar, cometer, ultimar, recrear, materializar.  construir, establecer, fundar, organizar, preparar, combinar, amasar, determinar, componer, arreglar, aderezar.  representar, corresponder, fingir, afectar, simular, aparentar, imitar.  reparar, rehacer, mejorar, ganar, perfeccionar.",
"va/ir : marcha, camina, parte, corre, anda, pasea, cambia, visita, recorre, viaja, pasa, emigra, dirige, traslada, desplaza, mueve, marcha, encamina.  asiste, acude, concurre, comparece, sigue, llega, presenta, aparece, sale, entra, sube.  conduce, guía, transporta, remueve.  obra, procede, baja, cae, estira, alarga.",
"tener : poseer, haber, apalear, asumir, disfrutar, gozar, beneficiarse, obtener, adquirir.  mantener, conservar, sostener, abrigar, acariciar, atesorar, alimentar, guardar, esconder, hospedar.  detener, parar, retener, frenar, contener, refrenar, dominar, sujetar.  incluir, comprender, abarcar, entender, encerrar.  coger, agarrar, tomar, asir.  aguantar, seguir, resistir, sufrir, padecer, adolecer.  disponer, ofrecer, presentar, ostentar.  juzgar, considerar, profesar, apreciar, estimar, valuar, evaluar, cumplir, realizar, compartir, participar.  precisar, necesitar, obligarse, comprometerse, sentir, experimentar.",
"tiempo : cosecha, estación, época, turno.  lapso, período, espacio, duración, curso, ciclo, lugar, vez, proceso, etapa, fase, grado, era, temporada, trecho, tirada, momento, instante, minuto, hora, segundo, rato.  fecha, sazón, plazo, día, término, prórroga, retardo, vencimiento, dilación, mora.  ocasión, oportunidad, coyuntura, pie, circunstancia, actualidad, conveniencia, suceso, ocurrencia, caso.  transcurso, intervalo, periodo, tregua, brevedad, precisión.  edad, siglo, reinado, longevidad, asentada, sentada, años, primaveras.  temperatura, ambiente, cielo, clima, intemperie, meteorología, elementos.  movimiento, paso, ejercicio.  ritmo, proporción, compás.  parte, división, fracción.",
"es/ser: existe, está, ha, halla, florece, coexiste, yace, concurre, preexiste, reside, consiste, vive, subsiste, queda, permanece, dura, mantiene, conserva.  sucede, acontece, acaece, ocurre, transcurre.  pertenece, toca, corresponde, depende, atañe, conviene.  sirve, aprovecha, vale, cuesta.  anda, actúa, obra.",
"ayuda : auxilio, favor, socorro, asistencia, refuerzo, apoyo, beneficio, servicio, caridad, limosna, donativo, paliativo, subvención, sufragio, contribución, subsidio, prestación, donación, amparo, protección, defensa, patrocinio, refugio.  cooperación, colaboración, reciprocidad, mediación, concomitancia, concurso, concurrencia, alianza, asociación.",
"rico : opulento, acaudalado, pudiente, poderoso, acomodado, desahogado, holgado, sobrado, harto, propietario, capitalista, rentista, mecenas, burgués, millonario, potentado, magnate, personaje, ricacho. sabroso, gustoso, apetitoso, exquisito, delicioso, suculento, delicado, sazonado, condimentado, agradable, simpático, dulce.  valioso, fructuoso, fructífero, bueno, abundante, copioso, cuantioso, exuberante, pingüe, feraz, fértil, fecundo.  próspero, floreciente, florido, adelantado, progresivo.  magnífico, espléndido, excelente, fastuoso, lujoso.  costoso, caro, querido.",
"pueblo : población, villa, poblado, aldea, lugar, caserío, municipio, parroquia, partido, cortijo, puebla.  nación, país, patria, estado, reino, terruño, suelo.  público, gente, plebe, masa, vulgo, proletariado, estado llano, gente de la calle, hombre de la calle.  raza, casta, linaje, familia, tribu, clan, ascendientes.  pobladores, ciudadanos, nativos, súbditos, gentes, habitantes, vecinos, vecindario.",
"vender: cede, traspasa, transfiere, salta, entrega, ofrece, adjudica, suministra, provee.  despacha, comercia, negocia, exporta, importa, trajina.  salda, liquida, realiza.  revende, expende, regatea, pregona.  traiciona, delata, denuncia, engaña, descubre.  enajena, aliena, expropia, feria, mercadea, desprende, quita, disponer de, deshacerse de.  mercantiliza, comercia, mercadea, distribuye, merca, comercializa, trata, intercambia, permuta, trueca, negocia, tranza.",
"poco : brizna, átomo, miga, pizca, partícula, punta, tilde, grano, algo, adarme, nonada, pellizco, puñado, miseria.  asomo, atisbo, nada, ribetes, tanto, brote.  escaso, insuficiente, exiguo, corto, irrisorio, parvo, ridículo, raro, disminuido, menguado, falto, incompleto, pobre, truncado, limitado, reducido, estrecho, justo, relativo, pequeño, mínimo, diminuto, chico, minúsculo, insignificante.  tasado, módico, contado, ralo, roído, mediano.  parco, templado, sobrio, moderado.",
"caro : costoso, dispendioso, subido, alto, gravoso, elevado, oneroso, lujoso, alzado, encarecido, sobrecargado, aumentado, prohibitivo.  amado, idolatrado, dilecto, adorado, entrañable, querido, apreciado, estimado, preciado, bienquisto.  exorbitante, abusivo, inmoderado, excesivo, exagerado.  precioso, valioso, inapreciable, incalculable.  penoso, dificultoso, difícil.",
"mucho : cantidad, profusión, abundancia, copia, saciedad, exuberancia, riqueza, raudal, plétora, fertilidad, exceso, demasía, montón, cúmulo, afluencia, aglomeración, acumulación.  numeroso, cuantioso, considerable, incontable, grande, profuso, innúmero, inconmensurable, superabundante, dilatado, nutrido, inmenso, inagotable, importante, abundante, copioso, pingüe.  exagerado, excesivo, extremado.",
"hablar: converso, departo, platico, conferencio, dialogo, discuto, entrevisto, parlamento, charlo, parloteo, rajo, enhebro, ensarto, predico, arengo, diserto, declamo, recito, sacar a colación, traer a cuento, poner paño al púlpito, calentársele la boca, meter baza, gastar palabras, hablar a chorros, no dejar meter baza, hablar por los codos.  digo, expreso, manifiesto, exteriorizo, declaro, proclamo, atestiguo, comunico, comento, explico, aseguro, afirmo, reitero, confirmo, ratifico.  pronuncio, articulo, enuncio, propongo, formulo, opino, profiero, prorrumpo, exclamo, vocifero, grito, trueno.  murmuro, musito, balbuzco, critico, balbuceo, mascullo, respondo, rezongo, susurro, cuchicheo, comadreo, chismorreo, hablar entre dientes.  razono, discurro, alego, pienso.  clamo, intercedo, ruego, suplico, influyo. ",
"pensar : cavilar, especular, recapacitar, repasar, rumiar, madurar, preocuparse, deliberar, masticar, ponderar, abstraerse, recogerse, concentrarse, ensimismarse, enfrascarse, reconcentrarse, repensar, asumir, detenerse, filosofar, premeditar, marearse, presuponer, preconcebir, torturarse, remirar, digerir, descabezarse, enfocar, hablar consigo mismo, tener presente, dar vueltas a la cabeza, calentarse los cascos, devanarse los sesos, romperse la cabeza, dar vueltas, consultar con la almohada, despertar a uno, hacer calendarios, decir para sí, parar mientes.  imaginar, idear, concebir, soñar, inventar, crear, trazar, acariciar, proyectar, planear, fraguar, tramar, urdir.  discurrir, reflexionar, meditar, razonar, relacionar, deducir, colegir, inducir, hilar, raciocinar, tejer.  examinar, estudiar, analizar, investigar, buscar, ver, observar, reparar.  calcular, tantear, medir, intentar.  juzgar, creer, considerar, entender, penetrar, profundizar.  figurarse, sospechar, recelar, presumir, escamarse, olerse, maliciar.",
"oír : escuchar, atender, auscultar, enterarse, interesarse, ocuparse, dar oídos, no perder ripio, aguzar el oído, aguzar las orejas, hacerse cargo, beber las palabras, tomar nota, prestar atención, prestar oídos, aguzar los sentidos.  percibir, notar, advertir, entender, sentir.  acceder, admitir, conceder, acoger, otorgar.",
"comprar : adquirir, tomar, obtener, conseguir, lograr, captar, ganar, conquistar, consumir.  feriar, regatear, proporcionarse, pujar.  sobornar, corromper, untar, captarse, perder, tapar la boca.  operar, luchar, acordar, pactar, estipular.  retraer, retractar, mohatrar.  pagar, abonar, redimir, recobrar, picar, dar, regalar.  mercantilizar, comerciar, mercadear, distribuir, mercar, comercializar, tratar, intercambiar, permutar, trocar, negociar, tranzar.",
"preguntar : examinar, inquirir, investigar, curiosear, indagar, averiguar, aclarar, sonsacar.  interrogar, interpelar, demandar, consultar, solicitar, interesarse, requerir, pedir, articular, comunicar, cuestionar, rogar, pedir cuenta.",
"ver: advertir, distinguir, notar, percibir, reparar, conocer, comprensa, enterar, prevenir, avistar, divisar, descubierta, ojear, vislumbrar, otear, revisar, entrevista, sacar, presentir.  avispar, presenciar, echar la vista encima, echar un vistazo, no perder de vista, estar a la mira, comerse con la vista, mirar con el rabillo del ojo, mirar de arriba abajo, dar una ojeada.  mirar, contemplar, observar, fija, acatar, acechar, vigilar, espiar, atenta, cuidar, curiosear, escarbar, entrometer, hurgar, remover, buscar, averiguar, escudriñar, indagar, inquirir, preguntar, sonsacar, imaginar, reconocer, explorar, sondear, cachear, estudiar, examinar.  experimentar, probar, ensayar, catar, tratar, intentar.  considerar, juzgar, apreciar, tantear, calcular, recapacitar, pensar, reflexionar, meditar, especular, hallar, tropezar.",
"trabajo : adeudo, débito, compromiso, saldo, encargo, responsabilidad.  labor, faena, obra, tarea, operación, fajina, quehacer, cometido, trajín, misión, función, obligación, ajetreo, labranza, maniobra, carga, servicio, asunto, agotamiento, gestión, recado, ocupación, empleo, oficio, colocación, actividad, cuidado, diligencia, laboriosidad, profesión, ejercicio, práctica, ministerio.  monografía, memoria, exposición, disertación, escrito, tesis, artículo, tratado, ensayo, publicación, resumen.  afán, esfuerzo, empujón, empeño.  estudio, investigación, examen, análisis.  penalidad, cuita, tormento, martirio, pena, dolor, padecimiento.  trote, reventón, tute, jornada.  manipulación, elaboración, fabricación, manufactura, realización.  molestia, enfado, dificultad, estorbo, impedimento.  empresa, campaña, hazaña, apretón.  paliza, julepe, tunda.  lucha, batalla, pugna, forcejeo, sudor.",
"trabajar: ocupo, atareo, afano, buscárselas, pasto, aporreo, deshago, atareo, velo, remo, abrumo, agobio, ponerse a, sudar la gota gorda, verse y desearse, arrimar el hombro, batirse el cobre, romperse la cabeza, llevar la carga, meterse a, ganarse la vida, dejarse la vida, no parar, echar el bofe, ir a jornal, ganarse el pan, ganarse el sustento.  elaboro, hago, produzco, fabrico, ejecuto, formo, manipulo, actúo, obro, ejerzo, profeso, funciono, ocupo, gano.  sudo, afano, esfuerzo, brego, mato, multiplico, agenciárselas, trajino, canso, ajetreo, reviento, muevo, dedico, aplico, consagro, persevero, peleo, batallo, lucho, acaloro.  cultivo, ejercito, adiestro, siembro, educo.  molesto, inquieto, atosigo, cargo, perturbo.  estudio, investigo, busco.  procuro, intento, gestiono, despacho.  colaboro, contribuyo, coopero, sirvo, marcho, voy, aprieto, empujo.",
"aprender : instruirse, educarse, cultivarse, formarse, ilustrarse, ejercitarse, asimilar, empollar, cursar, aplicarse, estudiar, repasar, ensayar, experimentar.  penetrar, profundizar, ahondar, pasar.  practicar, cultivar, seguir. ",
"saber : estar al corriente, estar al tanto, echar de ver, estar al cabo de la calle, estar fuerte en, saber al dedillo, no pecar de ignorancia, saber de buena tinta, calzar muchos puntos, pasarse de listo.  conocer, dominar, percibir, observar, percatarse, notar, alcanzar, distinguir, aprender.  entender, comprender, discernir, penetrar, intuir, averiguar, descifrar, interpretar, creer, pensar, opinar, concebir, juzgar.",
"llama : flama, fogonazo, llamarada, soflama, deflagración, fuego, hogar, pira, lumbre, fogata, marjal, falla, chispazo, explosión, soplete, antorcha, tea, ascua, brasa, fuegos fatuos.  ardor, pasión, entusiasmo, vehemencia, arrebato, fogosidad, ataque, efervescencia, paroxismo, rapto, volcán, acaloramiento, encendimiento, apasionamiento.  fulgor, luz, claror, claridad, resplandor, brillo, chispa.  alpaca, caracha, rumiante, vicuña, carnero. ",
"llamar: cita, convoca, emplaza, reúne.  grita, vocifera, aclama, exclama, di, vocea.  nombra, designa, señala, distingue, denomina, apellida, titula, apoda, intitula, bautiza, califica, adjetiva.  reclama, clama, avisa, solicita, requiere, exige, convida, invita, invoca, apela, evoca.  chista, silba, pía, atraer la atención.  toca, pulsa, interesa, oprime, atrae, seduce.",
"mejor : superior, excelente, principal, alto, sobresaliente, dominante, conspicuo, adelantado, aventajado, supremo, sumo.  preferible, perfeccionado, mejorado.",
"peor : malo, bajo, infame, vil, execrable.  inferior, peyorativo, deficiente, pésimo.",
"caliente : acalorado, ardiente, fogoso, vivo, violento, ardoroso, reñido, excitado, exaltado, febril, apasionado, enardecido, vehemente, exacerbado.  cálido, caluroso, tórrido, caldeado, tropical, bochornoso, caliginoso, térmico, calenturiento, candente, abrasador, rojo, incandescente, hirviente, humeante, encendido, inflamado, al rojo.",
"fría: sofría, saltee, dore, estofe, cocine, caliente, hierva, cueza, recaliente.  moleste, importune, fastidie, mortifique, incomode, irrite, exaspere, arrebate.  satirice, zahiera, vilipendie.",
"freír : sofreír, saltear, dorar, estofar, cocinar, calentar, hervir, cocer, recalentar.  molestar, importunar, fastidiar, mortificar, incomodar, irritar, exasperar, arrebatar.  satirizar, zaherir, vilipendiar.",
"ropa : ropaje, vestido, indumentaria, ajuar, traje, atavío, vestuario, atuendo, uniforme, vestidura, jaez, pelaje, trapos, paños, ropilla, prendas, galas, trajes.  trapo, género, tela, tejido.",
"comida : pitanza, manducatoria, pan, pábulo, bucólica, puchero, rozo, comestible, viático, ración, refracción, víveres, vianda, manjar, plato, golosina, bazofia, sustancia, potingue, bodrio, sustento, subsistencia, nutrición.  colación, refrigerio, tentempié, piscolabis, refacción, bocado, bocadillo, banquete, cena, comilona, merienda, convite, festín, gaudeamus, simposio, almuerzo, desayuno.",
"comer: almorzada, desayunada, merendada.  consumida, disipada, gastada, derrochada, dilapidada, rebajada, malgastada, destruida, debilitada, tirada, despachada.  masticada, mascada, desmenuzada, triturada, corroída, roída, erosionada.  nutrida, cebada, rellenada, embutida.  saboreada, paladeada, disfrutada, gozada.  tragada, engullida, zampada, ingerida, tomada, absorbida, embuchada, ganada, alimentada, nutrida, sustentada, jalada, devorada, atiborrada, embutida, echar un bocado, hacer penitencia, llenar la andorga, matar el hambre. ",
"dinero : capital, caudal, fortuna, peculio, fondos, patrimonio, riqueza, posición, tesoro, cantidad, suma, bienes, bolsillo, sustancia, posibles, hacienda, bolsa, talega, economías, ahorros, ahorro.  moneda, metálico, efectivo, oro, numerario, gato, divisas, suelto, calderilla, cambio, cuartos, valores, mosca, monises, pasta, papel, blanca, talego, dineruelo, dinerillo, níquel, porqué, unto, resuello, paga, un tanto.  dólares, plata, billete.   ",
"buscar : investigar, indagar, averiguar, rebuscar, escudriñar, inquirir, examinar, escrutar, preguntar, escarbar, revolver, husmear, fisgonear, bucear, cachear, explorar, rastrear, perseguir, registrar, sondear, batir, andar a caza de, ir al encuentro, sacar de debajo de la tierra, hacerse el encontradizo, dar vueltas.  demandar, pedir, solicitar, reclamar, mendigar. ",
"nada : simulacro, quimera, ficción, entelequia, sueño, ensueño, ofuscación, apariencia.  ausencia, inexistencia, carencia, falta, negación, nulo, nulidad, poco. ",
"nadar: bracea, baña, zambulle, bucea, flota, sobrenada.  rebosa, sobrepasa, sobra, abunda, huelga.",
"puedo/poder: logro, consigo, obtengo, alcanzo, tomo, realizo, sé.  valgo, agencio, merezco, otorgo, permito.  doy, concedo, otorgo, capacito.  disfruto, tengo, ostento.  influyo, intervengo, asumo, reasumo.   dominio, potestad, autoridad, imperio, jurisdicción, poderío, mando, soberanía, señorío, atribución, gobierno, absolutismo, autocracia, preponderancia, supremacía, superioridad, influjo, influencia, mano, hegemonía, omnipotencia, jerarquía, prepotencia, albedrío, arbitrio, recurso.  fuerza, vigor, eficacia, energía, virtud, eficiencia, peso, diligencia, pujanza, empuje, potencia.  facultad, capacidad, derecho, competencia, aptitud, voz.  prerrogativa, privilegio, exención, libertad, autorización, permiso, licencia, venia, concesión, salvoconducto.",
"belleza : hermosura, beldad, preciosidad, lindeza, perfección, primor, lindura, divinidad, gallardía, apostura, morbidez.  atractivo, encanto, gracia, seducción.  esplendor, magnificencia, brillo.  pimpollo, guapa, bonita, preciosa, hermosa, linda, agraciada, bella.  ejemplar, prototipo, norma.   ",
"fuerza : pujanza, potencia, fibra, nervio, impulso, poderío, ímpetu, influencia, robustez, reciedumbre, vigor, energía, fortaleza, eficacia, dinamismo, vivacidad, ánimo, aliento, empuje, brío, esfuerzo, bizarría, fervor, afán, empeño, ahínco.  resistencia, firmeza, dureza, corpulencia, solidez, capacidad.  forcejeo, tirón, sudor, reacción, brega, puja.  avanzada, avanzadilla, delantera, vanguardia, descubierta, destacamento, patrulla, pelotón, flota, escuadra, grupo, tropa, ejército.  batalla, lucha, acción, pugna. ",
"forzar: obliga, compele, constriñe, exige, violenta, impón, compromete, manda, grava, carga, apremia, azuza, impulsa.  desflora, desvirga, forcejea, goza, forceja, rapta, puja, viola, abusa, atropella, vulnera, profana, escarnece, mancilla, deshonra.  conquista, ocupa, toma, allana, penetra, asalta, invade, convence.  domina, retén, sujeta, reprime.   ",
"vez : ciclo, período, tiempo, sucesión, orden, intervalo, fecha, momento.  mano, turno, tanda, rueda, vicisitud, alternativa.  ocasión, coyuntura, razón, proporción, oportunidad, circunstancia, coincidencia, particularidad, trance, lance, punto, situación.  vuelta, revuelta, compás. ",
"creer: opino, profeso, entiendo, juzgo, reputo, pretendo, conceptúo, parecerle, fanatizo.  supongo, conjeturo, sospecho, presumo, figuro, pienso, imagino, estimo, calculo, considero.  afirmo, confío, manifiesto, declaro, evidencio.  admito, acepto, adopto.  sostengo, mantengo, sigo.  trago, parecerle a uno, dar crédito, dar asenso, tener buenas tragaderas, tragarse la píldora.   ",
"crear: fundo, establezco, instituyo, instauro, organizo, implanto, erijo, introduzco.  hago, formo, elaboro, realizo, compongo, invento, concibo, forjo, descubro, plasmo, imagino, pienso.  produzco, origino, engendro, paro, genero, procreo, alumbro.  nombro, designo, elijo. ",
"hombre : persona, individuo, mortal, prójimo, semejante, personaje, tipo.  varón, macho, masculino, caballero.  esposo, tipazo, castizo.  niño, joven, adolescente.   ",
"mujer : señora, dama, dueña, ama, matrona, adulta, hembra, madre.  joven, chica, muchacha, moza, niña, doncella, señorita, venus, hurí, beldad, hermosura.  esposa, consorte, cónyuge, pareja, contrayente, novia, compañera, casada, desposada, media naranja, cara mitad. ",
"vida : existencia, savia, subsistencia, duración, lapso, vidorria, substancia, supervivencia.  energía, fuerza, vigor, fortaleza, espíritu, aliento.  biografía, hazañas, acontecimientos, historia, relación, crónica, relato, memoria.  conducta, comportamiento, proceder, manera, modo.  carrera, empleo, ocupación, quehacer, actividad.  peregrinación, jornada, paso, movimiento.   ",
"cosa: ente, objeto, sujetas, formas, unidades, entidades, organismo, cuerpo, esencias, substancias.  trasto, chisme, chirimbolo, cacharro.  elemento, componente, piezas, factor.  caídas, ocurrencias.  efectos, enseres, arreglos.  mercancías, bien, artículo. ",
"acuerdo : pacto, convenio, alianza, contrato, arreglo, concierto, compromiso, unión, ajuste, acomodo, colaboración, relación, tratado, estipulación, acto, convención, transacción, negociación, trato, componenda, connivencia, manejo.  armonía, avenencia, unidad, paz, inteligencia, entendimiento.  dictamen, fallo, consejo, arbitraje, sentencia, opinión, resolución, decisión, determinación, decreto, edicto.  conformidad, consentimiento, concordancia, asentimiento.   ",
"amigo : camarada, compañero, aliado, conocido, colaborador, coadjutor, adicto, partidario, inseparable, incondicional, afecto, seguidor, hincha, devoto, apegado, leal, aficionado, inclinado, encariñado. ",
"lugar : parte, término, zona, terreno, esfera, distrito, territorio, comarca, sector, bando, expresión.  pueblo, aldea, ciudad, villa, localidad, población.  sitio, punto, paraje, andurrial, rincón, recinto, local, teatro, circuito.  situación, asentamiento, colocación, puesto, empleo, dignidad, oficio, ministerio, autoridad.  medio, ámbito, ambiente, atmósfera, espacio.  ocasión, circunstancia, momento, tiempo.  causa, motivo, fundamento.  posición.   ",
"gustar: saborea, cata, prueba, relame, experimenta, goza, deleita, siente.  encanta, atrae, cautiva, embelesa, toma, arrastra, capta, convence, conquista, enamora, deslumbra, seduce, suspende, interesa, prefiere, arrebata, embriaga, prenda.  desea, quiere, apetece, ambiciona, apasiona, codicia, pretende, aspira, hipa, encapricha, anhela, ansía.  agrada, complace, deleita, place, regala, entusiasma, satisfaz, contenta, alegra, celebra. ",
"beber : gustar, saborear, catar, probar, trincar, tragar, tomar, ingerir, consumir, absorber, sorber, succionar, chupar.  refrescar, soplarse, brindar, refrescarse, servirse, emborracharse, empinar el codo, echar un trago, humedecer el gañote, tener buen saque.   ",
"leer : estudiar, examinar, analizar, averiguar, observar, repasar, ojear, percibir.  descifrar, explicar, interpretar, instruir, adivinar, acertar, descubrir.  hojear, releer, devorar, deletrear, silabear.  asimilar, ilustrarse, cultivarse, aprender.  recitar, decir, contar, balbucear.  penetrar, comprender, profundizar, pasar, recorrer. ",
"escribir : rasguear, garrapatear, trazar, borronear, subrayar, garabatear, corresponderse, cifrar, firmar, autografiar, rotular, mecanografiar, documentar.  apuntar, dictar, asentar, anotar, marginar, notar, poner.  redactar, componer, estilar.  copiar, transcribir, representar, pintar.  extender, expresar, publicar, editar, reflejar.  consignar, expedir, librar.   ",
"llevar : transportar, trasladar, acarrear, facturar, cargar, transbordar, producir, trajinar, reportar, despachar, trasegar, aportar, barrer, meter, subir, pasear, trasplantar, levar, transferir, traspasar, pasar.  soportar, aguantar, sufrir, tolerar, sobrellevar, conllevar, resignarse, sostener, adaptarse.  conducir, guiar, encaminar, dirigir, mandar, manejar, regir, exigir.  escoltar, embalar, acompañar.  usar, utilizar, gastar, emplear.  cobrar, recaudar, tomar en cuenta.  inducir, persuadir, derivar, empujar, mover, incitar, excitar, arrastrar, remolcar.  ponerse, colocarse, vestir.  rebanar, trinchar, cortar.  quitar, sacar, apropiarse, apoderarse.  obtener, conseguir, merecer.  suministrar, dar, servir.",
"deben/deber: corresponden, incumben, comprometen, compensan.  obligan, comprometen, convienen, han. obligación, necesidad, compromiso, convenio, contrato, juramento, cuenta, molestia, cargo, peso.  obligación, peso, compromiso, carga, deuda, imposición, exigencia, necesidad, gravamen, servidumbre, cruz, lazo.  cometido, responsabilidad, trabajo, labor, encargo, cumplimiento, tarea, ejercicio, misión, comisión, competencia, oficio, cargo.",
"espera : expectativa, expectación, aguardo, plantón, esperanza, perspectiva, entretenida, confianza.  dilación, demora, prórroga, retraso, aplazamiento, plazo.  acecho, alerta, vigilancia, guardia, atención, cuidado.  paciencia, flema, permanencia, aguante, conformidad, calma, tranquilidad, sosiego, serenidad.   ",
"esperar: hacer cola, hacer tiempo, esperar sentado, dar tiempo al tiempo, hacer antesala, salir al camino, ir al encuentro, estar por, estar a la expectativa, tomarse tiempo.  persiste, persevera, detén, permanece, queda, dura, aguanta, sostén, conserva, insiste.  aguarda, acecha, atiende, prorroga, difiere, posterga.  cree, presume, supón, piensa, imagina, concibe, confía, fía.  anhela, desea, quiere.  anima, alienta, tranquiliza, promete.  capotea, entretén, hacer esperar, dar plantón, dar largas.  ilusiona, convence, abriga, alimenta. ",
"prosperar: hacer baza, salir a flote, alzar la cabeza.  progreso, adelanto, mejoro, perfecciono, renuevo, asciendo, subo, florezco, surjo, enriquezco.  acreciento, aumento, desarrollo, incremento, amplío, agrando, intensifico, expando.  encumbro, esponjo, impongo, cuajo, gano, triunfo, prevalezco, aventajo, abrirse camino, abrirse paso, ganar terreno.   ",
"",
"",
"",
"",
"",
"",
];



