
const spanishQ = [
["¿Estás listo? ¡Vamos!", "Are you ready? Let's go!"],
["Who?", "¿Quién?"],
["De quién", "Whose"],
["¿Quién es?", "Who is it?"],
["¿Quiénes son?", "Who are they?"],
["¿De quién son estos libros?", "Whose books are these?"],
["What?", "¿Qué?"], 
["Which", "¿Cuál?"],
["¿Qué haces ahora?", "What are you doing right now?"],
["¿Qué es esto?", "What’s that?"],
["¿Cuál es tu favorito?", "Which is your favourite?"],
["¿Cuál es tu película favorita?", "What is your favourite movie?"],
["When?", "¿Cuándo?"],
["¿A qué hora es la película?", "What time is the movie?"],
["¿Cuándo es tu cumpleaños?", "When is your birthday?"],
["¿Cuándo vas a ir?", "When will you go?"],
["Where?", "¿Dónde"],
["¿Dónde vives?", "Where do you live?"],
["¿A dónde vas?", "To where are you going?"],
["¿De dónde eres?", "Where are you from?"],
["from where", "de dónde"],
["¿Por qué? / ¿Para qué?", "Why?"],
["¿Por qué dices eso?", "Why do you say that?"],
["¿Para qué estás aprendiendo español?", 
				"What are you learning Spanish for?"],
["¿Cómo?", "How?"],
["¿Cómo está usted?", "How are you?"],
["¿Cómo hiciste eso?", "How did you do that?"],
["¿Cuántos? / ¿Cuánto? / ¿Cuántas? / ¿Cuánta?", "How many? / How much?"],
["¿Cuántas manzanas?", "How many apples?"],
["¿Cuántos aguacates?", "How many avocados?"],
["¿Cuánta agua?", "How much water?"],
["¿Cuánto té?", "How much tea?"],
["Bueno, ¿qué hay de la cena?", "Well, what’s for dinner?"],
["Tengo una pregunta", "I have a question"],
["¿Puedo hacerte una pregunta?", "Can I ask you a question?"],
["Tengo una pregunta para ti", "I have one question for you."],
["Tengo dos preguntas para ti", "I have two questions for you."],
["¿Puedo preguntarte algo?", "May I ask you something?"],
["Hola, ¿cómo te llamas?", "Hello, what’s your name?"],
["Soy Benny.", "I’m Benny."],
["¿Que tal?", "How’re you?"],
["Muy bien, gracias. ¿Y tu?", "I’m great, thanks. And you?"],
["¿Cuántos años tienes?", "How old are you?"],
["Tengo treinta años.", "I am 30 years old."],
["¿A qué te dedicas?", "What do you do for a living?"],
["Soy escritor y orador.", "I am a writer and speaker."],
["¿Donde trabajas?", "Where do you work?"],
["Trabajo en un restaurante.", "I work at a restaurant."],
["¿Cuáles son tus aficiones?", "What are your hobbies?"],
["Me gusta leer libros y ver películas.", 
			"I like to read books and watch movies."],
["¿De donde eres?", "Where are you from?"],
["Soy de Irlanda.", "I’m from Ireland."],

["¿Cuál es tu película favorita?", "What’s your favourite movie?"],
["Me encanta Star Wars.", "I love Star Wars."],
["¿Desde cuándo aprendes español?", 
			"How long have you been learning Spanish?"],
["Aprendo español desde hace tres meses.", 
				"I’ve been learning Spanish for 3 months."],
["¿Cuál es tu color favorito?", "What is your favourite colour?"],
["Me gusta el verde.", "I like green."],
["¿Hablas otros idiomas?", "Do you speak other languages?"],
["Sí, hablo inglés y francés.", "Yes, I speak English and French."],
["¿Tienes hermanos?", "Do you have any siblings?"],
["Sí, una hermana.", "Yes, one sister."],
["¿Tienes hijos?", "Do you have any kids?"],
["No, no tengo hijos.", "No, I don’t have kids."],
["¿Cuántos en tu familia?", "How many in your family?"],
["Tres. Yo, mi mujer y mi perrito.", "Me, my wife, and my puppy."],
["¿Tienes alguna mascota?", "Do you have a pet?"],
["Sí, tengo un perro.", "Yes, I have a dog."],
["¿Cuál es el nombre de tu hermano/hermana?",
					"What is your brother’s/sister’s name?"],


["El nombre de mi hermano/hermana es…", "My brother’s/sister’s name is…"],
["¿Qué hacen tus padres?", "What do your parents do?"],
["Mi padre es ingeniero y mi madre es enfermera.", 
			"My dad is an engineer and my mom is a nurse."],
["¿Dónde creciste?", "Where did you grow up?"],
["Yo crecí en…", "I grew up in…"],
["¿Que hora es?", "What time is it?"],
["Es la una.", "It’s 1 o’clock."],
["¿Qué día es?", "What day is it?"],
["Es viernes.", "It’s Friday."],
["¿A dónde vas?", "Where are you going?"],
["Me voy a trabajar.", "I’m going to work."],
["¿Qué haces?", "What are you doing?"],
["Estoy estudiando español.", "I’m studying Spanish."],
["¿Estás de acuerdo?", "Do you agree?"],
["Pues… yo no sé.", "Well… I don’t know."],
["¿Qué piensas?", "What do you think?"],
["Creo que esta bien.", "I think it’s good."],
["¿Qué has dicho?", "What did you say?"],
["Dije…", "I said…"],
["¿Dónde está el baño?", "Where’s the bathroom?"],
["Por ahí.", "Over there."],
["Hola, soy Benny.", "Hi, I'm Benny."],
["Holo, ¿cómo te llamas?", "Hi, what's your name?"],
["¿Está desocupada esta silla?", "Is this seat taken"],
["¿Sabe qué hora es?", "Do you know what the time is?"],
["¿Sabe a qué hora cierra este lugar?", "Do you know what time this place closes?"],
["¿Sabe dónde está el/la [place]?", "Do you know where the [place] is?"],
["¿De dónde eres?", "Where are you from?"],
["¿A qué te dedicas?", "What do you do for a living?"],
["¿Qué estudias?", "What do you study/What's your major?"],
["¿Qué te trae por aquí?", "What brings you here?"],
["¿Cuánto tiempo llevas aquí?", "How long have you been here?"],
["¿Cómo conoces a José?", "How do you know José?"],
["¿A quién conoces aquí?", "Who do you know here?"],
["¿Con quién estás aquí?", "Who are you here with?"],
["¿Vienes seguido por aquí?", "Do you come here often?"],
["¿Tienes hermanos/hijos?", "Do you have any siblings/children?"],
["¿Qué edad tienen?", "How old are they?"],
["¿Qué hacen tus padres?", "What do your parents do?"],
["¿Donde creciste?", "Where did you grow up?"],
["¿Ves a menudo a tus abuelos?", "Do you see your grandparents often?"],
["¿Eres cercano/a sus padres?", "Are you close with your parents?"],
["¿Cómo es tu pueblo natal?", "What's your hometown like?"],
["¿Tienes alguna mascota?", "Do you have any pets?"],
["¿Qué raza es tu perro/gato?", "What breed is your dog/cat?"],


["¿Te gusta viajar?", "Do you like to travel?"],
["¿Cuál es el lugar favorito en que has estado?", "What's your favourite place you've been to?"],
["¿En qué países has estado?", "Which countries have you been to?"],
["¿Has estado en [Roma]?", "Have you been to [Rome]?"],
["¿Querrías ir a [Barcelona]?", "Would you like to go to [Barcelona]?"],
["Si pudieras viajar a cualquier lugar, ¿dónde viajarías?", "If you could travel anywhere, where would you go?"],
["¿Hablas otros idiomas?", "Do you speak any other languages?"],
["¿A dónde fuiste la ultima vez de vacaciones?", "Where was the last place you went on holiday?"],
["¿Cuándo empezaste a aprender [español]?", "When did you start learning [Spanish]?"],
["¿Qué te hizo convertirte en [médico]?", "Why did you become a [doctor]?"],
["¿Te gusta tu trabajo?", "Do you like your job?"],
["¿Qué es lo que más te gusta de tu trabajo?", "What do you like the most about your job?"],
["¿Qué es la cosa más difícil sobre tu trabajo?", "What's the most difficult thing about your job?"],
["¿Fuiste a la universidad?", "Did you go to university?"],
["¿La disfrutaste?", "Did you enjoy it?"],



["¿Qué consejo le darías a alguien que quiere convertirse en [programador]?", "What advice would you give to someone who wants to become a [programmer]?"],
["¿Si pudieras volver atrás en el tiempo, estudiarías [psicología] de nuevo?", "If you could go back in time, would you study [psychology] again?"],
["¿Te gusta cocinar?", "Do you like to cook?"],
["¿Cuál es tu comida favorita?", "What's your favourite food?"],
["¿Te gusta la comida [italiana]?", "Do you like [Italian] food?"],
["¿Puedes recomendarme un buen restaurante cerca de aquí?", "Can you recommend me a good restaurant near here?"],
["¿Qué comen en su país?", "What do they eat in your country?"],
["¿Qué haces para divertirte?", "What do you like to do for fun?"],
["¿Te gusta [leer]?", "Do you like to [read]?"],
["¿Cuál tipo de música te gusta más?", "What's your favourite type of music?"],
["¿Cuál es tu [película/libro/banda] favorita?", "What's your favourite [film/book/band]?"],
["¿Tocas un instrumento?", "Do you play an instrument?"],



["¿Cuál es la peor película que has visto?", "What's the worst film you've seen?"],
["¿Practicas algún deporte?", "Do you play a sport?"],
["¿De qué equipo eres?", "What team do you support?"],
["¿Estás de acuerdo?", "Do you agree?"],
["¿Qué piensas tú sobre [X]?", "What do you think about [X]?"],
["Háblame/Cuéntame más de [X]", "Tell me more about [X]."],
["Si no te importa que te pregunte…", "If you don't mind me asking…"],
["Alguien me dijo que…", "Someone told me that…"],
["Escuché que…", "I heard that…"],
["¿Estás de acuerdo en que…?", "Would you agree that… ?"],
["Eso me recuerda…", "That reminds me…"],
["Hablando de eso…", "Speaking of which…"],
["Por otra parte…", "On another note…"],

["Estoy cambiando de tema, pero…", "I'm changing the subject, but…"],
["Me preguntaba…", "I was wondering…"],
["Te voy a decir una cosa…", "Let me tell you something"],
["¡Por supuesto! or ¡Claro que si!", "Of course!"],
["¿En serio?", "Really? / Seriously?"],
["¡Oye!", "Hey! (literally, 'listen!')"],
["¡Hostia!", "Damn!"],
["¡Ostras!", "A family-friendly version of '¡hostia!'."],
["¡Dios mio!", "Oh my god!"],
["A ver…", "Let’s see…"],

["¡No me digas!", "No way! (Literally: don’t tell me!)"],
["¡Vale!", "Okay! (Used in Spain, “dale” is more common in the Americas.)"],
["Qué yo sepa", "As far as I know."],
["Digo…", "Literally “I say”, but you can use this to correct yourself after you misspeak. “Somos dos… digo, tres personas.”"],
["O sea", "I mean…/Or rather…."],
["¿Sabes?", "You know?"],
["Una pregunta…", "a question"],



["spring", "la primavera"],
["summer", "el verano"],
["autumn/fall", "el otoño"],
["winter", "el invierno"],
["la estación lluviosa", "the rainy season"],
["la estación seca", "the dry season"],
["Es verano.", "It’s summer."],
["Nos vamos en primavera", "We’re leaving in the spring."],
["Es una fiesta de invierno", "It’s a winter party."],
["la flor", "flower/blossom"],
["florecer", "to bloom"],
["la oruga", "caterpillar"],
["la mariposa", "butterfly"],
["el pájaro", "bird"],
["la mariquita", "ladybug"],
["la semilla", "seed"],
["la planta", "plant"],
["el ramo", "bouquet"],
["clima templado", "temperate weather"],
["temperatura fresca", "cool temperature"],
["lloviznar", "to drizzle"],
["la brisa", "breeze"],


["Tengo un poco de frío", "I’m a bit cold"],
["sembrar", "to sow/to plant"],
["ir de picnic", "to have a picnic"],
["la limpieza de primavera", "spring cleaning"],
["el mar", "sea"],
["la arena", "sand"],
["el campo", "the country"],
["los mosquitos", "mosquitoes"],
["la fruta", "fruits"],
["la sandía", "watermelon"],
["la piña", "pineapple"],
["una barbacoa", "a barbecue"],
["el chicle", "chewing gum"],
["el helado", "ice cream"],
["colores vivos", "vibrant colors"],
["colores llamativos", "flashy colors"],
["azul", "blue"],
["amarillo", "yellow"],
["El clima", "the weather"],


["clima templado", "temperate weather"],
["temperaturas altas", "high temperatures"],
["el sol", "sun"],
["un día soleado", "a sunny day"],
["días largos", "long days"],
["noches cortas", "short nights"],
["Actividades", "activities"],

["las vacaciones de verano", "summer vacations"],
["tomar helado", "to have ice cream"],
["ir a la playa", "to go to the beach"],
["nadar", "to swim"],
["ir de viaje", "to go on a trip"],
["acampar, ir de acampada, or ir de camping", "to go camping"],
["una excursión", "a hike/a field trip"],
["relajarse", "to relax"],
["divertirse", "to have fun"],
["la Noche de San Juan", "Saint John’s Night"],


["El Día de los Padres", "Father’s Day"],
["fiestas", "parties"],
["La naturaleza", "nature"],

["la hoja", "leaf"],
["el árbol", "tree"],
["el tronco", "trunk"],
["el caracol", "snail"],
["el barro or el lodo", "mud"],
["cosecha", "harvest"],
["los colores", "colors"],

["marrón", "brown"],
["rojo", "red"],
["naranja or anaranjado", "orange"],
["colores cálidos", "warm colors"],
["el clima", "the weather"],

["el viento", "wind"],
["temperaturas en caída", "falling temperatures"],
["el cielo gris", "grey sky"],
["la tormenta", "storm"],
["La comida", "food"],

["el vino", "wine"],
["la manzana", "apple"],
["el maíz", "corn"],
["la calabaza", "pumpkin"],
["Actividades", "activities"],

["recoger hojas", "gather up leaves"],
["saltar en charcos", "jump into puddles"],
["bricolaje", "DIY"],
["hacer una fogata", "to build a bonfire"],
["La Fiesta de la Hispanidad", "Spanish Culture Day/October 12th"],

["Día de los Muertos", "Day of the Dead"],
["pureza", "purity"],


["La naturaleza", "nature"],

["la montaña", "mountain"],
["el muérdago", "mistletoe"],
["hibernación", "hibernation"],
["el pino", "pine"],
["Los colores", "colors"],

["colores fríos", "cold colors"],
["white", "blanco"],
["gris", "grey"],
["plata", "silver"],
["dorado", "golden"],
["El clima", "the weather"],

["temperaturas bajas", "low temperatures"],
["la nieve", "snow"],
["el hielo", "ice"],
["la escarcha", "frost"],
["las nubes", "clouds"],



["la bufanda", "scarf"],
["las medias/lo calcetines", "socks"],
["el abrigo", "coat"],
["las botas", "boots"],
["el gorro", "coat"],
["los guantes", "gloves"],
["La comida", "food"],

["la cena", "dinner"],
["chocolate a la taza/chocolate caliente", "hot chocolate"],
["bebidas calientes", "hot drinks"],
["la sopa", "soup"],
["Actividades", "activities"],

["hacer un muñeco/hombre de nieve", "to build a snowman"],
["tirar bolas de nieve", "to play snowballs"],
["vuna vuelta en trineo", "a sleigh ride"],
["celebrar", "to celebrate"],
["esquiar", "to ski"],
["patinar sobre hielo", "to ice skate"],
["snowboard", "to snowboard"],

["La ropa", "clothes"],
["la Navidad", "Christmas"],
["Nochebuena", "Christmas Eve/Good Night"],
["Nochevieja", "New Year’s Eve/Old Night"],
["Día de Año Nuevo", "New Year’s Day"],
["la Epifanía", "Epiphany"],
["Día de Reyes", "Day of the Kings"],
["Reyes Magos", "Three Wise Men"],
["San Valentín", "Valentine’s Day"],
["el Carnaval", "Carnival"],


["Jueves Lardero, Jueves Gordo, Jueves Graso, Jueves de Carnival", "Fat Thursday / Carnival Thursday"],
["El Miércoles de Cenizas", "Ash Wednesday"],
["¿Cuál es tu estación favorita?", "What’s your favorite season?"], 
["Mi estación favorita es…", "My favorite season is…"],
["¿Cuál es la estación que te gusta más?", "Which season do you like the most?"],
["La estación que más me gusta es…", "The season I like the most is…"],
["¿Cuál es la estación que te gusta menos?", "Which season do you like the least?"],
["La estación que menos me gusta es…", "The season I like the least is…"],
["Prefieres (el otoño) o (la primavera)?", "Do you prefer (autumn) or (spring)?"],
["Prefiero (el otoño), porque me gusta (el clima)", "I prefer (autumn) because I like (the weather)"],

["¿Qué te gusta más (del otoño)? / ¿Qué es lo que te gusta más (del otoño)?", "What do you like the most about (autumn)?"],
["Lo que me gusta más (del otoño) es…", "What I like the most about (autumn) is…"],
["Month", "Mes"],
["tres meses", "three months"],
["enero", "January"],
["febrero", "February"],
["marzo", "March"],
["abril", "April"],
["mayo", "May"],
["junio", "June"],
["julio", "July"],
["agosto", "August"],
["septiembre", "September"],
["octubre", "October"],
["noviembre", "November"],
["diciembre", "December"],
["un Junio caluroso", "a hot June"],
["un Diciembre frío", "a cold December"],

["in June", "en junio"],
["in December", "en diciembre"],
["el clima", "the weather"],
["hace frio", "“does cold”"],
["Hace calor/frío/fresco", "It’s hot/cold/cool"],
["Hace buen/mal tiempo", "The weather is good/bad"],
["Está soleado", "It’s sunny"],
["Está lloviendo", "It’s raining"],
["Está nevando", "It’s snowing"],
["Hay sol", "There’s sun"],
["Hay viento", "There’s wind"],
["”Hello” en español es “hola", "Hello in Spanish is hola"],
["Genial, ¡vamos!", "Great, let’s go!"],

["How Are You?", "¿Cómo estás?"],
["Hello, how are you?", "Hola, ¿cómo estás?"],
["How are you today?", "¿Cómo estás hoy?"],
["How Are You Doing?", "¿Cómo te va?"],
["Good, and you", "Bien, ¿y tú?"],
["Very well, thanks", "Muy bien, gracias"],
["Así así", "so-so"],
["Más o menos", "so-so"],
["Normal", "okay"],
["No tan bien", "Not so good"],
["No muy bien", "Not very well"],
["Mal", "bad"],
["Fatal", "awful"],
["What's Up", "¿Qué tal?"],

["¿Qué más?", "What else?"],
["¿Qué hay?", "What is there?/What’s happening?"],
["¿Qué hubo?", "What happened/ ¿Qué hay?"],
["¿Qué hay de nuevo?", "What’s new?"],
["¿Qué haces?", "What are you doing?"],
["Good Morning", "¡Buenos días!"],
["Good Afternoon", "¡Buenas tardes!"],
["Good Evening", "¡Buenas noches!"],
["Mucho gusto", "much pleasure/ Nice to Meet You"],
["Encantado/a", "glad/ Nice to Meet You"],
["¿Cómo te llamas?", "What’s your name?"],
["¿Cuál es tu nombre?", "What’s your name?"],
["Mi nombre es…", "My name is…"],
["Soy…", "I am…"],
["Me llamo…", "I am called…"],
["¡Bienvenido!/a", "Welcome"],
["Estimado/a Señor/Señora/Señorita", "Dear Sir/Mrs./Ms."],
["Distinguido/a Señor/Señora/Señorita", "Distinguished Sir/Mrs./Ms."],
["Querido/a…", "Dear…"],
["A quien corresponda", "To Whom it May Concern"],
["Gracias por llamar…", "Thank you for calling…"],
["En que le puedo ayudar?", "How may I help you?"],
["cordiales saludos", "best regards"],
["Dile hola a tu hermana", "Say hi to your sister"],
["Diles hola a tus primos", "Say hi to your cousins"],
["héroe/protagonista", "Hero"],
["el guerrero / la guerrera", "Warrior"],
["caballero de brillante armadura", "Knight in shining armor"],
["un dios / una diosa", "A god or goddess"],
["el semidiós / la semidiosa", "Demigod"],
["el soldado", "Soldier"],
["pacificadora", "Peacekeeper"],
["el campeón / la campeona", "Champion"],
["el capitán / la capitana", "Captain"],
["el prefesor / la profesora", "Professor"],
["los mutantes", "Mutants"],
["el vengador / la vengadora", "Avenger"],

["Thor, dios del trueno", "Thor, God of Thunder"],
["El Soldado de Invierno", "The Winter Sollder"],
["maestro jedi", "jedi master"],
["mi héroe", "my hero"],
["Los Vengadores", "The Avengers"],
["Hawkeye", "Ojo de Halcón"],
["Viuda Negra", "Black Widow"],
["Máquina de Guerra", "War Machine"],
["Pantera Negra", "Black Panther"],
["La Avispa", "The Wasp"],
["miembros del equipo", "team members"],



["Identidad secreta", "Secret identity"],
["La máscara", "Mask"],
["Capa", "Cape"],
["Enemigo / Enemiga", "Enemy"],
["Origen", "Origin"],
["El centro de comando", "Command center"],
["El compañero / La compañera", "Sidekick"],
["El universo", "Universe"],
["La galaxia", "Galaxy"],
["La astronave", "Spaceship"],
["La batalla", "Battle"],
["La guerra", "War"],
["Los inmortales", "Immortals"],
["El poder", "Power"],
["La responsabilidad", "Responsibility"],
["El deber", "Duty"],
["El villano malvado / La villana malvada", "Evil Villain"],
["Rescatar", "Rescue"],
["Salvar", "Save"],
["Proteger", "Protect"],
["Guardar", "Guard"],
["Luchar", "Fight"],


["cine / película", "movie"],
["el libro cómico", "comic book"],
["Me encantan las películas de superhéroes", "I love superhero movies"],




["ladrar", "to bark"],

["El perro seguía ladrando", "The dog kept barking"],
["Hubo una fuerte explosión, como ¡PATAPLUM!", "There was a loud explosion, like ‘BOOM!’"],


["Pataplum", "Boom"],
["Ñeec", "Squeak"],
["Zasca", "Bang"],
["Zas", "Zap"],
["Plaf", "Splash"],
["Pum", "Pow"],
["Ñam, ñam", "Om nom nom"],
["Jajaja", "Hahaha"],
["Rin", "Ding"],
["Achí", "Achoo"],
["Chinchín", "Clink"],
["Siseo", "Hiss"],
["Tan, tan", "Clank, clank"],
["Toc toc", "Knock knock"],
["Crag", "Crack"],



["Araña", "Spidergirl"],


["¿Cómo te llamas?", "What’s your name?"],

["Me llamo David. ¿Y tú, cómo te llamas?", "My name is David. And you, what is your name?"],
["¡ Hola! Mucho gusto. ¿Cómo te llamas?", "Hi ! Nice to meet you. What is your name?"],

 

["¿Puedes ayudarme, por favor?", "Could you help me, please?"],

 

["¿De dónde eres?", "Where are you from?"],

["No reconozco su acento. ¿De dónde es usted?", "I don’t recognize your accent.  Where are you from?"],

["Yo soy de Venezuela. ¿De dónde eres tú?", "I’m from Venezuela. Where are you from?"],

 

["¿Hablas inglés?", "Do you speak English?"],
["¿Hablas inglés en la casa?", "Do you speak English at home?"],
["¿Dónde está el baño?", "Where is the washroom?"],

["¿Estás bien?", "Are you alright?"],
["Te ves pálido", "You look pale"],
["¿Dónde está el baño?", "Where’s the toilet?"],
["¿Dónde vives?", "Where do you live?"],
["Te llevaré a casa", "I will drive you home"],
["¿Cuántos años tienes?", "How old are you?"],
["Tengo trenta años", "I’m thirty years old"],
["¿Te gusta _______?", "Do you like _______?"],
["¿Te gusta este cancion?", "Do you like this song?"],
["¿Cuál es tu _______?", "Which/What is your ______?"],
["¿Cuál es tu película favorita?", "Which/What is your favorite movie?"],
["Cuál es su número de teléfono?", "What’s your telephone number?"],
["¿Que haces ________?", "What are you doing ______?"],
["¿Que haces esta noche?", "What are you doing tonight?"],
["Por qué no?", "Why not?"],
["¿Y usted?", "And you?"],
["¿Qué hora es?", "What time is it?"],
["Es la una de la tarde", "It’s one in the afternoon"],
["Disculpe, ¿sabe usted qué hora es?", "Excuse me, do you know what time it is?"],
["¿Hay un(a) ______ cerca?", "Is there a ______ close by?"],
["¿Hay un banco cerca?", "Is there a bank nearby?"],
["¿Como llego a el/la ______?", "How do I get to ______?"],
["¿Como llego a el aeropuerto?", "How do I get to the airport?"],
["¿Como llego a la playa?", "How do I get to the beach?"],
["¿Qué significa esta palabra?", "What does this word mean?"],
["Qué tiempo hace?", "What’s the weather like?"],
["¿Qué tiempo hace? Hace sol y bastante calor", "What’s the weather like? It’s sunny and quite hot"],
["Quiero un/una _______", "I would like a ________"],
["Quiero una cerveza", "I would like a beer"],
["Quiero un café", "I would like a coffee"],
["¿Cuánto es?", "How much is that?"],
["¿Quieren pagar juntos o por separado?", "Do you want to pay together or separately?"],
["¿Tienes un/una______?", "Do you have a ________?"],
["¿Tienes chicle?", "Do you have gum?"],
["¿Dispone usted de información más precisa sobre este tema?", "Do you have more precise information on this subject?"],
["¿Quién es?", "Who’s there?"],
["¿Comprende?", "Do you understand?"],
["¿Adónde va usted?", "Where are you going?"],
["Where are you going? You have to leave in ten minutes!", "¿Para dónde vas? ¡Te tienes que ir en diez minutos!"],
["What are you waiting for?", "¡Vamos!"],
["Hola", "Hello"],
["¿Qué tal?", "How are you?"],
["¿Qué pasa?", "What’s up?"],
["¿Cómo te va?", "How’re you doing?"],
["Bien", "Good"],
["Muy bien", "Very good"],
["Así así", "So-so"],
["No tan bien", "Not so good"],
["¿Y tú?", "And you?"],
["Me llamo…", "My name is…"],
["¿Cómo te llamas?", "What’s your name?"],
["Mucho gusto", "Nice to meet you"],
["Placér", "A pleasure"],
["Encantado/Encantada", "Charmed, Likewise"],
["Nos vemos mañana", "See you tomorrow"],
["Hasta luego", "See you later"],
["Hasta pronto amigo", "See you soon, friend"],
["Gracias", "Thank you"],
["De nada", "You’re welcome"],
["No hay de qué", "No problem"],
["Disculpe", "Excuse me"],
["Lo siento", "I’m sorry"],

["¿Qué te gusta hacer?", "What do you like to do?"],
["Mi pasatiempo favorito es…", "My favourite pastime is…"],
["¿Cuáles son tus pasatiempos?", "What are your hobbies?"],
["¿Qué haces en tu tiempo libre?", "What do you do in your free time?"],
["Me gusta / No me gusta…", "I like / I don’t like…"],
["Me encanta…", "I love…"],
["¿Qué te gusta leer?", "Do you like to read?"],
["¿Que música te gusta?", "What music do you like?"],
["Mi favorito es…", "My favourite is…"],
["Me gusta ir…", "I like going to…"],
["¿En qué trabajas?", "What’s your job?"],
["¿Te gusta tu trabajo?", "Do you like your job?"],
["Trabajo en…", "I work at…"],




["Me encanta café. ¿Quieres ir a tomar una taza?", "I love coffee. Wanna go grab a cup?"],
["Trabajo en la escuela. Soy profesor.", "I work at the school. I’m a teacher."],

["¿Cuánto cuesta?", "How much is this?"],
["¿Dónde está el baño?", "Where’s the bathroom?"],
["¿Qué hora es?", "What time is it?"],
["¿Pasa algo?", "Is something wrong?"],
["¿Es esto correcto?", "Is this right?"],
["¿Me equivocado?", "Was I wrong?"],
["¿Me puede ayudar con esto?", "Can you help me with this?"],
["¿Puedes traerme … por favor?", "Can you bring me … please?"],
["¿Puedo entrar?", "Can I come in?"],
["¿Quieres tomar una copa?", "Want to grab a drink?"],
["¿A dónde deberíamos ir a comer?", "Where should we go to eat?"],
["¿Estás listo?", "Are you ready?"],



["¡Cuánto tiempo sin verlo(a)!", "Long time no see!"],
["¡Feliz cumpleaños!", "Happy birthday!"],
["¡Buena suerte!", "Good luck!"],
["¡Alto!", "Stop!"],
["¡Salud!", "Cheers!"],
["Que te mejores", "Get well soon"],
["Buen provecho", "Bon appetit"],
["Cuídate", "Take care"],
["Felicitaciones", "Congratulations"],
["¡Bien hecho!", "Well done!"],
["¡Genio!", "Genius!"],
["Estupendo", "Stupendous, Amazing"],
["Genial", "Great, Awesome"],
["¡Increíble!", "Incredible!, Impressive!"],


["A ver…", "Let’s see…"],
["Pues…", "Well…"],
["Bueno…", "Well then…"],
["¿Sabes?", "You know?"],
["Por supuesto", "Of course"],
["Por otra parte…", "On another note…"],
["Pero…", "But…"],
["De verdad?", "Really?"],
["Dios mio", "Oh my god"],
["Entonces…", "So…"],
["Asi que…", "So… About that…"],

["Necesito ayuda", "I need help"],
["Llámame cuando llegues", "Call me when you arrive"],
["Me voy a casa", "I’m going home"],
["Necesito ir a…", "I need to go to…"],
["¿Como llego hasta ahí?", "How do I get there?"],
["No lo sé", "I don´t know"],
["No tengo idea", "I have no idea"],
["¿Lo entiendes?", "Do you understand?"],
["No entiendo", "I don’t understand."],
["Quiero…", "I want…"],
["¿Puede hablar más despacio, por favor?", "Can you speak slowly, please?"],
["Hola", "Hello"],
["Buenas", "Hi (informal)"],
["Buenos días", "Good morning"],
["Buen día", "Good morning (less common, used in Argentina)"],
["Buenas tardes", "Good afternoon"],
["Buenas noches", "Good evening"],
["Bienvenido", "Welcome"],
["Que gusto de verlo", "What a pleasure to see you"],
["¡Buenos días!", "Good morning!"],
["¡Bienvenido!", "Welcome!"],
["¡Que gusto de verlo!", "What a pleasure to see you!"],
["Adiós", "Goodbye"],
["Chao", "Goodbye"],
["Hasta luego", "See you later"],
["Hasta pronto", "See you soon"],
["Hasta la vista", "See you next time"],
["Hasta mañana", "See you tomorrow"],
["Nos vemos", "See ya"],
["Buenas noches", "Good night"],
["Que tengas un buen día", "Have a good day"],
["Que te vaya bien", "Have a good day"],
["Cuídate", "Take care (informal)"],
["Cuídese", "Take care (formal)"],
["¿Qué tal?", "How are you?"],
["¿Cómo estás?", "How are you?"],
["¿Cómo está usted?", "How are you? (usted is more formal than tú)"],
["¿Cómo te va?", "How are you?"],
["¿Cómo te ha ido?", "How have you been?"],
["¿Qué pasa?", "What’s up?"],
["¿Qué cuentas?", "What’s up?"],
["Estoy bien, ¿y tú?", "I am fine, and you?"],
["Bien, ¿y usted?", "Good, and you? (usted is more formal than tú)"],
["Estoy estupendo", "I am great"],
["Estoy muy bien", "I am very well"],
["Estoy así así", "I am okay"],
["Estoy más o menos.", "I am so-so"],
["Estoy regular", "I am regular"],
["Estoy mal", "I feel unwell"],
["Estoy fatal", "I am terrible"],
["Estoy un poco cansado", "I am a little tired"],
["Estoy exhausto", "I am exhausted"],
["Estoy enfermo", "I am sick"],
["¿Cuál es tu nombre?", "What is your name? (informal)"],
["¿Cuál es su nombre?", "What is your name? (formal)"],
["¿Cómo te llamas?", "What is your name? (informal)"],
["¿Cómo se llama?", "What is your name? (formal)"],
["Me llamo…", "My name is…"],
["Mi nombre es…", "My name is…"],
["Gracias", "Thank you"],
["Muchas gracias", "Thank you very much"],
["De nada", "You’re welcome"],
["Perdón", "I am sorry"],
["Lo siento", "I am sorry"],
["Disculpe", "Sorry"],
["Mil disculpas", "A thousand sorry’s"],
["Por favor", "Please"],
["Con permiso", "Excuse me"],
["Perdone / Perdona", "Excuse me"],
["Señor (Sr.)", "Mr."],
["Señora (Sra.)", "Mrs."],
["Señorita (Srta.)", "Miss"],
["¿De dónde eres?", "Where are you from? (informal)"],
["¿De dónde es?", "Where are you from? (formal)"],
["¿De dónde son?", "Where are you from? (plural)"],
["¿Dónde vives?", "Where do you live?"],
["Yo soy de…", "I am from…"],
["Somos de…", "We are from…"],
["¿Qué…?", "What…?"],
["¿Cómo…?", "How…?"],
["¿Cuándo…?", "When…?"],
["¿Cuánto…?", "How much…?"],
["¿Dónde…?", "Where…?"],
["¿Quién…?", "Who…?"],
["¿Por qué…?", "Why…?"],
["¿Cuál?", "Which…?"],
["¿Qué hora tienes?", "What time is it?"],
["¿Qué edad tienes?", "How old are you?"],
["¿Cuántos años tienes?", "How old are you?"],
["¿Cuándo es tu cumpleaños?", "When is your birthday?"],
["¿Cuánto cuesta eso?", "How much is that?"],
["¿Quién eres?", "Who are you?"],
["¿Qué es esto?", "What is this?"],
["¿Cuál es la fecha de hoy?", "What is the date today?"],
["¿Entiende?", "Do you understand?"],
["¿Comprende?", "Do you understand?"],
["¿Por qué te gusta?", "Why do you like it?"],
["¿Hablas inglés?", "Do you speak English?"],
["¿Dónde está el baño?", "Where is the bathroom?"],
["Necesito ayuda", "I need help"],
["Sí", "Yes"],
["Claro", "Of course"],
["Siempre", "Always"],
["A veces", "Sometimes"],
["Tal vez", "Maybe"],
["Nunca", "Never"],
["Buena suerte", "Good luck"],
["Buen viaje", "Have a good trip"],
["Buen provecho", "Enjoy your meal"],
["Diviértete", "Have fun"],
["Salud", "Cheers / Bless you (when someone sneezes)"],
["Muy bien", "Well done"],
["Felicitaciones", "Congratulations"],
["Feliz Cumpleaños", "Happy Birthday"],
["Feliz Navidad", "Merry Christmas"],
["Feliz Año Nuevo", "Happy New Year"],
["Siento interrumpir", "I am sorry to interrupt"],
["No se preocupe", "Don’t worry"],
["Te amo", "I love you"],
["Con mucho amor", "With much love"],
["Hola", "Hello"],
["Adiós", "Goodbye"],
["Por favor", "Please"],
["Gracias", "Thank you"],
["Lo siento", "Sorry"],
["Salud", "Bless you (after someone sneezes)"],
["¿Quién?", "Who?"],
["¿Qué?", "What?"],
["¿Por qué?", "Why?"],
["¿Dónde?", "Where?"],
["Buenos días", "Good morning"],
["Buenas tardes", "Good afternoon"],
["Buenas noches", "Good evening"],
["Hola, me llamo Juan", "Hello, my name is John"],
["Me llamo…", "My name is…"],
["¿Cómo te llamas?", "What’s your name?"],
["Mucho gusto", "Nice to meet you"],
["¿Cómo estás?", "How are you?"],
["Estoy bien, gracias", "I’m well thank you"],
["Disculpa. ¿Dónde está el baño?", "Excuse me. Where is the bathroom?"],
["¿Qué hora es?", "What time is it?"],
["¿Cómo se dice ‘concert’ en español?", "How do you say ‘concert’ in Spanish?"],
["Estoy perdido/a", "I am lost"],
["Yo no comprendo", "I do not understand"],
["Por favor, habla más despacio", "Would you speak slower, please"],
["Te extraño", "I miss you"],
["Te quiero", "I love you"],
["Despacito", "Slowly"],
["Mi Gente", "My people"],
["Bailando", "Dancing"],
["Bésame mucho", "Kiss me a lot"],
["Gasolina", "Gasoline"],
["La Bicicleta", "The bicycle"],
["Sin Pijama", "Without pajamas"],
["Bella", "Beautiful"],
["Clandestino", "Clandestine, secret"],
["No Me Acuerdo", "I don’t remember"],
["¡Buenos días, Estela!", "Good morning, Estela!"],
["Buenos días, Esteban. ¿Cómo estás?", "Good morning, Esteban. How are you?"],
["Bien, ¿y tú?", "Well, how about you?"],
["Como siempre.", "As always."],
["Buenos días", "good morning"],
["Buenas tardes", "good afternoon"],
["Buenas noches", "good evening"],
["Hola", "hello"],
["¿Cómo estás?", "How are you?"],
["¿Cómo está usted?", "How are you?(more formal)"],
["¿Cómo te va?", "How's it going?"],
["¿Cómo has ido?", "How've you been?"],
["¿Qué tal?", "What's up?"],
["¿Qué pasa?", "What's happening?"],
["¿Qué haces?", "What are you doing?"],
["Más o menos", "Okay, so-so"],
["Mal", "Bad"],
["Todo bien", "All good"],

["¿Qué haces?", "What are you doing? "],
["Nada, nada. Estoy enferma.", "Nothing, nothing. I'm sick. "],
["Ah, lo siento.", "Ah, sorry. "],
["¿Y tú? ¿Cómo te va? ¿Bien?", "How about you? How are you doing? Well? "],
["Sí, todo bien.", "Yes, all right. "],
["Lo siento.", "I'm sorry. "],
["Te amo.", "I love you. "],
["Necesito ayuda.", "I need help "],


["adiós", "goodbye "],

["chao", "goodbye "],

["hasta luego", "later "],

["hasta pronto", "see you soon "],

["hasta la vista", "until we see each other again "],

["nos vemos", "see ya "],

["¡Buena suerte!", "Good luck! "],

["¡Diviértete!", "Have fun! "],

["¡Con mucho amor!", "Lots of love! "],

["¡Buen viaje!", "Have a good trip! "],

["¡Buen provecho!", "Enjoy your meal! "],

["¡Salud!", "Cheers! "],

["¡Muy bien!", "Well done! "],

["¡Cuídate!", "Take care! "],

["¡Cuídese!", "Take care! (formal) "],

["Los mejores deseos para…", "Best wishes to… "],

["¡Felicitaciones!", "Congratulations! "],

["¡Bienvenidos! / ¡Bienvenidas!", "Welcome! "],

["¡Feliz Cumpleaños!", "Happy Birthday! "],

["¡Salud!", "Bless you! "],

["¡Feliz Navidad!", "Merry Christmas! "],

["¡Feliz Año Nuevo!", "Happy New Year! "],


["¡Lo siento!", "I'm sorry! "],

["Perdón, pero dónde están los baños?", "Excuse me, but where are the toilets? "],

["¡Perdón!", "Excuse me! "],


["¡Mil disculpas!", "A thousand sorry's! "],


["Siento interrumpir.", "Sorry to interrupt. "],


["Con permiso.", "Excuse me. "],


["¡No se preocupe!", "No worries! "],


["See you soon!", "¡Hasta pronto! "],









["Why? (for what purpose)", "¿Para qué? "],

["Who?", "¿Quién? "],

["What?", "¿Cómo? ¿Qué? "],

["Which?", "¿Cuál? "],

["Seriously?", "¿En serio? "],


["What time is it?", "¿Qué hora es? "],

["It is 1 o’clock", "Es la una* "],

["It is 8 o’clock", "Son las ocho "],

["It is half past five", "Son las cinco y media "],

["It is quarter to eleven", "Son las once menos cuarto "],


["I’m lost", "Estoy perdido(a) "],

["Where is the bus station/bank/supermarket?", "¿Dónde está la estación de autobuses / banco / supermercado? "],

["It is straight ahead", "Está más adelante. "],

["It is to the left / to the right", "Está a la izquierda / a la derecha "],

["It is around the corner", "Está a la vuelta "],


["I would like to reserve a table for five people", "Quisiera reservar una mesa para cinco personas "],

["A table for two please", "Una mesa para dos, por favor "],

["The menu, please", "La carta, por favor "],

["I would like", "… Quisiera… "],

["Can you bring me a_____, please?", "¿Me trae un(a)_____, por favor? "],

["Can I ask you for a_____?", "¿Le pido un(a)_____? "],

["A beer / a glass of wine, please", "Una cerveza / una copa de vino, por favor "],

["I am hungry", "Tengo hambre "],

["I am thirsty", "Tengo sed "],

["At what time does the bus / train arrive?", "¿A qué hora llega el tren / el autobús? "],

["A single ticket for_____, please", "Un billete sencillo / pasaje de ida para_____, por favor "],

["A round trip ticket for_____, please", "Un billete / pasaje de ida y vuelta para_____, por favor "],

["Have a safe journey!", "¡Buen viaje! "],

["Have a great holiday!", "¡Felices vacaciones! "],



["Happy Easter", "¡Felices Pascuas! "],

["Happy Christmas", "¡Feliz Navidad! "],

["Happy New Year", "¡Feliz Año Nuevo! "],

["Happy Birthday", "¡Feliz cumpleaños! "],

["Cheers!", "¡Salud! "],

["Congratulations!", "¡Felicitaciones! "],


["Where’s the bathroom?", "¿Dónde está el baño? "],

["Shall we go for a drink?", "¿Vamos a tomar una copa? "],

["How much does this cost?", "¿Cuánto cuesta? "],

["Don’t worry", "¡No te preocupes! "],

["Good luck!", "¡Suerte! "],

["Sorry!", "¡Lo siento! "],


["Do you speak English?", "¿Hablas inglés? "],

["Thank you", "Gracias "],

["You’re welcome", "De nada "],

["Don’t worry about it", "No pasa nada "],

["I don’t understand", "No entiendo "],

["No problem", "No hay problema "],

["That’s a shame", "Es una lástima "],

["I don’t know", "No sé "],

["Quick!", "¡Rápido! "],



["¡Mucho tiempo sin verte!", "Long time no see! "],
["¡Cuánto tiempo sin verte!", "Long time no see! (alternative) "],
["¡Qué alegría verte!", "How nice to see you! "],
["¡No me lo puedo creer!", "I can’t believe it! "],
["¿Qué cuentas?", "Literally: “What do you tell?” (asking for news) "],
["¿Qué hay de nuevo?", "What’s new? "],

["Soy de Inglaterra.", "I’m from England. "],
["Soy inglés.", "I’m English. "],
["Vivo en Australia.", "I live in Australia. "],
["Tengo 27 años.", "Literally 'I have 27 years'. "],
["Soy casado(a).", "I’m married. "],
["Soy soltero(a).", "I’m single. "],


["Soy profesora de yoga.", "I’m a yoga teacher. "],
["Soy estudiante.", "I’m a student. "],
["Estoy jubilado/retirado.", "I’m retired. "],
["Estudio historia.", "I study history (for example, as a degree) "],
["Estoy estudiando español.", "I’m studying Spanish (temporary, doing it right now) "],
["Trabajo aquí.", "I work here. "],
["Trabajo a tiempo parcial.", "I work part-time. "],
["Estoy buscando trabajo.", "I’m looking for a job. "],


["¿Cómo te llamas?", "What’s your name? "],
["¿De dónde es?", "Where are you from? "],
["¿Dónde vives?", "Where do you live? "],
["¿Cuáles son tus pasatiempos?", "What are your hobbies? "],
["¿A qué te dedicas?", "What do you dedicate yourself to (what’s your job?) "],
["¿Cuál es tu trabajo/ocupación?", "What’s your job/occupation? "],

["Porque me encanta la cultura española.", "Because I love Spanish culture. "],
["Porque mi compañero(a)/pareja es venezolano.", "Because my partner is Venezuelan. "],
["Porque mis abuelos eran mexicanos.", "Because my grandparents were Mexican. "],
["Porque quiero entender la música en español.", "Because I want to understand music in Spanish. "],


["Sólo hablo un poco.", "I only speak a little bit. "],
["Entiendo bien el español.", "I understand Spanish well. "],
["Me cuesta hablar con fluidez.", "It’s hard for me to speak fluently. "],
["Puedo escribir/leer/hablar muy bien.", "I can write/read/speak very well. "],
["Todavía tengo que hablar despacio.", "I still have to speak slowly. "],
["Prefiero hablar que escribir.", "I prefer talking than writing. "],

["Soy principiante.", "I’m a beginner. "],


["Me gusta escuchar música.", "I like listening to music. "],

["Me gustan las series de terror.", "I like horror series. "],

["Uno de mis pasatiempos es escribir.", "One of my hobbies is writing. "],
["Me encanta el cine español.", "I love Spanish cinema. "],
["Me encantan los libros de fantasía.", "I love fantasy books. "],


["¿Te gustaría ir conmigo?", "Would you like to come with me? "],
["¿Te gustaría ir al cine mañana?", "Would you like to go to the movies tomorrow? "],
["¿Quieres tomar un café?", "Do you want to grab some coffee? "],
["¿Te gustaría salir conmigo?", "Would you like to go out with me? (romantic undertones) "],

["Estoy estresado(a).", "I’m stressed out. "],
["Estoy triste.", "I’m sad. "],
["Estoy muy nervioso(a).", "I’m very nervous. "],
["¡Estoy feliz!", "I’m happy! "],
["Estoy decepcionado.", "I’m disappointed. "],
["Me siento mal.", "I feel bad. "],
["Tengo miedo.", "I’m scared. "],

["No entiendo.", "I don’t understand. "],
["No lo sé.", "I don’t know. "],
["No tengo idea.", "I have no idea. "],
["No tengo ni idea de qué hacer.", "I have no clue what to do. "],
["Estoy perdido(a).", "I’m lost. "],
["Estoy confundido(a).", "I’m confused. "],
["No estoy seguro(a).", "I’m not sure. "],
["¿Puede(s) hablar más despacio, por favor?", "Could you please speak slowly? "],

["¡Buen viaje!", "Have a nice trip! "],
["¡Buena suerte!", "Good luck! "],



["Muchas gracias!", "Thanks a lot! "],
["¡Muchísimas gracias!", "Thank you so much! "],
["Eres/Es muy amable.", "It’s so kind of you. (The first is informal, the second is a formal option.) "],

["Estoy muy agradecido(a).", "I’m really thankful. "],
["Te lo agradezco.", "I thank you for that. "],

["¡Perdón!", "Pardon, excuse me, sorry. "],
["Disculpe(a).", "Sorry. (Use the letter 'a' instead of 'e' to make it informal) "],
["Lo siento.", "I’m sorry. "],
["Lo siento mucho/muchíssimo.", "I’m so sorry. "],
["Me equivoqué.", "I was wrong. "],

["¿Nos trae la carta, por favor?", "Can you bring us the menu, please? "],
["¿Qué me/nos recomienda?", "What do you recommend me/us? "],
["Voy a tomar un té, gracias.", "I’ll take a tea, thanks. "],
["Para mí, las enchiladas.", "I’ll have the enchiladas. "],
["Tenéis pulpo a la gallega?", "Do you have octopus a la gallega? "],
["¿Nos puede traer la cuenta?", "Can you bring us the check? "],

["¿Así que estás pensando viajar mañana?", "So you’re thinking of traveling tomorrow? "],
["No tenéis paella? Pues, entonces un bocadillo.", "You don’t have paella? Well, then a sandwhich. "],
["Pues…no sé qué hacer.", "Well... I don’t know what to do. "],
["A ver. Que quieres hacer hoy?", "Let’s see. What do you want to do today? "],
["No quiero ir con él. Es que me siento mal por lo que pasó.", "I don’t want to go with him. It’s just that I feel bad about what happened. "],
];

