let turkish = [["bir", "one"],
["bu ", "it"],
["ve", "and"],
["ne", "What"],
["mi", "Did you"],
["için", "for"],
["çok", "very"],
["ben", "I"],
["o", "he is"],
["evet", "Yes"],
["de", "also"],
["var", "there is"],
["ama", "but"],
["mı", "is"],
["değil", "not"],
["hayır", "no"],
["sen", "joyful"],
["şey", "thing"],
["da", "in"],
["daha", "more"],
["bana", "to me"],
["kadar", "until"],
["seni", "you"],
["beni", "me"],
["iyi", "good"],
["onu", "him-her-it"],
["tamam", "OK"],
["bunu", "this"],
["gibi", "like"],
["yok", "no"],
["benim", "just me"],
["her", "each"],
["sana", "you"],
["ki", "that"],
["sadece", "only"],
["neden", "why is that"],
["senin", "your"],
["burada", "here"],
["zaman", "time"],
["hiç", "no"],
["şimdi", "now"],
["nasıl", "how"],
["sonra", "Then"],
["olduğunu", "that"],
["en", "most"],
["mu", "is"],
["hadi", "let's"],
["misin", "will you"],
["şu", "That"],
["öyle", "so"],
["ya", "either"],
["güzel", "beautiful"],
["biraz", "some"],
["musun", "Do you"],
["önce", "prior to"],
["lütfen", "Please"],
["İyi", "Good"],
["bak", "look"],
["ona", "him"],
["böyle", "such"],
["oldu", "it was"],
["hey", "Hey"],
["istiyorum", "I want"],
["onun", "her"],
["geri", "back"],
["bile", "even"],
["eğer", "if"],
["artık", "no longer"],
["gerçekten", "really"],
["kim", "who"],
["bay", "Mr"],
["yani", "so"],
["çünkü", "because"],
["büyük", "big"],
["doğru", "TRUE"],
["peki", "Well"],
["buraya", "here"],
["biliyorum", "I know"],
["başka", "another"],
["belki", "maybe"],
["olarak", "as"],
["tanrım", "my god"],
["tek", "single"],
["efendim", "Sir"],
["biri", "someone"],
["olur", "would"],
["olacak", "it will be"],
["adam", "man"],
["haydi", "lets"],
["olan", "one"],
["İşte", "Request"],
["et", "meat"],
["sanırım", "I think"],
["merhaba", "Hi"],
["biz", "we"],
["orada", "there"],
["demek", "say"],
["teşekkürler", "thanks"],
["hiçbir", "no"],
["nerede", "where"],
["yardım", "help"],
["ederim", "I would"],
["bilmiyorum", "I do not know"],
["gün", "day"],
["gece", "night"],
["oh", "oh"],
["fazla", "much"],
["bütün", "all"],
["bunun", "its"],
["tüm", "all"],
["harika", "great"],
["ile", "with"],
["yeni", "new"],
["gel", "come"],
["biliyor", "he knows"],
["iki", "two"],
["kötü", "bad"],
["küçük", "small"],
["tam", "full"],
["olsun", "get"],
["siz", "you"],
["son", "end"],
["şeyler", "things"],
["ol", "be"],
["bayan", "Lady"],
["şeyi", "thing"],
["hemen", "immediately"],
["size", "to you"],
["sorun", "problem"],
["üzgünüm", "sorry"],
["ver", "give"],
["onları", "them"],
["lanet", "curse"],
["teşekkür", "thank"],
["devam", "continuation"],
["kız", "girl"],
["git", "go"],
["sizi", "you"],
["dostum", "my friend"],
["gerek", "need"],
["pekala", "well"],
["bizi", "us"],
["bize", "to us"],
["hakkında", "about"],
["buna", "this"],
["kendi", "own"],
["baba", "father"],
["aynı", "same"],
["anne", "mother"],
["dur", "Stop"],
["oluyor", "is happening"],
["mısın", "will you"],
["iş", "business"],
["kimse", "nobody"],
["asla", "never"],
["diye", "that"],
["izin", "permission"],
["hala", "still"],
["al", "get"],
["seninle", "with you"],
["şunu", "it"],
["olabilir", "can"],
["mü", "is"],
["söyle", "tell"],
["benimle", "with me"],
["tabii", "Of course"],
["para", "money"],
["bizim", "our"],
["selam", "Hello"],
["yoksa", "or"],
["içinde", "in"],
["önemli", "important"],
["değilim", "I am not"],
["yüzden", "why"],
["herkes", "everyone"],
["ister", "either"],
["gidelim", "lets go"],
["dakika", "minute"],
["bırak", "leave"],
["geldi", "came"],
["üç", "three"],
["biliyorsun", "you know"],
["işte", "Request"],
["tekrar", "again"],
["vardı", "had"],
["bakalım", "let's see"],
["istiyorsun", "Would you"],
["onlar", "them"],
["bugün", "today"],
["özür", "apology"],
["buradan", "from here"],
["hep", "always"],
["miyim", "Can I"],
["yine", "again"],
["yapıyorsun", "you are doing"],
["bekle", "wait"],
["uzun", "long"],
["gerçek", "real"],
["geliyor", "coming"],
["saat", "hour"],
["aslında", "actually"],
["olmak", "be"],
["çocuklar", "children"],
["neler", "What"],
["nedir", "what"],
["çocuk", "child"],
["bence", "in my opinion"],
["burası", "here"],
["onunla", "with him"],
["eve", "home"],
["ilk", "first"],
["göre", "by"],
["sizin", "your"],
["yer", "place"],
["nereye", "where"],
["birlikte", "together"],
["yıl", "year"],
["hepsi", "all"],
["kaç", "escape"],
["dinle", "listen"],
["şekilde", "the way"],
["olmaz", "No way"],
["pek", "very"],
["yere", "place"],
["tanrı", "God"],
["istemiyorum", "I do not want"],
["emin", "sure"],
["fakat", "but"],
["hazır", "ready"],
["zaten", "already"],
["birkaç", "a few"],
["dilerim", "I wish"],
["söz", "promise"],
["söyledi", "told"],
["lazım", "necessary"],
["kendini", "itself"],
["olmalı", "should be"],
["tane", "piece"],
["etmek", "to make"],
["misiniz", "Are you"],
["ediyorum", "I would"],
["seviyorum", "I love"],
["tatlım", "sweetie"],
["bunlar", "these"],
["karşı", "against"],
["kesinlikle", "absolutely"],
["görmek", "see"],
["birşey", "something"],
["yarın", "tomorrow"],
["olduğu", "that"],
["benden", "me"],
["elbette", "of course"],
["ha", "Ha"],
["istiyor", "wants"],
["aman", "Oh"],
["az", "little"],
["eski", "old"],
["edin", "Learn"],
["anda", "currently"],
["kadın", "woman"],
["İki", "Two"],
["kahretsin", "damn"],
["işi", "heat"],
["yapmak", "make"],
["ilgili", "about"],
["ah", "Ah"],
["an", "moment"],
["oraya", "to there"],
["onlara", "to them"],
["dikkat", "attention"],
["gerekiyor", "need"],
["dışarı", "out"],
["diğer", "other"],
["yapma", "making"],
["işe", "if"],
["hoş", "pleasant"],
["bundan", "from this"],
["zor", "difficult"],
["kez", "times"],
["sakin", "do not"],
["mutlu", "happy"],
["bakın", "Look"],
["geç", "late"],
["kabul", "accept"],
["senden", "from you"],
["dedim", "I said"],
["çabuk", "quickly"],
["gidip", "go"],
["niye", "why"],
["yemek", "eat"],
["hafta", "week"],
["yerde", "in place"],
["kişi", "person"],
["musunuz", "Do you"],
["zorunda", "must"],
["yanlış", "FALSE"],
["görüşürüz", "See you"],
["özel", "special"],
["gördüm", "I saw"],
["gidiyor", "going"],
["doktor", "doctor"],
["ediyor", "ediyor"],
["bazı", "Some"],
["kes", "cut"],
["yalnız", "alone"],
["hem", "and"],
["babam", "my father"],
["beş", "five"],
["gitti", "gone"],
["polis", "police"],
["erkek", "male"],
["merak", "wonder"],
["nereden", "Where from"],
["kontrol", "control"],
["insan", "human"],
["birini", "one"],
["eminim", "I am sure"],
["ondan", "from him"],
["insanlar", "people"],
["aptal", "silly"],
["gereken", "required"],
["falan", "like"],
["sağ", "right"],
["ihtiyacım", "I need"],
["etti", "It has"],
["gördün", "you saw"],
["dolar", "dollar"],
["umarım", "I hope"],
["beri", "since"],
["değildi", "it was not"],
["etme", "to"],
["öldü", "died"],
["nefret", "hate"],
["veya", "or"],
["sanki", "if"],
["yeter", "enough"],
["su", "That"],
["adamım", "man"],
["yap", "do"],
["kendine", "yourself"],
["haber", "news"],
["sabah", "morning"],
["kendimi", "Myself"],
["dün", "yesterday"],
["akşam", "evening"],
["ateş", "fire"],
["yalan", "lie"],
["dört", "four"],
["geçen", "last"],
["kal", "remain"],
["sonunda", "finally"],
["annem", "My mother"],
["dünya", "world"],
["sence", "what do you think"],
["değilsin", "You are not"],
["ay", "moon"],
["yaptım", "I did"],
["yerine", "instead"],
["hangi", "which"],
["istediğim", "I want"],
["bunları", "these"],
["boyunca", "throughout"],
["üzerinde", "over"],
["tamamen", "completely"],
["adı", "First Name"],
["tabi", "subject"],
["karar", "decision"],
["vardır", "has"],
["aç", "hungry"],
["olduğumu", "I have"],
["adım", "step"],
["olun", "be"],
["gitmek", "go"],
["dedi", "said"],
["ayrıca", "also"],
["bitti", "it's over"],
["gelecek", "the future"],
["sakın", "do not"],
["genç", "young"],
["öyleyse", "then"],
["olmuş", "dead"],
["bende", "Me too"],
["farklı", "different"],
["yaptın", "you did"],
["jack", "jack"],
["olamaz", "can not"],
["bazen", "sometimes"],
["açık", "open"],
["bebeğim", "my baby"],
["yol", "way"],
["pekâlâ", "all right"],
["söyledim", "I told"],
["dr", "dir"],
["john", "John"],
["olursa", "should"],
["İlk", "First"],
["oldukça", "quite"],
["zamanı", "the time"],
["tarafından", "by"],
["sahip", "owner"],
["içeri", "inside"],
["neyse", "anyways"],
["alo", "Hello"],
["oldum", "became"],
["beraber", "together"],
["mükemmel", "excellent"],
["onların", "they"],
["bilirsin", "you know"],
["eder", "it"],
["ettim", "I have"],
["oğlum", "son"],
["cevap", "reply"],
["henüz", "yet"],
["on", "front"],
["yapıyor", "doing"],
["ise", "if"],
["herif", "guy"],
["olması", "being"],
["aldım", "I got"],
["konuşmak", "talk"],
["uzak", "far"],
["kolay", "easy"],
["yanında", "beside"],
["evde", "at home"],
["adamı", "man"],
["birisi", "someone"],
["evlat", "child"],
["başına", "per"],
["fark", "difference"],
["hayatım", "sweetheart"],
["saniye", "second"],
["acele", "rush"],
["araba", "car"],
["düşünüyorsun", "you are thinking"],
["çocuğu", "children"],
["geldim", "I came"],
["yoktu", "did not have"],
["olsa", "Although"],
["rahat", "comfortable"],
["gidiyorum", "I'm going"],
["hâlâ", "still"],
["yolu", "way"],
["görünüyor", "it seems"],
["ara", "Search"],
["yüzünden", "because"],
["a", "a"],
["dersin", "of course"],
["neredeyse", "almost"],
["ancak", "but"],
["hızlı", "fast"],
["dans", "dance"],
["günü", "day"],
["halde", "although"],
["savaş", "war"],
["söylemek", "say"],
["çeneni", "up"],
["ev", "home"],
["geceler", "nights"],
["almak", "receive"],
["şuna", "following the"],
["altında", "under"],
["vay", "Wow"],
["olmadığını", "whether"],
["nasılsın", "how are you doing"],
["güle", "bye"],
["hepimiz", "we all"],
["sanmıyorum", "I do not think so"],
["oyun", "game"],
["boş", "null"],
["süre", "time"],
["bin", "thousand"],
["anlıyorum", "I understand"],
["komik", "funny"],
["durum", "status"],
["galiba", "probably"],
["yaptı", "made"],
["hava", "air"],
["kaldı", "stayed"],
["duydum", "I heard"],
["günaydın", "Good Morning"],
["yeniden", "again"],
["be", "ba"],
["kapıyı", "the door"],
["buldum", "I found"],
["miyiz", "Can"],
["takip", "follow"],
["new", "new"],
["olacağım", "I will be"],
["gelin", "bride"],
["hayal", "dream"],
["düşündüm", "I thought"],
["sende", "cents to"],
["gidiyoruz", "We are going"],
["bebek", "baby"],
["hayat", "life"],
["söylüyor", "says"],
["ciddi", "serious"],
["yardımcı", "helper"],
["kapa", "Collapse"],
["altı", "six"],
["istedim", "I wanted"],
["işin", "ray"],
["canım", "My dear"],
["konuda", "subject"],
["göz", "eye"],
["adamın", "the man"],
["beyler", "gentlemen"],
["düşünüyorum", "I'm thinking"],
["gidiyorsun", "You are going"],
["yaşlı", "old"],
["çalışıyorum", "I am working"],
["herhangi", "any"],
["azından", "least"],
["böylece", "so"],
["kardeşim", "my brother"],
["beyaz", "white"],
["başladı", "started"],
["şaka", "joke"],
["gelip", "to come"],
["telefon", "telephone"],
["hareket", "movement"],
["verin", "give"],
["gelen", "incoming"],
["sürü", "herd"],
["durun", "stay"],
["üzerine", "over"],
["gelir", "income"],
["memnun", "satisfied"],
["şeyin", "thing"],
["kesin", "exact"],
["yolunda", "right"],
["baban", "your father"],
["yeterince", "enough"],
["herşey", "everything"],
["hayatta", "in life"],
["arada", "between"],
["arkadaşım", "friend"],
["kimin", "whose"],
["güçlü", "strong"],
["el", "hand"],
["mısınız", "Are you"],
["anladın", "you understand"],
["verdi", "gave"],
["yakın", "near"],
["çıkar", "interest"],
["konusunda", "about"],
["garip", "strange"],
["bırakın", "release"],
["hepsini", "all"],
["şeye", "thing"],
["İçeri", "Inside"],
["sanıyorsun", "You thought you"],
["soru", "question"],
["silah", "weapon"],
["parayı", "money"],
["çıktı", "output"],
["otur", "sit down"],
["kısa", "short"],
["yapacağım", "I will do"],
["çık", "exit"],
["geldin", "You came"],
["çalışıyor", "working"],
["korkunç", "terrible"],
["durumda", "in the case"],
["anladım", "understood"],
["acaba", "I wonder"],
["kızı", "daughter"],
["iyiyim", "I'm fine"],
["sağol", "thanks"],
["hatta", "even"],
["uygun", "appropriate"],
["haklısın", "You are right"],
["yapamam", "I can not do"],
["terk", "abandonment"],
["yaptığını", "do that"],
["siktir", "Fuck"],
["tür", "type"],
["değildir", "it is not"],
["olduğuna", "that"],
["geliyorum", "I am coming"],
["dön", "frost"],
["şeyleri", "things"],
["kere", "times"],
["şöyle", "As"],
["dikkatli", "careful"],
["kan", "blood"],
["ait", "belonging to"],
["arasında", "between"],
["frank", "franc"],
["bilmek", "know"],
["neyin", "what"],
["neyi", "what"],
["aşağı", "down"],
["çek", "Check"],
["rahatsız", "uncomfortable"],
["veriyorum", "I am giving"],
["dünyanın", "the world"],
["bi", "one"],
["dolu", "full"],
["geçti", "passed"],
["ortaya", "out"],
["verdim", "I gave"],
["varsa", "If"],
["muhtemelen", "probably"],
["yakında", "soon"],
["burda", "here"],
["sevindim", "I'm glad"],
["ihtiyacı", "need"],
["olacağını", "would be"],
["neydi", "what was it"],
["annen", "mother"],
["diyorsun", "you say"],
["sürekli", "continuous"],
["milyon", "million"],
["yüksek", "high"],
["tuhaf", "strange"],
["sizinle", "With you"],
["hissediyorum", "I am feeling"],
["fikir", "idea"],
["zamanda", "time"],
["deli", "mad"],
["olmadan", "without"],
["dışında", "outside"],
["bizimle", "with us"],
["kahrolası", "goddamn"],
["at", "horse"],
["başkan", "president"],
["yukarı", "up"],
["olmayacak", "will be"],
["bayım", "sir"],
["acı", "pain"],
["aldı", "took"],
["olmadı", "It was not"],
["dedin", "you said"],
["aşk", "love"],
["olası", "possible"],
["yalnızca", "Only"],
["getir", "bring"],
["biliyordum", "I knew"],
["kızlar", "girls"],
["sensin", "you"],
["i", "I"],
["tatlı", "dessert"],
["hoşça", "nicely"],
["affedersiniz", "Excuse me"],
["ediyorsun", "you're"],
["yemin", "oath"],
["etmeye", "Do not"],
["ölüm", "death"],
["ölü", "dead"],
["içine", "into"],
["yapacağız", "we will do"],
["edecek", "will"],
["dışarıda", "outside"],
["üzere", "in"],
["yavaş", "slow"],
["tut", "Keep"],
["ihtiyacın", "Your need"],
["tahmin", "prediction"],
["herşeyi", "everything"],
["koca", "husband"],
["birinin", "one's"],
["york", "york"],
["sessiz", "quiet"],
["hasta", "patient"],
["gizli", "hidden"],
["mümkün", "possible"],
["yapacak", "will make"],
["duydun", "you heard"],
["olurdu", "it would be"],
["köpek", "dog"],
["amerika", "America"],
["yapıyorum", "I'm doing"],
["eden", "community"],
["gerektiğini", "ought"],
["ihtiyacımız", "we need"],
["berbat", "wretched"],
["charlie", "charlie"],
["istersen", "if you want"],
["zarar", "damage"],
["sıcak", "hot"],
["ana", "mother"],
["şans", "chance"],
["gidin", "Go"],
["joe", "joe"],
["sanıyordum", "I thought"],
["oradan", "from there"],
["kahve", "coffee"],
["yapmaya", "making"],
["yapar", "makes"],
["olay", "event"],
["dek", "until"],
["görünüyorsun", "you look"],
["diyor", "says"],
["şarkı", "song"],
["vermek", "give"],
["kalk", "get up"],
["nefes", "breath"],
["olup", "The"],
["anlaşıldı", "roger"],
["sevgili", "dear"],
["görüyorum", "I see"],
["orospu", "bitch"],
["bilmem", "I do not know"],
["üstüne", "over"],
["sam", "Sam"],
["insanların", "peoples"],
["evine", "house"],
["varmış", "had"],
["İnsanlar", "People"],
["basit", "simple"],
["film", "film"],
["istediğini", "he wanted"],
["pislik", "dirt"],
["kızım", "my daughter"],
["zavallı", "poor"],
["istedi", "wanted"],
["olmayan", "non-"],
["yedi", "seven"],
["david", "david"],
["pardon", "pardon"],
["alın", "Learn"],
["the", "the"],
["tıpkı", "just as"],
["olmalısın", "You should be"],
["yıldır", "years"],
["isterim", "I want"],
["buradayım", "buradayım"],
["tom", "tom"],
["george", "George"],
["birine", "to someone"],
["herkesin", "everybody's"],
["keşke", "if only"],
["dalga", "wave"],
["benziyor", "looks like"],
["zamandır", "time"],
["sesini", "your voice"],
["unutma", "forgetting"],
["neye", "what"],
["sefer", "expedition"],
["aldın", "lower"],
["bilmiyor", "he does not know"],
["diyorum", "I say"],
["normal", "normal"],
["çeviri", "Translation"],
["ufak", "small"],
["herhalde", "I suppose"],
["ahbap", "buddy"],
["bununla", "With this"],
["baş", "head"],
["ettin", "you've"],
["yapacaksın", "you do"],
["yeterli", "enough"],
["muhteşem", "spectacular"],
["yüz", "face"],
["olacaksın", "you will be"],
["çekil", "get out"],
["görüyor", "sees"],
["yeri", "place"],
["aşkına", "sake"],
["önünde", "in front of"],
["söyledin", "You said"],
["belli", "certain"],
["söylüyorum", "I say"],
["miydi", "was"],
["hata", "error"],
["michael", "michael"],
["söylemiştim", "I say"],
["aile", "family"],
["fena", "bad"],
["düşün", "think"],
["bunların", "these"],
["alabilir", "can take"],
["numara", "number"],
["evi", "the House"],
["bayanlar", "ladies"],
["tehlikeli", "dangerous"],
["millet", "nation"],
["alıp", "take"],
["bilir", "knows"],
["yaşında", "aged"],
["doğum", "birth"],
["yürü", "walk"],
["yoktur", "There is no"],
["bekliyor", "waiting"],
["inanamıyorum", "I cant believe"],
["gitmem", "I dont go"],
["adına", "in the name of"],
["birçok", "many"],
["ses", "sound"],
["içki", "drink"],
["erken", "early"],
["hayatını", "his life"],
["bok", "shit"],
["kendisi", "itself"],
["vakit", "time"],
["İsa", "Jesus"],
["adını", "name"],
["ele", "addressed"],
["seks", "sex"],
["sıkı", "tight"],
["anlıyor", "understands"],
["yaparım", "I do"],
["allah", "God"],
["edeceğim", "I will make"],
["aynen", "exactly"],
["güvenlik", "security"],
["canlı", "Alive"],
["müzik", "music"],
["kaptan", "captain"],
["hatırlıyor", "remember"],
["güç", "power"],
["sonraki", "next"],
["saçma", "absurd"],
["kimsin", "who are you"],
["kırmızı", "red"],
["günler", "days"],
["söyleme", "mention"],
["anlamıyorum", "I do not understand"],
["aşık", "in love"],
["arkadaş", "friend"],
["verir", "gives"],
["bekleyin", "wait"],
["durumu", "status"],
["bakma", "do not look"],
["kimsenin", "anyone"],
["arkadaşın", "your friend"],
["temiz", "clean"],
["oda", "room"],
["birşeyler", "something"],
["niçin", "why"],
["geldik", "we came"],
["çocukları", "children"],
["olduğum", "I'm"],
["düşünüyor", "think"],
["olduğun", "you are"],
["olsaydı", "had"],
["olmasını", "not the"],
["e", "to"],
["bilemiyorum", "I do not know"],
["konuşma", "talk"],
["buldun", "you found"],
["istediğin", "you want"],
["mıydı", "was"],
["s", "s"],
["ikinci", "second"],
["noel", "Christmas"],
["parti", "party"],
["zamanlar", "times"],
["baksana", "heigh"],
["yapmam", "I do not"],
["işler", "works"],
["üstünde", "on"],
["sonsuza", "infinity"],
["yerinde", "in place"],
["anlat", "tell"],
["insanları", "people"],
["sayın", "Dear"],
["bob", "boB"],
["gelmiş", "have come"],
["sıra", "desk"],
["bilmiyordum", "I did not know"],
["asıl", "noble"],
["kızın", "your daughter"],
["seviyor", "love"],
["soğuk", "cold"],
["siyah", "black"],
["yapalım", "let's do"],
["işim", "name"],
["birden", "suddenly"],
["general", "general"],
["almaya", "take"],
["in", "of"],
["yanına", "next"],
["göster", "show"],
["patron", "boss"],
["alacağım", "I will"],
["mike", "mike"],
["buradaki", "here"],
["sonu", "end"],
["tarafa", "party"],
["sigara", "cigaret"],
["salak", "idiot"],
["gerekir", "must"],
["bahsediyorsun", "talking about"],
["harry", "harry"],
["olmasın", "whether"],
["haklı", "right"],
["sert", "hard"],
["konu", "subject"],
["burayı", "here"],
["olmaya", "not to"],
["defa", "times"],
["umurumda", "care"],
["hak", "right"],
["özellikle", "especially"],
["biliyoruz", "we know"],
["bulmak", "find"],
["kimseye", "anyone"],
["baylar", "gentlemen"],
["gitsin", "let go"],
["adamlar", "men"],
["yemeği", "food"],
["tercih", "choice"],
["İyiyim", "I'm fine"],
["istiyorsan", "if you want"],
["dinleyin", "listen"],
["geldiniz", "welcome"],
["olma", "being"],
["iyisi", "good"],
["bilgi", "information"],
["işini", "Your job"],
["acil", "urgent"],
["kalın", "thick"],
["arabayı", "car"],
["dair", "about"],
["yapabilirim", "I can"],
["biriyle", "with a"],
["hepiniz", "all of you"],
["öldürmek", "kill"],
["söylüyorsun", "you say"],
["jimmy", "jimmy"],
["alır", "gets"],
["İşe", "If"],
["defol", "get out"],
["paul", "paul"],
["gerçeği", "truth"],
["bağlı", "connected"],
["babası", "father"],
["duyuyor", "hears"],
["babamın", "my fathers"],
["yola", "way"],
["onlarla", "with them"],
["görmedim", "I did not see"],
["amerikan", "American"],
["gayet", "very"],
["rağmen", "despite"],
["onlardan", "from them"],
["anlamı", "meaning"],
["istemiyor", "does not want"],
["tanıyor", "knows"],
["şehir", "city"],
["zorundayım", "I have to"],
["dua", "prayer"],
["değiliz", "We are not"],
["yaşıyor", "lives"],
["hoşçakal", "bye"],
["çoğu", "most"],
["taraftan", "from the side"],
["kitap", "book"],
["orası", "there"],
["yo", "you"],
["yerini", "place"],
["söyleyeyim", "Let me tell"],
["gelmek", "come"],
["adın", "your name"],
["bizden", "U.S"],
["peter", "Peter"],
["bakayım", "Let me see"],
["uyuşturucu", "drug"],
["kalan", "remaining"],
["dolayı", "because"],
["görmeye", "seeing"],
["kendime", "to myself"],
["teslim", "delivery"],
["güneş", "sun"],
["mary", "Mary"],
["kusura", "defect"],
["kral", "king"],
["kapı", "door"],
["zengin", "rich"],
["parçası", "Part of it"],
["edebilir", "is able to"],
["gir", "enter"],
["dürüst", "honest"],
["kendim", "myself"],
["iç", "inner"],
["kadınlar", "women"],
["cehenneme", "hell"],
["kalmak", "stay"],
["kapat", "Close"],
["altın", "gold"],
["silahı", "weapon"],
["okul", "school"],
["çalışıyorsun", "Are you trying"],
["gider", "expense"],
["canına", "dear to"],
["yüzbaşı", "captain"],
["affedersin", "sorry"],
["istiyorsunuz", "Would you"],
["şeyden", "the thing"],
["sık", "stylish"],
["gurur", "pride"],
["vereceğim", "I will give"],
["mesaj", "message"],
["istiyoruz", "we want"],
["b", "b"],
["sekiz", "eight"],
["hoşuma", "I liked"],
["yaptığı", "his"],
["eğlenceli", "funny"],
["ağır", "heavy"],
["takım", "team"],
["karım", "my wife"],
["davet", "invitation"],
["kutsal", "sacred"],
["ölmüş", "dead"],
["yıllar", "years"],
["yarım", "my love"],
["yapan", "who"],
["hanımefendi", "lady"],
["konuş", "Talk"],
["ray", "rail"],
["james", "james"],
["saçmalık", "bullshit"],
["sona", "ends"],
["olduğundan", "because"],
["herkese", "to everyone"],
["güvenli", "safe"],
["getirdim", "I brought"],
["sahibi", "owner"],
["fikrim", "my idea"],
["çekilin", "the retreat"],
["dünyada", "in the world"],
["satın", "buy"],
["bira", "beer"],
["gitmeliyim", "I must go"],
["teklif", "bid"],
["altına", "under"],
["aferin", "Well done"],
["gidecek", "will go"],
["aptalca", "stupid"],
["bul", "find"],
["mavi", "blue"],
["demektir", "means"],
["hatırlıyorum", "I remember"],
["yüce", "sublime"],
["koy", "put"],
["yaptığın", "you do"],
["unut", "forget"],
["suç", "crime"],
["elinde", "in your hand"],
["balık", "the fish"],
["şuraya", "Distance"],
["severim", "I like it"],
["sebep", "reason"],
["parça", "piece"],
["yapıyorsunuz", "you do"],
["arka", "back"],
["arkadaşı", "his friend"],
["elini", "your hand"],
["eskiden", "formerly"],
["verici", "transmitter"],
["katil", "join"],
["peder", "father"],
["henry", "Henry"],
["kelime", "word"],
["isterdim", "I would like to"],
["düşünüyordum", "I was thinking"],
["deniz", "sea"],
["günün", "your day"],
["çocuğun", "the child"],
["pis", "filthy"],
["istemedim", "I did not want"],
["hoşuna", "welcome to the"],
["gitme", "do not go"],
["adama", "man"],
["sene", "year"],
["istemem", "I do not want"],
["götür", "take"],
["akşamlar", "evenings"],
["cinayet", "murder"],
["İş", "Business"],
["ayağa", "foot"],
["ellerini", "your hands"],
["billy", "billy"],
["mesela", "for example"],
["anlaşma", "contract"],
["kimseyi", "anyone"],
["alan", "area"],
["yaz", "summer"],
["gerekiyordu", "It was supposed"],
["ilginç", "interesting"],
["kavga", "fight"],
["iyilik", "favor"],
["serbest", "independent"],
["söyler", "tell"],
["ye", "eat"],
["edelim", "let's"],
["geldiğini", "that came"],
["sevgilim", "my darling"],
["resmi", "formal"],
["arabaya", "car"],
["olacağız", "We will be"],
["biliyorsunuz", "you know"],
["afedersiniz", "excuse me"],
["veriyor", "giving"],
["oldun", "you have"],
["max", "max"],
["san", "singing"],
["söyleyeceğim", "I will say"],
["yaklaşık", "about"],
["öğrenmek", "learn"],
["yazık", "pity"],
["üçüncü", "third"],
["buralarda", "here"],
["kayıp", "lost"],
["tebrikler", "congratulations"],
["kendin", "yourself"],
["sizden", "from you"],
["hikaye", "story"],
["çoktan", "already"],
["başıma", "my head"],
["kaldım", "I stayed"],
["erkekler", "men"],
["söyleyin", "Say"],
["telefonu", "phone"],
["hale", "halo"],
["albay", "colonel"],
["birinci", "first"],
["yapmayı", "making"],
["birazdan", "soon"],
["duymak", "hear"],
["gideceğim", "I will go"],
["olanlar", "Those"],
["endişelenme", "Do not worry"],
["çeşit", "kind"],
["edeyim", "I will"],
["isim", "name"],
["gittim", "I went"],
["duyuyorum", "I hear"],
["park", "Park"],
["yapabilir", "can"],
["yaptığım", "I made"],
["nick", "Nick"],
["bill", "bill"],
["müthiş", "terrific"],
["piç", "Bastard"],
["ifade", "expression"],
["sesi", "sound"],
["sebebi", "reason"],
["şimdiye", "now"],
["şef", "chef"],
["zeki", "clever"],
["ee", "ee"],
["düşünmüştüm", "I think"],
["süper", "super"],
["hayatın", "Your life"],
["kalmadı", "Sold Out"],
["vakti", "time"],
["birileri", "someone"],
["dan", "from"],
["eee", "eee"],
["görünüşe", "appearance"],
["mıyım", "am I"],
["uh", "uh"],
["yaşamak", "live"],
["şanslı", "lucky"],
["derece", "degree"],
["geriye", "back"],
["okula", "to school"],
["tanıyorum", "I know"],
["herkesi", "everyone"],
["alıyorum", "I'm buying"],
["ta", "t"],
["karanlık", "dark"],
["kimi", "who"],
["yada", "or"],
["yapmış", "made"],
["paris", "Paris"],
["sırada", "Ranked"],
["verme", "supply"],
["gerekli", "necessary"],
["saygı", "respect"],
["koş", "rushed"],
["hayatımı", "my life"],
["orda", "there"],
["yiyecek", "food"],
["olmayı", "to be"],
["yaşam", "life"],
["çıkıp", "out"],
["kalacak", "will stay"],
["kadının", "woman"],
["vur", "hit"],
["sol", "left"],
["jim", "jim"],
["iyidir", "is good"],
["gördüğüm", "I have seen"],
["dene", "try"],
["farkında", "aware"],
["gördünüz", "You saw"],
["evin", "your house"],
["yapmadım", "I did not"],
["alıyor", "taking"],
["asker", "soldier"],
["olurum", "I will be"],
["hayatı", "vital"],
["isteyen", "want"],
["yaramaz", "naughty"],
["bulduk", "we found"],
["yoldan", "the road"],
["yapıyoruz", "we do"],
["suçlu", "guilty"],
["neredesin", "where are you"],
["nesi", "What"],
["çift", "double"],
["korkarım", "I am afraid"],
["alex", "alex"],
["görev", "task"],
["tarafta", "on the side"],
["kara", "black"],
["döndü", "returned"],
["nerde", "where"],
["inanılmaz", "unbelievable"],
["çavuş", "Sergeant"],
["verdin", "you gave"],
["yapabilirsin", "you can"],
["gözlerini", "your eyes"],
["nedeni", "Reason"],
["İkinci", "Second"],
["bilmiyorsun", "You do not know"],
["güven", "confidence"],
["üst", "top"],
["polisi", "police"],
["annesi", "mother"],
["sürece", "as long as"],
["arıyorum", "I'm looking for"],
["hayvan", "animal"],
["oyunu", "game"],
["etmez", "does not"],
["hediye", "present"],
["dünyayı", "the world"],
["danny", "danny"],
["istersin", "you want"],
["açın", "open"],
["istediğimi", "I want"],
["giden", "outgoing"],
["daima", "always"],
["mal", "goods"],
["ayak", "foot"],
["zorundasın", "you have to"],
["duruyor", "stands"],
["olayı", "event"],
["sarah", "sarah"],
["cidden", "really"],
["kadını", "woman"],
["ciddiyim", "I am serious"],
["olman", "Do not be"],
["öldürdü", "killed"],
["sever", "lovers"],
["uyan", "wake up"],
["profesör", "professor"],
["sevdim", "I loved"],
["kalsın", "Keep"],
["elde", "obtained"],
["sıradan", "ordinary"],
["nasılsınız", "nasılsınız"],
["şanslar", "luck"],
["çalıştım", "I worked"],
["olabilirim", "I can"],
["çalışan", "working"],
["alman", "German"],
["kalp", "heart"],
["söylemiştin", "tell you"],
["iğrenç", "disgusting"],
["yanımda", "by my side"],
["johnny", "johnny"],
["sarhoş", "drunk"],
["haline", "into"],
["tamamdır", "it is okay"],
["verecek", "will give"],
["alacak", "credit"],
["d", "D"],
["çıkmak", "exit"],
["yolda", "on the road"],
["tutun", "tobacco"],
["ediyoruz", "we do"],
["ortak", "partner"],
["kafa", "head"],
["ön", "front"],
["edersin", "edersin"],
["kaldır", "remove"],
["londra", "London"],
["sahi", "actually"],
["anlamına", "meaning"],
["amca", "uncle"],
["baştan", "all over"],
["istiyorlar", "they want"],
["teğmen", "lieutenant"],
["gibiydi", "it seemed to"],
["dedektif", "detective"],
["korkuyorum", "I'm afraid"],
["rica", "request"],
["dava", "case"],
["işleri", "jobs"],
["kulak", "ear"],
["gücü", "power"],
["gitmiş", "gone"],
["gerekecek", "need"],
["veririm", "I give"],
["tony", "tony"],
["arıyor", "calling"],
["muydu", "was"],
["geldiğinde", "when"],
["olduğumuzu", "we are"],
["güzeldi", "it was nice"],
["bobby", "bobby"],
["mektup", "letter"],
["eddie", "eddie"],
["günde", "day"],
["ders", "lesson"],
["annemin", "my mom's"],
["yoluna", "way to"],
["çay", "tea"],
["la", "la"],
["muyum", "am I"],
["yerden", "from the ground"],
["derin", "deep"],
["etmiş", "meat"],
["türlü", "various"],
["yaptık", "we did"],
["yolunu", "path"],
["akıllı", "smart"],
["değer", "value"],
["ettiğini", "Watch it"],
["getirin", "bring the"],
["oturun", "sit down"],
["etmeyin", "Do not"],
["domuz", "pig"],
["çalış", "Work"],
["özgür", "free"],
["önceden", "previously"],
["kapalı", "closed"],
["şeytan", "Satan"],
["yardıma", "help"],
["güney", "South"],
["önemi", "the importance"],
["sürpriz", "surprise"],
["kişisel", "personal"],
["grup", "group"],
["alayım", "alayım"],
["m", "m"],
["miydin", "Did you"],
["başlıyor", "starting"],
["uçak", "airplane"],
["sorunun", "the problem"],
["evli", "The married"],
["dünyaya", "to the world"],
["alırım", "I get"],
["ortadan", "the middle"],
["istediği", "wanted"],
["ikiniz", "both of you"],
["doğal", "natural"],
["buydu", "This was"],
["bekliyorum", "I am waiting"],
["bildiğim", "I know"],
["metre", "meter"],
["bazıları", "some"],
["konuşuyor", "speaking"],
["hani", "behold"],
["kaza", "accident"],
["majesteleri", "Your Majesty"],
["ilgisi", "interest"],
["insanlara", "to people"],
["ziyaret", "visit"],
["diğerleri", "others"],
["elimden", "stripped"],
["İnsan", "Human"],
["steve", "steve"],
["başladım", "I started"],
["yeşil", "green"],
["çocukların", "children"],
["ikna", "persuasion"],
["babanın", "father"],
["yarısı", "half"],
["rüya", "dream"],
["kat", "floor"],
["hmm", "hmm"],
["arkasında", "behind"],
["edildi", "It was"],
["you", "you"],
["hiçbirşey", "nothing"],
["topu", "ball"],
["kuzey", "North"],
["muydun", "Did you"],
["edip", "whether"],
["top", "ball"],
["bey", "bey"],
["buradasın", "you are here"],
["bahse", "bet"],
["etmeyi", "Do not"],
["sonuna", "to the end"],
["ölmek", "die"],
["can", "Bell"],
["jake", "jake"],
["şurada", "there"],
["adamla", "man"],
["almış", "received"],
["aşağıda", "below"],
["degil", "not"],
["değerli", "valuable"],
["ararım", "I'll call"],
["zorundayız", "We have"],
["kafayı", "head"],
["numaralı", "numbered"],
["olduğunuzu", "be you"],
["zamanlarda", "in time"],
["ileri", "Further"],
["önceki", "previous"],
["başarılı", "successful"],
["yapman", "do not"],
["gerekirse", "if necessary"],
["zevk", "taste"],
["destek", "support"],
["lee", "lee"],
["olabilirsin", "you can be"],
["gelmiyor", "does not come"],
["geçiyor", "passing"],
["seksi", "sexy"],
["ajan", "agent"],
["aradı", "called"],
["oğlu", "son-"],
["inanıyorum", "I believe"],
["olduklarını", "they are"],
["dışı", "female"],
["sorunu", "problem"],
["şeker", "candy"],
["gitmeliyiz", "we should go"],
["aşağıya", "down"],
["çıkıyor", "turns out"],
["kardeş", "brother"],
["derhal", "immediately"],
["olmam", "I have"],
["mıyız", "Are we"],
["charles", "charles"],
["dokuz", "nine"],
["iyiydi", "good"],
["mesele", "issue"],
["gelmedi", "did not come"],
["don", "frost"],
["yatak", "bed"],
["kalmış", "I have stayed"],
["olmadığı", "it is not"],
["insanın", "people"],
["çin", "China"],
["dönmek", "return"],
["mark", "marker"],
["roma", "Rome"],
["konuyu", "subject"],
["richard", "richard"],
["oturup", "sit"],
["geleni", "from the"],
["tommy", "tommy"],
["resim", "picture"],
["İmdat", "Help"],
["gelebilir", "may come"],
["arıyorsun", "are you looking"],
["yazıyor", "he is writing"],
["yabancı", "foreign"],
["şarap", "wine"],
["kaybettim", "I lost"],
["kıçını", "ass"],
["çalışma", "work"],
["ünlü", "famous"],
["bomba", "bomb"],
["nasıi", "How"],
["üzgün", "sad"],
["olanları", "ones"],
["jerry", "Jerry"],
["olduğunda", "when"],
["askeri", "military"],
["imkansız", "impossible"],
["tehdit", "threatening"],
["araya", "together"],
["yemeğe", "eat"],
["elimde", "in my hand"],
["alt", "lower"],
["deme", "do not say"],
["olanı", "with"],
["çalışmak", "work"],
["adamları", "men"],
["çılgın", "crazy"],
["plan", "plan"],
["yağmur", "rain"],
["anlamadım", "I did not understand"],
["etrafta", "around"],
["boktan", "shitty"],
["aşağılık", "Despicable"],
["buz", "ice"],
["güvende", "in confidence"],
["hapse", "jail"],
["gideceğiz", "we will go"],
["çekici", "attractive"],
["sanmıştım", "I think"],
["havaya", "up"],
["yakışıklı", "handsome"],
["İzin", "Permission"],
["aklıma", "to my mind"],
["der", "says"],
["yıldız", "star"],
["mantıklı", "sensible"],
["girdi", "entry"],
["sevdiğim", "Favorite"],
["sandım", "I thought"],
["aklını", "your mind"],
["demiştim", "I said"],
["ailem", "parents"],
["buyurun", "Help yourself"],
["İngiliz", "British"],
["edebilirim", "I can"],
["kocaman", "huge"],
["söylemem", "I say"],
["ailesi", "family"],
["kime", "to who"],
["öldür", "kill"],
["olsam", "I would"],
["ederiz", "we will"],
["teki", "one of"],
["evden", "house"],
["k", "k"],
["konuşabilir", "can speak"],
["çıkın", "Quit"],
["şerif", "Sheriff"],
["kardeşin", "brother"],
["başlıyoruz", "we begin"],
["söylediler", "they said"],
["düştü", "fell"],
["mr", "m"],
["jane", "jane"],
["geçmiş", "past"],
["sor", "sir"],
["hazırım", "I am ready"],
["başla", "Start"],
["dokunma", "Do not touch"],
["şimdilik", "for now"],
["evinde", "house"],
["aşırı", "extreme"],
["aramızda", "in our midst"],
["değildim", "I was not"],
["söyleyecek", "will say"],
["karısı", "his wife"],
["bunlardan", "of them"],
["hatırladın", "remind"],
["sayılmaz", "does not count"],
["memur", "officer"],
["yan", "side"],
["dünyadaki", "around the world"],
["gittiğini", "Go to it"],
["oynamak", "play"],
["yüzünü", "his face"],
["yapayım", "Shall I"],
["öylece", "just"],
["kitabı", "book"],
["girin", "enter"],
["anna", "anna"],
["birer", "a"],
["aldık", "We received"],
["zayıf", "weak"],
["sıkıcı", "boring"],
["bayağı", "pretty"],
["işten", "fired"],
["saatte", "hours"],
["adil", "fair"],
["önüne", "before"],
["söylemişti", "he said"],
["çirkin", "ugly"],
["ışık", "light"],
["uzakta", "away"],
["zamanında", "on time"],
["pazar", "Sunday"],
["anlama", "understanding"],
["geleceğim", "My future"],
["söylemedim", "I do not say"],
["ikimiz", "the two of us"],
["kenara", "aside"],
["not", "note"],
["İnanılmaz", "Unbelievable"],
["kuş", "bird"],
["yana", "sideways"],
["savaşı", "war"],
["hizmet", "service"],
["yaşayan", "live"],
["lan", "man"],
["sahte", "fake"],
["yapın", "Make"],
["polisler", "police officers"],
["başlayalım", "lets start"],
["t", "t"],
["ruh", "spirit"],
["olacaktır", "will be"],
["gemi", "ship"],
["buldu", "found"],
["chris", "chris"],
["söylemeye", "tell"],
["kate", "catenin"],
["söylediğim", "I say"],
["sınıf", "class"],
["dave", "dave"],
["başı", "head"],
["evlilik", "marriage"],
["çıkarın", "Disconnect"],
["anlaştık", "agreed"],
["bilim", "science"],
["işine", "job"],
["düzgün", "smooth"],
["ismi", "Browse"],
["robert", "robert"],
["dönerim", "I'll be back"],
["fazlasını", "more"],
["problem", "problem"],
["hayatımın", "my life"],
["binlerce", "thousands"],
["zenci", "black"],
["genelde", "usually"],
["afedersin", "sorry"],
["karın", "abdomen"],
["zamana", "time"],
["gelince", "as for"],
["gelmez", "does not"],
["aradım", "I called"],
["gibisin", "You seem"],
["com", "com"],
["bişey", "something"],
["korumak", "protect"],
["los", "loess"],
["ediyorlar", "they're"],
["fransız", "French"],
["göstermek", "show"],
["İngiltere", "Britain"],
["dahil", "including"],
["filmi", "film"],
["oradaki", "there"],
["andy", "andy"],
["hastaneye", "to hospital"],
["iyice", "thoroughly"],
["konuşmaya", "to talk"],
["öldürmeye", "kill"],
["tamir", "repair"],
["avukat", "Lawyer"],
["kocam", "my husband"],
["öldürdün", "you killed"],
["olursun", "you'd"],
["gösteriyor", "is showing"],
["suyu", "water"],
["hamile", "pregnant"],
["iptal", "cancel"],
["yukarıda", "above"],
["koç", "coach"],
["will", "will"],
["iyisini", "the best"],
["bol", "plenty"],
["prenses", "princess"],
["cuma", "Friday"],
["yargıç", "judge"],
["cesur", "brave"],
["mil", "shaft"],
["döneceğim", "I will come"],
["diyeceğim", "I say"],
["parasını", "money"],
["param", "my money"],
["taş", "rock"],
["hallederim", "I got"],
["kadarıyla", "as far as"],
["bıraktım", "I left"],
["bakmak", "look"],
["meşgul", "busy"],
["martin", "martin"],
["odasında", "in room"],
["yaptığımı", "do what I"],
["ettik", "I've"],
["etmem", "I would not"],
["nerden", "where"],
["süredir", "time is"],
["mutluyum", "I'm happy"],
["boşver", "Never mind"],
["doğu", "East"],
["yapacağımı", "to do"],
["getirdi", "brought"],
["görüyorsun", "you see"],
["canını", "canını"],
["yaparsın", "you do"],
["hangisi", "which"],
["yapamazsın", "You can not"],
["fırsat", "opportunity"],
["zamanki", "the time"],
["kedi", "cat"],
["birazcık", "a little"],
["sağlam", "sturdy"],
["şansı", "chance"],
["başkanı", "chairman"],
["zamandan", "time"],
["c", "c"],
["taksi", "taxi"],
["r", "r"],
["batı", "West"],
["sizce", "what do you think"],
["olmuştu", "had been"],
["kör", "blind"],
["girmek", "enter"],
["haberi", "news"],
["göremiyorum", "I can not see"],
["unuttum", "I forgot"],
["yakaladım", "I caught"],
["vahşi", "wild"],
["özledim", "I missed"],
["söylerim", "I say"],
["hayatımda", "in my life"],
["görmüş", "have seen"],
["elimizde", "our hands"],
["tv", "TV"],
["bıraktı", "he left"],
["hatırlamıyorum", "I do not remember"],
["değiller", "They are not"],
["gösteri", "show"],
["birbirimizi", "each other"],
["yolculuk", "trip"],
["arkadaşlar", "friends"],
["yahudi", "Jewish"],
["İşin", "Ray"],
["durma", "stop"],
["hayir", "no"],
["larry", "larry"],
["söylesene", "tell me"],
["william", "william"],
["girecek", "will enter"],
["emir", "order"],
["yapabiliriz", "we can"],
["kulağa", "ear"],
["sırasında", "during"],
["diyelim", "let's say"],
["olmasına", "not to"],
["adi", "First Name"],
["öğle", "noon"],
["brian", "brian"],
["kiminle", "with whom"],
["babamı", "my father"],
["walter", "walter"],
["geride", "back"],
["istedin", "did you"],
["silahını", "the weapons"],
["yerlerde", "places"],
["dönüp", "return"],
["elinden", "the hand"],
["kurtarmak", "rescue"],
["İnsanların", "Peoples"],
["nasıldı", "how was it"],
["test", "test"],
["fotoğraf", "photo"],
["ters", "reverse"],
["bölüm", "episode"],
["budur", "This is"],
["çıplak", "naked"],
["tavuk", "chicken"],
["washington", "washington"],
["geçiyorsun", "are you kidding me"],
["and", "and"],
["kevin", "kevin"],
["madam", "madam"],
["l", "l"],
["yarı", "half"],
["of", "Ugh"],
["benzer", "similar"],
["başında", "early"],
["buradayız", "we are here"],
["etmiyor", "does not"],
["öldüreceğim", "I will kill"],
["İstediğin", "You want"],
["söylemedin", "you did not tell"],
["veren", "that"],
["rapor", "report"],
["çıkmış", "out"],
["ikisi", "the two"],
["bilirsiniz", "you know"],
["kahraman", "hero"],
["odası", "room"],
["arama", "search"],
["şükür", "Thank god"],
["olmuyor", "It is not"],
["konusu", "subject"],
["konuştum", "I talked to"],
["kaltak", "bitch"],
["fahişe", "whore"],
["ayrı", "separate"],
["giriş", "login"],
["harekete", "motion"],
["kullan", "use"],
["cesaret", "courage"],
["ettiler", "they"],
["adında", "named"],
["edemem", "I can not"],
["parlak", "bright"],
["angeles", "angeles"],
["thomas", "thomas"],
["sayesinde", "thanks to"],
["alalım", "Let's"],
["yüzde", "percent"],
["işaret", "mark"],
["şeyim", "My stuff"],
["bakıyorum", "I'm looking"],
["bizler", "ourselves"],
["kızla", "girl"],
["İngilizce", "The English"],
["bilirim", "I know"],
["fbi", "FBI"],
["merkezi", "central"],
["konuşuyorsun", "you are talking"],
["masum", "innocent"],
["dediğimi", "I also"],
["kilo", "kilo"],
["girerim", "I'll"],
["düşman", "foe"],
["it", "it"],
["edeceğiz", "We will"],
["kişinin", "the people"],
["yirmi", "twenty"],
["sıradaki", "Next"],
["yapmamı", "make my"],
["birbirimize", "each other"],
["görüşmek", "discuss"],
["ettiğim", "I've"],
["başa", "head"],
["okulda", "at school"],
["bakıyorsun", "looking at you"],
["dönüyor", "returns"],
["çıkan", "outgoing"],
["beyefendi", "gentleman"],
["gittin", "you went"],
["kıza", "girl"],
["bölge", "region"],
["orta", "middle"],
["yat", "yacht"],
["parmak", "finger"],
["futbol", "football"],
["filan", "and so on"],
["itibaren", "from"],
["yapıyorlar", "They are doing"],
["ihtiyaç", "need"],
["araştırma", "research"],
["tedavi", "treatment"],
["sorumlu", "responsible"],
["hariç", "excluding"],
["cep", "pocket"],
["arasındaki", "between"],
["sus", "ornamental"],
["ardından", "next"],
["birisin", "one"],
["engel", "obstacle"],
["ülke", "country"],
["şimdiden", "already"],
["tren", "train"],
["ortada", "in the middle"],
["geliyorlar", "they come"],
["idare", "administration"],
["tarafı", "side"],
["fransa", "France"],
["serseri", "punk"],
["nazik", "kind"],
["bırakıp", "leave"],
["burdan", "from here"],
["istiyordum", "I wanted"],
["televizyon", "television"],
["yıllık", "yearly"],
["gene", "again"],
["olmaktan", "being"],
["tanıştığımıza", "to meet"],
["üzerinden", "over"],
["bulmaya", "find"],
["seçim", "selection"],
["iyisin", "you're good"],
["madem", "since"],
["odada", "in the room"],
["eh", "City"],
["kar", "snow"],
["arabada", "In the car"],
["parası", "money"],
["canavar", "monster"],
["j", "j"],
["numarası", "its number"],
["konuşalım", "Let's talk"],
["banka", "bank"],
["rock", "rock"],
["kurt", "Kurd"],
["sakıncası", "mind"],
["kızgın", "angry"],
["carl", "carla"],
["annenin", "your mother's"],
["barış", "peace"],
["sormak", "ask"],
["gördü", "he saw"],
["verdiği", "tweaking"],
["uyuyor", "sleeping"],
["yatağa", "To bed"],
["cumartesi", "Saturday"],
["kokuyor", "smells"],
["öğleden", "afternoon"],
["annemi", "my mother"],
["sey", "thing"],
["spor", "Sport"],
["nin", "the"],
["yalancı", "liar"],
["yolun", "the road"],
["hedef", "target"],
["avrupa", "Europe"],
["mutlaka", "surely"],
["kazanmak", "win"],
["onda", "tenth"],
["İçinde", "In"],
["polise", "police"],
["öldürecek", "will kill"],
["geleceğini", "the future"],
["itiraf", "confession"],
["üstelik", "moreover"],
["savunma", "defense"],
["odasına", "room"],
["gerekmiyor", "You do not need"],
["dönün", "Return"],
["arthur", "arthur"],
["olağanüstü", "exceptional"],
["sevimli", "cute"],
["dersiniz", "your course"],
["usta", "master"],
["epey", "quite"],
["matt", "matt"],
["bilmiyoruz", "We do not know"],
["olabileceğini", "might"],
["saldırı", "attack"],
["yıllardır", "for years"],
["sola", "left"],
["neymiş", "neymiş"],
["peşinde", "behind"],
["yapmayın", "do not"],
["demiştin", "You said"],
["olsaydım", "if I were"],
["çıkış", "exit"],
["aşkım", "Darling"],
["alice", "alice"],
["yapmamız", "we do"],
["n", "n"],
["vereyim", "Let me give you"],
["yarar", "benefit"],
["lisa", "lisa"],
["bunda", "herein"],
["kendinizi", "yourself"],
["öğrendim", "I learned"],
["hayatının", "of life"],
["tanışmak", "meet"],
["biliyordu", "he knew"],
["kimdi", "who"],
["korku", "fear"],
["veremem", "can not give"],
["başını", "head"],
["eğlence", "entertainment"],
["yapacağını", "would do"],
["bakmayın", "look"],
["derler", "they say"],
["unuttun", "you forgot"],
["hissettim", "I felt"],
["kısmı", "partial"],
["sanat", "art"],
["içeride", "inside"],
["doğrusu", "actually"],
["İnan", "Believe"],
["sır", "secret"],
["götürün", "take"],
["inanmıyorum", "I do not believe"],
["tutmak", "keep"],
["olmalıyım", "I should be"],
["amerikalı", "American"],
["kurşun", "bullet"],
["üzüldüm", "I'm sorry"],
["diyorlar", "they say"],
["değilse", "if not"],
["düğün", "wedding"],
["yasal", "legal"],
["ettiği", "Watch it"],
["fazlası", "more than"],
["kaçtı", "escaped"],
["dediğim", "I also"],
["bizde", "us"],
["başından", "At the beginning"],
["sırf", "sheer"],
["kendisini", "himself"],
["alma", "taking"],
["şeylerin", "things"],
["ulusal", "National"],
["beyin", "brain"],
["etmelisin", "You should"],
["fikrin", "the idea"],
["kardeşi", "brother"],
["edeceksin", "you're going"],
["sürtük", "slut"],
["şansın", "the chance"],
["insanı", "human"],
["istemiştim", "I want"],
["tavsiye", "advice"],
["sağa", "right"],
["ordu", "army"],
["şerefe", "Cheers"],
["canın", "the soul"],
["çalışıyoruz", "we are working"],
];
