let dict = [ ['de', 'of'],
['que', 'what'],
['no', 'not'],
['a', 'to'],
['la', 'the'],
['el', 'he'],
['y', 'Y'],
['es', 'is'],
['en', 'in'],
['lo', 'the'],
['un', 'a'],
['por', 'by'],
['qué', 'what'],
['me', 'I'],
['una', 'a'],
['te', 'tea'],
['se', 'I know'],
['los', 'the'],
['con', 'with'],
['para', 'for'],
['mi', 'me'],
['está', 'this'],
['si', 'yes'],
['sí', 'yes'],
['pero', 'but'],
['las', 'the'],
['bien', 'good'],
['yo', 'me'],
['su', 'his'],
['eso', 'that'],
['aquí', 'here'],
['del', 'of the'],
['al', 'to the'],
['como', 'how'],
['le', 'you'],
['tu', 'you'],
['más', 'plus'],
['todo', 'all'],
['ya', 'already'],
['muy', 'very'],
['esto', 'this'],
['vamos', 'Lets go'],
['ha', 'he has'],
['ahora', 'now'],
['esta', 'this'],
['hay', 'there are'],
['estoy', 'am'],
['algo', 'something'],
['tú', 'you'],
['tengo', 'I have'],
['así', 'So'],
['nada', 'nothing'],
['nos', 'us'],
['cuando', 'when'],
['cómo', 'how'],
['él', 'he'],
['sé', 'I know'],
['estás', 'these'],
['sólo', 'single'],
['o', 'or'],
['quiero', 'I want'],
['este', 'this'],
['tiene', 'have'],
['gracias', 'thanks'],
['he', 'I'],
['puedo', 'may l'],
['bueno', 'good'],
['soy', 'I am'],
['era', 'was'],
['ser', 'to be'],
['vez', 'time'],
['hacer', 'do'],
['todos', 'everybody'],
['ella', 'she'],
['son', 'They are'],
['fue', 'it was'],
['eres', 'you are'],
['usted', 'you'],
['tienes', 'you have'],
['puede', 'may'],
['señor', 'Sir'],
['ese', 'that'],
['voy', 'I go'],
['quién', 'who'],
['casa', 'House'],
['creo', 'I think'],
['porque', 'why'],
['tan', 'so'],
['favor', 'favor'],
['hola', 'Hello'],
['dónde', 'where'],
['nunca', 'never'],
['sus', 'their'],
['sabes', 'you know'],
['dos', 'two'],
['verdad', 'TRUE'],
['quieres', 'you want'],
['mucho', 'a lot'],
['entonces', 'so'],
['estaba', 'I was'],
['tiempo', 'weather'],
['mí', 'me'],
['esa', 'that'],
['mejor', 'best'],
['hombre', 'man'],
['hace', 'does'],
['va', 'goes'],
['dios', 'God'],
['también', 'too'],
['has', 'you'],
['vida', 'lifetime'],
['sin', 'without'],
['están', 'is it so'],
['ver', 'watch'],
['sr', 'Mr'],
['siempre', 'always'],
['oh', 'oh'],
['hasta', 'until'],
['ti', 'you'],
['ahí', 'there'],
['siento', 'sorry'],
['puedes', 'you may'],
['decir', 'tell'],
['ni', 'neither'],
['sobre', 'on'],
['años', 'years'],
['tenemos', 'we have'],
['uno', 'one'],
['día', 'day'],
['noche', 'night'],
['cosas', 'stuff'],
['alguien', 'someone'],
['antes', 'before'],
['mis', 'my'],
['ir', 'go'],
['poco', 'little bit'],
['otra', 'other'],
['quiere', 'wants'],
['solo', 'alone'],
['nadie', 'nobody'],
['nosotros', 'U.S'],
['padre', 'father'],
['gente', 'people'],
['parece', 'It seems'],
['dinero', 'money'],
['estar', 'to be'],
['hecho', 'done'],
['les', 'them'],
['mismo', 'same'],
['sea', 'be'],
['estamos', 'we are'],
['mira', 'look'],
['pasa', 'pass'],
['trabajo', 'job'],
['dijo', 'He said'],
['ellos', 'they'],
['vas', 'you go'],
['claro', 'Sure'],
['mañana', 'tomorrow'],
['han', 'They have'],
['otro', 'other'],
['después', 'then'],
['desde', 'since'],
['mundo', 'world'],
['hablar', 'talk'],
['tal', 'such'],
['había', 'there were'],
['sabe', 'knows'],
['acuerdo', 'agreement'],
['momento', 'moment'],
['donde', 'where'],
['fuera', 'outside'],
['hijo', 'son'],
['podría', 'might'],
['seguro', 'sure'],
['mujer', 'woman'],
['amigo', 'friend'],
['días', 'days'],
['madre', 'mother'],
['allí', 'there'],
['cosa', 'thing'],
['tus', 'your'],
['lugar', 'place'],
['dice', 'He says'],
['gusta', 'like'],
['será', 'will be'],
['gran', 'great'],
['mierda', 'shit'],
['tenía', 'I had'],
['mamá', 'mom'],
['papá', 'dad'],
['espera', 'wait'],
['hoy', 'today'],
['tener', 'to have'],
['ven', 'come'],
['buena', 'good'],
['estado', 'state'],
['nuevo', 'new'],
['luego', 'then'],
['podemos', 'we can'],
['tres', 'three'],
['dije', 'said'],
['nuestro', 'our'],
['sido', 'been'],
['menos', 'less'],
['debe', 'should'],
['tipo', 'type'],
['buen', 'good'],
['conmigo', 'with me'],
['mal', 'evil'],
['todas', 'all'],
['nombre', 'Name'],
['haciendo', 'doing'],
['crees', 'think'],
['toda', 'all'],
['amor', 'love'],
['mío', 'Own'],
['visto', 'viewed'],
['estas', 'these'],
['quería', 'wanted to'],
['eh', 'Hey'],
['tarde', 'late'],
['importa', 'matters'],
['parte', 'part'],
['aún', 'yet'],
['nuestra', 'our'],
['tienen', 'they have'],
['tanto', 'so much'],
['cada', 'each'],
['hora', 'time'],
['veces', 'times'],
['necesito', 'needed'],
['contigo', 'with you'],
['ve', 'go'],
['haber', 'to have'],
['buenas', 'good'],
['dicho', 'saying'],
['quien', 'who'],
['hacerlo', 'do what'],
['demasiado', 'too'],
['oye', 'hears'],
['ah', 'ah'],
['haces', 'do'],
['hombres', 'mens'],
['saber', 'to know'],
['entre', 'between'],
['adiós', 'goodbye'],
['problema', 'trouble'],
['unos', 'some'],
['vaya', 'go'],
['hemos', 'we have'],
['cierto', 'TRUE'],
['debo', 'I must'],
['razón', 'reason'],
['alguna', 'any'],
['esos', 'those'],
['pues', 'well'],
['veo', 'I see'],
['idea', 'idea'],
['chica', 'girl'],
['realmente', 'Really'],
['policía', 'policeman'],
['hizo', 'did'],
['estos', 'these'],
['amigos', 'friends'],
['ustedes', 'your'],
['quizá', 'maybe'],
['serio', 'I laughed'],
['cabeza', 'head'],
['hermano', 'brother'],
['digo', 'I say'],
['van', 'go'],
['pasado', 'past'],
['salir', 'get out'],
['cuenta', 'account'],
['familia', 'family'],
['cariño', 'sweetie'],
['vale', 'okay'],
['algún', 'some'],
['muchas', 'many'],
['señora', 'Ms'],
['somos', 'we are'],
['pueden', 'they can'],
['noches', 'nights'],
['muerto', 'dead'],
['ud', 'You'],
['todavía', 'still'],
['rápido', 'Quick'],
['viejo', 'old'],
['lado', 'side'],
['debería', 'should'],
['ves', 'you see'],
['sabía', 'I knew'],
['suerte', 'luck'],
['cuidado', 'watch out'],
['buenos', 'good ones'],
['sería', 'would'],
['da', 'gives'],
['mientras', 'While'],
['miedo', 'fear'],
['primera', 'first'],
['contra', 'against'],
['puerta', 'door'],
['pronto', 'soon'],
['e', 'and'],
['casi', 'almost'],
['nueva', 'new'],
['espero', 'I hope'],
['cualquier', 'any'],
['esas', 'those'],
['agua', 'Water'],
['os', 'you'],
['chico', 'boy'],
['cuánto', 'how much'],
['niños', 'children'],
['venga', 'come on'],
['camino', 'road'],
['primero', 'First'],
['hacia', 'toward'],
['pensé', 'I thought'],
['dentro', 'inside'],
['pasó', 'He passed'],
['debes', 'you must'],
['ciudad', 'city'],
['historia', 'history'],
['año', 'year'],
['viene', 'comes'],
['deja', 'let'],
['durante', 'during'],
['forma', 'shape'],
['volver', 'return'],
['feliz', 'happy'],
['ojos', 'eyes'],
['guerra', 'war'],
['caso', 'case'],
['chicos', 'Boys'],
['esposa', 'wife'],
['adelante', 'ahead'],
['cuál', 'which one'],
['mano', 'hand'],
['hice', 'I did'],
['vi', 'saw'],
['gustaría', 'would like'],
['muerte', 'death'],
['allá', 'there'],
['mas', 'more'],
['loco', 'crazy'],
['supuesto', 'supposed'],
['toma', 'taking'],
['minutos', 'minutes'],
['haré', 'I will do'],
['entiendo', 'I get it'],
['pasar', 'pass'],
['iba', 'I was going'],
['corazón', 'heart'],
['semana', 'week'],
['jefe', 'boss'],
['venir', 'come'],
['manos', 'hands'],
['ayuda', 'help'],
['problemas', 'problems'],
['juntos', 'together'],
['supongo', 'I suppose'],
['déjame', 'let me'],
['importante', 'important'],
['vete', 'go away'],
['niño', 'child'],
['arriba', 'up'],
['hija', 'daughter'],
['otros', 'others'],
['sra', 'Mrs'],
['personas', 'people'],
['tierra', 'land'],
['manera', 'way'],
['hablando', 'talking'],
['fin', 'end'],
['mujeres', 'women'],
['cara', 'face'],
['grande', 'big'],
['ningún', 'any'],
['nuestros', 'our'],
['cinco', 'five'],
['llama', 'call'],
['hey', 'hey'],
['habla', 'speaks'],
['bajo', 'low'],
['dices', 'say'],
['poder', 'power'],
['cuándo', 'when'],
['quizás', 'maybe'],
['escucha', 'listens'],
['persona', 'person'],
['horas', 'hours'],
['tío', 'uncle'],
['aunque', 'although'],
['io', 'io'],
['único', 'only'],
['dijiste', 'said'],
['siquiera', 'at least'],
['quieren', 'they want'],
['ninguna', 'none'],
['cerca', 'close'],
['pequeño', 'little'],
['debemos', 'we must'],
['cree', 'cree'],
['dame', 'give to me'],
['sigue', 'follow'],
['auto', 'car'],
['cuatro', 'four'],
['dejar', 'leave'],
['muchos', 'Many'],
['igual', 'same'],
['hago', 'I make'],
['listo', 'ready'],
['significa', 'it means'],
['capitán', 'captain'],
['clase', 'class'],
['llegar', 'to get'],
['doctor', 'doctor'],
['suficiente', 'enough'],
['tomar', 'drink'],
['vivir', 'to live'],
['joven', 'young'],
['trabajar', 'to work'],
['haya', 'beech'],
['abajo', 'down'],
['hubiera', 'had'],
['primer', 'first'],
['genial', 'great'],
['justo', 'fair'],
['pensar', 'think'],
['misma', 'same'],
['puta', 'bitch'],
['comer', 'eat'],
['necesita', 'needs to'],
['conozco', 'I know'],
['fui', 'I was'],
['algunos', 'Some'],
['entrar', 'get in'],
['fuerte', 'strong'],
['número', 'number'],
['srta', 'Ms'],
['morir', 'To die'],
['basta', 'Enough'],
['dar', 'give'],
['bastante', 'quite'],
['amo', 'love'],
['atrás', 'behind'],
['dicen', 'say'],
['difícil', 'difficult'],
['éste', 'this'],
['pueda', 'can'],
['punto', 'point'],
['vino', 'wine'],
['hermana', 'sister'],
['hijos', 'sons'],
['unas', 'nail'],
['final', 'final'],
['escuela', 'school'],
['podía', 'I could'],
['pueblo', 'village'],
['haga', 'make'],
['sangre', 'blood'],
['meses', 'months'],
['coche', 'car'],
['juego', 'game'],
['encontrar', 'find'],
['realidad', 'reality'],
['cuerpo', 'Body'],
['mayor', 'higher'],
['última', 'last'],
['eran', 'they were'],
['queda', 'remains'],
['ok', 'okay'],
['paz', 'peace'],
['dime', 'tell me'],
['vuelta', 'return'],
['hiciste', 'did'],
['tenido', 'had'],
['sola', 'alone'],
['hacen', 'make'],
['ido', 'gone'],
['querida', 'Dear'],
['iré', 'I will go'],
['culpa', 'guilt'],
['malo', 'bad'],
['chicas', 'girls'],
['comida', 'food'],
['dólares', 'Dollars'],
['dr', 'dr'],
['saben', 'they know'],
['fácil', 'easy'],
['alto', 'high'],
['posible', 'possible'],
['maldito', 'damned'],
['dormir', 'sleep'],
['deberías', 'you should'],
['maldita', 'damn'],
['pregunta', 'question'],
['incluso', 'even'],
['fiesta', 'party'],
['tampoco', 'neither'],
['cama', 'bed'],
['lejos', 'far'],
['medio', 'means, medium'],
['preocupes', 'worry'],
['ay', 'Oh'],
['teléfono', 'phone'],
['diga', 'tell'],
['ei', 'ei'],
['trata', 'about'],
['equipo', 'team'],
['palabra', 'word'],
['cuanto', 'how much'],
['idiota', 'moron'],
['esté', 'this'],
['luz', 'light'],
['tuve', 'I had'],
['país', 'country'],
['segundo', 'second'],
['querido', 'Dear'],
['diablos', 'Devils'],
['hagas', 'you do'],
['señorita', 'miss'],
['oportunidad', 'opportunity'],
['matar', 'kill'],
['algunas', 'some'],
['esperando', 'waiting'],
['necesitamos', 'we need'],
['adónde', 'where'],
['verte', 'to see you'],
['estará', 'will be'],
['venido', 'I come'],
['estabas', 'you were'],
['fueron', 'were'],
['seis', 'six'],
['tenga', 'have'],
['cuarto', 'room'],
['cielo', 'heaven'],
['vivo', 'alive'],
['recuerdo', 'memory'],
['perdón', 'sorry'],
['falta', 'lack'],
['pequeña', 'little'],
['oído', 'ear'],
['creer', 'believe'],
['john', 'john'],
['pienso', 'I think'],
['ésta', 'this'],
['esperar', 'wait'],
['necesitas', 'you need'],
['aqui', 'here'],
['película', 'movie'],
['además', 'further'],
['marido', 'husband'],
['perro', 'dog'],
['general', 'general'],
['calle', 'Street'],
['exactamente', 'exactly'],
['rey', 'king'],
['padres', 'parents'],
['lista', 'list'],
['habrá', 'there will be'],
['habitación', 'room'],
['carajo', 'fuck'],
['pensando', 'thinking'],
['par', 'pair'],
['fuego', 'fire'],
['niña', 'girl'],
['seguir', 'follow'],
['música', 'music'],
['di', 'gave'],
['habría', 'there would be'],
['mucha', 'a lot'],
['paso', 'He passed'],
['sentido', 'sense'],
['diré', 'I will say'],
['podrías', 'could you'],
['afuera', 'outside'],
['digas', 'you say'],
['ia', 'ia'],
['mía', 'mine'],
['murió', 'died'],
['dio', 'it gave'],
['café', 'coffee'],
['entiendes', 'You understand'],
['nuestras', 'our'],
['piensa', 'think'],
['ello', 'it'],
['lleva', 'carries'],
['estuvo', 'he was'],
['último', 'latest'],
['diciendo', 'saying'],
['grandes', 'big'],
['sitio', 'site'],
['libro', 'book'],
['buscando', 'searching'],
['bebé', 'baby'],
['cállate', 'shut up'],
['vuelve', 'returns'],
['jamás', 'Never'],
['minuto', 'minute'],
['arma', 'weapon'],
['viaje', 'travel'],
['única', 'only'],
['muchachos', 'boys'],
['perdido', 'lost'],
['jugar', 'to play'],
['diez', 'ten'],
['vemos', 'we see'],
['dado', 'dice'],
['sabemos', 'we know'],
['mil', 'thousand'],
['demás', 'the rest'],
['gusto', 'taste'],
['peor', 'worst'],
['irme', 'leave'],
['jack', 'Jack'],
['estaban', 'They were'],
['orden', 'order'],
['pasando', 'going'],
['cambio', 'change'],
['extraño', 'strange'],
['pobre', 'poor'],
['ropa', 'clothing'],
['queremos', 'we want'],
['oficina', 'office'],
['sino', 'if not'],
['modo', 'mode'],
['ocurre', 'occurs'],
['muchacho', 'boy'],
['otras', 'other'],
['hará', 'will'],
['libre', 'free'],
['conoces', 'know'],
['piensas', 'think'],
['presidente', 'President'],
['especial', 'special'],
['anoche', 'last night'],
['millones', 'millions'],
['acerca', 'about'],
['derecho', 'law'],
['negro', 'black'],
['acá', 'here'],
['caballeros', 'gentlemen'],
['semanas', 'weeks'],
['palabras', 'words'],
['buscar', 'search for'],
['segura', 'safe'],
['correcto', 'Right'],
['frente', 'front'],
['hacemos', 'we make'],
['seas', 'be'],
['detrás', 'behind'],
['puesto', 'Market Stall'],
['asunto', 'affair'],
['duro', 'Lasted'],
['sucede', 'happens'],
['llamar', 'to call'],
['disculpe', 'sorry'],
['boca', 'mouth'],
['atención', 'Attention'],
['mire', 'Look'],
['armas', 'weapons'],
['encima', 'over'],
['demonios', 'got damn'],
['mala', 'bad'],
['llevar', 'wear'],
['cual', 'which one'],
['odio', 'hate'],
['hospital', 'hospital'],
['deben', 'should'],
['sueño', 'dream'],
['quieras', 'want'],
['resto', 'rest'],
['llamo', 'I call'],
['perder', 'to lose'],
['llamado', 'called'],
['perfecto', 'perfect'],
['estaré', 'I will be'],
['tranquilo', 'quiet'],
['york', 'york'],
['seguridad', 'security'],
['ayudar', 'help'],
['tuvo', 'He had'],
['largo', 'long'],
['pena', 'pain'],
['probablemente', 'probably'],
['ayer', 'Yesterday'],
['dile', 'tell him'],
['prueba', 'proof'],
['siendo', 'being'],
['bonito', 'beautiful'],
['recuerdas', 'remember'],
['haz', 'make'],
['real', 'real'],
['veras', 'youll see'],
['increíble', 'amazing'],
['quisiera', 'I would like'],
['tonto', 'fool'],
['simplemente', 'simply'],
['vámonos', 'Lets go'],
['haría', 'would do'],
['preguntas', 'questions'],
['aire', 'air'],
['conoce', 'known'],
['fuerza', 'strength'],
['carta', 'letter'],
['trato', 'treatment'],
['plan', 'plan'],
['ése', 'that'],
['verlo', 'see him'],
['hambre', 'hungry'],
['vuelto', 'turned'],
['empezar', 'start'],
['campo', 'countryside'],
['acaba', 'just'],
['hablas', 'speak'],
['vive', 'lives'],
['barco', 'ship'],
['hotel', 'hotel'],
['poner', 'set'],
['grupo', 'group'],
['creí', 'thought'],
['sol', 'Sun'],
['tuyo', 'of yours'],
['pase', 'pass'],
['joe', 'joe'],
['voz', 'voice'],
['baño', 'bathroom'],
['usar', 'use'],
['conseguir', 'get'],
['placer', 'pleasure'],
['llegado', 'arrived'],
['decirte', 'tell you'],
['profesor', 'Teacher'],
['noticias', 'news'],
['lamento', 'lament'],
['decirle', 'tell'],
['blanco', 'White'],
['quédate', 'stay'],
['estuve', 'I was'],
['pie', 'foot'],
['anda', 'anda'],
['espere', 'Wait'],
['edad', 'age'],
['secreto', 'secret'],
['podríamos', 'we could'],
['compañía', 'company'],
['tren', 'train'],
['recuerda', 'remember'],
['tras', 'after'],
['siéntate', 'Sit down'],
['prisa', 'rush'],
['vista', 'view'],
['hermosa', 'beautiful'],
['negocio', 'deal'],
['deberíamos', 'we should'],
['gustan', 'like'],
['pagar', 'pay'],
['george', 'george'],
['futuro', 'future'],
['silencio', 'silence'],
['siente', 'feels'],
['médico', 'doctor'],
['maestro', 'teacher'],
['quiera', 'want'],
['llegó', 'I arrive'],
['loca', 'crazy'],
['cambiar', 'change'],
['frank', 'frank'],
['sal', 'Salt'],
['control', 'control'],
['raro', 'rare'],
['viste', 'dresses'],
['novia', 'girlfriend'],
['diferente', 'different'],
['imposible', 'impossible'],
['i', 'i'],
['amiga', 'friend'],
['enseguida', 'right away'],
['llamada', 'call'],
['dan', 'give'],
['dejó', 'left'],
['mes', 'month'],
['llevo', 'I wear'],
['avión', 'plane'],
['pelo', 'hair'],
['the', 'the'],
['error', 'error'],
['haremos', 'will'],
['tendrá', 'will have'],
['propia', 'own'],
['siguiente', 'following'],
['ganar', 'win'],
['ley', 'law'],
['dolor', 'pain'],
['oro', 'gold'],
['ten', 'ten'],
['acabó', 'finished'],
['maldición', 'damn'],
['oficial', 'official'],
['situación', 'situation'],
['daño', 'hurt'],
['sientes', 'you feel'],
['entendido', 'it is understood'],
['deseo', 'wish'],
['mente', 'mind'],
['ejército', 'army'],
['comprar', 'to buy'],
['muertos', 'dead'],
['pensaba', 'thought'],
['darle', 'give him'],
['estúpido', 'stupid'],
['decía', 'He said'],
['acabo', 'finished'],
['david', 'David'],
['suena', 'it sounds'],
['mitad', 'half'],
['caballo', 'horse'],
['asesino', 'assassin'],
['vio', 'he saw'],
['permiso', 'Excuse me'],
['ellas', 'they'],
['trabajando', 'working'],
['maravilloso', 'wonderful'],
['mesa', 'table'],
['divertido', 'funny'],
['mejores', 'top'],
['próxima', 'next'],
['entra', 'enters'],
['tom', 'tom'],
['mar', 'sea'],
['siete', 'seven'],
['hacía', 'toward'],
['sexo', 'sex'],
['encanta', 'love'],
['amable', 'nice'],
['mensaje', 'message'],
['información', 'information'],
['traje', 'suit'],
['alma', 'soul'],
['encontrado', 'found'],
['coronel', 'colonel'],
['dale', 'Go ahead'],
['san', 'saint'],
['cena', 'Dinner'],
['encontré', 'I found'],
['charlie', 'charlie'],
['tendrás', 'you will have'],
['eras', 'ages'],
['propio', 'own'],
['culo', 'ass'],
['asi', 'So'],
['adentro', 'indoors'],
['canción', 'song'],
['gobierno', 'government'],
['sam', 'sam'],
['temo', 'fear'],
['abre', 'opens'],
['dijeron', 'they said'],
['fuiste', 'you were'],
['media', 'half'],
['das', 'you give'],
['estábamos', 'we were'],
['estaría', 'It would'],
['daré', 'I will give'],
['vosotros', 'you'],
['frío', 'cold'],
['foto', 'Photo'],
['accidente', 'accident'],
['derecha', 'right'],
['funciona', 'works'],
['vayas', 'go'],
['centro', 'center'],
['necesario', 'necessary'],
['miren', 'look'],
['bonita', 'pretty'],
['ante', 'before'],
['terrible', 'terrible'],
['pude', 'I could'],
['teniente', 'lieutenant'],
['luna', 'Moon'],
['izquierda', 'left'],
['uds', 'You'],
['doy', 'I give'],
['servicio', 'service'],
['llamas', 'calls'],
['normal', 'normal'],
['junto', 'together'],
['tienda', 'store'],
['navidad', 'Christmas'],
['dirección', 'direction'],
['abuela', 'grandmother'],
['alrededor', 'around'],
['vine', 'came'],
['tendré', 'I will have'],
['libertad', 'freedom'],
['sale', 'comes out'],
['línea', 'line'],
['abogado', 'attorney'],
['pies', 'feet'],
['honor', 'honor'],
['tratando', 'trying'],
['regresar', 'to return'],
['hablo', 'I speak'],
['vieja', 'old woman'],
['papel', 'paper'],
['terminado', 'finished'],
['dejado', 'left'],
['juro', 'I swear'],
['hermoso', 'beautiful'],
['dulce', 'candy'],
['sentir', 'feel'],
['principio', 'beginning'],
['interesante', 'interesting'],
['caja', 'box'],
['cualquiera', 'anyone'],
['ocho', 'eight'],
['horrible', 'horrible'],
['respuesta', 'answer'],
['perra', 'female dog'],
['gracioso', 'funny'],
['s', 's'],
['trae', 'brings'],
['personal', 'personal'],
['mató', 'he killed'],
['completamente', 'completely'],
['paul', 'paul'],
['vienen', 'they come'],
['sean', 'are'],
['llega', 'arrives'],
['abuelo', 'grandfather'],
['tengas', 'you have'],
['linda', 'cute'],
['tendremos', 'we will have'],
['michael', 'Michael'],
['partes', 'parts'],
['cárcel', 'jail'],
['hubo', 'there was'],
['sistema', 'system'],
['lindo', 'cute'],
['director', 'director'],
['hazlo', 'do it'],
['hicieron', 'they made'],
['tía', 'aunt'],
['busca', 'search'],
['don', 'Don'],
['baja', 'low'],
['pudo', 'could'],
['salud', 'Health'],
['listos', 'ready'],
['cita', 'appointment'],
['tenías', 'had'],
['negocios', 'business'],
['tipos', 'types'],
['cámara', 'camera'],
['agente', 'agent'],
['verás', 'youll see'],
['infierno', 'hell'],
['regalo', 'present'],
['río', 'River'],
['través', 'through'],
['carne', 'meat'],
['totalmente', 'totally'],
['decirme', 'tell me'],
['piso', 'floor'],
['esposo', 'husband'],
['oír', 'hear'],
['harry', 'harry'],
['sargento', 'sergeant'],
['deje', 'leave'],
['tuya', 'yours'],
['ambos', 'both of them'],
['beber', 'to drink'],
['calma', 'calm'],
['vestido', 'dress'],
['salvo', 'except'],
['ésa', 'that'],
['verdadero', 'TRUE'],
['basura', 'garbage'],
['suelo', 'floor'],
['carrera', 'career'],
['cumpleaños', 'birthday'],
['rato', 'little while'],
['iremos', 'we ll go'],
['universidad', 'college'],
['bailar', 'dance'],
['triste', 'sad'],
['iglesia', 'church'],
['m', 'm'],
['delante', 'in front of'],
['nena', 'baby'],
['banco', 'Bank'],
['cuántos', 'how many'],
['encuentra', 'find'],
['supone', 'supposed'],
['existe', 'exists'],
['programa', 'Program'],
['alegro', 'glad'],
['santo', 'holy'],
['porqué', 'why'],
['novio', 'boyfriend'],
['broma', 'joke'],
['diría', 'would say'],
['salió', 'he left'],
['jesús', 'Jesus'],
['prometo', 'I promise'],
['partido', 'match'],
['pregunto', 'I ask'],
['radio', 'radio'],
['vuelva', 'return'],
['cenar', 'dinner'],
['ocurrió', 'occurred'],
['creía', 'thought'],
['corre', 'run'],
['disculpa', 'excuse'],
['vienes', 'you come'],
['cerveza', 'beer'],
['muerta', 'dead'],
['pensado', 'thought-out'],
['destino', 'destination'],
['bob', 'bob'],
['matrimonio', 'marriage'],
['fotos', 'Photos'],
['diablo', 'Devil'],
['volveré', 'I will be back'],
['saberlo', 'I know'],
['cielos', 'Heavens'],
['norte', 'north'],
['sala', 'room'],
['órdenes', 'orders'],
['según', 'according'],
['harás', 'you will do'],
['ataque', 'attack'],
['parís', 'Paris'],
['ejemplo', 'example'],
['sorpresa', 'surprise'],
['té', 'tea'],
['pudiera', 'could'],
['baile', 'dance'],
['club', 'club'],
['temprano', 'early'],
['público', 'public'],
['tí', 'you'],
['oí', 'heard'],
['mirando', 'looking'],
['ventana', 'window'],
['conocido', 'known'],
['duda', 'doubt'],
['boda', 'wedding'],
['peligro', 'danger'],
['trabaja', 'working'],
['quise', 'I wanted'],
['querías', 'wanted'],
['caliente', 'hot'],
['escribir', 'to write'],
['reina', 'Queen'],
['esperaba', 'I expected'],
['embargo', 'embargo'],
['sur', 'south'],
['enfermo', 'sick'],
['excelente', 'Excellent'],
['pone', 'places'],
['estés', 're'],
['escena', 'scene'],
['encuentro', 'meeting'],
['asesinato', 'murder'],
['mike', 'mike'],
['obra', 'work'],
['n', 'n'],
['veré', 'I will see'],
['llamó', 'I call'],
['aquel', 'that'],
['terminar', 'finish'],
['ganas', 'forward'],
['conocer', 'know'],
['pruebas', 'tests'],
['señores', 'Sirs'],
['vos', 'you'],
['escúchame', 'listen to me'],
['veamos', 'lets see'],
['creen', 'believe'],
['aun', 'yet'],
['ninguno', 'none'],
['parecía', 'looked like'],
['mary', 'mary'],
['viva', 'live'],
['apenas', 'barely'],
['segunda', 'second'],
['bill', 'bill'],
['llave', 'key'],
['regreso', 'Return'],
['trasero', 'rear'],
['ojalá', 'hopefully'],
['veremos', 'we will see'],
['simple', 'simple'],
['seré', 'I will be'],
['éi', 'Ei'],
['irse', 'leave'],
['cartas', 'letters'],
['l', 'l'],
['libros', 'books'],
['apuesto', 'handsome'],
['leer', 'read'],
['imbécil', 'fool'],
['opinión', 'opinion'],
['joder', 'fuck'],
['cambiado', 'changed'],
['sucedió', 'it happened'],
['señal', 'signal'],
['habían', 'they had'],
['agradable', 'nice'],
['cocina', 'kitchen'],
['relación', 'relationship'],
['sueños', 'dreams'],
['segundos', 'seconds'],
['corte', 'cut'],
['escuchar', 'hear'],
['cerebro', 'brain'],
['locura', 'madness'],
['peligroso', 'dangerous'],
['hermanos', 'siblings'],
['entender', 'understand'],
['cine', 'movie theater'],
['dejes', 'leave'],
['reunión', 'meeting'],
['tendría', 'would have'],
['verla', 'see it'],
['duele', 'it hurt'],
['hicimos', 'we did'],
['londres', 'London'],
['tocar', 'play'],
['mirar', 'look at'],
['verme', 'see me'],
['ben', 'ben'],
['suyo', 'yours'],
['causa', 'cause'],
['pelea', 'Fight'],
['prisión', 'prison'],
['jim', 'jim'],
['mayoría', 'most'],
['fondo', 'background'],
['acaso', 'perhaps'],
['vuelvo', 'I come back'],
['serán', 'will be'],
['montón', 'heap'],
['toca', 'plays'],
['comandante', 'commander'],
['tome', 'take'],
['éxito', 'success'],
['misión', 'mission'],
['vidas', 'lifes'],
['decisión', 'decision'],
['hogar', 'home'],
['rico', 'rich'],
['trago', 'drink'],
['capaz', 'able'],
['cargo', 'position'],
['unidos', 'United'],
['lleno', 'full'],
['bar', 'Pub'],
['estrella', 'star'],
['posición', 'position'],
['estación', 'station'],
['interesa', 'interested'],
['uh', 'uh'],
['edificio', 'building'],
['vayan', 'go'],
['consejo', 'advice'],
['pistola', 'gun'],
['humano', 'human'],
['irnos', 'leave'],
['fantástico', 'fantastic'],
['ojo', 'eye'],
['jóvenes', 'young boys'],
['zapatos', 'shoes'],
['majestad', 'majesty'],
['lee', 'read'],
['flores', 'flowers'],
['ocupado', 'occupied'],
['bienvenido', 'welcome'],
['zona', 'zone'],
['contacto', 'Contact'],
['henry', 'Henry'],
['sacar', 'take'],
['podrían', 'could'],
['jimmy', 'jimmy'],
['tema', 'theme'],
['matado', 'killed'],
['soldado', 'soldier'],
['sabías', 'You know'],
['johnny', 'johnny'],
['pido', 'I ask'],
['cierra', 'closes'],
['peter', 'peter'],
['intento', 'tried'],
['irá', 'go to'],
['calor', 'hot'],
['finalmente', 'Finally'],
['equivocado', 'wrong'],
['animales', 'animals'],
['departamento', 'Department'],
['enemigo', 'enemy'],
['caballero', 'gentleman'],
['color', 'Colour'],
['necesitan', 'need'],
['empieza', 'starts'],
['soldados', 'soldiers'],
['vea', 'see'],
['entiende', 'understands'],
['valor', 'value'],
['azul', 'blue'],
['miles', 'Thousands'],
['espacio', 'space'],
['estarás', 'you will'],
['mantener', 'keep'],
['aprender', 'to learn'],
['inteligente', 'intelligent'],
['serás', 'you will'],
['arte', 'art'],
['respeto', 'respect'],
['pedir', 'ask'],
['puso', 'put'],
['llaman', 'call'],
['oiga', 'Listen'],
['juez', 'judge'],
['inglés', 'English'],
['precio', 'price'],
['rojo', 'Red'],
['formas', 'shapes'],
['hagan', 'make'],
['verano', 'summer'],
['podido', 'I have'],
['piernas', 'legs'],
['isla', 'island'],
['darme', 'give me'],
['damas', 'ladies'],
['guardia', 'guard'],
['espalda', 'back'],
['c', 'c'],
['vengan', 'come'],
['parar', 'stop'],
['llevas', 'take'],
['banda', 'band'],
['quedarme', 'stay'],
['habéis', 'have'],
['marcha', 'March'],
['luces', 'lights'],
['estuviera', 'was'],
['crimen', 'crime'],
['dejo', 'left'],
['ayudarte', 'help you'],
['esperen', 'expect'],
['teníamos', 'we had'],
['diferencia', 'difference'],
['llamaré', 'I will call'],
['ama', 'love'],
['conocí', 'I met'],
['tiempos', 'time'],
['déjalo', 'leave it alone'],
['debajo', 'under'],
['compañero', 'partner'],
['dejé', 'leave'],
['come', 'eat'],
['déjeme', 'let me'],
['molesta', 'upset'],
['contar', 'tell'],
['dejaré', 'I ll leave'],
['hablamos', 'We speak'],
['cansado', 'tired'],
['ganado', 'won'],
['pareces', 'look'],
['juicio', 'judgment'],
['hablado', 'spoken'],
['estilo', 'style'],
['ayúdame', 'Help me'],
['sepa', 'know'],
['viendo', 'seeing'],
['salida', 'departure'],
['alegra', 'happy'],
['despierta', 'awake'],
['estupendo', 'great'],
['darte', 'to give you'],
['estados', 'state'],
['quedan', 'are'],
['próximo', 'next'],
['nota', 'note'],
['llevó', 'I wear'],
['puedas', 'can'],
['podrá', 'you can'],
['james', 'James'],
['nave', 'ship'],
['base', 'base'],
['tenían', 'They had'],
['sube', 'goes up'],
['vuelo', 'flight'],
['excepto', 'except'],
['golpe', 'knock'],
['d', 'd'],
['viento', 'wind'],
['estaremos', 'we will be'],
['acción', 'action'],
['tonterías', 'silly stuff'],
['respecto', 'respect'],
['desea', 'you want'],
['sigues', 'are you still'],
['debía', 'should'],
['vendrá', 'will come'],
['encontramos', 'we find'],
['beso', 'kiss'],
['cuestión', 'question'],
['volvió', 'went back'],
['reglas', 'rules'],
['ruido', 'noise'],
['acabado', 'finish'],
['salga', 'out'],
['olvidado', 'forgotten'],
['mentira', 'lie'],
['brazo', 'arm'],
['empezó', 'it started'],
['cálmate', 'take it easy'],
['caballos', 'horses'],
['experiencia', 'experience'],
['tranquila', 'quiet'],
['quedar', 'stay'],
['esperanza', 'hope'],
['irte', 'leave'],
['vd', 'you'],
['perros', 'dogs'],
['casado', 'married'],
['llegue', 'I arrived'],
['drogas', 'drugs'],
['pidió', 'he asked'],
['espíritu', 'spirit'],
['vacaciones', 'holidays'],
['copa', 'Cup'],
['investigación', 'investigation'],
['prefiero', 'I prefer'],
['solía', 'used to'],
['llevaré', 'I ll take'],
['menudo', 'often'],
['partir', 'from'],
['visita', 'visit'],
['alta', 'high'],
['abrir', 'open'],
['tony', 'tony'],
['nueve', 'nine'],
['bomba', 'bomb'],
['energía', 'Energy'],
['bolsa', 'bag'],
['hacerte', 'make'],
['santa', 'St.'],
['pan', 'bread'],
['piel', 'skin'],
['usa', 'uses'],
['metros', 'meters'],
['perdona', 'forgives'],
['escrito', 'written'],
['exacto', 'exact'],
['jugando', 'Playing'],
['cuello', 'neck'],
['larga', 'long'],
['escapar', 'escape'],
['salvar', 'save'],
['escuche', 'I listened'],
['perdone', 'forgive'],
['sirve', 'it serves'],
['preocupe', 'worry'],
['especie', 'species'],
['aquella', 'that'],
['verá', 'you will see'],
['brazos', 'arms'],
['llena', 'full'],
['subir', 'rise'],
['blanca', 'white'],
['fe', 'faith'],
['steve', 'steve'],
['modos', 'modes'],
['traído', 'brought'],
['películas', 'films'],
['dama', 'Lady'],
['suya', 'hers'],
['decirlo', 'I say'],
['doble', 'double'],
['inmediatamente', 'immediately'],
['culpable', 'guilty'],
['preocupa', 'worries'],
['tardes', 'afternoons'],
['vengo', 'I come'],
['bosque', 'forest'],
['perdí', 'I missed'],
['max', 'max'],
['volverá', 'To return to'],
['taxi', 'cab'],
['volar', 'fly'],
['debido', 'due'],
['repente', 'suddenly'],
['bromeando', 'joking'],
['ios', 'ios'],
['viejos', 'old'],
['planeta', 'planet'],
['leche', 'milk'],
['nick', 'nick'],
['tanta', 'so much'],
['tuviera', 'had'],
['encantado', 'charmed'],
['cabrón', 'dumbass'],
['correr', 'run'],
['depende', 'It depends'],
['eddie', 'eddie'],
['común', 'common'],
['informe', 'report'],
['billy', 'billy'],
['solamente', 'only'],
['máquina', 'machine'],
['muere', 'go dead'],
['principal', 'principal'],
['ridículo', 'ridiculous'],
['entrada', 'entry'],
['encontró', 'he found'],
['podamos', 'we can'],
['acabar', 'finish'],
['américa', 'America'],
['regresa', 'came back'],
['probar', 'try out'],
['príncipe', 'the prince'],
['mr', 'mr'],
['preparado', 'prepared'],
['pedido', 'order'],
['propósito', 'purpose'],
['dieron', 'they gave'],
['salido', 'stepped out'],
['cliente', 'client'],
['árbol', 'tree'],
['absoluto', 'absolute'],
['dejas', 'you let'],
['quiénes', 'Who'],
['habías', 'had'],
['b', 'b'],
['parecen', 'they look like'],
['belleza', 'beauty'],
['llame', 'I called'],
['intenta', 'try'],
['humanos', 'humans'],
['you', 'you'],
['tratar', 'try'],
['vuestra', 'your'],
['hayas', 'have'],
['princesa', 'Princess'],
['sigo', 'I follow'],
['quedarse', 'stay'],
['oeste', 'West'],
['traer', 'bring'],
['olvídalo', 'forget this'],
['francia', 'France'],
['tuvimos', 'we had'],
['ayudarme', 'help me'],
['deprisa', 'quickly'],
['llaves', 'keys'],
['tiro', 'threw'],
['cerdo', 'pork'],
['gato', 'cat'],
['inglaterra', 'England'],
['vistazo', 'glance'],
['cuántas', 'how many'],
['defensa', 'defending'],
['nuevos', 'new'],
['últimos', 'latest'],
['reloj', 'watch'],
['fuimos', 'we went'],
['batalla', 'battle'],
['hable', 'I talked'],
['caminar', 'walk'],
['hacerle', 'make'],
['vayamos', 'we go'],
['interior', 'inside'],
['bella', 'beautiful'],
['felices', 'happy'],
['intentando', 'trying'],
['apartamento', 'apartment'],
['teatro', 'theater'],
['hacerme', 'me'],
['papi', 'Daddy'],
['ee', 'ee'],
['asuntos', 'issues'],
['confiar', 'trust'],
['hielo', 'ice'],
['detective', 'detective'],
['deberían', 'should'],
['cantar', 'sing'],
['bajar', 'go down'],
['vuestro', 'your'],
['pelear', 'fight'],
['locos', 'locos'],
['paga', 'pay'],
['oyes', 'hear'],
['completo', 'full'],
['lucha', 'fight'],
['fuerzas', 'forces'],
['ideas', 'Ideas'],
['borracho', 'drunk'],
['héroe', 'hero'],
['camión', 'truck'],
['cabo', 'cape'],
['dientes', 'teeth'],
['verde', 'green'],
['despacio', 'slowly'],
['decidido', 'decided'],
['sociedad', 'society'],
['pareja', 'partner'],
['dígame', 'tell me'],
['estuviste', 'you were'],
['nariz', 'nose'],
['vergüenza', 'shame'],
['caer', 'fall out'],
['j', 'j'],
['herido', 'injured'],
['uu', 'uu'],
['cuentas', 'accounts'],
['pista', 'track'],
['siéntese', 'sit down'],
['bebe', 'baby'],
['sonido', 'sound'],
['estrellas', 'stars'],
['sombrero', 'hat'],
['cayó', 'it fell'],
['evitar', 'avoid'],
['pasará', 'it will happen'],
['maría', 'Mary'],
['memoria', 'memory'],
['solos', 'alone'],
['llorar', 'cry'],
['nervioso', 'nervous'],
['lástima', 'pity'],
['haberlo', 'I have'],
['época', 'epoch'],
['naturaleza', 'nature'],
['vender', 'to sell'],
['política', 'politics'],
['levántate', 'Get up'],
['estudio', 'study'],
['brillante', 'sparkly'],
['nivel', 'level'],
['diferentes', 'different'],
['dando', 'giving'],
['hubiese', 'had'],
['permite', 'It allows'],
['justicia', 'Justice'],
['planes', 'plans'],
['gay', 'gay'],
['mírame', 'Look at me'],
['llegamos', 'we arrived'],
['roma', 'Rome'],
['seguramente', 'surely'],
['papa', 'dad'],
['parecer', 'seem'],
['t', 't'],
['terminó', 'finished'],
['pierna', 'leg'],
['quienes', 'Who'],
['ray', 'ray'],
['millón', 'million'],
['enorme', 'huge'],
['charles', 'charles'],
['inocente', 'innocent'],
['mismos', 'same'],
['pantalones', 'pants'],
['ministro', 'Minister'],
['bienvenida', 'welcome'],
['u', 'or'],
['refiero', 'I mean'],
['nombres', 'Names'],
['mando', 'I send'],
['ponte', 'put'],
['preciosa', 'precious'],
['alex', 'alex'],
['quedó', 'it was'],
['podrás', 'you can'],
['pesar', 'to weigh'],
['animal', 'animal'],
['enferma', 'sick'],
['extraña', 'strange'],
['enamorado', 'in love'],
['tv', 'TV'],
['autobús', 'bus'],
['recordar', 'remember'],
['estáis', 'you are'],
['pequeños', 'little ones'],
['luchar', 'to struggle'],
['date', 'date'],
['contrario', 'contrary'],
['tomado', 'taken'],
['sois', 'you are'],
['movimiento', 'movement'],
['estan', 'is it so'],
['sentado', 'seated'],
['gana', 'desire'],
['robert', 'robert'],
['estén', 'are'],
['motivo', 'reason'],
['absolutamente', 'absolutely'],
['dé', 'of'],
['puente', 'bridge'],
['comprendo', 'I understand'],
['huevos', 'eggs'],
['tomó', 'I take'],
['cuento', 'story'],
['botella', 'bottle'],
['cuesta', 'cost'],
['detente', 'stop'],
['corriendo', 'running'],
['confianza', 'trust'],
['felicidad', 'happiness'],
['espada', 'sword'],
['silla', 'chair'],
['bobby', 'bobby'],
['noticia', 'News'],
['casas', 'houses'],
['televisión', 'television'],
['acuerdas', 'remember'],
['necesitaba', 'needed'],
['pared', 'wall'],
['aquellos', 'those'],
['prensa', 'press'],
['trampa', 'trap'],
['presente', 'Present'],
['estarán', 'will be'],
['jardín', 'yard'],
['cabello', 'hair'],
['espectáculo', 'show'],
['podré', 'I will be able'],
['grave', 'serious'],
['bastardo', 'bastard'],
['dará', 'give to'],
['siga', 'follow'],
['periódico', 'Newspaper'],
['coño', 'cone'],
['danny', 'danny'],
['negros', 'black'],
['alguno', 'any'],
['anillo', 'ring'],
['monstruo', 'monster'],
['total', 'total'],
['ai', 'ai'],
['tommy', 'tommy'],
['piedra', 'stone'],
['contento', 'happy'],
['quedarte', 'stay'],
['tengan', 'have'],
['oigan', 'hear'],
['sentí', 'felt'],
['debí', 'should'],
['ahi', 'there'],
['policías', 'police'],
['lugares', 'places'],
['contrato', 'contract'],
['playa', 'Beach'],
['costa', 'coast'],
['puertas', 'doors'],
['asiento', 'seat'],
['tarjeta', 'card'],
['restaurante', 'restaurant'],
['quede', 'stay'],
['paseo', 'walk'],
['hechos', 'acts'],
['hagamos', 'lets do'],
['maravillosa', 'wonderful'],
['pon', 'put'],
['inspector', 'inspector'],
['domingo', 'Sunday'],
['especialmente', 'especially'],
['velocidad', 'speed'],
['negra', 'black'],
['richard', 'richard'],
['intentar', 'try'],
['proyecto', 'draft'],
['clientes', 'customers'],
['victoria', 'victory'],
['encantaría', 'love'],
['operación', 'operation'],
['perdió', 'lost'],
['tonta', 'dumb'],
['imagen', 'image'],
['show', 'Show'],
['lleve', 'I carried'],
['amas', 'love'],
['responsable', 'responsable'],
['gustaba', 'He liked'],
['aspecto', 'appearance'],
['tantos', 'many'],
['sentimientos', 'feelings'],
['creerlo', 'I believe it'],
['objetivo', 'objective'],
['sarah', 'sarah'],
['llevan', 'They carry'],
['malas', 'bad'],
['red', 'net'],
['dejen', 'leave'],
['nuevas', 'news'],
['muchacha', 'girl'],
['dormido', 'asleep'],
['and', 'and'],
['historias', 'stories'],
['arreglar', 'fix'],
['turno', 'turn'],
['yendo', 'going'],
['tuviste', 'You saw'],
['ponga', 'put'],
['olvides', 'forget'],
['escuché', 'I listened'],
['pasada', 'pass'],
['mata', 'Bush'],
['tantas', 'many'],
['montaña', 'Montana'],
['gracia', 'Grace'],
['enfermedad', 'disease'],
['dedos', 'fingers'],
['guapa', 'beautiful'],
['querer', 'want'],
['p', 'p'],
['ocurrido', 'happened'],
['pocos', 'few'],
['deber', 'must'],
['refieres', 'mean'],
['viernes', 'Friday'],
['preocupado', 'worried'],
['clases', 'lessons'],
['rayos', 'Ray'],
['inútil', 'Useless'],
['washington', 'Washington'],
['abierto', 'open'],
['haberte', 'sorry'],
['oscuridad', 'darkness'],
['verdadera', 'real'],
['americano', 'American'],
['trajo', 'brought'],
['gustó', 'taste'],
['primo', 'cousin'],
['nacional', 'national'],
['supe', 'I knew'],
['colegio', 'school'],
['malditos', 'accursed'],
['cuchillo', 'knife'],
['ibas', 'going'],
['llegué', 'I arrived'],
['sir', 'sir'],
['diario', 'diary'],
['francés', 'French'],
['quedo', 'I remain'],
['podremos', 'we will can'],
['orgulloso', 'proud'],
['ladrón', 'thief'],
['martin', 'Martin'],
['preguntar', 'ask'],
['pedí', 'I asked'],
['central', 'central'],
['voluntad', 'Will'],
['harán', 'will'],
['jake', 'jake'],
['www', 'www'],
['militar', 'military'],
['agradezco', 'I appreciate'],
['llevaba', 'He wore'],
['mami', 'Mommy'],
['lluvia', 'rain'],
['éramos', 'we were'],
['natural', 'natural'],
['calles', 'streets'],
['cien', 'one hundred'],
['lengua', 'language'],
['china', 'China'],
['testigo', 'witness'],
['ayude', 'help'],
['quiso', 'He wanted'],
['cansada', 'tired'],
['puse', 'I put'],
['irás', 'you will go'],
['alemanes', 'German'],
['pago', 'payment'],
['mirada', 'look'],
['momentos', 'moments'],
['quieto', 'still'],
['sentía', 'felt'],
['escuchen', 'listen'],
['descansar', 'rest'],
['mercado', 'market'],
['dura', 'hard'],
['humana', 'human'],
['estúpida', 'stupid'],
['humor', 'humor'],
['bienvenidos', 'Welcome'],
['conocía', 'he knew'],
['jane', 'jane'],
['entero', 'whole'],
['roja', 'red'],
['larry', 'larry'],
['llamaba', 'He called'],
['tomas', 'shots'],
['dueño', 'owner'],
['echar', 'throw'],
['emergencia', 'emergency'],
['roto', 'broken'],
['actuar', 'Act'],
['mark', 'mark'],
['inmediato', 'righ now'],
['puntos', 'points'],
['paciente', 'patient'],
['olvidé', 'forgot'],
['hables', 'talk'],
['varios', 'various'],
['polvo', 'dust'],
['ángeles', 'angels'],
['coger', 'take'],
['distancia', 'distance'],
['bravo', 'Bravo'],
['europa', 'Europe'],
['mataron', 'they killed'],
['tomando', 'taking'],
['verle', 'see'],
['señoría', 'lordship'],
['casarse', 'get marry'],
['toque', 'I touched'],
['toques', 'touches'],
['ángel', 'Angel'],
['amante', 'lover'],
['habló', 'I speak'],
['saca', 'pulls out'],
['digamos', 'Lets say'],
['perfecta', 'perfect'],
['rosa', 'rose'],
['llámame', 'Giving me a call'],
['nosotras', 'we'],
['peso', 'weight'],
['carga', 'load'],
['acto', 'act'],
['robar', 'Steal'],
['dejaste', 'you left'],
['desastre', 'disaster'],
['bote', 'boat'],
['huele', 'smells'],
['embarazada', 'pregnant'],
['muestra', 'sample'],
['gordo', 'Fat'],
['puto', 'fucking'],
['sheriff', 'sheriff'],
['viviendo', 'living'],
['anna', 'anna'],
['cerrar', 'to close'],
['papeles', 'papers'],
['valiente', 'brave'],
['gloria', 'glory'],
['aceptar', 'to accept'],
['perdóname', 'excuse me'],
['perfectamente', 'perfectly'],
['oscuro', 'Dark'],
['cuidar', 'look after'],
['dedo', 'finger'],
['ruego', 'I beg'],
['pareció', 'it seemed'],
['tumba', 'tomb'],
['coge', 'picks'],
['resulta', 'result'],
['dejarlo', 'leave'],
['comenzar', 'start'],
['área', 'area'],
['metido', 'I got'],
['limpio', 'cleansed'],
['descanso', 'break'],
['lados', 'sides'],
['posibilidad', 'possibility'],
['jerry', 'jerry'],
['guapo', 'Handsome'],
['uso', 'use'],
['talento', 'talent'],
['matarme', 'kill me'],
['continuar', 'continue'],
['código', 'code'],
['comenzó', 'started'],
['duerme', 'sleeps'],
['r', 'r'],
['definitivamente', 'definitely'],
['dave', 'dave'],
['directo', 'direct'],
['vuelvas', 'return'],
['dia', 'day'],
['demonio', 'demon'],
['parque', 'Park'],
['cambia', 'change'],
['olvidar', 'to forget'],
['cinta', 'headband'],
['famoso', 'famous'],
['mataré', 'I will kill'],
['siguen', 'follow'],
['saliendo', 'coming out'],
['muevas', 'move'],
['señoras', 'ladies'],
['disparar', 'shoot'],
['to', 'to'],
['chris', 'chris'],
['sóio', 'onIy'],
['ja', 'ja'],
['pide', 'requests'],
['debió', 'he must have'],
['empresa', 'company'],
['precioso', 'beautiful'],
['termina', 'ends'],
['intención', 'intention'],
['tambien', 'too'],
['recibir', 'to receive'],
['hubieras', 'had'],
['abrigo', 'coat'],
['encuentras', 'you find'],
['diste', 'you gave'],
['tendrán', 'will'],
['cerrado', 'closed'],
['conocerte', 'meet'],
['hablé', 'I talked'],
['menor', 'less'],
['querría', 'I would want'],
['imagino', 'I imagine'],
['genio', 'genius'],
['profesional', 'professional'],
['oigo', 'hear'],
['pongo', 'I put'],
['niñas', 'girls'],
['muévete', 'move on'],
['opción', 'option'],
['tribunal', 'court'],
['tenéis', 'you have'],
['lago', 'lake'],
['unidad', 'Unit'],
['abierta', 'open'],
['efecto', 'effect'],
['presión', 'Pressure'],
['varias', 'several'],
['robo', 'Stole'],
['saldrá', 'will'],
['veía', 'He looked'],
['quedado', 'left'],
['alcalde', 'mayor'],
['empleo', 'job'],
['pollo', 'chicken'],
['whisky', 'whiskey'],
['california', 'California'],
['carretera', 'highway'],
['sábado', 'Saturday'],
['aeropuerto', 'airport'],
['jodido', 'fucking'],
['pobres', 'poor'],
['medicina', 'medicine'],
['llevará', 'carry'],
['gratis', 'free'],
['cae', 'falls off'],
['fortuna', 'fortune'],
['castillo', 'castle'],
['nieve', 'snow'],
['busco', 'I search'],
['riesgo', 'risk'],
['alemán', 'German'],
['sucio', 'dirty'],
['idiotas', 'idiots'],
['walter', 'walter'],
['conversación', 'conversation'],
['fuese', 'it was'],
['comienzo', 'Start'],
['pasé', 'pass'],
['encontraron', 'They found'],
['elección', 'choice'],
['ey', 'ey'],
['salgan', 'leave'],
['carro', 'car'],
['piensan', 'they think'],
['rostro', 'face'],
['razones', 'reasons'],
['fué', 'it was'],
['propiedad', 'property'],
['mundial', 'world'],
['familiar', 'family'],
['libras', 'pounds'],
['hablemos', 'lets talk'],
['pedazo', 'piece'],
['continúa', 'keep going'],
['cola', 'tail'],
['enemigos', 'enemies'],
['marca', 'brand'],
['líder', 'Leader'],
['hablan', 'speak'],
['durmiendo', 'sleeping'],
['socorro', 'Help'],
['fútbol', 'football'],
['detalles', 'details'],
['hiciera', 'do'],
['recibido', 'received'],
['tesoro', 'treasure'],
['camisa', 'shirt'],
['thomas', 'thomas'],
['comienza', 'begins'],
['conducir', 'drive'],
['andar', 'walk'] ];
